import type { Guide } from "./france-guides";

// Deep-dive landmark pages for Brussels, transcribed from 100region.com:
// p23551 (الميدان الكبير), p23572 (حديقة سينكو نت ناير), p23637 (القصر الملكي),
// p23617 (الأتوميوم), p23664 (حديقة أوروبا المصغرة).
const I = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

export const brusselsLandmarkGuides: Guide[] = [
  {
    slug: "grand-place",
    title_ar: "الميدان الكبير .. ايقونة السياحة في بروكسل",
    title_en: "The Grand Place .. the icon of tourism in Brussels",
    kicker_ar: "معالم بروكسل",
    kicker_en: "Brussels landmarks",
    image: I("2022/09/img_3546.jpg"),
    blocks: [
      {
        type: "P",
        ar: "الساحة الكبرى أو غراند بلاس The Grand Place أو Grote Markt هي الساحة المركزية في مدينة بروكسل ببلجيكا ، وقد اكتسبت أهميتها بسبب المباني المحيطة بها كقاعة المدينة وكنيسة القديس ميخائيل ، تبلغ أبعادها 68 متر عرضا و110 متر طولا ، وتعتبر اليوم الوجهة السياحية الأكثر أهمية في المدينة ، والأكثر احتواء على المعالم السياحية المتميزة ، حيث دار العمدية ومتاجر الشوكولاتة وتمثال الطفل مانيكن بيس ، وكالعادة التقليد السنوى توضع شجرة عيد ميلاد ضخمة في الساحة ، كما توجد سجادة زهور شهيرة فيها ، وقد تم ادراج الساحة على قائمة التراث العالمي لليونسكو عام 1998",
        en: "The Grand Place, or Grote Markt, is the central square of the city of Brussels in Belgium. It gained its importance from the buildings surrounding it, such as the town hall and the church of Saint Michael. It measures 68 metres wide and 110 metres long, and is today the most important tourist destination in the city and the one richest in distinguished landmarks — the town hall, the chocolate shops and the statue of the little boy Manneken Pis. As is the annual tradition, a huge Christmas tree is placed in the square, and there is also a famous carpet of flowers. The square was inscribed on the UNESCO World Heritage list in 1998.",
      },
      { type: "IMG", src: I("2022/09/img_3547.jpg"), cap_ar: "الميدان الكبير ببروكسل", cap_en: "The Grand Place in Brussels" },
      {
        type: "P",
        ar: "تضم ساحة الغراند بلاس في بروكسل مجموعة متجانسة على نحو رائع من المباني العامة والخاصة التي ترقى بشكل رئيس الى أواخر القرن السابع عشر ، وتتميز بهندستها المعمارية التي تختصر وتجسد بشكل حيوي النوعية الاجتماعية والثقافية الخاصة بهذا المركز السياسي والتجاري المهم",
        en: "The Grand Place in Brussels holds a wonderfully homogeneous group of public and private buildings dating mainly from the late seventeenth century, distinguished by an architecture that vividly sums up and embodies the social and cultural quality of this important political and commercial centre.",
      },
      { type: "IMG", src: I("2022/09/img_3548.jpg"), cap_ar: "الميدان الكبير ببروكسل", cap_en: "The Grand Place in Brussels" },
      { type: "IMG", src: I("2022/09/img_3555.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      { type: "IMG", src: I("2022/09/img_3556.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      { type: "IMG", src: I("2022/09/img_3557.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      {
        type: "H3",
        noNumber: true,
        ar: "افضل الانشطة التي يمكن القيام بها في الميدان الكبير ببروكسل",
        en: "The best activities to do in the Grand Place in Brussels",
      },
      {
        type: "P",
        ar: "سوف تحلو لك زيارة هذه الميدان عندما تستهل نهارك بجولة استكشافية لأنحاء المكان ، وتطلع أثنائها على أهم معالم الميدان وتستمتع برؤية الحياة والحيوية التي تدب من حولك ، وسوف تستمتع أيضا باستكشاف بعض الفنون المعمارية القديمة المنعكسة على الأبنية التاريخية في الميدان ، كما أن الميدان يتزين بأسراب من الطيور الجميلة ، وان وجدت ما يحيط بك يستحق التأمل أكثر ، فامنح نفسك وقتا كافيا للاستمتاع بذلك من خلال الاستراحة على أحد المواضع المخصصة للجلوس في الميدان",
        en: "You will enjoy visiting this square when you begin your day with an exploratory walk around the place, taking in its most important landmarks and enjoying the life and vitality stirring around you. You will also enjoy discovering some of the old architectural art reflected in the historic buildings of the square, which is likewise adorned with flocks of beautiful birds. And if you find what surrounds you deserves longer contemplation, give yourself enough time to enjoy it by resting in one of the seating areas of the square.",
      },
      {
        type: "P",
        ar: "ومع وجود بعض المتاجر المتوزعة في هذا الميدان ، سوف تستمتع بالتنزه فيها ورؤية ما تعرضه من منتجات متنوعة وربما أردت ابتياع ما يلزمك منها",
        en: "With a number of shops spread around the square, you will enjoy strolling through them and seeing the varied products they display — and you may want to buy whatever you need from them.",
      },
      {
        type: "P",
        ar: "وكي تحصل على متعة أكبر ، اوصي بزيارة هذا الميدان أثناء موسم رأس السنة ، حيث يتحول المكان الى ساحة تمتلئ بأسواق عيد الميلاد الرائعة وتتزين بالأشجار والأنوار الجذابة",
        en: "For even greater enjoyment, I recommend visiting the square during the New Year season, when the place turns into a square filled with wonderful Christmas markets and adorned with trees and attractive lights.",
      },
      {
        type: "P",
        ar: "تابع جولتك الممتعة في الميدان ، فبوسعك الاستمتاع بمشاهدة بعض العروض الفنية المميزة التي يتنافس في تقديمها بعض الهواة ، فهناك عروض موسيقية حية يقدمها بعض الهواة",
        en: "Continue your pleasant tour of the square, where you can enjoy watching distinctive artistic performances that amateurs compete to present, including live music offered by amateur performers.",
      },
      {
        type: "P",
        ar: "ولا سبيل لتفويت الفرصة الفريدة التي تتاح في الميدان خلال فصل الشتاء وهي التزلج وذلك عبر حلبة التزلج الموجودة في الميدان والتي يتزاحم عليها العديد من الزوار",
        en: "And there is no way to miss the unique opportunity available in the square during winter — skating on the rink set up in the square, which many visitors crowd onto.",
      },
      {
        type: "P",
        ar: "يعتبر الميدان مقراً لإقامة بعض الفعاليات المختلفة، وستكون محظوظاً إذا تزامن وقت نُزهتك في الميدان مع إحدى هذه الفعاليات أو الاحتفالات الوطنية التي تُقام فيه في أوقات متنوّعة خلال السنة.",
        en: "The square is a venue for various events, and you will be lucky if the time of your outing coincides with one of these events or the national celebrations held there at different times throughout the year.",
      },
      { type: "IMG", src: I("2022/09/img_3550.jpg"), cap_ar: "السجارة التي يشتهر بها الميدان الكبير ببروكسل", cap_en: "The carpet the Grand Place in Brussels is famous for" },
      {
        type: "P",
        ar: "لذا ومما تقدم ذكره فانك وفي حال كنت تبحث عن وجهة سياحية مثالية ، فان السياحة في بروكسل هي الخيار الأمثل لك ، فهي مدينة تتميز بالعديد من ميادين بروكسل والتي تختلف لترضي شتى الأذواق ومن أبرزها الميدان الكبير ببروكسل الذي يعود الى القرن السابع عشر",
        en: "So, from all that has been mentioned, if you are looking for an ideal tourist destination, tourism in Brussels is the perfect choice for you: it is a city distinguished by its many squares, which differ so as to satisfy every taste, the most prominent of them being the Grand Place, which goes back to the seventeenth century.",
      },
      {
        type: "P",
        ar: "سمي الميدان بالميدان الكبير لأنه المركز الجغرافي ، وما يرسخ أهمية هذه الميدان ، أنه نقطة تربط بين عدد من الشوارع الرئيسية في المدينة ، والتي بامكانك أيضا التجول فيها مثل بيوري وتشارلز بولز بالاضافة الى المصليات",
        en: "The square was called the Grand Place because it is the geographical centre, and what reinforces its importance is that it is a point connecting a number of the city's main streets, which you can also wander through, such as Beurre and Charles Buls, in addition to the chapels.",
      },
      { type: "IMG", src: I("2022/09/img_3558.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      { type: "IMG", src: I("2022/09/img_3559.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      { type: "IMG", src: I("2022/09/img_3560.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      { type: "IMG", src: I("2022/09/img_3561.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      {
        type: "P",
        ar: "ان الميدان الكبير في بروكسل هو أجمل ساحة في العالم اليوم ، وفقا لفيكتور هوغو ، وقد نشأت ساحة السوق في القرن الحادي عشر في موقع المستنقعات الجافة ، في أوائل العصور الوسطى ، فكانت المنازل الخشبية الصغيرة منتشرة في جميع أنحاء المنطقة ، ولكن منذ القرن الرابع عشر ، تم استبدالها بمباني حجرية تدريجيا ، ليتحول السوق الى المركز التجاري والاداري الرئيسي للمدينة",
        en: "The Grand Place in Brussels is the most beautiful square in the world today, according to Victor Hugo. The market square arose in the eleventh century on the site of dried-out marshes. In the early Middle Ages small wooden houses were scattered all over the area, but from the fourteenth century they were gradually replaced by stone buildings, turning the market into the main commercial and administrative centre of the city.",
      },
      {
        type: "P",
        ar: "ونظرا للأهمية المتزايدة للمدينة ، قررت سلطات المدينة هدم بعض المنازل الخشبية ، وبناء دار بلدية جديدة بدلا منها ، والتي من شأنها تلبية احتياجات المدينة في مركز اداري كبير ، لذلك في عام 1402 بدأ بناء مبنى البلدية ، والذي لا يزال حتى يومنا هذا هو المهيمن على الساحة ، وتم بناء الجناح الأيسر الأطول للمبنى في 1402-1422 من قبل المهندس المعماري جاكوب فان تينين لتوسيع البرج الحالي ، في وقت لاحق تقرر توسيع دار البلدية مرة أخرى في 1444-1448 ، أكمل مهندس معماري مجهول الجناح الأيمن ، والذي كان أقصر من الأول ، وكان ذلك بسبب حقيقة أن محيط الساحة قد تشكل في ذلك الوقت وأن المباني المجاورة لم تسمح للجانب الأيمن أن يكون متماثلا مع اليسار ، في عام 1449-1455 ، تم بناء برج جديد بطول 96 مترا في موقع البرج القديم ، صممه المهندس المعماري جان فان رويسبروك ، يتوج البرج بتمثال مذهب لرئيس الملائكة ميخائيل ، قاتل الشيطان شفيع بروكسل",
        en: "Given the growing importance of the city, the city authorities decided to demolish some of the wooden houses and build a new town hall in their place, one that would meet the city's need for a large administrative centre. So in 1402 construction of the town hall began, and to this day it still dominates the square. The longer left wing of the building was built in 1402–1422 by the architect Jacob van Thienen to extend the existing tower. Later it was decided to expand the town hall again in 1444–1448, when an unknown architect completed the right wing, which was shorter than the first — this was because the perimeter of the square had already taken shape by then and the neighbouring buildings did not allow the right side to be symmetrical with the left. In 1449–1455 a new tower 96 metres tall was built on the site of the old one, designed by the architect Jan van Ruysbroeck. The tower is crowned by a gilded statue of the archangel Michael, slayer of the devil and patron of Brussels.",
      },
      {
        type: "P",
        ar: "بالنظر الى قاعة المدينة ، لا يسع المرء الا أن يلاحظ عدم التناسق في المباني ، وكانت هناك أسطورة في بروكسل مفادها أن المهندس المعماري قد انتحر برمي نفسه من البرج عندما لاحظ أن البرج لم يكن في المنتصف ، يقع مقابل البرج مبنى Bread House (أو بيت الملك) على الطراز القوطي الجديد",
        en: "Looking at the town hall, one cannot help noticing the asymmetry of the buildings, and there was a legend in Brussels that the architect committed suicide by throwing himself from the tower when he noticed it was not in the middle. Opposite the tower stands the Bread House (or King's House) in the neo-Gothic style.",
      },
      {
        type: "P",
        ar: "تم تحديد وجود اسمين مختلفين جدا لمبنى واحد من خلال التاريخ ، في القرن الثالث عشر كان هناك مبنى خشبي في هذا الموقع ، والذي كان يستخدمه الخبازون كمكان لتجارة الخبز ، ومن هنا جاء Nidelades Broodhuis بيت الخبز ، ففي بداية القرن الخامس عشر كان الخبازون أقل استخداما للمبنى ، ولكن تم استخدامه أكثر فأكثر للأغراض الادارية لدوق برابانت ، ومن هنا جاء الاسم الفرنسي Maison du Roi منزل الملك",
        en: "The existence of two very different names for one building was determined by history. In the thirteenth century there was a wooden building on this site used by the bakers as a place to trade bread — hence the Dutch Broodhuis, the Bread House. At the beginning of the fifteenth century the bakers used the building less, while it was used more and more for the administrative purposes of the Duke of Brabant — hence the French name Maison du Roi, the King's House.",
      },
      { type: "IMG", src: I("2022/09/img_3554.jpg"), cap_ar: "صور من الميدان الكبير ببروكسل", cap_en: "Views of the Grand Place in Brussels" },
      {
        type: "P",
        ar: "في عهد الامبراطور تشارلز الخامس ، تم بناء مبنى حجري على الطراز القوطي (1515-1536) ، وفي السنوات اللاحقة كان المبنى يضم البلاط الملكي وحتى سجنا ، هنا قضى كونتات اغموند ودي أورني ليلتهما الأخيرة قبل اعدامهما في Grand Place في 5 يونيو 1568 ، بعد قصف الجيش الفرنسي عام 1695 ، دمر بيت الخبز جزئيا ، وفي عام 1868 وبموجب مرسوم من رئيس البلدية جول أنسباخ ، اشترت سلطات المدينة هذا المنزل ، الذي كان في ذلك الوقت في حالة يرثى لها ، أعيد بناء المبنى بالكامل من الصفر على الطراز القوطي الجديد من قبل المهندس المعماري فيكتور يامار (1873) ، وأصبح بيت الخبز في 2 يونيو 1887 متحفا في مدينة بروكسل",
        en: "In the reign of Emperor Charles V a stone building was erected in the Gothic style (1515–1536), and in later years the building housed the royal court and even a prison. Here the counts of Egmont and of Horn spent their last night before their execution in the Grand Place on 5 June 1568. After the bombardment by the French army in 1695 the Bread House was partly destroyed, and in 1868, by decree of mayor Jules Anspach, the city authorities bought this house, which was at that time in a lamentable state. The building was completely rebuilt from scratch in the neo-Gothic style by the architect Victor Jamaer (1873), and on 2 June 1887 the Bread House became a museum of the city of Brussels.",
      },
      {
        type: "P",
        ar: "ومع ذلك فإن روعة وجمال Grand Place لا يتم انشاؤهما فقط من خلال دار البلدية وKing’s House ، ولكن ربما قبل كل شيء ، من خلال الجمال المذهل لمنزل النقابة ، وعلى الرغم من أن جميع المنازل الموجودة في الميدان تسمى عادة بيوت النقابات ، الا أن بعضها لم ينتمي أبدا الى نقابات الحرفيين بل كانت مملوكة ملكية خاصة",
        en: "However, the splendour and beauty of the Grand Place are created not only by the town hall and the King's House, but perhaps above all by the astonishing beauty of the guild houses — and although all the houses on the square are usually called guild houses, some of them never belonged to craftsmen's guilds but were privately owned.",
      },
      {
        type: "P",
        ar: "في العصور الوسطى وما بعدها ، كان هناك العديد من النقابات في كل مدينة كجمعيات الحرفيين ، سعت النقابات الثرية والقوية سياسيا الى اظهار قيمتها في ديكور المنازل حيث التقوا بانتظام لمناقشة القواعد واللوائح الجديدة لتجارة بضاعتهم ، في بروكسل قامت النقابات بالطبع ببناء منازلها التمثيلية حول Grand Place ، بعد تدمير شبه كامل في أغسطس 1695 ، أمرت سلطات المدينة النقابات بتقديم خطط لاعادة بناء المنازل للحصول على الموافقة النهائية ، وهكذا تم الحفاظ على الوحدة الأسلوبية للمربع",
        en: "In the Middle Ages and afterwards there were many guilds in every city as associations of craftsmen. The wealthy and politically powerful guilds sought to display their worth in the decoration of the houses where they met regularly to discuss the new rules and regulations of their trade. In Brussels the guilds naturally built their representative houses around the Grand Place. After the almost complete destruction of August 1695 the city authorities ordered the guilds to submit plans for rebuilding the houses for final approval, and thus the stylistic unity of the square was preserved.",
      },
      {
        type: "P",
        ar: "يعد Grand Place ، أو Grote Markt ، مركزا تاريخيا وسياحيا مهما في بروكسل ، حيث توجد City Hall وKing’s House ، وتعتبر مجموعة ساحة السوق ، التي تم بناؤها على طراز لويس الرابع عشر والطراز الباروكي ، أحد مواقع التراث العالمي لليونسكو",
        en: "The Grand Place, or Grote Markt, is an important historical and touristic centre of Brussels, home to the City Hall and the King's House, and the ensemble of the market square, built in the style of Louis XIV and the Baroque, is one of the UNESCO World Heritage sites.",
      },
      {
        type: "P",
        ar: "الميدان الكبير هو الساحة المركزية الأكثر روعة وأناقة ، وتحيط به ساحة من التحف المعمارية المختارة بعناية والتي تنتمي الى نقابات التجار والحرفيين House of the Painter ، وHouse of the Tailor ، وHouse of the Boatman ، الأكثر اثارة للاعجاب هي King’s House وCity Hall ، أقيمت قاعة المدينة عام 1402 ، وتم تزيين برجها المرتفع بقطعة نحاسية طولها خمسة أمتار على شكل رئيس الملائكة ميخائيل ، وتماثيل الواجهة تصور قصصا مختلفة من حياة المدينة",
        en: "The Grand Place is the most magnificent and elegant central square, ringed by carefully chosen architectural masterpieces belonging to the guilds of merchants and craftsmen — the House of the Painter, the House of the Tailor and the House of the Boatman. The most impressive are the King's House and the City Hall. The town hall was erected in 1402, and its lofty tower was crowned with a five-metre bronze figure of the archangel Michael, while the statues of the façade depict different stories from the life of the city.",
      },
      {
        type: "P",
        ar: "يضم بيت الملك الضخم اليوم المتحف الكوميوني الذي يحكي قصة انشاء بروكسل ، على الرغم من اسمه ، لم يكن هذا المبنى مسكنا لملك واحد ، نشأت العمارة الحجرية المزركشة في King’s House في موقع Bread House السابق حيث كان في القرن الثالث عشر خبز مخبوز ومباع",
        en: "The imposing King's House today holds the communal museum, which tells the story of the founding of Brussels. Despite its name, this building was never the residence of a single king. The ornate stone architecture of the King's House arose on the site of the former Bread House, where in the thirteenth century bread was baked and sold.",
      },
      {
        type: "P",
        ar: "مرتين في السنة ، يتم انشاء سجادة ضخمة مستطيلة من الزهور في الساحة التي تزين Grand Place لمدة ثلاثة أيام ، تزرع بيجونيا متعددة الألوان بشكل خاص بالقرب من غنت لهذه المناسبة ، حيث يمكنك الاستمتاع بهذا المشهد الفخم وجمال المجموعة المعمارية بينما تجلس بشكل مريح في أحد المقاهي في الساحة ، هناك سترى أيضا حانة Golden Barkas الشهيرة ، حيث عاش فيكتور هوغو ، بالاضافة الى مطعم House of the Swan ، الذي تم تزيين مدخله بنحت بجعة ،كان هذا المطعم هو المكان الذي توجد فيه الحانة التي قرأ فيها ماركس وانجلز لأول مرة بيان الحزب الشيوعي",
        en: "Twice a year a huge rectangular carpet of flowers is created in the square, adorning the Grand Place for three days; multicoloured begonias are grown especially near Ghent for the occasion. You can enjoy this magnificent sight and the beauty of the architectural ensemble while sitting comfortably in one of the cafés on the square. There you will also see the famous Golden Barge tavern where Victor Hugo lived, as well as the House of the Swan restaurant, whose entrance is decorated with a carved swan — this restaurant was the place that held the tavern where Marx and Engels first read the manifesto of the Communist party.",
      },
      {
        type: "P",
        ar: "يستحق Grand Place ذو الموقع المركزي لقب أجمل ساحة في أوروبا وأكثرها أناقة ، هذا صحيح ليس فقط لأن القسم بأكمله مخصص تماما لمناظره ، كما قال نابليون عندما جاء لأول مرة الى وسط الميدان الكبير ، حتى اليوم يتفق المسافرون الذين شاهدوا الكثير على أن المباني التي تحيط بالساحة من جميع الجوانب في مربع متساو ، كما لو كانت منحوتة من الحجر على يد أمهر الحرفيين ، أدرجت اليونسكو بدورها مجموعة Grand Place والواجهات المفتوحة في قائمة التراث الثقافي العالمي",
        en: "The centrally located Grand Place deserves the title of the most beautiful and most elegant square in Europe. This is true not only because the whole section is devoted entirely to its views, as Napoleon said when he first came to the middle of the Grand Place; even today travellers who have seen a great deal agree that the buildings which surround the square on all sides in an equal square look as though they were carved out of stone by the most skilful craftsmen. UNESCO in turn inscribed the Grand Place ensemble and its open façades on the list of world cultural heritage.",
      },
      {
        type: "P",
        ar: "الأسطورة حول أصل Grand Place هي كما يلي ، ذات مرة سئم الملك لويس الرابع عشر من القصص عن جمال وروعة بروكسل ، قرر زيارة هذه المدينة شخصيا ، تخيل دهشته عندما اكتشف أن بروكسل هي بالفعل أجمل منها بكثير ، في نوبة غضب أمر الملك بتدمير المدينة والقاؤها بالألغام الأرضية المحترقة ، لكن البلجيكيين شعب عنيد التجار والحرفيون الأغنياء لم يدخروا أي نفقات وأعادوا بناء ساحة مركزية جديدة أكثر جمالا",
        en: "The legend about the origin of the Grand Place goes as follows. Once King Louis XIV grew weary of the stories about the beauty and splendour of Brussels and decided to visit the city in person. Imagine his astonishment when he discovered that Brussels was indeed far more beautiful than the tales. In a fit of rage the king ordered the city destroyed and struck with burning mines — but the Belgians are a stubborn people, and the rich merchants and craftsmen spared no expense and rebuilt a new central square that was even more beautiful.",
      },
      {
        type: "P",
        ar: "وبالتالي ، فإن Grand Place هي الساحة الوحيدة من العصور الوسطى في أوروبا ، والتي تم التفكير في تصميمها المعماري بعناية ، والعنصران اللذان يشكلان Grand Place في بروكسل هما Gothic Town Hall والبيت الملكي الذي أعيد بناؤه حديثا من 1873 الى 1896 ، بدون استثناء ظهرت جميع المنازل التابعة للنقابات المختلفة بعد عام 1695 ، ومهما كانت ضيقة ، لم يتخلى المهندس المعماري عن الديكور الباروكي الرائع ، على الجانب الشرقي من Grand Place يوجد ما يسمى House of the Dukes of Brabant ستة بيوت نقابة مخفية خلف واجهتها ، يوجد على اليسار نفس البيت الملكي ، الذي بني بروح التاريخية ومصمم على الطراز القوطي الفراندي البحت",
        en: "Thus the Grand Place is the only medieval square in Europe whose architectural design was carefully thought out. The two elements that make up the Grand Place in Brussels are the Gothic Town Hall and the King's House, rebuilt anew from 1873 to 1896. Without exception all the houses of the various guilds appeared after 1695, and however narrow they were, the architect did not give up the splendid Baroque decoration. On the eastern side of the Grand Place stands the so-called House of the Dukes of Brabant, with six guild houses hidden behind its façade; on the left is the same King's House, built in the spirit of historicism and designed in the purely Flemish Gothic style.",
      },
      { type: "IMG", src: I("2022/09/img_3553.jpg"), cap_ar: "الميدان الكبير ببروكسل", cap_en: "The Grand Place in Brussels" },
      {
        type: "H3",
        noNumber: true,
        ar: "المزيد من المعرفة عن الميدان الكبير ببروكسل",
        en: "More to know about the Grand Place in Brussels",
      },
      {
        type: "P",
        ar: "في العصور الوسطى ، لم تكن المنازل مرقمة ، لكن كانت تحمل أسماء ، تم تحديد أسماء المنازل ببعض التماثيل الصغيرة أو جزء من زخرفة الواجهة ، بالطبع بعد عدة قرون ليس من الممكن دائما العثور على التفاصيل التي أعطت اسم المنزل",
        en: "In the Middle Ages the houses were not numbered but bore names, and the names of the houses were identified by some small statue or a part of the decoration of the façade. Of course, after several centuries it is not always possible to find the detail that gave the house its name.",
      },
      {
        type: "LIST",
        ar: [
          "المنازل الموجودة على يسار مبنى البلدية (مرقمة من اليمين الى اليسار) ، فرقم 1 ملك اسبانيا .. المنزل ينتمي الى نقابة الخبازين ، يوجد فوق الباب تمثال نصفي للقديس أوبير ، شفيع الخبازين ، وحتى أعلى تمثال نصفي لتشارلز الثاني ملك اسبانيا",
          "رقم 2-3 عربة .. كان المنزل ملكا لنقابة منتجي الدهون والزيوت ، ولاحقا لتجار شموع الشحم ، مزينة بتمثال القديس جيل شفيع هذه النقابة",
          "رقم 4 حقيبة .. كان المنزل ملكا لنقابة صانعي الخزائن والخزائن",
          "رقم 5 هي الذئب .. كان المنزل ملكا لنقابة الرماة ، تتوج الواجهة بشكل طائر الفينيق وهو يرتفع من الرماد والنيران ويرمز الى اعادة بناء المدينة بعد قصف القوات الفرنسية عام 1695 ، وتم تزيين المنزل بنقوش تصور رومولوس وريموس تغذيها ذئب ، ومن هنا جاء الاسم",
          "رقم 6 البوق أو القرن .. ينتمي المنزل الى نقابة الملاحين ، وبالتالي فان أصل المنزل مصنوع على شكل مؤخرة السفينة",
          "رقم 7 فوكس .. المنزل ينتمي الى نقابة الخردوات ، النقوش فوق الطابق الثاني تصور رموز القارات الأربع ، في السابق توج المنزل بتمثال القديس نيكولاس شفيع النقابة",
          "المنازل على يمين مبنى البلدية (مرقمة من اليمين الى اليسار) فرقم 8 ستار .. بيت عمان في عام 1852 تم هدم المنزل ، وفي عام 1897 بمبادرة من رئيس البلدية تشارلز بولس تم ترميمه ، ومع ذلك تم استبدال الطابق الأول بأروقة خلف الممر ، توجد لوحة تذكارية لتشارلز بولس على خدماته في الحفاظ على المظهر التاريخي للميدان الكبير ، وكذلك لمهندسي Grand Place ، وهذا نصب تذكاري لعمدة بروكسل تشارلز بولز ، ليس بعيدا عن Grand Place ، وبجانب اللوحة يوجد النصب التذكاري لـ Everard t Serclaes بطل العصور الوسطى في بروكسل",
          "رقم 9 بجعة .. كان المنزل مملوكا لنقابة الجزارين في القرن التاسع عشر ، كان هذا المنزل عبارة عن مقهى ، حيث كان كارل ماركس وفريدريك انجلز رائعين للغاية",
          "رقم 10 الشجرة الذهبية .. المنزل ينتمي الى نقابة صانعي الجعة ، اكتملت الواجهة بتمثال الفروسية لتشارلز من لورين",
          "رقم 11 روز .. منزل خاص",
          "رقم 12 جبل فافور .. منزل خاص",
        ],
        en: [
          "The houses to the left of the town hall (numbered from right to left): No. 1, the King of Spain — the house belonged to the guild of bakers; above the door is a bust of Saint Aubert, patron of the bakers, and higher still a bust of Charles II, King of Spain.",
          "No. 2–3, the Wheelbarrow — the house belonged to the guild of producers of fats and oils, and later to the tallow-candle merchants; it is decorated with a statue of Saint Giles, the patron of this guild.",
          "No. 4, the Bag — the house belonged to the guild of cabinet and cupboard makers.",
          "No. 5, the She-Wolf — the house belonged to the guild of archers; the façade is crowned by the figure of a phoenix rising from the ashes and flames, symbolising the rebuilding of the city after the bombardment by the French forces in 1695, and the house is decorated with reliefs depicting Romulus and Remus suckled by a she-wolf, hence the name.",
          "No. 6, the Trumpet or the Horn — the house belongs to the guild of boatmen, and so its gable is made in the shape of the stern of a ship.",
          "No. 7, the Fox — the house belongs to the guild of haberdashers; the reliefs above the second floor depict the symbols of the four continents, and formerly the house was crowned with a statue of Saint Nicholas, the patron of the guild.",
          "The houses to the right of the town hall (numbered from right to left): No. 8, the Star — the Amman's house. In 1852 the house was demolished, and in 1897, on the initiative of mayor Charles Buls, it was restored, though the first floor was replaced by arcades behind the passage. There is a commemorative plaque to Charles Buls for his services in preserving the historic appearance of the Grand Place, and to the architects of the Grand Place; this is a memorial to the mayor of Brussels Charles Buls, not far from the Grand Place, and beside the plaque is the memorial to Everard 't Serclaes, the medieval hero of Brussels.",
          "No. 9, the Swan — the house was owned by the guild of butchers; in the nineteenth century this house was a café, where Karl Marx and Friedrich Engels were frequent guests.",
          "No. 10, the Golden Tree — the house belongs to the guild of brewers; the façade is completed by the equestrian statue of Charles of Lorraine.",
          "No. 11, the Rose — a private house.",
          "No. 12, Mount Thabor — a private house.",
        ],
      },
      {
        type: "P",
        ar: "ومع ذلك ، من المثير للاهتمام دراسة التاريخ بأسماء المنازل ، لمعرفة النقابات التي كانت موجودة في بروكسل في العصور الوسطى",
        en: "All the same, it is interesting to study history through the names of the houses, in order to learn which guilds existed in Brussels in the Middle Ages.",
      },
    ],
  },

  {
    slug: "cinquantenaire-park",
    title_ar: "حديقة سينكو نت ناير .. كل ما فيها سيدهشك",
    title_en: "Cinquantenaire Park .. everything in it will amaze you",
    kicker_ar: "معالم بروكسل",
    kicker_en: "Brussels landmarks",
    image: I("2022/09/img_3563.jpg"),
    blocks: [
      {
        type: "P",
        ar: "بارك دي سينكو نت ناير Parc du Cinquantenaire حديقة الذكرى الخمسين أو حديقة اليوبيل ، هي حديقة حضرية عامة كبيرة من 30 هكتار ، في الجزء الشرقي من الحي الاوروبي في بروكسل ببلجيكا",
        en: "Parc du Cinquantenaire, the park of the fiftieth anniversary or Jubilee Park, is a large public urban park of 30 hectares in the eastern part of the European Quarter of Brussels, Belgium.",
      },
      {
        type: "P",
        ar: "تم تصميم معظم مباني المجمع لتكون على شكل قوس وهي تهيمن على الحديقة وقد بنيت من قبل الحكومة البلجيكية تحت رعاية الملك ليوبولد الثاني للمعرض الوطني لعام 1880 للاحتفال بالذكرى الخمسين للثورة البلجيكية خلال المعارض المتتالية في نفس المنطقة ، تمت اضافة المزيد من المباني",
        en: "Most of the buildings of the complex were designed in the form of an arch and dominate the park; they were built by the Belgian government under the patronage of King Leopold II for the national exhibition of 1880, to celebrate the fiftieth anniversary of the Belgian revolution. During the successive exhibitions in the same area more buildings were added.",
      },
      {
        type: "P",
        ar: "مثل القوس التذكاري المركزي المعروف باسم قوس سينكو نت ناير في عام 1905 ليحل محل النموذج المؤقت السابق للممر بواسطة المهندس البلجيكي جيديون بورديو ، تم بناء المباني من الحديد والزجاج والحجر ، مما يرمز الى الأداء الاقتصادي والصناعي لبلجيكا ، المنطقة المحيطة 30 هكتار مليئة بالحدائق الخلابة والبرك والشلالات ، كانت الحديقة تضم العديد من الأقسام التجارية والمعارض والمهرجانات في بداية القرن في عام 1930 ، قررت الحكومة حجز حديقة سيكنتنير لاستخدامها كمنتزه ترفيهي",
        en: "Such as the central triumphal arch known as the Arch of the Cinquantenaire in 1905, which replaced the earlier temporary version of the arcade by the Belgian architect Gédéon Bordiau. The buildings were built of iron, glass and stone, symbolising the economic and industrial performance of Belgium. The surrounding area of 30 hectares is filled with picturesque gardens, ponds and waterfalls. The park held many commercial sections, exhibitions and festivals at the beginning of the century, and in 1930 the government decided to reserve the Cinquantenaire park for use as a leisure park.",
      },
      {
        type: "P",
        ar: "كان المتحف العسكري الملكي هو المستأجر الوحيد للنصف الشمالي من الحديقة منذ عام 1880 ، النصف الجنوبي مشغول بمتحف الفن والتاريخ ومتحف سيارات العالم للسيارات القديمة ، بالاضافة الى معبد المشاعر الانسانية لفيكتور هورتا وهو تذكار من عام 1886 ، ومسجد بروكسل الكبير من عام 1978 ، في الركن الشمالي الغربي من الحديقة",
        en: "The Royal Military Museum has been the sole tenant of the northern half of the park since 1880. The southern half is occupied by the museum of art and history and the Autoworld museum of vintage cars, in addition to Victor Horta's Temple of Human Passions, a memorial from 1886, and the Great Mosque of Brussels from 1978, in the north-western corner of the park.",
      },
      { type: "IMG", src: I("2022/09/img_3564.jpg"), cap_ar: "قوس سينكو نت ناير", cap_en: "The Arch of the Cinquantenaire" },
      {
        type: "P",
        ar: "يعود تاريخ الحديقة التي تبلغ مساحتها 30 هكتارا الى عهد الملك ليوبولد الثاني الذي أراد تطوير بروكسل لتصبح عاصمة أوروبية مرموقة ، ولتحقيق حلمه ، أمر الملك ببناء عدد كبير من المباني والشوارع والحدائق العامة ومنها حديقة سينكونت ناير بروكسل التي تم بنائها في عام 1880 ، وقد أشرف على عملية البناء المهندس المعماري بورديو الذي أشرف على المشروع حتى وفاته في عام 1904 ، ثم تولى المهندس المعماري الفرنسي تشارلز جيرولت حتى الانتهاء من المشروع في عام 1905 وفي هذه الأثناء توقف مشروع البناء عدة مرات بسبب نقص التمويل",
        en: "The history of the 30-hectare park goes back to the reign of King Leopold II, who wanted to develop Brussels into a prestigious European capital. To realise his dream the king ordered the construction of a large number of buildings, streets and public parks, among them the Cinquantenaire park in Brussels, built in 1880. The construction was supervised by the architect Bordiau, who oversaw the project until his death in 1904, after which the French architect Charles Girault took over until the project was completed in 1905 — and in the meantime the building works stopped several times for lack of funding.",
      },
      { type: "IMG", src: I("2022/09/img_3569.jpg"), cap_ar: "حديقة سينكو نت ناير ببروكسل", cap_en: "Cinquantenaire Park in Brussels" },
      {
        type: "H3",
        noNumber: true,
        ar: "افضل الانشطة التي يمكن القيام بها في حديقة سينكو نت ناير ببروكسل",
        en: "The best activities to do in Cinquantenaire Park in Brussels",
      },
      {
        type: "LIST",
        ar: [
          "الاستمتاع بجولة ساحرة بين المناظر الطبيعية الخلابة والتقاط العديد من الصور التذكارية الرائعة بجانب باقات الورود والأشجار النادرة المنتشرة في جميع أروقة الحديقة",
          "التجول عند القنطرة والتقاط الصور التذكارية عند النافورة الموجودة عند المدخل الخاص بالحديقة كما يمكن للزائر الصعود لأعلة ليشاهد المنظر البانورامي للمدينة بدون أي رسوم",
          "زيارة المتاحف الموجودة في الحديقة وهي عبارة عن ثلاث متاحف هي المتحف الملكي وهو متحف خاص بالفن والمتحف الحربي ومتحف السيارات ومراحل تطورها منذ بداية تصنيعها وحتى ما وصلت إليه الآن ويعرف بالمتحف أوتو وورلد ، كما يوجد بالحديقة مجموعة من الآثار والمنحوتات",
          "نظرا لمساحة الحديقة الهائلة يوجد بها العديد من شاشات العرض ليشاهد الزائر الأفلام والبرامج الترفيهية ويقام فيها العديد من الحفلات والمهرجانات ، كما يوجد أيضا مدينة خاصة لألعاب الفيديو SimCity التي تم اطلاقها في عام 2013",
          "زيارة المركز الاسلامي وهو أقدم وأكبر مسجد بمدينة ببلجيكا كلها ويعرف بمسجد بروكسل الكبير الذي بني في عام 1880 على يد المهندس المعماري ارنست فان هومبيك",
        ],
        en: [
          "Enjoying a charming walk among the picturesque natural scenery and taking many wonderful souvenir photographs beside the bouquets of roses and the rare trees spread through every corner of the park.",
          "Strolling by the arch and taking souvenir photographs at the fountain by the park's entrance; the visitor can also climb to the top to see the panoramic view of the city without any fee.",
          "Visiting the museums in the park — three museums: the Royal Museum, which is dedicated to art, the military museum, and the car museum showing the stages of the automobile's development from the beginning of its manufacture to what it has become today, known as the Autoworld museum. The park also holds a collection of monuments and sculptures.",
          "Given the park's enormous size, it has many screens where visitors can watch films and entertainment programmes, and many concerts and festivals are held there. There is also a special area for the video game SimCity, launched in 2013.",
          "Visiting the Islamic centre, the oldest and largest mosque in any city in the whole of Belgium, known as the Great Mosque of Brussels, built in 1880 by the architect Ernest van Humbeek.",
        ],
      },
      { type: "IMG", src: I("2022/09/img_3570.jpg"), cap_ar: "حديقة سينكو نت ناير ببروكسل", cap_en: "Cinquantenaire Park in Brussels" },
      { type: "H3", noNumber: true, ar: "أشهر معالم حديقة سينكونت ناير", en: "The most famous landmarks of Cinquantenaire Park" },
      {
        type: "P",
        ar: "تشتهر حديقة سينكونت ناير بقوسها الفريد ، والنافورة عند مدخلها ، وتجدر الاشارة الى أنه يمكن لزائر الحديقة الصعود الى أعلى الجسر فيها مجانا ، لرؤية المدينة بمنظر بانورامي من الأعلى ، وتتضمن ثلاثة متاحف تستحق الزيارة ، وهي بالترتيب :",
        en: "Cinquantenaire Park is famous for its unique arch and for the fountain at its entrance, and it is worth noting that a visitor to the park can climb to the top of its bridge for free to see the city in a panoramic view from above. It contains three museums worth visiting, which are, in order:",
      },
      { type: "H3", noNumber: true, ar: "متحف عالم السيارات", en: "The Autoworld museum" },
      {
        type: "P",
        ar: "وهو متحف خاص للسيارات في بروكسل ، يعرض تطورها عبر الزمن منذ اختراعها وحتى يومنا هذا ، وتحفظ فيه مجموعة مكونة من 200 سيارة تملكها عائلة ماهي (Mahy) ، المالكة لاحدى أكبر الشركات في العالم ، حيث كان مؤسسها غيسلان ماهي ميكانيكيا شغوفا بالسيارات منذ صغره ، واستمر في ترميم عشرات السيارات طوال حياته ، بالاضافة الى وجود سيارات أخرى ذات علامات تجارية مختلفة في نفس المتحف",
        en: "This is a museum dedicated to cars in Brussels, showing their development through time from their invention until today. It preserves a collection of 200 cars owned by the Mahy family, owners of one of the largest companies in the world; its founder Ghislain Mahy was a mechanic passionate about cars from his childhood and went on restoring dozens of cars all his life. There are also other cars of different makes in the same museum.",
      },
      { type: "IMG", src: I("2022/09/img_3565.jpg"), cap_ar: "متحف عالم السيارات ببروكسل", cap_en: "The Autoworld museum in Brussels" },
      { type: "H3", noNumber: true, ar: "المتحف الملكي للفنون والتاريخ", en: "The Royal Museum of Art and History" },
      {
        type: "P",
        ar: "وهو أحد أكبر المتاحف في بلجيكا ، والذي أمر ببنائه الملك البلجيكي السابق ليوبولد الثاني حين اكتشف أن بلاده تمتلك ثروة من القطع الأثرية من عصور ما قبل التاريخ الى العصور القديمة والعصور الاغريقية ، بالاضافة الى الفنون التطبيقية الأوروبية ، ومجموعة كبيرة من الأعمال الفنية غير الأوروبية ، مثل المنحوتات ، والملابس والأثواب الوطنية والشعبية ، والعربات التي كانت تجرها الأحصنة ، ومعدات وآلات التصوير القديمة ، وغيرها",
        en: "This is one of the largest museums in Belgium, whose construction was ordered by the former Belgian king Leopold II when he discovered that his country possessed a wealth of artefacts from prehistoric times through antiquity and the Greek era, in addition to European applied arts and a large collection of non-European works of art such as sculptures, national and folk clothing and robes, horse-drawn carriages, old photographic equipment and machines, and more.",
      },
      { type: "IMG", src: I("2022/09/img_3566.jpg"), cap_ar: "المتحف الملكي للفنون والتاريخ ببروكسل", cap_en: "The Royal Museum of Art and History in Brussels" },
      { type: "H3", noNumber: true, ar: "المتحف الملكي العسكري الحربي", en: "The Royal Military Museum" },
      {
        type: "P",
        ar: "المتحف العسكري الملكي هو مؤسسة علمية حكومية اتحادية فدرالية ، هدفها تعزيز المعرفة بالتاريخ العسكري وتاريخ الصراعات في المنطقة ، من خلال التراث العسكري المادي وغير المادي ، والذي تقوم ادارة المتحف على المحافظة عليها ، وتفسير وتحليل الأحداث التي مرت بها ، ويمتد الاطار الزمني لمحتويات المتحف يمتد الاطار الزمني من العصور الوسطى حتى الوقت الحاضر ، ويعمل فيه خبراء محليين ودوليين",
        en: "The Royal Military Museum is a federal government scientific institution whose aim is to advance knowledge of military history and the history of conflicts in the region through tangible and intangible military heritage, which the museum's administration preserves, interpreting and analysing the events it has passed through. The time frame of the museum's contents extends from the Middle Ages to the present day, and local and international experts work there.",
      },
      { type: "IMG", src: I("2022/09/img_3567.jpg"), cap_ar: "المتحف الملكي العسكري الحربي ببروكسل", cap_en: "The Royal Military Museum in Brussels" },
      { type: "H3", noNumber: true, ar: "الجامع الكبير في بروكسل", en: "The Great Mosque of Brussels" },
      {
        type: "P",
        ar: "يوجد الجامع الكبير في بروكسل داخل أسوار حديقة سينكونت ناير ، وهو أكبر مسجد في بروكسل ، مولت المملكة العربية السعودية بنائه في المنطقة الشمالية العربية من الحديقة ، ويجتمع فيه المسلمون لأداء صلاة الجمعة وصلاة العيد ، كما يقدم المسجد دورات لتعليم اللغة العربية ، ودورات لتحفيظ القرآن الكريم للأطفال ، ويسعى رواد المسجد لتمكين فكرة أن الدين الاسلامي لا علاقة له بالعمليات الارهابية المتطرفة ، وأنه يشجبها ويحث على السلام والمحبة",
        en: "The Great Mosque of Brussels stands within the walls of Cinquantenaire Park and is the largest mosque in Brussels. The Kingdom of Saudi Arabia financed its construction in the northern part of the park. Muslims gather there for the Friday prayer and the Eid prayer, and the mosque also offers courses to teach Arabic and courses for children to memorise the Holy Qur'an. Those who frequent the mosque seek to establish the idea that the Islamic religion has nothing to do with extremist terrorist operations, that it condemns them and urges peace and love.",
      },
      { type: "IMG", src: I("2022/09/img_3568.jpg"), cap_ar: "الجامع الكبير ببروكسل", cap_en: "The Great Mosque of Brussels" },
      { type: "H3", noNumber: true, ar: "كيفية الوصول الى حديقة سينكونت ناير ببروكسل", en: "How to reach Cinquantenaire Park in Brussels" },
      {
        type: "P",
        ar: "يمر الخط 1 من مترو بروكسل ونفق بيليارد من شارع دو لا لوا أسفل المنتزه ، ويمر الأخير جزئيا في قسم مفتوح أمام القوس ، أقرب محطات المترو هي شومان الى الغرب من المنتزه ومحطة مرود الى الشرق",
        en: "Line 1 of the Brussels metro and the Belliard tunnel from the Rue de la Loi pass beneath the park, the latter running partly in an open section in front of the arch. The nearest metro stations are Schuman to the west of the park and Merode station to the east.",
      },
    ],
  },

  {
    slug: "royal-palace-brussels",
    title_ar: "القصر الملكي .. تحفه معمارية فريدة",
    title_en: "The Royal Palace .. a unique architectural masterpiece",
    kicker_ar: "معالم بروكسل",
    kicker_en: "Brussels landmarks",
    image: I("2022/10/img_3584.jpg"),
    blocks: [
      {
        type: "P",
        ar: "بني القصر الملكي في بروكسل على أنقاض قصر آخر في عام 1820م ، ورمم بمرور السنوات ، ليتخذ طابع الملك لويس السادس عشر ، وبعض الأجنحة فيه يعود تاريخها الى القرن الثامن عشر ، ويحتوي على لوحات فنية قيمة وتحف ثمينة ، وافتتح للزوار منذ عام 1965م",
        en: "The Royal Palace in Brussels was built on the ruins of another palace in 1820 and was restored over the years to take on the character of King Louis XVI. Some of its wings date back to the eighteenth century. It holds valuable paintings and precious antiques, and has been open to visitors since 1965.",
      },
      {
        type: "P",
        ar: "يعد القصر الملكي هو المكان الذي يمارس فيه ملك بلجيكا سلطته كرئيس للدولة ، وهو القصر الرسمي لكل من ملك وملكة بلجيكا",
        en: "The Royal Palace is the place where the King of Belgium exercises his authority as head of state, and it is the official palace of both the King and Queen of Belgium.",
      },
      { type: "IMG", src: I("2022/10/img_3586.jpg"), cap_ar: "القصر الملكي ببروكسيل", cap_en: "The Royal Palace in Brussels" },
      {
        type: "P",
        ar: "يحتوي هذا القصر المدهش على العديد من الغرف والأجنحة المختلفة ، وفيما يلي أهم أجزاء القصر من الداخل :",
        en: "This astonishing palace contains many different rooms and wings, and the following are the most important parts of the palace inside:",
      },
      { type: "H3", noNumber: true, ar: "الردهة الرئيسية والسلم", en: "The main hall and the staircase" },
      {
        type: "P",
        ar: "صمم هذا المدخل الرائع في عهد الملك ليوبولد الثاني ، وتساهم الجدران والأعمدة الحجرية ، والسلم المصمم من الرخام الأبيض والمرايا والنوافذ الكبيرة في صناعة انسجام لا مثيل له",
        en: "This magnificent entrance was designed in the reign of King Leopold II, and the walls and stone columns, the staircase made of white marble, the mirrors and the large windows all contribute to creating an unrivalled harmony.",
      },
      { type: "H3", noNumber: true, ar: "غرفة الانتظار الكبيرة", en: "The great waiting room" },
      {
        type: "P",
        ar: "تحتوي هذه الغرفة على لوحات فنية تعود الى الملك ليوبولد الأول وزوجته شارلوت ، ويعود تاريخ غرفة الانتظار الكبيرة الى الفترة الهولندية ، عندما تم توحيد شمال وجنوب هولندا في مملكة واحدة",
        en: "This room holds paintings belonging to King Leopold I and his wife Charlotte, and the great waiting room dates back to the Dutch period, when the north and south of the Netherlands were united in one kingdom.",
      },
      { type: "H3", noNumber: true, ar: "غرفة الامبراطورية", en: "The Empire room" },
      {
        type: "P",
        ar: "تقع هذه الغرفة في الجزء الأقدم من القصر ، وكانت تستخدم كقاعة رقص لممثل الامبراطورية النمساوية ، وهي غرفة مذهبة جميلة ذات ديكور رائع مخصص لاقامة الحفلات الموسيقية للبلاط الملكي ، وتزخر باللوحات الفنية والمرايا ، ويتم فيها استقبال سفراء الدول الأخرى عند تقديم أعمالهم الى الملك البلجيكي",
        en: "This room lies in the oldest part of the palace and was used as a ballroom for the representative of the Austrian empire. It is a beautiful gilded room with splendid decoration dedicated to holding concerts for the royal court, rich in paintings and mirrors, and it is where the ambassadors of other states are received when presenting their credentials to the Belgian King.",
      },
      { type: "H3", noNumber: true, ar: "الغرفة البيضاء الكبيرة والصغيرة", en: "The large and small white rooms" },
      {
        type: "P",
        ar: "كانت الغرفة تخص دولة الرئيس النمساوي ، ولا تزال هذه الغرفة محافظة على الزخارف الأصلية والمفروشات نفسها التي تعود الى القرن الثامن عشر ، وتحتوي هذه الغرفة التاريخية الرائعة على لوحات تعود الى الملكة لويز ماري ، ووالديها الملك لويس فيليب ، والملكة ماري أميلي دي بوربون",
        en: "The room belonged to the state of the Austrian governor, and it still preserves the original decoration and the same furnishings dating from the eighteenth century. This wonderful historic room holds paintings belonging to Queen Louise-Marie and her parents King Louis-Philippe and Queen Marie-Amélie de Bourbon.",
      },
      { type: "H3", noNumber: true, ar: "غرفة كوبرغ", en: "The Coburg room" },
      {
        type: "P",
        ar: "تعتبر غنية باللوحات الفنية التاريخية والتي تعود معظمها الى الملك ليوبولد الأول ، وأفراد من عائلة كوبرغ ، منهم والد الملك ، دوق فرانسيس ، ويوجد أيضا لوحة فنية رسمية تمثل الملكة لويز ماري",
        en: "It is considered rich in historic paintings, most of them belonging to King Leopold I and members of the Coburg family, among them the king's father, Duke Francis. There is also an official painting representing Queen Louise-Marie.",
      },
      { type: "H3", noNumber: true, ar: "غرفة الأعمدة", en: "The room of the columns" },
      {
        type: "P",
        ar: "كانت هذه الغرفة بالأصل تعد غرفة انتظار ، ثم تحولت مع الزمن لتصبح غرفة طعام لكبار الشخصيات وأهمها ، وتتميز غرفة الأعمدة بديكوراتها المذهلة الرائعة ، والكراسي ذات الطراز الامبراطوري ، فجزء من الأثاث في هذه الغرفة استخدم من قبل نابليون بونابرت ، وجوزفين دي بوهارني ، ويوجد فيها لوحة فنية للملك ليوبولد الأول",
        en: "This room was originally a waiting room, then turned over time into a dining room for the most important dignitaries. The room of the columns is distinguished by its stunning, splendid decoration and its Empire-style chairs; part of the furniture in this room was used by Napoleon Bonaparte and Joséphine de Beauharnais, and it holds a painting of King Leopold I.",
      },
      { type: "H3", noNumber: true, ar: "غرفة العرش", en: "The throne room" },
      {
        type: "P",
        ar: "بنيت هذه الغرفة العريقة في عهد الملك ليوبولد الثاني ، وهي مزينة في الوسط بأربعة نقوش رائعة منخفضة ، وتتميز بديكوراتها الفخمة ، والثريات البرونزية المذهبة التي تعطي غرفة العرش مظهرا هائلا ومرموقا",
        en: "This venerable room was built in the reign of King Leopold II. It is decorated in the middle with four splendid low reliefs and is distinguished by its sumptuous decoration and the gilded bronze chandeliers that give the throne room an imposing and prestigious appearance.",
      },
      { type: "IMG", src: I("2022/10/img_3587.jpg"), cap_ar: "القصر الملكي ببروكسيل", cap_en: "The Royal Palace in Brussels" },
      { type: "IMG", src: I("2022/10/img_3588.jpg"), cap_ar: "صور للقصر الملكي ببروكسيل", cap_en: "Views of the Royal Palace in Brussels" },
      { type: "IMG", src: I("2022/10/img_3589.jpg"), cap_ar: "صور للقصر الملكي ببروكسيل", cap_en: "Views of the Royal Palace in Brussels" },
      { type: "IMG", src: I("2022/10/img_3590.jpg"), cap_ar: "صور للقصر الملكي ببروكسيل", cap_en: "Views of the Royal Palace in Brussels" },
      { type: "H3", noNumber: true, ar: "المزيد من المعرفة عن القصر الملكي ببروكسيل", en: "More to know about the Royal Palace in Brussels" },
      {
        type: "P",
        ar: "القصر الملكي في بروكسل Palais royal de Bruxelles ، هو القصر الرسمي لملك وملكة البلجيكيين في مركز عاصمة الأمة بروكسل ، ومع ذلك لا يتم استخدامه كمقر اقامة ملكي ، حيث يعيش الملك وعائلته في القصر الملكي في لاكن شمال بروكسل ، يصف موقع النظام الملكي البلجيكي وظيفة القصر على النحو التالي :",
        en: "The Royal Palace in Brussels, the Palais royal de Bruxelles, is the official palace of the King and Queen of the Belgians in the centre of the nation's capital, Brussels. It is not, however, used as a royal residence, since the King and his family live in the Royal Palace of Laeken north of Brussels. The website of the Belgian monarchy describes the function of the palace as follows:",
      },
      {
        type: "P",
        ar: "القصر هو المكان الذي يمارس فيه جلالة الملك صلاحياته كرئيس للدولة ، ويمنح الجمهور ويتعامل مع شؤون الدولة ، بصرف النظر عن مكاتب الملك والملكة ، يضم القصر الملكي خدمات المشير الكبير للمحكمة ، ورئيس مجلس الوزراء للملك ، ورئيس الأسرة العسكرية للملك والمشرف على القائمة المدنية للملك ، يضم القصر أيضا غرف الدولة حيث تقام حفلات الاستقبال الكبيرة ، فضلا عن الشقق المقدمة لرؤساء الدول الأجنبية خلال الزيارات الرسمية",
        en: "The palace is where His Majesty the King exercises his powers as head of state, grants audiences and deals with affairs of state. Apart from the offices of the King and Queen, the Royal Palace houses the services of the Grand Marshal of the Court, the head of the King's cabinet, the head of the King's military household and the intendant of the King's civil list. The palace also holds the state rooms where large receptions are held, as well as the apartments offered to foreign heads of state during official visits.",
      },
      {
        type: "P",
        ar: "تعود النواة الأولى للمبنى الحالي الى نهاية القرن الثامن عشر ، ومع ذلك فان الأرض التي يقوم عليها القصر كانت ذات يوم جزء من قصر Coudenberg ، وهو مجمع فخم قديم جدا يعود تاريخه الى العصور الوسطى ، تم بناء الواجهة الموجودة اليوم فقط بعد عام 1900 بمبادرة من الملك ليوبولد الثاني",
        en: "The first nucleus of the present building goes back to the end of the eighteenth century; the ground on which the palace stands, however, was once part of the Coudenberg Palace, a very old and sumptuous complex dating from the Middle Ages. The façade that exists today was built only after 1900, on the initiative of King Leopold II.",
      },
      {
        type: "P",
        ar: "يقع القصر الملكي أمام منتزه بروكسل الذي يفصله عنه ميدان طويل يسمى Place des Palais / Paleizenplein ، يمثل المحور الأوسط للحديقة كلا من الباريستو الأوسط للقصر الملكي ومبنى البرلمان الفيدرالي البلجيكي (قصر الأمة) على الجانب الآخر من الحديقة ، يقال ان المبنيين المواجهين يرمزان الى نظام الحكم في بلجيكا ملكية دستورية",
        en: "The Royal Palace stands in front of the Park of Brussels, separated from it by a long square called the Place des Palais / Paleizenplein. The central axis of the park lines up both the central bay of the Royal Palace and the building of the Belgian federal parliament (the Palace of the Nation) on the other side of the park; the two facing buildings are said to symbolise Belgium's system of government, a constitutional monarchy.",
      },
      { type: "IMG", src: I("2022/10/img_3591.jpg"), cap_ar: "القصر الملكي ببروكسيل", cap_en: "The Royal Palace in Brussels" },
      { type: "H3", noNumber: true, ar: "افضل الانشطة التي يمكن القيام بها في القصر الملكي ببروكسيل", en: "The best activities to do at the Royal Palace in Brussels" },
      {
        type: "P",
        ar: "من المميز بهذا القصر أنه على الرغم من اعتباره مقرا للحكم الا أنه مسموح بزيارة بعض الغرف فيه ، يمكنك التنقل بين تلك الغرف التي تحوي ممتلكات ملكية وزخارف ونقوش وأثاث يعود بعضها الى عصور سالفة من التاريخ البلجيكي ، على سبيل المثال غرفة الامبراطور وغرفة جويا وغيرها الكثير",
        en: "What is special about this palace is that although it is considered the seat of government, some of its rooms may be visited. You can move between those rooms, which hold royal possessions, decorations, reliefs and furniture, some of it going back to earlier eras of Belgian history — for example the Emperor's room and the Goya room, and many others.",
      },
      {
        type: "P",
        ar: "كما يمكنك الاستمتاع بزيارة الحديقة الخاصة بالقصر والتي تسمى حديقة بروكسل الملكية ، وهي من أهم الحدائق التي يلجأ اليها أهل البلد والسياح أيضا للاستمتاع والاسترخاء واللقاء والقيام بنزهات",
        en: "You can also enjoy visiting the palace's own garden, called the royal park of Brussels, one of the most important parks to which locals and tourists alike resort for enjoyment, relaxation, meeting and picnicking.",
      },
      {
        type: "P",
        ar: "كما يمكنك زيارة متحف بلفو BELvue الشهير الذي ستجده بجانب القصر الملكي ، وهو متحف للتاريخ الوطني البلجيكي مقسم الى اثنى عشر غرفة يعرض كل منها جزء خاصا من مشاهد التاريخ البلجيكي ويحوي أيضا عددا من المجوهرات والأشياء الملكية الخاصة من عصور مختلفة",
        en: "You can also visit the famous BELvue museum, which you will find beside the Royal Palace: a museum of Belgian national history divided into twelve rooms, each presenting a particular part of the scenes of Belgian history, and it also holds a number of jewels and private royal objects from different eras.",
      },
      { type: "IMG", src: I("2022/10/img_3585.jpg"), cap_ar: "القصر الملكي ببروكسيل", cap_en: "The Royal Palace in Brussels" },
      {
        type: "P",
        ar: "يوجد في القصر جزء مهم من المجموعة الملكية ، يتكون هذا بشكل أساسي من صور الدولة والأثاث الهام لنابليون وليوبولد الأول ولويس فيليب الأول وليوبولد الثاني ، يتم الاحتفاظ بالأواني الفضية والبورسلين والكريستال الفاخر في الأقبية المستخدمة أثناء الولائم الرسمية والمناسبات الرسمية في المحكمة ، أضافت الملكة باولا الفن الحديث في بعض غرف الدولة",
        en: "The palace holds an important part of the royal collection, consisting mainly of state portraits and important furniture of Napoleon, Leopold I, Louis-Philippe I and Leopold II. The silverware, porcelain and fine crystal used during official banquets and formal occasions at court are kept in the cellars, and Queen Paola added modern art to some of the state rooms.",
      },
      {
        type: "P",
        ar: "خلال زيارات الدولة ، تكون الشقق والأجنحة الملكية تحت تصرف رؤساء الدول الزائرين ، السفراء أيضا يتم استقبالهم هناك بمراسم رسمية ، تقام حفلات استقبال العام الجديد لحلف شمال الأطلسي وسفراء وسياسيين في الاتحاد الأوروبي ، تقام مآدب الزفاف الملكية في القصر ، وبعد وفاتهم يرقد جثمان الملك المتوفى هناك ، اذا كان الملك موجودا في البلاد فيتم رفع العلم على المبنى المركزي ، واذا كان موجودا داخل القصر فان حرس الشرف يقف أمام القصر",
        en: "During state visits the royal apartments and wings are placed at the disposal of visiting heads of state, and ambassadors are also received there with official ceremony. New Year receptions are held for NATO and for ambassadors and politicians of the European Union, royal wedding banquets are held in the palace, and after their death the body of a deceased king lies there. If the King is in the country the flag is raised on the central building, and if he is inside the palace the guard of honour stands in front of it.",
      },
      { type: "IMG", src: I("2022/10/img_3593.jpg"), cap_ar: "صور للقصر الملكي ببروكسيل", cap_en: "Views of the Royal Palace in Brussels" },
      { type: "IMG", src: I("2022/10/img_3592.jpg"), cap_ar: "صور للقصر الملكي ببروكسيل", cap_en: "Views of the Royal Palace in Brussels" },
      { type: "H3", noNumber: true, ar: "اوقات زيارة القصر الملكي ببروكسيل", en: "Visiting hours of the Royal Palace in Brussels" },
      {
        type: "P",
        ar: "يفتح القصر أبوابه ابتداء من 21 يوليو حتى 1 سبتمبر من كل عام ، ويمكن زيارته وفقا للأوقات التالية : الثلاثاء – الأحد : ابتداء من الساعة 10:30 صباحا وحتى الساعة 05:00 مساء ، ويغلق القصر أبوابه يوم الاثنين فقط خلال الفترة المسموح بها حسب أعلاه",
        en: "The palace opens its doors from 21 July until 1 September every year, and can be visited according to the following times: Tuesday – Sunday, from 10:30 in the morning until 05:00 in the afternoon. The palace closes only on Monday during the period allowed above.",
      },
    ],
  },

  {
    slug: "atomium",
    title_ar: "أتوميوم .. رمز معرض اكسبو",
    title_en: "The Atomium .. the symbol of the Expo fair",
    kicker_ar: "معالم بروكسل",
    kicker_en: "Brussels landmarks",
    image: I("2022/09/img_3572.jpg"),
    blocks: [
      {
        type: "P",
        ar: "أتوميوم معلم شهير يقع في مدينة بروكسيل ، صمم من قبل المهندس أندريه واتركيين ، كان أتوميوم الجناح الرئيسي ورمز للمعرض الدولي اكسبو 58 الذي أقيم في عاصمة بلجيكا على موقع هيسل عام 1958 ، لم يكن القصد من أتوميوم البقاء الى ما بعد المعرض ، لكن نجاحة جعله منه معلما دائما ورمزا عالميا لمدينة بروكسيل",
        en: "The Atomium is a famous landmark in the city of Brussels, designed by the engineer André Waterkeyn. It was the main pavilion and symbol of the Expo 58 international fair held in the Belgian capital on the Heysel site in 1958. The Atomium was not intended to remain beyond the fair, but its success made it a permanent landmark and a world symbol of the city of Brussels.",
      },
      {
        type: "P",
        ar: "كان من المخطط ان يصل أتوميوم الى ارتفاع 134 متر ، ولأسباب تتعلق بالسلامة ، خفض مستوى الارتفاع بنسبة 24٪ ليصبح الاجمالي 102 متر ، تم تجديد أتوميوم في مارس 2004",
        en: "It was planned for the Atomium to reach a height of 134 metres, but for safety reasons the height was reduced by 24% to a total of 102 metres. The Atomium was renovated in March 2004.",
      },
      { type: "IMG", src: I("2022/09/img_3583.jpg"), cap_ar: "أتوميوم بروكسيل", cap_en: "The Atomium, Brussels" },
      {
        type: "P",
        ar: "يعتبر الأتوميوم الرمز الأكثر شهرة لجميع السكان في مدينة بروكسل ، فهو مزار لا يمكن تجنبه أثناء تواجدك في بروكسل ، انه تحفة فنية فريدة في تاريخ العمارة وأثر رمزي للمعرض العالمي في بروكسل ، كما توجد فيه ذرة الفضة العملاقة التي تم بناؤها في معرض اكسبو عام 1958م ، والتي تستحق التوجه الى قمة المبنى من أجل الحصول على منظر رائع عبر المدينة ، وهي عبارة عن بلورة حديدية تضخمت 165 مليار مرة ، والكرات الفولاذية الضخمة هي غرف موصولة بدرج كهربائي فيما بينها ، ويمكن رؤيتها من مسافة بعيدة جدا",
        en: "The Atomium is considered the most famous symbol for all the inhabitants of the city of Brussels, and it is a sight that cannot be avoided while you are there. It is a unique masterpiece in the history of architecture and a symbolic relic of the world fair in Brussels. It holds the giant silver atom built for the Expo fair of 1958, which is worth going up to the top of the building for in order to get a wonderful view across the city — it is an iron crystal magnified 165 billion times, and the huge steel spheres are rooms connected to each other by escalators, visible from a very great distance.",
      },
      { type: "IMG", src: I("2022/09/img_3582.jpg"), cap_ar: "أتوميوم بروكسيل", cap_en: "The Atomium, Brussels" },
      { type: "IMG", src: I("2022/09/img_3581.jpg"), cap_ar: "أتوميوم بروكسيل", cap_en: "The Atomium, Brussels" },
      { type: "H3", noNumber: true, ar: "المزيد من المعرفة عن أتوميوم ببروكسيل", en: "More to know about the Atomium in Brussels" },
      {
        type: "P",
        ar: "في 25 مارس 1957 تم التوقيع على اتفاقية روما بتطلع الى مستقبل أفضل ، يتسم بالوئام والتقدم والسلام ، أتوميوم هذا الحلم هو في حد ذاته نتاج عصره ، أتوميوم أيضا حلم المدينة الفاضلة ، التي تجذرت في ذهن المهندس أندريه واتركيين والمهندسين المعماريين أندريه وجان بولاك",
        en: "On 25 March 1957 the Treaty of Rome was signed, looking towards a better future marked by harmony, progress and peace. The Atomium, this dream, is itself a product of its age; the Atomium is also a utopian dream, rooted in the mind of the engineer André Waterkeyn and the architects André and Jean Polak.",
      },
      {
        type: "P",
        ar: "استضافت مدينة بروكسيل اكسبو 58 المعرض الدولي في أبريل 1958 برسالة عالم من أجل حياة أفضل للبشرية ، كان أتوميوم الجناح الرئيسي ، يرمز الى الارادة الديمقراطية للحفاظ على السلام بين جميع الدول ، والايمان بالتقدم ، التقني والعلمي ، متفائل برؤية المستقبل ، والعالم الجديد ، فائق التقنية من أجل حياة أفضل",
        en: "The city of Brussels hosted Expo 58, the international fair, in April 1958 with the message of a world for a better life for humanity. The Atomium was the main pavilion, symbolising the democratic will to preserve peace among all nations, faith in technical and scientific progress, an optimistic vision of the future and of a new, highly technological world for a better life.",
      },
      {
        type: "P",
        ar: "الاستخدام السلمي للطاقة الذرية هو ما يحدد شكل أتوميوم بشكل خاص ، في 102 مترا ، مع تسعة كرات مترابطة ، فانه يمثل وحدة خلية الحديد المكعبة ، مكبرة 165 مليار (ألف مليون) مره ، مرتكز على احدى الذرات",
        en: "The peaceful use of atomic energy is what particularly determines the shape of the Atomium. At 102 metres, with nine interconnected spheres, it represents the unit cell of a cubic iron crystal, magnified 165 billion (thousand million) times, resting on one of its atoms.",
      },
      {
        type: "LIST",
        ar: [
          "ارتفاع اجمالي : 102m",
          "قطر الكرات الذرات : 18M",
          "قطر الأنابيب : 3m30",
          "طول الأنابيب : 29M",
          "طول الأنابيب قطري : 23M",
          "قطر للجناح القاعدة : 26M",
          "الكتلة الكلية (عام 1958) : 2400 طن",
          "يرتكز الهيكل على 3 أعمدة",
        ],
        en: [
          "Total height: 102 m",
          "Diameter of the spheres (the atoms): 18 m",
          "Diameter of the tubes: 3.30 m",
          "Length of the tubes: 29 m",
          "Length of the diagonal tubes: 23 m",
          "Diameter of the base pavilion: 26 m",
          "Total mass (in 1958): 2,400 tonnes",
          "The structure rests on 3 columns",
        ],
      },
      { type: "IMG", src: I("2022/09/img_3580.jpg"), cap_ar: "أتوميوم بروكسيل", cap_en: "The Atomium, Brussels" },
      { type: "H3", noNumber: true, ar: "الوصف الخارجي للأتيوميوم", en: "The exterior description of the Atomium" },
      {
        type: "P",
        ar: "تم بناء Atomium في بلجيكا من تسعة مجالات ، بتعبير أدق ، هذه الذرات التي تم دمجها في قطعة من الكريستال البلوري للحديد ، زادت بمقدار 165 مليار مرة ، الوزن الكلي للنحت يصل الى 2400 طن ، كان الطلاء الأولي للكائن عبارة عن كرة من الألومنيوم ، على كل مجال كان هناك 720 لوحة من الشكل الثلاثي ، ولكن في عام 2006 ، أجريت اصلاحات رئيسية ، ونتيجة لذلك حصلت Atomium على قذيفة من الفولاذ",
        en: "The Atomium in Belgium was built of nine spheres — more precisely, these are the atoms combined in a piece of iron crystal, magnified 165 billion times. The total weight of the sculpture reaches 2,400 tonnes. The original cladding of the object was an aluminium skin: on every sphere there were 720 triangular panels. But in 2006 major repairs were carried out, and as a result the Atomium received a shell of steel.",
      },
      {
        type: "P",
        ar: "نوافذ الممرات والمجالات كانت في الأصل مصنوعة من الزجاج العضوي ، ولكن في وقت لاحق تم استبدال هذه المواد بالزجاج المقسى ، خلال اعادة الاعمار الرئيسية للمنشأة ، استبدلت الأنابيب المتصلة ، والمصاعد والسلالم المتحركة",
        en: "The windows of the passages and the spheres were originally made of organic glass, but later this material was replaced with tempered glass. During the major reconstruction of the structure the connecting tubes, the lifts and the escalators were replaced.",
      },
      {
        type: "P",
        ar: "كل من ذرات الأتوميوم في بلجيكا في القطر لديه 18 مترا ، ترتبط بواسطة أنابيب 23 متر ، يوجد في منتصف هذه الأنابيب ممرات ربط وسلالم متحركة تسمح للسائحين بالسفر ، ستة من الكرات التسعة مفتوحة دائما للسياح",
        en: "Each of the atoms of the Atomium in Belgium is 18 metres in diameter, connected by tubes 23 metres long; in the middle of these tubes are connecting passages and escalators that allow tourists to travel. Six of the nine spheres are always open to visitors.",
      },
      { type: "IMG", src: I("2022/09/img_3579.jpg"), cap_ar: "أتوميوم بروكسيل", cap_en: "The Atomium, Brussels" },
      { type: "H3", noNumber: true, ar: "ما الذي يقدمه Atomium ؟", en: "What does the Atomium offer?" },
      {
        type: "P",
        ar: "في الجزء العلوي من الرمز الرئيسي لبروكسيل هناك مطعم وسطح بانورامي للمراقبة ، في أعماق الوصل يربط الأنبوب المصعد العالي السرعة الذي يسلم السياح الى الأماكن المذكورة أعلاه لمدة 23 ثانية ، من منصة المراقبة ، يفتح المنظر المذهل للعاصمة البلجيكية وضواحيها",
        en: "At the top of the main symbol of Brussels there is a restaurant and a panoramic observation deck. Deep in the connecting tube runs the high-speed lift that delivers tourists to the places mentioned above in 23 seconds, and from the observation platform a stunning view of the Belgian capital and its suburbs opens up.",
      },
      {
        type: "P",
        ar: "في مجالات Atomium هناك العديد من الفعاليات ، واحد منهم هو متحف يروي عرضه عن ذرة سلمية حول الطاقة الذرية ، حول الانجازات التي تحققت في أوقات مختلفة من بحثها ، هذا هو معرض دائم ، ومع ذلك يتم تنظيم المعارض المؤقتة بانتظام ، وتحكي الانجازات الأخرى للتقدم العلمي والتقني ، بالاضافة الى ذلك توجد مقاهي ودور سينما ومتجر للهدايا التذكارية وقاعات للحفلات الموسيقية ، هناك أيضا غرف يسمح فيها بالبقاء ليلة وضحاها للاعجاب بالرؤية الليلية",
        en: "In the spheres of the Atomium there are many attractions. One of them is a museum whose display tells of the peaceful atom, of atomic energy and of the achievements made at different times in its research; this is a permanent exhibition, though temporary exhibitions are organised regularly, telling of other achievements of scientific and technical progress. In addition there are cafés, cinemas, a souvenir shop and concert halls, and there are also rooms where you are allowed to stay overnight to admire the night-time view.",
      },
      { type: "IMG", src: I("2022/09/img_3578.jpg"), cap_ar: "أتوميوم بروكسيل", cap_en: "The Atomium, Brussels" },
      { type: "H3", noNumber: true, ar: "افضل الانشطة التي يمكن القيام بها في الأتوميوم ببروكسيل", en: "The best activities to do at the Atomium in Brussels" },
      {
        type: "LIST",
        ar: [
          "يمكنك زيارة المعرض الدائم المقام داخل واحدة من الأجسام الكروية المكونه لأتوميوم ، والمعرض خاص بتاريخ أتوميوم ذلك البناء الهام ، وأيضا يروي تاريخ المعرض الدولي اكسبو الذي أقيم عام 1958",
          "يمكنك أيضا زيارة المعرض الغير دائم والكائن أيضا باحدى تلك الأجسام الكروية ، يتغير المعرض كل عام ويتناول مجالات مختلفة في كل مرة ، كمعرض الطيران التجاري المرفه في القرن العشرين",
          "يمكنك أيضا الاستمتاع بالمطعم الكائن على قمة الكرة العليا ، والذي يتيح لك فرصة الغداء أو العشاء في منظر بانورامي رائع لمدينة بروكسل ، ويقدم المطعم أطباق متنوعة محلية وعالمية ، يمكنك الوصول الى المطعم من خلال المصعد الموجود في الأسفل",
          "ومن أعلى قمة أعلى جسم كروي من الأجسام الكروية التسع يمكنك استخدام التليسكوب لرؤية المشهد البانورامي الرائع للمدينة ، ويمكنك رؤية الكنيسة و الميناء من خلال التليسكوب",
          "بمكانك أيضا المرور بالأجسام الكروية الأخرى الخاصة بذلك البناء الفريد ، حيث يقام بها الندوات والأحداث المختلفة ويوجد أيضا مساحة مخصصة للأطفال وللأحداث والاحتفالات المدرسية",
          "يحيط الأتوميوم عدد من المقاصد السياحية الأخرى التي بامكانك المرور عليها ، على سبيل المثال الحديقة الشهيرة ذات الطابع الأوروبي والتي تسمى حديقة أوروبا المصغرة ، وأيضا يوجد حديقة مائية تحوي منزلقات وحمامات سباحة في تلك المنطقة التي تدعى هايسيل",
          "كما بامكانك زيارة الجناح الصيني والبرج الياباني وهما عبارة عن متحفين يحويان قطع من السيراميك المحلي المصنوع بأيدي أهل البلدين ، والذي كان يصدر الى أوروبا في القرون الـ 17 و18 و19",
        ],
        en: [
          "You can visit the permanent exhibition set inside one of the spheres that make up the Atomium; the exhibition is dedicated to the history of the Atomium, that important structure, and also tells the history of the Expo international fair held in 1958.",
          "You can also visit the temporary exhibition, likewise housed in one of those spheres. The exhibition changes every year and takes up different fields each time, such as the exhibition on luxury commercial aviation in the twentieth century.",
          "You can also enjoy the restaurant at the top of the highest sphere, which gives you the chance to have lunch or dinner with a wonderful panoramic view of the city of Brussels. The restaurant serves a variety of local and international dishes, and you can reach it by the lift at the bottom.",
          "And from the very top of the highest of the nine spheres you can use the telescope to see the wonderful panoramic scene of the city; through it you can see the church and the port.",
          "You can also pass through the other spheres of that unique structure, where seminars and various events are held, and there is also a space dedicated to children and to school events and celebrations.",
          "The Atomium is surrounded by a number of other tourist attractions you can visit, for example the famous European-themed park called Mini-Europe, and there is also a water park with slides and swimming pools in that area, called Heysel.",
          "You can also visit the Chinese Pavilion and the Japanese Tower, two museums holding pieces of local ceramics made by the hands of the people of both countries, which used to be exported to Europe in the 17th, 18th and 19th centuries.",
        ],
      },
      { type: "IMG", src: I("2022/09/img_3577.jpg"), cap_ar: "صور متفرقة لاتوميوم ببروكسل", cap_en: "Assorted views of the Atomium in Brussels" },
      { type: "IMG", src: I("2022/09/img_3576.jpg"), cap_ar: "صور متفرقة لاتوميوم ببروكسل", cap_en: "Assorted views of the Atomium in Brussels" },
      { type: "IMG", src: I("2022/09/img_3575.jpg"), cap_ar: "صور متفرقة لاتوميوم ببروكسل", cap_en: "Assorted views of the Atomium in Brussels" },
      { type: "IMG", src: I("2022/09/img_3574.jpg"), cap_ar: "صور متفرقة لاتوميوم ببروكسل", cap_en: "Assorted views of the Atomium in Brussels" },
      { type: "IMG", src: I("2022/09/img_3573.jpg"), cap_ar: "صور متفرقة لاتوميوم ببروكسل", cap_en: "Assorted views of the Atomium in Brussels" },
      { type: "IMG", src: I("2022/09/img_3571.jpg"), cap_ar: "صور متفرقة لاتوميوم ببروكسل", cap_en: "Assorted views of the Atomium in Brussels" },
      { type: "H3", noNumber: true, ar: "اوقات عمل وسعر تذكرة الأتوميوم ببروكسيل", en: "Opening hours and ticket price of the Atomium in Brussels" },
      {
        type: "P",
        ar: "الدخول الى الأتوميوم يوميا من الساعة 10:00 صباحا وحتى الساعة 18:00 مساء ، وأسعار الدخول 12 يورو للبالغين ، و6 يورو للاطفال",
        en: "Entry to the Atomium is daily from 10:00 in the morning until 18:00 in the evening, and the entry prices are 12 euros for adults and 6 euros for children.",
      },
    ],
  },

  {
    slug: "mini-europe",
    title_ar: "حديقة أوروبا المصغرة .. حديقة رائعة وشاملة",
    title_en: "Mini-Europe park .. a wonderful and all-embracing park",
    kicker_ar: "معالم بروكسل",
    kicker_en: "Brussels landmarks",
    image: I("2022/10/img_3605.jpg"),
    blocks: [
      {
        type: "P",
        ar: "اذا أردت رؤية جميع المعالم البارزة لقارة أوروبا في وقت واحد ، فعليك زيارة حديقة أوروبا المصغرة الواقعة في مدينة بروكسل ، اذ توفر للزوار فرصة رؤية جميع معالم أوروبا الشهيرة في مكان واحد كبرج ايفل ، وبرج بيزا المائل في ايطاليا ، وساعة بيغ بن في لندن ، وجراند بلاس في بروكسل ، وساحة الفاتيكان في روما ، وغيرها من المعالم الأوروبية الشهيرة التي يمكنك أن تكتشفها في غضون عدة ساعات وفي مكان واحد ، يوجد أزرار بجانب كل معلم اذ يمكنك أن تضغط عليها لتفاجئك بالأصوات التي تصدر منها",
        en: "If you want to see all the outstanding landmarks of the continent of Europe at once, you must visit Mini-Europe park in the city of Brussels, which gives visitors the chance to see all the famous sights of Europe in one place: the Eiffel Tower, the leaning tower of Pisa in Italy, Big Ben in London, the Grand Place in Brussels, St Peter's Square in Rome and other famous European landmarks that you can discover within a few hours in a single place. There are buttons beside every landmark which you can press to be surprised by the sounds they make.",
      },
      { type: "IMG", src: I("2022/10/img_3604.jpg"), cap_ar: "أحد نماذج حديقة اوروبا المصغرة ببروكسيل", cap_en: "One of the models in Mini-Europe park, Brussels" },
      {
        type: "P",
        ar: "أوروبا المصغرة Mini-Europe هي حديقة مصغرة تقع في برو بارك عند سفح أتوميوم الشهير ، بنيت الحديقة على مساحة 24000 متر مربع ، وذلك عام 1989 ، يوجد فيها عدة نسخ من آثار دول الاتحاد الأوروبي ، حيث يتم تمثيل ما يقرب من 80 مدينة و350 مبنى ، وبالتالي فهي تسمح لزائريها باستكشاف كامل أوروبا خلال يوم واحد ، هذا وتستقبل ميني-أوروبا 350.000 زائر سنويا الأمر الذي يجعل منها وجهة سياحية شهيرة",
        en: "Mini-Europe is a miniature park located in Bruparck at the foot of the famous Atomium. The park was built over an area of 24,000 square metres in 1989, and holds several replicas of the monuments of the European Union countries, with nearly 80 cities and 350 buildings represented, thus allowing its visitors to explore the whole of Europe in a single day. Mini-Europe receives 350,000 visitors a year, which makes it a famous tourist destination.",
      },
      { type: "IMG", src: I("2022/10/img_3603.jpg"), cap_ar: "أحد نماذج حديقة اوروبا المصغرة ببروكسيل", cap_en: "One of the models in Mini-Europe park, Brussels" },
      { type: "IMG", src: I("2022/10/img_3602.jpg"), cap_ar: "أحد نماذج حديقة اوروبا المصغرة ببروكسيل", cap_en: "One of the models in Mini-Europe park, Brussels" },
      { type: "H3", noNumber: true, ar: "أفضل الانشطة التي يمكن القيام بها في حديقة أوروبا المصغرة", en: "The best activities to do in Mini-Europe park" },
      {
        type: "P",
        ar: "يمكن الاستمتاع بالتنزه في ارجاء الحديقة والتقاط الصور مع مبنى أتوميوم والنماذج الابداعية للعواصم وزيارة المعرض التفاعلي في الحديقة بالاضافة الى حديقة بروبارك التي تضم منتزه وألعاب ومنتزه مائي مع حمامات سباحة",
        en: "You can enjoy strolling around the park and taking photographs with the Atomium building and the creative models of the capitals, and visiting the interactive exhibition in the park, in addition to Bruparck, which holds a leisure park with rides and a water park with swimming pools.",
      },
      {
        type: "P",
        ar: "لأن الحديقة تضم عددا كبيرا من أشهر معالم القارة الأوروبية فان مجرد زيارتك وتجولك داخل الحديقة سيجعلك تشعر وكأنك تتجول في أوروبا كلها ولكن في مكان واحد ، لذا خذ وقتك بالاستمتاع بكل ذلك",
        en: "Because the park holds a large number of the most famous landmarks of the European continent, simply visiting and walking around inside it will make you feel as if you are touring the whole of Europe but in one place, so take your time enjoying all of it.",
      },
      {
        type: "P",
        ar: "تقع أوروبا الصغيرة في حديقة تدعى بروبارك وتحوي تلك الحديقة على متنزه للألعاب ، ومتنزه مائي يوجد به حمامات سباحة ومنزلقات مائية ، كما يحوي مبنى الأتوميوم الشهير الذي يعد من معالم بروكسيل ، لذلك يمكنك الاستمتاع بكل هذه المعالم والأماكن الترفيهيه الى جانب زيارتك لحديقة أوروبا الصغيرة",
        en: "Mini-Europe lies in a park called Bruparck, which holds an amusement park and a water park with swimming pools and water slides, and also holds the famous Atomium building, one of the landmarks of Brussels. So you can enjoy all these landmarks and leisure places alongside your visit to Mini-Europe.",
      },
      { type: "IMG", src: I("2022/10/img_3601.jpg"), cap_ar: "أحد نماذج حديقة اوروبا المصغرة ببروكسيل", cap_en: "One of the models in Mini-Europe park, Brussels" },
      {
        type: "P",
        ar: "تضم ميني – اوروبا نماذجا مصغرة لغالبية المعالم الجذابة والشهيرة في الدول الأوروبية ، بحيث يبدو كل معلم مصغرا 25 مرة وأكثر عن حجمه الطبيعي ، وتشتهر هذه النماذج رغم حجمها الصغير بدقة بالغة تظهر في الاعتناء بأدق التفاصيل الدقيقة ، حتى أن نموذج كاتدرائية سانتياغو دي كومبوستيلا في أسبانيا استغرق 24 ألف ساعة من العمل ، وبلغت تكلفة بعضها الى 350 ألف يورو ، وصنعت النماذج باستخدام السليكون والايبوكسي والبوليستر ، وان كانت بعض النماذج تحتاج تكنولوجيا معقدة فيتم استخدام الكمبيوتر في بعض الحالات",
        en: "Mini-Europe holds miniature models of most of the attractive and famous landmarks in the European countries, each one appearing 25 times or more smaller than its natural size. Despite their small size these models are famous for their extreme precision, seen in the care given to the finest details: the model of the cathedral of Santiago de Compostela in Spain took 24 thousand hours of work, and the cost of some of them reached 350 thousand euros. The models were made using silicone, epoxy and polyester, and where some of them required complex technology, computers were used in certain cases.",
      },
      { type: "IMG", src: I("2022/10/img_3599.jpg"), cap_ar: "أحد نماذج حديقة اوروبا المصغرة ببروكسيل", cap_en: "One of the models in Mini-Europe park, Brussels" },
      {
        type: "P",
        ar: "توفر عليك هذه الحديقة رحلة الى 80 مدينة أوروبية ، ففي أربع ساعات فقط وفي مكان واحد يمكنك الوقوف وجها لوجه مع ساعة بيج بن في قلب لندن ، تنتقل بعدها الى الجندول المائي الذي يخترق شوارع مدينة البندقية الايطالية ، ومنها الى روعة برج ايفل في فرنسا ، ومنها الى برج بيزا الايطالي ، ثم الطواحين Kinderdijk الهولندية ، وجسر Adolphe في لوكسمبورج ، ونموذج لجدار برلين وبوابة براندنبورج من ألمانيا ، وغيره من 350 نموذج ، ومولت كثير من الدول الأوروبية المعالم التي تخصها في الحديقة",
        en: "This park saves you a journey to 80 European cities: in just four hours and in one place you can stand face to face with Big Ben in the heart of London, then move on to the gondola crossing the streets of Venice in Italy, and from there to the splendour of the Eiffel Tower in France, then the leaning tower of Pisa, then the Kinderdijk windmills of the Netherlands, the Adolphe bridge in Luxembourg, a model of the Berlin Wall and the Brandenburg Gate from Germany, and others among the 350 models. Many European countries financed the landmarks that belong to them in the park.",
      },
      { type: "IMG", src: I("2022/10/img_3598.jpg"), cap_ar: "حديقة أوروبا المصغرة ببروكسيل من الاعلى", cap_en: "Mini-Europe park in Brussels from above" },
      {
        type: "P",
        ar: "تم اختيار بعض النماذج بعناية من أجل اضافة حيوية لحديقة mini Europe ، فعلي سبيل المثال يعيش السياح جوا صاخبا على أصوات قطار Thalys الذي يخترق فرنسا من أولها لآخرها ، وبعد قليل نلاحظ ثوران بركان فيزوف Vesuvius ثم صوت المطاحن الهولندية والصوت المصاحب لسقوط جدار برلين وصيحات الثيران في اشبيلية ، كل ذلك يضيف حيوية للحديقة ، مما يجعل السائح يقف أمامها مندهشا من جمالها وجمال المحاكاة",
        en: "Some models were chosen carefully in order to add liveliness to Mini-Europe: for example, visitors experience a bustling atmosphere with the sounds of the Thalys train crossing France from end to end, and a little later we notice the eruption of Vesuvius, then the sound of the Dutch windmills, the sound accompanying the fall of the Berlin Wall, and the cries of the bulls in Seville. All of this adds vitality to the park, leaving the visitor standing before it amazed at its beauty and the beauty of the simulation.",
      },
      {
        type: "P",
        ar: "وفي نهاية الجولة يتم دخول مكان مخصص للعرض التفاعلي يطلق عليه روح أوروبا Spirit of Europe ، الذي يعرض فيه تاريخ أوروبا بشكل كامل باستخدام وسائل جديدة جذابة ، حيث يتم عرض التاريخ بواسطة ألعاب الوسائط المتعددة",
        en: "At the end of the tour you enter a place dedicated to the interactive display called the Spirit of Europe, where the history of Europe is presented in full using new and attractive means, with history displayed through multimedia games.",
      },
      { type: "IMG", src: I("2022/10/img_3600.jpg"), cap_ar: "صور متفرقة لحديقة أوروبا المصغرة ببروكسيل", cap_en: "Assorted views of Mini-Europe park in Brussels" },
      { type: "IMG", src: I("2022/10/img_3597.jpg"), cap_ar: "صور متفرقة لحديقة أوروبا المصغرة ببروكسيل", cap_en: "Assorted views of Mini-Europe park in Brussels" },
      { type: "IMG", src: I("2022/10/img_3596.jpg"), cap_ar: "صور متفرقة لحديقة أوروبا المصغرة ببروكسيل", cap_en: "Assorted views of Mini-Europe park in Brussels" },
      { type: "IMG", src: I("2022/10/img_3595.jpg"), cap_ar: "صور متفرقة لحديقة أوروبا المصغرة ببروكسيل", cap_en: "Assorted views of Mini-Europe park in Brussels" },
      { type: "H3", noNumber: true, ar: "أوقات عمل واسعار تذاكر حديقة اوروبا المصغرة ببروكسيل", en: "Opening hours and ticket prices of Mini-Europe park in Brussels" },
      {
        type: "P",
        ar: "تذكرة دخول حديقة Mini Eourope أو أوروبا المصغرة 13.50 يورو للكبار ، و10 يورو للأطفال ، وتفتح الحديقة أبوابها من الساعة 09:30 صباحا وحتى الساعة 06:00 مساء ، وفي الصيف تقدم عرض أوروبا الصغيرة ليلا ويستمر حتى منتصف الليل ويشمل عرض للألعاب النارية",
        en: "The entry ticket for Mini-Europe park is 13.50 euros for adults and 10 euros for children, and the park opens its doors from 09:30 in the morning until 06:00 in the evening. In summer it presents the Mini-Europe by night show, which continues until midnight and includes a fireworks display.",
      },
    ],
  },
];
