import type { Guide } from "./france-guides";
import bigBenAsset from "@/assets/big-ben.png.asset.json";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

// Deep-dive "read more" pages linked from the London city article.
export const londonLandmarkGuides: Guide[] = [
  {
    slug: "big-ben",
    title_ar: "ساعة بيغ بن .. رمز الثقافة البريطانية",
    title_en: "Big Ben — a symbol of British culture",
    kicker_ar: "معلم",
    kicker_en: "Landmark",
    image: bigBenAsset.url,
    blocks: [
      {
        type: "P",
        ar: "ساعة بيغ بن الشهيرة في لندن بدأ عملها 3 يونيو عام 1859 ، وبيغ بن اسم الجرس العظيم الذي يدق على مدار الساعة ، ويقع في الطرف الشمالي من قصر وستمنستر في لندن وعادة ما يمتد ليشير الى كل من الساعة وبرج الساعة أيضا ، ويعرف البرج رسميا باسم برج اليزابيث ، سمي بذلك أثناء الاحتفال باليوبيل الماسي للملكة اليزابيث الثانية في عام 2012 ، وكان يعرف قبل ذلك ببرج الساعة",
        en: "London's famous Big Ben began working on 3 June 1859. Big Ben is the name of the great bell that strikes around the clock; it stands at the northern end of the Palace of Westminster in London, and the name is usually extended to the clock and the clock tower as well. The tower is officially called the Elizabeth Tower, named during the Diamond Jubilee celebrations of Queen Elizabeth II in 2012; before that it was known simply as the Clock Tower.",
      },
      {
        type: "P",
        ar: "وأصبحت الساعة رمزا ثقافيا للمملكة المتحدة ، ولا سيما في وسائط الاعلام المرئية ، فعندما يرغب التلفزيون أو صانعو الأفلام في الاشارة الى موقع عام في البلاد ، فان الطريقة الشائعة للقيام بذلك هي اظهار صورة للبرج ، وغالبا ما يكون مع حافلة حمراء ذات طابقين أو سيارة أجرة سوداء في المقدمة",
        en: "The clock has become a cultural symbol of the United Kingdom, especially in visual media: when television or film-makers want to signal a general location in the country, the common way of doing it is to show a picture of the tower, often with a red double-decker bus or a black cab in the foreground.",
      },
      {
        type: "P",
        ar: "في عام 2008 وجد استطلاع لـ 2,000 شخص أن البرج كان المعلم الأكثر شعبية في المملكة المتحدة ، وتم أيضا استخدام صوته كاشارة لضبط الوقت في بعض الاذاعات مثل BBC وهي ممارسة بدأت في 31 ديسمبر 1923 من الميكروفونات المثبتة بشكل دائم في البرج وتوصيلها عن طريق الخط الى البث الحي ، ويعتبر محور احتفالات السنة الجديدة في المملكة المتحدة مع محطات الاذاعة والتلفزيون التي تنقل دقاته للترحيب ببداية السنة الجديدة",
        en: "In 2008 a survey of 2,000 people found the tower to be the most popular landmark in the United Kingdom. Its sound has also been used as a time signal by broadcasters such as the BBC — a practice that began on 31 December 1923, from microphones permanently installed in the tower and connected by line to the live broadcast. It is the centrepiece of New Year celebrations in the UK, with radio and television stations carrying its chimes to welcome in the new year.",
      },
      { type: "IMG", src: U("2022/09/img_2673.jpg"), cap_ar: "جرس ساعة بيغ بن من الداخل", cap_en: "The bell of Big Ben from the inside" },
      {
        type: "P",
        ar: "يبلغ ارتفاع البرج الذي يحمل الساعة والمؤلف من 16 طابقا حوالي 96 مترا ، وهو مبني على نمط الحضارة القوطية الحديثة الذي استخدم في بناء العديد من المباني التاريخية في انجلترا",
        en: "The tower carrying the clock has 16 floors and rises about 96 metres. It is built in the Gothic Revival style used for many historic buildings in England.",
      },
      { type: "IMG", src: U("2022/09/img_2674.jpg"), cap_ar: "ساعة بيغ بن كما تبدو بروعتها المعهودة", cap_en: "Big Ben in its familiar splendour" },
      {
        type: "P",
        ar: "يضم برج ساعة بيغ بن من الداخل متحفا صغيرا وجرس الساعة الواقع في قمة البرج ، حيث يزن الأخير حوالي 13 طنا ، أما فيما يخص الساعة نفسها فان طول عقربها الصغير يبلغ 9 أقدام فيما يبلغ طول عقربها الأكبر 14 قدما ، وهناك العديد من الأماكن السياحية التي يمكن زيارتها بالقرب من ساعة بيغ بن ومن ضمنها قصر وستمنستر الشهير ، كما تتواجد العديد من المطاعم الجيدة على بعد خطوات من الساعة",
        en: "Inside, the tower holds a small museum and the clock bell at its summit, which weighs about 13 tonnes. As for the clock itself, the shorter hand is 9 feet long and the longer one 14 feet. There are many sights to visit near Big Ben, including the famous Palace of Westminster, and several good restaurants stand only steps away.",
      },
      { type: "IMG", src: U("2022/09/img_2623-1.jpg"), cap_ar: "صورة توضح روعة ساعة بيغ بن وقربها من قصر وستمنستر بلندن", cap_en: "Big Ben and its closeness to the Palace of Westminster" },
      { type: "IMG", src: U("2022/09/image-3.jpg"), cap_ar: "ساعة بيغ بن", cap_en: "Big Ben" },
      { type: "H3", ar: "معلومات متفرقة عن ساعة بيغ بن بلندن", en: "Assorted facts about Big Ben", noNumber: true },
      {
        type: "LIST",
        ar: [
          "ساعة بيغ بن أشهر ساعات العالم وأشهر معالم لندن على الاطلاق ، رن جرسها الشهير للمرة الأولى في 3 يونيو عام 1859",
          "البرج الذي تتخذ الساعة مكانها فيه كان يطلق عليه حتى عام 2012 برج الساعة ، لكن الاسم الرسمي له حاليا هو برج اليزابيث ، وأطلق عام 2012 بمناسبة اليوبيل الماسي لتولي الملكة اليزابيث الثانية عرش بريطانيا",
          "تقع ساعة بيغ بن على الجانب الغربي من قصر وستمنستر ، وهو مقر البرلمان البريطاني ويعتبر أكبر مبنى برلماني في العالم ، والقصر التاريخي الذي أنشئ عام 1600 دمر عام 1834 بسبب حريق هائل وأعيد بناؤه واستغرق الأمر 30 عاما ، ومع البناء تم بناء البرج وساعة بيغ بن",
          "وراء اطلاق تسمية بيغ بن على الساعة الشهيرة العديد من النظريات ، لكن النظرية الأكثر رواجا أن الساعة أطلق عليها بيغ بن نسبة لأكبر جرس فيها ويزن 13.7 طنا ويبلغ قطره 2.7 متر ، وفي الساعة أربعة أجراس أخرى أصغر",
          "بعد شهرين فقط من دخول الساعة الخدمة عام 1859 أصيب الجرس العملاق بالتصدع بسبب المطرقة المرافقة له والتي كانت بوزنه تقريبا ، وبعد حدوث الضرر تم تركيب مطرقة أخف وزنا ، لكن التصدع ما زال موجودا على الجرس حتى الآن",
          "يدق جرس بيغ بن كل 15 دقيقة ويمكن سماعه على بعد 5 أميال ، وقد توقف عن الرنين مرات قليلة ، منها توقفه عام 1941 أثناء غارة ألمانية على لندن حيث سقطت المطرقة وتوقف الجرس لمدة 21 ساعة ، كما توقف عام 1965 بسبب جنازة رئيس الوزراء البريطاني الراحل تشرشل ، وكذلك عام 2013 أثناء جنازة رئيسة الوزراء مارغريت تاتشر ، وتوقف عدة مرات من أجل الصيانة",
          "الساعة التي تعد الأدق في العالم تعد تحفة معمارية ، ووجوه الساعة الأربعة مصنوعة من 312 قطعة من الزجاج العقيق ، كما تشتمل الساعة على 1284 قطعة فردية من الزجاج الهش للغاية ، ويتم عمل صيانة دقيقة للساعة كل 5 سنوات ، كما يوجد فريق كامل يقوم بتنظيف كل شبر فيها وتلميعه على مدار الساعة",
        ],
        en: [
          "Big Ben is the most famous clock in the world and London's best-known landmark; its famous bell first rang on 3 June 1859.",
          "Until 2012 the tower housing the clock was called the Clock Tower; its official name today is the Elizabeth Tower, given in 2012 to mark the Diamond Jubilee of Queen Elizabeth II.",
          "Big Ben stands on the western side of the Palace of Westminster, the seat of the British Parliament and the largest parliamentary building in the world. The historic palace, established in 1600, was destroyed by a huge fire in 1834 and rebuilt over 30 years; the tower and Big Ben were built along with it.",
          "Many theories surround the name Big Ben, but the most widespread is that the clock took its name from its largest bell, which weighs 13.7 tonnes and measures 2.7 metres across. The clock has four other, smaller bells.",
          "Only two months after the clock entered service in 1859 the giant bell cracked because of its hammer, which weighed almost as much as the bell itself. A lighter hammer was fitted after the damage, but the crack is still there today.",
          "Big Ben strikes every 15 minutes and can be heard 5 miles away. It has fallen silent only a few times: in 1941 during a German raid on London, when the hammer fell and the bell stopped for 21 hours; in 1965 for the funeral of Winston Churchill; and in 2013 for the funeral of Margaret Thatcher — as well as several times for maintenance.",
          "Reckoned the most accurate clock in the world, it is also an architectural masterpiece. Its four faces are made of 312 pieces of opal glass, and the clock contains 1,284 individual pieces of extremely fragile glass. It receives meticulous maintenance every five years, and a full team cleans and polishes every inch of it round the clock.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_2676.jpg"), cap_ar: "صورة لساعة بيغ بن أثناء الصيانة الدورية لها", cap_en: "Big Ben during routine maintenance" },
      { type: "IMG", src: U("2022/09/img_2678.jpg"), cap_ar: "المباني المجاورة لساعة بيغ بن", cap_en: "The buildings beside Big Ben" },
    ],
  },
  {
    slug: "tower-of-london",
    title_ar: "برج لندن .. قلعة تاريخية عريقة",
    title_en: "The Tower of London — an ancient fortress",
    kicker_ar: "معلم",
    kicker_en: "Landmark",
    image: U("2022/09/img_2662.jpg"),
    blocks: [
      {
        type: "P",
        ar: "برج لندن Tower of London ، ورسميا قصر وقلعة صاحبة الجلالة ، قلعة تاريخية على الضفة الشمالية لنهر التايمز في قلب لندن ، بني برج لندن في أواخر عام 1066 كجزء من غزو النورمان لانجلترا ، وفي عام 1078 أمر ويليام الفاتح ببناء البرج الأبيض الذي أصبح رمزا لقهر الأسرة الحاكمة الجديدة لأعدائهم في لندن",
        en: "The Tower of London, officially Her Majesty's Palace and Fortress, is a historic castle on the northern bank of the Thames in the heart of London. It was built in late 1066 as part of the Norman conquest of England, and in 1078 William the Conqueror ordered the construction of the White Tower, which became a symbol of the new ruling house's dominance over its enemies in London.",
      },
      {
        type: "P",
        ar: "وبحلول عام 1100 استخدمت القلعة كسجن ، بالرغم من أنه لم يكن الهدف الأساسي من بنائها ، واستخدم هذا القصر الكبير قديما كمقر للاقامة الملكية ، وبصفة عامة فالبرج تجمع لعدة مبان داخل حلقتين من الجدران الدفاعية وخندق مائي ، وأجريت عدة توسعات للبرج لا سيما في عهد الملوك ريتشارد قلب الأسد وهنري الثالث وادوارد الأول في القرنين الثاني عشر والثالث عشر ، كما استقرت حدود البرج على وضعها الحالي منذ أواخر القرن الثالث عشر مع بعض التحسينات اللاحقة",
        en: "By 1100 the castle was being used as a prison, though that was not the purpose for which it was built, and this great palace once served as a royal residence. Broadly, the Tower is a cluster of buildings inside two rings of defensive walls and a moat. Several expansions were carried out, especially under Richard the Lionheart, Henry III and Edward I in the twelfth and thirteenth centuries, and the boundaries of the Tower have been settled in their present form since the late thirteenth century, with some later improvements.",
      },
      { type: "IMG", src: U("2022/09/img_2657.jpg"), cap_ar: "مشهد لبرج لندن من نهر التايمز وتظهر فيه البوابة المائية الشهيرة باسم بوابة الخونة", cap_en: "The Tower from the Thames, showing the water gate known as Traitors' Gate" },
      {
        type: "P",
        ar: "لعب برج لندن دورا بارزا في التاريخ الانجليزي ، فقد تعرض للحصار عدة مرات ، كما كانت السيطرة عليه أولى الخطوات للسيطرة على البلاد ، واستخدم البرج كمستودع لحفظ الأموال والأسلحة والحيوانات ، وكدار لصك العملة ولحفظ السجلات العامة ، وكمقر لحفظ الكنوز الملكية ، ومنذ أوائل القرن الرابع عشر وحتى تشارلز الثاني كان موكب التتويج يبدأ من البرج وحتى دير وستمنستر",
        en: "The Tower played a prominent role in English history: it was besieged several times, and taking it was the first step towards controlling the country. It served as a store for money, weapons and animals, as a mint, as a repository of public records and as the home of the royal treasures. From the early fourteenth century until Charles II the coronation procession set out from the Tower to Westminster Abbey.",
      },
      {
        type: "P",
        ar: "وفي عهد أسرة تيودور قل استخدام البرج كمقر للاقامة الملكية ، على الرغم من محاولات تقويته واصلاح دفاعاته لتقاوم القصف بالمدفعية ، وكانت فترة ذروة استخدامه كسجن في القرنين السادس عشر والسابع عشر ، حيث سجن به العديد من الشخصيات أشهرهم اليزابيث الأولى قبل أن تصبح ملكة ، وأصبحت عبارة أرسل الى البرج كناية عن أن الشخص سيتعرض للتعذيب والموت",
        en: "Under the Tudors the Tower was used less as a royal residence, despite attempts to strengthen it and repair its defences against artillery. Its peak as a prison came in the sixteenth and seventeenth centuries, when many figures were held there — most famously Elizabeth I before she became queen — and the phrase 'sent to the Tower' came to mean that a person would face torture and death.",
      },
      {
        type: "P",
        ar: "وفي النصف الأخير من القرن التاسع عشر انتقلت مؤسسات مثل دار صك العملة الملكية الى خارج البرج لتترك العديد من المباني فارغة ، فاستغل المهندسان أنتوني سالفين وجون تايلور الفرصة لاعادة البرج لما كان عليه في العصور الوسطى وازالة العديد من المباني الشاغرة التي بنيت في مرحلة ما بعد القرون الوسطى ، وأثناء الحربين العالميتين الأولى والثانية استخدم البرج مرة أخرى كسجن وشهد اعدام 12 رجلا بتهمة التجسس ، وبعد الحربين أعيد ترميم الأضرار التي سببتها الغارات وأعيد فتح البرج للجمهور",
        en: "In the later nineteenth century institutions such as the Royal Mint moved out of the Tower, leaving many buildings empty. The architects Anthony Salvin and John Taylor took the chance to restore the Tower to its medieval appearance, removing many vacant post-medieval structures. During both World Wars the Tower was again used as a prison and saw twelve men executed for espionage; afterwards the damage from air raids was repaired and the Tower reopened to the public.",
      },
      {
        type: "P",
        ar: "اليوم يعد برج لندن واحدا من أكثر مناطق الجذب السياحي في انجلترا شعبية ، كما أضيف الى مواقع التراث العالمي في عام 1988 ، ويأتي في مقدمة الأماكن التي يزعم أنها مسكونة بالأشباح في انجلترا وكامل الجزر البريطانية ، وقد تناقلت الأجيال قصصا مفادها أن أرواح أولئك الذين أعدموا في البرج لا تزال تطوفه ومن أبرزهم آن بولين الزوجة الثانية للملك هنري الثامن ، كما اشتهر البرج بغربانه التي تعشش على أراضيه والتي ارتبطت بنبوءة قديمة مفادها أنه في اليوم الذي سيغادر فيه آخر الغربان برج لندن فان عرش انجلترا سيسقط ومعه ستسقط بريطانيا العظمى ، لذلك حرص عدد من الملوك قديما على الحفاظ على الغربان وأراضي تعشيشها في البرج",
        en: "Today the Tower of London is one of the most popular attractions in England and was added to the World Heritage list in 1988. It also tops the list of places said to be haunted in England and across the British Isles: generations have passed down tales that the spirits of those executed there still roam it, most notably Anne Boleyn, the second wife of Henry VIII. The Tower is also famous for the ravens that nest in its grounds, tied to an old prophecy that on the day the last raven leaves the Tower the throne of England will fall and Great Britain with it — which is why a number of monarchs took care to protect the ravens and their nesting grounds.",
      },
      { type: "IMG", src: U("2022/09/img_2658.jpg"), cap_ar: "الواجهة الجنوبية لثكنات ووترلو", cap_en: "The south front of the Waterloo Barracks" },
      {
        type: "P",
        ar: "صمم البرج بحيث تواجه أقوى تحصيناته وأعظمها القسم الساكسوني من لندن عمدا ، وتتألف القلعة من ثلاثة أجنحة ، الجناح الأعمق يحتوي على البرج الأبيض وهو أقدم مباني القلعة ، يلتف حوله شمالا وشرقا وغربا الجناح الداخلي الذي بني في عهد ريتشارد قلب الأسد ، وأخيرا هناك الجناح الخارجي الذي يحيط بالقلعة والذي بني في عهد ادوارد الأول ، وقد ثبتت حدود البرج بعد اكتمال البناء في عهد ادوارد الأول في عام 1285 ، ومساحة القلعة 12 آكرا تقريبا بالاضافة الى 6 آكرات حول البرج تمثل حرم برج لندن",
        en: "The Tower was deliberately designed so that its strongest and greatest fortifications faced the Saxon part of London. The castle consists of three wards: the innermost holds the White Tower, the oldest building of the castle, wrapped to the north, east and west by the inner ward built under Richard the Lionheart; and finally the outer ward that encircles the castle, built under Edward I. The boundaries were fixed when building was completed under Edward I in 1285. The castle covers about 12 acres, with a further 6 acres around it forming the Tower Liberties.",
      },
      {
        type: "P",
        ar: "كانت بداية تكوين منطقة الحرم في القرن الثالث عشر عندما أمر الملك هنري الثالث باخلاء شريط من الأراضي المجاورة للقلعة ، وعلى الرغم من ما هو شائع شعبيا فانه لم تكن هناك غرفة تعذيب أبدا في برج لندن ، على الرغم من أن الطابق السفلي من البرج الأبيض كان يضم أدوات للتعذيب في فترات لاحقة ، وقد بني مرفأ على ضفة نهر التايمز في عهد ادوارد الأول ثم تمت توسعته الى حجمه الحالي في عهد ريتشارد الثاني",
        en: "The Liberties began to take shape in the thirteenth century, when Henry III ordered a strip of land beside the castle to be cleared. Contrary to popular belief there was never a torture chamber in the Tower of London, although the lower floor of the White Tower did hold instruments of torture in later periods. A wharf was built on the bank of the Thames under Edward I and later expanded to its present size under Richard II.",
      },
      { type: "IMG", src: U("2022/09/img_2660.jpg"), cap_ar: "صورة للبرج على نهر التايمز يظهر بها جسر برج لندن", cap_en: "The Tower on the Thames, with Tower Bridge behind" },
      { type: "H3", ar: "أفضل الأنشطة التي يمكن القيام بها في برج لندن", en: "The best things to do at the Tower of London", noNumber: true },
      {
        type: "LIST",
        ar: [
          "يتألف لندن تاور من 3 أقسام رئيسية ، يمكنكم زيارة البرج الأبيض ويعتبر أقدم المباني في قلعة لندن ، ويحيط به الجناح الداخلي الذي يعود تاريخه الى عهد الملك ريتشارد الملقب بقلب الأسد",
          "أما القسم الثالث فهو الجناح الخارجي والذي يحيط بقلعة لندن من كافة أطرافها",
          "يمكنكم مشاهدة العديد من الآثار في برج لندن مثل الأسلحة والدروع الملكية التي تعود للأسر الملكية التي حكمت انجلترا",
          "يمكنكم الاستمتاع بالاطلالة التي يوفرها لندن تاور على مدينة لندن ، حيث يعتبر المكان الأمثل لالتقاط أجمل الصور التذكارية",
          "يمكنكم بعد الانتهاء من جولتكم في برج لندن زيارة جسر البرج ، حيث يبعد عن البرج مسافة قصيرة مشيا على الأقدام",
        ],
        en: [
          "The Tower has three main parts: you can visit the White Tower, the oldest building in the castle, surrounded by the inner ward dating from the reign of Richard the Lionheart.",
          "The third part is the outer ward, which encircles the castle on every side.",
          "You can see many relics inside the Tower, such as the royal arms and armour belonging to the houses that ruled England.",
          "Enjoy the views the Tower offers over London — it is the perfect place for memorable photographs.",
          "After finishing your tour of the Tower, visit Tower Bridge, a short walk away.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_2663.jpg"), cap_ar: "سطح تلة برج لندن المرصوف حيث أعدم 112 شخصا على مدى 400 عام", cap_en: "Tower Hill, where 112 people were executed over 400 years" },
      { type: "H3", ar: "سعر تذاكر وأوقات دخول برج لندن", en: "Tickets and opening hours", noNumber: true },
      {
        type: "P",
        ar: "مفتوح من الثلاثاء الى السبت من الساعة 09:00 صباحا الى الساعة 04:30 مساء ، ويومي الأحد والاثنين من الساعة 10:00 صباحا الى الساعة 04:30 مساء ، وأسعار التذاكر للبالغين 21.5 جنيه استرليني وللأطفال 9.70 جنيه استرليني",
        en: "Open Tuesday to Saturday from 09:00 to 16:30, and on Sunday and Monday from 10:00 to 16:30. Tickets cost £21.5 for adults and £9.70 for children.",
      },
      { type: "IMG", src: U("2022/09/img_2665.jpg"), cap_ar: "المدخل الرئيسي لبرج لندن", cap_en: "The main entrance to the Tower of London" },
    ],
    gallery: [
      "2022/09/img_2670.jpg",
      "2022/09/img_2669.jpg",
      "2022/09/img_2668.jpg",
      "2022/09/img_2667.jpg",
      "2022/09/img_2666.jpg",
      "2022/09/img_2664.jpg",
      "2022/09/img_2661.jpg",
      "2022/09/img_2659.jpg",
    ].map((n) => ({ src: U(n), cap_ar: "برج لندن", cap_en: "The Tower of London" })),
  },
  {
    slug: "westminster-palace",
    title_ar: "قصر ويستمنستر .. بيت البرلمان البريطاني",
    title_en: "The Palace of Westminster — home of Parliament",
    kicker_ar: "معلم",
    kicker_en: "Landmark",
    image: U("2022/09/img_2623.jpg"),
    blocks: [
      {
        type: "P",
        ar: "قصر وستمنستر Palace of Westminster ، ومعروف أيضا باسم بيوت البرلمان ، في مدينة وستمنستر في لندن بالمملكة المتحدة ، هو القصر الذي يجتمع فيه أعضاء البرلمان البريطاني ، والقصر واحد من أكبر مباني البرلمانات في العالم",
        en: "The Palace of Westminster, also widely known as the Houses of Parliament, stands in the City of Westminster in London and is where the members of the British Parliament meet. It is one of the largest parliamentary buildings in the world.",
      },
      {
        type: "P",
        ar: "مخطط القصر معقد جدا ، ويحتوي على ما يقرب من 1200 غرفة مع الأخذ بالحسبان المباني القائمة فيه ، اضافة الى 100 سلم وأكثر من ثلاثة كيلومترات من الممرات ويعود تاريخها الى القرن التاسع عشر ، وفيه قاعة وستمنستر التي تعتبر من المباني التاريخية وتستخدم في الوقت الحاضر للاحتفالات العامة الرئيسية",
        en: "The palace's plan is highly complex, with nearly 1,200 rooms counting all its buildings, along with 100 staircases and more than three kilometres of corridors dating from the nineteenth century. It contains Westminster Hall, a historic building now used for major public ceremonies.",
      },
      {
        type: "P",
        ar: "البرلمان ذو مجلسين ، المجلس الأعلى الممثل بمجلس اللوردات ومجلس سفلي ممثل بمجلس العموم ، ومجلس اللوردات يحتوي على نوعين من الأعضاء ، اللوردات الروحيون الممثلون بأعلى أساقفة كنيسة انكلترا واللوردات الدنيويون الممثلون بالنبلاء ، وأعضاؤه لا يتم انتخابهم من قبل عامة الشعب ولكن يتم تعيينهم ، أما مجلس العموم فهو منتخب ديمقراطيا مع انتخابات تقام كل خمس سنوات على الأقل ، والمجلسان يجتمعان في غرف مفصولة في قصر وستمنستر",
        en: "Parliament is bicameral: an upper house represented by the House of Lords and a lower house represented by the House of Commons. The Lords has two kinds of member — the Lords Spiritual, the senior bishops of the Church of England, and the Lords Temporal, the nobility — and its members are appointed rather than elected by the public. The Commons is democratically elected, with elections held at least every five years. The two houses meet in separate chambers within the palace.",
      },
      { type: "IMG", src: U("2022/09/img_2624.jpg"), cap_ar: "صورة لقصر ويستمنستر من الأعلى", cap_en: "The Palace of Westminster from above" },
      {
        type: "P",
        ar: "يقع قصر وستمنستر على ضفة ميدلسكس من نهر التايمز في مدينة ويستمنستر في وسط لندن ، واسمه مستمد من كنيسة وستمنستر المجاورة ، وقد يشير الى أي من هيكلين ، القصر القديم وهو مجمع بناء من القرون الوسطى دمرته النيران في عام 1834 ، والقصر الجديد الذي يقف اليوم ، والقصر يحتفظ باسلوبه الأصلي ووضعه باعتباره مقرا ملكيا",
        en: "The palace lies on the Middlesex bank of the Thames in the City of Westminster, in central London, and takes its name from the neighbouring Westminster Abbey. The name may refer to either of two structures: the old palace, a medieval complex destroyed by fire in 1834, and the new palace that stands today. The palace retains its original style and its status as a royal residence.",
      },
      {
        type: "P",
        ar: "تم بناء القصر الملكي الأول على الموقع في القرن الحادي عشر ، وكان وستمنستر مقر الاقامة الأساسي لملوك انجلترا حتى حريق دمر جزءا كبيرا من المجمع في عام 1512 ، وفي عام 1834 وقع أكبر حريق دمر مباني البرلمان التي أعيد بناؤها بشكل كبير ، وكانت الهياكل التي بقيت ذات أهمية ومنها قاعة وستمنستر ودير القديس ستيفن وكنيسة سانت ماري وبرج الجوهرة",
        en: "The first royal palace was built on the site in the eleventh century, and Westminster was the primary residence of England's monarchs until a fire destroyed much of the complex in 1512. In 1834 a far larger fire destroyed the parliamentary buildings, which were then largely rebuilt; the surviving structures were significant ones, including Westminster Hall, St Stephen's Chapel, St Mary's Chapel and the Jewel Tower.",
      },
      {
        type: "P",
        ar: "وقد تم اعادة بناء القصر من قبل المهندس المعماري تشارلز باري بتصميم على الطراز القوطي العمودي ، ويحتوي على أكثر من 1,100 غرفة نظمت بشكل متناظر حول سلسلتين من الساحات ، وقد استصلح جزء من مساحة القصر الجديد من نهر التايمز لتصبح واجهته الرئيسية المطلة على النهر بطول 266 مترا ، وساعد باري المعماري أوغسطس بوجن وهو من رواد العمارة القوطية الذي قدم تصاميم الزخرفة والأثاث للقصر",
        en: "The palace was rebuilt by the architect Charles Barry to a Perpendicular Gothic design, and contains more than 1,100 rooms arranged symmetrically around two series of courtyards. Part of the new palace's ground was reclaimed from the Thames so that its main river frontage runs 266 metres. Barry was assisted by Augustus Pugin, a leading figure in Gothic architecture, who provided designs for the palace's decoration and furniture.",
      },
      { type: "IMG", src: U("2022/09/img_2629.jpg"), cap_ar: "أحد قاعات قصر ويستمنستر بلندن", cap_en: "One of the halls inside the Palace of Westminster" },
      {
        type: "P",
        ar: "بدأ البناء في عام 1840 واستمر لمدة ثلاثين عاما ، وقد عانى من التأخير الكبير وتجاوز التكاليف فضلا عن وفاة كل من المهندسين المعماريين ، واستمر العمل من أجل الديكور الداخلي بشكل متقطع في القرن العشرين ، وقد نفذت أعمال صيانة رئيسية لعكس آثار تلوث الهواء في لندن ، ووقعت اصلاحات واسعة النطاق بعد الحرب العالمية الثانية بما في ذلك اعادة بناء غرفة العموم بعد قصفها في عام 1941",
        en: "Construction began in 1840 and lasted thirty years, suffering major delays and cost overruns as well as the deaths of both architects. Work on the interiors continued intermittently through the twentieth century, and major maintenance has been carried out to reverse the effects of London's air pollution. Extensive repairs followed the Second World War, including the rebuilding of the Commons chamber after it was bombed in 1941.",
      },
      {
        type: "P",
        ar: "القصر واحد من مراكز الحياة السياسية في المملكة المتحدة ، وقد أصبح ويستمنستر يرمز لبرلمان المملكة المتحدة كما اتخذ نظام وستمنستر للحكومة اسمه بعد ذلك ، وبرج اليزابيث على وجه الخصوص والذي غالبا ما يشار اليه باسم جرسه الرئيسي بيغ بن هو المعلم المميز والفريد في لندن والمملكة المتحدة بشكل عام ، وواحد من مناطق الجذب السياحي الأكثر شعبية في المدينة وشعار للديمقراطية البرلمانية ، وكان قصر وستمنستر في الصف الأول للمباني المدرجة منذ عام 1970 وجزءا من مواقع التراث العالمي لليونسكو منذ عام 1987",
        en: "The palace is one of the centres of political life in the United Kingdom: Westminster has come to stand for the UK Parliament, and the Westminster system of government took its name from it. The Elizabeth Tower in particular — often referred to by the name of its main bell, Big Ben — is the distinctive landmark of London and the UK as a whole, one of the city's most popular attractions and an emblem of parliamentary democracy. The palace has been a Grade I listed building since 1970 and part of a UNESCO World Heritage Site since 1987.",
      },
      { type: "IMG", src: U("2022/09/img_2623-1.jpg"), cap_ar: "صورة توضح روعة تصميم قصر ويستمنستر بلندن", cap_en: "The splendour of the palace's design" },
      { type: "IMG", src: U("2022/09/img_2628.jpg"), cap_ar: "داخل قصر ويستمنستر بلندن", cap_en: "Inside the Palace of Westminster" },
      { type: "IMG", src: U("2022/09/fullsizerender-1.jpg"), cap_ar: "صورة من أمام قصر ويستمنستر بلندن", cap_en: "In front of the Palace of Westminster" },
      { type: "H3", ar: "سعر تذاكر وأوقات دخول قصر ويستمنستر بلندن", en: "Tickets and opening hours", noNumber: true },
      {
        type: "P",
        ar: "مفتوح بشكل يومي من الساعة 09:00 صباحا وحتى الساعة 05:00 مساء ، وسعر تذكرة دخول القصر 8 جنيهات استرلينية",
        en: "Open daily from 09:00 to 17:00, with an entry ticket costing £8.",
      },
    ],
  },
  {
    slug: "london-eye",
    title_ar: "عين لندن .. أيقونة السياحة بلندن",
    title_en: "The London Eye — an icon of the city",
    kicker_ar: "معلم",
    kicker_en: "Landmark",
    image: U("2022/09/4dca19f9-71e8-4892-ae39-cd7ddaecf4a9.jpg"),
    blocks: [
      {
        type: "P",
        ar: "عجلة لندن آي في بريطانيا هي واحدة من أهم المعالم السياحية في لندن التي تؤمن لزوارها رحلة فريدة من نوعها في سماء المدينة مع الاستمتاع بواحدة من أجمل الاطلالات الباهرة التي يمكنهم مشاهدتها للعاصمة الانجليزية لندن",
        en: "The London Eye is one of the city's most important attractions, giving visitors a one-of-a-kind ride through the sky above London along with one of the most dazzling views to be had over the English capital.",
      },
      {
        type: "P",
        ar: "اذ تقع عجلة العين في مدينة لندن في وسط منطقة لامبيث النابضة بالحياة ، وافتتحت عجلة عين لندن للزوار أول مرة في آخر عام 1999 ميلادي ، وهي عبارة عن عجلة دوارة كبيرة يصل ارتفاعها الى ما يقارب 135 مترا وقطرها الى 120 مترا ، ويوجد فيها حوالي 32 عربة تقوم كل واحدة منها بنقل 25 شخصا كحد أقصى في رحلة تدوم لمدة 30 دقيقة",
        en: "The wheel stands in the lively district of Lambeth and first opened to visitors at the very end of 1999. It is a great rotating wheel rising about 135 metres, with a diameter of 120 metres, and holds around 32 capsules, each carrying a maximum of 25 people on a ride lasting 30 minutes.",
      },
      { type: "IMG", src: U("2022/09/img_2630.jpg"), cap_ar: "صورة توضح جمال عين لندن ليلا", cap_en: "The London Eye by night" },
      {
        type: "P",
        ar: "لندن آي أو عجلة لندن هي عجلة سياحية ضخمة أو دولاب هواء تم انشاؤه في العاصمة البريطانية قبيل مطلع القرن الحادي والعشرين ، وتقع على ضفاف نهر التايمز ويمكن للشخص ركوبها لمشاهدة معالم مدينة لندن والتمتع بالمناظر الجميلة أثناء دورانها حول محورها ، ويمكن للراكب أن يرى كثيرا من الأشياء حتى مسافة 40 كيلومترا في المتوسط ، وأيضا رؤية بعض المعالم البارزة الشهيرة مثل كاتدرائية سنت بول وقصر وستمنستر وقلعة وندسور ، ويمكن أن تحمل العجلة 15 ألف زائر يوميا",
        en: "The London Eye is a huge observation wheel built in the British capital just before the turn of the twenty-first century. It stands on the bank of the Thames, and riders can take in the city's landmarks and enjoy the views as it turns on its axis, seeing as far as 40 kilometres on average, including famous sights such as St Paul's Cathedral, the Palace of Westminster and Windsor Castle. The wheel can carry 15,000 visitors a day.",
      },
      { type: "IMG", src: U("2022/09/09f7a75e-61ae-410c-9740-a76afff16566.jpg"), cap_ar: "صورة من أمام عين لندن", cap_en: "In front of the London Eye" },
      {
        type: "P",
        ar: "تعتبر لندن آي منذ انشائها منافسا قويا لنظيرتيها ساعة بيغ بن وبرج لندن أشهر معالم مدينة الضباب ، حيث نالت الجائزة البرونزية لأفضل أماكن الجذب الترفيهية في المملكة المتحدة لعام 2011 ، كما أنها تعتبر من أهم معالم السياحة في لندن عامة وأوروبا خاصة",
        en: "Since it was built the London Eye has been a strong rival to Big Ben and the Tower of London, the best-known landmarks of the foggy city. It won the bronze award for the best leisure attraction in the United Kingdom in 2011 and is considered one of the leading attractions in London, and in Europe more widely.",
      },
      { type: "IMG", src: U("2022/09/97265aaf-521f-482e-8695-f68ae4db43c1.jpg"), cap_ar: "صورة لعين لندن توضح جمالها الأخاذ", cap_en: "The London Eye in all its beauty" },
      { type: "IMG", src: U("2022/09/img_2631.jpg"), cap_ar: "صورة من أعلى عجلة عين لندن", cap_en: "The view from the top of the London Eye" },
      { type: "H3", ar: "أفضل الأنشطة التي يمكن القيام بها في عين لندن", en: "The best things to do at the London Eye", noNumber: true },
      {
        type: "LIST",
        ar: [
          "بامكانكم في بداية مشواركم الترفيهي التجول في محيط العجلة الخارجي لمعرفة ما سوف تقومون به لاحقا من نشاطات أو ركوب العجلة لمشاهدة المدينة من الأعلى",
          "تستطيعون بالاضافة الى ذلك زيارة إحدى الحدائق الطبيعية المتناسقة برفقة الأصحاب لتناول وجبات الغداء أو اللعب مع الأطفال لبعض الوقت",
          "في ختام رحلتكم المليئة بالاثارة والمتعة في محيط العجلة لا تنسوا زيارة أحد الأسواق الشاملة لكل ما تبحث عنه العائلة لاقتناء بعض الهدايا التذكارية من هذه المدينة",
        ],
        en: [
          "Start your outing with a walk around the wheel to see what activities you might do later, or ride the wheel to look out over the city from above.",
          "You can also visit one of the well-kept gardens nearby with friends, to have lunch or let the children play for a while.",
          "At the end of your visit around the wheel, don't miss one of the markets that has everything a family looks for, to pick up some souvenirs of the city.",
        ],
      },
      { type: "H3", ar: "سعر التذكرة وأوقات دخول عجلة لندن", en: "Tickets and opening hours", noNumber: true },
      {
        type: "P",
        ar: "مفتوحة بشكل يومي من الساعة 11:00 صباحا وحتى الساعة 07:00 مساء ، وسعر تذكرة ركوب العجلة 32 جنيها استرلينيا",
        en: "Open daily from 11:00 to 19:00, with a ticket to ride costing £32.",
      },
    ],
  },
  {
    slug: "buckingham-palace",
    title_ar: "قصر باكنغهام .. قصر الملوك البريطانيين",
    title_en: "Buckingham Palace — home of Britain's monarchs",
    kicker_ar: "معلم",
    kicker_en: "Landmark",
    image: U("2022/09/img_2641.jpg"),
    blocks: [
      {
        type: "P",
        ar: "قصر باكنغهام Buckingham Palace هو المقر الرسمي لملوك بريطانيا ويقع في لندن العاصمة ، ويعتبر مكانا لجل الأحداث المتصلة بالعائلة البريطانية المالكة ومكانا لانعقاد العديد من الاجتماعات وزيارات قادة الدول ، اضافة لكونه نقطة جذب سياحية رئيسية",
        en: "Buckingham Palace is the official residence of Britain's monarchs, in the capital, London. It is the setting for most events connected with the British royal family and the venue for many meetings and visits by heads of state, as well as a major tourist attraction.",
      },
      {
        type: "P",
        ar: "يعتبر القصر مزار جذب سياحي ونقطة محورية للشعب البريطاني في لحظات الفرح والأزمات والمتاعب ، ومن هناك أيضا تصدر جل التصريحات الصحفية التابعة للمكاتب الملكية",
        en: "The palace is both a visitor attraction and a focal point for the British people in moments of joy, crisis and trouble, and it is from there that most press statements from the royal offices are issued.",
      },
      {
        type: "P",
        ar: "تم الانتهاء من أول منزل بني على الموقع في سنة 1624 بناء على أوامر سير وليم بلاك ، وكان ذلك بداية لفترة مختلطة ومثيرة للجدل بالنسبة للموقع ، فقد استمرت الحجج القانونية والوثائق المفقودة والارتباك حول الملكية الحقيقية للموقع لعدة سنوات ، ومع ذلك كان المبنى الرئيسي الأول الذي نصب في الحدود الحالية لقصر باكنغهام هو بيت جورينج على الرغم من أنه أحرق في 1674 ، وبيت أرلينغتون هو الآن الجناح الجنوبي من القصر ومقر للكثير من المناسبات الرسمية وحفلات الاستقبال",
        en: "The first house on the site was completed in 1624 on the orders of Sir William Blake, beginning a mixed and much-disputed period for the site: legal arguments, lost documents and confusion over the true ownership went on for years. The first main building erected within today's boundaries was Goring House, though it burned down in 1674. Arlington House is now the south wing of the palace and the setting for many official occasions and receptions.",
      },
      {
        type: "P",
        ar: "ويحتوي القصر على غرف الدولة التي تفتح للزوار كل عام ، وفي عام 1703 قرر دوق باكنغهام ونورماندي انشاء منزل كبير على الأرض والذي يشكل جزءا كبيرا من قصر باكنغهام اليوم ، وفي عام 1761 بيع منزل باكنغهام للملك جورج الثالث مقابل 21,000 جنيه استرليني",
        en: "The palace contains the State Rooms, which open to visitors each year. In 1703 the Duke of Buckingham and Normanby decided to build a large house on the land, and it forms a great part of Buckingham Palace today. In 1761 Buckingham House was sold to King George III for £21,000.",
      },
      {
        type: "P",
        ar: "لم يكن القصر حتى عام 1837 عندما اعتلت الملكة فيكتوريا العرش مسؤولا عن الاقامة الملكية الرئيسية كما هو الآن ، وعندما تزوجت الملكة فيكتوريا الأمير ألبرت في عام 1840 أخذ على عاتقه تنظيم شؤون المقر الملكي الرئيسي ، وهكذا ظهر قصر باكنغهام الذي نعرفه اليوم",
        en: "Not until 1837, when Queen Victoria came to the throne, did the palace become the principal royal residence as it is today. When Victoria married Prince Albert in 1840, he took on the organisation of the chief royal residence — and so the Buckingham Palace we know today emerged.",
      },
      { type: "IMG", src: U("2022/09/img_2640.jpg"), cap_ar: "واجهة قصر باكنغهام بلندن", cap_en: "The front of Buckingham Palace" },
      {
        type: "P",
        ar: "أما مواصفات القصر فيبلغ طول واجهته 108 أمتار ويبلغ عمقه 120 مترا بما في ذلك الساحة المربعة المركزية ، وارتفاعه 24 مترا ، ويوجد بالقصر 775 غرفة تشتمل على 19 غرفة دولة و 52 غرفة ملكية وغرف للضيوف و 188 غرفة للموظفين و 92 مكتبا و 78 حماما",
        en: "As for its dimensions, the palace front is 108 metres long and it is 120 metres deep including the central quadrangle, standing 24 metres high. It has 775 rooms: 19 state rooms, 52 royal and guest bedrooms, 188 staff rooms, 92 offices and 78 bathrooms.",
      },
      {
        type: "P",
        ar: "أما الأهمية السياسية للقصر فهو مبنى خاص بالعمل الى حد كبير ، وهو يعد الدعامة الأساسية للنظام الملكي الدستوري في بريطانيا ، ويضم مكاتب أولئك الذين يدعمون النشاطات اليومية وواجبات الملكة ودوق أدنبرة وأسرهم ، وهو أيضا المقر الرسمي لانعقاد الاحتفالات الملكية الكبيرة والزيارات الخارجية والتعيينات التي تنظمها الأسرة المالكة ، وغرف الدولة تشكل نواة القصر كمقر للعمل",
        en: "Politically, the palace is very much a working building and the mainstay of Britain's constitutional monarchy. It houses the offices of those who support the daily activities and duties of the Queen, the Duke of Edinburgh and their families, and is the official setting for great royal ceremonies, state visits and appointments arranged by the royal household, with the State Rooms forming its working core.",
      },
      { type: "IMG", src: U("2022/09/img_0841.jpg"), cap_ar: "صورة من أمام قصر باكنغهام بلندن", cap_en: "In front of Buckingham Palace" },
      {
        type: "P",
        ar: "وعن الأهمية التراثية فقد زين قصر باكنغهام بالعديد من التحف الفنية التي لا تقدر بثمن والتي تشكل جزءا من المجموعة الملكية ، أحد أهم المجموعات الفنية في العالم ، لكن هذا لم يجعل منه متحفا أو معرضا فنيا ، ويزور القصر أكثر من 50,000 شخص سنويا كمدعوين الى ولائم أو وجبات الغداء أو العشاء أو حفلات الاستقبال أو احتفالات الحديقة الملكية",
        en: "In heritage terms, the palace is adorned with priceless works of art that form part of the Royal Collection, one of the most important art collections in the world — though this has not made it a museum or gallery. More than 50,000 people visit each year as guests at banquets, lunches, dinners, receptions or the royal garden parties.",
      },
      {
        type: "P",
        ar: "وبالنسبة لأولئك الذين يتلقون دعوة لقصر باكنغهام ، فان الخطوة الأولى عبر العتبة تكون داخل القاعة الكبرى ثم صعود الدرج الرخامي المقوس في الدرج الكبير ، ولا يزال يتم وضع اللوحات في الجدران كما كان في عهد الملكة فيكتوريا",
        en: "For those who receive an invitation, the first step across the threshold leads into the Grand Hall and then up the curving marble flight of the Grand Staircase, where paintings are still hung on the walls as they were in Queen Victoria's day.",
      },
      { type: "IMG", src: U("2022/09/img_2643.jpg"), cap_ar: "أحد قاعات قصر باكنغهام بلندن", cap_en: "One of the halls in Buckingham Palace" },
      { type: "H3", ar: "أفضل الأنشطة التي يمكن القيام بها في قصر باكنغهام", en: "The best things to do at Buckingham Palace", noNumber: true },
      {
        type: "LIST",
        ar: [
          "عند زيارة معلم تاريخي كهذا ، من أول الأنشطة التي نوصيك بها أن تذهب في جولة مبدئية في أنحاء المكان لتتمتع برؤية الطراز المعماري الذي يتزين به القصر من الخارج ، ولا تنس أنه بامكانك المشاركة في إحدى الجولات الارشادية أو الاستعانة بالارشادات الصوتية المتاحة",
          "وفيما يخص التقاط الصور التذكارية فان ادارة القصر تتيح ذلك في أماكن محددة من القصر",
          "استكشف قصر باكنغهام من الداخل وشاهد ما يضمه ، حيث يبلغ عدد غرفه 775 غرفة بين الغرف الملكية وغرف الخدم والغرف التي خصصت قديما لاستقبال الزوار",
          "من أكثر أجزاء القصر استقطابا للضيوف قاعة الاستقبال ، حيث تشد الأنظار بالنقوش والزخارف الرائعة والثريات الثمينة",
          "كل قسم في القصر يتضمن أشياء عديدة تستحق الاستكشاف ، فقطع الأثاث القديم المنتشرة في معظم أجزاء القصر تستحق وقتا مناسبا لرؤية تصاميمها الرائعة",
          "سوف ترى في أقسام العرض مقتنيات أثرية شاهدة على تاريخ هذا القصر العريق ، من قطع أثرية الى مجوهرات",
          "في قاعات عرض الفنون يوجد منحوتات وتماثيل بالاضافة الى مجموعة من اللوحات الفنية لأشهر الرسامين",
          "من المعروضات البارزة صورة توماس كيليجرو وويليام لورد كروفتس للفنان أنتوني ديك ، ونصب فيكتوريا التذكاري ، ولوحة ود بالقرب من سودبوري سوفولك للفنان توماس غينزبورو",
          "شاهد العروض المسرحية التي تقام في مسرح القصر",
          "من المتوقع أن يجذبك محل الهدايا المتوفر في المكان لشراء مجموعة من الهدايا الجميلة أو التذكارات الفريدة",
          "تمتع بالتنزه في الحديقة المحيطة بالقصر والاستراحة على أحد مقاعدها ، وتتزين الحديقة ببعض البرك المائية والنوافير ومجموعة من المنحوتات الرائعة",
          "ما زال القصر مقرا لعرض تبديل حراس القصر الذي يتوق لرؤيته الكثيرون والتعرف على المراسم التي يتم عملها لتبديل الحرس",
        ],
        en: [
          "At a historic site like this, the first thing we recommend is an initial walk around the grounds to enjoy the architecture of the palace from the outside — and remember you can join a guided tour or use the audio guides available.",
          "As for photographs, the palace allows them in certain designated areas.",
          "Explore Buckingham Palace inside and see what it holds: 775 rooms in all, among them the royal rooms, the servants' rooms and the rooms once set aside for receiving visitors.",
          "One of the most popular parts for guests is the reception hall, which draws the eye with its wonderful carvings, ornament and precious chandeliers.",
          "Every section of the palace holds much worth exploring: the antique furniture spread through most of it deserves time to appreciate its remarkable designs.",
          "In the display rooms you will see antiquities that bear witness to the palace's long history, from archaeological pieces to jewellery.",
          "The art galleries hold sculptures and statues as well as a collection of paintings by the most famous artists.",
          "Among the standout works are the portrait of Thomas Killigrew and William, Lord Crofts by Anthony van Dyck, the Victoria Memorial, and Wooded Landscape near Sudbury, Suffolk by Thomas Gainsborough.",
          "Watch the performances staged in the palace theatre.",
          "The gift shop is likely to tempt you into buying some lovely presents or unique souvenirs.",
          "Enjoy a stroll through the garden around the palace and rest on one of its benches; the garden is set with pools, fountains and a group of fine sculptures.",
          "The palace is still the setting for the Changing of the Guard, which many long to see, and a chance to learn the ceremony behind the handover.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_2644.jpg"), cap_ar: "صورة توضح مدخل قصر باكنغهام بلندن", cap_en: "The entrance to Buckingham Palace" },
      { type: "H3", ar: "سعر تذاكر وأوقات دخول قصر باكنغهام", en: "Tickets and opening hours", noNumber: true },
      {
        type: "P",
        ar: "مفتوح بشكل يومي ، وسعر تذكرة دخول القصر 30 جنيها استرلينيا ، وللأطفال دون سن 5 سنوات مجانا ، وأكثر من 5 سنوات 19.5 جنيه استرليني",
        en: "Open daily. Entry costs £30, free for children under 5, and £19.5 for children over 5.",
      },
      { type: "IMG", src: U("2022/09/img_2645.jpg"), cap_ar: "أحد معروضات قصر باكنغهام بلندن", cap_en: "One of the displays in Buckingham Palace" },
    ],
  },
  {
    slug: "oxford-street",
    title_ar: "شارع اكسفورد .. القلب النابض للندن",
    title_en: "Oxford Street — the beating heart of London",
    kicker_ar: "تسوق",
    kicker_en: "Shopping",
    image: U("2022/09/img_2648-2.jpg"),
    blocks: [
      {
        type: "P",
        ar: "أكسفورد ستريت هو شارع يقع في ناحية الوست إند بالعاصمة البريطانية لندن ، ويعتبر أشهر شارع للتسوق على الصعيد الأوروبي غير منازع ، ويمر به نحو نصف مليون شخص يوميا",
        en: "Oxford Street lies in the West End of the British capital and is the undisputed best-known shopping street in Europe, with around half a million people passing along it every day.",
      },
      {
        type: "P",
        ar: "يمتد الشارع لنحو 1.9 كيلومتر ، ويبدأ غربا من ماربل آرش عند تلاقي إدجوير رود وبارك لين ، ويتجه شرقا ليتقاطع مع نيو بوند ستريت ثم ينتهي عند التقاطع مع ريجنت ستريت",
        en: "The street runs for about 1.9 km, beginning in the west at Marble Arch where Edgware Road meets Park Lane, heading east to cross New Bond Street and ending at the junction with Regent Street.",
      },
      {
        type: "P",
        ar: "بالرغم من التنافس المتزايد من المراكز التجارية من أمثال وستفيلد ، ما زال الشارع مرغوبا عند أصحاب المحلات ، كما أن الكثير من المتاجر المعروفة ترغب في وضع فرعها الأساسي في أكسفورد ستريت من أمثال سيلفريدجز وجون لويس وغيرها ، وفيها تطلق معروضاتها الجديدة أو تعلن بداية موسم التخفيضات",
        en: "Despite growing competition from malls such as Westfield, the street is still coveted by retailers, and many well-known stores want their flagship on Oxford Street — Selfridges, John Lewis and others — where they launch new collections or announce the start of the sales.",
      },
      {
        type: "P",
        ar: "يضم الشارع أكثر من 300 محل تجاري ، وفي عام 2013 وصلت المبيعات فيه الى أرقام قياسية تقدر بنحو 5 مليارات جنيه استرليني ، ويعد هذا الرقم ضخما ويفوق حتى عائدات الكثير من دول العالم في مدة سنة ، ويعادل عائدات مدينة برمنغهام بأكملها وهي ثاني أكبر مدينة في بريطانيا ، كما يعادل مرتين ونصف المرة عائدات متجري وستفيلد العملاقين في شرق لندن وغربها",
        en: "The street holds more than 300 shops, and in 2013 its sales reached record figures of around £5 billion — a huge sum, greater than the annual revenue of many countries, equal to the revenue of the whole of Birmingham, Britain's second largest city, and two and a half times the takings of the two giant Westfield centres in east and west London.",
      },
      {
        type: "P",
        ar: "وفي السنوات القليلة الماضية ظهر متجر برايمارك المعروف بأسعاره الرخيصة نسبيا وبدأ ينافس المتاجر الكبيرة في الشارع من أمثال سيلفريدجز ، وتمثل مبيعات برايمارك نحو 15% من مبيعات شارع أكسفورد",
        en: "In recent years Primark, known for its relatively cheap prices, has appeared and begun to compete with the street's large stores such as Selfridges; Primark's sales account for around 15% of Oxford Street's total.",
      },
      { type: "IMG", src: U("2022/09/img_2646.jpg"), cap_ar: "شارع أكسفورد كما يبدو بزحمته اليومية", cap_en: "Oxford Street in its daily crush" },
      {
        type: "P",
        ar: "يمر بالشارع أربع محطات مترو هي ابتداء من جهة الشرق ماربل آرش وبوند ستريت وأكسفورد سيركس وتوتنهام كورت رود ، وحين ينتهي العمل على مشروع كروس ريل وهدفه ربط شرق لندن بغربها عبر نفق جديد للقطارات ستضاف محطتان جديدتان في أكسفورد ستريت وتحديدا عند بوند ستريت وتوتنهام كورت رود",
        en: "Four underground stations serve the street — from the east: Marble Arch, Bond Street, Oxford Circus and Tottenham Court Road. When the Crossrail project, intended to link east and west London by a new rail tunnel, is finished, two new stations will be added on Oxford Street, at Bond Street and Tottenham Court Road.",
      },
      {
        type: "P",
        ar: "بسبب كثرة مرور الباصات والسيارات تعد نسبة تلوث الهواء في أكسفورد ستريت عالية بالمقاييس الأوروبية ، وفي منتصف عام 2016 أعلن مكتب عمدة لندن أن الشارع سيصبح خاليا تماما من السيارات ، وذلك ضمن خطط العمدة صادق خان للتخفيف من حدة التلوث ، ومن المخطط أن يمتد حظر السيارات من شارع توتنهام كورت عبر محل سلفريدجز والى مدخل محطة مترو بوند ستريت",
        en: "Because of the heavy bus and car traffic, air pollution on Oxford Street is high by European standards. In mid-2016 the Mayor of London's office announced that the street would become completely car-free as part of Mayor Sadiq Khan's plans to reduce pollution, with the ban planned to run from Tottenham Court Road past Selfridges to the entrance of Bond Street station.",
      },
      { type: "IMG", src: U("2022/09/img_2647.jpg"), cap_ar: "شارع أكسفورد في أيام الأعياد", cap_en: "Oxford Street at Christmas" },
      {
        type: "P",
        ar: "يحتوي شارع أكسفورد على عدد كبير من المحلات التجارية التي يصل عددها إلى 300 محل ، وتبيع هذه المتاجر كل ما يخطر في بال الزائر من الأمور التي تتعلق بالأزياء والموضة ، حيث يوجد في الشارع محلات لأشهر الماركات من حول العالم ، كما يوجد فيه العديد من المقاهي التي تقدم مجموعة من المشروبات الانجليزية اللذيذة",
        en: "Oxford Street has a great many shops — as many as 300 — selling everything a visitor could think of in fashion and clothing, with stores for the most famous brands from around the world, along with many cafés serving delicious English drinks.",
      },
      {
        type: "P",
        ar: "كما يتميز الشارع بأنه يظهر للسائح النمط الحياتي الخاص بالمدينة ، فهو مزدحم ويعج بالبشر والسيارات ، ورغم أن هذا ليس بالأمر الذي يفضله الجميع ، فان الأمر ممتع لأنه يعرفك على العديد من التفاصيل التي تتعلق بالمدينة",
        en: "The street also shows visitors the city's way of life: it is crowded and teeming with people and cars. Although that is not to everyone's taste, it is enjoyable because it introduces you to so much of the detail of the city.",
      },
      { type: "IMG", src: U("2022/09/img_2648.jpg"), cap_ar: "صورة توضح جمال وروعة المباني المطلة على شارع أكسفورد بلندن", cap_en: "The handsome buildings overlooking Oxford Street" },
      { type: "IMG", src: U("2022/09/img_2649.jpg"), cap_ar: "أحد جوانب شارع أكسفورد وقت اغلاق المحلات", cap_en: "A corner of Oxford Street after the shops close" },
      { type: "H3", ar: "أفضل الأنشطة التي يمكن القيام بها في شارع أكسفورد", en: "The best things to do on Oxford Street", noNumber: true },
      {
        type: "LIST",
        ar: [
          "يعتبر التجول في هذا الشارع متعة استثنائية سوف تدفعك لمعاودة زيارته مرة تلو الأخرى ، فهو المكان الذي يعكس الملامح الثقافية لهذه المدينة على أرض الواقع ، وأثناء التجول سوف يشد نظرك الى تلك الأشجار الموجودة على طرفي الشارع كما ستعثر على مقاعد الجلوس التي تتيح لك تأمل الشارع والمارة",
          "والماضي العريق هو أحد العناوين التي تلوح في هذا الشارع بكل وضوح ، اذ أن شارع أكسفورد شارع تاريخي تنعكس عليه صور الزمن الجميل الذي ستجد نفسك مندهشا بكل تفاصيله",
          "وبما أن أرصفة شارع أكسفورد تعج بعدد من المحلات التجارية التي تعرض سلعا متنوعة فلن تقدر على مواصلة التجول دون أن تشد اليها لمشاهدة ما تقدمه ، ومن أشهر هذه المتاجر متجر برايمارك ، كما ستعثر على عدد من المتاجر العربية",
          "كما يمكنك قضاء يوم سعيد برفقة من تحب في أيام عيد الميلاد في شارع أكسفورد ، حيث أن كل المحال التجارية تكون مزينة احتفالا بهذا العيد",
        ],
        en: [
          "Walking this street is an exceptional pleasure that will bring you back again and again — it is the place where the city's cultural character shows itself on the ground. As you walk, the trees along both sides will catch your eye, and you will find benches where you can sit and watch the street and the passers-by.",
          "A long past is one of the themes that show clearly here: Oxford Street is a historic street reflecting images of a beautiful era whose every detail will surprise you.",
          "Since the pavements of Oxford Street are lined with shops displaying all kinds of goods, you will not manage to keep walking without being drawn in to see what they offer. Among the most famous is Primark, and you will also find a number of Arab-owned shops.",
          "You can also spend a happy day with those you love on Oxford Street at Christmas, when every shop is decorated for the season.",
        ],
      },
    ],
  },
  {
    slug: "british-museum",
    title_ar: "المتحف البريطاني .. التاريخ الناصع للحضارة البريطانية",
    title_en: "The British Museum — a bright record of civilisation",
    kicker_ar: "متحف",
    kicker_en: "Museum",
    image: U("2022/09/img_2654.jpg"),
    blocks: [
      {
        type: "P",
        ar: "المتحف البريطاني British Museum في منطقة بلومزبري بلندن هو متحف ومؤسسة عامة مكرسة لتاريخ البشرية والفن والثقافة ، وتعد مجموعة المتحف الدائمة التي تضم حوالي ثمانية ملايين عمل فني من بين الأكبر والأكثر شمولا في العالم ، وتم الحصول على أغلبها خلال عصر الامبراطورية البريطانية ، ويوثق المتحف قصة الثقافة البشرية من بدايتها حتى الوقت الحاضر ، وهو أقدم متحف وطني عام في العالم ، ويعد مبنى المتحف من أبرز الأمثلة على طراز الاحياء الاغريقي",
        en: "The British Museum in the Bloomsbury district of London is a museum and public institution dedicated to human history, art and culture. Its permanent collection of some eight million works is among the largest and most comprehensive in the world, most of it acquired during the era of the British Empire. The museum documents the story of human culture from its beginnings to the present day; it is the oldest national public museum in the world, and its building is a prominent example of the Greek Revival style.",
      },
      {
        type: "P",
        ar: "تأسس المتحف البريطاني عام 1753 واستند الى حد كبير الى أعمال الطبيب والعالم الايرلندي السير هانز سلون ، وافتتح لأول مرة للجمهور في 1759 في مونتاجو هاوس في موقع المبنى الحالي ، وكان توسعه على مدى السنوات الـ 250 التالية الى حد كبير نتيجة لتوسع الاستعمار البريطاني ، وأدى ذلك الى انشاء العديد من المؤسسات الفرعية أولها متحف التاريخ الطبيعي في عام 1881",
        en: "The British Museum was founded in 1753, based largely on the collections of the Irish physician and scientist Sir Hans Sloane, and first opened to the public in 1759 at Montagu House on the site of the present building. Its expansion over the following 250 years was largely a result of the spread of British colonialism, and this led to the creation of several offshoot institutions, the first being the Natural History Museum in 1881.",
      },
      {
        type: "P",
        ar: "في عام 1973 فصل قانون المكتبات البريطانية لعام 1972 قسم المكتبة عن المتحف البريطاني ، لكنه استمر في استضافة المكتبة البريطانية المنفصلة في نفس غرفة القراءة ومبنى المتحف حتى عام 1997 ، والمتحف هيئة عامة غير وزارية ، وكما هو الحال مع جميع المتاحف الوطنية في المملكة المتحدة لا يتقاضى أي رسوم للدخول باستثناء بعض المعارض الخاصة ، وهناك جدل دولي كبير بسبب امتلاك المتحف لبعض من أشهر القطع التي تعود أصولها الى دول أخرى وعلى الأخص في حالة رخام الالجين اليوناني وحجر رشيد المصري ، كما يحتوي المتحف على أكبر كنز من الذهب والفضة الروماني القديم المكتشف في بريطانيا وهو كنز هوكسن",
        en: "In 1973 the British Library Act 1972 separated the library department from the museum, though it continued to host the separate British Library in the same reading room and building until 1997. The museum is a non-departmental public body, and as with all national museums in the UK it charges no entry fee except for some special exhibitions. There is considerable international controversy over its ownership of some of the most famous pieces originating in other countries, notably the Greek Elgin Marbles and the Egyptian Rosetta Stone. The museum also holds the largest hoard of ancient Roman gold and silver found in Britain, the Hoxne Hoard.",
      },
      { type: "IMG", src: U("2022/09/img_2650.jpg"), cap_ar: "المتحف البريطاني بلندن", cap_en: "The British Museum in London" },
      { type: "H3", ar: "تاريخ المتحف البريطاني بلندن", en: "The history of the British Museum", noNumber: true },
      {
        type: "LIST",
        ar: [
          "عرض الأمر على البرلمان البريطاني الذي أقر في عام 1753 في عهد الملك جورج الثاني أن يدفع مبلغ 20 ألف جنيه استرليني لورثة الطبيب على أن يجعل من المجموعة نواة المتحف الذي عرف الآن باسم المتحف البريطاني والذي فتح أبوابه في 15 يناير 1759",
          "وكان المبنى الذي استعمل لذلك هو بيت مونتاج",
          "ومع أن الزيارة كانت في أول الأمر بدون رسم دخول إلا أنهم حرصوا على أن يعطى للزائر تذكرة لا يمر بدونها",
          "وكان الزوار يحصلون على شرح من موظف مختص يقودهم بين ردهات المتحف ، ومع مرور الزمن حدث شيء من التراخي بالنسبة لشروط الدخول الى أن سمح أخيرا للجمهور في عام 1879 بالدخول بدون تذكرة",
          "وفي عام 1808 صدرت لائحة تنظيمية بشأن زيارات الأجانب والفنانين للمتحف ويفهم منها أن المتحف كان مفتوحا للجمهور أيام الاثنين والثلاثاء والأربعاء والخميس",
          "ولا يسمح بدخول أكثر من ثماني مجموعات في اليوم الواحد على أن لا يزيد عدد المجموعة الواحدة عن خمسين شخصا",
          "ولا يجوز للزائر أن يتحرك بدون تذكرة وفي صحبة أحد الموظفين من المتحف أو أحد الحراس ، وقد خصص يوم الجمعة للزيارات الخاصة وكان من حين لآخر يتم حجز المتحف كله لطلبة الأكاديمية الملكية البريطانية",
          "وقد تركت معظم المعروضات بدون بطاقات شرح إلا في حالات قليلة جدا ، ولم يتم طبع أول دليل للزوار إلا في عام 1808",
          "وقرب نهاية القرن التاسع عشر نشط المتحف في نشر الكتالوجات العلمية وبالتحديد في عام 1888 ، ومع مرور الوقت تزايدت مجموعات المتحف البريطاني بشكل كبير وكان من أشهرها المجموعة المصرية التي استولى عليها الانجليز بعد انتصارهم في موقعة أبو قير البحرية على الفرنسيين وأهم ما فيها حجر رشيد",
          "وتضم مكتبة المتحف العديد من الكتب القديمة والمخطوطات النادرة المطبوعة والخطية",
          "موقعة أبي قير البحرية أو معركة النيل وقعت في 2 أغسطس 1798 بين الأسطول الفرنسي والأسطول الانجليزي بقيادة نيلسون ، وقد قدرت الخسائر الفرنسية بـ 1700 قتيل بينهم نائب الأدميرال و 3000 أسير ، وكانت الخسائر البريطانية 218 قتيلا ، وكان من نتائجها أن أغرق الأسطول الفرنسي وقضي على آمال فرنسا في تكوين امبراطورية فرنسية ، وكان من ضمن شروطها أن يسلم الفرنسيون كل القطع الأثرية المصرية للانجليز ومن بينها حجر رشيد",
        ],
        en: [
          "The matter was put before the British Parliament, which in 1753, in the reign of George II, resolved to pay £20,000 to the physician's heirs so that the collection could form the nucleus of the museum now known as the British Museum, which opened its doors on 15 January 1759.",
          "The building used for this was Montagu House.",
          "Although at first there was no entry fee, they were careful that each visitor be given a ticket without which they could not pass.",
          "Visitors received an explanation from a member of staff who led them through the museum's halls. Over time the entry conditions relaxed, until the public was finally allowed to enter without a ticket in 1879.",
          "In 1808 regulations were issued about visits by foreigners and artists, from which it appears the museum was open to the public on Mondays, Tuesdays, Wednesdays and Thursdays.",
          "No more than eight groups a day were admitted, with no group exceeding fifty people.",
          "A visitor could not move about without a ticket and in the company of a member of staff or a guard. Friday was set aside for private visits, and from time to time the whole museum was reserved for students of the Royal Academy.",
          "Most exhibits were left without explanatory labels except in very few cases, and the first visitors' guide was not printed until 1808.",
          "Towards the end of the nineteenth century the museum became active in publishing scientific catalogues, specifically from 1888. Over time its collections grew greatly, among the most famous being the Egyptian collection seized by the English after their victory over the French at the naval Battle of Abu Qir — its most important piece being the Rosetta Stone.",
          "The museum's library holds many old books and rare printed and handwritten manuscripts.",
          "The naval Battle of Abu Qir, or the Battle of the Nile, took place on 2 August 1798 between the French fleet and the English fleet under Nelson. French losses were estimated at 1,700 killed, including a rear-admiral, and 3,000 taken prisoner, while British losses were 218 killed. Its results were the sinking of the French fleet and the end of France's hopes of building a French empire; among its terms was that the French hand over all Egyptian antiquities to the English, the Rosetta Stone among them.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_2651.jpg"), cap_ar: "سقف القاعة الرئيسية بالمتحف البريطاني بلندن", cap_en: "The roof of the museum's Great Court" },
      {
        type: "P",
        ar: "ولعل من بين أبرز المعالم التي يتضمنها المتحف البريطاني المومياوات المصرية التي يتم عرضها في الغرفتين رقم 62 و 63 مع التوابيت وأدوات الدفن من أيام الفراعنة ، وهنا يمكنك أن تتعلم كل شيء عن عبادة الموتى المصرية في زمن الفراعنة ، حيث يمتلك المتحف أكبر مجموعة من الآثار المصرية خارج مصر",
        en: "Perhaps the most striking of the museum's holdings are the Egyptian mummies, displayed in rooms 62 and 63 along with coffins and burial objects from the days of the pharaohs. Here you can learn everything about the Egyptian cult of the dead in pharaonic times — the museum holds the largest collection of Egyptian antiquities outside Egypt.",
      },
      { type: "IMG", src: U("2022/09/img_2656.jpg"), cap_ar: "من معروضات المتحف البريطاني", cap_en: "From the museum's displays", size: "compact" },
      { type: "IMG", src: U("2022/09/img_2655.jpg"), cap_ar: "من معروضات المتحف البريطاني", cap_en: "From the museum's displays", size: "compact" },
      { type: "IMG", src: U("2022/09/img_2652-1.jpg"), cap_ar: "لوحة آشور ناصربال الثاني وهي أثر ضخم من الحجر الجيري أقيم في عهد الملك آشور ناصربال الثاني", cap_en: "The relief of Ashurnasirpal II, a huge limestone monument raised in his reign" },
      { type: "IMG", src: U("2022/09/img_2653.jpg"), cap_ar: "أحد قاعات المتحف البريطاني بلندن", cap_en: "One of the halls of the British Museum" },
      { type: "H3", ar: "أوقات عمل المتحف البريطاني بلندن", en: "Opening hours", noNumber: true },
      {
        type: "P",
        ar: "مفتوح من السبت الى الخميس من الساعة 10:00 صباحا وحتى الساعة 05:30 مساء ، ويوم الجمعة من 10:00 صباحا وحتى الساعة 08:00 مساء ، والدخول له مجانا ، ويقع المتحف في منطقة بلومزبري في العاصمة لندن ويمكن الوصول له بالحافلة عبر محطة غريت روسيل",
        en: "Open Saturday to Thursday from 10:00 to 17:30, and on Friday from 10:00 to 20:00. Entry is free. The museum lies in the Bloomsbury district of London and can be reached by bus via the Great Russell Street stop.",
      },
    ],
  },
];
