export type Attraction = {
  num: string;
  name_ar: string;
  name_en: string;
  desc_ar: string;
  desc_en: string;
  image: string;
  tall?: boolean;
};

export type CityFeature = {
  tagline_ar: string;
  tagline_en: string;
  intro_ar: string;
  intro_en: string;
  section_title_ar: string;
  section_title_en: string;
  closing_ar: string;
  closing_en: string;
  attractions: Attraction[];
};

export const CITY_FEATURES: Record<string, CityFeature> = {
  paris: {
    tagline_ar: "مدينة النور · عاصمة فرنسا · وجهة الفن والأزياء والثقافة",
    tagline_en: "The City of Light · Capital of France · Home of art, fashion and culture",
    section_title_ar: "أجمل وأشهر أماكن السياحة في باريس",
    section_title_en: "The finest sights of Paris",
    intro_ar:
      "باريس، عاصمة فرنسا وأجمل مدنها السياحية. مدينة النور — أو مدينة الحب كما يحلو للبعض تسميتها — تُعدّ منذ عقود واحدة من المراكز الرائدة في العالم للأعمال والأزياء والترفيه والفن والثقافة. يرتبط اسمها بالمعالم العالمية الشهيرة والمتاحف والكاتدرائيات، وهي الوجهة الأولى للسياحة في فرنسا.",
    intro_en:
      "Paris, capital of France and the loveliest of its cities. The City of Light — or the City of Love, as some prefer to call it — has for decades been a leading centre for business, fashion, entertainment, art and culture. Its name is bound to world-famous landmarks, museums and cathedrals, and it remains the first destination for tourism in France.",
    closing_ar: "«باريس تستحق الزيارة دائماً، مهما تغيّرت الفصول.»",
    closing_en: "\u201CParis is always a good idea, no matter the season.\u201D",
    attractions: [
      { num: "01", name_ar: "برج إيفل", name_en: "Eiffel Tower",
        desc_ar: "برج إيفل من أبرز معالم باريس السياحية، إن لم يكن فرنسا كلها. بُني عام 1889م على يد المهندس غوستاف إيفل، ويبلغ ارتفاعه 324 متراً، ويُعدّ أطول مباني العاصمة باريس على الإطلاق، وأحد أكثر الأماكن السياحية زيارةً في المدينة.",
        desc_en: "The Eiffel Tower is one of the most iconic landmarks of Paris — if not all of France. Built in 1889 by engineer Gustave Eiffel, it rises 324 metres, making it the tallest building in the capital and one of the most visited attractions in the city.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg", tall: true },
      { num: "02", name_ar: "شارع الشانزليزيه", name_en: "Champs-Élysées",
        desc_ar: "يُعتبر شارع الشانزليزيه من أشهر الشوارع الفرنسية وأطولها، وهو من أرقى وأفخم الشوارع السياحية والتجارية في العالم. يضم أرقى المحلات التجارية العالمية والمطاعم الراقية، وتنتشر على جانبيه المقاهي التي تمنحه طابعاً باريسياً خاصاً.",
        desc_en: "The Champs-Élysées is one of France's most famous and longest avenues, and one of the most elegant shopping and tourist streets in the world. It is lined with luxury boutiques, fine restaurants, and countless cafés that give it its unmistakable Parisian character.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Avenue_des_Champs-%C3%89lys%C3%A9es_July_24%2C_2009_N1.jpg" },
      { num: "03", name_ar: "قوس النصر", name_en: "Arc de Triomphe",
        desc_ar: "قوس النصر يقع في بداية شارع الشانزليزيه، في ميدان شارل ديغول الذي كان يُعرف بميدان النجمة في قلب باريس. يُعدّ من أهم رموز المدينة بعد برج إيفل، ويبلغ ارتفاعه 50 متراً، ويحظى بشعبية خاصة بين زوار العاصمة.",
        desc_en: "The Arc de Triomphe stands at the start of the Champs-Élysées in Place Charles de Gaulle — once known as Place de l'Étoile — in the heart of Paris. Rising 50 metres high, it is one of the city's most beloved symbols, second only to the Eiffel Tower.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1280px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg", tall: true },
      { num: "04", name_ar: "ميدان الكونكورد", name_en: "Place de la Concorde",
        desc_ar: "ميدان الكونكورد أحد أكبر ميادين العاصمة الفرنسية، ويقع في نهاية شارع الشانزليزيه من طرفه الشرقي. يحوي مسلّة مصرية ضخمة أهداها الخديوي إسماعيل إلى الملك لويس فيليب عام 1831، ويُعدّ من أبرز الأماكن السياحية في باريس.",
        desc_en: "Place de la Concorde is one of the largest squares in the French capital, located at the eastern end of the Champs-Élysées. At its centre stands a great Egyptian obelisk, gifted by Khedive Ismail to King Louis-Philippe in 1831 — a defining landmark of the city.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Place_de_la_Concorde_from_the_Eiffel_Tower%2C_Paris_April_2011.jpg/1280px-Place_de_la_Concorde_from_the_Eiffel_Tower%2C_Paris_April_2011.jpg" },
      { num: "05", name_ar: "الحي اللاتيني", name_en: "Latin Quarter",
        desc_ar: "الحي اللاتيني من أشهر وأقدم الأماكن السياحية في باريس، يقع على الضفة اليسرى لنهر السين. يضم عدداً كبيراً من المباني التاريخية، ويمنح زواره متعة استكشاف الحياة الباريسية الحقيقية عبر مطاعمه الفرنسية ومقاهيه ومحلات الموضة العالمية.",
        desc_en: "The Latin Quarter is one of the oldest and most celebrated neighbourhoods in Paris, sitting on the Left Bank of the Seine. Filled with historic buildings, traditional bistros, cafés and boutique fashion houses, it offers visitors a taste of authentic Parisian life.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/46/P1300734_Paris_V_place_de_la_Sorbonne_rwk.jpg" },
      { num: "06", name_ar: "باريس ديزني لاند", name_en: "Disneyland Paris",
        desc_ar: "باريس ديزني لاند — وتُعرف أيضاً باسم ديزني لاند ريزورت باريس أو يورو ديزني — من أشهر معالم باريس الترفيهية. تقع على بُعد 32 كم من مركز العاصمة، وتضم مدينتي ملاهي و7 فنادق، وتُعدّ ثاني أكبر منتجع لديزني خارج الولايات المتحدة بعد طوكيو ديزني لاند.",
        desc_en: "Disneyland Paris — also called Disneyland Resort Paris or Euro Disney — is the city's flagship entertainment destination, 32 km from the centre of Paris. It holds two theme parks and seven hotels, and is the second-largest Disney resort outside the United States after Tokyo Disneyland.",
        image: "https://upload.wikimedia.org/wikipedia/en/8/88/Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg" },
      { num: "07", name_ar: "متحف اللوفر", name_en: "Louvre Museum",
        desc_ar: "متحف اللوفر واحد من أكبر متاحف العالم وأشهر متحف في باريس، ويشكّل معلماً بارزاً في وسط المدينة. يعرض ما يقرب من 35,000 قطعة أثرية تمتد من عصور ما قبل التاريخ حتى القرن الحادي والعشرين، على مساحة تبلغ 60,600 متر مربع.",
        desc_en: "The Louvre is one of the world's largest museums and the most famous in Paris, sitting at the heart of the city. It displays some 35,000 objects — from prehistory to the 21st century — across an exhibition space of 60,600 square metres.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg" },
      { num: "08", name_ar: "متحف بيكاسو", name_en: "Musée Picasso",
        desc_ar: "متحف بيكاسو في باريس هو ثاني أكبر متحف مخصص للفنان بيكاسو بعد متحفه في برشلونة. يعود المبنى إلى عام 1659، وقد كان قصراً ثم تحوّل إلى مدرسة قبل أن تسيطر عليه حكومة الثورة الفرنسية. يُعدّ اليوم من أشهر متاحف باريس.",
        desc_en: "The Musée Picasso in Paris is the second-largest museum dedicated to the artist, after the one in Barcelona. Its 17th-century building — completed in 1659 — was originally a mansion, later a school, before being seized during the French Revolution. Today it stands among the city's most celebrated museums.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/93/H%C3%B4tel_Sal%C3%A9.JPG" },
      { num: "09", name_ar: "حدائق لوكسمبورغ", name_en: "Luxembourg Gardens",
        desc_ar: "جاردان دو لوكسمبورغ — أو حدائق لوكسمبورغ — هي ثاني أكبر الحدائق العامة في باريس، وتمتد على مساحة 224,500 متر مربع. تشتهر بأجوائها الهادئة وأحواضها المائية، وسلسلة تماثيل تخلّد ملكات فرنسا القديمات والقديسين.",
        desc_en: "The Jardin du Luxembourg is the second-largest public garden in Paris, spread across 224,500 square metres. It is loved for its tranquil atmosphere, its reflecting pools, and the long line of statues honouring former queens of France and saints.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LuxembourgMontparnasse.JPG/1280px-LuxembourgMontparnasse.JPG" },
      { num: "10", name_ar: "حديقة النباتات", name_en: "Jardin des Plantes",
        desc_ar: "حديقة النباتات من أهم حدائق باريس، وتقع بالقرب من معلمَين مهمّين بالنسبة للسائح العربي: المعهد الإسلامي — الذي يضم أكبر مساجد باريس — ومعهد العالم العربي، مما يجعلها محطّة مميّزة في زيارة العاصمة.",
        desc_en: "The Jardin des Plantes is one of Paris's most important gardens, located near two landmarks of special interest to Arab visitors: the Great Mosque of Paris, which is the largest mosque in the city, and the Arab World Institute — making it a rewarding stop in any tour of the capital.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/48/Paris_75005_Grande_Galerie_de_l%27Evolution_20070804.jpg" },
      { num: "11", name_ar: "قصر فرساي", name_en: "Palace of Versailles",
        desc_ar: "يُعدّ قصر فرساي من أجمل قصور باريس وفرنسا عموماً. بُني عام 1624 ويقع على بُعد 20 كيلومتراً جنوب باريس. يتميّز بقاعة المرايا الشهيرة، ويحتضن آلاف اللوحات والأعمال الفنية المذهلة، ويُعدّ مثالاً على روعة الفن المعماري الفرنسي. مفتوح يومياً من 09:00 صباحاً حتى 06:30 مساءً، وسعر التذكرة نحو 80 يورو.",
        desc_en: "The Palace of Versailles is among the most beautiful palaces in Paris — and in France as a whole. Built in 1624, it sits 20 km south of Paris. It is famed for the Hall of Mirrors and houses thousands of paintings and works of art, standing as a masterpiece of French architecture. Open daily from 09:00 to 18:30, with tickets around €80.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_081_%28cropped%29.jpg/1280px-Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_081_%28cropped%29.jpg" },
      { num: "12", name_ar: "قصر غارنييه", name_en: "Palais Garnier",
        desc_ar: "يقع قصر غارنييه — المعروف باسم أوبرا باريس — في مبنى فخم غاية في الروعة. أسّسه لويس الرابع عشر عام 1669، ثم أُعيد بناؤه بطلب من نابليون الثالث ضمن حملة إعادة إعمار باريس، ليصبح من أكبر دور الأوبرا في العالم.",
        desc_en: "The Palais Garnier — better known as the Paris Opera — occupies one of the most sumptuous buildings in the city. Founded under Louis XIV in 1669 and later commissioned by Napoleon III as part of the great redevelopment of Paris, it stands today as one of the largest opera houses in the world.",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Paris_Opera_full_frontal_architecture%2C_May_2009.jpg" },
      { num: "13", name_ar: "قصر الإليزيه", name_en: "Élysée Palace",
        desc_ar: "قصر الإليزيه من أشهر قصور باريس، ويُعدّ المقر الرسمي لرئاسة الجمهورية الفرنسية، حيث يضمّ مكتب رئيس الدولة ومكان اجتماع مجلس الوزراء. يقع بالقرب من شارع الشانزليزيه، وبُني في القرن الثامن عشر مع الحفاظ على تصميمه الكلاسيكي عبر القرون.",
        desc_en: "The Élysée Palace is one of the most renowned palaces in Paris and the official residence of the French Republic, hosting the head of state's office and Cabinet meetings. Located near the Champs-Élysées, it was built in the 18th century and has kept its classical design intact through the centuries.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Secretary_Pompeo_Arrives_to_Meet_with_French_Foreign_Minister_Le_Drian_in_Paris_%2850610423656%29_%28cropped%29.jpg/1280px-Secretary_Pompeo_Arrives_to_Meet_with_French_Foreign_Minister_Le_Drian_in_Paris_%2850610423656%29_%28cropped%29.jpg" },
    ],
  },

  marseille: {
    tagline_ar: "ثاني أكبر مدن فرنسا · عاصمة الثقافة الأوروبية 2013 · مدينة البحر والميناء",
    tagline_en: "France's second city · European Capital of Culture 2013 · A city of sea and port",
    section_title_ar: "أجمل معالم السياحة في مارسيليا",
    section_title_en: "The finest sights of Marseille",
    intro_ar:
      "تُعدّ مارسيليا من أهم المدن الفرنسية وثاني أكبر منطقة حضرية بعد باريس، وهي أكبر مدينة ساحلية في فرنسا تقع على البحر الأبيض المتوسط. تحتضن ميناء مارسيليا — أكبر موانئ فرنسا — وقد اختيرت عاصمة للثقافة الأوروبية عام 2013، وتضم أكثر من 24 متحفاً و42 مسرحاً، فضلاً عن كونها موطناً لواحدة من أكبر الجاليات العربية المسلمة في فرنسا.",
    intro_en:
      "Marseille is one of France's most important cities and the second-largest urban area after Paris. It is the country's largest coastal city, sitting on the Mediterranean, and home to the Port of Marseille — France's biggest harbour. Chosen European Capital of Culture in 2013, it holds more than 24 museums and 42 theatres, and hosts one of the largest Arab and Muslim communities in France.",
    closing_ar: "«في مارسيليا يلتقي البحر بالتاريخ.»",
    closing_en: "\u201CIn Marseille, the sea meets history.\u201D",
    attractions: [
      { num: "01", name_ar: "كاتدرائية نوتردام دو لا غارد", name_en: "Notre-Dame de la Garde",
        desc_ar: "كاتدرائية نوتردام دو لا غارد رمز مارسيليا الشامخ، تعتلي أعلى تلال المدينة وتُطلّ على البحر الأبيض المتوسط. تشكّل نموذجاً بديعاً للعمارة الدينية، وتضم آثاراً كاثوليكية ذات قيمة عالية، وتحظى بأعلى نسب زيارة بين معالم المدينة.",
        desc_en: "Notre-Dame de la Garde is Marseille's soaring symbol, crowning the city's highest hill and gazing out over the Mediterranean. A masterpiece of religious architecture, it holds treasured Catholic relics and is the city's most visited landmark.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Notre-Dame_de_la_Garde_aerial_view_2020.jpeg", tall: true },
      { num: "02", name_ar: "الميناء القديم", name_en: "The Old Port (Vieux-Port)",
        desc_ar: "يقع الميناء القديم في نهاية شارع لا كانبيير — الشارع الرئيسي والشعبي في مارسيليا. يضم حوله معالم بارزة كدير سانت فيكتور — أقدم دور العبادة المسيحية في فرنسا — وفندق قاعة المدينة، والعبّارة التاريخية التي تُبحر بين ضفتَي الميناء، إلى جانب متحف رومان دوك الشهير.",
        desc_en: "The Old Port lies at the end of La Canebière, Marseille's main and most popular avenue. Around it stand landmarks such as Saint-Victor Abbey — one of France's oldest Christian sites — the Hôtel de Ville, the historic ferry crossing between the two banks, and the celebrated Roman Docks Museum.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Marseille_Old_Port.jpg/3840px-Marseille_Old_Port.jpg" },
      { num: "03", name_ar: "متحف الحضارات الأوروبية (موسيم)", name_en: "MuCEM — Museum of European & Mediterranean Civilisations",
        desc_ar: "من أبرز رموز مارسيليا، افتُتح عام 2013م في السنة نفسها التي تُوّجت فيها المدينة عاصمة للثقافة الأوروبية. مخصّص للحضارات المتوسّطية والأوروبية، صُمم على شكل مكعّب من الحجر والماء والرياح بمساحة 15,000 متر مربع، ويضم قاعات معارض ومكتبة ومطعماً.",
        desc_en: "One of Marseille's icons, opened in 2013 — the same year the city was named European Capital of Culture. Dedicated to Mediterranean and European civilisations, it is designed as a 15,000 m² cube of stone, water and wind, holding exhibition halls, a library and a restaurant.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/%22Beeindruckende_Architektur%22._5.jpg/3840px-%22Beeindruckende_Architektur%22._5.jpg" },
      { num: "04", name_ar: "سوق نواي", name_en: "Noailles Market",
        desc_ar: "سوق نواي مكان نابض بالحياة في قلب مارسيليا. إن كنت من محبّي التسوق فبإمكانك شراء الأقمشة الملوّنة، ومختلف أنواع الأطعمة والتوابل الأفريقية والهندية، والأدوات المنزلية والاكسسوارات وغيرها الكثير.",
        desc_en: "Noailles Market is a vibrant, colourful place at the heart of Marseille. If you love shopping, wander through it for bright fabrics, African and Indian spices and foods, household goods, accessories and much more.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Marseille_-_M%C3%A9tro_%26_Tramway_-_Noailles_%287537853682%29.jpg/3840px-Marseille_-_M%C3%A9tro_%26_Tramway_-_Noailles_%287537853682%29.jpg" },
      { num: "05", name_ar: "حي لو بانييه", name_en: "Le Panier District",
        desc_ar: "لو بانييه أقدم أحياء مارسيليا والقلب الثقافي التاريخي للمدينة. يقع الحي الملوّن على تلّة تُطلّ على الميناء القديم، ويمكنك التجوّل في شوارعه القديمة المرصوفة بالحجر، والتقاط الصور أمام الجداريات، واكتشاف متاجر الحرفيين ومحلات الأطعمة والمعارض الفنية.",
        desc_en: "Le Panier is Marseille's oldest quarter and its historic cultural heart. Perched on a hill above the Old Port, its colourful streets are paved with stone and lined with murals, artisan workshops, delicatessens and small galleries — an unforgettable walk.",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Rue_Panier_Marseille.jpg" },
      { num: "06", name_ar: "حديقة كالانك الوطنية", name_en: "Calanques National Park",
        desc_ar: "حديقة كالانك الوطنية موقع طبيعي رائع يلتقي فيه البحر الأبيض المتوسط بجبال كالانك الصخرية. توفّر الحديقة مناظر خلّابة وجدراناً صخرية من الحجر الجيري وخلجاناً ببرك مياه فيروزية، وأنشطة تشمل السباحة والتجديف بالكاياك وركوب اليخوت وتسلق الصخور.",
        desc_en: "Calanques National Park is a breathtaking natural site where the Mediterranean meets sheer limestone cliffs. Turquoise coves and dramatic rock walls invite swimming, kayaking, boating, hiking and climbing — a favourite escape for visitors.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/En-Vau_calanque_4.jpg/3840px-En-Vau_calanque_4.jpg", tall: true },
    ],
  },

  lyon: {
    tagline_ar: "عاصمة الحرير · مدينة النهرين · التراث العالمي لليونسكو",
    tagline_en: "Capital of silk · City of two rivers · UNESCO World Heritage",
    section_title_ar: "أجمل معالم السياحة في ليون",
    section_title_en: "The finest sights of Lyon",
    intro_ar:
      "تُعتبر ليون عاصمة إقليم رون، وثاني أكبر منطقة حضرية في فرنسا. تشتهر بمعالمها التاريخية والحضارية، وقد أُدرجت ضمن لائحة اليونسكو للتراث العالمي، فضلاً عن دورها البارز في مجال السينما ومهرجان الأضواء الشهير Festival of Lights وفنون الطبخ العالمية. تقع عند ملتقى نهرَي الرون والساون في جنوب شرق فرنسا.",
    intro_en:
      "Lyon is the capital of the Rhône region and France's second-largest urban area. Famous for its historic sites — a UNESCO World Heritage listing — Lyon plays a leading role in cinema, hosts the celebrated Festival of Lights, and is renowned for its world-class gastronomy. It sits at the meeting point of the Rhône and Saône rivers in south-eastern France.",
    closing_ar: "«في ليون يجتمع النهران، والتاريخ، والذوق.»",
    closing_en: "\u201CIn Lyon, two rivers, history and taste all meet.\u201D",
    attractions: [
      { num: "01", name_ar: "حديقة تيت دور", name_en: "Parc de la Tête d'Or",
        desc_ar: "حديقة حضرية كبيرة جدا تبلغ مساحتها 117 هكتاراً، اكتسبت طابعاً شعبياً وشهرة واسعة بفضل بحيرتها الجميلة وقواربها المتحرّكة. تُعدّ المكان الأفضل لمحبّي المشي والركض وركوب الدراجات، وتضم حديقة حيوانات كبيرة فيها زرافات وفيلة وغزلان وزواحف.",
        desc_en: "A vast 117-hectare urban park loved for its lake, boat rides and shaded paths. It's a favourite for walking, running and cycling, and includes a large free zoo home to giraffes, elephants, deer and reptiles.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Parc_de_la_T%C3%AAte_d%27Or_Vue_sur_le_lac7.jpg" },
      { num: "02", name_ar: "متحف التقاليد الشعبية (متاحف غادان)", name_en: "Gadagne Museums",
        desc_ar: "متحف يقع في وسط ليون وتُركّز أغلب مقتنياته على الفعاليات والأنشطة الشعبية للناس من الحاضر والماضي. تحفة معمارية قائمة بذاتها تروي حكاية المدينة وتقاليدها.",
        desc_en: "Set in the heart of Lyon, the Gadagne Museums focus on the everyday life and popular traditions of the city, past and present. The building itself is an architectural gem that tells the story of Lyon.",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Cour-gadagne_Photo_Service-communication-Gadagne_2021_%285%29.jpg" },
      { num: "03", name_ar: "ساحة بلكور", name_en: "Place Bellecour",
        desc_ar: "ساحة كبيرة تقع في وسط ليون، وتُعدّ من أكبر المناطق المربعة المفتوحة في فرنسا وأكبر ساحة مشاة فيها. يتوسطها تمثال فروسي للملك لويس الرابع عشر، وتضم مكتب المعلومات السياحية ومعرضاً فنياً، وقد أُدرجت ضمن لائحة اليونسكو للتراث العالمي.",
        desc_en: "One of France's largest open squares and its biggest pedestrian plaza, Place Bellecour lies at the centre of Lyon. An equestrian statue of Louis XIV stands at its middle; two pavilions house the tourist office and an art gallery, and the square is part of Lyon's UNESCO World Heritage listing.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Place_Bellecour_%28Lyon%2C_2024%2C_version_recentr%C3%A9e_2%29.jpg" },
      { num: "04", name_ar: "المدينة القديمة (فيو ليون)", name_en: "Old Lyon (Vieux Lyon)",
        desc_ar: "مكان مثالي للاستمتاع بتاريخ ليون، مع مبانٍ وكنائس مذهلة يعود تاريخها إلى آلاف السنين. شوارع ضيقة مرصوفة بالحصى، ومحلات ساحرة، ومطاعم ومقاهي، وممرات سرية تُدعى traboules استخدمها عمال الحرير لحماية بضائعهم. يمكنك زيارة كاتدرائية سان-جان — مثال ممتاز للعمارة القوطية.",
        desc_en: "A perfect place to soak up Lyon's history among centuries-old buildings and churches. Narrow cobbled streets are lined with charming shops, cafés and restaurants, connected by hidden passages called traboules once used by silk workers. Don't miss the Gothic Saint-Jean Cathedral at its heart.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Vieuxlyon_saintjean_toits.jpg", tall: true },
    ],
  },

  cannes: {
    tagline_ar: "مدينة الأثرياء · موطن مهرجان كان السينمائي · الواجهة الفنية بعد باريس",
    tagline_en: "The city of the wealthy · Home of the Cannes Film Festival · France's artistic capital after Paris",
    section_title_ar: "أجمل معالم السياحة في كان",
    section_title_en: "The finest sights of Cannes",
    intro_ar:
      "بجوار مدينة نيس في الجنوب تقع كان الفرنسية، التي حصلت على لقب مدينة الأثرياء وحقّ لها ذلك؛ فهي من أكثر الأماكن التي مرّ عليها مشاهير العالم، وارتبط اسمها بالطبقة الغنية. تحتضن مهرجانات ومؤتمرات عالمية، وفنادق ومطاعم راقية، ومتاحف شهيرة، إلى جانب الكنائس الرائعة والحدائق والمعارض والقصور والفلل الخاصة بالمهرجانات — وأشهرها مهرجان كان السينمائي السنوي.",
    intro_en:
      "Just along the coast from Nice sits Cannes, rightly known as the city of the wealthy — the meeting point of the world's celebrities. It hosts global festivals and conferences, world-class hotels and restaurants, famous museums, elegant churches and gardens, and villas built for its festivals — most famously the annual Cannes Film Festival.",
    closing_ar: "«على البساط الأحمر يبدأ مساء كان.»",
    closing_en: "\u201CEvening in Cannes begins on the red carpet.\u201D",
    attractions: [
      { num: "01", name_ar: "قصر المهرجانات وقاعة المؤتمرات", name_en: "Palais des Festivals et des Congrès",
        desc_ar: "رمز من رموز فرنسا، يحتضن كل الاحتفالات والمراسم والمهرجانات في كان، وعلى الأخص مهرجان كان السينمائي الدولي ومهرجان كان ليونز الدولي للإبداع. تبلغ مساحته المخصّصة للمعارض 25 ألف متر مربع، ويحوي البساط الأحمر الشهير الذي يعرف به المكان.",
        desc_en: "A French icon, host to Cannes' every ceremony and festival — above all the Cannes International Film Festival and Cannes Lions. Its 25,000 m² of exhibition space and famous red carpet make it the beating heart of the city.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Cannes_Palais_des_Festivals_et_des_Congr%C3%A8s.jpg" },
      { num: "02", name_ar: "متحف لا كاستر", name_en: "Musée de la Castre",
        desc_ar: "مع الإطلالة على البحر والقيمة التاريخية والثقافية التي يضمّها بين جدرانه، يصبح متحف كان أحد أجمل متاحف فرنسا. يقع على بُعد كيلومتر واحد من المدينة، ويعرض كنوزاً عثر عليها في البحر، بعضها يعود إلى عصر الإمبراطورية الرومانية.",
        desc_en: "With its sea view and its walls filled with cultural and historic value, the Musée de la Castre is one of France's most beautiful museums. A kilometre from the city, it displays treasures recovered from the sea — some dating to the Roman Empire.",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/Des_batiments_2.jpg" },
      { num: "03", name_ar: "المدينة القديمة (لو سوكيه)", name_en: "The Old Town (Le Suquet)",
        desc_ar: "بعيداً عن الصخب ومظاهر الحياة الفارهة، يقصد كثير من زوار كان المدينة القديمة — قرية صيد قديمة يعود عمر مبانيها إلى ما يقارب 100 سنة. الجزء الأكبر منها للمشاة، حيث المحلات الصغيرة والمطاعم ذات الرائحة الذكية والسلالم القديمة والجوّ الرومانسي.",
        desc_en: "Away from the glamour and buzz, Le Suquet is Cannes' original fishing village, its buildings around a century old. Mostly pedestrian, it charms with tiny boutiques, fragrant restaurants, old staircases and a quietly romantic atmosphere.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Le_Suquet_01.jpg/3840px-Le_Suquet_01.jpg", tall: true },
      { num: "04", name_ar: "فيلا دومرج", name_en: "Villa Domergue",
        desc_ar: "شاهدٌ على تاريخ فن الآرت ديكو الحديث، من تصميم وتنفيذ الرسام جان غابرييل دومرغي عام 1926م. أُدرجت مكاناً تاريخياً عام 1990م، وتضم حديقتها تماثيل نصفية عتيقة وأعمالاً فنية لزوجة الرسام. تُقام فيها معارض فنية وأحداث ثقافية، وكانت مقرّاً للجنة تحكيم مهرجان كان السينمائي.",
        desc_en: "A living record of Art Deco design, built in 1926 by the painter Jean-Gabriel Domergue and listed as a historic site in 1990. Its garden holds antique busts and works by the painter's wife, and hosts art exhibitions and cultural events — it was once the meeting place of the Cannes Festival jury.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Cannes_Palais_des_Festivals_et_des_Congr%C3%A8s.jpg" },
    ],
  },

  colmar: {
    tagline_ar: "البندقية الصغيرة · لؤلؤة الألزاس · مدينة القنوات",
    tagline_en: "Little Venice · The pearl of Alsace · A city of canals",
    section_title_ar: "أجمل معالم السياحة في كولمار",
    section_title_en: "The finest sights of Colmar",
    intro_ar:
      "كولمار مدينة وبلدية في إقليم أوت رين شمال شرق فرنسا بمنطقة الألزاس الثقافية. تُطلّ على نهر لاوش، وترتبط بنهر الراين من خلال قناة، وتشتهر بقراها الريفية وبلداتها القديمة ومتاحفها ومعالمها الحضارية. يُطلق عليها لقب البندقية الصغيرة لتشابهها مع فينيسيا، وتحظى بحصة عالية من السياحة في فرنسا.",
    intro_en:
      "Colmar is a town in the Haut-Rhin department in north-eastern France, in the cultural region of Alsace. Sitting on the Lauch river and linked by canal to the Rhine, it is famed for its rural villages, old town, museums and historic sites. Its resemblance to Venice earned it the name Little Venice, and it draws a large share of French tourism.",
    closing_ar: "«كولمار مدينة صغيرة بحكاية كبيرة.»",
    closing_en: "\u201CColmar — a small town with a great story.\u201D",
    attractions: [
      { num: "01", name_ar: "المدينة القديمة", name_en: "The Old Town",
        desc_ar: "جوّ المدينة الريفية ستجده هنا في كولمار القديمة، التي حافظت على سحرها الرائع البسيط، وتُقدّم إطلالة سحرية على 1000 عام من التاريخ الأوروبي عبر تراثها الثقافي. ستجد المنازل القديمة نصف الخشبية، والقنوات الجميلة، ومركز مدينة المشاة النابض بالحياة، والمطاعم والمحلات التجارية.",
        desc_en: "Colmar's old town preserves its unmistakable rural charm, offering visitors a magical window onto a thousand years of European history. Wander among half-timbered houses, along pretty canals, through a lively pedestrian centre lined with restaurants and boutiques.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/View_of_%C3%89glise_Saint-Martin_%2843833049001%29.jpg/3840px-View_of_%C3%89glise_Saint-Martin_%2843833049001%29.jpg" },
      { num: "02", name_ar: "البندقية الصغيرة", name_en: "Little Venice (Petite Venise)",
        desc_ar: "في كولمار كل شيء ممكن، فقد أُحضرت فينيسيا الإيطالية إلى هنا وسُمّيت بـ فينيسيا الصغيرة. تعتبر إحدى رموز كولمار وتجمع بين الثقافتين الفرنسية والألمانية بنكهة إيطالية، من خلال القنوات المائية والجسور التي تعبر فوق نهر اللاش، والقوارب الصغيرة التي تُبحر بين قنواتها.",
        desc_en: "In Colmar anything is possible — even a little Venice. This district blends French and German culture with an Italian flavour: canals, bridges over the Lauch, and small boats gliding between the waterways make it one of Colmar's most iconic scenes.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/ColmarFrance.jpg/3840px-ColmarFrance.jpg", tall: true },
      { num: "03", name_ar: "متحف أونترليندن", name_en: "Unterlinden Museum",
        desc_ar: "يقع هذا المتحف في دير الأخوات الدومنيكان، ويضمّ مجموعة كبيرة ورائعة من الأعمال الفنية والمصنوعات اليدوية المحلية والدولية من عصور ما قبل التاريخ إلى العصور المعاصرة. يحمل علامة الجودة الفرنسية، ويعتبر من أكثر المتاحف زيارة في فرنسا.",
        desc_en: "Set in the former Dominican sisters' convent, the Unterlinden Museum holds an outstanding collection of local and international art and craft from prehistory to the present day. Certified with France's official quality label, it is one of the country's most visited museums.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Mus%C3%A9e_d%27Unterlinden_Colmar.jpg" },
      { num: "04", name_ar: "ميزون دي تيت (بيت الرؤوس)", name_en: "Maison des Têtes",
        desc_ar: "المعروف بمجلس الرؤساء، يعود تاريخ بنائه إلى القرن السادس عشر، وهو من أقدم المباني الخشبية في كولمار. يتميّز بوجود صور وجوه لأبرز شخصيات المدينة، ويحتوي على لوحات جدارية رائعة.",
        desc_en: "Dating from the 16th century, the Maison des Têtes — House of Heads — is one of Colmar's oldest timber-framed buildings. It is famous for the sculpted faces of the city's leading figures adorning its façade, and for its beautiful murals.",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Maison_des_T%C3%AAtes_2.jpg" },
      { num: "05", name_ar: "كنيسة الدومنيكان", name_en: "Dominican Church",
        desc_ar: "من أجمل المباني في كولمار، بُنيت على الطراز المعماري القديم الذي يعود إلى عصر النهضة. تتميّز بالأحجار الوردية الرائعة، وتحتوي على لوحة Schongauer الشهيرة، مما جعلها من أفضل معالم السياحة في كولمار.",
        desc_en: "Among Colmar's most beautiful buildings, this Gothic church is built of striking pink stone and houses the famous Schongauer painting — making it a highlight of any visit to the city.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Cloitre_colmar.jpg" },
    ],
  },

  annecy: {
    tagline_ar: "لؤلؤة جبال الألب الفرنسية · فينيسيا الجبال · بحيرة وقلاع",
    tagline_en: "Pearl of the French Alps · Alpine Venice · A city of lake and castles",
    section_title_ar: "أجمل معالم السياحة في أنسي",
    section_title_en: "The finest sights of Annecy",
    intro_ar:
      "أنسي من أكبر المدن الواقعة في جنوب شرق فرنسا على الطرف الشمالي لبحيرة أنسي، وتُلقّب بلؤلؤة جبال الألب الفرنسية لموقعها المميّز بين البحيرات والجبال. يُطلق عليها البعض أيضاً فينيسيا جبال الألب بسبب الأنهار والبحيرات والقنوات المحيطة بها. تبعد 55 كم عن باريس، و43 كم عن جنيف — فأنت بين جنّتَي فرنسا وسويسرا.",
    intro_en:
      "Annecy is one of the largest cities of south-eastern France, sitting on the northern tip of Lake Annecy. Nicknamed the Pearl of the French Alps for its position between mountains and lakes, it is also called Alpine Venice for the rivers, lake and canals that surround it. 55 km from Paris and 43 km from Geneva, it lies between two paradises — France and Switzerland.",
    closing_ar: "«على ضفاف أنسي تهدأ الحكاية.»",
    closing_en: "\u201COn Annecy's shores, every story finds calm.\u201D",
    attractions: [
      { num: "01", name_ar: "بحيرة أنسي", name_en: "Lake Annecy",
        desc_ar: "ثالث أكبر بحيرة في فرنسا، ووجهة سياحية مشهورة تُلقّب بأنظف بحيرة في أوروبا. يصل عمقها إلى 82 متراً، وطولها 14 كم بعرض 4 كم. تمتاز ببرودة مياهها في الصيف، ما يجعلها مقصداً للسياح في فصل الصيف، وتحيط بها بلدات وقرى رائعة الجمال.",
        desc_en: "France's third-largest lake and one of Europe's cleanest, Lake Annecy stretches 14 km long and 4 km wide, plunging to 82 metres deep. Cool in summer, its shores are lined with beautiful villages and welcome millions of visitors each year.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Boat_%40_Compagnie_des_Bateaux_du_Lac_d%27Annecy_%40_Lake_Annecy_%40_Saint-Jorioz_%2850488289926%29.jpg/3840px-Boat_%40_Compagnie_des_Bateaux_du_Lac_d%27Annecy_%40_Lake_Annecy_%40_Saint-Jorioz_%2850488289926%29.jpg" },
      { num: "02", name_ar: "جسر الفنون (جسر الحب)", name_en: "Pont des Amours (Lovers' Bridge)",
        desc_ar: "جسر يقع في مدينة أنسي ويعبر قناة فاسّي في وسط المدينة. اشتهر بتعليق العشاق أقفال الحب فوقه دلالةً على استحالة الفراق، حتى أُدرج ضمن لائحة التراث الوطني الفرنسي. يربط بين حدائق أوروبا في باكييه، ويُعدّ مثالاً رائعاً للهندسة المعمارية النموذجية من الحديد في أوائل القرن العشرين.",
        desc_en: "The Lovers' Bridge crosses the Vassé canal in central Annecy. Couples long hung padlocks here as a symbol of undying love, and it is now on France's national heritage list. Linking the Jardins de l'Europe to the Pâquier, it is a classic example of early-20th-century ironwork.",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/da/0306_Annecy_-_Pont_des_Amours.jpg" },
      { num: "03", name_ar: "قصر الإيل (Palais de l'Isle)", name_en: "Palais de l'Isle",
        desc_ar: "منزل محصّن قديم كان يُستخدم كسجن، تعرّض لعدّة عمليات إصلاح وترميم، ويحتوي على قاعات محكمة قديمة وزنزانات للسجناء، والكنيسة القديمة، وغرف نصف دائرية مقبّبة، وقاعة جمهور كبيرة، وسلّم حلزوني يصل بين الطوابق. يُعدّ ضمن لائحة التراث العالمي، ويُدخَل إليه عبر جسر مربوط.",
        desc_en: "This fortified island house has served as a prison and a courthouse. Restored many times, it contains old courtrooms, prison cells, a small chapel, vaulted rooms, an assembly hall and a spiral staircase between floors. On the World Heritage list, it is reached by a footbridge.",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Pr%C3%A9fecture_de_Haute-Savoie_%28Annecy%29_%28cropped%29.JPG" },
      { num: "04", name_ar: "حدائق أوروبا", name_en: "Jardins de l'Europe",
        desc_ar: "من أهم الأماكن السياحية في أنسي، تمتاز بمساحتها الكبيرة وموقعها على ضفاف بحيرة أنسي وجمالها الطبيعي. تجد فيها أنواعاً عديدة من الأشجار والنباتات، مع أماكن للجلوس والتنزّه، ومكاناً للأطفال، وتماثيل حجرية ونافورات، وساعة شمسية تعود إلى القرن التاسع عشر.",
        desc_en: "One of Annecy's key attractions, a large lakeside garden famed for its natural beauty. Broad lawns and rare trees mix with fountains, stone statues, family seating, a children's play area and a 19th-century sundial on Napoleon III's quay.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Jardin_de_l%27Europe_-_Annecy.JPG" },
      { num: "05", name_ar: "جبل سيمنوز", name_en: "Mont Semnoz",
        desc_ar: "يقع جبل سيمنوز في أنسي ضمن كتلة باجيس في جبال الألب، وتتباين ارتفاعات قممه بين 1530 متر و1699 متر في قمة تشاتيلون. يوفّر إطلالات رائعة على المدينة والبحيرات المجاورة والمروج الخضراء، ويُعدّ وجهة مفضّلة للتنزّه، مع أنشطة كالمشي وركوب الدراجات والخيل والقفز بالمظلات.",
        desc_en: "Mount Semnoz rises above Annecy in the Bauges massif, its peaks reaching from 1,530 to 1,699 metres at Châtillon. It offers stunning views over the city, the lakes and lush meadows, and is a beloved outdoor playground for hiking, cycling, horseback riding and paragliding.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Semnoz_%40_Lac_d%27Annecy_%40_Annecy-le-Vieux_%2834804245794%29.jpg/3840px-Semnoz_%40_Lac_d%27Annecy_%40_Annecy-le-Vieux_%2834804245794%29.jpg", tall: true },
    ],
  },

  strasbourg: {
    tagline_ar: "عاصمة الألزاس · مقرّ البرلمان الأوروبي · مدينة على الحدود",
    tagline_en: "Capital of Alsace · Seat of the European Parliament · A city on the border",
    section_title_ar: "أجمل معالم السياحة في ستراسبورغ",
    section_title_en: "The finest sights of Strasbourg",
    intro_ar:
      "تقع مدينة ستراسبورغ في شرق فرنسا، بجوار الحدود الألمانية على نهر إيل من روافد نهر الراين. تحظى بأهمية سياسية عالمية إذ هي مقرّ البرلمان الأوروبي والعديد من المؤسسات الأوروبية. أُدرجت كموقع للتراث العالمي من قبل اليونسكو، وتحتوي على ثاني أكبر جامعة في فرنسا، وهي موطن لأضخم دور العبادة الإسلامية في فرنسا: مسجد ستراسبورغ الكبير.",
    intro_en:
      "Strasbourg lies in eastern France on the German border, on the River Ill — a tributary of the Rhine. It enjoys global political weight as the seat of the European Parliament and many EU institutions. Listed as a UNESCO World Heritage Site, it hosts France's second-largest university and the country's biggest mosque — the Grande Mosquée de Strasbourg.",
    closing_ar: "«ستراسبورغ حيث تلتقي الثقافتان الفرنسية والألمانية.»",
    closing_en: "\u201CStrasbourg — where French and German cultures meet.\u201D",
    attractions: [
      { num: "01", name_ar: "كاتدرائية ستراسبورغ", name_en: "Strasbourg Cathedral",
        desc_ar: "قال عنها الأديب فيكتور هوغو: أعجوبة عملاقة وحسّاسة. كاتدرائية السيدة العذراء الرومانية الكاثوليكية تعود إلى القرن الثالث عشر، وكانت تملك أطول برج في العالم بارتفاع 142 متراً حتى عام 1874م، وما زالت سادس أطول برج في العالم وأعلى هيكل في العصور الوسطى. تُعدّ من أروع الأمثلة على العمارة القوطية المتأخرة.",
        desc_en: "Victor Hugo called it \u201Ca gigantic and delicate marvel.\u201D This Gothic Roman Catholic cathedral dates from the 13th century; its 142-metre spire made it the tallest building in the world until 1874, and it remains the sixth-tallest church spire and the highest medieval structure ever built.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Strasbourg_Cathedral_Exterior_-_Diliff.jpg/3840px-Strasbourg_Cathedral_Exterior_-_Diliff.jpg", tall: true },
      { num: "02", name_ar: "حي فرنسا الصغيرة", name_en: "La Petite France",
        desc_ar: "حي تاريخي في شرق فرنسا يحتوي على المركز التاريخي للمدينة. كان في العصور الوسطى مركزاً لدبّاغي المدينة والصيادين والمطاحن، واليوم منطقة جذب سياحي كبيرة. أُدرج عام 1988م في لائحة التراث العالمي، وتجد فيه الأبراج والجسور والقنوات المائية والمنازل ذات الجدران الخارجية النصف خشبية.",
        desc_en: "A historic district holding the city's old centre. Once home to Strasbourg's tanners, fishermen and millers in the Middle Ages, it is now a major tourist quarter — listed as UNESCO World Heritage in 1988. Wander among towers, bridges, canals and iconic half-timbered houses.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Strasbourg_Petite-France_place_Benjamin-Zix_septembre_2015.jpg" },
      { num: "03", name_ar: "حديقة أورانجري", name_en: "Parc de l'Orangerie",
        desc_ar: "أقدم حديقة في مدينة ستراسبورغ، والوجهة المفضّلة للعشّاق والشباب وممارسي رياضة المشي والأمهات في أيام الأحد. من المناطق المحبّبة للأطفال بفضل مساحة اللعب والألعاب الخفيفة، وتضم حديقة حيوانات يمكن الدخول إليها مجاناً وبحيرة بمنظرها المتلألئ وقواربها.",
        desc_en: "Strasbourg's oldest park, a Sunday favourite of couples, walkers, joggers and families. Loved by children for its play area and small rides, it includes a free zoo and a shimmering lake for boating.",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Absolute_Pavillon_Jos%C3%A9phine_01.jpg" },
      { num: "04", name_ar: "متحف ستراسبورغ التاريخي", name_en: "Strasbourg Historical Museum",
        desc_ar: "يشغل مبنى جميلاً، ويقدّم للزوار مجموعات رائعة من الكتب القديمة والأسلحة التاريخية والأعمال الفنية التي لا تُقارن، كما يضم كتاباً فريداً من نوعه صنعه يوهان جوتنبرغ في أول مطبعة حديثة قام باختراعها.",
        desc_en: "Housed in a beautiful building, this museum holds rare books, historic weapons and remarkable works of art — including a unique volume printed by Johannes Gutenberg on the first modern printing press he invented.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/FR-67-Strasbourg29.JPG" },
      { num: "05", name_ar: "ساحة كليبر", name_en: "Place Kléber",
        desc_ar: "أكبر ساحة في وسط ستراسبورغ، وهي المنطقة التجارية الأفضل في المدينة، حيث ستجد الكثير من خيارات التسوّق. مكان رائع للاستمتاع بأجواء المدينة، لا سيما في شهر ديسمبر مع سوق رأس السنة.",
        desc_en: "The largest square in central Strasbourg and its finest shopping district. A wonderful place to soak up city life — especially in December, when the famous Christmas market takes over.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Absolute_place_Kleber_02.jpg" },
      { num: "06", name_ar: "الحديقة النباتية", name_en: "Botanical Garden",
        desc_ar: "الحديقة النباتية في ستراسبورغ تتمتّع بمساحة كبيرة ومجموعة رائعة من النباتات. تعود إلى القرن السابع عشر وتستضيف أكثر من ستمئة من النباتات والزهور المختلفة، مع مقاعد لطيفة في جميع أنحائها وبركة تسكنها السلاحف.",
        desc_en: "A generous 17th-century botanical garden with a remarkable collection of over 600 different plants and flowers. Quiet benches are scattered throughout, and a pond hosts a small colony of turtles.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Observatoire-Strasbourg.JPG" },
    ],
  },

  nice: {
    tagline_ar: "لؤلؤة الريفييرا · شواطئ الشمس · عاصمة كوت دازور",
    tagline_en: "Pearl of the Riviera · Sunlit beaches · Capital of the Côte d'Azur",
    section_title_ar: "أجمل معالم السياحة في نيس",
    section_title_en: "The finest sights of Nice",
    intro_ar:
      "نيس مدينة تقع في جنوب فرنسا على ساحل البحر الأبيض المتوسط، بين مارسيليا وجنوى في إقليم ألب كوت دازور. يبلغ عدد سكانها 933,080 نسمة، ومساحتها 71.92 كيلومتر مربع. تُعدّ مركزاً سياحياً رئيسياً في البلاد وتشتهر بمصايفها وشواطئها الجميلة، ويزورها ملايين السياح كل سنة عبر مطار كوت دا زور.",
    intro_en:
      "Nice sits on the Mediterranean coast of southern France, between Marseille and Genoa, in the Alpes-Maritimes department. Home to 933,080 people over 72 km², it is one of the country's foremost tourist destinations — celebrated for its resorts and beautiful beaches, welcoming millions of visitors each year through Nice Côte d'Azur Airport.",
    closing_ar: "«الشمس في نيس لا تغيب.»",
    closing_en: "\u201CIn Nice, the sun never sets on the promenade.\u201D",
    attractions: [
      { num: "01", name_ar: "متحف ماتيس", name_en: "Matisse Museum",
        desc_ar: "يجذب هذا المتحف محبّي الفن الراقي وعشّاق أعمال هنري ماتيس الفنية، حيث يعرض المتحف عدداً كبيراً من الأعمال الفنية الخالدة لهذا الرسام الفرنسي العريق، فضلاً عن عرض مفصّل لقصة حياته منذ ولادته وحتى مماته، وبعض ممتلكاته الشخصية.",
        desc_en: "A magnet for lovers of fine art and Henri Matisse's work, this museum displays a large number of the great French painter's works, along with a detailed telling of his life story and some of his personal belongings.",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Mus%C3%A9e_Matisse_Nice.JPG" },
      { num: "02", name_ar: "متحف الفنون الجميلة", name_en: "Musée des Beaux-Arts",
        desc_ar: "يضم المتحف مجموعة متنوّعة من الفنون الفرنسية التابعة لمونيه وبودان ورودان وكاربو وغيرهم الكثير من القرنين التاسع عشر والعشرين. يقع المتحف في قصر الأميرة الأوكرانية السابق.",
        desc_en: "The museum holds a rich collection of French art by Monet, Boudin, Rodin, Carpeaux and others from the 19th and 20th centuries, all set inside a former Ukrainian princess's palace.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Villa_Thomson_03.jpg/3840px-Villa_Thomson_03.jpg" },
      { num: "03", name_ar: "ميدان الماسينا", name_en: "Place Masséna",
        desc_ar: "يقع في منتصف مدينة نيس ويُعدّ المنطقة الحيوية للمدينة، شُيّد عام 1832م. يتضمّن ممرّاً مخصّصاً للسير على الأقدام وعدداً كبيراً من المحلات والمطاعم والمقاهي، إلى جانب نافورة ينبوع الشمس التي تظهر روعتها في ساعات المساء مع الأضواء الملوّنة المحيطة بها.",
        desc_en: "The lively heart of Nice, built in 1832. It features a pedestrian boulevard lined with shops, restaurants and cafés, and the Fountain of the Sun that dazzles at night with its coloured lights.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Place-Mass%C3%A9na_01.jpg" },
      { num: "04", name_ar: "منتزه أنغليس", name_en: "Promenade des Anglais",
        desc_ar: "يُعدّ منتزه أنغليس من أفضل الحدائق المفتوحة في نيس، ويتميّز بإطلالة ساحرة على مياه البحر المتوسط، مع مظلاّت ومقاعد نظيفة توفّر لك وقتاً هادئاً للاسترخاء والقراءة، ورمال شاطئ ذهبية ومياه صافية لممارسة السباحة.",
        desc_en: "The famous seafront walk of Nice, gazing over the Mediterranean. Umbrellas, clean benches and quiet corners invite reading and relaxation, while golden sands and clear water make it perfect for a swim.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/CollineDuChateau_NiceFrance2022.png/3840px-CollineDuChateau_NiceFrance2022.png", tall: true },
      { num: "05", name_ar: "حديقة فونيكس", name_en: "Parc Phoenix",
        desc_ar: "تقع حديقة فونيكس في الجهة الجنوبية الغربية لمدينة نيس، وتُعدّ من أكبر الحدائق العامة في أوروبا بمساحة 7 هكتار. تضم عدداً كبيراً من الأنشطة الترفيهية والثقافية والحيوانات النادرة، ونافورة موسيقية ضخمة عند مدخلها، ومتحفاً خاصاً بالفنون الآسيوية.",
        desc_en: "In south-western Nice, one of Europe's largest urban parks at 7 hectares. It offers cultural and family activities, rare animals and birds, a huge musical fountain at its main entrance, and a museum of Asian arts.",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Parc_Phoenix_serre_Nice.jpg" },
      { num: "06", name_ar: "حديقة ألبرت الأول", name_en: "Jardin Albert Ier",
        desc_ar: "حديقة عامة رائعة في وسط نيس بالقرب من ساحة ماسينا، وهي واحدة من أقدم حدائق نيس. تجد فيها أشجار النخيل والورود العطرة والنباتات المختلفة من اليابان والصين والأمريكتين وأستراليا والهيمالايا، إضافة إلى نوافير المياه المذهلة وأقسام مخصّصة للأطفال.",
        desc_en: "A wonderful public garden in central Nice near Place Masséna — one of the city's oldest. Palm trees, fragrant roses and plants brought from Japan, China, the Americas, Australia and the Himalayas share space with stunning fountains and family play areas.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Jardin_Albert_1er.jpg" },
      { num: "07", name_ar: "سوق زهرة كور ساليا", name_en: "Cours Saleya Market",
        desc_ar: "أحد الأماكن التي تدبّ فيها الحركة والنشاط على مدار اليوم داخل نيس، ويستقطب عدداً كبيراً من الزوار على مدار العام. تجد فيه متاجر الورود ذات الألوان والأشكال المتعدّدة — فالمدينة تشتهر بزراعة الورد — إلى جانب الملابس والمنتجات الجلدية ومحلات التحف والاكسسوارات والهدايا التذكارية.",
        desc_en: "A market bursting with life from morning to evening in central Nice, drawing visitors year-round. Its flower stalls are legendary — Nice is famed for its roses — alongside clothes, leather goods, antiques, souvenirs and fine handmade crafts.",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Nizza.jpg" },
      { num: "08", name_ar: "أوبرا نيس", name_en: "Opéra de Nice",
        desc_ar: "من أشهر معالم نيس الثقافية، تُقدّم دار الأوبرا العروض الكلاسيكية والراقصة على مدار العام، وتُعدّ من أبرز المؤسسات الفنية في جنوب فرنسا.",
        desc_en: "One of Nice's most celebrated cultural landmarks. The opera house stages classical and ballet performances throughout the year and stands among the leading artistic institutions of southern France.",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/03/Op%C3%A9ra_de_Nice_%28fa%C3%A7ade_nord%29.jpg" },
    ],
  },

  bordeaux: {
    tagline_ar: "مدينة النبيذ · عاصمة أكيتان · تراث الملوك والنبلاء",
    tagline_en: "The city of wine · Capital of Aquitaine · Heritage of kings and nobles",
    section_title_ar: "أجمل معالم السياحة في بوردو",
    section_title_en: "The finest sights of Bordeaux",
    intro_ar:
      "بوردو مدينة فرنسية عرفها العرب باسم برديل، تقع على نهر غارون في جنوب غرب البلاد، بالقرب من مصبّ النهر عند خليج غاسكونيا بالمحيط الأطلسي، ويبلغ عدد سكانها مليون و100 ألف تقريباً. تُعدّ من أشهر المدن الفرنسية عالمياً بعد باريس، بشهرة تنبع من زراعة الدالية وتاريخ ملكي طويل تفخر به المدينة على الدوام.",
    intro_en:
      "Bordeaux — known to Arab visitors as Bardīl — sits on the River Garonne in south-western France, near its mouth at the Bay of Biscay on the Atlantic. Home to roughly 1.1 million people, it is one of the most world-famous French cities after Paris — a fame born not only from its vineyards but from a long royal history the city has cherished for centuries.",
    closing_ar: "«في بوردو يشرب التاريخ من كأس النبيذ.»",
    closing_en: "\u201CIn Bordeaux, history is served in a glass of wine.\u201D",
    attractions: [
      { num: "01", name_ar: "ساحة الكوميديا", name_en: "Place de la Comédie",
        desc_ar: "توجد ساحة الكوميديا في شارع سانت كاثرين التجاري، ويتفرّع منها الكثير من الشوارع التي تضم محلات راقية وفخمة. الممر الرئيسي إلى الأحياء الداخلية لبوردو المعروفة بضيق شوارعها وأثريّتها، وتُعدّ البيوت فيها من أكثر الأماكن جذباً للسياح، إلى جانب المطاعم الصغيرة التي تُضفي جوّاً رومانسياً.",
        desc_en: "Place de la Comédie opens off the shopping street of Rue Sainte-Catherine, radiating into narrow lanes filled with fine boutiques. The gateway to Bordeaux's old inner quarters — famed for their narrow, historic streets, welcoming little houses and romantic bistros.",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Bordeaux_Grand_Th%C3%A9%C3%A2tre_Vue_n%C2%B02.jpg" },
      { num: "02", name_ar: "مبنى الأوبرا الكبير", name_en: "Grand Théâtre (Opera House)",
        desc_ar: "بُني مبنى الأوبرا حسب طلب ماريشال دي ريتشيليو حاكم غويين، وصمّمه المهندس المعماري فيكتور لويس، وانتهى بناؤه عام 1780م. ينتمي إلى الهندسة النيوكلاسيكية، ويضم متحفاً صغيراً، وتُقام فيه على مدار السنة عشرات الحفلات الكلاسيكية والراقصة، وتعزف فيه كل شهر فرق موسيقية من أشهر فرق أوروبا.",
        desc_en: "Commissioned by the Maréchal de Richelieu, Governor of Guyenne, and designed by architect Victor Louis, the Grand Théâtre was completed in 1780. A neoclassical masterpiece, it houses a small museum and hosts dozens of classical concerts and ballets each year, welcoming leading European orchestras every month.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/GrandTheatreBordeaux2.jpg", tall: true },
      { num: "03", name_ar: "ساحة البورصة", name_en: "Place de la Bourse",
        desc_ar: "من أفضل المعالم السياحية في المدينة، تحتوي على مبانٍ كلاسيكية جميلة يرجع تاريخها إلى القرن الثامن عشر، مصمّمة على طول النهر. أُنشئت في الفترة 1730-1755م على يد مهندسين من عائلة غابرييل، ويتوسّطها نافورة النعم الثلاثة، وتحيط بها مبانٍ هامة كمتحف الجمارك ومبنى البورصة.",
        desc_en: "One of Bordeaux's finest sights: beautiful 18th-century classical buildings laid out along the river. Built between 1730 and 1755 by the Gabriel family of architects, its centrepiece is the Fountain of the Three Graces, framed by the Customs Museum and the old Stock Exchange.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Bordeaux_place_de_la_bourse_with_tram.JPG" },
      { num: "04", name_ar: "متحف الفنون الجميلة", name_en: "Musée des Beaux-Arts",
        desc_ar: "يقع متحف الفنون الجميلة في حديقة جاردان دي لا ميري العامة الجميلة، ويحتلّ جزءاً من مبنى قاعة المدينة. يقدّم فكرة رائعة عن تاريخ الفن الأوروبي، مع مجموعة تمتد من القرن الخامس عشر إلى القرن العشرين، وتُنظَّم اللوحات موضوعياً حسب العصر والبلد.",
        desc_en: "Set inside the pretty Jardin de la Mairie public park and part of the Hôtel de Ville, this museum offers a beautiful overview of European art from the 15th to the 20th century, its paintings arranged by period and country.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Mus%C3%A9e_Aquitaine.JPG" },
      { num: "05", name_ar: "متحف أكيتان", name_en: "Musée d'Aquitaine",
        desc_ar: "يوضّح متحف أكيتان بجلاء تاريخ بوردو ومنطقة أكيتان من عصور ما قبل التاريخ وحتى يومنا هذا. يحتوي على قطع استثنائية من العصور القديمة بما في ذلك قطعة Laussel Venus التي يعود تاريخها إلى 25000 قبل الميلاد، وعملات ذهبية من القرن الثاني قبل الميلاد، وتمثال لهرقل يعود إلى القرن الثالث.",
        desc_en: "The Musée d'Aquitaine traces the story of Bordeaux and the Aquitaine region from prehistory to the present. Its treasures include the Venus of Laussel (25,000 BCE), rare 2nd-century BCE gold coins, and a 3rd-century statue of Hercules.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Mus%C3%A9e_Aquitaine.JPG" },
      { num: "06", name_ar: "حوض آركاشون", name_en: "Arcachon Bay",
        desc_ar: "بعد زيارة بوردو يمكنك التوجّه جنوباً نحو حوض آركاشون لتحسّس مياه المحيط. مناظر برية بين الشواطئ الرملية وموانئ المحار الصغيرة، ملعبٌ رائع لعشّاق الطبيعة. اركب دراجتك في الغابات المزروعة بأشجار الصنوبر، أو تسلّق كثبان بيلات الرملية الشهيرة لتحصل من ارتفاع 109 أمتار على إطلالة بانورامية استثنائية.",
        desc_en: "South of Bordeaux, Arcachon Bay opens onto the ocean. Wild sand beaches and tiny oyster harbours make it a paradise for lovers of the sea and nature. Cycle through pine forests or climb the famous Dune du Pilat — 109 metres high — for panoramic views over Banc d'Arguin's turquoise waters.",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/d7/PassesBassin.JPG" },
      { num: "07", name_ar: "ساحة إسبلاناد (كوينكونس)", name_en: "Esplanade des Quinconces",
        desc_ar: "من أهم الساحات في المدينة، توجد بوسط بوردو وتُعدّ من أكبر الساحات في أوروبا. تتميّز بنافورة ضخمة أُنشئت في الفترة 1818-1828م لتكريم مجموعة من السياسيين الجمهوريين المعاصرين للثورة الفرنسية. يوجد بجانبها منتزه رائع يُطلّ على مناظر بحرية ساحرة، إلى جانب متحف التاريخ الطبيعي والحدائق النباتية.",
        desc_en: "One of Bordeaux's most important squares — and one of Europe's largest. Its grand fountain, built between 1818 and 1828 to honour republican politicians of the French Revolution, stands beside a park that opens onto stunning river views, near the Natural History Museum and Botanical Garden.",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Grande_Roue_Bordeaux_%28127782377%29.jpeg" },
      { num: "08", name_ar: "جسر بون دو بيير", name_en: "Pont de Pierre",
        desc_ar: "يُعتبر من أهم المعالم السياحية في المدينة، وهو جسر حجري رائع أُنشئ عام 1817م على يد المهندس المعماري الشهير كلود ديكامب، وانتهى بناؤه عام 1821م. يتميّز بإطلالته على نهر غارون، ويوجد به 17 قوساً لتحمّل التيارات القوية، بارتفاع 12 عموداً كورنثياً على السطح الخارجي.",
        desc_en: "One of Bordeaux's most iconic monuments — a majestic stone bridge begun in 1817 by architect Claude Deschamps and completed in 1821. It carries 17 arches across the Garonne to resist strong currents, with 12 Corinthian columns adorning its length.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Bordeaux_%C3%89glise_Saint-Michel_Fl%C3%A8che_Saint-Michel_Vue_sur_le_Pont_de_Pierre_1.jpg/3840px-Bordeaux_%C3%89glise_Saint-Michel_Fl%C3%A8che_Saint-Michel_Vue_sur_le_Pont_de_Pierre_1.jpg" },
    ],
  },

  chamonix: {
    tagline_ar: "سقف أوروبا · وطن التزلج · جبل مون بلان",
    tagline_en: "Roof of Europe · Home of skiing · At the foot of Mont Blanc",
    section_title_ar: "أجمل معالم السياحة في شامونيه",
    section_title_en: "The finest sights of Chamonix",
    intro_ar:
      "تُعتبر شامونيه من أهم مدن فرنسا السياحية، وواحدة من أقدم المنتجعات في فرنسا. تقع بالقرب من قمم جبال إيغويي روج، وتضم 16 قرية ومنتجعاً صحياً، بمناخ قاري رطب — معتدل في الصيف وبارد ثلجي في الشتاء. وجهة رئيسية للرياضات الشتوية، وتحتوي على أعلى محطة تلفريك في العالم، وأول مدينة تستضيف الألعاب الأولمبية الشتوية عام 1924م.",
    intro_en:
      "Chamonix is one of France's most important tourist towns and one of its oldest resorts. Nestled beside the Aiguilles Rouges, it contains 16 villages and a health spa, with a damp continental climate — mild in summer, cold and snowy in winter. A leading destination for winter sports, it hosts the world's highest cable car and, in 1924, staged the very first Winter Olympic Games.",
    closing_ar: "«حين تصعد شامونيه، ترى فرنسا كلها تحت قدميك.»",
    closing_en: "\u201CClimb Chamonix, and all of France lies beneath your feet.\u201D",
    attractions: [
      { num: "01", name_ar: "الجبل الأبيض (مون بلان)", name_en: "Mont Blanc",
        desc_ar: "يقع الجبل الأبيض في شامونيه على الحدود الفرنسية الإيطالية، ويُعدّ من أعلى جبال أوروبا الغربية. يشكّل جزءاً من الحدود الفرنسية مع إيطاليا، إذ يصل ارتفاعه إلى 4810 متر، ويكون دوماً مغطّى بالثلوج، ويشتهر باسم سقف أوروبا. يقدّم للزوار مسارات مشي رائعة عبر التلفريك أو تسلق القمة برفقة دليل.",
        desc_en: "Mont Blanc rises on the French–Italian border above Chamonix, the highest peak in Western Europe at 4,810 metres. Perpetually crowned in snow, it is nicknamed the Roof of Europe — accessible via cable car or, for experienced climbers with a guide, all the way to the summit.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Mont_Blanc_Aiguille.jpg", tall: true },
      { num: "02", name_ar: "قمة إيغويي دو ميدي", name_en: "Aiguille du Midi",
        desc_ar: "قمّة يزيد ارتفاعها عن 3800 متر، ومن أبرز رموز شامونيه السياحية. تستطيع الوصول إليها عبر محطات التلفريك التي تنقلك وتُطلعك على الكهوف الطبيعية الرائعة، مع منظر لا يُنسى حين تكون شامونيه وفرنسا بأكملها تحت ناظريك.",
        desc_en: "Soaring above 3,800 metres, the Aiguille du Midi is one of Chamonix's most iconic sights. Cable cars whisk you up past stunning natural caves to a view you will never forget — with Chamonix and much of France stretched beneath you.",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Aiguille-du-Midi-sundown.JPG" },
      { num: "03", name_ar: "فاليه بلانش", name_en: "Vallée Blanche",
        desc_ar: "أحد رموز مدينة شامونيه في فرنسا، عبارة عن مسار تزلج بطول 20 كم يقودك إلى أكبر كتلة جليدية وأعلى قمة — قمة الجبل الأبيض. في منتصف الطريق يمكنك المرور على المطاعم والمقاهي، ثم استئناف المسير قبل الوصول إلى محطة القطار التي تعيدك إلى شامونيه.",
        desc_en: "One of Chamonix's icons: a 20 km off-piste descent that leads through the largest glacier in the area, from the summit of Mont Blanc. Halfway down, restaurants and cafés await; then continue on skis to the train station that carries you back to Chamonix.",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/ValleeBlancheFromSE_%28cropped%29.JPG" },
      { num: "04", name_ar: "متحف شامونيه (المتحف الألبي)", name_en: "Chamonix Alpine Museum",
        desc_ar: "يمنحك متحف شامونيه الفرصة لاكتشاف الحقائق المثيرة عن تاريخ الوادي ومشاهدة مجموعة من المعروضات المثيرة للاهتمام، بما في ذلك مجموعة من المعادن والطباعة الحجرية والمطبوعات والملصقات القديمة التي تروي تطوّر المدينة بين القرنين الثامن عشر والعشرين.",
        desc_en: "The Chamonix Alpine Museum lets you dive into the valley's rich history, with fascinating exhibits: minerals, lithographs, and vintage prints and posters tracing the town's evolution from the 18th to the 20th century.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Mer_de_Glace_Glacier_in_France_-_2009-08-06.jpg" },
      { num: "05", name_ar: "قرية شامونيه", name_en: "Chamonix Village",
        desc_ar: "تعكس قرية شامونيه مزيجاً من التقليدية والحداثة، مع الشاليهات الألبية الجذابة والكنائس الباروكية والبروتستانتية التاريخية. تضم القرية فنادق حديثة فاخرة ونزلاً ريفياً رائعاً، إلى جانب بوتيكات فخمة وعشرات المطاعم التي تتنوّع بين المحلية والعالمية.",
        desc_en: "Chamonix village mixes tradition with modernity — charming Alpine chalets sit beside baroque churches and historic Protestant chapels. Luxury hotels, a wonderful country inn, elegant boutiques and dozens of local and international restaurants make it a place worth staying for days.",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Chamonix_valley_from_la_Fl%C3%A9g%C3%A8re%2C2010_07.JPG" },
    ],
  },
};
