import bordeauxRiverCruisesAsset from "@/assets/bordeaux-river-cruises.avif.asset.json";
import museeBeauxArtsBordeauxAsset from "@/assets/musee-beaux-arts-bordeaux.jpg.asset.json";
import esplanadeQuinconcesBordeauxAsset from "@/assets/esplanade-quinconces-bordeaux.png.asset.json";
import cannesPalaisFestivalsAsset from "@/assets/cannes-palais-festivals.jpg.asset.json";
import cannesMuseeDeLaMerAsset from "@/assets/cannes-musee-de-la-mer.jpg.asset.json";
import cannesOldTownAsset from "@/assets/cannes-old-town.jpg.asset.json";
import cannesVillaDomergueAsset from "@/assets/cannes-villa-domergue.jpg.asset.json";
import colmarQuaiDeLaPoissonnerieAsset from "@/assets/colmar-quai-de-la-poissonnerie.jpg.asset.json";
import lyonMuseeGadagneAsset from "@/assets/lyon-musee-gadagne.jpg.asset.json";
import niceEtoileAsset from "@/assets/nice-etoile.jpg.asset.json";

export type Attraction = {
  num: string;
  name_ar: string;
  name_en: string;
  desc_ar: string;
  desc_en: string;
  image: string;
  tall?: boolean;
};

export type CityFeature = {
  tagline_ar: string;
  tagline_en: string;
  /** Paragraphs shown BEFORE the attractions list, in exact source order. */
  intro_ar: string[];
  intro_en: string[];
  section_title_ar: string;
  section_title_en: string;
  closing_ar: string;
  closing_en: string;
  attractions: Attraction[];
  /** URL of the original 100region.com source article. */
  source_url: string;
};

// Placeholder used when the original city article's image cannot be safely mirrored.
const MISSING_IMAGE = "__missing__";

export const CITY_FEATURES: Record<string, CityFeature> = {
  paris: {
    tagline_ar: "مدينة النور · عاصمة فرنسا · وجهة الفن والأزياء والثقافة",
    tagline_en: "The City of Light · Capital of France · Home of art, fashion and culture",
    section_title_ar: "أجمل وأشهر أماكن السياحة في باريس",
    section_title_en: "The finest sights of Paris",
    source_url: "https://100region.com/?p=11215&amp=1",
    intro_ar: [
      "باريس، العاصمة الفرنسية وأجمل مدن فرنسا والعالم السياحية، مدينة النور أو مدينة الحب كما يحلو للبعض تسميتها. تعتبر باريس منذ عقود مضت وإلى يومنا هذا واحدة من المراكز الرائدة في العالم للأعمال التجارية والأزياء والترفيه والفن والثقافة، يرتبط اسمها بالمعالم العالمية الشهيرة والمتاحف والكاتدرائيات وهي الوجهة الأولى عند السياحة في فرنسا.",
    ],
    intro_en: [
      "Paris — the French capital and the loveliest of France's tourist cities. The City of Light, or the City of Love as some prefer to call it, has for decades been a leading centre for business, fashion, entertainment, art and culture. Its name is bound to world-famous landmarks, museums and cathedrals, and it remains the first destination for tourism in France.",
    ],
    closing_ar: "«باريس تستحق الزيارة دائماً، مهما تغيّرت الفصول.»",
    closing_en: "\u201CParis is always a good idea, no matter the season.\u201D",
    attractions: [
      { num: "01", name_ar: "برج إيفل", name_en: "Eiffel Tower",
        desc_ar: "برج إيفل في باريس من معالم باريس السياحية البارزة، إن لم يكن فرنسا كلها. بُني عام 1889م على يد المهندس جوستاف إيفل، يصل ارتفاعه إلى 324 متراً ويُعدّ أطول مباني العاصمة باريس على الإطلاق، إضافة إلى أنه أحد أكثر الأماكن السياحية في باريس زيارة.",
        desc_en: "The Eiffel Tower is one of the most iconic landmarks of Paris — if not all of France. Built in 1889 by engineer Gustave Eiffel, it rises 324 metres and is the tallest building in the capital, and one of the most visited attractions in the city.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Tour_Eiffel_Wikimedia_Commons_%28cropped%29.jpg", tall: true },
      { num: "02", name_ar: "شارع الشانزليزيه", name_en: "Champs-Élysées",
        desc_ar: "يُعتبر شارع الشانزليزيه في باريس من أشهر الشوارع الفرنسية وأطولها، وهو من أرقى وأفخم الشوارع السياحية والتجارية في العالم. يحوي الشارع أرقى المحلات التجارية العالمية والمطاعم الراقية، كما تكثر على جنبات الرصيف والطرقات الجانبية العديد من المقاهي.",
        desc_en: "The Champs-Élysées is one of France's longest and most famous avenues, and one of the most elegant shopping and tourist streets in the world. It is lined with luxury boutiques, fine restaurants, and countless cafés on its side streets.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Avenue_des_Champs-%C3%89lys%C3%A9es_July_24%2C_2009_N1.jpg" },
      { num: "03", name_ar: "قوس النصر", name_en: "Arc de Triomphe",
        desc_ar: "قوس النصر في باريس قوس يقع في بداية شارع الشانزليزيه الشهير في ميدان شارل ديغول أو ما كان يُعرف باسم ميدان النجمة في قلب العاصمة باريس. يُعدّ من معالم باريس السياحية الشهيرة ومن أهم رموز المدينة بعد برج إيفل، ويبلغ ارتفاع القوس 50 متراً.",
        desc_en: "The Arc de Triomphe stands at the start of the Champs-Élysées in Place Charles de Gaulle — formerly Place de l'Étoile — at the heart of Paris. Rising 50 metres, it is one of the city's most beloved symbols after the Eiffel Tower.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Arc_de_Triomphe%2C_Paris_21_October_2010.jpg/1280px-Arc_de_Triomphe%2C_Paris_21_October_2010.jpg", tall: true },
      { num: "04", name_ar: "ميدان الكونكورد", name_en: "Place de la Concorde",
        desc_ar: "ميدان الكونكورد أحد أكبر ساحات وميادين باريس العاصمة الفرنسية. تقع ساحة الكونكورد في نهاية شارع الشانزليزيه من طرفه الشرقي، ويحوي الميدان مسلّة مصرية ضخمة أهداها الخديوي إسماعيل إلى لويس فيليب عام 1831.",
        desc_en: "Place de la Concorde is one of the largest squares in Paris, at the eastern end of the Champs-Élysées. At its centre stands a great Egyptian obelisk, gifted by Khedive Ismail to King Louis-Philippe in 1831.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Place_de_la_Concorde_from_the_Eiffel_Tower%2C_Paris_April_2011.jpg/1280px-Place_de_la_Concorde_from_the_Eiffel_Tower%2C_Paris_April_2011.jpg" },
      { num: "05", name_ar: "الحي اللاتيني", name_en: "Latin Quarter",
        desc_ar: "يُعتبر الحي اللاتيني من أشهر الأماكن السياحية في باريس ومن أقدمها أيضاً، يقع على الضفة اليسرى لنهر السين حيث يضم عدداً كبيراً من المباني التاريخية، كما أنه يوفر لزائريه من السياح متعة استكشاف الحياة الباريسية الحقيقية من خلال المطاعم الفرنسية والمقاهي وأشهر علامات الموضة الفرنسية والعالمية.",
        desc_en: "The Latin Quarter is one of the oldest and most famous neighbourhoods in Paris, on the Left Bank of the Seine. It holds many historic buildings and lets visitors explore authentic Parisian life through French bistros, cafés and the most famous French and international fashion houses.",
        image: "/__l5e/assets-v1/404a7b7d-f606-41da-8e1a-52befacb1ec2/place-du-terre-paris.jpg" },
      { num: "06", name_ar: "باريس ديزني لاند", name_en: "Disneyland Paris",
        desc_ar: "باريس ديزني لاند، وتُدعى أيضاً ديزني لاند ريزورت باريس أو يورو ديزني، تُعتبر من معالم باريس الترفيهية. تقع على بُعد 32 كم من مركز العاصمة الفرنسية باريس، وتضم ديزني لاند مدينتَي ملاهي و7 فنادق، جميعها عائدة لشركة والت ديزني، وتُعدّ ثاني أكبر مدينة ديزني لاند خارج الولايات المتحدة الأمريكية بعد طوكيو ديزني لاند.",
        desc_en: "Disneyland Paris — also called Disneyland Resort Paris or Euro Disney — is the city's flagship entertainment destination, 32 km from central Paris. It contains two theme parks and seven hotels, all owned by Walt Disney, making it the second-largest Disneyland outside the United States after Tokyo Disneyland.",
        image: "https://upload.wikimedia.org/wikipedia/en/8/88/Sleeping_Beauty_Castle%2C_Disneyland%2C_Paris.jpg" },
      { num: "07", name_ar: "متحف اللوفر", name_en: "Louvre Museum",
        desc_ar: "متحف اللوفر واحد من أكبر المتاحف الكبيرة في العالم كما أنه يُعدّ أشهر متحف في باريس، حيث يشكّل معلماً مهماً وسط مدينة باريس في فرنسا. يتم عرض ما يقرب من 35 ألف من الكائنات من عصور ما قبل التاريخ إلى القرن الحادي والعشرين على مساحة 60,600 متر مربع.",
        desc_en: "The Louvre is one of the world's largest museums and Paris's most famous, at the very heart of the city. It displays some 35,000 objects — from prehistory to the 21st century — across 60,600 square metres.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Louvre_Museum_Wikimedia_Commons.jpg/1280px-Louvre_Museum_Wikimedia_Commons.jpg" },
      { num: "08", name_ar: "متحف بيكاسو", name_en: "Musée Picasso",
        desc_ar: "متحف بيكاسو في باريس هو ثاني أكبر متحف للفنان العالمي بيكاسو بعد متحف بيكاسو بمدينة برشلونة في إسبانيا. مبنى متحف بيكاسو في باريس بُني عام 1659، وقد كان قصراً ثم تغيّر لمدرسة وانتقلت ملكيته للعديد من الأشخاص ثم سيطرت عليه حكومة الثورة الفرنسية، يُعتبر من أشهر متاحف باريس.",
        desc_en: "The Musée Picasso in Paris is the second-largest museum dedicated to Picasso after the one in Barcelona. Its building, completed in 1659, was originally a mansion, later a school, before being seized by the government of the French Revolution. It stands among Paris's most celebrated museums.",
        image: "/__l5e/assets-v1/960d8683-0c13-4c60-8a0d-2d699e0e6903/musee-picasso-paris.jpg" },
      { num: "09", name_ar: "حدائق لوكسمبورغ", name_en: "Luxembourg Gardens",
        desc_ar: "جاردان دو لوكسمبورغ، أو حدائق لوكسمبورغ، هي ثاني أكبر الحدائق في باريس العامة. تحتوي الحديقة على مساحة 224,500 متر مربع، وتشتهر بالجو الهادئ مع الأحواض المحيطة وسلسلة من التماثيل التي تخلّد ملكات فرنسا السابقات والقديسين.",
        desc_en: "The Jardin du Luxembourg is the second-largest public garden in Paris at 224,500 square metres. It is famed for its peaceful atmosphere, ornamental pools and the long line of statues honouring former queens of France and saints.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/LuxembourgMontparnasse.JPG/1280px-LuxembourgMontparnasse.JPG" },
      { num: "10", name_ar: "حديقة النباتات", name_en: "Jardin des Plantes",
        desc_ar: "حديقة النباتات في باريس من أهم حدائق باريس، وهي حديقة تقع غير بعيد عن معلمين هامّين بالنسبة للسائح العربي، هما: المعهد الإسلامي (وفيه أكبر مساجد باريس)، ومعهد العالم العربي.",
        desc_en: "The Jardin des Plantes is one of Paris's most important gardens, near two landmarks of special interest to Arab visitors: the Islamic Institute (home of the largest mosque in Paris) and the Arab World Institute.",
        image: "/__l5e/assets-v1/6ac13bbd-52f1-4c07-a260-3341aae77e82/jardin-des-plantes-paris.jpg" },
      { num: "11", name_ar: "قصر فرساي", name_en: "Palace of Versailles",
        desc_ar: "يُعدّ قصر فرساي في باريس من أجمل قصور باريس وفرنسا عامة، بُني هذا القصر عام 1624 ويقع على بُعد 20 كيلومتراً جنوب باريس. يتميّز قصر فرساي بوجود قاعة المرايا الشهيرة كما أنه يحوي آلاف اللوحات والأعمال الفنية المذهلة، ويُعدّ القصر مثالاً على الفن المعماري في فرنسا. مفتوح بشكل يومي من الساعة 09:00 صباحاً وحتى 06:30 مساءً، سعر التذكرة 80 يورو أي ما يعادل 96.85 دولار أمريكي.",
        desc_en: "The Palace of Versailles is among the most beautiful palaces of Paris and of France as a whole. Built in 1624, it lies 20 km south of Paris. It is renowned for the Hall of Mirrors and holds thousands of paintings and works of art — a masterpiece of French architecture. Open daily 09:00–18:30; tickets around €80 (approx. USD 96.85).",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_081_%28cropped%29.jpg/1280px-Vue_a%C3%A9rienne_du_domaine_de_Versailles_par_ToucanWings_-_Creative_Commons_By_Sa_3.0_-_081_%28cropped%29.jpg" },
      { num: "12", name_ar: "قصر غارنييه", name_en: "Palais Garnier",
        desc_ar: "يقع قصر غارنييه والمعروف باسم أوبرا باريس في مبنى فخم وغاية في الروعة، كان قد قام بتأسيسه لويس الرابع عشر سنة 1669م بطلب من نابليون الثالث ضمن الحملة التي أُقيمت لإعادة إعمار باريس. يُعدّ دار الأوبرا في باريس الأكبر من بين دور الأوبرا في العالم.",
        desc_en: "The Palais Garnier — known as the Paris Opera — occupies one of the most sumptuous buildings in the city. Founded under Louis XIV in 1669 and later commissioned by Napoleon III as part of the great redevelopment of Paris, it is one of the largest opera houses in the world.",
        image: "/__l5e/assets-v1/2edcf21d-1f2d-4503-b913-bee174d4be06/palais-garnier-paris.avif" },
      { num: "13", name_ar: "قصر الإليزيه", name_en: "Élysée Palace",
        desc_ar: "قصر الإليزيه من أشهر قصور باريس ويُعدّ المقر الرسمي لرئاسة الجمهورية الفرنسية حيث يضم مكتب رئيس الدولة ومكان اجتماع مجلس الوزراء. يقع قصر الإليزيه بالقرب من شارع الشانزليزيه الشهير في باريس، بُني القصر في القرن الثامن عشر وقد أُجريت عليه العديد من التعديلات خلال القرون التالية غير أنه حافظ على تصميمه الكلاسيكي.",
        desc_en: "The Élysée Palace is one of the most renowned palaces in Paris and the official residence of the French Republic, holding the office of the head of state and Cabinet meetings. It lies near the Champs-Élysées and dates from the 18th century, keeping its classical design across the centuries.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Secretary_Pompeo_Arrives_to_Meet_with_French_Foreign_Minister_Le_Drian_in_Paris_%2850610423656%29_%28cropped%29.jpg/1280px-Secretary_Pompeo_Arrives_to_Meet_with_French_Foreign_Minister_Le_Drian_in_Paris_%2850610423656%29_%28cropped%29.jpg" },
    ],
  },

  marseille: {
    tagline_ar: "ثاني أكبر مدن فرنسا · عاصمة الثقافة الأوروبية 2013 · مدينة البحر والميناء",
    tagline_en: "France's second city · European Capital of Culture 2013 · A city of sea and port",
    section_title_ar: "السياحة بمدينة مارسيليا",
    section_title_en: "Sightseeing in Marseille",
    source_url: "https://100region.com/?p=33141&amp=1",
    intro_ar: [
      "تُعد مرسيليا إحدى أهم المدن الفرنسية، وقد اكتسبت هذه الأهمية بفعل عدة عوامل، منها أنها ثاني أكبر منطقة حضرية في فرنسا بعد باريس، كما أنها تحتل مكانة بارزة في قوائم السياحة في فرنسا، فهي تُعتبر أكبر مدينة فرنسية ساحلية، حيث تقع على ساحل فرنسا الجنوبي، وتمتلك ميناء مرسيليا الذي يُعتبر أكبر ميناء بحري في فرنسا، فضلاً عن المجال الثقافي ودور هذه المدينة فيه، حيث تم اختيارها في عام 2013م كعاصمة للثقافة الأوروبية، وفوق كل ذلك فهي تحتوي تقريباً على أكبر جالية عربية مسلمة في فرنسا.",
      "هذه المدينة تُعتبر من المراكز الرئيسية في المجال الصناعي التجاري، بسبب ميناء مرسيليا ومطار مرسيليا الذي يُعتبر رابع أكبر مطار في فرنسا. أخذت مارسيليا جزءاً كبيراً من السياحة في فرنسا، فهي المدينة المشهورة بشواطئها وبحارها وعماراتها ومبانيها ومعارضها وأسواقها ومتاحفها، حيث يوجد فيها أكثر من 24 متحف و42 مسرح، وهي من المدن المناسبة للسفر سواء كان ذلك لوحدك أو مع من تحبه.",
      "أفضل وقت للسفر والسياحة في مارسيليا يكون خلال فصلَي الربيع والصيف، أي في الفترة ما بين شهرَي مارس إلى أغسطس، حيث تكون درجات الحرارة معتدلة ودافئة، مما يسمح لك بالتنزّه بحرية مطلقة وممارسة الرياضات المائية وركوب القوارب وحضور المهرجانات الفرنسية المليئة بالموسيقى الحية.",
      "المدة المثالية للسفر والسياحة في مارسيليا هي تقريباً ثلاثة أيام، يمكنك خلالها زيارة القرى المجاورة واستكشاف العجائب الطبيعية بالمدينة، وقضاء الكثير من الوقت في البحر للاسترخاء، إلى جانب زيارة أبرز معالم مرسيليا كالميناء القديم ومتحف كاسياس للفنون والتقاليد الشعبية، وتسلق المنحدرات، والتجوّل وسط حقول اللافندر الجميلة.",
    ],
    intro_en: [
      "Marseille is one of France's most important cities. Its stature comes from several things: it is France's second-largest urban area after Paris, holds a leading place on France's tourism map, and is the country's largest coastal city — sitting on the southern French coast with the Port of Marseille, France's biggest seaport. Chosen European Capital of Culture in 2013, it also hosts one of France's largest Arab and Muslim communities.",
      "The city is a major industrial and commercial hub thanks to its port and to Marseille Airport — France's fourth-largest. Marseille draws a big share of French tourism with its beaches, seascapes, architecture, exhibitions, markets and museums — over 24 museums and 42 theatres — and it suits both solo travellers and couples.",
      "The best time to visit Marseille is spring and summer, from March through August: temperatures are mild and warm, perfect for water sports, boat trips and French festivals full of live music.",
      "The ideal length of stay is about three days — enough to visit nearby villages, explore the city's natural wonders, relax by the sea, and see key sights: the Old Port, the museum of folk arts and traditions, cliff climbing and walks through lavender fields.",
    ],
    closing_ar: "«في مارسيليا يلتقي البحر بالتاريخ.»",
    closing_en: "\u201CIn Marseille, the sea meets history.\u201D",
    attractions: [
      { num: "01", name_ar: "كاتدرائية نوتردام دو باري", name_en: "Notre-Dame Cathedral",
        desc_ar: "بسبب عظمتها فقد اختارها الكاتب الشهير فيكتور هوجو مسرحاً لروايته أحدب نوتردام. تعني كاتدرائية السيدة العذراء، وهي كاتدرائية كاثوليكية تعود إلى القرون الوسطى، وتُشكّل واحدة من أروع نماذج العمارة القوطية الفرنسية، وهي أيضاً من أشهر مباني الكنيسة الكاثوليكية في فرنسا وفي العالم. تحتوي بداخلها على بعض أهم الآثار الكاثوليكية مثل تاج الشوك المزعوم، وشظية من الصليب الحقيقي، وواحدة من المسامير المقدسة، لذا تحظى هذه الكاتدرائية بدرجة عالية جداً من الزيارات.",
        desc_en: "So great is its majesty that Victor Hugo chose it as the setting for The Hunchback of Notre-Dame. This Catholic cathedral of Our Lady dates from the Middle Ages and is one of the finest examples of French Gothic architecture, one of the most famous Catholic churches in France and the world. It holds some of the most important Catholic relics — the reputed Crown of Thorns, a fragment of the True Cross, and one of the Holy Nails — drawing a very high number of visitors.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/Notre-Dame_de_la_Garde_aerial_view_2020.jpeg", tall: true },
      { num: "02", name_ar: "الميناء القديم", name_en: "The Old Port (Vieux-Port)",
        desc_ar: "يقع هذا الميناء في نهاية شارع Canebiere، الذي يُعتبر الشارع الرئيسي والمكان الشعبي في مرسيليا، فيما يضم حوله عدداً من المعالم المهمة والبارزة. ومن بين هذه المعالم دير سانت فيكتور الذي يُعتبر أحد أقدم دور العبادة المسيحية في فرنسا، وفندق قاعة المدينة، والعبّارة التاريخية التي تُبحر بين الجانبين المتقابلين للميناء القديم، ومتحف رومان دوك الشهير.",
        desc_en: "The Old Port lies at the end of La Canebière — Marseille's main and most popular avenue — surrounded by important sights: Saint-Victor Abbey, one of France's oldest Christian houses of worship; the Hôtel de Ville; the historic ferry that crosses between the two banks; and the celebrated Roman Docks Museum.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Marseille_Old_Port.jpg/3840px-Marseille_Old_Port.jpg" },
      { num: "03", name_ar: "متحف الحضارات الأوروبية", name_en: "Museum of European Civilisations (MuCEM)",
        desc_ar: "في كل دولة متحف يجسّد ماضي هذه الدولة، وفي كل مدينة متحف يخلّد ماضي هذه المدينة، أما أن تجد متحفاً يخلّد حضارات مختلفة ويحفظها فهذا هو العجب. متحف الحضارات الأوروبية الواقع في مدينة مرسيليا يُعتبر من الرموز الكبيرة لمدينة مرسيليا، ومحطّ أنظار من ينوي السياحة في فرنسا، فقد افتُتح في العام 2013م، في نفس السنة التي تم تصنيف مرسيليا فيها كعاصمة الثقافة الأوروبية. مخصّص للحضارات الأوروبية والبحر الأبيض المتوسط، وقد صُمّم من الحجر والماء والرياح على شكل مكعّب يبلغ حجمه 15,000 متر مربع، ويضم معارض وقاعات احتفالات تحت الأرض ومكتبة كتب ومطعم.",
        desc_en: "Every country has a museum of its past — but a museum that preserves whole civilisations is a wonder. MuCEM is one of Marseille's great symbols, opened in 2013, the same year the city was named European Capital of Culture. Dedicated to Mediterranean and European civilisations, its 15,000 m² cube of stone, water and wind holds underground exhibition halls and event spaces, a library and a restaurant.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/%22Beeindruckende_Architektur%22._5.jpg/3840px-%22Beeindruckende_Architektur%22._5.jpg" },
      { num: "04", name_ar: "سوق نواي Noailles", name_en: "Noailles Market",
        desc_ar: "سوق نواي مكان رائع ومفعم بالحياة في مدينة مرسيليا الفرنسية. إن كنت من محبّي جولات التسوق فيمكنك التسوق خلاله وشراء الأقمشة متعددة الألوان، ومختلف أنواع الطعام والتوابل الأفريقية والهندية، والأدوات المنزلية والاكسسوارات وغيرها الكثير.",
        desc_en: "Noailles Market is a vibrant place in the heart of Marseille. Shoppers can find colourful fabrics, all kinds of African and Indian foods and spices, household goods, accessories and much more.",
        image: "/__l5e/assets-v1/f1c88381-eb5d-4795-8e12-42fb0b84e029/marche-de-noailles-marseille.jpg" },
      { num: "05", name_ar: "حي لو بانيير", name_en: "Le Panier District",
        desc_ar: "لو بانيير هو أقدم حي في مدينة مرسيليا، وهو يُعدّ المركز التاريخي والقلب الثقافي للمدينة، كما يقع هذا الحي الملوّن في موقع رائع على أحد التلال فوق الميناء القديم. من أجمل أماكن السياحة في مارسيليا، يمكنك الاستمتاع بالتجوّل في شوارعه القديمة المرصوفة بالحجر والمنحدرة والضيّقة، والتقاط الصور على اللوحات الجدارية على جوانب المباني ذات الألوان الجميلة، واكتشاف متاجر الحرفيين المحليين ومحلات الأطعمة والمعارض الفنية.",
        desc_en: "Le Panier is Marseille's oldest quarter and its historic cultural heart, perched on a hill above the Old Port. Wander its narrow, sloping cobbled streets, photograph the murals on the colourful buildings, and discover artisan workshops, delicatessens and small galleries.",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Rue_Panier_Marseille.jpg" },
      { num: "06", name_ar: "حديقة كالانك الوطنية", name_en: "Calanques National Park",
        desc_ar: "حديقة كالانك الوطنية Parc National des Calanques موقع طبيعي رائع، حيث يلتقي البحر الأبيض المتوسط بجبال كالانك الصخرية. توفّر لك الحديقة فرصة الاستمتاع بمشاهدة المناظر الطبيعية والجدران الصخرية المهيبة من الحجر الجيري، مع خلجان مليئة ببرك من المياه المالحة بألوان فيروزية ساحرة، فضلاً عن ممارسة العديد من الأنشطة الرياضية في الهواء الطلق كالسباحة والتجديف بالكاياك وركوب القوارب واليخوت والمشي لمسافات طويلة وتسلق الصخور.",
        desc_en: "Calanques National Park is a stunning natural site where the Mediterranean meets sheer limestone cliffs. Enjoy dramatic scenery and turquoise coves, and try swimming, kayaking, boating and yachting, long hikes and rock climbing.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/En-Vau_calanque_4.jpg/3840px-En-Vau_calanque_4.jpg", tall: true },
    ],
  },

  lyon: {
    tagline_ar: "عاصمة إقليم رون · التراث العالمي لليونسكو · ملتقى الرون والساون",
    tagline_en: "Capital of the Rhône · UNESCO World Heritage · Meeting of the Rhône and Saône",
    section_title_ar: "السياحة بمدينة ليون",
    section_title_en: "Sightseeing in Lyon",
    source_url: "https://100region.com/?p=33169&amp=1",
    intro_ar: [
      "تُعتبر مدينة ليون عاصمة لإقليم رون الواقع في جنوب شرق فرنسا، وتحظى بأهمية كبرى لكونها ثاني أكبر منطقة حضرية في فرنسا، وتشتهر بالمعالم التاريخية والحضارية فيها، وقد تم إدراجها ضمن لائحة اليونسكو للتراث العالمي، فضلاً عن أنها تلعب دوراً بارزاً في مجال السينما، كما تشتهر بمهرجان الأضواء Festival of Lights وفنون الطبخ العالمية.",
      "تحتل ليون موقعاً استراتيجياً هاماً، حيث تقع عند ملتقى نهرَي الرون والساون، وتتميّز هذه المدينة بمناخها الذي يجمع بين المناخ المحيطي والمناخ شبه القاري، وتُعتبر من مناطق فرنسا الباردة في الشتاء، ولكن ذلك لم يمنع من ينوي السياحة في فرنسا من زيارة هذه المدينة الرائعة ومشاهدة معالمها الأثرية والحضارية، والاطلاع على ثقافتها وتاريخها وحاضرها عبر زيارة المتاحف والمطاعم والفنادق، وحضور المهرجانات والفعاليات التي تُقام سنوياً فيها.",
    ],
    intro_en: [
      "Lyon is the capital of the Rhône region in south-eastern France and France's second-largest urban area. Famed for its historic and cultural landmarks — a UNESCO World Heritage listing — Lyon also plays a leading role in cinema, hosts the celebrated Festival of Lights, and is renowned for its world-class cuisine.",
      "Strategically placed at the meeting of the Rhône and Saône rivers, Lyon has a mixed oceanic and semi-continental climate. Its winters are cool, but that never stops visitors from enjoying its heritage, culture and modern life through its museums, restaurants, hotels and the many festivals it hosts each year.",
    ],
    closing_ar: "«في ليون يجتمع النهران، والتاريخ، والذوق.»",
    closing_en: "\u201CIn Lyon, two rivers, history and taste all meet.\u201D",
    attractions: [
      { num: "01", name_ar: "حديقة بارك دي لا تيت دي أور", name_en: "Parc de la Tête d'Or",
        desc_ar: "حديقة حضرية كبيرة جداً، حيث تبلغ مساحتها 117 هكتار، ونظراً لقلة المنتزهات الأخرى في ليون، فقد اكتسبت هذه الحديقة طابعاً شعبياً وشهرة واسعة، خاصة مع وجود البحيرة الجميلة، ومناظر القوارب المتحركة فيها. وبالنسبة لمحبّي الرياضة من المشي والركض أو راكبي الدراجات، فإنها تُعدّ المكان الأفضل لهم، ونظراً للإقبال الكبير من الناس لزيارة هذه الحديقة، فقد تم وضع حديقة حيوانات كبيرة فيها، تحتوي على زرافات وفيلة وغزلان وزواحف وغيرها.",
        desc_en: "A vast 117-hectare urban park loved for its lake and boat rides. With few large parks nearby, it has become Lyon's most popular escape, ideal for walking, running and cycling — and its large free zoo home to giraffes, elephants, deer and reptiles.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/56/Parc_de_la_T%C3%AAte_d%27Or_Vue_sur_le_lac7.jpg" },
      { num: "02", name_ar: "متحف التقاليد الشعبية", name_en: "Museum of Popular Traditions",
        desc_ar: "نسمع كثيراً عن المتاحف كمتحف الشوكولاتة، وهو أمر غريب جداً أن تجد متحفاً للشوكولاتة، ولكن الأغرب هو متحف للتقاليد الشعبية، ينبغي وضعه في متحف آخر لأنه بذاته تحفة. يقع هذا المتحف في وسط مدينة ليون، وتُركّز أغلب مقتنياته على الفعاليات والأنشطة الشعبية للناس من الحاضر والماضي.",
        desc_en: "We often hear of unusual museums — even one for chocolate. Stranger still is a Museum of Popular Traditions, itself a work of art. In the heart of Lyon, its collections focus on everyday life and popular activities of people past and present.",
        image: lyonMuseeGadagneAsset.url },
      { num: "03", name_ar: "ساحة بلكور", name_en: "Place Bellecour",
        desc_ar: "ساحة كبيرة تقع في وسط مدينة ليون، وتُعتبر من أكبر المناطق المربعة المفتوحة في فرنسا وأكبر ساحة مشاة فيها، وفي منتصف الحديقة يتربّع تمثال فروسي للملك لويس الرابع عشر. كما يحتوي على جناحين: الجناح الأول يضم مكتب المعلومات السياحية في ليون، والجناح الثاني يضم معرضاً فنياً، أيضاً فقد تم ضم الساحة ضمن لائحة اليونسكو للتراث العالمي.",
        desc_en: "A great square at the centre of Lyon — one of France's largest open squares and its biggest pedestrian plaza. An equestrian statue of Louis XIV stands at its centre. Two pavilions house Lyon's tourist office and an art gallery, and the square is part of Lyon's UNESCO World Heritage listing.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/99/Place_Bellecour_%28Lyon%2C_2024%2C_version_recentr%C3%A9e_2%29.jpg" },
      { num: "04", name_ar: "المدينة القديمة", name_en: "Old Lyon (Vieux Lyon)",
        desc_ar: "تُعدّ مدينة ليون القديمة مكاناً مثالياً للاستمتاع بتاريخ مدينة ليون، مع المباني والكنائس المذهلة التي يعود تاريخها إلى آلاف السنين، حيث يضيء ماضي ليون هذا الجانب من المدينة. فانضم في جولة مشي مجانية في ليون القديمة، والتي تفتخر بالشوارع الضيقة المرصوفة بالحصى مع المحلات الساحرة ومحلات المواد الغذائية والمطاعم والمقاهي، حيث يمكنك السير عبر الممرات السرية التي تربط الشوارع المختلفة، والتي تُسمى traboules، والتي كانت تُستخدم من قبل عمّال الحرير خلال عصر النهضة لحماية بضائعهم من الطقس العاصف عندما كانت ليون مركز صناعة الحرير. ويمكنك عند زيارة المدينة القديمة الدخول إلى كاتدرائية Saint-Jean، وهي مثال ممتاز للعمارة القوطية.",
        desc_en: "Old Lyon is a perfect place to soak up the city's history among ancient buildings and churches. Take a free walking tour along its narrow cobbled streets lined with charming shops, delicatessens, restaurants and cafés, and step through the traboules — hidden passages once used by Renaissance silk workers to protect goods from storms when Lyon was the silk-making capital. Don't miss Saint-Jean Cathedral, a fine Gothic example.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Vieuxlyon_saintjean_toits.jpg", tall: true },
    ],
  },

  cannes: {
    tagline_ar: "مدينة الأثرياء · موطن مهرجان كان السينمائي · الواجهة الفنية بعد باريس",
    tagline_en: "The city of the wealthy · Home of the Cannes Film Festival · France's second art capital",
    section_title_ar: "السياحة بمدينة كان",
    section_title_en: "Sightseeing in Cannes",
    source_url: "https://100region.com/?p=33197&amp=1",
    intro_ar: [
      "بجوار مدينة نيس في الجنوب، تقع مدينة كان الفرنسية، وقد حصلت على لقب مدينة الأثرياء وحقّ لها ذلك، فهي أكثر مكان مرّ عليه أغلب مشاهير العالم، وارتبط اسمها بالطبقة الغنية من الأثرياء ورجال الأعمال والفنانين ومشاهير العالم، بما تستضيفه هذه المدينة من مهرجانات ومؤتمرات عالمية، وما تحتويه أيضاً من فنادق ومطاعم عالية المستوى، ومتاحف شهيرة أشهرها متحف Castre ومقتنياته الفريدة.",
      "إضافةً إلى الكنائس الرائعة والحدائق والمنتزهات والمطارات الدولية، والمعارض والبيوت والقصور والفلل الخاصة بالمهرجانات، فمدينة كان هي موطن كل من ينوي السفر إلى فرنسا، خاصة وأن المدينة تستضيف سنوياً المهرجان الذي تمت تسميته على اسم المدينة — مهرجان كان السنوي.",
    ],
    intro_en: [
      "Just along the coast from Nice sits Cannes, rightly nicknamed the city of the wealthy — the meeting point of the world's celebrities. Its name is bound to the rich and famous: businessmen, artists and stars, drawn by global festivals and conferences, world-class hotels and restaurants, and famous museums — above all the Musée de la Castre with its unique collections.",
      "Add to that fine churches, gardens, parks and international airports, together with exhibitions, mansions, palaces and festival villas, and Cannes becomes the home base for anyone heading to France — especially thanks to the annual event that gave it its name, the Cannes Film Festival.",
    ],
    closing_ar: "«على البساط الأحمر يبدأ مساء كان.»",
    closing_en: "\u201CEvening in Cannes begins on the red carpet.\u201D",
    attractions: [
      { num: "01", name_ar: "قصر الاحتفالات وقاعة المؤتمرات", name_en: "Palais des Festivals et des Congrès",
        desc_ar: "أن يجتمع مشاهير العالم وممثّليهم وفنانيهم في مكان واحد أمر شبه مستحيل، لكن هنا في فرنسا أي شيء ممكن. نحن نتحدث عن رمز من رموز فرنسا، وهو قصر الاحتفالات وقاعة المؤتمرات بمدينة كان الفرنسية، الذي يحتضن كل الاحتفالات والمراسم والمهرجانات في المدينة، وعلى الأخص المهرجان السينمائي الدولي أو كما يُسمى مهرجان كان السينمائي. ويُضاف إلى ذلك أيضاً مهرجان كان ليونز الدولي للإبداع، كما يحتضن القصر المؤتمرات الأخرى المختلفة، وتبلغ المساحة المخصّصة للمعارض 25 ألف متر مربع، مع البساط الأحمر الطويل الذي يشتهر به المكان.",
        desc_en: "That the world's celebrities gather in one place seems impossible — yet in France anything is possible. The Palais des Festivals et des Congrès is a French icon, host to Cannes' every ceremony and festival, above all the Cannes International Film Festival and Cannes Lions International Festival of Creativity. It offers 25,000 m² of exhibition space and, of course, its famous long red carpet.",
        image: cannesPalaisFestivalsAsset.url },
      { num: "02", name_ar: "متحف لا مير كان", name_en: "Musée de la Mer",
        desc_ar: "مع الإطلالة التي يتمتّع بها على البحر في مدينة كان الفرنسية والقيمة التاريخية والثقافية التي يضمها بين جدرانه، يصبح متحف لا مير كان فرنسا واحداً من أجمل وأروع المتاحف في فرنسا على الإطلاق. يقع على بُعد كيلومتر واحد من المدينة ويتخصّص في عرض عدد كبير من الكنوز التي عُثر عليها في البحر، بعض هذه الكنوز والتحف يعود إلى عصر الإمبراطورية الرومانية.",
        desc_en: "With its sea view and its walls filled with historic and cultural value, the Musée de la Mer is one of France's most beautiful museums. A kilometre from the city, it specialises in treasures recovered from the sea — some dating back to the Roman Empire.",
        image: cannesMuseeDeLaMerAsset.url },
      { num: "03", name_ar: "المدينة القديمة", name_en: "The Old Town (Le Suquet)",
        desc_ar: "بعيداً عن الصخب والضجيج ومظاهر الحياة الفارهة، فالكثير ممن ينوون السفر إلى فرنسا والسياحة في فرنسا ينوون البعد عن الأماكن الصاخبة، وفي مدينة كان مقصدهم، وخاصة في المدينة القديمة، والتي كانت قرية صيد قديمة، والتي يعود عمر مبانيها إلى ما يقارب 100 سنة. الجزء الأكبر من هذه المدينة هو للمشاة، الذين يحبّون التجوّل في المحلات التجارية الصغيرة، والمرور على المطاعم ذوات الرائحة الذكية، والسلالم القديمة والجو الرومانسي.",
        desc_en: "Away from Cannes' glamour and buzz, many visitors seek out the Old Town — an ancient fishing village whose buildings are around a century old. Mostly pedestrian, it charms with small shops, fragrant restaurants, old staircases and a quietly romantic atmosphere.",
        image: cannesOldTownAsset.url, tall: true },
      { num: "04", name_ar: "فيلا دومرج", name_en: "Villa Domergue",
        desc_ar: "تُعدّ فيلا دومرج شاهداً على تاريخ فن الآرت ديكو الحديث، فالمكان من تصميم وتنفيذ الرسام جان جابرييل دوميرغي في 1926م. تم إدراج الفيلا كمكان تاريخي في 1990م، وذلك بسبب روعة وأناقة التصميم والساحة الخارجية للفيلا. يوجد في حديقة الفيلا العديد من التماثيل النصفية العتيقة وبعض الأعمال الفنية الرائعة لزوجة الرسام. يقام بالمكان بعض الأحداث الاجتماعية والرسمية بالمدينة مثل المعارض الفنية، وكانت الفيلا مكان اجتماع للجنة التحكيم الرسمية لمهرجان كان السينمائي، والآن أصبحت ساحة للفن والندوات الثقافية.",
        desc_en: "Villa Domergue is a living record of modern Art Deco, designed and built in 1926 by the painter Jean-Gabriel Domergue and listed as a historic monument in 1990 for its striking design and outdoor grounds. Its garden holds antique busts and works by the painter's wife. It hosts art exhibitions and social events, and once served as the meeting place of the Cannes Film Festival jury.",
        image: cannesVillaDomergueAsset.url },
    ],
  },

  colmar: {
    tagline_ar: "البندقية الصغيرة · لؤلؤة الألزاس · مدينة القنوات",
    tagline_en: "Little Venice · The pearl of Alsace · A city of canals",
    section_title_ar: "السياحة بمدينة كولمار",
    section_title_en: "Sightseeing in Colmar",
    source_url: "https://100region.com/?p=33204&amp=1",
    intro_ar: [
      "كولمار هي مدينة وبلدية في إقليم أوت رين ومنطقة غراند إست في شمال شرق فرنسا بمنطقة الألزاس الثقافية، يبلغ عدد سكانها حوالي 150 ألف نسمة.",
      "تُعتبر عاصمة إقليم الراين الأعلى، وهذه المدينة تشتهر بقراها الريفية وبلداتها القديمة ومعالمها الحضارية ومتاحفها. تُطلّ هذه المدينة على نهر لاوش، وترتبط بنهر الراين من خلال قناة. تتمتّع كولمار بمناخ مشمس، إلا أنها تُعتبر من أكثر مدن فرنسا جفافاً، وذلك بسبب مجاورتها لسلاسل الجبال القريبة منها. يُطلق البعض على هذه المدينة لقب البندقية الصغيرة بسبب تشابهها مع فينيسيا، كما تتمتّع بدرجة عالية من إجمالي السياحة في فرنسا، حيث إنها مدينة متجانسة ومعروفة بين السياح باحتوائها على معالم دينية ومعمارية وحضارية معروفة متنوّعة.",
    ],
    intro_en: [
      "Colmar is a town and municipality in the Haut-Rhin department, Grand Est region of north-eastern France, in the cultural area of Alsace. Its population is around 150,000.",
      "Capital of the Haut-Rhin, it is famed for its rural villages, old towns, cultural landmarks and museums. Overlooking the Lauch river and linked by canal to the Rhine, Colmar has a sunny yet dry climate thanks to the surrounding mountains. Its resemblance to Venice earned it the name Little Venice, and it draws a large share of French tourism as a harmonious city known for its varied religious, architectural and cultural heritage.",
    ],
    closing_ar: "«كولمار مدينة صغيرة بحكاية كبيرة.»",
    closing_en: "\u201CColmar — a small town with a great story.\u201D",
    attractions: [
      { num: "01", name_ar: "مدينة كولمار القديمة", name_en: "The Old Town",
        desc_ar: "جو المدينة الريفية ستجده هنا في مدينة كولمار القديمة، والتي استطاعت الحفاظ على سحرها الريفي الرائع والبسيط، كما تُقدّم بدورها لمن ينوون السفر إلى فرنسا فرصة الإطلالة بشكل سحري على 1000 عام من التاريخ الأوروبي من خلال تراثها الثقافي. وعند المشي في شوارعها ستجد المنازل القديمة نصف الخشبية، والقنوات الجميلة، ومركز مدينة المشاة المزدهر، والمطاعم والمحلات التجارية.",
        desc_en: "Colmar's old town has kept its charming, simple rural character, offering a magical window onto a thousand years of European history. Wander among half-timbered houses, along pretty canals and through a lively pedestrian centre lined with restaurants and shops.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/View_of_%C3%89glise_Saint-Martin_%2843833049001%29.jpg/3840px-View_of_%C3%89glise_Saint-Martin_%2843833049001%29.jpg" },
      { num: "02", name_ar: "فينيسيا المصغرة", name_en: "Little Venice (Petite Venise)",
        desc_ar: "في كولمار كل شيء معقول، فقد أُحضرت فينيسيا إيطاليا ووُضعت في كولمار، وتمّت تسميتها بـ فينيسيا الصغيرة، فهذه المنطقة تُعتبر إحدى رموز كولمار والتي تجمع بين الثقافتين الفرنسية والألمانية، وتفوح منها النكهة الإيطالية، نكهة فينيسيا إيطاليا خاصة من خلال القنوات المائية الرهيبة والجسور التي تعبر فوق نهر اللاش، والقوارب الصغيرة التي تُبحر بين قنواتها.",
        desc_en: "In Colmar anything seems possible — even a piece of Venice. Little Venice is one of Colmar's icons, blending French and German culture with an Italian flavour: dreamy canals, bridges over the Lauch and small boats drifting between the waterways.",
        image: colmarQuaiDeLaPoissonnerieAsset.url, tall: true },
      { num: "03", name_ar: "متحف انترليندن", name_en: "Unterlinden Museum",
        desc_ar: "يقع هذا المتحف في دير الأخوات الدومنيكان، ويتميّز بوجود مجموعة كبيرة ورائعة من الأعمال المحلية الفنية والدولية والمصنوعات اليدوية من عصور ما قبل التاريخ إلى العصور المعاصرة، ويحمل المتحف علامة الجودة الفرنسية، ويُعتبر واحداً من أكثر المتاحف زيارة في فرنسا. وفي عام 2009م تم العمل على تطوير المتحف وزيادة مساحته، وافتُتح المبنى الجديد بحضور الرئيس الفرنسي فرانسوا هولاند في 2016م.",
        desc_en: "Housed in the former Dominican sisters' convent, the Unterlinden Museum holds a remarkable collection of local and international art and craft from prehistory to today. It carries France's official quality label and is one of the country's most visited museums. Its expansion was completed in 2016 and inaugurated by then-President François Hollande.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/40/Mus%C3%A9e_d%27Unterlinden_Colmar.jpg" },
      { num: "04", name_ar: "ميزون دي تيس", name_en: "Maison des Têtes",
        desc_ar: "المعروف بمجلس الرؤساء حيث يعود تاريخ بنائه للقرن السادس عشر، ويُعدّ من أقدم المباني الخشبية في مدينة كولمار، والذي يتميّز بوجود صور وجوه لأبرز شخصيات المدينة، ويحتوي على لوحات جدارية رائعة.",
        desc_en: "Dating from the 16th century, the Maison des Têtes — the House of Heads — is one of Colmar's oldest timber-framed buildings, famed for the sculpted faces of the city's leading figures on its façade and its beautiful murals.",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Maison_des_T%C3%AAtes_2.jpg" },
      { num: "05", name_ar: "كنيسة الدوميكان", name_en: "Dominican Church",
        desc_ar: "تُعتبر الكنيسة من أجمل المباني في كولمار، حيث بُنيت على الطراز المعماري القديم الذي يعود إلى عصر النهضة، ومما يميّزها بناؤها بالأحجار الوردية الرائعة، واحتواؤها على لوحة Schongauer الشهيرة، مما جعلها من أفضل أماكن السياحة في كولمار الفرنسية.",
        desc_en: "The Dominican Church is one of Colmar's most beautiful buildings, built in the Gothic Renaissance style. Its striking pink stone and the famous Schongauer painting inside make it one of Colmar's finest sights.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9b/Cloitre_colmar.jpg" },
    ],
  },

  annecy: {
    tagline_ar: "لؤلؤة جبال الألب الفرنسية · فينيسيا الجبال · بحيرة وقلاع",
    tagline_en: "Pearl of the French Alps · Alpine Venice · A city of lake and castles",
    section_title_ar: "السياحة بمدينة أنسي",
    section_title_en: "Sightseeing in Annecy",
    source_url: "https://100region.com/?p=33181&amp=1",
    intro_ar: [
      "تُعتبر هذه المدينة من أكبر المدن الواقعة في جنوب شرق فرنسا على الطرف الشمالي لبحيرة أنسي، وتُلقّب لدى الكثيرين بـ لؤلؤة جبال الألب الفرنسية، حيث تقع في المنتصف بين البحيرات والجبال، ويطلق عليها آخرون أيضاً لقب فينيسيا جبال الألب، بسبب موقعها المتميّز الذي اكتسبته من الأنهار والبحيرات والقنوات المحيطة بها.",
      "تبعد أنسي 55 كم عن باريس، في حين تبعد 43 كم عن جنيف عاصمة سويسرا، ففي أنسي أنت بين البينين، بين الجنة والجنة، جنة فرنسا وجنة سويسرا، ولكنك بالحري في جنة ثالثة. تحتوي هذه المدينة على معالم بارزة تشهد حيّزاً ممن ينوون السياحة في فرنسا، مثل: جبل سيمنوز، بحيرة أنسي، قصر الديل، قلعة أنسي، جسر العشاق، القصر الإمبراطوري وغيرها.",
    ],
    intro_en: [
      "Annecy is one of the largest cities of south-eastern France, sitting on the northern edge of Lake Annecy. Nicknamed the Pearl of the French Alps for its position between mountains and lakes, it is also called Alpine Venice for the rivers, lakes and canals that surround it.",
      "Annecy lies 55 km from Paris and 43 km from Geneva — between two paradises, France and Switzerland — or rather in a third one. Its major sights include Mount Semnoz, Lake Annecy, the Palais de l'Isle, Annecy Castle, the Lovers' Bridge, the Imperial Palace and more.",
    ],
    closing_ar: "«على ضفاف أنسي تهدأ الحكاية.»",
    closing_en: "\u201COn Annecy's shores, every story finds calm.\u201D",
    attractions: [
      { num: "01", name_ar: "بحيرة أنسي", name_en: "Lake Annecy",
        desc_ar: "هي ثالث أكبر بحيرة في فرنسا، وهي وجهة سياحية مشهورة تُلقّب بأنظف بحيرة في أوروبا، وذلك بسبب نظافة البحيرة وعمقها أيضاً الذي يصل إلى 82 متراً، وطولها الذي يبلغ 14 كم بعرض 4 كم. كما تمتاز هذه البحيرة ببرودة مياهها في الصيف، مما جعلها مزار السياح في فرنسا في فصل الصيف، ويحيط بالبحيرة بلدات وقرى رائعة الجمال، منها: قرية مسنتو سانت برنارد، سيفريه، وتالوار، وغيرها.",
        desc_en: "France's third-largest lake and one of Europe's cleanest, Lake Annecy is 14 km long, 4 km wide and reaches 82 metres deep. Cool in summer, it becomes a magnet for tourists, its shores lined with beautiful villages such as Menthon-Saint-Bernard, Sévrier and Talloires.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Boat_%40_Compagnie_des_Bateaux_du_Lac_d%27Annecy_%40_Lake_Annecy_%40_Saint-Jorioz_%2850488289926%29.jpg/3840px-Boat_%40_Compagnie_des_Bateaux_du_Lac_d%27Annecy_%40_Lake_Annecy_%40_Saint-Jorioz_%2850488289926%29.jpg" },
      { num: "02", name_ar: "جسر الفنون (جسر الحب)", name_en: "Pont des Amours (Lovers' Bridge)",
        desc_ar: "تعاهدنا على أن يحب الواحد منا الآخر طيلة عمره، ولا يفرّقنا إلا الموت. هذا التعهد لم يكن يُكتب بصيغة خطية، وإنما يجب توثيقه في جسر الحب أو جسر العشاق، وذلك عبر وضع قفل مغلق على هذا الجسر للدلالة على استحالة الفراق. يقع هذا الجسر في مدينة أنسي ويعبر فوق قناة Vassé، ويربط بين حدائق أوروبا في Pâquier، وهو مثال رائع للهندسة المعمارية النموذجية من الحديد من أوائل القرن العشرين، وقد تم إدراجه ضمن لائحة التراث الوطني الفرنسي.",
        desc_en: "A promise to love one another for life was not written down but sealed here on the Lovers' Bridge — with a padlock locked shut to symbolise that only death could part the couple. It spans the Vassé canal in Annecy, linking the Jardins de l'Europe to the Pâquier, a fine example of early-20th-century ironwork, listed on France's national heritage register.",
        image: "https://upload.wikimedia.org/wikipedia/commons/d/da/0306_Annecy_-_Pont_des_Amours.jpg" },
      { num: "03", name_ar: "قصر الإليزيه Palais de l'Isle", name_en: "Palais de l'Isle",
        desc_ar: "هو عبارة عن منزل محصّن قديم كان يُستخدم كسجن، وقد تعرّض لعدّة عمليات إصلاح وترميم، ويحتوي على قاعات محكمة قديمة، وزنزانات السجناء القديمة، بالإضافة إلى الكنيسة القديمة، وغرف نصف دائرية مقبّبة، وقاعة جمهور كبيرة، إضافة إلى السلّم الحلزوني الواصل بين الطوابق، وقد تم تصنيف هذا القصر ضمن لائحة التراث العالمي، ويتم الوصول إلى القصر والدخول إليه عبر جسر مربوط.",
        desc_en: "An old fortified house once used as a prison, restored many times over. It holds old courtrooms, prison cells, a small chapel, vaulted rooms, a large audience hall and a spiral staircase between floors. Listed as World Heritage, it is reached across a footbridge.",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f9/Pr%C3%A9fecture_de_Haute-Savoie_%28Annecy%29_%28cropped%29.JPG" },
      { num: "04", name_ar: "حدائق أوروبا", name_en: "Jardins de l'Europe",
        desc_ar: "من أهم الأماكن السياحية في أنسي التي تمتاز بمساحتها الكبيرة وموقعها على ضفاف بحيرة أنسي وجمالها الطبيعي، حيث تجد الأنواع العديدة من الأشجار والنباتات الرائعة. وتُعدّ حديقة أوروبا المكان المثالي للعائلات حيث توجد فيها أماكن للجلوس والتنزّه ومكان مخصص للأطفال يضم العديد من الألعاب الترفيهية المسلية. يوجد في الحديقة العديد من التماثيل الحجرية المدهشة والنافورات الجميلة إضافة إلى الساعة الشمسية والتي تعود إلى القرن التاسع عشر وتقع على رصيف نابليون الثالث.",
        desc_en: "One of Annecy's key attractions, a big lakeside garden famed for its natural beauty and rare trees. Ideal for families, it has seating, walking paths and a children's play area, along with striking stone statues, beautiful fountains and a 19th-century sundial on Napoleon III's quay.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/57/Jardin_de_l%27Europe_-_Annecy.JPG" },
      { num: "05", name_ar: "جبل سيمنوز", name_en: "Mont Semnoz",
        desc_ar: "يقع جبل سيمنوز في مدينة أنسي ضمن كتلة باجيس في جبال الألب، تتباين ارتفاعات قممه بين 1530 متر في قمة غراند دان وتصل إلى 1699 متر في قمة تشاتيلون. يوفّر الجبل إطلالات رائعة على المدينة والبحيرات المجاورة والمروج الخضراء الجميلة، ويُعتبر الوجهة المفضّلة للتنزّه من قبل السكان المحليين وزوّار المدينة. يوفّر جبل سيمنوز الفرصة للقيام بالعديد من الأنشطة، منها المشي وسط الطبيعة، وركوب الدراجات الهوائية، وجولات على الخيل، والقفز بالمظلات، وركوب الكراسي المعلقة، إلى جانب حديقة الغزلان والعديد من الألعاب الترفيهية.",
        desc_en: "Mount Semnoz rises above Annecy in the Bauges massif, its peaks ranging from 1,530 m at Grand Dane to 1,699 m at Châtillon. It gives sweeping views of the city, the surrounding lakes and green meadows, and is a beloved outdoor playground for hiking, cycling, horse riding, paragliding and chairlift rides — plus a deer park and family attractions.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Semnoz_%40_Lac_d%27Annecy_%40_Annecy-le-Vieux_%2834804245794%29.jpg/3840px-Semnoz_%40_Lac_d%27Annecy_%40_Annecy-le-Vieux_%2834804245794%29.jpg", tall: true },
    ],
  },

  strasbourg: {
    tagline_ar: "عاصمة الألزاس · مقرّ البرلمان الأوروبي · مدينة على الحدود",
    tagline_en: "Capital of Alsace · Seat of the European Parliament · A city on the border",
    section_title_ar: "السياحة بمدينة ستراسبورغ",
    section_title_en: "Sightseeing in Strasbourg",
    source_url: "https://100region.com/?p=33152&amp=1",
    intro_ar: [
      "تقع مدينة ستراسبورغ في شرق فرنسا، بجوار الحدود الألمانية على نهر إيل الذي يُعتبر من روافد نهر الراين، وتتمتّع بمناخ محيطي يتّسم بالحرارة العالية في الصيف وشتاء بارد. هذا وتتمتّع مدينة ستراسبورغ بأهمية سياسية عالمية، فهي مقر البرلمان والعديد من المؤسسات الأوروبية.",
      "ومن الناحية الثقافية أيضاً تلعب مدينة ستراسبورغ دوراً بارزاً، فقد تم إدراجها كموقع للتراث العالمي من قبل اليونسكو، وتحتوي على ثاني أكبر جامعة في فرنسا، وهي جامعة ستراسبورغ، وأيضاً هي موطن لأضخم دور العبادة الإسلامية في فرنسا، وهو مسجد ستراسبورغ الكبير.",
      "ومن الناحية الاقتصادية، فتُعتبر ستراسبورغ مركزاً هاماً للتصنيع والهندسة، ومركزاً للنقل البري والسكك الحديدية، وميناء ستراسبورغ هو ثاني أكبر ميناء على نهر الراين. فمدينة ستراسبورغ تستحق أن يمر عليها من ينوي السياحة في فرنسا لتمتلئ روحه بمعاني الحضارة البشرية.",
    ],
    intro_en: [
      "Strasbourg lies in eastern France, on the German border, on the River Ill — a tributary of the Rhine. It has an oceanic climate with hot summers and cold winters, and enjoys global political weight as the seat of the European Parliament and many EU institutions.",
      "Culturally, Strasbourg plays a leading role: listed as UNESCO World Heritage, home to France's second-largest university (the University of Strasbourg), and home to the country's biggest mosque, the Grande Mosquée de Strasbourg.",
      "Economically, Strasbourg is an important centre for industry and engineering, and a hub for road and rail transport, while the Port of Strasbourg is the second-largest on the Rhine. It is a city worth stopping in on any trip through France.",
    ],
    closing_ar: "«ستراسبورغ حيث تلتقي الثقافتان الفرنسية والألمانية.»",
    closing_en: "\u201CStrasbourg — where French and German cultures meet.\u201D",
    attractions: [
      { num: "01", name_ar: "كاتدرائية ستراسبورغ", name_en: "Strasbourg Cathedral",
        desc_ar: "قال عنها الأديب فيكتور هوغو: أعجوبة عملاقة وحساسة، في حين وصفها غوته: شاهقة رفيعة كشجرة واسعة من عند الله. كل ذلك قيل عن كاتدرائية ستراسبورغ أو كما تُسمّى بكاتدرائية السيدة العذراء الرومانية الكاثوليكية، البالغة من القدم ما يعود بها إلى القرن 13 ميلادي. ومن روعة البناء وجماله أنها كانت تملك أطول برج في العالم بطول 142 متراً، ولكن ذلك استمر إلى عام 1874م حيث بُني ما هو أطول منها، ولكن ذلك لم يمنعها من إحراز مجد سادس أطول برج في العالم وأعلى هيكل في العصور الوسطى. بُنيت في الفترة من 1015م إلى 1439م، وكانت أطول مبنى في العالم من 1647م حتى 1874م (لمدة 227 عاماً).",
        desc_en: "Victor Hugo called it \u201Ca gigantic and delicate marvel,\u201D and Goethe likened it to a tall, slender tree from God. This 13th-century Roman Catholic cathedral of Our Lady had the tallest tower in the world at 142 metres until 1874, and remains the sixth-tallest church spire and the highest medieval structure ever built. Built between 1015 and 1439, it was the tallest building on Earth for 227 years, from 1647 to 1874.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Strasbourg_Cathedral_Exterior_-_Diliff.jpg/3840px-Strasbourg_Cathedral_Exterior_-_Diliff.jpg", tall: true },
      { num: "02", name_ar: "حي فرنسا الصغيرة", name_en: "La Petite France",
        desc_ar: "حي فرنسا الصغيرة Petite France — هل يمكن اختزال فرنسا بعظمتها في حي صغير يُطلق عليه حي فرنسا الصغيرة؟ هذا الحي هو حي تاريخي يقع بمدينة ستراسبورغ في شرق فرنسا، ويحتوي على المركز التاريخي للمدينة. وفي العصور الوسطى كان هذا الحي مركزاً لدباغي المدينة والصيادين والمطاحن، لكنها اليوم تُعتبر منطقة جذب سياحي كبير في فرنسا، ففي عام 1988م تم إدراج هذا الحي في لائحة التراث العالمي، وتجد فيه الأبراج والجسور والقنوات المائية الرهيبة، ومنازل ومبانٍ ذات جدران خارجية نصف خشبية، مع روعة الجسور المزينة بالأزهار.",
        desc_en: "Can all the greatness of France really fit into one small quarter called Little France? La Petite France is a historic district in Strasbourg, containing the city's old core. In the Middle Ages it was home to the city's tanners, fishermen and millers; today it is a major tourist attraction, listed as UNESCO World Heritage in 1988. Wander among towers, bridges, canals, half-timbered houses and flower-lined footbridges.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Strasbourg_Petite-France_place_Benjamin-Zix_septembre_2015.jpg" },
      { num: "03", name_ar: "حديقة أورانجرية", name_en: "Parc de l'Orangerie",
        desc_ar: "الحديقة البرتقالية Orangerie Park هي أقدم حديقة في مدينة ستراسبورغ، وهي الوجهة المفضّلة للعشاق والشباب، وممارسي رياضة المشي وسائقي عربات الأطفال والأمهات في أيام الأحد. وهي من المناطق المحبّبة للأطفال، بسبب توفّر مساحة للعب وبعض الألعاب الخفيفة، إضافة إلى وجود حديقة خاصة للحيوانات يمكن الدخول إليها مجاناً، وإلى جانبها تقع البحيرة بمنظرها المتلألئ وحركة القوارب الممتعة فيها.",
        desc_en: "Strasbourg's oldest park, the Orangerie is a Sunday favourite of couples, joggers, walkers and families. Loved by children for its play area and small rides, it also includes a free zoo and a shimmering lake with rowing boats.",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/Absolute_Pavillon_Jos%C3%A9phine_01.jpg" },
      { num: "04", name_ar: "متحف ستراسبورغ التاريخي", name_en: "Strasbourg Historical Museum",
        desc_ar: "يستحق الزيارة بالفعل، حيث يشغل مبنى جميلاً، ويُقدّم للزائرين مجموعات رائعة من الكتب القديمة مع مجموعات من الأسلحة التاريخية والأعمال الفنية التي لا تُقارن، كما يضم المتحف كتاباً فريداً من نوعه صنعه يوهان جوتنبرغ في أول مطبعة حديثة قام باختراعها.",
        desc_en: "Housed in a beautiful building, the Historical Museum displays rare old books, historic weapons and remarkable works of art — including a unique volume printed by Johannes Gutenberg on the first modern printing press he invented.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a1/FR-67-Strasbourg29.JPG" },
      { num: "05", name_ar: "ساحة كليبر", name_en: "Place Kléber",
        desc_ar: "تُعدّ ساحة كليبر أكبر ساحة في وسط مدينة ستراسبورغ، كما أنها أيضاً المنطقة التجارية الأفضل في المدينة، حيث ستجد الكثير من خيارات التسوق، كما تُعدّ الساحة مكاناً رائعاً للاستمتاع بالمزيد من أجواء المدينة، لاسيما عند الزيارة في شهر ديسمبر، بالتزامن مع إقامة سوق رأس السنة.",
        desc_en: "Place Kléber is the largest square in central Strasbourg and its best shopping district. It's a wonderful place to soak up the atmosphere of the city, especially in December when the Christmas market takes over.",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Absolute_place_Kleber_02.jpg" },
      { num: "06", name_ar: "الحديقة النباتية", name_en: "Botanical Garden",
        desc_ar: "تُعدّ السياحة في ستراسبورغ مكاناً ممتازاً للعطلات العائلية، بفضل ما تُقدّمه للزائرين من مجموعة متنوّعة من أماكن الترفيه، بما في ذلك الحديقة النباتية التي تتمتّع بمساحة كبيرة مع مجموعة رائعة من النباتات. تحظى بشعبية كبيرة بين محبّي جولات السير على الأقدام، حيث يعود تاريخها إلى القرن السابع عشر وتستضيف أكثر من ست مئات من النباتات والزهور المختلفة، كما أن هناك مناطق راحة جميلة مع مقاعد في جميع أنحاء الحديقة وبركة تسكنها السلاحف.",
        desc_en: "Strasbourg is a fine family-holiday spot, thanks to its variety of leisure places — including the Botanical Garden, a generous 17th-century park with over 600 different plants and flowers. Beloved by walkers, it has quiet benches throughout and a pond home to a small colony of turtles.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Observatoire-Strasbourg.JPG" },
      { num: "07", name_ar: "المركز التاريخي", name_en: "The Historic Centre",
        desc_ar: "تظهر المباني في المركز التاريخي مزيجاً من التأثيرات الفرنسية والألمانية، مع تصميمات تعود إلى عصور القرون الوسطى، ولعل السير حول هذا المركز هو أفضل استعراض لتطوّر ستراسبورغ عبر العصور، حيث يمكنك اكتشاف روعة التاريخ والاستمتاع بالتجوّل ما بين الشوارع القديمة الساحرة. فضلاً عن ذلك يمكنك خلال هذه الجولة اقتناء مجموعة من الهدايا التذكارية الجميلة التي يتم عرضها في المحال التجارية.",
        desc_en: "The buildings of the historic centre blend French and German influences and reach back to the Middle Ages. A walk here is the best way to trace Strasbourg's evolution across the ages — a stroll among charming old streets, with lovely souvenirs on display in the little shops.",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Strasbourg_Petite-France_place_Benjamin-Zix_septembre_2015.jpg" },
    ],
  },

  nice: {
    tagline_ar: "لؤلؤة الريفييرا · شواطئ الشمس · عاصمة كوت دازور",
    tagline_en: "Pearl of the Riviera · Sunlit beaches · Capital of the Côte d'Azur",
    section_title_ar: "السياحة بمدينة نيس",
    section_title_en: "Sightseeing in Nice",
    source_url: "https://100region.com/?p=33075&amp=1",
    intro_ar: [
      "نيس هي مدينة تقع في جنوب فرنسا على ساحل البحر الأبيض المتوسط، بين مارسيليا وجنوى في إقليم ألب كوت دازور، يبلغ عدد سكانها 933,080 نسمة، ومساحتها 71.92 كيلومتر مربع.",
      "تُعتبر المدينة مركزاً سياحياً رئيسياً في البلاد، وتشتهر بمصايفها وشواطئها الجميلة، ويزورها ملايين السياح كل سنة. للمدينة مطار مدني تُقلع وتهبط فيه طائرات معظم شركات الطيران العالمية وهو مطار كوت دا زور.",
    ],
    intro_en: [
      "Nice sits on the Mediterranean coast of southern France, between Marseille and Genoa, in the Alpes-Maritimes department. Home to 933,080 people over 71.92 km².",
      "It is one of the country's leading tourist hubs, famed for its seaside resorts and beautiful beaches, welcoming millions of visitors each year through Nice Côte d'Azur Airport.",
    ],
    closing_ar: "«الشمس في نيس لا تغيب.»",
    closing_en: "\u201CIn Nice, the sun never sets on the promenade.\u201D",
    attractions: [
      { num: "01", name_ar: "متحف ماتيس", name_en: "Matisse Museum",
        desc_ar: "يجذب هذا المتحف محبّي الفن الراقي وعشّاق أعمال هنري ماتيس الفنية، حيث يعرض المتحف عدداً كبيراً من الأعمال الفنية الخالدة لهذا الرسام الفرنسي العريق، فضلاً عن عرض مفصّل لقصة حياته منذ ولادته وحتى مماته، كما تُعرض بعض الممتلكات الشخصية لهذا الرسام في متحفه الخاص.",
        desc_en: "A magnet for lovers of fine art and Henri Matisse's work, this museum displays many of the great French painter's timeless pieces, tells the detailed story of his life, and even shows some of his personal belongings.",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3e/Mus%C3%A9e_Matisse_Nice.JPG" },
      { num: "02", name_ar: "متحف الفنون الجميلة", name_en: "Musée des Beaux-Arts",
        desc_ar: "يضم المتحف مجموعة متنوّعة من الفنون الفرنسية التابعة لمونيه وبودان ورودان وكاربو وغيرهم الكثير، والتي يعود تاريخها إلى القرنين التاسع عشر والعشرين من الميلاد، ويقع المتحف في قصر الأميرة الأوكرانية السابق.",
        desc_en: "The museum holds a rich collection of French art by Monet, Boudin, Rodin, Carpeaux and others from the 19th and 20th centuries, set inside a former Ukrainian princess's palace.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Villa_Thomson_03.jpg/3840px-Villa_Thomson_03.jpg" },
      { num: "03", name_ar: "ميدان الماسينا", name_en: "Place Masséna",
        desc_ar: "يقع في منتصف مدينة نيس ويُعدّ المنطقة الحيوية للمدينة، شُيّد في عام 1832م، ويتضمّن ممرّاً مخصّصاً للسير على الأقدام وعدداً كبيراً من المحلات التجارية والمطاعم والمقاهي، بالإضافة إلى نافورة ينبوع الشمس والتي تظهر روعتها في ساعات المساء مع الأضواء الملوّنة المحيطة بها.",
        desc_en: "The lively heart of Nice, built in 1832. A pedestrian avenue is lined with shops, restaurants and cafés, and the Fountain of the Sun dazzles at night with its coloured lights.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8b/Place-Mass%C3%A9na_01.jpg" },
      { num: "04", name_ar: "نيس إيتوال", name_en: "Nice Étoile",
        desc_ar: "أحد أشهر أماكن التسوق في نيس، ويقع بالقرب من وسط المدينة، ويضم مجموعة كبيرة من الماركات التجارية العالمية والمشهورة، بالإضافة إلى المواد الغذائية وغيرها، والعديد من المقاهي والمطاعم.",
        desc_en: "One of Nice's most famous shopping destinations, close to the city centre. It brings together many international brands, a food hall and a wide choice of cafés and restaurants.",
        image: niceEtoileAsset.url },
      { num: "05", name_ar: "ملاهي خشب العفاريت", name_en: "Bois des Lutins Adventure Park",
        desc_ar: "أفضل الملاهي في نيس التي تأخذ الطراز الطبيعي، تمتد لمساحة تصل إلى هكتارين، وتوفّر ألعاباً ممتعة من التسلق على الشباك أو الحبال مع ارتفاع يتراوح من أحد عشر إلى ثلاثة عشر متراً. توفّر كذلك ألعاباً أخرى ممتعة ومسلية كالركوب والتدحرج داخل كرات بلاستيكية ضخمة، والقفز الحر، لذا تُعدّ ضمن أفضل ملاهي نيس للأطفال. تفتح الملاهي أبوابها كل أربعاء وقت الظهيرة، وكذلك في العطلات الأسبوعية والعطلات الوطنية.",
        desc_en: "Nice's finest nature-style adventure park, spread over two hectares. Its games include net and rope climbs 11–13 metres up, giant plastic ball rolls and free jumping — one of the best parks for children in Nice. Open Wednesday afternoons, weekends and public holidays.",
        image: MISSING_IMAGE },
      { num: "06", name_ar: "حديقة فونيكس", name_en: "Parc Phoenix",
        desc_ar: "تقع حديقة فونيكس في الجهة الجنوبية الغربية لمدينة نيس الفرنسية الساحرة تحديداً في حي أريناس ملاصقة لمنتزه انغليس، وتُعدّ واحدة من أكبر الحدائق والمنتزهات العامة ليس في فرنسا فقط بل في أوروبا بشكل عام، حيث تبلغ مساحتها 7 هكتار. تضم عدداً كبيراً من الأنشطة الترفيهية والثقافية، كما يوجد بها عدد كبير من الحيوانات والطيور، بعضها نادر، من أشهر هذه الحيوانات ثعلب النهر والكنغر والقنفذ وعدد من الطيور. وتضم الحديقة أيضاً نافورة موسيقية ضخمة عند مدخلها الرئيسي، ومتحفاً خاصاً بالفنون الآسيوية.",
        desc_en: "In south-western Nice next to the Promenade des Anglais, Parc Phoenix is one of Europe's biggest urban parks at 7 hectares. It offers cultural and leisure activities, many animals and birds — including river otters, kangaroos, hedgehogs and rare species — a huge musical fountain at the main entrance, and a museum of Asian arts.",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c6/Parc_Phoenix_serre_Nice.jpg" },
      { num: "07", name_ar: "حديقة ألبرت الأول", name_en: "Jardin Albert Ier",
        desc_ar: "هذه الحديقة العامة الرائعة في وسط مدينة نيس بالقرب من ساحة ماسينا، وهي واحدة من أقدم الحدائق العامة في نيس. عند زيارتك سوف تجد نفسك على الفور في وسط أشجار النخيل والورود العطرة، والنباتات المختلفة التي تم جلبها من اليابان والصين والأمريكتين وأستراليا والهيمالايا، بالإضافة إلى المساحات الواسعة المخصّصة للزهور. تنتشر داخل الحديقة العديد من نوافير المياه المذهلة، ولم تُغفَل الأقسام الخاصة بالصغار فأُنشئ عدد من الألعاب مثل الأرجوحات ولعبة الخيول الدوّارة.",
        desc_en: "This wonderful public garden in central Nice, near Place Masséna, is one of the city's oldest. Palms, fragrant roses, plants brought from Japan, China, the Americas, Australia and the Himalayas share space with wide flowerbeds. Stunning fountains dot the park, and there are swings and a carousel for children.",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/59/Jardin_Albert_1er.jpg" },
      { num: "08", name_ar: "منتزه أنغليس", name_en: "Promenade des Anglais",
        desc_ar: "يُعدّ منتزه أنغليس أحد أفضل الحدائق المفتوحة في مدينة نيس الفرنسية الساحرة، تتميّز هذه الحديقة بإطلالة ساحرة على مياه البحر المتوسط، بالإضافة إلى تعدّد الأنشطة والخدمات الموجودة بداخلها. الحديقة تمتلئ بالمظلات والمقاعد النظيفة التي توفّر لك وقتك الخاص من الهدوء والاسترخاء، كما أن رمال الشاطئ الذهبية ومياهه الصافية سبب كافٍ لقضاء القليل من الوقت في ممارسة رياضة السباحة.",
        desc_en: "One of Nice's finest open promenades, gazing over the Mediterranean. Umbrellas and clean benches invite quiet reading and relaxation, and the golden sands and clear waters make it perfect for a swim.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/CollineDuChateau_NiceFrance2022.png/3840px-CollineDuChateau_NiceFrance2022.png", tall: true },
      { num: "09", name_ar: "سوق زهرة كور ساليا", name_en: "Cours Saleya Flower Market",
        desc_ar: "يُعدّ سوق زهرة كور ساليا أحد الأماكن التي تدبّ بها الحركة والنشاط على مدار اليوم داخل مدينة نيس الفرنسية، ويستقطب عدداً كبيراً من الزوّار على مدار العام. من أبرز المتاجر التي يضمها السوق هي متاجر الورود ذات الألوان والأشكال والأحجام المتعدّدة — حيث تشتهر المدينة بزراعة الورد — بالإضافة إلى الملابس والمنتجات الجلدية، ومحلات بيع التحف والاكسسوارات والهدايا التذكارية إلى جوار المشغولات اليدوية البديعة.",
        desc_en: "The Cours Saleya market bustles all day long, drawing visitors year-round. Its flower stalls are legendary — Nice is famed for its roses — alongside clothes, leather goods, antiques, souvenirs and beautiful handmade crafts.",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e4/Nizza.jpg" },
      { num: "10", name_ar: "شاطئ لو غاليه", name_en: "Le Galet Beach",
        desc_ar: "قدّم شاطئ لو غاليه أكبر مثال على أناقة الريفييرا الفرنسية، يفتح هذا الشاطئ أبوابه رسمياً ما بين أشهر أبريل وأكتوبر. أما موقعه مقابل المدينة القديمة وحدائق ألبرت الأول، فهو يوفّر أفضل الإطلالات على المواكب خلال موسم الكرنفال في شهر فبراير.",
        desc_en: "Le Galet sets the standard for French Riviera elegance. Open officially from April to October, its position opposite the Old Town and the Jardin Albert Ier gives it some of the best views of the Carnival parades each February.",
        image: MISSING_IMAGE },
      { num: "11", name_ar: "شاطئ أوبرا", name_en: "Opéra Beach",
        desc_ar: "يُعرف سابقاً باسم أوبرا بافيليون، إنه أقدم شاطئ خاص في نيس وأكثرها شعبية. هناك الموظفون مستعدون لتلبية جميع احتياجاتك حتى الصعبة منها، فإذا نسيت ملابس السباحة الخاصة بك فلا داعي للقلق، إذ تُقدّم لك مساعدة المبيعات مجموعتها لتختار من بينها الأنسب لك، وإذا كنت تحلم بالتدليك على الشاطئ فيمكن إرسال خبير تدليك مباشرة إلى كرسيك.",
        desc_en: "Formerly Opéra Pavillon, this is Nice's oldest and most popular private beach. Staff will meet almost any request — forget your swimwear and sales assistants bring options to choose from; dream of a beach massage and a therapist can come straight to your lounger.",
        image: MISSING_IMAGE },
      { num: "12", name_ar: "حديقة جبل فسيوبيا", name_en: "Vésubia Mountain Park",
        desc_ar: "واحدة من أفضل ملاهي نيس، ليست كمدن الملاهي التقليدية، بل هي مدينة ملاهي مغلقة تعتمد المتعة والإثارة بها على الأنشطة الجبلية. تشمل الأنشطة والألعاب هناك كلاً من التسلق وركوب الزوارق والسباحة والتنزّه ضمن الكهوف. بالنسبة لركوب القوارب فهناك مجموعة من الدورات وورش العمل، وشلال خاص وممرات تصل ارتفاعها إلى ثلاثة أمتار. للتجوّل في الكهوف يوجد خمس مستويات مع ممرات تمتد لثمانين متراً، أما التسلق فهناك مستويات مختلفة للمبتدئين والمحترفين من مختلف الأعمار. وللسباحة برك خاصة بالأطفال الصغار وأخرى للكبار وأخرى ضخمة للأطفال الأكبر سناً والبالغين.",
        desc_en: "One of Nice's best leisure venues, and unlike ordinary amusement parks: a covered mountain-activity centre offering climbing, canoeing, swimming and cave walks. Boating includes courses and workshops with a dedicated waterfall and slides up to three metres, cave walks cross five levels along 80 metres of passages, and climbing has beginner-to-advanced routes for all ages. Pools include a toddler basin, a relaxation pool and a large pool for older children and adults.",
        image: MISSING_IMAGE },
      { num: "13", name_ar: "ملاهي غابة بيتشاون", name_en: "Pitchoun Forest Adventure Park",
        desc_ar: "واحدة من أفضل ملاهي نيس للأطفال، حيث تسمح لهم باستكشاف الطبيعة في جو من المرح والمتعة. تبدأ زيارتك بجولة حول الغابة للتعرّف على الأشجار والحيوانات الموجودة، من خلال مرشدين محترفين يوفّرون كورسات تعليمية. بعد ذلك يتم التوجّه إلى الألعاب الجبلية وما تتضمن من مزالق، ومزالج تناسب مختلف الأعمار للمبتدئين والمحترفين كذلك.",
        desc_en: "One of Nice's best parks for children, letting them explore nature in a fun setting. Your visit begins with a guided tour of the forest to learn about the trees and animals, followed by mountain games and slides suited to different ages and skill levels.",
        image: MISSING_IMAGE },
    ],
  },

  bordeaux: {
    tagline_ar: "مدينة النبيذ · عاصمة أكيتان · تراث الملوك والنبلاء",
    tagline_en: "The city of wine · Capital of Aquitaine · Heritage of kings and nobles",
    section_title_ar: "السياحة بمدينة بوردو",
    section_title_en: "Sightseeing in Bordeaux",
    source_url: "https://100region.com/?p=33077&amp=1",
    intro_ar: [
      "بوردو مدينة فرنسية عرفها العرب باسم برديل، تقع على نهر غارون في جنوب غرب البلاد، بالقرب من مصبّ النهر عند خليج غاسكونيا بالمحيط الأطلسي، يبلغ عدد سكانها مليون و100 ألف تقريباً.",
      "تُعدّ مدينة بوردو من المدن الأشهر عالمياً بين المدن الفرنسية، وبعد باريس مباشرة. هذه الشهرة التي تحملها إلى كافة أنحاء العالم لم تأتِ من زراعة الدالية فقط التي تشتهر بها المدينة، بل هي آتية من تاريخ طويل تمتلكه المدينة، ويشكّل لها مادة تفتخر بها طوال الوقت.",
      "تقع المدينة على الساحل الجنوبي لنهر جيروند الكبير الذي كانت تختبئ السفن المسافرة فيه قبل عدة قرون اتقاءً لحالات النَّوّ الخطيرة التي تصيب المحيط الأطلسي في أيام الشتاء، ما حوّل المنطقة إلى ميناء مهم على الضفة الشرقية للأطلسي، وهي في السابق كانت منطقة ممتلئة بالمستنقعات التي لم يزل لغاية اليوم بعض منها بالقرب من المدينة.",
      "وقد ساهمت هذه المستنقعات بعد استصلاح الأراضي بتحويلها إلى أكثر الأراضي خصوبة في فرنسا، خاصة في زراعة الكرمة التي يعيش على جزء منها الاقتصاد الفرنسي. كما وتمتلك بوردو كما غيرها من المدن الفرنسية علماً خاصاً بها، يرمز إلى تاريخها الملكي، إضافة إلى تاريخ وجود النبلاء فيها، وهي إضافة لذلك من المناطق التي تمتلك أكبر عدد من قصور النبلاء والملوك الذين تعاقبوا على حكم فرنسا. وتُعدّ منطقة سانت إيميليون في إقليم جيروند من المناطق الغنية جداً في فرنسا.",
    ],
    intro_en: [
      "Bordeaux — known to Arab visitors as Bardīl — sits on the River Garonne in south-western France, near its mouth at the Bay of Biscay on the Atlantic. Home to around 1.1 million people.",
      "It is one of the most globally famous French cities after Paris. That fame comes not only from its celebrated vineyards but from its long history — a source of pride the city has always celebrated.",
      "Bordeaux lies on the southern bank of the great Gironde river, where ships once sheltered from the Atlantic's dangerous winter storms — a role that made the area an important port on the Atlantic's eastern shore. The region was long a stretch of marshes, some of which still remain nearby.",
      "Once reclaimed, those marshes became some of France's most fertile land, especially for vine growing — a mainstay of the French economy. Like other French cities, Bordeaux has its own emblem, symbolising its royal past and the nobles who once lived here. It holds one of the largest concentrations of noble mansions and royal palaces in France, and the Saint-Émilion area in the Gironde is one of the country's wealthiest.",
    ],
    closing_ar: "«في بوردو يشرب التاريخ من كأس النبيذ.»",
    closing_en: "\u201CIn Bordeaux, history is served in a glass of wine.\u201D",
    attractions: [
      { num: "01", name_ar: "ساحة الكوميديا", name_en: "Place de la Comédie",
        desc_ar: "ساحة الكوميديا موجودة في شارع سانت كاثرين التجاري، ويتفرّع منها الكثير من الشوارع، والتي تمتلك محلات راقية وفخمة، وهناك ممر أساسي يدخل إلى الأحياء الداخلية لمدينة بوردو، والمعروفة بضيق وأثرية شوارعها. تُعتبر البيوت فيها من أكثر الأماكن جذباً للسياح، وهناك المطاعم الصغيرة التي تُضفي جواً رومانسياً لروادها، وخاصة في فصل الصيف.",
        desc_en: "Place de la Comédie opens off Rue Sainte-Catherine, radiating into streets lined with fine boutiques. A main passage leads into Bordeaux's inner quarters, famed for their narrow, historic lanes. The houses here are among the biggest draws for visitors, together with small bistros that give the area a romantic feel — especially in summer.",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/79/Bordeaux_Grand_Th%C3%A9%C3%A2tre_Vue_n%C2%B02.jpg" },
      { num: "02", name_ar: "مبنى الأوبرا", name_en: "Opera House",
        desc_ar: "بُني مبنى الأوبرا حسب طلب ماريشال دي ريتشيليو وهو حاكم غويين، وتم تصميمه من قبل المهندس المعماري فيكتور لويس، وتم الانتهاء من بنائه عام 1780م. ينتمي إلى الهندسة النيوكلاسيكية، وهناك بداخل المبنى الكثير من المتحف، ويقام به على مدار السنة العشرات من الحفلات الكلاسيكية والراقصة، ويعزف فيه كل شهر فرق موسيقية من أشهر الفرق في قارة أوروبا.",
        desc_en: "Commissioned by Marshal de Richelieu, Governor of Guyenne, and designed by architect Victor Louis, the Opera House was completed in 1780. A neoclassical masterpiece, it houses a museum inside and stages dozens of classical concerts and ballets each year, welcoming leading European orchestras every month.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/GrandTheatreBordeaux2.jpg", tall: true },
      { num: "03", name_ar: "مسرح Le Grand Théâtre", name_en: "Le Grand Théâtre",
        desc_ar: "يُعدّ مسرح Grand Théâtre هو محور حياة المدينة والموقع القديم للمنتدى الروماني، وقد تم بناء هذا المسرح الضخم في عام 1780م. يُعدّ واحداً من أكثر المباني رمزية في المدينة، وقد صمّم المبنى المهندس المعماري Victor Louis الذي صمّم أيضاً القصر الملكي والمسرح الفرنسي في باريس.",
        desc_en: "The Grand Théâtre is the pulse of city life and stands on the old site of the Roman forum. Completed in 1780, it is one of Bordeaux's most symbolic buildings, designed by Victor Louis — the architect behind the Palais-Royal and the Comédie-Française in Paris.",
        image: "https://upload.wikimedia.org/wikipedia/commons/8/8c/GrandTheatreBordeaux2.jpg" },
      { num: "04", name_ar: "بلاس دو لا بورس", name_en: "Place de la Bourse",
        desc_ar: "من الأماكن الجديرة بالزيارة في بوردو Place de la Bourse، والذي يجسّد أناقة تصميم القرن الثامن عشر، ويوجد في وسط الساحة نافورة النعم الثلاثة. يحيط بالنافورة مبنيان شهيران وهما جناح قصر البورصة ومتحف الفنون الوطنية، وتُطلّ هذه الآثار الرملية الرائعة على ضفاف نهر غارون.",
        desc_en: "One of Bordeaux's essential sights: Place de la Bourse embodies 18th-century elegance, with the Fountain of the Three Graces at its centre, flanked by the Palais de la Bourse pavilion and the national art museum. These beautiful sandstone monuments look out over the Garonne.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Bordeaux_place_de_la_bourse_with_tram.JPG" },
      { num: "05", name_ar: "رحلات بوردو البحرية", name_en: "Bordeaux River Cruises",
        desc_ar: "الاسترخاء على طول النهر أو وسط كروم العنب، لا حاجة للاختيار مع توفّر العديد من الرحلات النهرية، من بوردو، بلاي أو بوياك. فعند مصبّ نهر الجيروند نبحر بين الجزر، من جزيرة مارغو حيث تزدهر مزارع الكروم على حافة المياه، إلى جزيرة باتيراس التي تُطلّ منارتها على قصور ميدوك. وللاسترخاء وأخذ جرعة من الطاقة والنشاط، حاول أن تجرّب علاج كروم العنب، فهو علاج حصري في ينابيع كودالي، وهو منتجع صحي وسط مزارع الكروم الفريدة التي تجمع بين مزايا الينابيع الساخنة وفوائد الكروم والعنب.",
        desc_en: "Relax by the river or among the vines — with cruises from Bordeaux, Blaye or Pauillac, you don't have to choose. At the mouth of the Gironde, glide between islands: from Île Margaux, where vineyards flourish at the water's edge, to Île de Patiras, whose lighthouse looks over the châteaux of the Médoc. To recharge, try the vine-therapy treatments at Caudalie Vinothérapie, a spa nestled in the vineyards that blends thermal spring benefits with the goodness of grapes.",
        image: bordeauxRiverCruisesAsset.url },
      { num: "06", name_ar: "متحف Musée des Beaux-Arts", name_en: "Musée des Beaux-Arts",
        desc_ar: "يقع متحف Beaux-Arts في حديقة Jardin de la Mairie العامة الجميلة، ويحتلّ جزءاً من Hôtel de Ville قاعة المدينة. يُقدّم المتحف فكرة رائعة عن تاريخ الفن الأوروبي، مع مجموعة من الفنون تمتد من القرن الخامس عشر إلى القرن العشرين، ويتم تنظيم اللوحات في المتحف بطريقة موضوعية مجمّعة حسب العصر والبلد، مثل عصر النهضة واللوحات الهولندية من القرن السابع عشر واللوحات الفرنسية من القرن 17 إلى القرن 18.",
        desc_en: "Set in the lovely Jardin de la Mairie and occupying part of the Hôtel de Ville, the Musée des Beaux-Arts offers a beautiful overview of European art history — a collection running from the 15th to the 20th century, its paintings arranged by period and country: Renaissance, 17th-century Dutch works, and 17th–18th-century French painting.",
        image: museeBeauxArtsBordeauxAsset.url },
      { num: "07", name_ar: "متحف Musée d'Aquitaine", name_en: "Musée d'Aquitaine",
        desc_ar: "يوضّح متحف آكيتاين بوضوح تاريخ بوردو ومنطقة أكيتان من عصور ما قبل التاريخ وحتى يومنا هذا. يحتوي المتحف على قطع استثنائية من العصور القديمة بما في ذلك القطعة الأثرية المسماة Laussel Venus، وهي قطعة أثرية من 25000 ق.م، كذلك يوجد عملات ذهبية غالية من القرن الثاني قبل الميلاد، وتمثال لهرقل يعود إلى القرن الثالث.",
        desc_en: "The Musée d'Aquitaine traces the story of Bordeaux and the Aquitaine region from prehistory to the present. Its treasures include the Venus of Laussel (25,000 BCE), rare 2nd-century BCE gold coins, and a 3rd-century statue of Hercules.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Mus%C3%A9e_Aquitaine.JPG" },
      { num: "08", name_ar: "حوض آركاشون", name_en: "Arcachon Bay",
        desc_ar: "بعد زيارة بوردو، يمكنك أيضاً التوجّه جنوباً نحو حوض آركاشون لتحسّس مياه المحيط. تمثل هذه المناظر الطبيعية البرية بين الشواطئ الرملية وموانئ المحار الصغيرة التي تكوّنت بفعل المد والجزر، ملعباً رائعاً لعشّاق شاطئ البحر والطبيعة. نملأ رئتينا بأكسجينها ونحن نقود دراجاتنا في الغابات المزروعة بأشجار الصنوبر، أو عن طريق التسلق على الكثبان الرملية الشهيرة في بيلات التي تمنحنا من ارتفاعها البالغ 109 أمتار إطلالة بانورامية استثنائية على مياه فيروزية للمحمية الطبيعية بان أرغوان في حوض أركاشون.",
        desc_en: "South of Bordeaux, head to Arcachon Bay to feel the ocean. Wild landscapes stretch between sand beaches and small tidal oyster harbours — a paradise for lovers of the coast and nature. Fill your lungs with ocean air on cycle rides through the pine forests, or climb the famous Dune du Pilat, 109 metres high, for panoramic views over the turquoise waters of the Banc d'Arguin nature reserve.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Dune_du_Pilat_-_20090914.jpg/1920px-Dune_du_Pilat_-_20090914.jpg" },
      { num: "09", name_ar: "ساحة البورصة", name_en: "Place de la Bourse (square)",
        desc_ar: "تُعدّ من أفضل المعالم السياحية في المدينة لاحتوائها على الكثير من المباني الكلاسيكية الجميلة والتي يرجع تاريخها إلى القرن الثامن عشر، وتتميّز هذه المباني بتصميمها على طول النهر. تم إنشاء الساحة في الفترة من 1730-1755م على يد مهندسين من عائلة غابريل، وستستمتع برؤية النافورة الكبيرة في وسطها، كما تحيط بالساحة مبانٍ هامة كمتحف الجمارك ومبنى البورصة.",
        desc_en: "One of Bordeaux's finest sights, thanks to its beautiful 18th-century classical buildings laid out along the river. Built between 1730 and 1755 by the Gabriel family of architects, the square is centred on a great fountain and framed by important buildings such as the Customs Museum and the old Stock Exchange.",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/64/Bordeaux_place_de_la_bourse_with_tram.JPG" },
      { num: "10", name_ar: "متحف الفنون الجميلة", name_en: "Fine Arts Museum",
        desc_ar: "يوجد المتحف في حديقة قاعة المدينة، وعليك بالذهاب إليه للاستمتاع برؤية مقتنياته المميّزة، يتميّز بوجوده في جزء من فندق دي فيل. عند زيارتك إلى المتحف ستستمتع بإلقاء نظرة على الأعمال الأوروبية الجميلة والتي ترجع إلى الفترة من القرن الخامس عشر وحتى القرن العشرين، ويحتوي المتحف على لوحات رائعة مقسّمة على حسب الفترة الزمنية التي تم رسمها بها كاللوحات الهولندية وأيضاً الفرنسية التي تعود إلى القرن السابع عشر، ويضم المتحف مجموعة من أعمال الفنون المعاصرة.",
        desc_en: "Set in the city-hall garden and part of the Hôtel de Ville, this museum showcases beautiful European works from the 15th to the 20th century, arranged by period — including 17th-century Dutch and French paintings — along with a collection of contemporary art.",
        image: MISSING_IMAGE },
      { num: "11", name_ar: "ساحة إسبلاناد", name_en: "Esplanade des Quinconces",
        desc_ar: "تُعدّ من أهم الساحات في المدينة، توجد الساحة بوسط المدينة وتُعتبر من أكبر الساحات في أوروبا، تتميّز بوجود نافورة ضخمة بها وتم إنشاؤها في الفترة من عام 1818-1828م بهدف تكريم مجموعة من السياسيين الجمهوريين المعاصرين للثورة الفرنسية. دُمّرت النافورة الأصلية في أحداث الحرب العالمية الثانية وتم إعادة إنشائها مرة أخرى، كما يوجد بجانبها منتزه رائع يُطلّ على مناظر طبيعية ساحرة خاصة الإطلالة البحرية، بالإضافة إلى الحديقة العامة ومتحف التاريخ الطبيعي والحدائق النباتية.",
        desc_en: "One of Bordeaux's most important squares and among Europe's largest. Its huge fountain, built between 1818 and 1828, honours a group of republican politicians of the French Revolution. The original was destroyed in World War II and later rebuilt. Beside it lies a fine park with beautiful views — especially over the water — along with a public garden, the Natural History Museum and Botanical Garden.",
        image: esplanadeQuinconcesBordeauxAsset.url },
      { num: "12", name_ar: "جسر بونت دي بيير", name_en: "Pont de Pierre",
        desc_ar: "يُعتبر هذا الجسر من أهم المعالم السياحية في المدينة، وهو جسر حجري رائع تم إنشاؤه عام 1817م على يد المهندس المعماري الشهير كلود ديكامب، وتم الانتهاء من بنائه عام 1821م. يتميّز الجسر بإطلالته على نهر غارون، كما يوجد به 17 قوساً تم تثبيتها به لتحمّل التيارات القوية، السطح الخارجي للجسر يتميّز بوجود 12 عموداً كورنثياً.",
        desc_en: "One of Bordeaux's most iconic monuments — a majestic stone bridge begun in 1817 by architect Claude Deschamps and completed in 1821. Overlooking the Garonne, it carries 17 arches to withstand the strong currents, with 12 Corinthian columns along its outer face.",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Bordeaux_%C3%89glise_Saint-Michel_Fl%C3%A8che_Saint-Michel_Vue_sur_le_Pont_de_Pierre_1.jpg/3840px-Bordeaux_%C3%89glise_Saint-Michel_Fl%C3%A8che_Saint-Michel_Vue_sur_le_Pont_de_Pierre_1.jpg" },
    ],
  },

  chamonix: {
    tagline_ar: "سقف أوروبا · وطن التزلج · جبل مون بلان",
    tagline_en: "Roof of Europe · Home of skiing · At the foot of Mont Blanc",
    section_title_ar: "السياحة بمدينة شامونيه",
    section_title_en: "Sightseeing in Chamonix",
    source_url: "https://100region.com/?p=33191&amp=1",
    intro_ar: [
      "إن كنت تبحث عن مدينة أوروبية سياحية رائعة ورخيصة في نفس الوقت فننصحك بشامونيه.",
      "تُعتبر مدينة شامونيه من أهم مدن فرنسا السياحية، فعند نيّة السفر إلى فرنسا، تكون هذه المدينة موضوعة في قائمة المدن الفرنسية المنويّ زيارتها. تقع شامونيه بالقرب من قمم جبال Aiguilles Rouges، وتُعتبر هذه المدينة واحدة من أقدم المنتجعات السياحية في فرنسا.",
      "تضم هذه المدينة 16 قرية ومنتجعاً صحياً، هذا مع تمتّعها بمناخ قاري رطب، وذلك بسبب ارتفاع هذه المدينة، ففي الصيف معتدل وفي الشتاء بارد وثلجي، لذلك تُعتبر منتجع الرياضات الشتوية، وموسم السياحة في فرنسا في هذا التوقيت يكون لمدينة شامونيه النصيب الأكبر منه، وخاصة لهواة رياضات التزلج وتسلق الجبال الثلجية. ويُضاف إلى كل ذلك أن هذه المدينة تحتوي على أعلى محطة تلفريك في العالم، وأعلى سيارة كابينة صعود في العالم.",
      "تشتهر مدينة شامونيه الفرنسية بكونها واحدة من المراكز الرئيسية للسياحة والرياضات الشتوية في جبال الألب في فرنسا، فهي أول مدينة في العالم استضافت الألعاب الأولمبية الشتوية سنة 1924م، وإلى يومنا هذا تظل أحد أجمل الوجهات السياحية الفرنسية التي تستحق الزيارة على مدار العام.",
      "توفّر شامونيه العديد من وسائل النقل العامة لسهولة التنقّل بين أجزاء المدينة وبعضها البعض، كما توفّر شبكة من القطارات التي تربط المدينة بمدن فرنسا الأخرى، لذلك تستطيع تقليل تكلفة التنقّل في المدينة باستخدام وسائل النقل العامة أو القطار.",
      "تتنوّع أنشطة السائحين في شامونيه ما بين ممارسة التزلج، والمشي، والأنشطة في الهواء الطلق والاستمتاع بالمناظر الخلابة، ذلك فضلاً عن التجديف، وجولات التزلج مع جولات من يوم إلى عدة أيام، كما تشمل قائمة الأنشطة في شامونيه التجديف وتسلق الجبال وصيد الأسماك.",
    ],
    intro_en: [
      "Looking for a wonderful European destination that's also easy on the wallet? We'd point you to Chamonix.",
      "Chamonix is one of France's most important tourist towns and one of the first places anyone planning a trip to France will add to their list. Nestled beside the Aiguilles Rouges peaks, it is one of the country's oldest resorts.",
      "It contains 16 villages and a health spa, with a damp continental climate — mild in summer, cold and snowy in winter — which makes it a winter-sports resort par excellence. During the season Chamonix takes the lion's share of French tourism, especially among skiers and snow climbers, and it holds the world's highest cable car and highest cabin lift.",
      "Chamonix is one of the main hubs for tourism and winter sports in the French Alps — the first city ever to host the Winter Olympics, in 1924 — and remains a beautiful year-round destination.",
      "Public transport within Chamonix makes it easy to get around, and a rail network connects it to other French cities, so you can keep travel costs low with buses and trains.",
      "Activities range from skiing, hiking and outdoor adventure to river rafting and multi-day ski tours, along with mountain climbing and fishing.",
    ],
    closing_ar: "«حين تصعد شامونيه، ترى فرنسا كلها تحت قدميك.»",
    closing_en: "\u201CClimb Chamonix, and all of France lies beneath your feet.\u201D",
    attractions: [
      { num: "01", name_ar: "الجبل الأبيض Mont Blanc", name_en: "Mont Blanc",
        desc_ar: "الجبل الأبيض (مون بلون) Mont Blanc يقع هذا الجبل في مدينة شامونيه على الحدود الفرنسية الإيطالية، ويُعتبر من أعلى جبال أوروبا الغربية، والغريب في الأمر أن علو الجبل وارتفاعه يختلف من عام إلى آخر بين الزيادة والنقصان. يُعدّ مونت بلانك أحد أروع المعالم الطبيعية في شامونيه، وهو أعلى قمة في جبال الألب، ويُشكّل جزءاً من الحدود الفرنسية مع إيطاليا، إذ يصل مونت بلانك إلى ارتفاع 4810 متر، بحيث يكون دوماً مغطى بالثلوج، الأمر الذي يُفسّر لماذا يُطلق عليه الجبل الأبيض، كما يشتهر مونت بلانك باسم سقف أوروبا. يمكن للمتسلقين من ذوي الخبرة الوصول إلى القمة بمساعدة دليل، وبالنسبة للهواة هناك أيضاً مسارات أخرى للمشي لمسافات طويلة والتي تتفاوت في الصعوبة.",
        desc_en: "Mont Blanc rises on the French–Italian border at Chamonix, the highest peak in Western Europe — its height varies subtly from year to year. Reaching 4,810 metres and perpetually snow-covered, it earned the name White Mountain and is nicknamed the Roof of Europe. Experienced climbers can reach the summit with a guide; hikers have plenty of other trails to choose from at varying difficulty levels.",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Mont_Blanc_Aiguille.jpg", tall: true },
      { num: "02", name_ar: "قمة دو ميدي", name_en: "Aiguille du Midi",
        desc_ar: "أن تكون الأرض تحت قدميك، ذلك أمر مدهش، لكن الذين يعانون من فوبيا المناطق المرتفعة سيكون الأمر صعباً عليهم. لا تخف عزيزي، فأنت في قمة دو ميدي، التي يزيد ارتفاعها عن 3800 متر، والتي من أبرز الرموز السياحية في شامونيه فرنسا. تستطيع الوصول إلى هذه القمة عبر محطات التلفريك التي تنقلك وتريك الكهوف الطبيعية الرائعة، بالإضافة إلى المنظر الذي لن تنساه أبداً، عندما تكون الأرض كلها، شامونيه وفرنسا بأكملها، تحت ناظريك.",
        desc_en: "Standing above the earth is astonishing — though not for those afraid of heights. At the Aiguille du Midi, over 3,800 metres up, one of Chamonix's most iconic sights, cable cars carry you past stunning natural caves to a view you'll never forget: Chamonix and much of France stretched out beneath you.",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Aiguille-du-Midi-sundown.JPG" },
      { num: "03", name_ar: "فاليه بلانش Vallee Blanche", name_en: "Vallée Blanche",
        desc_ar: "يُعتبر فاليه بلانش أحد رموز مدينة شامونيه في فرنسا، وهو عبارة عن مسار تزلج بطول 20 كم، ويقودك مسار التزلج هذا إلى أكبر كتلة جليدية وأعلى قمة، قمة الجبل الأبيض مون بلون. كما يمكنك في منتصف الطريق المرور على المطاعم والمقاهي والحانات الموجودة، هذا في طريق العودة من القمة، ثم تستأنف مسيرك قليلاً وأنت تتزلج قبل أن تصل إلى محطة القطار التي ستقودك إلى مدينة شامونيه.",
        desc_en: "Vallée Blanche is one of Chamonix's icons — a 20 km ski run leading through the largest glacier and highest peak, Mont Blanc. Halfway down, stop at restaurants, cafés and bars on the way back from the summit, then ski on to the train station that carries you back into Chamonix.",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/29/ValleeBlancheFromSE_%28cropped%29.JPG" },
      { num: "04", name_ar: "متحف شامونيه", name_en: "Chamonix Alpine Museum",
        desc_ar: "يمنحك متحف شامونيه الفرصة لاكتشاف الحقائق المثيرة عن تاريخ الوادي ومشاهدة مجموعة من المعروضات المثيرة للاهتمام، بما في ذلك مجموعة من المعادن والطباعة الحجرية، فضلاً عن مجموعة من المطبوعات والملصقات القديمة، التي يحكي كل منها قصة حدث مهم في تاريخ المدينة، كما ويحتوي متحف شامونيه على مجموعة ممتازة من المطبوعات والصور التي تُظهر تطوّر المدينة بين القرنين الثامن عشر والعشرين، هناك أيضاً مقتنيات قديمة تُظهر روعة الفن والأزياء التقليدية.",
        desc_en: "The Chamonix Alpine Museum lets you dive into the valley's rich history: minerals, lithographs, and old prints and posters — each telling the story of an important moment in the town's past. Its excellent collection of prints and photographs traces Chamonix's development from the 18th to the 20th century, alongside older pieces showcasing traditional art and dress.",
        image: "/__l5e/assets-v1/a570410d-42c4-4a9e-8661-3b1f5e5f7af4/chamonix-alpine-museum.jpg" },
      { num: "05", name_ar: "سوق شامونيه", name_en: "Chamonix Market",
        desc_ar: "يتم تنظيم حدث تقليدي مثير للاهتمام كل يوم سبت في وسط شامونيه، وهو سوق المدينة الرائع الذي يقام أسبوعياً في مركز المدينة، ويتم إغلاق العديد من الشوارع خصيصاً له، حيث يحظى بشعبية كبيرة ما بين السائحين. ليس فقط لكونه يمنحهم الفرصة لاكتشاف طبيعة الحياة بالمدينة، بل لكونه يقدم لزائريه أفضل الأطباق الوطنية، ولعل أكثر الوجبات شيوعاً هنا هي الدجاج المقلي المطبوخ مباشرة في السوق، حيث يمكنك شراء هذا الدجاج والخبز الطازج والذهاب إلى الحديقة المجاورة لقضاء بعض الوقت الممتع.",
        desc_en: "Every Saturday, a lovely tradition takes over central Chamonix: the town's weekly market, with several streets closed off for it. Popular with tourists, it lets you discover local life and offers the best of national dishes — most famously fried chicken cooked on the spot; grab some with fresh bread and picnic in the nearby park.",
        image: "/__l5e/assets-v1/f4f00ad8-dd74-4f93-b74e-b340c07abe62/chamonix-market.jpg" },
      { num: "06", name_ar: "منتزه شامونيه الترفيهي", name_en: "Chamonix Amusement Park",
        desc_ar: "يمثّل منتزه شامونيه الترفيهي أحد أجمل الأماكن السياحية التي نوصيك بزيارتها في مدينة شامونيه، لاسيما إن كنت مسافراً بصحبة الأطفال الصغار. إذ يضم هذا المكان الرائع العديد من الألعاب المميزة التي تناسب كافة أفراد العائلة، بما في ذلك الكبار والصغار، من الزحليقة المثيرة والقارب الطائر والتزحلق على أطول زحليقة في المنتزه بطول 40 متر، والتزلج على الجليد.",
        desc_en: "The Chamonix amusement park is one of the loveliest spots to visit, especially with small children. Its rides suit the whole family — the exciting slide, the flying boat, a 40-metre slide (the park's longest) and ice-skating.",
        image: "/__l5e/assets-v1/57aa7559-40ef-4688-ab17-751042ffe238/chamonix-amusement-park.jpg" },
      { num: "07", name_ar: "قرية شامونيه", name_en: "Chamonix Village",
        desc_ar: "يعكس تاريخ قرية شامونيه مزيجاً من التقليدية والحديثة والكثير من الأمور الممتعة التي سيكون بإمكانك اكتشافها عبر التجوّل في المدينة واكتشاف الشاليهات الألبية الجذابة والكنائس الباروكية الجميلة والكنائس البروتستانتية التاريخية، كما يمكنك عزيزي المسافر البقاء في تلك القرية الجميلة لعدة أيام، لاسيما مع كونها تضم عدداً من الفنادق الحديثة الفاخرة، مع نُزل ريفي رائع، وسط الأجواء الراقية والبوتيكات الفاخرة، كما تضم القرية أيضاً العشرات من المطاعم التي تتنوّع ما بين المحلية والعالمية.",
        desc_en: "Chamonix village blends tradition with modernity — charming Alpine chalets, beautiful baroque churches and historic Protestant chapels. It's a place worth staying for several days: it holds elegant modern luxury hotels, a wonderful country inn, sophisticated boutiques and dozens of local and international restaurants.",
        image: MISSING_IMAGE },
    ],
  },
};
