import type { Guide } from "./france-guides";

const U = (p: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${p}?w=1200&ssl=1`;

const erasOne: Guide = {
  slug: "egypt-eras-1",
  title_ar: "تسلسل العصور التاريخية لمصر — الجزء الأول",
  title_en: "Egypt's historical eras — Part one",
  kicker_ar: "تاريخ",
  kicker_en: "History",
  image: U("2022/10/img_3949-1.jpg"),
  blocks: [
    { type: "P", ar: "تعرف على تسلسل العصور التاريخية لجمهورية مصر العربية — الجزء الأول", en: "The sequence of historical eras of the Arab Republic of Egypt — part one" },
    { type: "H3", ar: "عصر ما قبل الأسرات", en: "Predynastic Period", noNumber: true },
    { type: "P", ar: "3100-5500 قبل الميلاد", en: "5500–3100 BC" },
    { type: "IMG", src: U("2022/10/img_4162.jpg"), cap_ar: "عصر ما قبل الأسرات", cap_en: "Predynastic Period", size: "compact" as const },
    { type: "H3", ar: "العصر العتيق", en: "Early Dynastic Period", noNumber: true },
    { type: "P", ar: "2686-3100 قبل الميلاد", en: "3100–2686 BC" },
    { type: "IMG", src: U("2022/10/img_4163.jpg"), cap_ar: "العصر العتيق", cap_en: "Early Dynastic Period", size: "compact" as const },
    { type: "H3", ar: "الدولة القديمة", en: "The Old Kingdom", noNumber: true },
    { type: "P", ar: "2181-2686 قبل الميلاد", en: "2686–2181 BC" },
    { type: "IMG", src: U("2022/10/img_4164.jpg"), cap_ar: "الدولة القديمة", cap_en: "The Old Kingdom", size: "compact" as const },
    { type: "H3", ar: "عصر الانتقال الاول", en: "First Intermediate Period", noNumber: true },
    { type: "P", ar: "2055-2181 قبل الميلاد", en: "2181–2055 BC" },
    { type: "IMG", src: U("2022/10/img_4165.jpg"), cap_ar: "عصر الانتقال الاول", cap_en: "First Intermediate Period", size: "compact" as const },
    { type: "H3", ar: "الدولة الوسطى", en: "The Middle Kingdom", noNumber: true },
    { type: "P", ar: "1650-2055 قبل الميلاد", en: "2055–1650 BC" },
    { type: "IMG", src: U("2022/10/img_4167.jpg"), cap_ar: "الدولة الوسطى", cap_en: "The Middle Kingdom", size: "compact" as const },
    { type: "H3", ar: "عصر الانتقال الثاني", en: "Second Intermediate Period", noNumber: true },
    { type: "P", ar: "1550-1650 قبل الميلاد", en: "1650–1550 BC" },
    { type: "IMG", src: U("2022/10/img_4168.jpg"), cap_ar: "عصر الانتقال الثاني", cap_en: "Second Intermediate Period", size: "compact" as const },
    { type: "H3", ar: "الدولة الحديثة", en: "The New Kingdom", noNumber: true },
    { type: "P", ar: "1069-1550 قبل الميلاد", en: "1550–1069 BC" },
    { type: "IMG", src: U("2022/10/img_4169.jpg"), cap_ar: "الدولة الحديثة", cap_en: "The New Kingdom", size: "compact" as const },
    { type: "H3", ar: "عصر الانتقال الثالث", en: "Third Intermediate Period", noNumber: true },
    { type: "P", ar: "747-1069 قبل الميلاد", en: "1069–747 BC" },
    { type: "IMG", src: U("2022/10/img_4170.jpg"), cap_ar: "عصر الانتقال الثالث", cap_en: "Third Intermediate Period", size: "compact" as const },
    { type: "H3", ar: "العصر المتأخر", en: "The Late Period", noNumber: true },
    { type: "P", ar: "332-747 قبل الميلاد", en: "747–332 BC" },
    { type: "IMG", src: U("2022/10/img_4171.jpg"), cap_ar: "العصر المتأخر", cap_en: "The Late Period", size: "compact" as const },
    { type: "H3", ar: "العصر البطلمي", en: "The Ptolemaic Period", noNumber: true },
    { type: "P", ar: "30-332 قبل الميلاد", en: "332–30 BC" },
    { type: "IMG", src: U("2022/10/img_4173.jpg"), cap_ar: "العصر البطلمي", cap_en: "The Ptolemaic Period", size: "compact" as const },
  ],
};

const erasTwo: Guide = {
  slug: "egypt-eras-2",
  title_ar: "تسلسل العصور التاريخية لمصر — الجزء الثاني",
  title_en: "Egypt's historical eras — Part two",
  kicker_ar: "تاريخ",
  kicker_en: "History",
  image: U("2022/10/img_3949-1.jpg"),
  blocks: [
    { type: "P", ar: "تعرف على تسلسل العصور التاريخية لجمهورية مصر العربية — الجزء الثاني", en: "The sequence of historical eras of the Arab Republic of Egypt — part two" },
    { type: "H3", ar: "العصر الروماني", en: "The Roman Period", noNumber: true },
    { type: "P", ar: "30 قبل الميلاد – 395 ميلادي", en: "30 BC – 395 AD" },
    { type: "IMG", src: U("2022/10/img_4174.jpg"), cap_ar: "العصر الروماني", cap_en: "The Roman Period", size: "compact" as const },
    { type: "H3", ar: "العصر البيزنطي", en: "The Byzantine Period", noNumber: true },
    { type: "P", ar: "641-330 ميلادي", en: "330–641 AD" },
    { type: "IMG", src: U("2022/10/img_4175.jpg"), cap_ar: "العصر البيزنطي", cap_en: "The Byzantine Period", size: "compact" as const },
    { type: "H3", ar: "عصر الخلفاء الراشدون", en: "The Rashidun Caliphate", noNumber: true },
    { type: "P", ar: "661-632 ميلادي", en: "632–661 AD" },
    { type: "IMG", src: U("2022/10/img_4176.jpg"), cap_ar: "عصر الخلفاء الراشدون", cap_en: "The Rashidun Caliphate", size: "compact" as const },
    { type: "H3", ar: "العصر الأموي", en: "The Umayyad Period", noNumber: true },
    { type: "P", ar: "750-661 ميلادي", en: "661–750 AD" },
    { type: "IMG", src: U("2022/10/img_4177.jpg"), cap_ar: "العصر الأموي", cap_en: "The Umayyad Period", size: "compact" as const },
    { type: "H3", ar: "العصر العباسي", en: "The Abbasid Period", noNumber: true },
    { type: "P", ar: "1517-750 ميلادي", en: "750–1517 AD" },
    { type: "IMG", src: U("2022/10/img_4178.jpg"), cap_ar: "العصر العباسي", cap_en: "The Abbasid Period", size: "compact" as const },
    { type: "H3", ar: "الدولة الطولونية", en: "The Tulunid State", noNumber: true },
    { type: "P", ar: "905-868 ميلادي", en: "868–905 AD" },
    { type: "IMG", src: U("2022/10/img_4179.jpg"), cap_ar: "الدولة الطولونية", cap_en: "The Tulunid State", size: "compact" as const },
    { type: "H3", ar: "العصر الاخشيدي", en: "The Ikhshidid Period", noNumber: true },
    { type: "P", ar: "969-935 ميلادي", en: "935–969 AD" },
    { type: "IMG", src: U("2022/10/img_4180.jpg"), cap_ar: "العصر الاخشيدي", cap_en: "The Ikhshidid Period", size: "compact" as const },
    { type: "H3", ar: "الدولة الفاطمية", en: "The Fatimid State", noNumber: true },
    { type: "P", ar: "1171-912 ميلادي", en: "912–1171 AD" },
    { type: "IMG", src: U("2022/10/img_4181.jpg"), cap_ar: "الدولة الفاطمية", cap_en: "The Fatimid State", size: "compact" as const },
    { type: "H3", ar: "الدولة الأيوبية", en: "The Ayyubid State", noNumber: true },
    { type: "P", ar: "1250-1171 ميلادي", en: "1171–1250 AD" },
    { type: "IMG", src: U("2022/10/img_4182.jpg"), cap_ar: "الدولة الأيوبية", cap_en: "The Ayyubid State", size: "compact" as const },
    { type: "H3", ar: "دولة المماليك البحرية", en: "The Bahri Mamluk State", noNumber: true },
    { type: "P", ar: "1382-1250 ميلادي", en: "1250–1382 AD" },
    { type: "IMG", src: U("2022/10/img_4183.jpg"), cap_ar: "دولة المماليك البحرية", cap_en: "The Bahri Mamluk State", size: "compact" as const },
    { type: "H3", ar: "دولة المماليك الجراكسة (البرجية)", en: "The Circassian (Burji) Mamluk State", noNumber: true },
    { type: "P", ar: "1517-1382 ميلادي", en: "1382–1517 AD" },
    { type: "IMG", src: U("2022/10/img_4184.jpg"), cap_ar: "دولة المماليك الجراكسة (البرجية)", cap_en: "The Circassian (Burji) Mamluk State", size: "compact" as const },
    { type: "H3", ar: "العصر العثماني", en: "The Ottoman Period", noNumber: true },
    { type: "P", ar: "1805-1517 ميلادي", en: "1517–1805 AD" },
    { type: "IMG", src: U("2022/10/img_4185.jpg"), cap_ar: "العصر العثماني", cap_en: "The Ottoman Period", size: "compact" as const },
    { type: "H3", ar: "عصر أسرة محمد علي", en: "The Muhammad Ali Dynasty", noNumber: true },
    { type: "P", ar: "1953-1805 ميلادي", en: "1805–1953 AD" },
    { type: "IMG", src: U("2022/10/img_4186.jpg"), cap_ar: "عصر أسرة محمد علي", cap_en: "The Muhammad Ali Dynasty", size: "compact" as const },
  ],
};

const distances: Guide = {
  slug: "egypt-distances",
  title_ar: "المسافات بين المدن المصرية",
  title_en: "Distances between Egypt's cities",
  kicker_ar: "مسافات",
  kicker_en: "Distances",
  image: U("2022/10/image-8.jpg"),
  blocks: [
    { type: "P", ar: "للتنقل داخل جمهورية مصر العربية لاستكشاف مدنها السياحية وأشهر معالمها البارزة ، اليك المسافات بين أشهر المدن الرئيسية فيها", en: "To move around the Arab Republic of Egypt and explore its tourist cities and best-known landmarks, here are the distances between its main cities." },
    { type: "H3", ar: "المسافة من القاهرة الى بقية المدن", en: "Distances from Cairo to the other cities", noNumber: true },
    { type: "LIST", ar: ["من القاهرة الى الاسكندرية 216 كم", "من القاهرة الى اسوان 926 كم", "من القاهرة الى شرم الشيخ 503 كم", "من القاهرة الى الغردقة 548 كم", "من القاهرة الى الفيوم 91 كم", "من القاهرة الى الاسماعيلية 140 كم", "من القاهرة الى بور سعيد 220 كم", "من القاهرة الى أسيوط 386 كم", "من القاهرة الى الأقصر 708 كم", "من القاهرة الى السويس 135 كم"], en: ["Cairo to Alexandria — 216 km", "Cairo to Aswan — 926 km", "Cairo to Sharm El Sheikh — 503 km", "Cairo to Hurghada — 548 km", "Cairo to Fayoum — 91 km", "Cairo to Ismailia — 140 km", "Cairo to Port Said — 220 km", "Cairo to Assiut — 386 km", "Cairo to Luxor — 708 km", "Cairo to Suez — 135 km"] },
    { type: "H3", ar: "المسافة من الاسكندرية الى بقية المدن", en: "Distances from Alexandria to the other cities", noNumber: true },
    { type: "LIST", ar: ["من الاسكندرية الى القاهرة 216 كم", "من الاسكندرية الى اسوان 1133 كم", "من الاسكندرية الى شرم الشيخ 716 كم", "من الاسكندرية الى الغردقة 761 كم", "من الاسكندرية الى الفيوم 295 كم", "من الاسكندرية الى الاسماعيلية 260 كم", "من الاسكندرية الى بور سعيد 273 كم", "من الاسكندرية الى أسيوط 593 كم", "من الاسكندرية الى الأقصر 662 كم", "من الاسكندرية الى السويس 348 كم"], en: ["Alexandria to Cairo — 216 km", "Alexandria to Aswan — 1133 km", "Alexandria to Sharm El Sheikh — 716 km", "Alexandria to Hurghada — 761 km", "Alexandria to Fayoum — 295 km", "Alexandria to Ismailia — 260 km", "Alexandria to Port Said — 273 km", "Alexandria to Assiut — 593 km", "Alexandria to Luxor — 662 km", "Alexandria to Suez — 348 km"] },
    { type: "H3", ar: "المسافة من اسوان الى بقية المدن", en: "Distances from Aswan to the other cities", noNumber: true },
    { type: "LIST", ar: ["من اسوان الى القاهرة 926 كم", "من اسوان الى الاسكندرية 1133 كم", "من اسوان الى شرم الشيخ 1429 كم", "من اسوان الى الغردقة 500 كم", "من اسوان الى الفيوم 852 كم", "من اسوان الى الاسماعيلية 1066 كم", "من اسوان الى بور سعيد 1146 كم", "من اسوان الى أسيوط 540 كم", "من اسوان الى الأقصر 229 كم", "من اسوان الى السويس 1061 كم"], en: ["Aswan to Cairo — 926 km", "Aswan to Alexandria — 1133 km", "Aswan to Sharm El Sheikh — 1429 km", "Aswan to Hurghada — 500 km", "Aswan to Fayoum — 852 km", "Aswan to Ismailia — 1066 km", "Aswan to Port Said — 1146 km", "Aswan to Assiut — 540 km", "Aswan to Luxor — 229 km", "Aswan to Suez — 1061 km"] },
    { type: "H3", ar: "المسافة من شرم الشيخ الى بقية المدن", en: "Distances from Sharm El Sheikh to the other cities", noNumber: true },
    { type: "LIST", ar: ["من شرم الشيخ الى القاهرة 503 كم", "من شرم الشيخ الى الاسكندرية 716 كم", "من شرم الشيخ الى اسوان 1429 كم", "من شرم الشيخ الى الغردقة 781 كم", "من شرم الشيخ الى الفيوم 608 كم", "من شرم الشيخ الى الاسماعيلية 456 كم", "من شرم الشيخ الى بور سعيد 536 كم", "من شرم الشيخ الى أسيوط 889 كم", "من شرم الشيخ الى الأقصر 1211 كم", "من شرم الشيخ الى السويس 368 كم"], en: ["Sharm El Sheikh to Cairo — 503 km", "Sharm El Sheikh to Alexandria — 716 km", "Sharm El Sheikh to Aswan — 1429 km", "Sharm El Sheikh to Hurghada — 781 km", "Sharm El Sheikh to Fayoum — 608 km", "Sharm El Sheikh to Ismailia — 456 km", "Sharm El Sheikh to Port Said — 536 km", "Sharm El Sheikh to Assiut — 889 km", "Sharm El Sheikh to Luxor — 1211 km", "Sharm El Sheikh to Suez — 368 km"] },
    { type: "H3", ar: "المسافة من الغردقة الى بقية المدن", en: "Distances from Hurghada to the other cities", noNumber: true },
    { type: "LIST", ar: ["من الغردقة الى القاهرة 548 كم", "من الغردقة الى الاسكندرية 761 كم", "من الغردقة الى اسوان 500 كم", "من الغردقة الى شرم الشيخ كم", "من الغردقة الى الفيوم 781 كم", "من الغردقة الى الاسماعيلية 501 كم", "من الغردقة الى بور سعيد 581 كم", "من الغردقة الى أسيوط 458 كم", "من الغردقة الى الأقصر 282 كم", "من الغردقة الى السويس 413 كم"], en: ["Hurghada to Cairo — 548 km", "Hurghada to Alexandria — 761 km", "Hurghada to Aswan — 500 km", "Hurghada to Sharm El Sheikh — —", "Hurghada to Fayoum — 781 km", "Hurghada to Ismailia — 501 km", "Hurghada to Port Said — 581 km", "Hurghada to Assiut — 458 km", "Hurghada to Luxor — 282 km", "Hurghada to Suez — 413 km"] },
    { type: "H3", ar: "المسافة من الفيوم الى بقية المدن", en: "Distances from Fayoum to the other cities", noNumber: true },
    { type: "LIST", ar: ["من الفيوم الى القاهرة 91 كم", "من الفيوم الى الاسكندرية 295 كم", "من الفيوم الى اسوان 852 كم", "من الفيوم الى شرم الشيخ 608 كم", "من الفيوم الى الغردقة 781 كم", "من الفيوم الى الاسماعيلية 245 كم", "من الفيوم الى بور سعيد 325 كم", "من الفيوم الى أسيوط 312 كم", "من الفيوم الى الأقصر 620 كم", "من الفيوم الى السويس 240 كم"], en: ["Fayoum to Cairo — 91 km", "Fayoum to Alexandria — 295 km", "Fayoum to Aswan — 852 km", "Fayoum to Sharm El Sheikh — 608 km", "Fayoum to Hurghada — 781 km", "Fayoum to Ismailia — 245 km", "Fayoum to Port Said — 325 km", "Fayoum to Assiut — 312 km", "Fayoum to Luxor — 620 km", "Fayoum to Suez — 240 km"] },
    { type: "H3", ar: "المسافة من الاسماعيلية الى بقية المدن", en: "Distances from Ismailia to the other cities", noNumber: true },
    { type: "LIST", ar: ["من الاسماعيلية الى القاهرة 140 كم", "من الاسماعيلية الى الاسكندرية 260 كم", "من الاسماعيلية الى اسوان 1066 كم", "من الاسماعيلية الى شرم الشيخ 456 كم", "من الاسماعيلية الى الغردقة 501 كم", "من الاسماعيلية الى الفيوم 245 كم", "من الاسماعيلية الى بور سعيد 80 كم", "من الاسماعيلية الى أسيوط 526 كم", "من الاسماعيلية الى الأقصر 848 كم", "من الاسماعيلية الى السويس 88 كم"], en: ["Ismailia to Cairo — 140 km", "Ismailia to Alexandria — 260 km", "Ismailia to Aswan — 1066 km", "Ismailia to Sharm El Sheikh — 456 km", "Ismailia to Hurghada — 501 km", "Ismailia to Fayoum — 245 km", "Ismailia to Port Said — 80 km", "Ismailia to Assiut — 526 km", "Ismailia to Luxor — 848 km", "Ismailia to Suez — 88 km"] },
    { type: "H3", ar: "المسافة من بور سعيد الى بقية المدن", en: "Distances from Port Said to the other cities", noNumber: true },
    { type: "LIST", ar: ["من بور سعيد الى القاهرة 220 كم", "من بور سعيد الى الاسكندرية 273 كم", "من بور سعيد الى اسوان 1146 كم", "من بور سعيد الى شرم الشيخ 536 كم", "من بور سعيد الى الغردقة 581 كم", "من بور سعيد الى الفيوم 325 كم", "من بور سعيد الى الاسماعيلية 89 كم", "من بور سعيد الى أسيوط 606 كم", "من بور سعيد الى الأقصر 928 كم", "من بور سعيد الى السويس 168 كم"], en: ["Port Said to Cairo — 220 km", "Port Said to Alexandria — 273 km", "Port Said to Aswan — 1146 km", "Port Said to Sharm El Sheikh — 536 km", "Port Said to Hurghada — 581 km", "Port Said to Fayoum — 325 km", "Port Said to Ismailia — 89 km", "Port Said to Assiut — 606 km", "Port Said to Luxor — 928 km", "Port Said to Suez — 168 km"] },
    { type: "H3", ar: "المسافة من أسيوط الى بقية المدن", en: "Distances from Assiut to the other cities", noNumber: true },
    { type: "LIST", ar: ["من أسيوط الى القاهرة 386 كم", "من أسيوط الى الاسكندرية 593 كم", "من أسيوط الى اسوان 540 كم", "من أسيوط الى شرم الشيخ 889 كم", "من أسيوط الى الغردقة 458 كم", "من أسيوط الى الفيوم 312 كم", "من أسيوط الى الاسماعيلية 526 كم", "من أسيوط الى بور سعيد 606 كم", "من أسيوط الى الأقصر 322 كم", "من أسيوط الى السويس 521 كم"], en: ["Assiut to Cairo — 386 km", "Assiut to Alexandria — 593 km", "Assiut to Aswan — 540 km", "Assiut to Sharm El Sheikh — 889 km", "Assiut to Hurghada — 458 km", "Assiut to Fayoum — 312 km", "Assiut to Ismailia — 526 km", "Assiut to Port Said — 606 km", "Assiut to Luxor — 322 km", "Assiut to Suez — 521 km"] },
    { type: "H3", ar: "المسافة من الأقصر الى بقية المدن", en: "Distances from Luxor to the other cities", noNumber: true },
    { type: "LIST", ar: ["من الأقصر الى القاهرة 708 كم", "من الأقصر الى الاسكندرية 662 كم", "من الأقصر الى اسوان 229 كم", "من الأقصر الى شرم الشيخ 1211 كم", "من الأقصر الى الغردقة 282 كم", "من الأقصر الى الفيوم 620 كم", "من الأقصر الى الاسماعيلية 848 كم", "من الأقصر الى بور سعيد 928 كم", "من الأقصر الى أسيوط 322 كم", "من الأقصر الى السويس 843 كم"], en: ["Luxor to Cairo — 708 km", "Luxor to Alexandria — 662 km", "Luxor to Aswan — 229 km", "Luxor to Sharm El Sheikh — 1211 km", "Luxor to Hurghada — 282 km", "Luxor to Fayoum — 620 km", "Luxor to Ismailia — 848 km", "Luxor to Port Said — 928 km", "Luxor to Assiut — 322 km", "Luxor to Suez — 843 km"] },
    { type: "H3", ar: "المسافة من السويس الى بقية المدن", en: "Distances from Suez to the other cities", noNumber: true },
    { type: "LIST", ar: ["من السويس الى القاهرة 135 كم", "من السويس الى الاسكندرية 348 كم", "من السويس الى اسوان 1061 كم", "من السويس الى شرم الشيخ 368 كم", "من السويس الى الغردقة 413 كم", "من السويس الى الفيوم 240 كم", "من السويس الى الاسماعيلية 88 كم", "من السويس الى بور سعيد 168 كم", "من السويس الى أسيوط 521 كم", "من السويس الى الأقصر 843 كم"], en: ["Suez to Cairo — 135 km", "Suez to Alexandria — 348 km", "Suez to Aswan — 1061 km", "Suez to Sharm El Sheikh — 368 km", "Suez to Hurghada — 413 km", "Suez to Fayoum — 240 km", "Suez to Ismailia — 88 km", "Suez to Port Said — 168 km", "Suez to Assiut — 521 km", "Suez to Luxor — 843 km"] },
  ],
};

const album: Guide = {
  slug: "egypt-album",
  title_ar: "ألبوم صور مصر",
  title_en: "Egypt photo album",
  kicker_ar: "ألبوم الصور",
  kicker_en: "Photo album",
  image: U("2022/05/img_6427.jpg"),
  blocks: [
    { type: "P", ar: "مجموعة من صور الرحلة إلى جمهورية مصر العربية", en: "A selection of photographs from the journey through the Arab Republic of Egypt." },
  ],
  gallery: [
    { src: U("2022/05/img_6427.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6428.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6429.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6430.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6431.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6438.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6437.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6436.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6435.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6434.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6433.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6432.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6439.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6440.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6441.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6442.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6443.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6444.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6445.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6452.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6451.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6450.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6449.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6448.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6447.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
    { src: U("2022/05/img_6446.jpg"), cap_ar: "مصر", cap_en: "Egypt" },
  ],
};

export const egyptErasGuides: Guide[] = [erasOne, erasTwo, distances, album];
