import type { Guide } from "./france-guides";

const U = (p: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${p}?w=1200&ssl=1`;

const g = (p: string, cap_ar = "", cap_en = "") => ({
  type: "IMG" as const,
  src: U(p),
  cap_ar,
  cap_en,
  size: "compact" as const,
});

const mainSites: Guide = {
  slug: "egypt-archaeological-sites",
  title_ar: "أشهر المواقع الأثرية في مصر",
  title_en: "Egypt's most famous archaeological sites",
  kicker_ar: "مواقع أثرية",
  kicker_en: "Archaeological sites",
  image: U("2022/10/image-6.jpg"),
  blocks: [
    { type: "H3", ar: "مفهوم المواقع الأثرية", en: "The concept of archaeological sites", noNumber: true },
    { type: "P", ar: "خلفت الحضارات الغابرة خلفها العديد من الآثار التي بقيت شاهدة عليها ، ودالة على ما كان يتميز به أبناؤها من عمق في التفكير ، وابداع في العمارة ، والفنون ، وفلسفة حياتية عظيمة ، الآثار اجمالا ليست حكرا على منطقة دون المناطق الأخرى ، فهي موجودة في كافة أصقاع المعمورة ، فلا تكاد تخلو دولة ما من معلم أثري هام استطاع أن يخلد حضارة ، وابداعا ، وعظمة", en: "Ancient civilisations left behind many antiquities that still bear witness to them, showing the depth of thought, architectural creativity, arts and great philosophy of life of their people. Antiquities are not confined to one region: they exist all over the world, and hardly any country is without an important archaeological landmark that immortalises a civilisation, a creativity and a greatness." },
    { type: "P", ar: "يمكن تعريف الموقع الأثري على أنه ذلك الموقع الذي يتضمن الدلائل الأثرية ، والتي تتم دراستها ، وفحصها من قبل المختصين في علم الآثار ، ليتم الاستفادة منها لاحقا ، وتوظيفها في العديد من المجالات المختلفة ، حيث تفيد المواقع الأثرية بشكل رئيسي في التعرف على سلوكات الأشخاص الذين تواجدوا يوما ما في الموقع قيد البحث ، والدراسة ، أو أولئك الذين استفادوا منه في حياتهم اليومية ، مما يساعد في التعرف على طبيعة الحياة التي كانت سائدة قديما", en: "An archaeological site can be defined as a place containing archaeological evidence that is studied and examined by specialists in archaeology so it can later be used in many different fields. Archaeological sites mainly help us understand the behaviour of the people who once lived at the site under study, or who used it in their daily lives, which helps us learn about the nature of life in ancient times." },
    { type: "H3", ar: "البحث عن المواقع الأثرية", en: "Searching for archaeological sites", noNumber: true },
    { type: "P", ar: "يعتبر البحث والتنقيب عن المواقع الأثرية من أهم الخطوات المؤدية الى اكتشاف الكنوز الأثرية التي تتضمنها هذه المواقع ، المواقع الأثرية بشكل عام توجد اما على اليابسة ، أو في أعماق البحار ، والمسطحات المائية ، ومن هنا فان بعضها يمتاز بسهولة ايجادها ، حيث تقع في مواقع بارزة من اليابسة ، أو من أماكن التجمعات البشرية ، من جهة أخرى ، فان يجاد بعض المواقع الأثرية يحتاج من العلماء المختصين الى اتباع الطرق العلمية الدقيقة ، وبذل مجهودات كبيرة في سبيل ذلك ، ولعل أبرز هذه الطرق مسح المنطقة المتوقع ايجاد موقع ما فيها سيرا على الأقدام ، الى جانب توظيف الوسائل التقنية الحديثة في ذلك ، كالتصوير الجوي ، والكواشف المعدنية وغيرها", en: "Searching and excavating for archaeological sites is one of the most important steps towards discovering the treasures they contain. Archaeological sites are generally found either on land or in the depths of seas and other bodies of water; some are easy to find because they lie in prominent places on land or near human settlements, while others require specialists to follow precise scientific methods and make great efforts, most notably surveying the expected area on foot alongside modern technical means such as aerial photography and metal detectors." },
    { type: "P", ar: "بعد اكتشاف الموقع الأثري ، يقوم العلماء بتسجيل ملاحظاتهم حوله ، كما ويقومون أيضا بالتقاط الصور له ، ثم رسم الخرائط ، ثم يبدؤون بالتعمق أكثر في محتويات هذا الموقع بالطرق العلمية", en: "After a site is discovered, scholars record their observations about it, take photographs, draw maps, and then begin to examine the contents of the site more deeply through scientific methods." },
    { type: "H3", ar: "المحافظة على المواقع الأثرية", en: "Preserving archaeological sites", noNumber: true },
    { type: "P", ar: "ان واجب المحافظة على المواقع الأثرية من العبث ، والتخريب يعتبر من أولى الواجبات وأكثرها أهمية ، وهذا الواجب غير منوط بجهة معينة دون الجهات الأخرى ، حيث يقع على عاتق الجميع ، لعل الدول والحكومات هي أكثر الجهات تحملا لمسؤولية المحافظة على المواقع الأثرية التي تقع ضمن حدودها ، وذلك من خلال عملها الدوؤب على تنظيفه ، وترتيبه ، وتهيئته لاستقبال الزوار ، الى جانب تعريف العالم عليه ، احياء له ، وجذبا للسياح", en: "The duty of protecting archaeological sites from tampering and vandalism is among the first and most important of duties, and it is not assigned to one party alone — it rests on everyone. States and governments perhaps bear the greatest responsibility for preserving the sites within their borders, through constant work to clean, organise and prepare them to receive visitors, as well as introducing them to the world to revive them and attract travellers." },
    { type: "P", ar: "كما أن المواطنين مسؤولون أيضا عن المواقع الأثرية ، وذلك من خلال عدم العبث بها ، أو تخريبها ، خاصة وأن هذه المواقع تعتبر ارثا وطنيا هاما ، وحساسا ، ويجب ألا تكون في أي وقت من الأوقات عرضة لأنواع العبث المختلفة", en: "Citizens are also responsible for archaeological sites by not tampering with or damaging them, especially since these sites are an important and sensitive national heritage that must never be exposed to any kind of abuse." },
    { type: "H3", ar: "أولا : القاهرة", en: "First: Cairo", noNumber: true },
    {
      type: "CARDS",
      items: [
        { topic: "egypt-site-heliopolis", label_ar: "مصر الجديدة هيليوبوليس", label_en: "Heliopolis", src: U("2022/10/img_3919.jpg") },
        { topic: "muhammad-ali-mosque", label_ar: "قلعة صلاح الدين الايوبي", label_en: "The Citadel of Saladin", src: U("2022/10/img_3915.jpg") },
        { topic: "egypt-site-al-muizz", label_ar: "شارع المعز وتوابعه", label_en: "Al-Muizz Street and its surroundings", src: U("2022/10/img_3956.jpg") },
        { topic: "giza-pyramids", label_ar: "هضبة الجيزة وتوابعها", label_en: "The Giza Plateau and its surroundings", src: U("2022/10/img_3952.jpg") },
        { topic: "egypt-site-al-saliba", label_ar: "شارع الصليبة وتوابعه", label_en: "Al-Saliba Street and its surroundings", src: U("2022/10/img_4096.jpg") },
        { topic: "egypt-site-salah-al-din-square", label_ar: "ميدان صلاح الدين وتوابعه", label_en: "Salah al-Din Square and its surroundings", src: U("2022/10/img_4080.jpg") },
        { topic: "egypt-site-senusret-obelisk", label_ar: "مسلة سنوسرت الأول", label_en: "The Obelisk of Senusret I", src: U("2022/10/img_4146.jpg") },
        { topic: "egypt-site-al-suyufiyya", label_ar: "شارع السيوفية وتوابعه", label_en: "Al-Suyufiyya Street and its surroundings", src: U("2022/10/img_4138.jpg") },
      ],
    },
    { type: "H3", ar: "ثانيا : أسوان", en: "Second: Aswan", noNumber: true },
    {
      type: "CARDS",
      items: [
        { topic: "egypt-site-amada-temples", label_ar: "معابد عمدا وتوابعهم", label_en: "The Amada Temples and their surroundings", src: U("2022/10/img_4034.jpg") },
        { topic: "egypt-site-wadi-al-sebua", label_ar: "معابد وادي السبوع", label_en: "The Wadi al-Sebua Temples", src: U("2022/10/img_4027.jpg") },
        { topic: "egypt-site-philae", label_ar: "آثار فيله", label_en: "The Philae Antiquities", src: U("2022/10/img_4127.jpg") },
        { topic: "egypt-site-abu-simbel", label_ar: "معبد أبو سمبل", label_en: "The Abu Simbel Temple", src: U("2022/10/img_4109.jpg") },
      ],
    },
    { type: "H3", ar: "ثالثا : الاسكندرية", en: "Third: Alexandria", noNumber: true },
    {
      type: "CARDS",
      items: [
        { topic: "egypt-site-pompeys-pillar", label_ar: "عمود دقلديانوس", label_en: "Pompey's Pillar", src: U("2022/10/img_4144.jpg") },
        { topic: "egypt-site-abu-mena", label_ar: "منطقة أبو مينا", label_en: "The Abu Mena area", src: U("2022/10/img_4148.jpg") },
      ],
    },
    { type: "H3", ar: "رابعا : سيناء", en: "Fourth: Sinai", noNumber: true },
    {
      type: "CARDS",
      items: [
        { topic: "egypt-site-saint-catherine", label_ar: "دير سانت كاترين وتوابعه", label_en: "Saint Catherine's Monastery and its surroundings", src: U("2022/10/img_4161.jpg") },
      ],
    },
  ],
};

const heliopolis: Guide = {
  slug: "egypt-site-heliopolis",
  title_ar: "مصر الجديدة هيليوبوليس",
  title_en: "Heliopolis",
  kicker_ar: "مواقع أثرية · القاهرة",
  kicker_en: "Archaeological sites · Cairo",
  image: U("2022/10/img_3916.jpg"),
  blocks: [
    { type: "H3", ar: "مصر الجديدة هيليوبوليس", en: "Heliopolis", noNumber: true },
    { type: "P", ar: "وقع اختيار البارون امبان بداية القرن العشرين ، وبمعاونة شريكه المصري باغوص نوبار باشا على منطقة نائية ليبني فيه مدينة احلامه والتي تقع شمال شرق القاهرة ، وبالتحديد بالقرب من منطقة المطرية ، وأطلال مدينة هليوبوليس القديمة ، وتعتبر تلك المدينة التي تحولت من فكرة في ذهن البارون امبان ، الى واحدة من أنجح التجارب العمرانية في أوائل القرن العشرين ، حيث استطاع تحويل الصحراء الى ضاحية نابضة بالحياة متكاملة الخدمات ، تضم كل فئات الشعب وأطيافه", en: "At the beginning of the twentieth century, Baron Empain — with the help of his Egyptian partner Boghos Nubar Pasha — chose a remote area north-east of Cairo, near Matariya and the ruins of ancient Heliopolis, to build the city of his dreams. What began as an idea in the Baron's mind became one of the most successful urban experiments of the early twentieth century: he turned desert into a lively suburb with complete services, home to every class and shade of society." },
    { type: "P", ar: "كما كانت مصر الجديدة بوتقة انصهر فيها العديد من الطرز المعمارية الجديدة والمبتكرة ، والتي دمجت الطراز الاسلامي مع الطراز الهندوسي والأوروبي ، ويعد قصر البارون الذي انتهى بناؤه عام 1911 م أكبر شاهد على هذا التنوع ، حيث استوحى تصميمه المهندس الفرنسي ألكسندر مارسيل من طراز المعابد الكمبودية", en: "Heliopolis was also a melting pot of new and inventive architectural styles that fused Islamic design with Hindu and European forms. The Baron's Palace, completed in 1911, is the greatest witness to that variety: the French architect Alexandre Marcel drew its design from the style of Cambodian temples." },
    { type: "P", ar: "لم يتم تصميم مدينة مصر الجديدة الجميلة كمشروع معماري وحضري مبتكر يعيد احياء التراث الإسلامي الغني لمصر بشكل جديد فقط ، ولكن رأى مؤسساها أيضا وهما البارون امبان ، وشريكه باغوص نوبار باشا أن تكون المدينة شاملة وعالمية", en: "Beautiful Heliopolis was not only designed as an innovative architectural and urban project reviving Egypt's rich Islamic heritage in a fresh way: its founders, Baron Empain and his partner Boghos Nubar Pasha, also intended the city to be inclusive and cosmopolitan." },
    g("2022/10/img_3920.jpg", "مصر الجديدة", "Heliopolis"),
    g("2022/10/img_3921.jpg", "قصر البارون", "The Baron's Palace"),
    g("2022/10/img_3923.jpg", "مصر الجديدة", "Heliopolis"),
    g("2022/10/img_3922.jpg", "مصر الجديدة", "Heliopolis"),
  ],
};

const alMuizz: Guide = {
  slug: "egypt-site-al-muizz",
  title_ar: "شارع المعز وتوابعه",
  title_en: "Al-Muizz Street and its surroundings",
  kicker_ar: "مواقع أثرية · القاهرة",
  kicker_en: "Archaeological sites · Cairo",
  image: U("2022/10/img_3956-1.jpg"),
  blocks: [
    { type: "H3", ar: "شارع المعز وتوابعه", en: "Al-Muizz Street and its surroundings", noNumber: true },
    { type: "P", ar: "يرجع تاريخ شارع المعز الى عصر الخليفة الفاطمي المعز لدين الله (341-365هـ/ 953-975م) ، والذي حكم مصر في الفترة مابين (358-365هـ/ 969-975م) كأول الخلفاء الفاطميين لمصر ، يعد الشارع حاليا أكبر متحف مفتوح للآثار الاسلامية في العالم ، وموقع تراثي فريد تم ادراجه على قائمة مواقع التراث العالمي في عام 1979م ، تغيرت مسميات الشارع على مر العصور التاريخية ، حتى عرف بشارع المعز منذ عام 1937م تكريما له كمنشيء للقاهرة", en: "Al-Muizz Street dates back to the era of the Fatimid caliph al-Muizz li-Din Allah (341–365 AH / 953–975 AD), who ruled Egypt between 358 and 365 AH / 969 and 975 AD as the first Fatimid caliph of Egypt. Today the street is the largest open-air museum of Islamic antiquities in the world, a unique heritage site inscribed on the World Heritage list in 1979. Its names changed over the ages until it became known as Al-Muizz Street in 1937, in honour of the founder of Cairo." },
    { type: "P", ar: "يمتد الشارع بين بابين من أسوار القاهرة القديمة من باب الفتوح شمالا حتى باب زويلة جنوبا ، مرورا بعدة حارات وشوارع تاريخية عريقة من أشهرها شارع أمير الجيوش ، الدرب الأصفر ، حارة برجوان ، خان الخليلي ، والغورية", en: "The street runs between two gates of the old Cairo walls, from Bab al-Futuh in the north to Bab Zuwayla in the south, passing through several ancient alleys and historic streets, the most famous of which are Amir al-Guyush Street, al-Darb al-Asfar, Harat Barjwan, Khan el-Khalili and al-Ghuriya." },
    { type: "P", ar: "يضم الشارع مجموعة من أروع آثار مدينة القاهرة يصل عددها الى تسعة وعشرين أثرا تعكس انطباعا كاملا عن مصر الاسلامية في الفترة من القرن العاشر حتى القرن التاسع عشر الميلادي ، والتي تبدأ من العصر الفاطمي بمصر (358-567هـ/ 969- 1171م) حتى عصر أسرة محمد علي (1220- 1372هـ/ 1805-1953م) ، وتتنوع الآثار الموجودة ما بين مباني دينية وسكنية وتجارية ودفاعية ، واليوم تصطف الأسواق ومحلات الحرف اليدوية التقليدية على طول الشارع مما يضيف الى سحر الشارع التاريخي", en: "The street holds some of Cairo's finest monuments — twenty-nine in total — giving a complete impression of Islamic Egypt from the tenth to the nineteenth century, from the Fatimid era (358–567 AH / 969–1171 AD) to the era of the family of Muhammad Ali (1220–1372 AH / 1805–1953 AD). The monuments range from religious to residential, commercial and defensive buildings, and today markets and traditional craft shops line the street, adding to its historic charm." },
    g("2022/10/img_3955.jpg", "شارع المعز", "Al-Muizz Street"),
    g("2022/10/img_3954.jpg", "شارع المعز", "Al-Muizz Street"),
    g("2022/10/img_3953-1.jpg", "شارع المعز", "Al-Muizz Street"),
    g("2022/10/img_3964.jpg", "شارع المعز", "Al-Muizz Street"),
    { type: "H3", ar: "جامع المؤيد شيخ", en: "The Mosque of al-Mu'ayyad Shaykh" },
    { type: "P", ar: "يقع الجامع في شارع المعز لدين الله ملاصقا لباب زويلة ، شيده السلطان المؤيد شيخ في عام 818 ھ / 1415 م ، يتكون الجامع من صحن ( فناء ) أوسط مكشوف تحيط به أربعة أروقة أكبرها رواق القبلة ، تزين الجدران وزرات رخامية ملونة بارتفاع المحراب ، وبجواره المنبر المطعم بالعاج والصدف ، وعليه كتابات تحمل اسم وألقاب المؤيد الشيخ", en: "The mosque stands on Al-Muizz Street adjoining Bab Zuwayla, built by Sultan al-Mu'ayyad Shaykh in 818 AH / 1415 AD. It consists of an open central courtyard surrounded by four arcades, the largest being the qibla arcade. Coloured marble dadoes decorate the walls to the height of the mihrab, and beside it stands the pulpit inlaid with ivory and mother-of-pearl, bearing inscriptions with the name and titles of al-Mu'ayyad Shaykh." },
    { type: "P", ar: "امتاز الجامع بظاهرة فريدة من نوعها حيث شيدت مئذنتا الجامع فوق أثر آخر وهو باب زويلة المجاور للجامع والذي يرجع للعصر الفاطمي ، وأصبح كلاهما عنصرا معماريا متكاملا بشكل أكثر من رائع ، تحمل المئذنة الغربية اسم منشيء الجامع ، والأخرى تحمل اسم محمد بن القزاز مهندس المئذنة", en: "The mosque has a unique feature: its two minarets were built on top of another monument, the neighbouring Fatimid gate of Bab Zuwayla, so that the two became one superb architectural whole. The western minaret carries the name of the mosque's founder, the other the name of Muhammad ibn al-Qazzaz, the minaret's engineer." },
    { type: "P", ar: "ومن التحف الرائعة التي تزين هذا المسجد الباب الكبير بالمدخل وهو يحمل اسم السلطان حسن ، وقد نقله المؤيد شيخ من مدرسة السلطان حسن الى جامعه هذا ، وهو من أجمل الأبواب الخشبية المصفحة بالنحاس", en: "Among the masterpieces adorning the mosque is the great door at the entrance, which carries the name of Sultan Hasan; al-Mu'ayyad Shaykh moved it from the Madrasa of Sultan Hasan to his own mosque, and it is one of the most beautiful copper-plated wooden doors." },
    g("2022/10/img_3957.jpg"),
    g("2022/10/img_3958.jpg"),
    g("2022/10/img_3959.jpg"),
    g("2022/10/img_3960.jpg"),
    g("2022/10/img_3961.jpg"),
    g("2022/10/img_3968.jpg"),
    g("2022/10/img_3967.jpg"),
    g("2022/10/img_3966.jpg"),
    g("2022/10/img_3965.jpg"),
    g("2022/10/img_3964-1.jpg"),
    g("2022/10/img_3963.jpg"),
    g("2022/10/img_3962.jpg"),
    g("2022/10/img_3971.jpg"),
    { type: "H3", ar: "مدرسة وقبة الصالح نجم الدين أيوب", en: "The Madrasa and Dome of al-Salih Najm al-Din Ayyub" },
    { type: "P", ar: "واحدة من أهم المنشآت المعمارية الباقية من العصر الأيوبي ، تقع في منطقة بين القصرين من شارع المعز لدين الله ، عرفت بالمدرسة الصالحية حيث بدأ في انشائها السلطان الملك الصالح نجم الدين أيوب في عام 641 هـ / 1243 م ، تعد هذه المدرسة هي الأولى من نوعها لتدريس المذاهب السنية في مصر حيث أنشئت لتدريس المذاهب الفقهية الأربعة بدلا من المذهب الشيعي الذي كان يدرسه الفاطميون من قبل ، وكان لكل مذهب مكان خاص بداخل المدرسة", en: "One of the most important surviving Ayyubid buildings, located in the Bayn al-Qasrayn area of Al-Muizz Street. Known as the Salihiyya Madrasa, it was begun by Sultan al-Malik al-Salih Najm al-Din Ayyub in 641 AH / 1243 AD, and was the first of its kind for teaching the Sunni schools in Egypt: it was founded to teach the four schools of jurisprudence instead of the Shiite doctrine previously taught by the Fatimids, with a dedicated space inside for each school." },
    { type: "P", ar: "من أهم ما يميز هذه المدرسة احتفاظ واجهتها الرئيسية بزخارفها الفنية ومئذنتها المميزة التي تعلو المدخل ، ولم يتبق من المدرسة حاليا سوى الايوان الغربي ( ايوان المذهب المالكي )", en: "Among its most distinctive features is that the main façade preserves its artistic decoration and its remarkable minaret above the entrance. Only the western iwan (the iwan of the Maliki school) survives today." },
    { type: "P", ar: "يرجع تاريخ انشاء القبة الضريحية الملاصقة للمدرسة الى عام 647 هـ / 1249 م والتي شيدتها السلطانة شجر الدر زوجة الملك الصالح وذلك بعد وفاة زوجها خلال الحروب الصليبية في المنصورة ، الذي دفن في قلعة الروضة الى أن اكتمل بناء القبة ونقل اليها فى عام 648 هـ / 1250 م", en: "The mausoleum dome adjoining the madrasa dates to 647 AH / 1249 AD and was built by Sultana Shajar al-Durr, wife of al-Malik al-Salih, after her husband died during the Crusades at Mansoura. He was buried in the Rawda citadel until the dome was completed and he was moved into it in 648 AH / 1250 AD." },
    { type: "P", ar: "وللقبة واجهة واحدة رئيسية بها مدخل على شارع المعز يعلوه لوحة تحمل كتابات تشير الى تاريخ وفاة الملك الصالح ، تمثل المقصورة الخشبية بداخل القبة نموذج فريد من نوعه للتحف الخشبية في العصر الأيوبي بزخارفها الكتابية المحيطه بها", en: "The dome has one main façade with an entrance onto Al-Muizz Street, above which a panel bears inscriptions recording the date of al-Malik al-Salih's death. The wooden screen inside the dome is a unique example of Ayyubid woodwork, with inscribed decoration running around it." },
    g("2022/10/img_3969.jpg"),
    g("2022/10/img_3970.jpg"),
    g("2022/10/img_3971-1.jpg"),
    g("2022/10/img_3972.jpg"),
    g("2022/10/img_3979.jpg"),
    g("2022/10/img_3978.jpg"),
    g("2022/10/img_3977.jpg"),
    g("2022/10/img_3976.jpg"),
    g("2022/10/img_3975.jpg"),
    g("2022/10/img_3974.jpg"),
    g("2022/10/img_3973.jpg"),
    g("2022/10/img_3989.jpg"),
    { type: "H3", ar: "سبيل وكتاب عبد الرحمن كتخدا", en: "The Sabil-Kuttab of Abd al-Rahman Katkhuda" },
    { type: "P", ar: "يقع هذا السبيل عند تقاطع شارع المعز مع شارع التمبكشية ، شيده الأمير عبد الرحمن كتخدا القازدغلي سنة 1157 هـ / 1744 م ، وكان أحد قادة الجيش في العصر العثماني بمصر ، وكان مهتما بتشييد العمائر المتنوعة بمدينة القاهرة ، يقع المدخل الرئيسي للسبيل بشارع التمبكشية على يسار الواجهة القبلية ، يعلو باب الدخول لوحة كتابية عبارة عن أبيات من الشعر واسم المنشيء وتاريخ الانشاء بطريقة حساب الجمل ، كما يوجد أيضا مساحة مربعة بداخلها دائرة بها كتابات لأسماء أصحاب الكهف أسفل طاقية العقد", en: "This sabil stands where Al-Muizz Street meets al-Tanbakshiya Street, built by Amir Abd al-Rahman Katkhuda al-Qazdughli in 1157 AH / 1744 AD, a commander of the army in Ottoman Egypt who took a keen interest in erecting buildings of many kinds in Cairo. The main entrance is on al-Tanbakshiya Street to the left of the southern façade; above the door a panel carries verses of poetry, the founder's name and the date of construction in numerological form, and there is also a square panel containing a circle inscribed with the names of the Companions of the Cave beneath the arch hood." },
    { type: "P", ar: "يتكون السبيل من غرفة التسبيل وهي مستطيلة الشكل لها ثلاث واجهات بكل منها شباك نحاسي يتقدمها ألواح رخامية من الخارج مخصصة لوضع كيزان الشرب لسقاية المارة ، غطيت جدران السبيل من الداخل بالبلاطات الخزفية ( القاشاني ) ، والتي تنوعت زخارفها بين الزخارف النباتية العثمانية ، ورسم للحرم المكي ، بالاضافة الى الزخارف الكتابية ومنها كلما دخل عليها زكريا المحراب ، يا مفتح الأبواب افتح لنا خير الباب ، وغيرها من الكتابات ، يعلو السبيل كتاب لتعليم أيتام المسلمين القرآن الكريم والأحاديث الشريفة", en: "The sabil consists of a rectangular distribution room with three façades, each with a bronze grille fronted outside by marble slabs where drinking cups were placed for passers-by. The interior walls are covered with ceramic (qishani) tiles whose decoration ranges from Ottoman plant motifs to a depiction of the Sacred Mosque in Mecca, along with inscriptions such as 'whenever Zakariya entered upon her in the prayer chamber' and 'O opener of doors, open for us the best of doors'. Above the sabil is a kuttab where Muslim orphans were taught the Qur'an and the noble hadiths." },
    g("2022/10/img_3980-1.jpg"),
    g("2022/10/img_3981.jpg"),
    g("2022/10/img_3982.jpg"),
    g("2022/10/img_3989-1.jpg"),
    g("2022/10/img_3988.jpg"),
    g("2022/10/img_3987.jpg"),
    g("2022/10/img_3986.jpg"),
    g("2022/10/img_3985.jpg"),
    g("2022/10/img_3984.jpg"),
    g("2022/10/img_3983.jpg"),
    g("2022/10/img_3994.jpg"),
    { type: "H3", ar: "بوابة زويلة", en: "Bab Zuwayla" },
    { type: "P", ar: "تعد بوابة زويلة ذات البناء المعماري المميز بمئذنتيها الرشيقتان واحدة من أهم المعالم الأثرية في القاهرة الفاطمية ، وهي البوابة الحجرية الباقية من السور الجنوبي لمدينة القاهرة الفاطمية ، تقع عند نهاية شارع الخيامية وتفتح على شارع المعز الذي ينتهي بباب الفتوح ، أنشأها الوزير بدر الجمالي في عهد الخليفة الفاطمي المستنصر بالله سنة (485هـ/1092م) ، سميت البوابة بزويلة نسبة الى قبيلة جاءت من شمال أفريقيا مع قائد الجيوش الفاطمية جوهر الصقلي وسكنت بالقرب من البوابة ، كما عرفت باسم بوابة المتولي لأن متولي الحسبة في العصر الفاطمي كان يجلس عند البوابة لتحصيل الضرائب", en: "With its distinctive architecture and two slender minarets, Bab Zuwayla is one of the most important monuments of Fatimid Cairo — the surviving stone gate of the city's southern wall. It stands at the end of al-Khayamiya Street and opens onto Al-Muizz Street, which ends at Bab al-Futuh. It was built by the vizier Badr al-Jamali during the reign of the Fatimid caliph al-Mustansir in 485 AH / 1092 AD, and named after a tribe that came from North Africa with the Fatimid commander Jawhar al-Siqilli and settled near the gate. It was also known as Bab al-Mutawalli because the Fatimid market inspector sat at the gate to collect taxes." },
    { type: "P", ar: "تتكون البوابة من برجين مستديرين يحصران بينهما باب ، أما بالنسبة للمئذنتين فقد تمت اضافتهما في عام 818هـ/ 1415م على يد السلطان المملوكي المؤيد شيخ حيث بنى مسجده بجوار البوابة واستغل برجيها لاقامة مئذنتي جامعه", en: "The gate consists of two round towers enclosing a doorway. The two minarets were added in 818 AH / 1415 AD by the Mamluk sultan al-Mu'ayyad Shaykh, who built his mosque beside the gate and used its towers to raise the minarets of his mosque." },
    { type: "P", ar: "وشهد باب زويلة حادثة شنق السلطان طومانباي آخر سلاطين المماليك والتي كانت ايذانا بانتهاء الدولة المملوكية وبداية الدولة العثمانية (923هـ /1517م)", en: "Bab Zuwayla witnessed the hanging of Sultan Tuman Bay, the last of the Mamluk sultans, which marked the end of the Mamluk state and the beginning of Ottoman rule (923 AH / 1517 AD)." },
    g("2022/10/img_3990.jpg"),
    g("2022/10/img_3991.jpg"),
    g("2022/10/img_3992.jpg"),
    g("2022/10/img_3993.jpg"),
    g("2022/10/img_3994-1.jpg"),
    g("2022/10/img_3995.jpg"),
    g("2022/10/img_3996-1.jpg"),
    { type: "H3", ar: "بيت السحيمي", en: "Bayt al-Suhaymi" },
    { type: "P", ar: "يقع في حارة الدرب الأصفر في منطقة الجمالية المميزة في شارع المعز ، ويعد من أجمل بيوت مدينة القاهرة ، أقام هذا البيت الشيخ عبد الوهاب الطبلاوي في سنة 1058هـ / 1648م ، وأنشأ القسم الثاني منه الحاج اسماعيل جلبي في سنة 1211هـ / 1796م ، وقام بدمجه بالقسم الأول ليصبح بيتا واحدا ، وعرف البيت بالسحيمي نسبة الى آخر من سكنه الشيخ السحيمي وهو من كبار علماء الأزهر وشيخ رواق الأتراك في العصر العثماني ، وفي سنة 1349هـ/ 1931م باع ورثة السحيمي هذا البيت الى لجنة حفظ الآثار العربية بمبلغ ستة آلاف من الجنيهات", en: "Situated in the alley of al-Darb al-Asfar in the distinctive Gamaliya quarter off Al-Muizz Street, this is one of the most beautiful houses in Cairo. It was built by Sheikh Abd al-Wahhab al-Tablawi in 1058 AH / 1648 AD, and its second section was added by Hajj Ismail Chelebi in 1211 AH / 1796 AD, who merged it with the first to make a single house. The house is named after its last resident, Sheikh al-Suhaymi, a senior scholar of al-Azhar and head of the Turkish riwaq in the Ottoman era. In 1349 AH / 1931 AD his heirs sold the house to the Committee for the Conservation of Arab Monuments for six thousand pounds." },
    { type: "P", ar: "يحتوي البيت على عدة مباني تطل على فناء واسع وحديقة خلابة بمجموعة من المشربيات الخشبية الرائعة ، ويحتوي على مقعد كبير وقاعات استقبال فريدة من نوعها مجهزة بأثاث يمثل روح العصر الذي بني فيه", en: "The house contains several buildings overlooking a wide courtyard and a lovely garden, with a set of magnificent wooden mashrabiyas, a large loggia and unique reception halls furnished in the spirit of the age in which it was built." },
    { type: "P", ar: "ومن أهم العناصر الموجودة بالبيت كرسي الولادة ، حمام ، عدة آبار توفر المياه للبيت بالاضافة الى ساقية مياه تستخدم لري الحديقة ومازال ترسها الخشبي موجودا الى اليوم ، وطاحونة للحبوب تدار عن طريق ثور ومجموعة من الأواني الفخارية والحجرية لحفظ الحبوب", en: "Its most notable elements include the birthing chair, a bathhouse, several wells supplying the house with water, a waterwheel used to irrigate the garden whose wooden gear survives to this day, a grain mill turned by an ox, and a collection of pottery and stone vessels for storing grain." },
    g("2022/10/img_3996.jpg"),
    g("2022/10/img_3997.jpg"),
    g("2022/10/img_3998.jpg"),
    g("2022/10/img_3999.jpg"),
    g("2022/10/img_4001.jpg"),
    g("2022/10/img_4002.jpg"),
    g("2022/10/img_4003.jpg"),
    g("2022/10/img_4010.jpg"),
    g("2022/10/img_4009.jpg"),
    g("2022/10/img_4008.jpg"),
    g("2022/10/img_4007.jpg"),
    g("2022/10/img_4006.jpg"),
    g("2022/10/img_4005.jpg"),
    g("2022/10/img_4004.jpg"),
    g("2022/10/img_4016-1.jpg"),
    { type: "H3", ar: "مدرسة وخانقاة السلطان الظاهر برقوق", en: "The Madrasa and Khanqah of Sultan al-Zahir Barquq" },
    { type: "P", ar: "أنشأها السلطان الظاهر برقوق ما بين عامي ( 786-788ھ/1384-1386م) ، وتقع هذه المجموعة بشارع المعز وتتوسط أحد أكبر مجموعات التراث المعماري في العالم ، للمنشأة وظائف خيرية دينية ، حيث كانت تستخدم كمدرسة لتدريس المذاهب الفقهية الأربعة ومسجد وخانقاه للصوفية ، وبها قبة ضريحية دفن بها والده وعدد من زوجاته وأبنائه", en: "Built by Sultan al-Zahir Barquq between 786 and 788 AH / 1384 and 1386 AD, this complex stands on Al-Muizz Street at the heart of one of the largest concentrations of architectural heritage in the world. It served charitable and religious functions: a madrasa for teaching the four schools of jurisprudence, a mosque and a khanqah for Sufis, with a mausoleum dome where his father and a number of his wives and children were buried." },
    { type: "P", ar: "تتكون المدرسة من صحن مكشوف تحيط به أربعة ايوانات أكبرهم الايوان الجنوبي الشرقي الذي يحتوي على محراب رخامي ومنبر خشبي وكرسي المصحف ودكة المبلغ ، كما ألحق بالمنشأة وطبقات للصوفية وغرف للطلبة ومطبخ ودورة مياه وحظيرة للدواب كمنشأت خدمية للمدرسة ، ويعلو واجهة المدخل مئذنة قمتها على الطراز المملوكى ، تعد المنشأة تحفة معمارية رائعة بكل ما فيها من عناصر معمارية وزخرفية ، ويميز المنشأة النصوص الكتابية النسخية التي تحتوي على آيات قرآنية ، واسم المنشيء وتاريخ الانشاء ، كما تتميز أيضا بالتكسيات الرخامية الملونة وسقف ايوان القبلة بزخارفه الرائعة", en: "The madrasa consists of an open courtyard surrounded by four iwans, the largest being the south-eastern one with its marble mihrab, wooden pulpit, Qur'an stand and muezzin's platform. Attached to it were lodgings for Sufis, rooms for students, a kitchen, latrines and a stable as service buildings, and above the entrance façade rises a minaret with a Mamluk-style top. The whole complex is an architectural masterpiece in its structural and decorative elements, distinguished by naskhi inscriptions containing Qur'anic verses, the founder's name and the date of construction, as well as coloured marble revetments and the superbly decorated ceiling of the qibla iwan." },
    g("2022/10/img_4011.jpg"),
    g("2022/10/img_4012.jpg"),
    g("2022/10/img_4013.jpg"),
    g("2022/10/img_4014.jpg"),
    g("2022/10/img_4015.jpg"),
    g("2022/10/img_4016.jpg"),
    g("2022/10/img_4017.jpg"),
    g("2022/10/img_4018.jpg"),
    g("2022/10/img_4025.jpg"),
    g("2022/10/img_4024.jpg"),
    g("2022/10/img_4023.jpg"),
    g("2022/10/img_4022.jpg"),
    g("2022/10/img_4021.jpg"),
    g("2022/10/img_4020.jpg"),
    g("2022/10/img_4019.jpg"),
  ],
};

const alSaliba: Guide = {
  slug: "egypt-site-al-saliba",
  title_ar: "شارع الصليبة وتوابعه",
  title_en: "Al-Saliba Street and its surroundings",
  kicker_ar: "مواقع أثرية · القاهرة",
  kicker_en: "Archaeological sites · Cairo",
  image: U("2022/10/img_4083-1.jpg"),
  blocks: [
    { type: "H3", ar: "شارع الصليبة وتوابعه", en: "Al-Saliba Street and its surroundings", noNumber: true },
    { type: "P", ar: "يعد شارع الصليبة واحد من أقدم شوارع القاهرة الاسلامية الرئيسية في العصور الوسطى ، يمتد من ميدان القلعة (ميدان صلاح الدين ، المعروف أيضا باسم ميدان القلعة) وصولا الى ميدان السيدة زينب ، وقد أطلق على الشارع اسم الصليبة منذ حوالي 700 عام ، بسبب تقاطعه مع العديد من الشوارع الأخرى ، من القرن الرابع عشر الى منتصف القرن السادس عشر الميلادي كان شارع الصليبة مشغول بمؤسسات الدولة ومساكن أهم الأمراء في مصر", en: "Al-Saliba is one of the oldest main streets of medieval Islamic Cairo, running from the Citadel square (Salah al-Din Square, also known as Citadel Square) to Sayyida Zaynab Square. It has been called al-Saliba — 'the crossing' — for some 700 years because it intersects many other streets. From the fourteenth to the mid-sixteenth century it was occupied by state institutions and the residences of Egypt's most important emirs." },
    { type: "P", ar: "شهد هذا الشارع التاريخي على العديد من الأحداث السياسية والاجتماعية والتاريخية ، من مرور مواكب المحمل السلطاني ، الى احتفالات الدولة ، وحتى المؤامرات التي حاكها حكام المماليك ضد بعضهم البعض ، العديد من الأمراء على مر العصور في الصليبة وبنوا منشآت عسكرية ، بما في ذلك مدرسة عسكرية وورش لصناعة الأسلحة والبنادق", en: "This historic street witnessed many political, social and historical events, from the passing of the sultan's mahmal processions to state celebrations and even the plots the Mamluk rulers wove against one another. Many emirs lived on al-Saliba through the ages and built military establishments there, including a military school and workshops for making weapons and guns." },
    { type: "P", ar: "يحتوي الصليبة على مجموعة واسعة من المباني الاسلامية التي تعرض مجموعة متنوعة من الطرز المعمارية الغنية والمتنوعة من فترات مختلفة ، يمكن العثور على المساجد والمدارس والكتاب (مدارس تعليم القرآن) ، والأسبلة (صنابير المياه العامة) والخانقاوات (مواقع تجمع الصوفية) والحمامات القديمة والقصور ، الشارع بأكمله عبارة عن متحف في الهواء الطلق يعرض العصر الاسلامي بكل بهائه ، ومن أهم الآثار الموجودة بالشارع جامع أحمد بن طولون ، بيت الكريتلية ، وسبيل وكتاب أم عباس", en: "Al-Saliba contains a wide range of Islamic buildings displaying rich and varied architectural styles from different periods: mosques, madrasas, kuttabs (Qur'an schools), sabils (public fountains), khanqahs (Sufi gathering places), old bathhouses and palaces. The whole street is an open-air museum presenting the Islamic era in all its splendour, and among its most important monuments are the Mosque of Ahmad ibn Tulun, the Gayer-Anderson House (Bayt al-Kritliyya) and the Sabil-Kuttab of Umm Abbas." },
    g("2022/10/img_4083-2.jpg", "شارع الصليبة", "Al-Saliba Street"),
    g("2022/10/img_4084.jpg", "شارع الصليبة", "Al-Saliba Street"),
    { type: "H3", ar: "سبيل وكتاب ام عباس", en: "The Sabil-Kuttab of Umm Abbas" },
    { type: "P", ar: "يقع سبيل وكتاب أم عباس بالصليبة بمنطقة القلعة بالقاهرة ، وشيدته السيدة بنبه قادن بنت عبد الله البيضا عام 1284هـ / 1867م على روح ابنها والي مصر عباس حلمي الأول 1280–1296 هـ / 1863-1879م ، ابن عم الخديوي اسماعيل باشا", en: "The Sabil-Kuttab of Umm Abbas stands on al-Saliba in the Citadel district of Cairo. It was built by Lady Bamba Qadin, daughter of Abdullah al-Bayda, in 1284 AH / 1867 AD in memory of her son Abbas Hilmi I, governor of Egypt (1280–1296 AH / 1863–1879 AD) and cousin of Khedive Ismail Pasha." },
    { type: "P", ar: "يعد هذا السبيل من الأسبلة الرائعة في مدينة القاهرة في القرن التاسع عشر الميلادي ، وعادة ما كان يلحق بالسبيل كتاب أو مدرسة لتعليم الأطفال القرآن الكريم ، وقد شيد على مساحة شاسعة وزخرفت جدرانه بزخارف نباتية بديعة متقنة محفورة على الرخام متأثرة بفن الروكوكو الأوروبي ، كما يتميز بوجود كتابات باللغتين العربية والتركية ، وتنتهي احدى الأشرطة الكتابية باسم الخطاط عبد الله الزهدي النابلسي مقرونا بوظفيته", en: "It is one of the finest nineteenth-century sabils in Cairo. A sabil was usually attached to a kuttab or school where children were taught the Qur'an. Built over a vast area, its walls are decorated with exquisite plant motifs carved in marble, influenced by European Rococo, and it is notable for inscriptions in both Arabic and Turkish; one inscription band ends with the name of the calligrapher Abdullah al-Zuhdi al-Nabulsi together with his title." },
    g("2022/10/img_4082.jpg"),
    g("2022/10/img_4083.jpg"),
    g("2022/10/img_4084-1.jpg"),
    g("2022/10/img_4085.jpg"),
    g("2022/10/img_4086.jpg"),
    g("2022/10/img_4087.jpg"),
    g("2022/10/img_4088.jpg"),
    g("2022/10/img_4095.jpg"),
    g("2022/10/img_4094.jpg"),
    g("2022/10/img_4093.jpg"),
    g("2022/10/img_4092.jpg"),
    g("2022/10/img_4091.jpg"),
    g("2022/10/img_4090.jpg"),
    g("2022/10/img_4089.jpg"),
  ],
};

const salahAlDinSquare: Guide = {
  slug: "egypt-site-salah-al-din-square",
  title_ar: "ميدان صلاح الدين وتوابعه",
  title_en: "Salah al-Din Square and its surroundings",
  kicker_ar: "مواقع أثرية · القاهرة",
  kicker_en: "Archaeological sites · Cairo",
  image: U("2022/10/img_4037.jpg"),
  blocks: [
    { type: "H3", ar: "ميدان صلاح الدين وتوابعه", en: "Salah al-Din Square and its surroundings", noNumber: true },
    { type: "P", ar: "يعد ميدان قلعة صلاح الدين من أهم الميادين التاريخية بالقاهرة ، وقد عرف بعدة أسماء منها : الميدان الأسود ( قراميدان ) ، وميدان الرميلة ، وميدان سوق الخيل ، وهو يقع أسفل القلعة صلاح الدين", en: "The square below the Citadel of Saladin is one of Cairo's most important historic squares. It has been known by several names, among them the Black Square (Qaramaydan), al-Rumayla Square and the Horse Market Square, and it lies beneath the Citadel of Saladin." },
    { type: "P", ar: "تعطل اعماره على يد العديد من الملوك والسلاطين ، بينما كانت أزهى أيامه عندما أعاد الناصر محمد بن قلاوون عمارته حيث كان يلعب فيه لعبة الصولجان والكرة ( الجوكان أو البولو ) مع أمرائه ، كما استخدم في صلاة العيدين ، واستقبال مواكب السلاطين والرسل والسفراء ، والاحتفالات ، واستعراض الجيوش", en: "Its development stalled under many kings and sultans, while its most brilliant days came when al-Nasir Muhammad ibn Qalawun rebuilt it and played the mallet-and-ball game (jukan, or polo) there with his emirs. It was also used for the feast prayers, for receiving the processions of sultans, envoys and ambassadors, for celebrations and for military parades." },
    { type: "P", ar: "يطل عليه عدد من الآثار الاسلامية منها : قلعة صلاح الدين وتفتح على الشارع عن طريق باب العزب ، مسجد المحمودية ، مدرسة السلطان حسن ، جامع الرفاعي ، ويتفرع من هذا الميدان عدة شوارع مهمة مثل شارع سوق السلاح ، سكة المحجر ، الامام الشافعي وشارع الأقدام المؤدي الى مقابر السيدة نفيسة", en: "A number of Islamic monuments overlook it: the Citadel of Saladin, which opens onto the street through Bab al-Azab, the Mahmudiya Mosque, the Madrasa of Sultan Hasan and the Mosque of al-Rifai. Several important streets branch off the square, such as Suq al-Silah Street, Sikkat al-Mahjar, al-Imam al-Shafi'i and the Street of Feet leading to the tombs of Sayyida Nafisa." },
    g("2022/10/img_4037-1.jpg", "ميدان صلاح الدين", "Salah al-Din Square"),
    g("2022/10/img_4038.jpg", "ميدان صلاح الدين", "Salah al-Din Square"),
    { type: "H3", ar: "منزل علي لبيب", en: "The House of Ali Labib" },
    { type: "P", ar: "يقع المنزل بحارة درب اللبانة بمنطقة الخليفة ، ويعتبر واحدا من أفضل المباني الباقية من منازل القرن الثامن عشر الميلادي ، يعرف باسم بيت الفنانين ، حيث سكن به العديد من الفنانين مثل راغب عياد وشادي عبد السلام", en: "The house stands in the alley of Darb al-Labbana in the Khalifa district and is one of the finest surviving eighteenth-century houses. It is known as the Artists' House because many artists lived in it, such as Ragheb Ayad and Shadi Abdel Salam." },
    { type: "P", ar: "أنشأه عمر الملاطيلي وشقيقه إبراهيم في أواخر القرن الثاني عشر الهجري / الثامن عشر الميلادي ، لكنه عرف لاحقا باسم علي لبيب", en: "It was built by Umar al-Malatili and his brother Ibrahim in the late twelfth century AH / eighteenth century AD, but later became known by the name of Ali Labib." },
    { type: "P", ar: "يمثل هذا المنزل واحدا من أنماط المساكن في العصر العثماني التي اتبعت تقاليد العمارة المملوكية ، وتعرض حجرات المنزل مقتنيات رواده مثل رمسيس ويصا واصف ، والمعماري العالمي حسن فتحي ، وتزين القاعات العلوية لوحات تصور المباني والحدائق في القاهرة ، ويطل سطح المنزل على مشهد رائع لمعظم معالم القاهرة التاريخية", en: "The house represents one of the Ottoman-era housing types that followed Mamluk architectural traditions. Its rooms display belongings of those who frequented it, such as Ramses Wissa Wassef and the world-renowned architect Hassan Fathy, while the upper halls are decorated with paintings depicting the buildings and gardens of Cairo, and the roof offers a magnificent view over most of the city's historic landmarks." },
    { type: "P", ar: "تم اهمال المنزل في نهاية القرن العشرين حتى تم تجديده وتحويله الى متحف وبيت للمعمار المصري في مطلع القرن الحادي والعشرين", en: "The house was neglected at the end of the twentieth century until it was renovated and turned into a museum and a house of Egyptian architecture at the beginning of the twenty-first century." },
    g("2022/10/img_4039.jpg"),
    g("2022/10/img_4040.jpg"),
    g("2022/10/img_4041.jpg"),
    g("2022/10/img_4042.jpg"),
    g("2022/10/img_4043.jpg"),
    g("2022/10/img_4044.jpg"),
    g("2022/10/img_4045.jpg"),
    g("2022/10/img_4052.jpg"),
    g("2022/10/img_4051.jpg"),
    g("2022/10/img_4050.jpg"),
    g("2022/10/img_4049.jpg"),
    g("2022/10/img_4048.jpg"),
    g("2022/10/img_4047.jpg"),
    g("2022/10/img_4046.jpg"),
    g("2022/10/img_4057.jpg"),
    { type: "H3", ar: "جامع الرفاعي", en: "The Mosque of al-Rifai" },
    { type: "P", ar: "يقع جامع الرفاعي بميدان صلاح الدين ( ميدان القلعة ) ، تم انشائه في القرن التاسع عشر ليضاهي جاره الذي تم بناؤه في القرن الرابع عشر الميلادي جامع السلطان حسن المملوكي ، سمي الجامع بهذا الاسم نسبة الى الشيخ علي المعروف بأبو شباك حفيد الامام أحمد الرفاعي ، ثم نسب الجامع بعد انشاءه الى الامام أحمد الرفاعي نفسه صاحب الطريقة الرفاعية احدى الطرق الصوفية ، وعلى الرغم من أن الامام أحمد الرفاعي لم يدفن بذاك المسجد الا أنه يشهد الاحتفال بمولده سنويا في مشهد مليئا بأجواء الفرحة والسعادة", en: "The Mosque of al-Rifai stands on Salah al-Din Square (Citadel Square) and was built in the nineteenth century to rival its fourteenth-century Mamluk neighbour, the Mosque of Sultan Hasan. It is named after Sheikh Ali, known as Abu Shubbak, grandson of Imam Ahmad al-Rifai, and after its construction was attributed to Imam Ahmad al-Rifai himself, founder of the Rifai Sufi order. Although the imam is not buried in the mosque, his birthday is celebrated there every year in scenes full of joy." },
    { type: "P", ar: "كان يوجد بنفس موقع المسجد قديما مسجدا من العصر الفاطمي يسمى ذخيرة الملك ، ثم تحول الى مقام للشيخ علي أبو شباك ، الى أن اشترت خوشيار هانم والدة الخديوي اسماعيل الأماكن المحيطة به وأوكلت الى المهندس حسين باشا فهمي انشاء الجامع عام 1286هـ / 1869م وأن يلحق به مدافن للأسرة العلوية ، واستوردت مواد البناء من أوروبا مثل الرخام الايطالي ، تعرض بناء الجامع للتوقف حتى اكتمل بناءه وافتتحه الخديوي عباس حلمي الثاني عام 1330هـ / 1912م", en: "On the same site there once stood a Fatimid mosque called Dhakhirat al-Malik, which became a shrine for Sheikh Ali Abu Shubbak until Khushyar Hanim, mother of Khedive Ismail, bought the surrounding properties and commissioned the engineer Husayn Pasha Fahmy to build the mosque in 1286 AH / 1869 AD, with tombs for the Alawiyya royal family attached. Building materials such as Italian marble were imported from Europe; construction was interrupted until the mosque was completed and opened by Khedive Abbas Hilmi II in 1330 AH / 1912 AD." },
    { type: "P", ar: "ويتميز المسجد بتصميمه المعماري المميز ، حيث يذهل كل من يزور المسجد لدقة تفاصيل الزخارف بالحوائط الخارجية والأعمدة العملاقة عند البوابة الخارجية ، وقد امتازت مئذنتا المسجد بالرشاقة والجمال ، ومن الجدير بالذكر أن هذا الجامع يعد أول المبانى التي أستخدمت مادة الأسمنت في بنائها في تاريخ العمارة الاسلامية بمصر وكان ذلك مؤشرا للانتقال الى العصر الحديث", en: "The mosque is distinguished by its remarkable architecture: every visitor is astonished by the precision of the decoration on the outer walls and the giant columns at the outer gate, and its two minarets are slender and beautiful. Notably, it was the first building in the history of Islamic architecture in Egypt to use cement in its construction, marking the transition to the modern age." },
    { type: "P", ar: "خصص جزء من المسجد للصلاة ، والجزء الآخر للمقابر الملكية الخاصة بأسرة محمد علي ، حيث دفن بها الخديوي اسماعيل ووالدته خوشيار قادن والملك فؤاد الأول والملك فاروق الأول في أضرحة منفصلة ، كما يضم أيضا مدفن محمد رضا بهلوي آخر شاه لايران والمتوفي عام 1400هـ / 1980م", en: "Part of the mosque is devoted to prayer and the other part to the royal tombs of the family of Muhammad Ali, where Khedive Ismail, his mother Khushyar Qadin, King Fuad I and King Farouk I are buried in separate mausoleums. It also contains the tomb of Mohammad Reza Pahlavi, the last Shah of Iran, who died in 1400 AH / 1980 AD." },
    g("2022/10/img_4054.jpg"),
    g("2022/10/img_4055.jpg"),
    g("2022/10/img_4056.jpg"),
    g("2022/10/img_4057-1.jpg"),
    g("2022/10/img_4058.jpg"),
    g("2022/10/img_4059.jpg"),
    g("2022/10/img_4060.jpg"),
    g("2022/10/img_4066.jpg"),
    g("2022/10/img_4067.jpg"),
    g("2022/10/img_4065.jpg"),
    g("2022/10/img_4064.jpg"),
    g("2022/10/img_4063.jpg"),
    g("2022/10/img_4062.jpg"),
    g("2022/10/img_4061.jpg"),
    g("2022/10/img_4079.jpg"),
    { type: "H3", ar: "مسجد ومدرسة السلطان حسن", en: "The Mosque and Madrasa of Sultan Hasan" },
    { type: "P", ar: "يعتبر مسجد ومدرسة السلطان حسن من أضخم مساجد مصر عمارة وأعلاها بنيانا ، حيث أنشأهم السلطان حسن بن الناصر محمد بن قلاوون في الفترة ما بين عامي 757هـ / 1356م و764هـ / 1362م ، وتقع هذه المدرسة في نهاية شارع محمد علي أمام جامع الرفاعي بميدان صلاح الدين", en: "The Mosque and Madrasa of Sultan Hasan is among the largest and tallest mosques in Egypt, built by Sultan Hasan ibn al-Nasir Muhammad ibn Qalawun between 757 AH / 1356 AD and 764 AH / 1362 AD. It stands at the end of Muhammad Ali Street, facing the Mosque of al-Rifai on Salah al-Din Square." },
    { type: "P", ar: "يتكون المسجد من صحن ( فناء ) أوسط مكشوف يتوسطه فوارة ، ويحيط به أربعة ايوانات مساحة مربعة أو مستطيلة مغلقة من ثلاثة أضلاع ومفتوح ضلعها الرابع بالكامل ، وفي زوايا الصحن الأربعة يوجد أربعة أبواب توصل الى المدارس الأربعة التي خصصت لتدريس المذاهب الفقهية الأربعة ، كل منها يتكون من صحن وايوان الى جانب خلاوي سكنية للطلبة ، بالاضافة الى ملحقات خدمية ومئذنتين", en: "The mosque consists of an open central courtyard with a fountain at its centre, surrounded by four iwans — square or rectangular spaces closed on three sides and entirely open on the fourth. In the four corners of the courtyard, four doors lead to the four madrasas dedicated to teaching the four schools of jurisprudence, each with its own courtyard and iwan alongside cells for students, plus service annexes and two minarets." },
    { type: "P", ar: "وقد استخدم مسجد السلطان حسن كحصن نظرا لقربة من القلعة ، اذ كانت تطلق من فوق سطحه المجانق على القلعة عندما تثور الفتن بين أمراء المماليك البرجي ، تعرض المسجد للعديد من عمليات الترميم واعادة البناء على مر العصور حتى القرن العشرين كمعظم المعالم الاسلامية في القاهرة ، وأهم ما يميز المسجد القباب ذو الزخارف الرائعة والتصميم المعماري المميز", en: "Because of its closeness to the Citadel, the Mosque of Sultan Hasan was used as a fortress: catapults were fired at the Citadel from its roof whenever strife broke out among the Burji Mamluk emirs. Like most Islamic monuments in Cairo, it underwent many restorations and rebuildings through the ages up to the twentieth century, and its most distinctive features are its superbly decorated domes and remarkable architectural design." },
    { type: "P", ar: "كما يتميز أيضا بجمال ودقة الزخارف الحجرية والجصية خاصة في الأشرطة الكتابية المنفذة بالخط الكوفي ، وكذلك الأعمال الرخامية وجمال الزخارف بمحراب الايوان الرئيسي ومحراب القبة ، وكذلك مدخل المنبر الرخامي ذو التفاصيل الدقيقة ، ودكة المبلغ الرخامية ، وأخيرا دكة المقريء ذات الحشوات الهندسية المجمعة بأشكال الأطباق النجمية", en: "It is also distinguished by the beauty and precision of its stone and stucco decoration, especially the inscription bands executed in Kufic script, as well as its marblework and the beautiful ornament of the mihrab of the main iwan and the mihrab of the dome, the finely detailed marble pulpit entrance, the marble muezzin's platform and finally the reciter's platform with its assembled geometric panels in star-plate patterns." },
    g("2022/10/img_4068.jpg"),
    g("2022/10/img_4069.jpg"),
    g("2022/10/img_4070.jpg"),
    g("2022/10/img_4071.jpg"),
    g("2022/10/img_4072.jpg"),
    g("2022/10/img_4079-1.jpg"),
    g("2022/10/img_4078.jpg"),
    g("2022/10/img_4077.jpg"),
    g("2022/10/img_4076.jpg"),
    g("2022/10/img_4075.jpg"),
    g("2022/10/img_4074.jpg"),
    g("2022/10/img_4073.jpg"),
  ],
};

const senusretObelisk: Guide = {
  slug: "egypt-site-senusret-obelisk",
  title_ar: "مسلة سنوسرت الأول",
  title_en: "The Obelisk of Senusret I",
  kicker_ar: "مواقع أثرية · القاهرة",
  kicker_en: "Archaeological sites · Cairo",
  image: U("2022/10/img_4145.jpg"),
  blocks: [
    { type: "H3", ar: "مسلة سنوسرت الأول بعين شمس", en: "The Obelisk of Senusret I at Ain Shams", noNumber: true },
    { type: "P", ar: "أقيمت مدينة عين شمس على أطلال مدينة ايونو الفرعونية القديمة ، أقدم عواصم العالم ، وسميت كذلك أون ، ذات العماد حيث كان يوجد بها عدد لافت من الأعمدة والمسلات الكبيرة ، وأطلق عليها اليونانيون اسم هليوبوليس ، فهيليوس (الشمس) وبوليس (المدينة) ، أى مدينة الشمس أو مدينة النور ، وذلك لأن مدينة أون كانت تشتهر بعبادة الشمس نسبة الى الاله رع اله الشمس ، ويقابله الرب هيليوس لدى اليونان", en: "The town of Ain Shams was built on the ruins of the ancient Egyptian city of Iunu, one of the oldest capitals in the world, also called On, 'the pillared', because it held a striking number of large columns and obelisks. The Greeks named it Heliopolis — helios (sun) and polis (city), the City of the Sun or City of Light — because On was famous for the worship of the sun in honour of the god Ra, whose Greek counterpart was Helios." },
    { type: "P", ar: "لم يبق من المدينة القديمة أو معابدها الا نذر يسير من المعالم ، وخلال الحقب الاسلامية ، استعان المصريون بحجارتها في بناء منازلهم ومنافعهم الأخرى ، ولا تزال أعمال البعثات الأثرية جارية في المنطقة حتى اليوم ، وهناك مقابر تعود الى الدولة القديمة ، وخاصة مقبرتي بانحسي وخنسو عنخ ، ولا يستبعد أن يكون معبد المدينة ، الذي لم يعد قائما اليوم ، مماثلا في ضخامته وأهميته لمعبد الكرنك في الأقصر ، وقد كان كهنته مسئولون عن تسجيل التقويم المصري الشمسي ، فهم من وضع أساس التقويم بالسنة المصرية القديمة", en: "Only scant traces remain of the ancient city and its temples; during the Islamic periods Egyptians used its stones to build their houses and other structures. Archaeological missions are still working in the area today, and there are tombs dating to the Old Kingdom, notably those of Panehsy and Khonsu-ankh. It is quite possible that the city's temple, no longer standing, matched Karnak in Luxor in scale and importance; its priests were responsible for recording the Egyptian solar calendar and laid the foundation of the ancient Egyptian year." },
    { type: "P", ar: "وما تزال مسلة سنوسرت الأول ، التي يعود تاريخها الى الأسرة الثانية عشرة 1956-1911 (ق. م) قائمة في موقعها ، والمسلات تجسيد بالحجر لخيوط أشعة الشمس ، ورمز بها المصري القديم لاله الشمس ، وقد نقل الاغريق والرومان العديد من المسلات من معابدها الأصلية ، واكتشفنا تفكيك عمود من الجرانيت والحجر الرملي أقامه الملك مرنبتاح 1213-1203 (ق م) ، وجرى نقله واعادة بنائه وعرضه في المتحف المصري الكبير", en: "The Obelisk of Senusret I, dating to the Twelfth Dynasty (1956–1911 BC), still stands in its place. Obelisks are the sun's rays embodied in stone, the ancient Egyptian symbol of the sun god. The Greeks and Romans moved many obelisks from their original temples, and a granite and sandstone column erected by King Merneptah (1213–1203 BC) was dismantled, moved, rebuilt and displayed in the Grand Egyptian Museum." },
    { type: "P", ar: "وعرف العالم مكانة أون الدينية والسياسية المؤثرة في مصر الفرعونية بعد العثور على العديد من النصوص ذات الصلة بالديانة التي كانت مزدهرة بها ، وارتبط رع اله الشمس بواحدة من أقدم نظريات الخلق لدى المصريين ، ولدت تلك النظرية في مدرسة مدينة أون ، وعرفت بنظرية التاسوع (أي تشمل تسعة آلهة) ، ومفادها أن العالم قبل وجود الأرباب كان عبارة عن محيط أزلي لا نهائي من المياه نون ، ومن هذا المحيط ظهرت روح الاله آتوم (رع) اله الشمس فى صورته الكاملة ، وكان يستقر على تل فوق تلك المياه ، وعندما استشعر الوحدة قام بخلق رفقاء آخرين ليخرج اله الهواء شو والرطوبة تفنوت ، اللذان تزوجا وأنجبا اله الأرض جب والهة السماء نوت اللذان بدورهما تزوجا وأنجبا أوزير وايزيس وست ونفتيس ، ومن ثم توالى الخلق", en: "The world came to know the influential religious and political standing of On in pharaonic Egypt after many texts were found relating to the religion that flourished there. Ra, the sun god, was linked to one of the oldest Egyptian creation theories, born in the school of On and known as the Ennead (nine gods): before the gods existed, the world was an infinite primordial ocean of water, Nun, out of which the spirit of the god Atum (Ra), the sun god, appeared in his complete form, resting on a mound above those waters. Feeling alone, he created other companions, bringing forth Shu, god of air, and Tefnut, goddess of moisture, who married and bore Geb, god of the earth, and Nut, goddess of the sky, who in turn married and bore Osiris, Isis, Seth and Nephthys — and so creation continued." },
    { type: "IMG", src: U("2022/10/img_4145-1.jpg"), cap_ar: "مسلة سنوسرت الأول", cap_en: "The Obelisk of Senusret I" },
  ],
};

const alSuyufiyya: Guide = {
  slug: "egypt-site-al-suyufiyya",
  title_ar: "شارع السيوفية وتوابعه",
  title_en: "Al-Suyufiyya Street and its surroundings",
  kicker_ar: "مواقع أثرية · القاهرة",
  kicker_en: "Archaeological sites · Cairo",
  image: U("2022/10/img_4128.jpg"),
  blocks: [
    { type: "H3", ar: "شارع السيوفية وتوابعه", en: "Al-Suyufiyya Street and its surroundings", noNumber: true },
    { type: "P", ar: "يعد من الشوارع المهمة بمصر الاسلامية فهو جزء من الشارع الأعظم الذي يبدأ من تقاطع شارع محمد علي وينتهي عند تقاطعه مع شارع الصليبة", en: "This is one of the important streets of Islamic Egypt, part of the Great Street that begins at the junction with Muhammad Ali Street and ends where it meets al-Saliba Street." },
    { type: "P", ar: "يعكس هذا الشارع التطور التاريخي لهذه المنطقة ، حيث أن بداية نشأته كانت جزء من مدينة القطائع ، وشهد عمرانا ملموسا بالعصر الفاطمي ، وكان في العصر الأيوبي محاطا بالبساتين ويطل على بركة كبيرة يطلق عليها بركة الفيل ، وكان لتشييد قلعة صلاح الدين سنة 572هـ / 1176م أثرا كبيرا في امتداد العمران الى تلك المنطقة ، وأصبح الشارع بعد ذلك في العصر المملوكي سكنا لأفراد الطبقة الحاكمة وصفوة المماليك ، واستمر الوضع هكذا في العصر العثماني وعصر أسرة محمد علي ، ويضم شارع السيوفية مجموعة من الآثار الاسلامية بأنماطها (أنواعها) المختلفة من قصور ومساجد وتكايا وقباب ضريحية ، وأسبلة والتي ترجع الى عصور مختلفة", en: "The street reflects the historical development of the area: it began as part of the city of al-Qata'i, saw considerable building in the Fatimid era, and in the Ayyubid era was surrounded by orchards overlooking a large pond called Birkat al-Fil. The construction of the Citadel of Saladin in 572 AH / 1176 AD had a great effect in extending building into the area, and in the Mamluk era the street became the residence of the ruling class and the elite of the Mamluks, as it remained in the Ottoman era and the era of the family of Muhammad Ali. Al-Suyufiyya contains a range of Islamic monuments of different types — palaces, mosques, takiyyas, mausoleum domes and sabils — dating from various periods." },
    g("2022/10/img_4128-1.jpg", "شارع السيوفية", "Al-Suyufiyya Street"),
    g("2022/10/img_4134-1.jpg", "شارع السيوفية", "Al-Suyufiyya Street"),
    { type: "H3", ar: "التكية المولوية ومدرسة سنقر السعدى", en: "The Mawlawi Takiyya and the Madrasa of Sunqur al-Sa'di" },
    { type: "P", ar: "كانت التكية المولوية في الأصل مدرسة ، أنشأها الأمير شمس الدين سنقر السعدي في عام 721هـ / 1321م وتقع بشارع السيوفية ، عرفت بعد ذلك بقبة حسن صدقة الشرابيشي في عام 745هـ / 1344م ، والمدرسة عبارة عن صحن مكشوف لم يتبق منه سوى فسقية مياه (نافورة) ، وعلى جانبيه بقايا غرف صغيرة للطلبة", en: "The Mawlawi Takiyya was originally a madrasa, founded by Amir Shams al-Din Sunqur al-Sa'di in 721 AH / 1321 AD on al-Suyufiyya Street, and later known as the Dome of Hasan Sadaqa al-Sharabishi in 745 AH / 1344 AD. The madrasa is an open courtyard of which only a water basin (fountain) survives, with the remains of small student rooms on either side." },
    { type: "H3", ar: "التكية المولوية", en: "The Mawlawi Takiyya" },
    { type: "P", ar: "أنشئت سنة 1005 هـ / 1595م واستخدمت كسكن للفقراء ، وتميزت واجهه التكية بأنها تجمع بين الطرازين المملوكي والعثماني ، وقد حلت الطريقة المولوية الصوفية بهذه المدرسة في القرن السابع عشر الميلادي ثم انتقلت الى مكان آخر ، وأهم ما يميز التكية هي القبة المقامة على اثني عشر عمودا خشبيا ، وزعت حجرات التكية على طابقين : الأرضي به ثماني غرف بأسقف خشبية ، والأول به ثماني غرف مختلفة في المساحات والأغراض", en: "Founded in 1005 AH / 1595 AD and used as lodging for the poor, the takiyya's façade combines Mamluk and Ottoman styles. The Mawlawi Sufi order settled in this madrasa in the seventeenth century and later moved elsewhere. Its most distinctive feature is the dome raised on twelve wooden columns. Its rooms are spread over two floors: the ground floor has eight rooms with wooden ceilings, and the first floor eight rooms of differing sizes and purposes." },
    { type: "H3", ar: "السمع خانة أو مسرح الدراويش", en: "The Sama' Khana, or theatre of the dervishes" },
    { type: "P", ar: "بني مسرح الدراويش في عام 1255هـ / 1810م وكان مخصص لاقامة حلقات الذكر الخاصة بأتباع الطريقة المولوية ، وهو يتكون من منصة خشبية مستديرة بها دائرة بلون مختلف ويحيطها درابزين خشبي له بابان ، أما الطابق الثاني فهو مكون من سلم خشبي ومساحات غير منتظمة للجمهور ومكان للنساء", en: "The dervishes' theatre was built in 1255 AH / 1810 AD for the dhikr circles of the followers of the Mawlawi order. It consists of a round wooden platform with a circle in a different colour, surrounded by a wooden balustrade with two doors, while the upper floor has a wooden staircase, irregular spaces for the audience and an area for women." },
    g("2022/10/img_4129.jpg"),
    g("2022/10/img_4130.jpg"),
    g("2022/10/img_4131.jpg"),
    g("2022/10/img_4132.jpg"),
    g("2022/10/img_4133.jpg"),
    g("2022/10/img_4134.jpg"),
    g("2022/10/img_4135.jpg"),
    g("2022/10/img_4136.jpg"),
    g("2022/10/img_4137-1.jpg"),
    { type: "H3", ar: "قصر الأمير طاز", en: "The Palace of Amir Taz" },
    { type: "P", ar: "يقع هذا القصر بشارع السيوفية بحي الخليفة ، أنشأه الأمير سيف الدين طاز دوادار السلطان الصالح بن الناصر محمد بن قلاوون ونائب حلب وذلك في عام 753هـ / 1352م", en: "This palace stands on al-Suyufiyya Street in the Khalifa district, built in 753 AH / 1352 AD by Amir Sayf al-Din Taz, secretary to Sultan al-Salih ibn al-Nasir Muhammad ibn Qalawun and deputy of Aleppo." },
    { type: "P", ar: "يعد من أروع وأجمل نماذج القصور في عصر دولة المماليك البحرية وأكبرها في المساحة ، وأهم ما يميز القصر المقعد المطل على الفناء الداخلي الكبير ، ببائكته المكونة من أربعة عقود مدببه ترتكز على ثلاث أعمدة رخامية ، وقاعاته الفريدة ذات الزخارف الجميلة", en: "It is one of the finest and most beautiful examples of palaces from the Bahri Mamluk period and the largest in area. Its most striking feature is the loggia overlooking the great inner courtyard, with an arcade of four pointed arches resting on three marble columns, and its unique halls with their beautiful decoration." },
    { type: "P", ar: "زخرفت الأسقف بزخارف هندسية ونباتية ، والجدران بأشرطة كتابية تحمل ألقاب الأمير ويتخللها جامات مستديرة عليها رنك الكأس الذي يرمز لوظيفة الساقي احدى الوظائف التي تقلدها الأمير ، يزخرف أحد القاعات الملحقة بالمقعد شريط كتابي عبارة عن بحور تحمل كتابات بالخط الفارسي من بردة البوصيري (مدح للرسول محمد صلى الله عليه وسلم) باللون الأبيض", en: "The ceilings are decorated with geometric and plant motifs, and the walls with inscription bands carrying the amir's titles, interspersed with round medallions bearing the cup blazon that symbolises the office of cupbearer, one of the posts the amir held. One of the halls attached to the loggia is decorated with an inscription band of verses in Persian script, in white, from al-Busiri's Burda in praise of the Prophet Muhammad." },
    { type: "IMG", src: U("2022/10/img_4137.jpg"), cap_ar: "قصر الأمير طاز", cap_en: "The Palace of Amir Taz" },
  ],
};

const amadaTemples: Guide = {
  slug: "egypt-site-amada-temples",
  title_ar: "معابد عمدا وتوابعها",
  title_en: "The Amada Temples and their surroundings",
  kicker_ar: "مواقع أثرية · أسوان",
  kicker_en: "Archaeological sites · Aswan",
  image: U("2022/10/img_4028.jpg"),
  blocks: [
    { type: "H3", ar: "معابد عمدا وتوابعها", en: "The Amada Temples and their surroundings", noNumber: true },
    { type: "P", ar: "يقع حاليا كلا من معبد عمدا ومعبد الدر ومقبرة بنوت في موقع عمدا الجديدة ، التي تقع على بعد حوالي 160 كم جنوب أسوان ، وخشية من تعرضهم لخطر الغمر الدائم تحت مياه النيل مع بناء السد العالي في أسوان في الستينيات ، ونظرا لقيمتهم التاريخية الهائلة ، فقد تم انقاذ هذه الآثار القديمة من خلال مشروع اليونسكو لانقاذ المعالم الأثرية في النوبة ، فقد تم تفكيكهم ونقلهم من مواقعهم الأصلية الى موقعهم الجديد في عمدا الجديدة ، على بعد بضعة كيلومترات فقط ، وفي عام 1979م ، تم ادراج هذه المعالم الجميلة في قائمة التراث العالمي لليونسكو", en: "The Temple of Amada, the Temple of al-Derr and the Tomb of Pennut now all stand at the New Amada site, about 160 km south of Aswan. Fearing they would be permanently submerged beneath the Nile once the Aswan High Dam was built in the 1960s, and given their immense historical value, these ancient monuments were saved through the UNESCO project to rescue the monuments of Nubia: they were dismantled and moved from their original locations to their new site at New Amada, only a few kilometres away. In 1979 these beautiful monuments were inscribed on the UNESCO World Heritage list." },
    g("2022/10/img_4028-1.jpg", "موقع عمدا الجديدة", "The New Amada site"),
    g("2022/10/img_4029.jpg", "موقع عمدا الجديدة", "The New Amada site"),
    { type: "H3", ar: "معبد عمدا", en: "The Temple of Amada" },
    { type: "P", ar: "تم بناء معبد عمدا في عصر الأسرة الثامنة عشر حوالي 1550-1295( ق.م) خلال عصر الدولة الحديثة ، ويعد أحد أقدم المعالم الأثرية المصرية القديمة الواقعة على طول ضفاف بحيرة ناصر ، تم الحفاظ على نصوص ونقوش المعبد بحالة جيدة لأنها كانت مغطاة بطبقة من الجص عندما تم تحويله الى هيكل كنائسى", en: "The Temple of Amada was built in the Eighteenth Dynasty, around 1550–1295 BC, during the New Kingdom, and is one of the oldest ancient Egyptian monuments along the shores of Lake Nasser. Its texts and reliefs are well preserved because they were covered with a layer of plaster when it was converted into a church." },
    { type: "P", ar: "تعاقب ثلاثة أجيال من الملوك على بناء هذا المعبد الجميل ، فقد قام كلا من الملك المحارب الفاتح العظيم تحتمس الثالث حوالي 1479-1425 (ق.م) وابنه أمنحتب الثاني حوالي 1427-1400 (ق.م) ببناء الجزء الأساسي من المعبد ، وأضاف تحتمس الرابع حوالي 1400-1390 (ق.م) قاعة الأعمدة المهيبة ، بعض الاضافات والتعديلات تمت خلال الأسرة 19 حوالي 1295-1186 (ق.م)", en: "Three generations of kings worked on this beautiful temple: the great warrior-conqueror Thutmose III (c. 1479–1425 BC) and his son Amenhotep II (c. 1427–1400 BC) built the core of the temple, Thutmose IV (c. 1400–1390 BC) added the imposing hypostyle hall, and further additions and alterations were made during the Nineteenth Dynasty (c. 1295–1186 BC)." },
    { type: "P", ar: "تظهر نقوش المعبد الملك وهو يقوم بأداء طقوس المعبد وبصحبته مجموعة متنوعة من المعبودات ، كان المعبد مكرسا لكل من المعبودين آمون رع ورع حورآختي ، وغالبا ما كان الملك يصور وهو يدخل أو يقاد الى أحد هذين المعبودين ، تحتوي جدران المعبد على نصوص أخرى هامة ، مثل النقش الموجود أسفل الجزء الأيسر من مدخل المعبد الذي يوضح المآثر العسكرية للملك مرنبتاح من الأسرة التاسعة عشر حوالي 1213-1203 (ق.م) بينما سجل أمنحتب الثاني حملته العسكرية الناجحة الى بلاد الشام على الجدار الخلفي لقدس الأقداس", en: "The temple's reliefs show the king performing the temple rituals accompanied by a variety of deities. The temple was dedicated to Amun-Ra and Ra-Horakhty, and the king is often depicted entering or being led to one of these two gods. Its walls carry other important texts, such as the inscription below the left part of the entrance recording the military feats of King Merneptah of the Nineteenth Dynasty (c. 1213–1203 BC), while Amenhotep II recorded his successful campaign in the Levant on the rear wall of the sanctuary." },
    { type: "P", ar: "مع بناء السد العالي في أسوان في الستينيات ، كان معبد عمدا مهددا بخطر الاندثار بسبب ارتفاع منسوب مياه بحيرة ناصر ، ولحسن الحظ ، كان من الممكن اعادة بناء هذا المعبد ، هنا في الموقع الحالي على بعد 2.5 كم من موقعه الأصلي", en: "With the building of the Aswan High Dam in the 1960s, the Temple of Amada was threatened with destruction by the rising waters of Lake Nasser. Fortunately it proved possible to rebuild the temple here at its present site, 2.5 km from its original location." },
    g("2022/10/img_4032.jpg"),
    g("2022/10/img_4031.jpg"),
    g("2022/10/img_4030.jpg"),
    g("2022/10/img_4029-1.jpg"),
    g("2022/10/img_4035.jpg"),
    { type: "H3", ar: "معبد الدر", en: "The Temple of al-Derr" },
    { type: "P", ar: "تم نحت هذا المعبد في الصخر بتكليف من الملك رمسيس الثاني حوالي 1279- 1213 (ق.م) كان اسمه المصري القديم معبد رمسيس محبوب أمون في بيت رع ، ويتكون بشكل أساسي من قاعتين ذات أعمدة وينتهي بقدس الأقداس ، وبه العديد من السمات المشابهة المثيرة للاهتمام مع أشهر معابد رمسيس الثاني المنحوتة في الصخر ، مثل المعبد الكبير لأبي سمبل ، هنا أيضا في معبد الدر يمكن رؤية تماثيل نفس المعبودات الأربعة في قدس الأقداس ، مقطوعة في الصخر بتاح ، رع حورآختي ، رمسيس الثاني المؤله ، وآمون رع", en: "This temple was cut into the rock by order of King Ramesses II (c. 1279–1213 BC); its ancient Egyptian name was 'the Temple of Ramesses, Beloved of Amun, in the House of Ra'. It consists mainly of two columned halls ending in the sanctuary, and shares many intriguing features with the most famous of Ramesses II's rock-cut temples, the Great Temple of Abu Simbel. Here too, in al-Derr, statues of the same four deities can be seen in the sanctuary, cut from the rock: Ptah, Ra-Horakhty, the deified Ramesses II and Amun-Ra." },
    { type: "P", ar: "على الرغم من أن بعض المناظر في قاعة الأعمدة الأولى تصور بعض الحملات العسكرية لرمسيس الثاني ، الا أن معظم زخرفة جدران المعبد تظهره برفقة المعبودات ، وهو يؤدي طقوس تأسيس المعبد ، تظهر ألوان النقوش في قاعة الأعمدة الثانية محفوظة بشكل جيد للغاية", en: "Although some scenes in the first columned hall depict military campaigns of Ramesses II, most of the wall decoration shows him in the company of the gods, performing the rituals of the temple's foundation. The colours of the reliefs in the second columned hall are exceptionally well preserved." },
    { type: "P", ar: "في وقت لاحق تم تحويل المعبد الى كنيسة ، وفي عام 1964 ، تم تفكيكه ونقله من موقعه الأصلي في الدر على الجانب الآخر من النيل ، اليوم يقف بالقرب من معبد عمدا في الموقع الجديد ، بعد تنفيذ عملية انقاذ المعبد من الغرق نتيجة لبناء السد العالي في أسوان في الستينيات", en: "The temple was later converted into a church, and in 1964 it was dismantled and moved from its original site at al-Derr on the other side of the Nile. Today it stands close to the Temple of Amada at the new site, after being rescued from submersion caused by the building of the Aswan High Dam in the 1960s." },
    g("2022/10/img_4035-1.jpg"),
    g("2022/10/img_4036.jpg"),
    { type: "H3", ar: "مقبرة بنوت", en: "The Tomb of Pennut" },
    { type: "P", ar: "كان بنوت مسئولا مهما في عهد أحد ملوك الأسرة العشرين رمسيس السادس حوالي 1143 – 1136 (ق.م) ، على الرغم من أن مقبرته هنا حاليا في عمدا الجديدة ، الا أنها كانت تقع في الأصل على بعد 25 كم غربا في منطقة عنيبة ، وبسبب زخارفها الجميلة وقيمتها التاريخية العظيمة ، تم انقاذها من ارتفاع منسوب مياه بحيرة ناصر عام 1964م ، بصفته نائب الواوات الاسم المصري القديم للنوبة السفلى ، لعب بنوت دورا رئيسيا في النوبة ، كما كان مشرفا على معبد حورس بمنطقة عنيبة ، بينما كانت زوجته تاخا مغنية", en: "Pennut was an important official in the reign of Ramesses VI of the Twentieth Dynasty (c. 1143–1136 BC). Although his tomb now stands here at New Amada, it was originally 25 km to the west in the Aniba area; because of its beautiful decoration and great historical value it was rescued from the rising waters of Lake Nasser in 1964. As deputy of Wawat — the ancient Egyptian name for Lower Nubia — Pennut played a major role in Nubia and also oversaw the Temple of Horus at Aniba, while his wife Takha was a singer." },
    { type: "P", ar: "تعكس مقبرته الجميلة مكانته المهمة ، والتي يبرزها الجدار الشرقي ( على اليمين ) ، حيث تم تصوير الملك وهو شرف عظيم للغاية ، يظهر هذا المنظر الذي لم يتم الحفاظ عليه بشكل جيد للأسف ، فيظهر بنوت وهو يكافأ من قبل رمسيس السادس ( تم تدمير الشكل ) كما يظهر في النص المصاحب ، أنه كلف بنوت باقامة تمثال له ، وفي نقش آخر ورد ذكر معبد رمسيس الثاني في الدر", en: "His beautiful tomb reflects his important standing, highlighted by the eastern wall (on the right), where the king is depicted — a very great honour. This scene, unfortunately not well preserved, shows Pennut being rewarded by Ramesses VI (the figure has been destroyed), and the accompanying text shows that he commissioned Pennut to erect a statue of him; another inscription mentions the temple of Ramesses II at al-Derr." },
    { type: "P", ar: "في بقية مناظر المقبرة ، يمكن رؤية بنوت وهو يتقرب الى العديد من المعبودات ، وهناك العديد من المشاهد من كتاب الموتى ، وهدفهم هو التأكيد على أن بنوت وتاخا يعيشون حياة سعيدة في العالم الآخر ، نجد تجويف في وسط الجدار الشمالي يحتوي على ثلاثة تماثيل منحوتة في الصخر ، وسطها معبودة أنثى برأس بقرة", en: "In the remaining scenes Pennut can be seen making offerings to many deities, and there are numerous scenes from the Book of the Dead whose purpose is to affirm that Pennut and Takha live a happy life in the next world. In the middle of the northern wall is a niche containing three statues cut into the rock, the central one a goddess with a cow's head." },
    g("2022/10/img_4036-1.jpg"),
  ],
};

const wadiAlSebua: Guide = {
  slug: "egypt-site-wadi-al-sebua",
  title_ar: "معابد وادي السبوع",
  title_en: "The Wadi al-Sebua Temples",
  kicker_ar: "مواقع أثرية · أسوان",
  kicker_en: "Archaeological sites · Aswan",
  image: U("2022/10/img_4026.jpg"),
  blocks: [
    { type: "H3", ar: "معابد وادي السبوع", en: "The Wadi al-Sebua Temples", noNumber: true },
    { type: "P", ar: "أثمرت عملية نقل معابد النوبة ، بعد بناء السد العالي في أسوان في الستينيات من قبل الحكومة المصرية ، عن ظهور موقع وادي السبوع الجديد ، ويقع على بعد 4 كم فقط شمال غرب الموقع الأصلي لوادي السبوع ، وهو يضم العديد من المعابد التي كانت على وشك أن تغمر بمياه النيل ، كمعبد وادي السبوع من فترة الرعامسة ، المخصص لآمون رع ورع حور آختي ، والمعبد اليوناني الروماني في الدكة المكرس للمعبود جحوتي ، والمعبد الروماني بالمحرقة المخصص للمعبودين ايزيس وسيرابيس ، تم تسجيل كل هذه المعابد في مواقع التراث العالمي لليونسكو في عام 1979 كجزء من آثار النوبة", en: "The relocation of the Nubian temples by the Egyptian government after the building of the Aswan High Dam in the 1960s produced the new Wadi al-Sebua site, only 4 km north-west of the original one. It gathers several temples that were about to be flooded by the Nile: the Ramesside temple of Wadi al-Sebua dedicated to Amun-Ra and Ra-Horakhty, the Greco-Roman temple of al-Dakka dedicated to the god Thoth, and the Roman temple of al-Maharraqa dedicated to Isis and Serapis. All these temples were inscribed on the UNESCO World Heritage list in 1979 as part of the Nubian monuments." },
    { type: "IMG", src: U("2022/10/img_4026-1.jpg"), cap_ar: "معابد وادي السبوع", cap_en: "The Wadi al-Sebua Temples" },
  ],
};

const philae: Guide = {
  slug: "egypt-site-philae",
  title_ar: "آثار فيله",
  title_en: "The Philae Antiquities",
  kicker_ar: "مواقع أثرية · أسوان",
  kicker_en: "Archaeological sites · Aswan",
  image: U("2022/10/img_4126-1.jpg"),
  blocks: [
    { type: "H3", ar: "آثار فيله", en: "The Philae Antiquities", noNumber: true },
    { type: "P", ar: "تشمل آثار فيله العديد من المباني التي يعود تاريخها الى العصر البطلمي 332-30 (ق.م) ، وأبرزها ذلك المعبد الذى بدأه بطلميوس الثانى فيلادلفوس 285 – 246 (ق.م) ، والذى كان مكرسا لايزيس أم حورس ، وهناك منظر فى الماميزى أى حجرة الولادة ، حيث كان يتم الاحتفال بولادة حورس ، تظهر فيها ايزيس وهى ترضع ابنها حورس فى الأحراش", en: "The Philae antiquities include many buildings dating to the Ptolemaic period (332–30 BC), the most prominent being the temple begun by Ptolemy II Philadelphus (285–246 BC) and dedicated to Isis, mother of Horus. In the mammisi, the birth house where the birth of Horus was celebrated, there is a scene showing Isis suckling her son Horus in the marshes." },
    { type: "P", ar: "يعتبر معبد ايزيس واحدا من أكثر المعابد المصرية القديمة استمرارا ، حيث ظل المعبد يؤدى دوره حتى عهد الملك البيزنطي جستنيان 527 – 565م ، والذي أمر باغلاق كل المعابد الوثنية ، حيث نقش كاهن يدعى اسمت-اخوم آخر نص هيروغليفي ويرجع ذلك الى القرن الرابع الميلادي 394م ، تم تحويل المعبد الى كنيسة مسيحية وتم تدمير العديد من نقوش المعبد", en: "The Temple of Isis is one of the longest-lived of the ancient Egyptian temples: it continued to function until the reign of the Byzantine emperor Justinian (527–565 AD), who ordered all pagan temples closed. A priest named Esmet-Akhom carved the last hieroglyphic text there, dating to 394 AD in the fourth century. The temple was converted into a Christian church and many of its reliefs were destroyed." },
    { type: "P", ar: "يقع بجوار معبد ايزيس معبدا مكرس لحتحور بناه بطلميوس الرابع فيلوماتور 180 – 145 (ق.م) ، وأغسطس أول امبراطور لروما 30 ق.م – 14م ، ولا تزال مقصورة تراجان 98 – 117م ، المقامة أمام معبد فيله قائمة على الرغم من أن سقفها لم يعد موجودا ، وكان الترتيب المنتظم لأعمدتها الرائعة قد جذب أنظار الرحالة وقاموا بوصفه وتصويره ، كانت ايزيس المعبودة الرئيسية للمنطقة ، حيث تم تصوير الامبراطور يقدم القرابين لها ولزوجها أوزيريس وابنهما حورس", en: "Beside the Temple of Isis stands a temple dedicated to Hathor, built by Ptolemy IV Philometor (180–145 BC) and by Augustus, the first emperor of Rome (30 BC – 14 AD). The Kiosk of Trajan (98–117 AD), erected in front of the Philae temple, still stands although its roof is gone, and the regular arrangement of its superb columns caught the eye of travellers, who described and depicted it. Isis was the principal deity of the area, and the emperor is shown making offerings to her, to her husband Osiris and to their son Horus." },
    { type: "P", ar: "تم نقل كل هذه الآثار من جزيرة فيلة الأصلية الى جزيرة أجيلكيا القريبة خلال حملة اليونسكو للنوبة فى الستينات لانقاذ المواقع التي غمرتها مياه النيل فى عملية بناء السد العالي بأسوان", en: "All these monuments were moved from the original island of Philae to the nearby island of Agilkia during the UNESCO Nubia campaign of the 1960s, which rescued the sites flooded by the Nile during the building of the Aswan High Dam." },
    g("2022/10/img_4110.jpg"),
    g("2022/10/img_4111.jpg"),
    g("2022/10/img_4112.jpg"),
    g("2022/10/img_4119.jpg"),
    g("2022/10/img_4118.jpg"),
    g("2022/10/img_4117.jpg"),
    g("2022/10/img_4116.jpg"),
    g("2022/10/img_4115.jpg"),
    g("2022/10/img_4114.jpg"),
    g("2022/10/img_4113.jpg"),
    g("2022/10/img_4120.jpg"),
    g("2022/10/img_4121.jpg"),
    g("2022/10/img_4122.jpg"),
    g("2022/10/img_4123.jpg"),
    g("2022/10/img_4124.jpg"),
    g("2022/10/img_4125.jpg"),
    g("2022/10/img_4126.jpg"),
  ],
};

const abuSimbel: Guide = {
  slug: "egypt-site-abu-simbel",
  title_ar: "معبد أبو سمبل",
  title_en: "The Abu Simbel Temple",
  kicker_ar: "مواقع أثرية · أسوان",
  kicker_en: "Archaeological sites · Aswan",
  image: U("2022/10/img_4104-1.jpg"),
  blocks: [
    { type: "H3", ar: "معبد أبو سمبل", en: "The Abu Simbel Temple", noNumber: true },
    { type: "P", ar: "يعد معبد أبو سمبل الكبير ، الواقع في النوبة بالقرب من الحدود الجنوبية لمصر ، من بين المعالم الأكثر روعة في مصر ، قام الملك رمسيس الثاني من الأسرة التاسعة عشرة بقطعه كاملا في الجبل ، حوالي عام 1264 قبل الميلاد ، يشتهر المعبد بتماثيله الأربعة الضخمة جالسة والتى تزين واجهته ، والتي انهار أحدها بسبب زلزال قديم ولا تزال بقاياه على الأرض", en: "The Great Temple of Abu Simbel, in Nubia near Egypt's southern border, is among the most magnificent monuments in Egypt. King Ramesses II of the Nineteenth Dynasty cut it entirely from the mountain around 1264 BC. The temple is famous for the four colossal seated statues adorning its façade, one of which collapsed in an ancient earthquake, its remains still lying on the ground." },
    { type: "P", ar: "تقف تماثيل الملك الضخمة على جانبي الصالة الرئيسية المؤدية الى قدس الأقداس ، حيث تجلس أربعة آلهة : آمون رع ، ورع حورآختي ، وبتاح ، ورمسيس الثاني مؤلها ، وتم بناء المعبد بدقة عالية بحيث تدخل أشعة الشمس في المعبد يومين في السنة ، في 22 فبراير و 22 أكتوبر ، وتعبر الصالة الرئيسية ، وتضيء التماثيل الموجودة في عمق المعبد ، ويعتقد أن هذه التواريخ تتوافق مع تتويج وميلاد رمسيس الثاني", en: "Colossal statues of the king stand on either side of the main hall leading to the sanctuary, where four gods are seated: Amun-Ra, Ra-Horakhty, Ptah and the deified Ramesses II. The temple was built with such precision that on two days each year, 22 February and 22 October, the sun's rays enter the temple, cross the main hall and illuminate the statues deep inside. These dates are believed to correspond to the coronation and the birth of Ramesses II." },
    { type: "P", ar: "يقع الى الشمال معبدا آخر من الصخور معروف باسم المعبد الصغير ، مكرس للالهة حتحور والزوجة الملكية العظمى لرمسيس الثاني ، الملكة نفرتاري ، وعلى واجهة المعبد الصغير ، تقف تماثيلها الضخمة بنفس حجم تماثيل زوجها ، في مثال نادر جدا", en: "To the north lies another rock-cut temple known as the Small Temple, dedicated to the goddess Hathor and to the great royal wife of Ramesses II, Queen Nefertari. On its façade her colossal statues stand at the same size as those of her husband — a very rare example." },
    { type: "P", ar: "تم نقل المعبدين من موقعهما الأصلي في عام 1968 بعد بناء السد العالي بأسوان ، الذي هدد باغراقهما ، وتم الانتهاء من عملية النقل بفضل الجهود الدولية التي قادتها اليونسكو ، وتم قبول المعبد في قائمة مواقع التراث العالمي في عام 1979", en: "Both temples were moved from their original location in 1968 after the building of the Aswan High Dam, which threatened to submerge them. The relocation was completed thanks to international efforts led by UNESCO, and the temple was added to the World Heritage list in 1979." },
    g("2022/10/img_4097.jpg"),
    g("2022/10/img_4098.jpg"),
    g("2022/10/img_4099.jpg"),
    g("2022/10/img_4100.jpg"),
    g("2022/10/img_4101.jpg"),
    g("2022/10/img_4108.jpg"),
    g("2022/10/img_4107.jpg"),
    g("2022/10/img_4106.jpg"),
    g("2022/10/img_4105.jpg"),
    g("2022/10/img_4104.jpg"),
    g("2022/10/img_4103.jpg"),
    g("2022/10/img_4102.jpg"),
  ],
};

const pompeysPillar: Guide = {
  slug: "egypt-site-pompeys-pillar",
  title_ar: "عمود دقلديانوس",
  title_en: "Pompey's Pillar",
  kicker_ar: "مواقع أثرية · الاسكندرية",
  kicker_en: "Archaeological sites · Alexandria",
  image: U("2022/10/img_4139.jpg"),
  blocks: [
    { type: "H3", ar: "عمود دقلديانوس", en: "Pompey's Pillar", noNumber: true },
    { type: "P", ar: "أسس الاسكندر الاكبر المدينة التي تحمل اسمه على ساحل البحر المتوسط في 7 ابريل 331 ق.م ، على أطلال مدينة مصرية قديمة كانت تسمى رع قدت أو راقودة ، وبعد وفاة الاسكندر في بابل عام 323 ق.م ، تصارع قادة جيشه فيما بينهم من أجل السيطرة على أجزاء امبراطوريته الكبيرة ، وكانت مصر من نصيب القائد بطلميوس الأول سوتير 305-285 (ق.م) والذي أسس دولة تحمل اسمه عرفت باسم دولة البطالمة 332-30 (ق.م) ، وأصبحت الاسكندرية عاصمة لحكم البطالمة وباتت اهم وأكبر مدينة في شرق البحر المتوسط حتى نهوض القسطنطينية بالقرن الخامس الميلادي", en: "Alexander the Great founded the city that bears his name on the Mediterranean coast on 7 April 331 BC, on the ruins of an ancient Egyptian town called Ra-Qedet or Rhakotis. After Alexander's death in Babylon in 323 BC, his generals fought over the parts of his great empire, and Egypt fell to Ptolemy I Soter (305–285 BC), who founded the Ptolemaic state (332–30 BC). Alexandria became the capital of Ptolemaic rule and the largest and most important city of the eastern Mediterranean until the rise of Constantinople in the fifth century AD." },
    { type: "P", ar: "من أهم المعالم الأثرية التي يمكن رؤيتها في الاسكندرية اليوم هو عمود دقلديانوس الضخم أو عمود السواري (أواخر عام 290م) والذي يعرف خطأ باسم عمود بومبي ، حيث يقع مباشرة بجوار موقع السيرابيوم وهو المعبد الرئيسي للمعبود سرابيس المعبود الرسمى خلال هذه الفترة ، وقد تم تدمير هذا المعبد عندما حظر الامبراطور البيزنطي ثيودوسيوس الوثنية في عام 391م ، لسوء الحظ لم تنج العديد من المعالم الأثرية للاسكندرية من الهلاك مثل فنار الاسكندرية العظيم ومكتبة الاسكندرية ومقبرة الاسكندر الأكبر", en: "One of the most important monuments still visible in Alexandria today is the huge Column of Diocletian, or Pillar of the Masts (late 290 AD), wrongly known as Pompey's Pillar. It stands right beside the Serapeum, the main temple of Serapis, the official god of the period, which was destroyed when the Byzantine emperor Theodosius banned paganism in 391 AD. Unfortunately many of Alexandria's monuments did not survive, such as the great Lighthouse, the Library and the tomb of Alexander the Great." },
    { type: "P", ar: "تعد أكثر آثار الاسكندرية الباقية حاليا هي الجبانات ، ومن أكثرها أهمية وابداعا هي جبانة او كتاكومب كوم الشقافة من العصر الروماني بالقرب من السيرابيوم ، ويحتوي الكتاكومب على سراديب الموتى على الطراز اليوناني والدفنات الثلاثية ومزار ومنطقة مأدبة كان يتم استخدامها خلال الجنازات ، تجمع المناظر والنقوش ما بين المعتقدات والتقاليد الفنية المصرية واليونانية القديمة", en: "Most of Alexandria's surviving antiquities are its cemeteries, the most important and inventive being the Roman-period catacombs of Kom el-Shoqafa near the Serapeum. They contain Greek-style burial galleries, triple burials, a shrine and a banqueting area used during funerals, and their scenes and reliefs combine ancient Egyptian and Greek beliefs and artistic traditions." },
    { type: "P", ar: "ومن أجمل المواقع الاثرية الغير جنائزية الباقية منطقة كوم الدكة ، والتي ترجع آثارها لأواخر العصر الروماني وحتى العصر البيزنطي والتي تتضمن المسرح الروماني وحمام وقاعة محاضرات ومنازل للصفوة والمميزة بزخارف الفسيفساء بالاضافة الى ورش عمل", en: "Among the finest surviving non-funerary sites is Kom el-Dikka, whose remains date from the late Roman to the Byzantine period and include the Roman theatre, a bath, a lecture hall, elite houses noted for their mosaic decoration, and workshops." },
    { type: "P", ar: "عانت المدينة القديمة كثيرا طوال تاريخها ، حيث تعرضت للتدمير على يد الملكة زنوبيا ملكة تدمر عام 259م ، كما تعرضت لعدة زلازل كبرى في اواخر العصور القديمة والعصور الوسطى ، ومع ذلك فقد بقي مجد الاسكندرية والعديد من آثارها في ذاكرة وكتابات الرحالة الاغريق والرومان ، مؤخرا بدأت عمليات الكشف عن الآثار الغارقة في العثور على آثار وتماثيل ضخمة بعدة مواقع ساحلية مختلفة", en: "The ancient city suffered greatly throughout its history: it was destroyed by Queen Zenobia of Palmyra in 259 AD and struck by several major earthquakes in late antiquity and the Middle Ages. Yet the glory of Alexandria and many of its monuments survive in the memory and writings of Greek and Roman travellers, and recent underwater excavations have begun to uncover monuments and colossal statues at several coastal sites." },
    g("2022/10/img_4139-1.jpg", "عمود دقلديانوس بالاسكندرية", "Pompey's Pillar in Alexandria"),
    { type: "H3", ar: "جبانة الشاطبي", en: "The Shatby Necropolis" },
    { type: "P", ar: "تتضمن جبانة الشاطبي أقدم مقابر أثرية بالاسكندرية حيث يبدو أنها شيدت بعد تأسيس المدينة مباشرة عام 332 ق.م ، ويمكن للزائر أن يلمح تطور معمار المقابر في تلك الجبانة بداية من آبار الدفن مرورا بممرات الدفن وحتى ما يعرف بالهيبوجيوم ، وهي عبارة عن مجموعة من الحجرات الواقعة تحت الأرض والمنحوتة في باطن الصخر تفتح على مساحة مفتوحة والتي كان يقام فيها الطقوس الجنائزية", en: "The Shatby necropolis contains the oldest tombs in Alexandria, apparently built immediately after the city's founding in 332 BC. Visitors can trace the development of tomb architecture here, from burial shafts through burial corridors to what is known as the hypogeum, a group of underground chambers cut into the rock and opening onto an open space where funerary rites were performed." },
    { type: "P", ar: "وكان البعض من تلك الحجرات تضم توابيت ضخمة على شكل أسرة تسمى كليني وهي كلمة يونانية تعنى سرير ، ولكن أغلب الدفنات كانت تتضمن لوكولي ، وهي عبارة عن فجوات مستطيلة منحوتة في الجدران ، وكانت أغلب الدفنات تتضمن تلك الكوة التي تحتوي على جرار تضم رفات الموتى بعد حرقها وهي العادة التي جاءت إلى مصر من اليونان", en: "Some of these chambers held huge bed-shaped sarcophagi called kline, a Greek word meaning bed, but most burials used loculi, rectangular niches cut into the walls, containing jars with the cremated remains of the dead — a custom that came to Egypt from Greece." },
    { type: "P", ar: "ويمكن لزوار المنطقة أن يروا بقايا الهيبوجيوم الذي يرجع لحوالي عام 280 ق.م ، والذي يبدو أنه كان يخص عائلة واحدة كبيرة والذي توسع لتتوارثه عدة أجيال ، وعلى الرغم من أن مناظر الجدران ليست في حالة جيدة من الحفظ ، الا أن ما تبقى منها يعطينا فكرة على ما كانت عليه المناظر من روعة في السابق ، حيث كانت أغلب الجدران منحوتة تضم أفاريز وأعمدة ونوافذ وهمية مسمطة ، أما المناظر فكانت تعلق بين أعمدة الساحة وتمثل طيور محلقة في السماء الزرقاء في محاكاة للطبيعة المفتوحة", en: "Visitors can see the remains of the hypogeum dating to about 280 BC, which seems to have belonged to one large family and was expanded as it passed down through several generations. Although the wall scenes are not well preserved, what remains gives an idea of their former splendour: most walls were carved with friezes, columns and false windows, while the scenes hung between the columns of the courtyard and depicted birds soaring in a blue sky in imitation of open nature." },
    { type: "P", ar: "أما الكليني الخاص بالهيبوجيوم فكان منحوتا في الصخر على شكل سرير منفذا بدقة عالية تظهر كل أجزاء السرير بما في ذلك المراتب والوسائد ، واتي تعكس صورة رمزية للموت كنوم طويل ، كما استخدمت تلك الأسرة المنحوتة في مناسبات المآدب كي يمتع المتوفى بمتع الحياة بعد موته مما يحول المقبرة الى منزل الأبدية", en: "The hypogeum's kline was cut into the rock in the shape of a bed, executed with great precision so that every part of it appears, including mattresses and cushions, reflecting death symbolically as a long sleep. These carved beds were also used at banquets so the deceased could enjoy the pleasures of life after death, turning the tomb into a house of eternity." },
    { type: "P", ar: "أوقات عمل واسعار تذاكر جبانة الشاطبي : مفتوح يوميا من الساعة 9 صباحا وحتى الساعة 5 مساء ، وتذاكر الدخول للأجانب 40 جنيه مصري ، وللمصريين والعرب 10 جنيه مصري ، وللطلبة نصف اسعار هذه التذاكر", en: "Opening hours and tickets for the Shatby necropolis: open daily from 9 am to 5 pm; entry is 40 Egyptian pounds for foreigners and 10 pounds for Egyptians and Arabs, with half price for students." },
    g("2022/10/img_4142.jpg", "جبانة الشاطبي بالاسكندرية", "The Shatby necropolis in Alexandria"),
    g("2022/10/img_4142-1.jpg", "جبانة الشاطبي بالاسكندرية", "The Shatby necropolis in Alexandria"),
    g("2022/10/img_4141.jpg", "جبانة الشاطبي بالاسكندرية", "The Shatby necropolis in Alexandria"),
    g("2022/10/img_4140.jpg", "جبانة الشاطبي بالاسكندرية", "The Shatby necropolis in Alexandria"),
  ],
};

const abuMena: Guide = {
  slug: "egypt-site-abu-mena",
  title_ar: "منطقة أبو مينا",
  title_en: "The Abu Mena area",
  kicker_ar: "مواقع أثرية · الاسكندرية",
  kicker_en: "Archaeological sites · Alexandria",
  image: U("2022/10/img_4148.jpg"),
  blocks: [
    { type: "H3", ar: "منطقة أبو مينا", en: "The Abu Mena area", noNumber: true },
    g("2022/10/img_4148-1.jpg", "منطقة أبو مينا", "The Abu Mena area"),
    { type: "P", ar: "تضم منطقة أبو مينا الأثرية العديد من المنشآت أغلبها ذات طابع ديني ، أبرزها قبر القديس مينا (285–309م) الذي سميت المنطقة المحيطة باسمه بسبب شهرته في أواخر العصور الرومانية ، فأصبح قبره مزارا دينيا يتبارك به الحجاج", en: "The archaeological area of Abu Mena contains many structures, most of them religious, the most notable being the tomb of Saint Menas (285–309 AD), after whom the surrounding area was named because of his fame in late Roman times; his tomb became a religious shrine where pilgrims sought blessings." },
    { type: "P", ar: "توالى بناء المنشآت المعمارية حول قبر القديس مينا مثل المعمودية ومجموعة من الكنائس والحمامات والمنازل والمعاصر والورش ، بالاضافة الى دور الضيافة وساحة الحجاج وهي عبارة عن فناء يحده صفوف من الأعمدة الرخامية كان يتجمع فيه الحجاج الوافدون على المكان المقدس", en: "Buildings rose one after another around the tomb of Saint Menas: the baptistery, a group of churches, baths, houses, presses and workshops, as well as guest houses and the pilgrims' square — a courtyard bordered by rows of marble columns where pilgrims arriving at the holy place would gather." },
    { type: "P", ar: "اندثرت بقايا المدينة القديمة وكذلك قبر القديس مينا مع مرور الزمن حتى تم اكتشافها على يد عالم الآثار الألماني كاوفمان أوائل القرن العشرين ، لتتوالى أعمال الحفائر للكشف عن بقايا المدينة السكنية من قبل بعثات المتحف القبطي والمتحف اليوناني الروماني ، نظرا للقيمة الدينية والتاريخية للموقع الأثري لأبو مينا ، تم ادراج الموقع بأكمله ضمن قائمة التراث العالمي لليونسكو في عام 1979م", en: "The remains of the ancient city and the tomb of Saint Menas were lost over time until they were discovered by the German archaeologist Kaufmann in the early twentieth century, after which successive excavations by missions from the Coptic Museum and the Greco-Roman Museum uncovered the remains of the residential city. Given the religious and historical value of Abu Mena, the whole site was inscribed on the UNESCO World Heritage list in 1979." },
    g("2022/10/img_4147.jpg", "منطقة أبو مينا بالاسكندرية", "The Abu Mena area in Alexandria"),
  ],
};

const stubs: Guide[] = [
  {
    slug: "egypt-site-saint-catherine",
    title_ar: "دير سانت كاترين وتوابعه",
    title_en: "Saint Catherine's Monastery and its surroundings",
    kicker_ar: "مواقع أثرية · سيناء",
    kicker_en: "Archaeological sites · Sinai",
    image: U("2022/10/img_4161.jpg"),
    blocks: [
      { type: "P", ar: "هذه الصفحة قيد الإعداد وسيتم إضافة تفاصيلها قريباً.", en: "This page is being prepared; its details will be added soon." },
    ],
  },
];

export const egyptSitesGuides: Guide[] = [
  mainSites,
  heliopolis,
  alMuizz,
  alSaliba,
  salahAlDinSquare,
  senusretObelisk,
  alSuyufiyya,
  amadaTemples,
  wadiAlSebua,
  philae,
  abuSimbel,
  pompeysPillar,
  abuMena,
  ...stubs,
];
