import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

// Photo album — images from the Helsinki article (https://100region.com/?p=11732)
const ALBUM = [
  "2022/08/img_1672.jpg",
  "2022/08/img_1673.jpg",
  "2022/08/img_1674.jpg",
  "2022/08/img_1675.jpg",
  "2022/08/img_1676.jpg",
  "2022/08/img_1677.jpg",
  "2022/08/img_1678.jpg",
  "2022/08/img_1679.jpg",
  "2022/08/img_1680.jpg",
  "2022/08/img_1681.jpg",
  "2022/04/img_4494.jpg",
  "2022/04/img_4660.png",
  "2022/01/img_0450.jpg",
  "2022/03/img_3778.jpg",
].map((n) => ({ src: U(n), cap_ar: "صور من فنلندا", cap_en: "Photographs from Finland" }));

export const finlandGuides: Guide[] = [
  {
    slug: "flag",
    title_ar: "علم جمهورية فنلندا",
    title_en: "The flag of the Republic of Finland",
    kicker_ar: "مدلولات العلم",
    kicker_en: "Flag meanings",
    image: U("2022/03/img_3778.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "وصف مدلولات علم جمهورية فنلندا", en: "The meanings of the flag of the Republic of Finland" },
      {
        type: "P",
        ar: "يرجع استخدام الأعلام الى فترات الحرب قديما ، فكانت تستخدم لتحديد شارات القيادة وجمع الحلفاء في ساحة الحرب ، أما الآن تستخدم الأعلام للإشارة الى الدولة وتحديد الهوية ، وفي صناعة الأعلام تعتبر الأنماط البسيطة أساسا لها مع استعمال ألوان وشعارات تدل على هوية الدولة . وبالرجوع أكثر إلى التاريخ يعود اختراع العلم الى شبه القارة الهندية ، حيث ان مؤسس سلالة تشو الصينية في الفترة (1046-256 قبل الميلاد) استخدم الأعلام والرايات البيضاء حيث كانت تتميز بالرموز مثل الطيور والحيوانات ، وانتشرت التنانين الزرقاء على المراكب ، وان سقط العلم سقط أصحابه مما يعني هزيمتهم ، وتعتبر الأعلام رموزا مقدسة وملكية ، وسواء على مراكب أو عربات كان للأعلام أهمية كبيرة في الصين ، وفي مصر القديمة التي استخدمت الحيوانات في رموز الأعلام ، ومع مرور الزمن تم تناقل فكرة الأعلام بين القارات الى ان وصلت الى أوروبا",
        en: "The use of flags goes back to times of war in antiquity, when they were used to mark the insignia of command and to gather allies on the battlefield. Today flags are used to indicate the state and to establish identity, and in flag-making simple patterns are the foundation, together with colours and emblems that point to the identity of the country. Looking further back in history, the invention of the flag goes back to the Indian subcontinent: the founder of the Chinese Zhou dynasty (1046–256 BC) used white flags and banners distinguished by symbols such as birds and animals, and blue dragons spread across ships. If the flag fell, its bearers had fallen, which meant their defeat. Flags were considered sacred and royal symbols, and whether on ships or carts they held great importance in China, and in ancient Egypt, which used animals in the symbols of its flags. Over time the idea of flags passed between continents until it reached Europe.",
      },
      { type: "IMG", src: U("2022/10/img_4686.jpg"), cap_ar: "علم فنلندا", cap_en: "The flag of Finland" },
      { type: "H3", ar: "أهمية علم الدولة", en: "The importance of a country's flag" },
      {
        type: "P",
        ar: "في حال إن كنت تظن ان العلم ما هو إلا شعار يطير في الهواء فأنت مخطئ تماما ، حيث تتعدى أهمية العلم كونه رمزا يرفرف في الهواء : على مر العصور كان العلم يمثل الهوية للحد الذي جعله مقدسا ، تستطيع كل هيئة تحديد العلم الخاص بها واختيار الرمز والشكل ، وبذلك نجد ان الأعلام ليست تقتصر على الدول بل كان من الممكن أن يكون للنبلاء قديما علما وشارة خاصة بهم ، وإذا لامس الأرض قل شأن البلد ، وإذا تم تنكيس الأعلام فهذا دليل على الحداد ، لذلك كان التعامل مع الأعلام على مر التاريخ بحذر شديد",
        en: "If you think a flag is no more than an emblem flying in the air, you are entirely mistaken: the importance of a flag goes far beyond being a symbol fluttering in the wind. Through the ages the flag has represented identity to the point of being held sacred. Every body may define its own flag and choose its symbol and shape, and so flags are not limited to states — in the past nobles too could have their own flag and badge. If a flag touched the ground the standing of the country was diminished, and if flags were lowered to half-mast it was a sign of mourning; that is why flags have been treated with great care throughout history.",
      },
      {
        type: "P",
        ar: "علم الدولة يرمز إلى الدولة ، فبمجرد رؤيته على مكان يتم التعرف أن هذا المكان أو تلك المنشأة ملك لهذه الدولة ، ونرى أعلام الدول على السفن أيضا فنعرف من خلالها من أين أتت هذه السفينة ، وبذلك نجد ان الأعلام تلعب دورا هاما في السلامة البحرية أيضا ليس البرية فقط . لون علم الدولة له أهمية كبرى ، حيث يشير الى شيء يمثل هذه الدولة ، على سبيل المثال يمكن أن يرمز اللون الأحمر الى دم الجنود واللون الأخضر الى الزراعة أو التوحيد ، وتختار كل دولة رموزا على العلم تمثلها ، على سبيل المثال النجوم أو النسر أو سيف ، وبالنظر الى الوقت والمال الذي يحتاجه تصميم علم واحد نجد أهمية العلم بالنسبة للدولة خاصة مع القصص وراءه",
        en: "A state's flag stands for the state: as soon as it is seen over a place, it is understood that this place or facility belongs to that country. We see national flags on ships as well, and through them we know where the ship came from — so flags play an important role in maritime safety, not only on land. The colour of a flag carries great importance, since it points to something that represents the country: red, for example, may stand for the blood of soldiers and green for agriculture or unity. Each country chooses symbols on its flag to represent it, such as stars, an eagle or a sword. Considering the time and money a single flag design requires, we see how important the flag is to a country, especially with the stories behind it.",
      },
      { type: "IMG", src: U("2022/03/img_3778.jpg"), cap_ar: "علم جمهورية فنلندا", cap_en: "The flag of the Republic of Finland" },
      {
        type: "P",
        ar: "لقد تحول العلم الفنلندي الذي وصف ألوانه في 1870م أحد الشعراء قائلا (بزرقة سمائنا وبياض ثلوج شتائنا) ، العلم الرسمي بموجب القانون الصادر بتاريخ 29 مايو 1918م ، بعد مرور فترة لا تتجاوز ستة أشهر من تاريخ استقلال فنلندا",
        en: "The Finnish flag, whose colours a poet described in 1870 as “the blue of our skies and the white of the snows of our winter”, became the official flag under the law issued on 29 May 1918, no more than six months after the date of Finland's independence.",
      },
      {
        type: "P",
        ar: "ويتألف العلم الفنلندي من صليب باللون الأزرق على خلفية بيضاء اللون ، وله صورتان ، العلم الوطني المدني وعلم الدولة",
        en: "The Finnish flag consists of a blue cross on a white background, and it has two forms: the civil national flag and the state flag.",
      },
      { type: "H3", ar: "العلم الوطني", en: "The national flag" },
      {
        type: "P",
        ar: "يأخذ العلم الوطني شكلا مربعا وأبعاده هي : الارتفاع 11 والعرض 18 وحدة قياس ، وعرض الصليب هو 3 وحدات ، اللون هو PMS294C ، يبلغ ارتفاع الحقول 4 وحدات ، وطولها في قسم الرافعة 5 وحدات أما في القسم الحر فيبلغ 10 وحدات ، يتمتع كل مواطن فنلندي بحق رفع العلم الوطني ، تستخدم السفن الفنلندية العلم الوطني شعارا لها الا في بعض الاستثناءات الخاصة",
        en: "The national flag is rectangular, with dimensions of 11 units in height and 18 units in width; the width of the cross is 3 units and the colour is PMS294C. The fields are 4 units high, and 5 units long in the hoist section and 10 units in the free section. Every Finnish citizen has the right to raise the national flag, and Finnish ships use the national flag as their ensign, with a few special exceptions.",
      },
      { type: "H3", ar: "علم الدولة", en: "The state flag" },
      {
        type: "P",
        ar: "قد يتخذ علم الدولة اما الشكل المربع أو ذي الثلاث نقاط ، يضاف شعار النبل الفنلندي في منتصف تقاطع ذراعي الصليب ، يتكون هذا المربع من اطار أصفر اللون ، وعرضه يعادل وحدة من أربعين وحدة لعرض الصليب ، ترفع الوزارات والهيئات الحكومية العلم المربع ، تستخدم قوات الدفاع الاصدار المثلث من العلم ، والذي يكون أطول بمقدار وحدة واحدة من العلم الوطني أو العلم المربع للدولة ، يستخدم رئيس الجمهورية العلم المثلث ، في المقاطعة التي يتقاطع فيها الصليب الأزرق مع الأصفر تعبيرا عن الحرية",
        en: "The state flag may take either the rectangular form or the swallow-tailed form with three points. The Finnish coat of arms is added at the centre where the arms of the cross meet, set in a square with a yellow frame whose width equals one fortieth of the width of the cross. Ministries and government bodies raise the rectangular flag, while the defence forces use the swallow-tailed version, which is one unit longer than the national flag or the rectangular state flag. The President of the Republic uses the swallow-tailed flag, in the canton where the blue cross meets the yellow as an expression of freedom.",
      },
    ],
  },
  {
    slug: "famous-for",
    title_ar: "تعرف على كل ما تشتهر به فنلندا",
    title_en: "Everything Finland is famous for",
    kicker_ar: "ما تشتهر به فنلندا",
    kicker_en: "Famous for",
    image: U("2022/10/img_5338.jpg"),
    blocks: [
      { type: "IMG", src: U("2022/10/img_5338.jpg"), cap_ar: "فنلندا", cap_en: "Finland" },
      { type: "H3", noNumber: true, ar: "التفرد والاستثناء", en: "Uniqueness and exception" },
      {
        type: "P",
        ar: "بلد رائع وشعب عظيم يعيش في أرقى بقاع العالم ، حيث الطبيعة الساحرة والأجواء المثالية للحياة الكريمة ، ومن الطبيعي جدا ان يتفرد ويتميز ويكون استثنائيا في كل شيء ، فهذا وضع طبيعي نتيجة لتهيئة الظروف لكل ما من شأنه الابداع والرقي . وفيما يلي بعض الأمور التي تشتهر بها فنلندا",
        en: "A wonderful country and a great people living in one of the finest corners of the world, with charming nature and ideal conditions for a dignified life. It is only natural that it should be unique, distinguished and exceptional in everything — a natural outcome of creating the conditions for creativity and refinement. Below are some of the things Finland is famous for.",
      },
      { type: "H3", ar: "سلمياكي", en: "Salmiakki" },
      {
        type: "P",
        ar: "هي خيار غريب نوعا ما ، حيث ان الحلويات الأكثر شعبية في فنلندا والتي هي عبارة عن عرق سوس مالح ، لكن الفنلنديين لا يستطيعون الحصول على ما يكفي منه ، ويضعونه في كل شيء من المشروبات الى الآيس كريم ، فاذا كنت شجاعا بما يكفي لتجربتها أو ترغب في اختبار أصدقائك ، فان الأمر يستحق الحصول على بعض من عناصر Salmiakki من السوبر ماركت أو متجر الحلويات أثناء تواجدك في فنلندا",
        en: "A somewhat strange choice: the most popular sweet in Finland is salty liquorice, and Finns simply cannot get enough of it, putting it in everything from drinks to ice cream. If you are brave enough to try it, or want to test your friends, it is worth picking up some Salmiakki items from a supermarket or sweet shop while you are in Finland.",
      },
      { type: "IMG", src: U("2022/10/img_5344.jpg"), cap_ar: "شوكولاتة سلمياكي بفنلندا", cap_en: "Salmiakki chocolate in Finland" },
      { type: "H3", ar: "كانتيلي", en: "Kantele" },
      {
        type: "P",
        ar: "هي آلة موسيقية وترية خشبية تقليدية من منطقة كاريليا ، تشبه القيثارة ، لكنها أطول ، يعد صنع الكانتيل من التمارين الحرفية الشائعة للطلاب ولا يزال يتم استخدامها في الموسيقى الشعبية الفنلندية ، لا يبدو Kantele الصغير رائعا فحسب ، بل انه يصنع زخرفة جميلة",
        en: "A traditional wooden stringed instrument from the Karelia region, similar to a zither but longer. Making a kantele is a common craft exercise for students, and it is still used in Finnish folk music. A small kantele not only looks wonderful, it also makes a beautiful ornament.",
      },
      { type: "IMG", src: U("2022/10/img_5341.jpg"), cap_ar: "آلة كانتيلي بفنلندا", cap_en: "The kantele in Finland" },
      { type: "H3", ar: "زجاجيات", en: "Glassware" },
      {
        type: "P",
        ar: "تشتهر فنلندا بأوانيها الزجاجية ، واحدى العلامات التجارية الأكثر شهرة وقيمة هي Iittala ، التي تصنع الزجاج منذ عام 1881م وهي الآن تملأ كل منزل فنلندي تقريبا بمواد زجاجية ، تدوم لفترة طويلة لدرجة أنه من الشائع أن يرث الناس عناصر Iittala من أقاربهم ، التصميمات بسيطة ولكنها مباشرة وتوظف بعضا من أفضل الفنانين في فنلندا ، هذا يعني أنها تبدو جيدة في أي منزل ، سواء للاستخدام اليومي أو لحفلات العشاء",
        en: "Finland is famous for its glassware, and one of the best-known and most valued brands is Iittala, which has been making glass since 1881 and now fills almost every Finnish home. Its pieces last so long that it is common for people to inherit Iittala items from relatives. The designs are simple but direct and employ some of Finland's finest artists, which means they look good in any home, whether for everyday use or for dinner parties.",
      },
      { type: "H3", ar: "مصنوعات مومين", en: "Moomin goods" },
      {
        type: "P",
        ar: "يمكنك شراء كتب وسلع Moomin في جميع أنحاء العالم ، وهناك عدد لا بأس به من متاجر Moomin التي تظهر في فنلندا موطنها فقط ، يمكنك العثور على أفضل مجموعة من عناصر Moomin ، بما في ذلك الألعاب والمناشف والأدوات المنزلية والحقائب المدرسية والقرطاسية وأدوات الأطفال والمجوهرات والمقتنيات",
        en: "You can buy Moomin books and goods all over the world, but a fair number of Moomin shops appear only in Finland, their homeland. There you can find the best selection of Moomin items, including toys, towels, household goods, school bags, stationery, children's utensils, jewellery and collectibles.",
      },
      { type: "H3", ar: "عناصر السونا", en: "Sauna items" },
      {
        type: "P",
        ar: "يمكن استخدام حمامات البخار في جميع أنحاء العالم ، ولكنها في فنلندا تحظى بشعبية سائدة وكبيرة ، ويحتوي كل منزل في فنلندا تقريبا على ساونا خاصة به ، وعلى هذا النحو يمكن العثور على أدوات الساونا مثل الدلاء والمغارف وأقمشة الجلوس في العديد من المتاجر الفنلندية ، والأكثر غرابة من ذلك كله هو أوراق البتولا ، التي يتم ضربها تقليديا على الجلد أثناء التواجد في الساونا لتحسين الدورة الدموية",
        en: "Steam baths can be used all over the world, but in Finland they enjoy overwhelming popularity, and almost every home has its own sauna. As such, sauna tools such as buckets, ladles and seat covers can be found in many Finnish shops — and strangest of all, birch leaves, traditionally beaten against the skin while in the sauna to improve circulation.",
      },
      { type: "H3", ar: "سكين بوكو", en: "The puukko knife" },
      {
        type: "P",
        ar: "هي سكين صيد فنلندي تقليدي وتسمى Puukko ، تباع عادة في غلاف مصنوع يدويا ويمكن ربطه بحزام ، قد يبدو هذا غير عادي لكن من القانوني بيع هذه المنتجات في أسواق الشوارع في فنلندا ، انها جيدة ليست فقط للصيد ولكن أيضا للأغراض العامة ، بما في ذلك تحضير الأسماك وتصنيع الجلود ونحت الخشب",
        en: "A traditional Finnish hunting knife called the puukko, usually sold in a handmade sheath that can be attached to a belt. It may seem unusual, but it is legal to sell these products in street markets in Finland. They are good not only for hunting but also for general purposes, including preparing fish, working leather and carving wood.",
      },
      { type: "H3", ar: "حلويات فزر", en: "Fazer sweets" },
      {
        type: "P",
        ar: "تبيع شركة Fazer الحلويات والمواد الغذائية الأخرى في فنلندا منذ عام 1891م ، ولا يزال بامكانك العثور على مجموعة كبيرة ومتنوعة من حلويات وشوكولاتة Fazer في البلاد ، وتتكون من ألواح الحلوى العادية للوجبات الخفيفة ، وغالبا ما تكون ألواح شوكولاتة الحليب Fazer blue الى علب الهدايا المتخصصة",
        en: "Fazer has been selling sweets and other foodstuffs in Finland since 1891, and you can still find a large and varied range of Fazer sweets and chocolate in the country, from ordinary snack bars — often the Fazer Blue milk chocolate bars — to specialised gift boxes.",
      },
      { type: "H3", ar: "معجنات كاريليان", en: "Karelian pasties" },
      {
        type: "P",
        ar: "تعتبر معجنات كاريليا عنصرا أساسيا آخر في منطقة كاريليا ، وهي عبارة عن معجنات بيضاوية الشكل مملوءة بالأرز أو البطاطس أو الجزر وعادة ما تعلوها زبدة البيض ، في حين أنه من الممكن صنعها في المنزل ، فان المخابز الفنلندية المحلية هي أفضل الأماكن لتجربة معجنات كاريليا الأصلية الدافئة من الفرن وتعلوها زبدة البيض ، انها لذيذة جدا لدرجة أن متاجر الحرف اليدوية في Karelian تبيع عناصر محلية الصنع على شكل معجنات كاريليان",
        en: "Karelian pasties are another staple of the Karelia region: oval pastries filled with rice, potato or carrot and usually topped with egg butter. While it is possible to make them at home, local Finnish bakeries are the best places to try authentic Karelian pasties warm from the oven with egg butter on top. They are so delicious that Karelian craft shops sell handmade items shaped like Karelian pasties.",
      },
      { type: "H3", ar: "شراب سيما", en: "Sima" },
      {
        type: "P",
        ar: "سيما هو نوع من الشراب يحتوي على نسبة منخفضة من الكحول ، يتم تقديمه تقليديا في عيد العمال جنبا الى جنب مع كعكة القمع ، تباع Sima عادة كمشروب غازي فوار ويمكن أن تشمل العسل أو قشر الليمون أو حتى الزبيب ، يتم بيعها فقط في المتاجر الفنلندية قبل عيد العمال مباشرة",
        en: "Sima is a drink with a low alcohol content, traditionally served on May Day alongside funnel cake. Sima is usually sold as a fizzy drink and may include honey, lemon peel or even raisins. It is sold in Finnish shops only just before May Day.",
      },
      { type: "H3", ar: "ماريميكو", en: "Marimekko" },
      {
        type: "P",
        ar: "يمكن العثور على هذه العلامة التجارية الأكثر شهرة في فنلندا في جميع أنحاء العالم ، ولكن الاختيار الأكبر والأفضل موجود في فنلندا ، يوجد في كل مركز تسوق في المدينة متجر Marimekko وعمليا تجد كل امرأة في فنلندا لديها قميص أو فستان أو حقيبة أو محفظة Marimekko واحدة على الأقل ، يمكنك أيضا العثور على عناصر بتصميمات Marimekko في محلات السوبر ماركت ، مثل ورق التغليف أو المناديل أو الأكواب",
        en: "Finland's most famous brand can be found all over the world, but the largest and best selection is in Finland itself. Every shopping centre in the city has a Marimekko store, and practically every woman in Finland has at least one Marimekko shirt, dress, bag or purse. You can also find items with Marimekko designs in supermarkets, such as wrapping paper, napkins or mugs.",
      },
      { type: "H3", ar: "تريكو فنلندي", en: "Finnish knitwear" },
      {
        type: "P",
        ar: "كان على الفنلنديين ايجاد طريقة للتدفئة قبل التدفئة المركزية ، ولا تزال ملابس التريكو الفنلندية التقليدية تحافظ على دفئهم خلال فصول الشتاء شديدة البرودة ، يمكنك العثور على أنماط تقليدية وأنماط هزلية الى حد ما في متاجر الحرفيين وعادة ما تجد القليل منها في متاجر السلع المستعملة أيضا ، على الرغم من أن المصممين المعاصرين يستخدمون أنماطا أكثر حداثة أيضا",
        en: "Finns had to find a way to keep warm before central heating, and traditional Finnish knitwear still keeps them warm through the bitterly cold winters. You can find traditional patterns, and some rather comic ones, in artisan shops, and you will usually find a few in second-hand stores as well, although contemporary designers use more modern patterns too.",
      },
      { type: "H3", ar: "التناقضات", en: "Contrasts" },
      {
        type: "P",
        ar: "مليئة بالتناقضات المثيرة للاهتمام ، مثل الفصول الأربعة ، شمس منتصف الليل والظلام الشتوي ، الحضري والريفي ، الشرق والغرب",
        en: "Finland is full of interesting contrasts: the four seasons, the midnight sun and the winter darkness, urban and rural, east and west.",
      },
      { type: "H3", ar: "المزيد من الغابات والمياه", en: "More forest and water" },
      {
        type: "P",
        ar: "ربما تكون قد سمعت أن فنلندا هي أرض الألف بحيرة ، لكن هي أيضا أرض الآلاف من الغابات ، أكثر من 70 ٪ من فنلندا تغطيه الغابات الجميلة ، أكثر من أي دولة أوروبية أخرى ومنطقة أكبر من المملكة المتحدة أو ايطاليا ، بحيرات فنلندا البالغ عددها 188,000 بحيرة ، من ناحية أخرى ، شاسعة لدرجة أن فنلندا لديها معظم المياه فيما يتعلق بكتلة اليابسة في جميع دول العالم",
        en: "You may have heard that Finland is the land of a thousand lakes, but it is also the land of thousands of forests: more than 70% of Finland is covered by beautiful forest, more than any other European country and an area larger than the United Kingdom or Italy. Finland's 188,000 lakes, on the other hand, are so vast that Finland has the most water relative to its land mass of all the countries in the world.",
      },
      { type: "H3", ar: "بابا نويل", en: "Santa Claus" },
      {
        type: "P",
        ar: "فنلندا هي المكان الوحيد في العالم الذي يقابل سانتا كلوز الحقيقي ، على الرغم من أن الرجل ذو اللون الأحمر ينتمي الى كورفاتونتوري ، الا أنه يقيم الآن في روفانييمي ، لابلاند ، حيث يستقبل الزوار على مدار السنة",
        en: "Finland is the only place in the world where you meet the real Santa Claus. Although the man in red belongs to Korvatunturi, he now resides in Rovaniemi, Lapland, where he welcomes visitors all year round.",
      },
      { type: "H3", ar: "افضل مكان للتزلج", en: "The best place to ski" },
      {
        type: "P",
        ar: "في فنلندا يمكن لموسم التزلج أن يستمر لأكثر من 6 أشهر ، من أواخر أكتوبر حتى مايو ، فخلال أحلك أيام الشتاء ، تضاء منحدرات التزلج وفي الربيع تشرق الشمس حتى وقت متأخر من الليل ، فاذا كنت تود السفر عبر البلاد ، فهناك مئات ومئات الكيلومترات من مسارات التزلج في Finnish Lapland ، وعلى سبيل المثال تعد مسارات Ylläs التي يبلغ طولها 330 كيلومترا أكثر من أي مكان توفره أوروبا",
        en: "In Finland the ski season can last more than six months, from late October until May. During the darkest days of winter the slopes are floodlit, and in spring the sun shines late into the night. If you want to travel across the country, there are hundreds and hundreds of kilometres of ski trails in Finnish Lapland — the Ylläs trails, for example, run for 330 kilometres, more than anywhere else in Europe.",
      },
      { type: "H3", ar: "الهواء النظيف", en: "Clean air" },
      {
        type: "P",
        ar: "هل تعلم أن هلسنكي لديها بعض من أنظف مياه الصنبور لجميع المدن الكبرى في العالم ، وأن Kilpisjärvi في لابلاند لديه أنظف الهواء في أوروبا",
        en: "Did you know that Helsinki has some of the cleanest tap water of all the major cities in the world, and that Kilpisjärvi in Lapland has the cleanest air in Europe?",
      },
      { type: "H3", ar: "المكان الأكثر أمانا في العالم", en: "The safest place in the world" },
      {
        type: "P",
        ar: "تعد فنلندا واحدة من الدول القليلة في العالم التي يتم فيها ارجاع الحقائب والهواتف المحمولة المفقودة الى مالكها الشرعي ، وبالتالي يشعر الناس بالأمان عند المشي بمفردهم في حدائق المدينة أو استخدام وسائل النقل العام بغض النظر عن الساعة",
        en: "Finland is one of the few countries in the world where lost bags and mobile phones are returned to their rightful owner, and so people feel safe walking alone in the city parks or using public transport whatever the hour.",
      },
      { type: "H3", ar: "مكان مثالي لعشاق القهوة", en: "A perfect place for coffee lovers" },
      {
        type: "P",
        ar: "ربما يتعلق الأمر ببرودة الشتاء ، الفنلنديون فقط يحبون قهوتهم ، يستهلك الفنلنديون القهوة أكثر من أي دولة أخرى في العالم ، ومن الواضح أن هذا يعني أن هناك العديد من المقاهي الرائعة في جميع أنحاء البلاد",
        en: "Perhaps it has to do with the cold of winter — Finns simply love their coffee. Finns consume more coffee than any other country in the world, which obviously means there are many wonderful cafés all over the country.",
      },
      { type: "H3", ar: "مهرجان منتصف الليل السينمائي", en: "The Midnight Sun Film Festival" },
      {
        type: "P",
        ar: "عندما تبقى الشمس لأكثر من شهرين متتاليين في أقصى الأجزاء الشمالية من البلاد ، فقد حان الوقت للاحتفال ، ولعل أكثر الأحداث الصيفية شهرة هو مهرجان منتصف الليل لأفلام الشمس في سودانكيلا ، لابلاند ، احتفل عام 2015 بالذكرى السنوية الثلاثين للحدث ، حيث دعا عشرات الآلاف من هواة السينما الدوليين لمشاهدة الأفلام تحت أشعة الشمس التي لا تغيب أبدا",
        en: "When the sun stays up for more than two months in a row in the far northern parts of the country, it is time to celebrate. Perhaps the most famous summer event is the Midnight Sun Film Festival in Sodankylä, Lapland. In 2015 the event celebrated its thirtieth anniversary, inviting tens of thousands of international film lovers to watch films under a sun that never sets.",
      },
      { type: "H3", ar: "التصميم الأكثر جرأة", en: "The boldest design" },
      {
        type: "P",
        ar: "بعض المصممين والمهندسين المعماريين الأكثر جرأة واعجابا في العالم يأتون من فنلندا",
        en: "Some of the boldest and most admired designers and architects in the world come from Finland.",
      },
      { type: "H3", ar: "أروع الأحداث", en: "The quirkiest events" },
      {
        type: "P",
        ar: "هل سبق لك أن سمعت عن بطولة حمل الزوجة أو العزف على الجيتار أو بطولة رمي الهواتف المحمولة ؟ الفنلنديون مجنونون بعض الشيء عندما يتعلق الأمر بالمسابقات والأحداث ، سواء حدث منطقي أم لا ، لا يهم ، المهم هو أن تدع نفسك تذهب وتستمتع",
        en: "Have you ever heard of the wife-carrying championship, air guitar contests, or the mobile-phone throwing championship? Finns are a little crazy when it comes to competitions and events. Whether the event makes sense or not does not matter — what matters is that you let yourself go and enjoy it.",
      },
      { type: "H3", ar: "أفضل مكان ليكون أما أو طفلا", en: "The best place to be a mother or a child" },
      {
        type: "P",
        ar: "هل تعلم أن العديد من الأطفال حديثي الولادة الفنلندية ينامون في صناديق من الورق المقوى ؟ منذ عام 1938م ، زودت الدولة الفنلندية جميع الأمهات الحوامل بصندوق جميل ودائم بالملابس والملاءات وحفاضات الأطفال واللعب والفراش مما يجعله سريرا ممتازا لقادم جديد صغير ، تصل جميع الأمهات الى المنزل مع طفلهن لمدة عام تقريبا براتب كامل أو مزايا ممتازة",
        en: "Did you know that many Finnish newborns sleep in cardboard boxes? Since 1938 the Finnish state has provided every expectant mother with a beautiful, durable box containing clothes, sheets, nappies, toys and bedding, which makes an excellent cot for a small new arrival. All mothers stay at home with their child for around a year on full pay or excellent benefits.",
      },
      { type: "H3", ar: "أغرب لغة", en: "The strangest language" },
      {
        type: "P",
        ar: "جرب نطق Äkäslompolo وسترى ، يمكن أن يحتوي أي اسم فنلندي على أكثر من 200 شكل مختلف",
        en: "Try pronouncing Äkäslompolo and you will see. Any Finnish noun can have more than 200 different forms.",
      },
      { type: "H3", ar: "أسعد بلد في العالم", en: "The happiest country in the world" },
      {
        type: "P",
        ar: "لن يفاجأ عشاق Northern Lights والساونا وسانتا كلوز بسماع أن فنلندا قد أصبحت أسعد مكان للعيش فيه ، تصدرت فنلندا هذا العام تقرير السعادة العالمية ، حيث تم تصنيف 156 دولة حسب مستويات السعادة ، بناء على عوامل مثل متوسط العمر المتوقع والدعم الاجتماعي والفساد",
        en: "Lovers of the Northern Lights, the sauna and Santa Claus will not be surprised to hear that Finland has become the happiest place to live. Finland topped the World Happiness Report, in which 156 countries were ranked by levels of happiness on the basis of factors such as life expectancy, social support and corruption.",
      },
    ],
  },
  {
    slug: "album",
    title_ar: "صور من فنلندا",
    title_en: "Photographs from Finland",
    kicker_ar: "ألبوم الصور",
    kicker_en: "Photo album",
    image: U("2022/08/img_1680.jpg"),
    blocks: [],
    gallery: ALBUM,
  },
];
