export type GuideBlock =
  | { type: "P"; ar: string; en: string }
  | { type: "H3"; ar: string; en: string }
  | { type: "LIST"; ar: string[]; en: string[] }
  | { type: "IMG"; src: string; cap_ar: string; cap_en: string };

export type Guide = {
  slug: string;
  title_ar: string;
  title_en: string;
  kicker_ar: string;
  kicker_en: string;
  image: string;
  blocks: GuideBlock[];
};

const HERO = {
  program: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600&q=80",
  before: "https://images.unsplash.com/photo-1550340499-a6c60fc8287c?w=1600&q=80",
  facts: "https://images.unsplash.com/photo-1431274172761-fca41d930114?w=1600&q=80",
  todo: "https://images.unsplash.com/photo-1522093007474-d86e9bf7ba6f?w=1600&q=80",
  castles: "https://images.unsplash.com/photo-1591289009723-aef0a1a8a23b?w=1600&q=80",
};

export const franceGuides: Guide[] = [
  {
    slug: "program",
    title_ar: "تعرف على البرنامج السياحي المعد لفرنسا لمدة 15 يوماً",
    title_en: "The 15-day travel program prepared for France",
    kicker_ar: "برنامج سياحي",
    kicker_en: "Itinerary",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_9954.jpg?w=1400&ssl=1",
    blocks: [
      { type: "P", ar: "دولة سياحية سمعت الكثير عن جمالها وربما حلمت بزيارتها وتخيلت مدنها وأماكنها الساحرة، قد تكون فرنسا السياحية التي يحلم الكثير بزيارتها لغناها بالكثير من الميزات السياحية التي تجعلها مقصد السياح للتعرف عليها.", en: "A country of tourism whose beauty you have heard much about, and perhaps dreamed of visiting while imagining its charming cities and places. France may well be the destination that many dream of visiting, thanks to the wealth of attractions that make it a magnet for travellers." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_9954.jpg?w=1400&ssl=1", cap_ar: "اكتشف فرنسا", cap_en: "Discover France" },
      { type: "H3", ar: "اليوم الأول — الوصول إلى العاصمة الفرنسية باريس", en: "Day 1 — Arrival in the French capital, Paris" },
      { type: "LIST", ar: ["بعد الوصول إلى العاصمة الفرنسية باريس يتم التوجه إلى الفندق للاستراحة قليلاً قبل البدء بالجولة السياحية في باريس", "زيارة برج ايفل Eiffel Tower الذي يعد من أهم المقاصد السياحية للسياح حيث يمكنكم الصعود إلى أعلى البرج والاستمتاع بمشاهدة منظر ساحر لمدينة باريس من قمة البرج", "زيارة متحف اللوفر Louvre Museum الذي يقع على الضفة الشمالية لنهر السين وهو من أهم المتاحف الفنية في العالم، يوجد بالقرب من المتحف كافيه تجد فيه دونات وكيك وعصير بالإضافة لوجبات خفيفة", "القيام برحلة كروز لمدة ساعة ونصف في نهر السين الرائع والاستمتاع بالأجواء الطبيعية اللطيفة", "الذهاب إلى المطعم الكشميري للبرياني، ثم الذهاب إلى منطقة لاديفانس La Défense وهي مجمع تسوق جميل يمكنكم التجول في المنطقة والمرور على مجمع الأدوم والفصول الأربعة كما أن أسعارهم مناسبة جداً"], en: ["After arriving in Paris, head to the hotel to rest a little before starting the tour of the city.", "Visit the Eiffel Tower, one of the most important destinations for visitors, where you can go up to the top and enjoy a charming view over Paris.", "Visit the Louvre Museum on the north bank of the Seine, one of the most important art museums in the world. Near the museum there is a café serving donuts, cake, juice and light meals.", "Take a one-and-a-half-hour cruise on the beautiful river Seine and enjoy the pleasant natural surroundings.", "Go to the Kashmiri restaurant for biryani, then head to La Défense, a lovely shopping district where you can walk around and pass by Les Quatre Temps mall — the prices there are very reasonable."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_9922.jpg?w=1400&ssl=1", cap_ar: "برج ايفل", cap_en: "The Eiffel Tower" },
      { type: "H3", ar: "اليوم الثاني — جولة في العاصمة باريس", en: "Day 2 — A tour of Paris" },
      { type: "LIST", ar: ["الذهاب لزيارة قصر فرساي Palace of Versailles والتجول فيه للتعرف عليه عن قرب فهو رائع جداً وقد تحتاج للتجول فيه حوالي 3 ساعات تقريباً لأن القصر كبير جداً بالإضافة لوجود حديقة رائعة فيه، كما يوجد بالقرب منه مجمع تجاري وكافيه ممتاز جداً وفيه أكلات خفيفة ويتميز بأسعاره الممتازة", "زيارة ساحة الكونكورد وحديقة التويلري وهي حديقة جميلة جداً", "الذهاب لشارع الشانزليزيه Avenue des Champs-Élysées وهو أجمل شوارع باريس وهناك إقبال كبير من السائحين عليه حيث يضم الكثير من المحلات التجارية والترفيهية", "العشاء: في مطعم بيتزا روما المشهور بتقديم أفضل أنواع بيتزا الجبن"], en: ["Visit the Palace of Versailles and walk through it to see it up close — it is magnificent and you may need around 3 hours because the palace is very large, with a wonderful garden as well. Nearby there is a shopping centre and an excellent café with light food at great prices.", "Visit Place de la Concorde and the Tuileries Garden, a very beautiful park.", "Go to the Avenue des Champs-Élysées, the most beautiful street in Paris and hugely popular with visitors, full of shops and entertainment.", "Dinner: at Pizza Roma, famous for the best cheese pizza."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0225.jpg?w=1400&ssl=1", cap_ar: "قصر فرساي", cap_en: "The Palace of Versailles" },
      { type: "H3", ar: "اليوم الثالث — زيارة أشهر الأماكن السياحية في باريس", en: "Day 3 — The most famous sights of Paris" },
      { type: "LIST", ar: ["الذهاب للغاليري لافييت وهو سوق ممتاز وفيه ماركات متعددة وفيه طوابق لكل طابق قسم معين كملابس الأطفال والألعاب وغيرها", "زيارة متحف الشمع فهو قريب من السوق السابق", "الذهاب إلى المطعم الكردي لتناول الشاورما مع البيبسي والشبس", "زيارة ساحة الأوبرا", "زيارة متحف العطور، الدخول مجاني يوجد فيه أنواع مختلفة من العطورات وبإمكانهم تصميم خلطات من العطر لتكون خاصة بك فقط، زيارة الحي اللاتيني وفيه أسواق ومحلات رخيصة جداً", "العشاء: بإحدى المطاعم الموجودة في الحي وخاصة مطعم معز للفلافل فهو يقدم وجبات لذيذة"], en: ["Go to Galeries Lafayette, an excellent store with many brands, each floor dedicated to a section such as children's clothes, toys and more.", "Visit the wax museum, which is close to the previous store.", "Go to the Kurdish restaurant for shawarma with a Pepsi and crisps.", "Visit the Opera square.", "Visit the perfume museum — entry is free, there are many kinds of perfume and they can blend a scent that is uniquely yours. Then visit the Latin Quarter with its markets and very cheap shops.", "Dinner: at one of the restaurants in the quarter, especially Maoz falafel, which serves delicious food."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0226.jpg?w=1400&ssl=1", cap_ar: "دار الأوبرا", cap_en: "The Opera house" },
      { type: "H3", ar: "اليوم الرابع — زيارة أشهر الأماكن السياحية في باريس", en: "Day 4 — More of the famous sights of Paris" },
      { type: "LIST", ar: ["الذهاب لهضبة المونمارت وهي هضبة يوجد فيها مجموعة رسامين تقع على مكان مرتفع تستطيع مشاهدة باريس من أعلى نقطة فيها", "زيارة متحف رجال الشرطة وهو متحف جميل جداً فيه أسماء أشهر المحققين وصور رجال الشرطة ومعداتهم، الدخول للمتحف مجاني", "زيارة قرية بيرسي التي تقدم لكم تجربة تسوق مميزة ويوجد فيها أيضاً متاحف وكافيهات ومطاعم يمكنكم الغداء بإحدى المطاعم الموجودة هناك", "زيارة حديقة مونسو القريبة من شارع الشانزليزيه، الدخول إليها مجاني", "العودة لشارع الشانزليزيه والصعود إلى سطح قوس النصر الذي يقع على رأس طريق الشانزليزيه يوجد فيه درج ومصعد كهربائي لكنه فقط للحالات الخاصة", "التسوق من محلات شارع الشانزليزيه", "العشاء: بإحدى مطاعم البيتزا لتذوق وجبة لذيذة"], en: ["Go to the hill of Montmartre, home to a community of painters and set high up so you can see Paris from its highest point.", "Visit the police museum, a very nice museum with the names of the most famous detectives and photographs of officers and their equipment. Entry is free.", "Visit Bercy Village, which offers a special shopping experience and also has museums, cafés and restaurants where you can have lunch.", "Visit Parc Monceau near the Champs-Élysées; entry is free.", "Return to the Champs-Élysées and climb to the roof of the Arc de Triomphe at the head of the avenue. There are stairs and a lift, but the lift is only for special cases.", "Shop in the stores of the Champs-Élysées.", "Dinner: at one of the pizza restaurants for a delicious meal."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0227.jpg?w=1400&ssl=1", cap_ar: "هضبة مونمارت", cap_en: "The hill of Montmartre" },
      { type: "H3", ar: "اليوم الخامس — زيارة سوق أوتلت Outlet", en: "Day 5 — Visiting the outlet mall" },
      { type: "LIST", ar: ["الذهاب إلى سوق أوتلت Outlet سوق التخفيضات والماركات المنتهية موضتها والمنطقة فيها مولات ومجمع Val d'Europe وهو مجمع كبير جداً", "الغداء بإحدى مطاعم العاصمة الفرنسية والاستمتاع بتذوق وجبة فرنسية أصيلة", "زيارة برج مونبارناس Montparnasse Tower وهو أطول برج في أوروبا يوجد كافيه بأعلى دور فيه مميز بإطلالته الساحرة", "الذهاب إلى شارع الشانزليزيه والعشاء بمطعم كويك للوجبات السريعة يوجد فيه وجبات حلال"], en: ["Go to the outlet mall, the place for discounts and end-of-season brands. The area has several malls and the very large Val d'Europe centre.", "Lunch at one of the capital's restaurants, enjoying an authentic French meal.", "Visit Montparnasse Tower, the tallest tower in Europe, with a café on the top floor famous for its charming view.", "Go to the Champs-Élysées and have dinner at Quick fast food, which serves halal meals."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0228.jpg?w=1400&ssl=1", cap_ar: "برج مونبارناس", cap_en: "Montparnasse Tower" },
      { type: "H3", ar: "اليوم السادس — زيارة ملاهي بارك أستريكس", en: "Day 6 — Parc Astérix theme park" },
      { type: "LIST", ar: ["زيارة ملاهي بارك أستريكس وهي مجمع ألعاب شهير تمنحك عيش أجمل الأجواء الترفيهية والمرح وهي مناسبة لقضاء يوم كامل فيها", "مساءً: يمكنكم التجول في مدينة باريس قبل مغادرتها والعشاء بإحدى مطاعمها المشهورة"], en: ["Visit Parc Astérix, a famous theme park that gives you the best atmosphere of fun and entertainment — perfect for a full day out.", "Evening: wander through Paris before leaving it, and have dinner at one of its well-known restaurants."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0229.jpg?w=1400&ssl=1", cap_ar: "بارك أستريكس", cap_en: "Parc Astérix" },
      { type: "H3", ar: "اليوم السابع — زيارة مدينة ستراسبورغ", en: "Day 7 — The city of Strasbourg" },
      { type: "LIST", ar: ["زيارة مدينة ستراسبورغ Strasbourg وهي من أهم المدن السياحية في فرنسا، والتي لا تقل أهمية عن باريس فهي تجذب عدداً كبيراً من السياح للتعرف على معالمها العريقة ومن أشهرها: كاتدرائية ستراسبورغ وتعتبر أحد أهم المعالم السياحية التي تتواجد في ستراسبورغ وهي من أشهر الكنائس التي تتواجد في أوروبا وقد تم بناؤها في القرن السابع عشر وكانت أطول مبنى في ذلك الوقت", "زيارة متحف ستراسبورغ التاريخي حيث يعد واحداً من أهم متاحف فرنسا، ويجسد هذا المتحف التاريخ والأصالة الفرنسية فهو يجسد الحقبة التاريخية التي تقع في الفترة بين العصور الوسطى والعصور الحديثة لمدينة ستراسبورغ الرائعة، يمكنكم القيام بجولة داخل المتحف والتعرف على الأقسام المختلفة، بالإضافة لذلك يضم المتحف العديد من المقتنيات الثمينة والقطع الأثرية النفيسة والتي تعود إلى العصور القديمة ومنها الأسلحة القديمة والأزياء العسكرية والتحف الأثرية القديمة وغيرها الكثير"], en: ["Visit Strasbourg, one of the most important tourist cities in France and no less important than Paris; it draws large numbers of visitors to its historic landmarks. The most famous is Strasbourg Cathedral, one of the city's key sights and one of the most famous churches in Europe, built in the seventeenth century and the tallest building of its time.", "Visit the Strasbourg Historical Museum, one of France's most important museums. It embodies French history and heritage, covering the period between the Middle Ages and modern times in this wonderful city. You can tour its different sections, and it holds many precious possessions and valuable antiquities from ancient times, including old weapons, military uniforms and antique artefacts."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0231.jpg?w=1400&ssl=1", cap_ar: "كاتدرائية ستراسبورغ", cap_en: "Strasbourg Cathedral" },
      { type: "H3", ar: "اليوم الثامن — زيارة مدينة شامونيه", en: "Day 8 — The city of Chamonix" },
      { type: "LIST", ar: ["زيارة مدينة شامونيه Chamonix التي تعد من أهم المدن الفرنسية وهي أعلى منطقة في فرنسا بأكملها كما أنها تعد من أجمل المدن السياحية والتي تحتوي على العديد من الجبال والقمم والمرتفعات فهي مناسبة لمحبي مغامرات التزلج وتسلق الجبال حيث يمكنهم ممارسة مجموعة أنشطة هناك", "من المعالم السياحية المهمة التي يمكنكم زيارتها: منتزه شامونيه الترفيهي وهو رائع جداً يقصده العديد من الزوار من مختلف أنحاء العالم، حيث يعتبر من أهم الوجهات السياحية ويضم مجموعة مميزة من الألعاب المثيرة ومن أشهرها زحليقة شامونيه، والتي تمتد لمسافات طويلة في الهواء الطلق فهي تجربة مثيرة وممتعة جداً تمنحك فرصة العيش بأجمل الأجواء الترفيهية، كما يمكنكم أيضاً ممارسة العديد من الرياضات المائية الرائعة ومن أشهرها تجربة ركوب الطائر الذي ينحدر من ارتفاع 8 أمتار بأقصى سرعة ممكنة وغيرها من الألعاب المختلفة المليئة بالإثارة والمغامرات داخل المنتزه لقضاء أوقات سعيدة"], en: ["Visit Chamonix, one of France's most important cities and the highest area in the whole country. It is also one of the most beautiful tourist cities, with many mountains, peaks and highlands, making it ideal for lovers of skiing and mountain climbing, with a range of activities on offer.", "Among the important sights to visit: the Chamonix amusement park, which is wonderful and draws visitors from around the world. It is one of the leading attractions and holds a special collection of thrilling rides, the most famous being the Chamonix luge, which runs for long distances in the open air — an exciting and very enjoyable experience. You can also try many great water activities, the most famous being the zip-line ride that drops from a height of 8 metres at full speed, along with other rides full of thrills and adventure for a happy day out."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0236.jpg?w=1400&ssl=1", cap_ar: "مدينة شامونيه", cap_en: "The city of Chamonix" },
      { type: "H3", ar: "اليوم التاسع — زيارة مدينة آنسي", en: "Day 9 — The city of Annecy" },
      { type: "LIST", ar: ["زيارة مدينة أنسي Annecy والتي تعتبر من أهم المدن في فرنسا، ومن أهم الأماكن السياحية المفضلة للكثير من الزوار والتي تتميز بطبيعتها الساحرة وجوها البديع، ومن أهم معالمها السياحية: بحيرة آنسي وهي من أهم وأشهر البحيرات التي تتواجد في آنسي بصفة خاصة وفي فرنسا بصفة عامة كما أنها ثالث أكبر بحيرة في فرنسا، وهي من أهم الواجهات السياحية المميزة التي تجذب السياح، كما أنها أنظف بحيرة في أوروبا، يمكنكم ممارسة مجموعة من الأنشطة مثل الجلوس على ضفاف البحيرة والتجول سيراً على الأقدام أو بالاعتماد على الدراجة الهوائية والتي تعتبر من أروع الجولات بين أجمل مناظر الطبيعة الخلابة، بالإضافة لذلك يمكنكم ممارسة بعض الرياضات المائية المختلفة مثل الغطس والسباحة والتزلج وركوب الأمواج وغيرها الكثير من الرياضات الرائعة، ويعد هذا المكان رائعاً لالتقاط أجمل الصور التذكارية"], en: ["Visit Annecy, one of the most important cities in France and a favourite destination for many visitors thanks to its charming nature and lovely climate. Its most important sight is Lake Annecy, one of the most famous lakes in Annecy in particular and France in general, and the third largest lake in the country. It is a distinctive attraction that draws visitors, and it is the cleanest lake in Europe. You can enjoy many activities such as sitting on the shore and walking or cycling around it — among the finest tours through beautiful scenery. You can also try water sports such as diving, swimming, water skiing, surfing and much more, and the place is wonderful for taking memorable photographs."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0232.jpg?w=1400&ssl=1", cap_ar: "مدينة أنسي", cap_en: "The city of Annecy" },
      { type: "H3", ar: "اليوم العاشر — زيارة مدينة كان Cannes", en: "Day 10 — The city of Cannes" },
      { type: "LIST", ar: ["زيارة مدينة كان Cannes الفرنسية والتي تعتبر من أهم مدن الريفيرا الفرنسية كما أن مدينة كان مشهورة بتقديم أهم مهرجانات السينما العالمية وتحتوي على العديد من المعالم السياحية التي يمكن زيارتها منها: زيارة مدينة كان القديمة التي تعتبر واحدة من أهم أماكن السياحة في مدينة كان الفرنسية، كما يوجد فيها العديد من المعالم التراثية الأصيلة، وأكثر ما يميز هذه المدينة شوارعها الجميلة وأجواؤها الهادئة، يمكن لزوار مدينة كان القيام بالعديد من الأنشطة المختلفة ومن أشهرها التجول بين شوارع وأزقة المدينة القديمة ورؤية البيوت الملونة", "زيارة العديد من المعالم السياحية المختلفة ومن أشهرها ساحة كاستر والتي تعد أهم المعالم والقلب النابض لمدينة كان القديمة"], en: ["Visit Cannes, one of the most important cities on the French Riviera, famous for hosting the world's leading film festival and home to many sights. Among them: the old town of Cannes, one of the city's most important tourist areas, with many authentic heritage landmarks. What distinguishes it most are its beautiful streets and calm atmosphere; visitors can enjoy many activities, the most popular being strolling the lanes of the old town and seeing the coloured houses.", "Visit many other sights, the most famous being Square Castre, the most important landmark and the beating heart of old Cannes."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0233.jpg?w=1400&ssl=1", cap_ar: "مقر مؤتمرات مهرجان كان", cap_en: "The Cannes festival congress hall" },
      { type: "H3", ar: "اليوم الحادي عشر — مدينة نيس Nice", en: "Day 11 — The city of Nice" },
      { type: "LIST", ar: ["الانطلاق لزيارة مدينة نيس Nice الفرنسية الشهيرة، التي تضم العديد من الواجهات السياحية المتنوعة", "زيارة أشهر الأماكن السياحية في نيس منها: حديقة فونيكس وتعتبر واحدة من أشهر المنتزهات التي توجد في فرنسا ومن أكبر المنتزهات التي يوجد فيها الكثير من الأقسام المختلفة والتي تعتبر من أهم المعالم السياحية، يمكنكم التجول داخل الأقسام المختلفة لحديقة فونيكس ومنها زيارة القسم الخاص بالنباتات والذي يحتوي على العديد من النباتات المختلفة، كما أنه يضم مجموعة واسعة من النباتات النادرة والتي كانت تتواجد في عصور ما قبل التاريخ", "زيارة حديقة الحيوان التي تتواجد في حديقة فونيكس والتي يوجد فيها العديد من الأنواع المختلفة للحيوانات التي توجد بالعالم كله، ومنها الكنغر وثعلب النهر وغيرها"], en: ["Set off to visit the famous French city of Nice, home to many and varied attractions.", "Visit the most famous sights in Nice, among them Parc Phoenix, one of the best known and largest parks in France with many different sections and a leading attraction. You can wander its various sections, including the plant section with its many different species and a wide collection of rare plants that existed in prehistoric times.", "Visit the zoo inside Parc Phoenix, home to many animal species from all over the world, including kangaroos, otters and others."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0107-2.jpg?w=1400&ssl=1", cap_ar: "مدينة نيس", cap_en: "The city of Nice" },
      { type: "H3", ar: "اليوم الثاني عشر — زيارة مدينة كولمار Colmar", en: "Day 12 — The city of Colmar" },
      { type: "LIST", ar: ["الذهاب إلى مدينة كولمار Colmar الفرنسية والتي تعتبر من أجمل مدن العالم لغناها بالكثير من المعالم السياحية الجميلة", "زيارة كنيسة الدومينيكان وتعتبر هذه الكنيسة واحدة من أهم المعالم السياحية في كولمار، وقد تم بناء هذه الكنيسة على الطراز القديم في عصر النهضة، يمكنكم التجول داخلها والتعرف على معالمها الرائعة ومن أشهرها لوحة Schongauer، والأحجار الوردية الرائعة التي استخدمت في بناء الكنيسة، وغيرها الكثير من المعالم الأخرى الجميلة التي تجذب السيّاح لزيارتها", "زيارة مدينة كولمار القديمة حيث تشاهد فيها الكثير من الأبنية القديمة والكلاسيكية الرائعة كما أن التجول في المدينة القديمة يمنحك الفرصة لمشاهدة محلاتها التجارية الجميلة ومطاعمها المشهورة بتقديم أشهى وألذ الأطباق"], en: ["Go to the French city of Colmar, considered one of the most beautiful cities in the world for its wealth of lovely sights.", "Visit the Dominican Church, one of Colmar's most important landmarks, built in the old Renaissance style. You can walk inside and see its wonderful features, the most famous being the Schongauer painting and the beautiful pink stone used to build the church, along with many other lovely details that draw visitors.", "Visit the old town of Colmar, where you will see many wonderful old and classical buildings. Strolling the old town also lets you see its beautiful shops and restaurants famous for the tastiest dishes."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0237.jpg?w=1400&ssl=1", cap_ar: "مدينة كولمار", cap_en: "The city of Colmar" },
      { type: "H3", ar: "اليوم الثالث عشر — التجول في مدينة كولمار", en: "Day 13 — Exploring Colmar" },
      { type: "LIST", ar: ["صباحاً: بعد الإفطار يتم التجول في المدينة", "زيارة فينيسيا الصغيرة وهي قناة مائية تتفرع عن نهر الراين تمر بداخل مدينة كولمار ويوجد حولها الكثير من المباني الجميلة التي تجعلك تشعر بأنك في مدينة البندقية، ويمكنكم القيام برحلة في أحد القوارب والتجول داخل مدينة كولمار ومشاهدة أهم معالمها السياحية الساحرة", "زيارة ميزون دي تيت المعروف بمجلس الرؤساء ويعد من أقدم المباني الخشبية في مدينة كولمار، والذي يتميز بوجود صور وجوه لأبرز شخصيات المدينة، ويحتوي على الكثير من اللوحات الجدارية الجميلة", "زيارة متحف انترليندن وهو من أهم الأماكن السياحية في كولمار ويوجد فيه العديد من لوحات بيكاسو وماتيس وغيرهم من الفنانين، كما يحتوي على تحف عديدة من الدروع والسجاد والفضيات، بالإضافة لذلك يقام فيه بعض الحفلات الموسيقية الرائعة"], en: ["Morning: after breakfast, stroll around the city.", "Visit Little Venice, a canal branching from the Rhine that runs through Colmar, surrounded by beautiful buildings that make you feel you are in Venice. You can take a boat trip through the city and see its most charming landmarks.", "Visit Maison des Têtes, known as the house of heads, one of the oldest wooden buildings in Colmar, distinguished by the carved faces of the city's most prominent figures and many beautiful murals.", "Visit the Unterlinden Museum, one of Colmar's most important attractions, holding many paintings by Picasso, Matisse and other artists, as well as numerous artefacts including armour, carpets and silverware — and wonderful concerts are held there too."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0238.jpg?w=1400&ssl=1", cap_ar: "مدينة كولمار", cap_en: "The city of Colmar" },
      { type: "H3", ar: "اليوم الرابع عشر — العودة إلى مدينة باريس", en: "Day 14 — Back to Paris" },
      { type: "LIST", ar: ["صباحاً: العودة إلى باريس ثم التوجه إلى الفندق للاستراحة قليلاً", "التجول في المدينة والغداء بإحدى مطاعمها المشهورة أو في الفندق", "مساءً: لكم حرية اختيار زيارة الأماكن المفضلة لديكم في العاصمة باريس"], en: ["Morning: return to Paris and head to the hotel to rest a little.", "Stroll around the city and have lunch at one of its well-known restaurants or at the hotel.", "Evening: you are free to choose your favourite places to visit in the capital."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0241.jpg?w=1400&ssl=1", cap_ar: "شارع الشانزليزيه", cap_en: "The Champs-Élysées" },
      { type: "H3", ar: "اليوم الخامس عشر — مغادرة فرنسا والعودة للديار", en: "Day 15 — Leaving France and heading home" },
      { type: "LIST", ar: ["صباحاً: لكم حرية اختيار أنشطتكم المفضلة مثل التسوق أو التجول في المدينة أو غير ذلك", "الغداء بإحدى مطاعم المدينة والاستمتاع بتناول وجبة فرنسية أصيلة", "مساءً: الذهاب إلى مطار باريس الدولي للعودة للديار بسلامة مع أجمل الذكريات وأسعد لحظات هذه الرحلة الممتعة"], en: ["Morning: you are free to choose your favourite activities such as shopping or walking around the city.", "Lunch at one of the city's restaurants, enjoying an authentic French meal.", "Evening: head to Paris international airport to travel home safely with the finest memories and happiest moments of this enjoyable trip."] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/03/img_0239.jpg?w=1400&ssl=1", cap_ar: "", cap_en: "" },
    ],
  },
  {
    slug: "before-you-go",
    title_ar: "تعرف على فرنسا قبل السفر لها",
    title_en: "Know France before you travel",
    kicker_ar: "قبل السفر",
    kicker_en: "Before you go",
    image: HERO.before,
    blocks: [
      { type: "P", ar: "فرنسا بلد منظّم يحب الهدوء والاحترام المتبادل، ومعرفة بعض التفاصيل الصغيرة قبل السفر تجعل الرحلة أسهل وأجمل بكثير.", en: "France is an orderly country that values calm and mutual respect, and knowing a few small details before you travel makes the trip far easier and more enjoyable." },
      { type: "H3", ar: "التأشيرة والدخول", en: "Visa and entry" },
      { type: "P", ar: "فرنسا ضمن منطقة شنغن، ويمكن التقديم على التأشيرة قبل الرحلة بأسابيع مع حجز الفندق وتذاكر الطيران والتأمين الصحي. احتفظ بنسخة ورقية ورقمية من كل مستند.", en: "France is part of the Schengen area; apply for the visa weeks before the trip with hotel bookings, flight tickets and health insurance. Keep a paper and digital copy of every document." },
      { type: "H3", ar: "أفضل وقت للزيارة", en: "Best time to visit" },
      { type: "P", ar: "الربيع من أبريل إلى يونيو والخريف في سبتمبر وأكتوبر هما الأجمل: جو معتدل وزحام أقل وأسعار أهدأ. أغسطس موسم ذروة وكثير من المحال المحلية تغلق للعطلة.", en: "Spring from April to June and autumn in September and October are the loveliest: mild weather, fewer crowds and calmer prices. August is peak season and many local shops close for the holidays." },
      { type: "H3", ar: "المال واللغة", en: "Money and language" },
      { type: "LIST", ar: ["العملة اليورو، والبطاقات مقبولة في كل مكان تقريباً مع الاحتفاظ بقليل من النقد للأسواق.", "كلمة Bonjour قبل أي حديث تفتح كل الأبواب، وMerci عند المغادرة.", "الإنجليزية مفهومة في المدن الكبيرة، وأقل في القرى."], en: ["The currency is the euro and cards are accepted almost everywhere, though keep a little cash for markets.", "Saying Bonjour before any conversation opens every door, and Merci when you leave.", "English is understood in big cities and less so in villages."] },
      { type: "H3", ar: "أعراف وسلوكيات", en: "Etiquette" },
      { type: "P", ar: "الصوت المنخفض في المطاعم والقطارات مطلوب، والخدمة عادة محسوبة في الفاتورة فالبقشيش اختياري، والوقوف في الصفوف أمر مقدّس.", en: "A low voice in restaurants and trains is expected, service is usually included in the bill so tipping is optional, and queuing is taken seriously." },
    ],
  },
  {
    slug: "facts",
    title_ar: "تعرف على عدد من الحقائق والمعلومات عن فرنسا",
    title_en: "Facts and information about France",
    kicker_ar: "حقائق",
    kicker_en: "Facts",
    image: HERO.facts,
    blocks: [
      { type: "P", ar: "مجموعة من الحقائق التي تعطي صورة أوضح عن فرنسا: أرضها وناسها وثقافتها وما يجعلها الدولة الأكثر زيارة في العالم.", en: "A set of facts that give a clearer picture of France: its land, people, culture and what makes it the most visited country in the world." },
      { type: "LIST", ar: [
        "العاصمة باريس، وعدد السكان نحو ٦٧ مليون نسمة.",
        "المساحة نحو ٦٧٤٬٨٤٣ كم² وهي أكبر دولة في الاتحاد الأوروبي.",
        "فرنسا الدولة الأولى عالمياً في عدد الزوار السنوي.",
        "أعلى قمة في أوروبا الغربية هي مون بلان بارتفاع ٤٨٠٧ أمتار على الحدود مع إيطاليا.",
        "متحف اللوفر أكبر متحف فني في العالم ويضم لوحة الموناليزا.",
        "في فرنسا أكثر من ٤٠٠ نوع من الجبن، والخبز الفرنسي محمي بقانون.",
        "شبكة قطارات TGV تربط المدن بسرعة تصل إلى ٣٢٠ كم/س.",
        "العلم الفرنسي ثلاثي الألوان، وشعار الدولة: حرية، مساواة، أخوّة.",
        "لفرنسا سواحل على المحيط الأطلسي والبحر المتوسط وبحر المانش.",
      ], en: [
        "The capital is Paris and the population is around 67 million.",
        "The area is about 674,843 km², making it the largest country in the European Union.",
        "France is first in the world for annual visitor numbers.",
        "The highest peak in Western Europe is Mont Blanc at 4,807 metres on the Italian border.",
        "The Louvre is the largest art museum in the world and home to the Mona Lisa.",
        "France has more than 400 kinds of cheese, and French bread is protected by law.",
        "The TGV network links cities at speeds up to 320 km/h.",
        "The French flag is a tricolour and the national motto is Liberty, Equality, Fraternity.",
        "France has coasts on the Atlantic, the Mediterranean and the English Channel.",
      ] },
    ],
  },
  {
    slug: "things-to-do",
    title_ar: "أشياء عليك القيام بها في فرنسا",
    title_en: "Things you must do in France",
    kicker_ar: "تجارب",
    kicker_en: "Experiences",
    image: HERO.todo,
    blocks: [
      { type: "P", ar: "ليست قائمة أماكن فقط، بل تجارب تجعل الرحلة إلى فرنسا ذكرى لا تُنسى.", en: "Not just a list of places, but experiences that turn a trip to France into an unforgettable memory." },
      { type: "LIST", ar: [
        "شاهد برج إيفل وقت الغروب ثم انتظر إضاءته اللامعة كل ساعة.",
        "تناول فطوراً فرنسياً في مقهى على الرصيف: كرواسان وقهوة وصحيفة.",
        "اصعد بتلفريك إيغي دو ميدي في شامونيه لترى جبال الألب من الأعلى.",
        "تجوّل في أسواق المدن القديمة واشترِ الجبن والفواكه من الفلاحين.",
        "اركب قارباً في بحيرة أنسي أو رحلة نهرية في بوردو.",
        "زُر قصر فرساي وحدائقه الواسعة في رحلة يوم من باريس.",
        "امشِ على كورنيش الإنجليز في نيس عند الصباح الباكر.",
        "جرّب قطار TGV بين مدينتين لتشاهد الريف الفرنسي من النافذة.",
        "زُر مزارع اللافندر في بروفانس في يونيو ويوليو.",
        "اقضِ أمسية في أوبرا غارنييه أو مسرح صغير في ليون.",
      ], en: [
        "Watch the Eiffel Tower at sunset, then wait for its hourly sparkle.",
        "Have a French breakfast at a pavement café: croissant, coffee and a newspaper.",
        "Ride the Aiguille du Midi cable car in Chamonix to see the Alps from above.",
        "Wander the old-town markets and buy cheese and fruit from the farmers.",
        "Take a boat on Lake Annecy or a river cruise in Bordeaux.",
        "Visit the Palace of Versailles and its vast gardens on a day trip from Paris.",
        "Walk the Promenade des Anglais in Nice in the early morning.",
        "Take the TGV between two cities and watch the French countryside pass by.",
        "Visit the lavender fields of Provence in June and July.",
        "Spend an evening at the Palais Garnier or a small theatre in Lyon.",
      ] },
    ],
  },
  {
    slug: "castles",
    title_ar: "أشهر عشر قلاع في فرنسا",
    title_en: "The ten most famous castles in France",
    kicker_ar: "قلاع وقصور",
    kicker_en: "Castles",
    image: HERO.castles,
    blocks: [
      { type: "P", ar: "فرنسا بلد القلاع، ومعظمها في وادي اللوار حيث بُنيت قصور الملوك بين الأنهار والغابات. هذه أشهر عشر قلاع يمكن زيارتها.", en: "France is a land of castles, most of them in the Loire Valley where the kings built their palaces among rivers and forests. These are the ten most famous castles to visit." },
      { type: "LIST", ar: [
        "قصر فرساي – أشهر قصر ملكي في العالم وقاعة المرايا وحدائقه الهائلة.",
        "قلعة شامبور – أكبر قلاع وادي اللوار بسلالمها الحلزونية المزدوجة.",
        "قلعة شينونسو – قلعة النساء الممتدة فوق نهر الشير.",
        "قلعة مون سان ميشيل – دير محصّن على جزيرة يحيط بها المد.",
        "قلعة كاركاسون – مدينة محصنة كاملة بأسوار وأبراج من العصور الوسطى.",
        "قلعة شيفرني – قلعة كلاسيكية بأثاثها الأصلي وحدائقها.",
        "قلعة أمبواز – قلعة ملكية تطل على اللوار ويرقد فيها ليوناردو دافنشي.",
        "قلعة بلوا – ثلاث حقب معمارية في فناء واحد.",
        "قلعة أزاي لو ريدو – قلعة صغيرة أنيقة تنعكس في الماء.",
        "قلعة بو – مسقط رأس هنري الرابع في جنوب غرب فرنسا.",
      ], en: [
        "Palace of Versailles – the world's most famous royal palace, with the Hall of Mirrors and immense gardens.",
        "Château de Chambord – the largest Loire castle, with its double spiral staircase.",
        "Château de Chenonceau – the ladies' castle, stretching across the river Cher.",
        "Mont-Saint-Michel – a fortified abbey on an island surrounded by the tide.",
        "Carcassonne – a complete medieval walled city of ramparts and towers.",
        "Château de Cheverny – a classical castle with its original furniture and gardens.",
        "Château d'Amboise – a royal castle above the Loire where Leonardo da Vinci is buried.",
        "Château de Blois – three architectural eras around a single courtyard.",
        "Château d'Azay-le-Rideau – a small, elegant castle reflected in the water.",
        "Château de Pau – birthplace of Henry IV in south-west France.",
      ] },
    ],
  },
];

export const getGuide = (slug: string) => franceGuides.find((g) => g.slug === slug);
