import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

// Deep-dive landmark pages for Munich, linked from the city article only.
// Arabic text is copied verbatim from the source pages on 100region.com.
export const munichLandmarkGuides: Guide[] = [
  {
    slug: "st-peters-church",
    title_ar: "كنيسة القديس بطرس .. أشهر كنائس ميونخ",
    title_en: "St Peter's Church — Munich's most famous church",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/img_3487.jpg"),
    blocks: [
      { type: "P", ar: "تعتبر كنيسة القديس بطرس ميونخ في المانيا السياحية الجميلة في قارة أوروبا واحدة من أشهر الاماكن السياحية في ميونخ التي تعبر عن الوجه التاريخي العريق الخاص بالمدينة والممزوج بأهميتها الدينية التي تجعلها من أهم معالم ألمانيا", en: "St Peter's Church in beautiful touristic Munich in Germany, on the continent of Europe, is considered one of the most famous tourist places in Munich, expressing the city's deep-rooted historical face blended with its religious importance, which makes it one of Germany's most important landmarks." },
      { type: "P", ar: "اذ تقع كنسية القديس بطرس في ميونخ في وسط منطقة ريندرماركت التي يقصدها العديد من الزوار على مدار العام من سكان المدينة والسياح المحليين وكذلك السياح الأجانب من خارج البلاد وخصوصا العرب منهم ، كما تم بناء كنيسة سان بطرس بميونخ على شكلها الحالي في أواخر عام 1368م ، وهي واحدة من أهم الكنائس الرومانية الكاثوليكية التي تتميز بطرازها المعماري البافاري الروماني والممزوج بالفن العمراني القوطي", en: "St Peter's Church in Munich stands in the middle of the Rindermarkt district, which many visitors head to all year round — city residents, local tourists and foreign tourists from outside the country, especially Arabs among them. St Peter's Church in Munich was built in its present form in late 1368, and it is one of the most important Roman Catholic churches, distinguished by its Bavarian Romanesque architectural style blended with Gothic architecture." },
      { type: "IMG", src: U("2022/09/img_3481.jpg"), cap_ar: "كنيسة القديس بطرس بميونخ من أعلى", cap_en: "St Peter's Church in Munich from above" },
      { type: "P", ar: "تعتبر كنيسة القديس بطرس (Peterskirche) أقدم كنيسة أبرشية في ميونيخ ، وهي معروفة باسم بيتر القديمة ، وهي تقع في Petersberg ، وهي تلة صغيرة سكنها الرهبان في الأصل ، بنيت الكنيسة على الطراز القوطي في عام 1386 ، وتم تغيير الكنيسة باضافة جوقة باروكية مع ثلاثة أبصار في عام 1636 ، في حين تم منح البرج قبة فانوس بدلا من أبراجه القوطية السابقة ، تشمل المناطق الداخلية البارزة خط هانز كرومبر ، الآثار الرخامية الحمراء من قبل Erasmus Grasser ، وSchrenk Altar من القرن الـ 15 مع تماثيله للصلب وLast Judgment", en: "Peterskirche is the oldest parish church in Munich, known as Old Peter. It stands on the Petersberg, a small hill originally settled by monks. The church was built in the Gothic style in 1386, and was altered by the addition of a Baroque choir with three apses in 1636, while the tower was given a lantern dome instead of its earlier Gothic spires. Notable interiors include the line of Hans Krumper, the red marble monuments by Erasmus Grasser, and the 15th-century Schrenk Altar with its figures of the Crucifixion and the Last Judgment." },
      { type: "P", ar: "ومن الجدير بالذكر أيضا المذبح العالي الذي يبلغ طوله 20 مترا والذي يصل الى القرن الثامن عشر مع شخصيات من آباء الكنيسة الأربعة وسانت بيتر ، كما أن اللوحات الفنية على جدران الجوقة من قبل جان بولاك تستحق المشاهدة ، كما هو الحال مع مذبح عظمة الرحمة (Mariahilf-Altar) من 1756م ، في النهاية البرج ذو الـ 299 خطوة – الذي يشتهر بثماني وجوه على مدار الساعة ، من ثماني أجراس يصل ارتفاعه الى 91 متر ويوفر مناظر بانورامية حتى جبال الألب", en: "Also worth mentioning is the 20-metre high altar dating to the eighteenth century with figures of the four Church Fathers and St Peter. The paintings on the choir walls by Jan Pollack are worth seeing, as is the Mariahilf Altar of 1756. Finally, the 299-step tower — famous for its eight clock faces and eight bells — rises to 91 metres and offers panoramic views as far as the Alps." },
      { type: "IMG", src: U("2022/09/img_3488.jpg"), cap_ar: "كنيسة القديس بطرس بميونخ من الداخل", cap_en: "St Peter's Church in Munich from inside" },
      { type: "IMG", src: U("2022/09/img_3489.jpg"), cap_ar: "كنيسة القديس بطرس بميونخ", cap_en: "St Peter's Church in Munich" },
      { type: "H3", ar: "كنيسة القديس بطرس", en: "St Peter's Church" },
      { type: "P", ar: "تقع كنيسة القديس بطرس على قمة التل في بيترسبرغل ، وبنيت في مدينة ميونخ مرتين ، كانت الأولى في نهاية القرن الحادي عشر ميلادي ، ولكن تم حرقها وتدميرها في عام 1347م ، ليعاد اعمارها فيما بعد على الطراز القوطي ، حاملة بذلك العديد من عناصر عصر النهضة والعصر الباروكي في أرجائها ، اذ تضم الكنيسة داخلها تمثال القديس بطرس ، الذي نحته اراسموس غراسر في بدايات القرن السادس عشر ، ولوحات قوطية تعود للقرن الخامس عشر ، ولوحات جدارية من أواخر العصر الباروكي ، الأمر الذي يجعلها أحد أهم معالم السياحة في ميونخ", en: "St Peter's Church sits on the hilltop at Petersbergl, and it was built in Munich twice: the first at the end of the eleventh century, but it was burned and destroyed in 1347, then rebuilt afterwards in the Gothic style, carrying many Renaissance and Baroque elements throughout. Inside, the church holds the statue of St Peter carved by Erasmus Grasser in the early sixteenth century, Gothic panels dating to the fifteenth century and wall paintings from the late Baroque period, which makes it one of the most important sights of Munich." },
      { type: "H3", ar: "افضل الانشطة التي يمكن القيام بها في كنيسة القديس بطرس", en: "The best activities you can do at St Peter's Church" },
      {
        type: "LIST",
        ar: [
          "يمكنكم البدء بالتجوال في ارجاء كنيسة القديس بطرس ومشاهدة روعتها وروعة جدرانها وزخرفة عواميدها ، حيث انها تعتبر من افضل الاركان السياحية بميونخ لاكتسابها تاريخ قديم وقطع اثرية نادرة وجميلة",
          "يمكنكم الصعود الى برج الكنيسة حيث انها توفر منظرا خلابا رائعا مطلا على مدينة ميونخ وهو مكان جميل ومناسب لالتقاط الصور التذكارية والاستمتاع بالاطلالة الساحرة",
          "يمكنكم زيارة العديد من المعالم التاريخية القريبة من الكنيسة على بعد خطوات فقط",
        ],
        en: [
          "You can begin by wandering around St Peter's Church and seeing its splendour, the splendour of its walls and the ornament of its columns, as it is one of the finest tourist corners in Munich thanks to its ancient history and its rare, beautiful artefacts.",
          "You can climb the church tower, as it offers a stunning, magnificent view overlooking the city of Munich, and it is a lovely, suitable place for taking souvenir photographs and enjoying the enchanting outlook.",
          "You can visit the many historical landmarks close to the church, only a few steps away.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3483.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "IMG", src: U("2022/09/img_3484.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "IMG", src: U("2022/09/img_3485.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "IMG", src: U("2022/09/img_3482.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "IMG", src: U("2022/09/img_3487-1.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "IMG", src: U("2022/09/img_3486.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "IMG", src: U("2022/09/img_3480-1.jpg"), cap_ar: "مجموعة صو لكنيسة القديس بطرس بميونخ", cap_en: "A set of photographs of St Peter's Church in Munich" },
      { type: "H3", ar: "أوقات عمل كنيسة القديس بطرس بميونخ", en: "Opening hours of St Peter's Church in Munich" },
      { type: "P", ar: "في فصل الصيف كافة ايام الاسبوع من الساعة 09:00 صباحا حتى الساعة 18:30 مساء ، وفي فصل الشتاء كافة ايام الأسبوع من الساعة 09:00 صباحا حتى الساعة 17:30 مساء", en: "In summer, all days of the week from 09:00 in the morning until 18:30 in the evening; in winter, all days of the week from 09:00 in the morning until 17:30 in the evening." },
    ],
  },
  {
    slug: "deutsches-museum",
    title_ar: "المتحف الالماني .. متحف التقنية والعلوم",
    title_en: "The Deutsches Museum — the museum of technology and science",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/image-24.jpg"),
    blocks: [
      { type: "P", ar: "المتحف الألماني Deutsches Museum هو متحف التقنية والعلوم في مدينة ميونخ بألمانيا ، بدأ تأسيسه في صيف 1903 من قبل اتحاد المهندسين الالمان في عهد القيصر فيلهلم الثاني وقد افتتح في شهر نوفمبر 1906 ، هو ليس فقط أول المتاحف التقنية في وقته ولكن أيضا من أكثرها زيارة الآن وأكبرها مساحة اذ يقع على مساحة أكثر من 50000 متر مربع", en: "The Deutsches Museum is the museum of technology and science in the city of Munich in Germany. Its founding began in the summer of 1903 by the Association of German Engineers in the era of Kaiser Wilhelm II, and it opened in November 1906. It was not only the first technical museum of its time but is also among the most visited now and the largest in area, covering more than 50,000 square metres." },
      { type: "P", ar: "في المتحف تعرض النماذج بحجمها الطبيعي ، سفن ، مولدات ذرية ، مطاحن هوائية ، مضخات صناعية ومحركات عملاقة وحتى العديد من الطائرات ، أعيد ترميم المتحف بعد نهاية الحرب العالمية الثانية حتى سنوات الستينيات ، يقع المتحف على جزيرة المتحف (Museumsinsel) وهو أحد أكبر معالم مدينة ميونخ ، كما ويستطيع السائح الحصول على منظر جميل لمدينة ميونخ من خلال برج المتحف", en: "In the museum the models are displayed at their natural size: ships, atomic reactors, windmills, industrial pumps and giant engines, and even many aircraft. The museum was restored after the end of the Second World War through to the 1960s. It stands on the museum island (Museumsinsel) and is one of the largest landmarks of Munich, and the visitor can also get a beautiful view of the city from the museum tower." },
      { type: "IMG", src: U("2022/09/img_3509.jpg"), cap_ar: "المتحف الالماني بميونخ", cap_en: "The Deutsches Museum in Munich" },
      { type: "P", ar: "يعرض حوالي 17000 من القطع التقنية الحديثة والاثرية القديمة حيث يتم توسيعه باستمرار عن طريق اضافة أحدث التطورات التقنية ويعد المتحف من اهم الاماكن السياحية في ميونخ ويقع في قلب المدينة", en: "It displays around 17,000 modern technical and ancient historic pieces, and it is continually expanded by adding the latest technical developments. The museum is one of the most important tourist places in Munich and lies in the heart of the city." },
      { type: "IMG", src: U("2022/09/img_3510.jpg"), cap_ar: "المتحف الالماني بميونخ", cap_en: "The Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3511.jpg"), cap_ar: "المتحف الالماني بميونخ", cap_en: "The Deutsches Museum in Munich" },
      { type: "H3", ar: "افضل الانشطة التي يمكن القيام بها في المتحف الالماني بميونخ", en: "The best activities you can do at the Deutsches Museum in Munich" },
      {
        type: "LIST",
        ar: [
          "يمكنكم البدء بزيارة قاعة الاجتماعات الرئيسية التي تستضيف منتدى التقنيات ، حيث يقوم بجذب الكثير من الزوار اذ يتم عرض احدث الاجهزة التقنية وفي بعض الاحيان قد يأتي المخترع او المصمم لهذه الاجهزة",
          "ثم يمكنكم زيارة الأقسام المتنوعة في المتحف ، حيث تم تنظيمها بشكل ممتاز مع شروحات موضحة تسمح للزوار بأن يتعرفوا بشكل اكبر على الكثير من المجالات العلمية والتكنولوجية بصورة جيدة",
          "يمكنكم زيارة مكتبة المتحف وهي تعتبر مرجع في العلوم والتكنولوجيا حيث تحتوي على 750 الف مجلد تقريبا و4000 مطبوعة ومجموعات من الجرائد الالكترونية والخرائط وبراءات الاختراعات والكثير من الادلة العلمية الثابتة اثناء القيام بالابحاث العلمية",
          "كذلك ومن أجمل الأنشطة التي يمكن القيام بها في المتحف الالماني ميونخ هو مشاهدة العروض الحديثة التي تقام في بعض أقسام المتحف ، حيث يتم دمج الأدوات العلمية بطريقة مميزة ويتم عرضها عن طريق استخدام أجهزة الإسقاط ، ولاشك بأنك سوف تعيش لحظات مليئة بالدهشة وأوقات لا يمكن نسيانها",
        ],
        en: [
          "You can begin by visiting the main assembly hall that hosts the technology forum, which attracts many visitors as the newest technical devices are displayed, and sometimes the inventor or designer of these devices attends.",
          "Then you can visit the museum's varied departments, which are excellently organised with clear explanations that allow visitors to learn much more about many scientific and technological fields.",
          "You can visit the museum library, considered a reference in science and technology, containing around 750,000 volumes, 4,000 periodicals, collections of electronic journals, maps, patents and many scientific guides used while carrying out scientific research.",
          "Likewise, one of the finest activities you can do at the Deutsches Museum in Munich is watching the modern presentations held in some of the museum's departments, where the scientific instruments are combined in a distinctive way and shown using projection devices — no doubt you will live moments full of wonder and times that cannot be forgotten.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3512.jpg"), cap_ar: "المتحف الالماني بميونخ", cap_en: "The Deutsches Museum in Munich" },
      { type: "P", ar: "كما تم الاشارة اليه اعلاه فان المتحف الالماني يعرض النماذج بحجمها الطبيعي ، وهو الامر الذي يمكن من الجلوس مباشرة في قمرة القيادة لاحدى طائرات لوفتهانزا الحديثة ، او القبض على دفة القيادة لاحدى السفن العملاقة ، فهناك نماذج كثيرة وحقيقية لانواع مختلفة من الغواصات ، وعدد كبير من المخترعات والمخترعين", en: "As indicated above, the Deutsches Museum displays models at their natural size, which makes it possible to sit directly in the cockpit of one of the modern Lufthansa aircraft, or to grip the helm of one of the giant ships, and there are many real models of different kinds of submarine, and a great number of inventions and inventors." },
      { type: "IMG", src: U("2022/09/img_3518.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3517.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3516.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3515.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3514.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3513.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3523.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3522.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3521.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "IMG", src: U("2022/09/img_3520.jpg"), cap_ar: "صور من المتحف الالماني بميونخ", cap_en: "Photographs from the Deutsches Museum in Munich" },
      { type: "P", ar: "المتحف الالماني هو جيد للأطفال كونه يقدم مجموعة كبيرة من المعارض التفاعلية للأيدي العاملة ، وهناك قسم كامل مخصص للأطفال الفضوليين ، في مملكة الأطفال ، يمكن للمستكشفين الشباب الجلوس خلف عجلة قيادة محرك اطفاء حقيقي ، أو الطيران في الهواء ، أو العزف على غيتار عملاق ، فقط على سبيل المثال لا الحصر من 1000 نشاط صديق للطفل في المتحف الألماني في ميونيخ", en: "The Deutsches Museum is good for children as it offers a large range of hands-on interactive exhibits, and there is a whole section devoted to curious children. In the Kids' Kingdom, young explorers can sit behind the wheel of a real fire engine, fly through the air or play a giant guitar — just a few examples among 1,000 child-friendly activities at the Deutsches Museum in Munich." },
      { type: "IMG", src: U("2022/09/img_3519.jpg"), cap_ar: "المتحف الالماني بميونخ", cap_en: "The Deutsches Museum in Munich" },
      { type: "P", ar: "يمكن الوصول الى المتحف عن طريق أقرب محطة ترام Deutsches Museum ، وأقرب محطة أتوبيس Boschbrücke", en: "The museum can be reached via the nearest tram stop, Deutsches Museum, and the nearest bus stop, Boschbrücke." },
      { type: "H3", ar: "اوقات عمل وسعر تذكرة دخول المتحف الالماني بميونخ", en: "Opening hours and entry ticket price of the Deutsches Museum in Munich" },
      { type: "P", ar: "مفتوح كافة أيام الاسبوع من الساعة 09:00 صباحا وحتى الساعة 17:00 مساء ، وسعر تذكرة الدخول 11 يورو للكبار ، وللاطفال 4 يورو", en: "Open all days of the week from 09:00 in the morning until 17:00 in the evening, and the entry ticket price is 11 euros for adults and 4 euros for children." },
    ],
  },
  {
    slug: "nymphenburg-palace",
    title_ar: "قصر نيمفينبورغ .. القصر الراقي",
    title_en: "Nymphenburg Palace — the elegant palace",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/img_3524.jpg"),
    blocks: [
      { type: "P", ar: "يقع قصر نيمفينبورغ Schloss Nymphenburg في غرب ميونخ في منطقة نويهاوزن نيمفينبورغ ، ويتكون القصر من القصر نفسه وحديقة واسعة وعدة أكشاك ملكية صغيرة ، ويعد قصر نيمفينبورغ أحد أكبر القصور في أوروبا ، ويزوره في وقتنا هذا أعدادا كبيرة من السياح من جميع أنحاء العالم سنويا ، كان هذا القصر المقر الصيفي لعائلة ويتيلزباخ لفترة طويلة", en: "Schloss Nymphenburg lies in the west of Munich in the Neuhausen-Nymphenburg district. The palace consists of the palace itself, a wide garden and several small royal pavilions. Nymphenburg Palace is one of the largest palaces in Europe, and in our time it is visited yearly by large numbers of tourists from all over the world. This palace was the summer residence of the Wittelsbach family for a long time." },
      { type: "IMG", src: U("2022/09/img_3524.jpg"), cap_ar: "قصر نيمفينبورغ بميونخ", cap_en: "Nymphenburg Palace in Munich" },
      { type: "P", ar: "تم تأسيس هذا القصر احتفالا بولادة ولي العهد ماكس ايمانويل المولود في عام 1662م ولقد ولد بعد زواج والده ملك بافاريا بالانتخاب فرديناند ماريا وأمه هنرييت أديلايد بعشر سنوات وعندما أسس هذا القصر أصبح المقر الرسمي الصيفي لملوك بافاريا", en: "This palace was founded in celebration of the birth of the crown prince Max Emanuel, born in 1662, ten years after the marriage of his father, the elector of Bavaria Ferdinand Maria, and his mother Henriette Adelaide, and when this palace was founded it became the official summer residence of the rulers of Bavaria." },
      { type: "P", ar: "عند علم فرديناند ماريا باقتراب موعد قدوم ولي العهد فكر في تشييد قصر نيمفنبورغ تيمنا بولده وقد بدأ في التشييد لهذا البناء في غرب ميونيج في واحدة من أجمل حدائق ميونيخ وبدأ من الجزء الأوسط وشكل مجموعة من الفيلات على التراث الايطالي وأهداها الى زوجته", en: "When Ferdinand Maria learned that the arrival of the crown prince was near, he thought of building Nymphenburg Palace in his son's honour, and he began the construction of this building in the west of Munich in one of the most beautiful gardens of Munich, starting from the central part, and formed a group of villas in the Italian tradition and presented them to his wife." },
      { type: "H3", ar: "أفضل الانشطة التي يمكن القيام بها في قصر نيمفينبورغ بميونخ", en: "The best activities you can do at Nymphenburg Palace in Munich" },
      {
        type: "LIST",
        ar: [
          "عند زيارة معلم تاريخي كهذا فمن أول الأنشطة التي نوصيك القيام بها أن تذهب في جولة مبدئية في أرجاء المكان ، وستستمتع خلالها بمشاهدة الطراز المعماري الذي يتزين به القصر من الخارج",
          "ومن أجل توثيق ذكرى زيارة هذا المكان ستجد أنه من المتاح لك ولجميع الزوار التقاط بعض الصور التذكارية وذلك في جميع أرجاء المكان",
          "حينما تشرع في التعرف على قصر نيمفنبورغ في ميونيخ من الداخل ، سوف تستقطب لرؤية جميع التفاصيل الموجودة بداخله ، وبالتأكيد لن تفوت رؤية غرف القصر والتي تم تجهيز بعض منها كغرف ملكية ومجموعة أخرى للخدم وعددا آخر منها لاستقبال الضيوف",
          "ما يميز هذا القصر ويزيد من روعته صالة الاستقبال الموجودة بداخله والتي جهزت لاستقبال الزوار وصممت بذوق مميز ينعكس في الزخارف والنقوش التي تزين جدرانها والثريات الثمينة التي تعتلي أسقفها",
          "تعكس قطع الأثاث التي توجد في قصر نيمفنبورغ ميونخ لمسات من الفن القديم و هي بالطبع أحد النقاط التي سوف تثير اهتمامك لمشاهدتها لبعض الوقت ، اذ يوجد في القصر قطع أثاث على النمط الباروكي وكذلك قطع أثاث على الطراز الكلاسيكي",
          "من منا لا يهوى الفن وتستقطبه تلك الأعمال الفنية الابداعية ، وجولتك في القصر سوف تخولك من مشاهدة عدد من الآثار الفنية المتنوعة مثل التماثيل والمنحوتات ومجموعة من اللوحات الفنية لأبرز الرسامين",
          "باستطاعتك الاستمتاع برؤية بعض المقتنيات الأثرية في قاعات العرض التي توجد بداخل متحف قصر نيمفنبورغ والتي تظهر مكانة هذا القصر وتاريخه العريق ، ومن أمثلة المعروضات الموجودة في هذه القاعات ، المجوهرات بالاضافة الى القطع الأثرية",
          "سوف تستمتع بالاطلاع على جزء من حياة أفراد الأسرة الحاكمة الذين عاشوا في قصر نيمفنبورغ في ميونيخ عن طريق ما يعرضه القصر من مقتنيات تعود للأسرة الحاكمة",
          "ستشاهد تمثال جونو لدومينيك أوليكزيك وعربات وعربات الملك لودفيج الثاني وبورتريه هيلين سيدلمير لجوزيف كارل ستيلر وغرفة انتظار الناخب تشارلز ثيودور ، بالاضافة الى بورتريه لولا مونتيز بقلم جوزيف كارل ستيلر",
          "من المسموح لكافة زوار قصر نيمفينبورج بالتنزه في الحديقة المحيطة به وقضاء بعض الوقت بداخلها للتمتع بهوائها المنعش وأيضا مشاهدة ما تزدان به الحديقة من برك مائية ونوافير وكذلك منحوتات رائعة ، وبالطبع بوسعك الاستراحة على أحد المقاعد المخصصة للجلوس هناك",
        ],
        en: [
          "When visiting a historical landmark such as this, the first activity we recommend is to go on an initial tour around the place, during which you will enjoy seeing the architectural style that adorns the palace from outside.",
          "In order to record the memory of your visit to this place, you will find that you and all visitors may take some souvenir photographs throughout the whole place.",
          "When you begin to get to know Nymphenburg Palace in Munich from inside, you will be drawn to see every detail it holds, and you will certainly not miss seeing the palace rooms, some of which were fitted out as royal chambers, another group for the servants and a number of others for receiving guests.",
          "What distinguishes this palace and adds to its splendour is the reception hall inside it, prepared for receiving visitors and designed with distinctive taste reflected in the ornament and carving that adorn its walls and the precious chandeliers that crown its ceilings.",
          "The furniture found in Nymphenburg Palace in Munich reflects touches of ancient art, and it is of course one of the things that will draw your interest to look at for a while, as the palace holds furniture in the Baroque style as well as furniture in the Classical style.",
          "Who among us does not love art and is not drawn by those creative works of art? Your tour of the palace will allow you to see a number of varied artistic treasures such as statues and sculptures and a collection of paintings by leading artists.",
          "You can enjoy seeing some of the antiquities in the display halls inside the museum of Nymphenburg Palace, which show the standing of this palace and its deep-rooted history; examples of the exhibits in these halls include jewellery in addition to antique pieces.",
          "You will enjoy learning about part of the life of the members of the ruling family who lived in Nymphenburg Palace in Munich through the belongings of the ruling family that the palace displays.",
          "You will see the statue of Juno by Dominik Auliczek, and the carriages of King Ludwig II, and the portrait of Helene Sedlmayr by Joseph Karl Stieler, and the waiting room of the elector Charles Theodore, in addition to the portrait of Lola Montez by Joseph Karl Stieler.",
          "All visitors to Nymphenburg Palace are allowed to stroll in the garden surrounding it and spend some time inside it to enjoy its fresh air and also to see what adorns the garden of water pools and fountains as well as magnificent sculptures, and of course you can rest on one of the benches provided for sitting there.",
        ],
      },
      { type: "P", ar: "طور بناء قصر نيمفنبورغ في ميونيخ ولي العهد ماكس ايمانول في عام 1700م ولقد وكل في تلك المهمة المهندس أنريكو زوكالي مع المهندس أنطونيوا فيكاردي وشيدوا الأجنحة لهذا القصر من اليسار واليمين ثم ربطوا المباني الجديدة بالفيلل الايطالية التي شيدت في عهد فرديناند ماريا", en: "The crown prince Max Emanuel developed the building of Nymphenburg Palace in Munich in 1700, entrusting that task to the architect Enrico Zuccalli together with the architect Antonio Viscardi, and they built the wings of this palace on the left and the right, then connected the new buildings with the Italian villas raised in the era of Ferdinand Maria." },
      { type: "P", ar: "تكاتف المهندس المعماري جوزيف ايفنر مع المهندس المعماري الفرنسي الشهير دومينيك جيرار في عام 1915م ووضعوا خطة شاملة لتطوير القصر وواحدة من النقاط التي تم التركيز عليها اعادة التصميم للجناح المركزي بالقصر وأصبح نقطة محورية كما تم تأسيس شقق ملكية وأعيد بناء المرافق الواقعة أمام القصر الرئيسي لتتناسب مع المباني الحديثة ولقد خصصت مساكن لموظفي الحكومة", en: "The architect Joseph Effner joined forces with the famous French architect Dominique Girard in 1915 and they laid a comprehensive plan for developing the palace. One of the points focused on was the redesign of the central wing of the palace, which became a focal point; royal apartments were also created and the facilities in front of the main palace were rebuilt to match the newer buildings, and residences were allocated for government employees." },
      { type: "IMG", src: U("2022/09/img_3525.jpg"), cap_ar: "قصر نيمفينبورغ بميونخ", cap_en: "Nymphenburg Palace in Munich" },
      { type: "P", ar: "بعد مرور عام 1751م خطط المهندسين الى اعادة التشكيل لحديقة القصر وهذا ما أضاف اليها الأبعاد الحالية والنمط الباروكي وقد تولى بالانتخاب الحكم الملك كارل ألبريشت في عام 1726م ومن بعده الامبراطور تشارلز السابع عام 1742م ولقد واصل الامبراطور عمليات التطوير في بناء قصر نيمفنبورغ في ميونيخ الذي بدأه والده", en: "After the year 1751 the architects planned to reshape the palace garden, which added its present dimensions and the Baroque style. King Karl Albrecht took over the elective rule in 1726 and after him Emperor Charles VII in 1742, and the emperor continued the development works on the building of Nymphenburg Palace in Munich which his father had begun." },
      { type: "P", ar: "عندما تولى الحكم بالانتخاب الامبراطور كارل تيودور في كلا من بافاريا والبالاتينيت من عام 1777م الى عام 1799م تم توسيع صالات العرض بالقصر وافتتح الامبراطور حديقة القصر للجمهور في عام 1792م وطور في الزخارف والديكورات لتتناسب مع التراث الحديث", en: "When Emperor Karl Theodor took over the elective rule in both Bavaria and the Palatinate from 1777 to 1799, the display halls of the palace were expanded, and the emperor opened the palace garden to the public in 1792 and developed the ornament and the decoration to suit more modern heritage." },
      { type: "IMG", src: U("2022/09/img_3524-1.jpg"), cap_ar: "صور لقصر نيمفينبورغ بميونخ", cap_en: "Photographs of Nymphenburg Palace in Munich" },
      { type: "IMG", src: U("2022/09/img_3532-1.jpg"), cap_ar: "صور لقصر نيمفينبورغ بميونخ", cap_en: "Photographs of Nymphenburg Palace in Munich" },
      { type: "H3", ar: "عنوان ومواعيد عمل وسعر تذكرة قصر نيمفينبورغ بميونخ", en: "Address, opening hours and ticket price of Nymphenburg Palace in Munich" },
      { type: "P", ar: "العنوان : 1 نيمفينبورغ شلوس , 80638 , ميونيخ ، اما مواعيد العمل فهو مفتوح يوميا من الساعة 09:00 صباحا وحتى الساعة 06:00 مساء ، وسعر تذكرة الدخول 11,5 يورو", en: "Address: 1 Nymphenburg Schloss, 80638, Munich. As for the opening hours, it is open daily from 09:00 in the morning until 06:00 in the evening, and the entry ticket price is 11.5 euros." },
    ],
  },
  {
    slug: "olympic-park",
    title_ar: "الحديقة الاولمبية .. ايقونة السياحة في ميونخ",
    title_en: "The Olympic Park — an icon of tourism in Munich",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/img_3539.jpg"),
    blocks: [
      { type: "P", ar: "الحديقة الأولمبية في ميونيخ ، هي حديقة أولمبية شيدت لدورة الألعاب الأولمبية الصيفية لعام 1972 ، تقع الحديقة في حي Oberwiesenfeld وتواصل العمل كمكان للمناسبات الثقافية والاجتماعية والدينية ، مثل أحداث العبادة ، ويشمل كاريلون المعاصر", en: "The Olympic Park in Munich is an Olympic park built for the 1972 Summer Olympic Games. The park lies in the Oberwiesenfeld district and continues to serve as a venue for cultural, social and religious occasions, such as acts of worship, and it includes a contemporary carillon." },
      { type: "P", ar: "تتميز الحديقة الاولمبية بهندستها المعمارية التي تميزها عن العديد من المواقع الأولمبية الأخرى ، فانها فريدة من نوعها وكل عام يأتي اليها ما يقارب أربعة ملايين شخص لممارسة الرياضة أو للاستمتاع بالمعالم السياحية أو لمشاهدة العديد من الأحداث ووسائل الترفيه ، كل هذا جعلها من افضل اماكن السياحة في ميونخ", en: "The Olympic Park stands out for its architecture, which distinguishes it from many other Olympic sites, as it is one of a kind. Every year some four million people come to it to play sport, to enjoy the sights, or to watch its many events and entertainment — all of which has made it one of the best tourist places in Munich." },
      { type: "IMG", src: U("2022/09/img_3540.jpg"), cap_ar: "الحديقة الاولمبية بميونخ", cap_en: "The Olympic Park in Munich" },
      { type: "P", ar: "الملعب الاولمبي .. هو مكان مميز وفريد بفضل بنائه المذهل تحت سقف أيقوني ، وليس فقط المحور المعماري للحديقة الأولمبية بل كان دائما المكان الأكثر أهمية لأكبر وأعظم الأحداث في الرياضة ، منذ افتتاحه رسميا في 26 مايو 1972 وهو من تصميم المعماري الألماني فراي أوتو", en: "The Olympic Stadium is a distinctive, unique place thanks to its astonishing structure beneath an iconic roof. It is not only the architectural axis of the Olympic Park but has always been the most important venue for the biggest and greatest events in sport, since it opened officially on 26 May 1972, and it was designed by the German architect Frei Otto." },
      { type: "P", ar: "ومن حيث الثقافة لا يزال الاستاد الأولمبي أحد أهم المواقع في ألمانيا ورائدتها ، فقد قدم Robbie Williams ، وGenesis وMichael Jackson ، وRolling Stones ، وBruce Springsteen وThree Tenors والعديد من نجوم العالم الآخرين حفلات موسيقية رائعة في الهواء الطلق أمام جمهور تم بيع التذاكر فيها بالكامل ، وكانت هناك أيضا بعض مهرجانات موسيقى الروك استمرت عدة أيام وجذبت عشرات الآلاف من المتفرجين الى الملعب", en: "In terms of culture, the Olympic Stadium remains one of the most important and leading venues in Germany: Robbie Williams, Genesis, Michael Jackson, the Rolling Stones, Bruce Springsteen, the Three Tenors and many other world stars have given superb open-air concerts there before completely sold-out crowds, and there have also been some rock music festivals that lasted several days and drew tens of thousands of spectators to the stadium." },
      { type: "IMG", src: U("2022/09/img_3541.jpg"), cap_ar: "الحديقة الاولمبية بميونخ", cap_en: "The Olympic Park in Munich" },
      { type: "IMG", src: U("2022/09/img_3542.jpg"), cap_ar: "الحديقة الاولمبية بميونخ", cap_en: "The Olympic Park in Munich" },
      { type: "IMG", src: U("2022/09/img_3543.jpg"), cap_ar: "الحديقة الاولمبية بميونخ", cap_en: "The Olympic Park in Munich" },
      { type: "P", ar: "يقع البرج الاولمبي في الحديقة الاولمبية بمدينة ميونخ ، ويبلغ ارتفاعه 290 مترا ، كما ويوجد في اعلى البرج مطعم دوار ، ويوفر البرج اطلاله بانورامية على كل من الحديقة الاولمبية ومدينة ميونخ وجبال الألب ، كما ويتوفر متجر يبيع الهدايا التذكارية عند مدخل البرج", en: "The Olympic Tower stands in the Olympic Park in the city of Munich and is 290 metres high, and at the top of the tower there is a revolving restaurant. The tower offers a panoramic outlook over the Olympic Park, the city of Munich and the Alps, and there is also a shop selling souvenirs at the tower entrance." },
      { type: "P", ar: "منذ افتتاحه في عام 1968 سجل البرج اكثر من 35 مليون زائر ، واعتبارا من عام 2004 وعلى ارتفاع 182 متر هناك مطعم دوار يتسع الى 230 شخصا ، ويعمل البرج ايضا كبرج اذاعي", en: "Since it opened in 1968 the tower has recorded more than 35 million visitors, and as of 2004, at a height of 182 metres, there is a revolving restaurant seating 230 people, and the tower also works as a broadcasting tower." },
      { type: "P", ar: "يتميز البرج بالحياة العصرية والكلاسيكية والاثرية لمدينة ميونخ ، حيث يشاهد الزوار القطع الفنية التي ترجع الى الاف السنين والمقتنيات الاثرية التي تضفي من العبق التاريخي على البرج ، ويعتبر من المعالم الواضحة والمميزة في ميونخ", en: "The tower is marked by the modern, classical and historic life of the city of Munich, where visitors see works of art going back thousands of years and antiquities that lend a historic fragrance to the tower, and it is considered one of the clear and distinctive landmarks in Munich." },
      { type: "IMG", src: U("2022/09/img_3544.jpg"), cap_ar: "الحديقة الاولمبية بميونخ", cap_en: "The Olympic Park in Munich" },
      { type: "H3", ar: "أفضل الانشطة التي يمكن القيام بها في الحديقة الاولمبية بميونخ", en: "The best activities you can do at the Olympic Park in Munich" },
      {
        type: "LIST",
        ar: [
          "حضور المناسبات الرياضية المختلفة حيث تسمح الحديقة لك بالمشاركة في الرياضة نفسها أو حتى المشاهدة ومن هذه الفعاليات السباحة في المسبح الاولمبي وملاعب التنس",
          "بمكانكم ركوب القوارب الصغيرة والاستمتاع بجولة في الحديقة ومشاهدة المناظر الطبيعية والمساحات الخضراء",
          "التزلج علي الثلج أو حتى مشاهدة المسابقات الأولمبية التي تقام في المنطقة المخصصة لهذه المسابقات في الحديقة الاولمبية في ميونخ",
          "حضور الحفلات الموسيقية التي تقام بصورة مستمرة كالروك والبوب",
        ],
        en: [
          "Attending the various sporting occasions, as the park lets you take part in the sport itself or even watch; among these activities are swimming in the Olympic pool and the tennis courts.",
          "You can ride the small boats and enjoy a tour of the park and see the natural scenery and the green spaces.",
          "Skiing on the snow, or even watching the Olympic competitions held in the area dedicated to these competitions in the Olympic Park in Munich.",
          "Attending the music concerts held continuously, such as rock and pop.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3545.jpg"), cap_ar: "الحديقة الاولمبية بميونخ", cap_en: "The Olympic Park in Munich" },
      { type: "H3", ar: "اوقات عمل واسعار تذاكر الحديقة الاولمبية بميونخ", en: "Opening hours and ticket prices of the Olympic Park in Munich" },
      { type: "P", ar: "في الشتاء تفتح من الساعة 11:00 صباحا وحتى 16:00 مساء ، وفي الصيف من الساعة 09:00 صباحا وحتى 20:00 مساء ، وأسعار التذاكر للكبار 3 يورو ، وللاطفال مادون 16 سنة 2 يورو ، وللمجموعات 2.50 يورو", en: "In winter it opens from 11:00 in the morning until 16:00 in the evening, and in summer from 09:00 in the morning until 20:00 in the evening. Ticket prices are 3 euros for adults, 2 euros for children under 16 years, and 2.50 euros for groups." },
    ],
  },
];
