import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

// Deep-dive landmark pages for Munich, linked from the city article only.
export const munichLandmarkGuides: Guide[] = [
  {
    slug: "st-peters-church",
    title_ar: "كنيسة القديس بطرس .. أشهر كنائس ميونخ",
    title_en: "St Peter's Church — Munich's most famous church",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/img_3487.jpg"),
    blocks: [
      { type: "P", ar: "تعتبر كنيسة القديس بطرس ميونخ في المانيا السياحية الجميلة في قارة أوروبا واحدة من أشهر الاماكن السياحية في ميونخ التي تعبر عن الوجه التاريخي العريق الخاص بالمدينة والممزوج بأهميتها الدينية التي تجعلها من أهم معالم ألمانيا", en: "St Peter's Church in Munich is one of the most famous places to visit in the city, expressing its deep historical character blended with the religious importance that makes it one of Germany's key landmarks." },
      { type: "P", ar: "اذ تقع كنيسة القديس بطرس في ميونخ في وسط منطقة ريندرماركت التي يقصدها العديد من الزوار على مدار العام من سكان المدينة والسياح المحليين وكذلك السياح الأجانب من خارج البلاد وخصوصا العرب منهم ، كما تم بناء كنيسة سان بطرس بميونخ على شكلها الحالي في أواخر عام 1368م ، وهي واحدة من أهم الكنائس الرومانية الكاثوليكية التي تتميز بطرازها المعماري البافاري الروماني والممزوج بالفن العمراني القوطي", en: "The church stands in the middle of the Rindermarkt district, visited all year round by locals and by tourists from inside and outside the country. St Peter's took its present form in late 1368 and is one of the most important Roman Catholic churches, marked by a Bavarian-Romanesque style mixed with Gothic architecture." },
      { type: "IMG", src: U("2022/09/img_3481.jpg"), cap_ar: "كنيسة القديس بطرس من الخارج", cap_en: "St Peter's Church from outside" },
      { type: "P", ar: "تعتبر كنيسة القديس بطرس (Peterskirche) أقدم كنيسة أبرشية في ميونيخ ، وهي معروفة باسم بيتر القديمة ، وهي تقع في Petersberg ، وهي تلة صغيرة سكنها الرهبان في الأصل ، بنيت الكنيسة على الطراز القوطي في عام 1386 ، وتم تغيير الكنيسة باضافة جوقة باروكية مع ثلاثة أبصار في عام 1636 ، في حين تم منح البرج قبة فانوس بدلا من أبراجه القوطية السابقة ، تشمل المناطق الداخلية البارزة خط هانز كرومبر ، والآثار الرخامية الحمراء من قبل ايراسموس غراسر ، ومذبح شرينك من القرن الخامس عشر مع تماثيله للصلب ويوم الحساب", en: "Peterskirche is the oldest parish church in Munich, known as Old Peter. It stands on the Petersberg, a small hill originally settled by monks. The church was built in Gothic style in 1386, then altered in 1636 with a Baroque choir and three apses, while the tower was given a lantern dome in place of its earlier Gothic spires. Notable interior features include work by Hans Krumper, red marble monuments by Erasmus Grasser and the fifteenth-century Schrenk Altar with its figures of the Crucifixion and the Last Judgement." },
      { type: "P", ar: "ومن الجدير بالذكر أيضا المذبح العالي الذي يبلغ طوله 20 مترا والذي يصل الى القرن الثامن عشر مع شخصيات من آباء الكنيسة الأربعة وسانت بيتر ، كما أن اللوحات الفنية على جدران الجوقة من قبل جان بولاك تستحق المشاهدة ، كما هو الحال مع مذبح عظمة الرحمة (Mariahilf-Altar) من 1756م ، في النهاية البرج ذو الـ 299 خطوة – الذي يشتهر بثماني وجوه على مدار الساعة ، ومن ثماني أجراس يصل ارتفاعه الى 91 متر ويوفر مناظر بانورامية حتى جبال الألب", en: "Also worth noting is the 20-metre high altar dating to the eighteenth century with figures of the four Church Fathers and St Peter. The paintings on the choir walls by Jan Pollack deserve a look, as does the Mariahilf Altar of 1756. Finally the 299-step tower — famous for its eight clock faces and eight bells — rises to 91 metres and offers panoramic views as far as the Alps." },
      { type: "IMG", src: U("2022/09/img_3488.jpg"), cap_ar: "داخل الكنيسة", cap_en: "Inside the church" },
      { type: "IMG", src: U("2022/09/img_3489.jpg"), cap_ar: "زخارف الكنيسة", cap_en: "The church's ornament" },
      { type: "H3", ar: "كنيسة القديس بطرس", en: "St Peter's Church" },
      { type: "P", ar: "تقع كنيسة القديس بطرس على قمة التل في بيترسبرغل ، وبنيت في مدينة ميونخ مرتين ، كانت الأولى في نهاية القرن الحادي عشر ميلادي ، ولكن تم حرقها وتدميرها في عام 1347م ، ليعاد اعمارها فيما بعد على الطراز القوطي ، حاملة بذلك العديد من عناصر عصر النهضة والعصر الباروكي في أرجائها ، اذ تضم الكنيسة داخلها تمثال القديس بطرس الذي نحته اراسموس غراسر في بدايات القرن السادس عشر ، ولوحات قوطية تعود للقرن الخامس عشر ، ولوحات جدارية من أواخر العصر الباروكي ، الأمر الذي يجعلها أحد أهم معالم السياحة في ميونخ", en: "St Peter's Church sits atop the Petersbergl hill and was built in Munich twice: first at the end of the eleventh century, but it burned and was destroyed in 1347, then rebuilt in Gothic style, carrying many Renaissance and Baroque elements throughout. Inside stands the statue of St Peter carved by Erasmus Grasser in the early sixteenth century, along with fifteenth-century Gothic panels and late Baroque wall paintings — all of which make it one of Munich's most important sights." },
      { type: "H3", ar: "افضل الانشطة التي يمكن القيام بها في كنيسة القديس بطرس", en: "The best things to do at St Peter's Church" },
      {
        type: "LIST",
        ar: [
          "يمكنكم البدء بالتجوال في ارجاء كنيسة القديس بطرس ومشاهدة روعتها وروعة جدرانها وزخرفة عواميدها ، حيث انها تعتبر من افضل الاركان السياحية بميونخ لاكتسابها تاريخا قديما وقطعا اثرية نادرة وجميلة",
          "يمكنكم الصعود الى برج الكنيسة حيث انه يوفر منظرا خلابا رائعا مطلا على مدينة ميونخ وهو مكان جميل ومناسب لالتقاط الصور التذكارية والاستمتاع بالاطلالة الساحرة",
          "يمكنكم زيارة العديد من المعالم التاريخية القريبة من الكنيسة على بعد خطوات فقط",
        ],
        en: [
          "Begin by walking through the church to see its splendour, its walls and the ornament of its columns; it is one of the finest corners of Munich thanks to its ancient history and rare, beautiful artefacts.",
          "Climb the church tower, which offers a stunning view over Munich — a lovely spot for photographs and for enjoying the enchanting outlook.",
          "Visit the many historic landmarks that stand only a few steps from the church.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3483.jpg"), cap_ar: "تفاصيل داخلية", cap_en: "Interior detail" },
      { type: "IMG", src: U("2022/09/img_3484.jpg"), cap_ar: "المذبح العالي", cap_en: "The high altar" },
      { type: "IMG", src: U("2022/09/img_3485.jpg"), cap_ar: "من داخل الكنيسة", cap_en: "Inside the church" },
      { type: "IMG", src: U("2022/09/img_3486.jpg"), cap_ar: "الاطلالة من البرج", cap_en: "The view from the tower" },
      { type: "H3", ar: "أوقات عمل كنيسة القديس بطرس بميونخ", en: "Opening hours of St Peter's Church" },
      { type: "P", ar: "في فصل الصيف كافة ايام الاسبوع من الساعة 09:00 صباحا حتى الساعة 18:30 مساء ، وفي فصل الشتاء كافة ايام الأسبوع من الساعة 09:00 صباحا حتى الساعة 17:30 مساء", en: "In summer, every day of the week from 09:00 in the morning until 18:30; in winter, every day from 09:00 until 17:30." },
    ],
  },
  {
    slug: "deutsches-museum",
    title_ar: "المتحف الالماني .. متحف التقنية والعلوم",
    title_en: "The Deutsches Museum — the museum of technology and science",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/image-24.jpg"),
    blocks: [
      { type: "P", ar: "المتحف الألماني Deutsches Museum هو متحف التقنية والعلوم في مدينة ميونخ بألمانيا ، بدأ تأسيسه في صيف 1903 من قبل اتحاد المهندسين الالمان في عهد القيصر فيلهلم الثاني وقد افتتح في شهر نوفمبر 1906 ، هو ليس فقط أول المتاحف التقنية في وقته ولكن أيضا من أكثرها زيارة الآن وأكبرها مساحة اذ يقع على مساحة أكثر من 50000 متر مربع", en: "The Deutsches Museum is the museum of technology and science in Munich. Its founding began in the summer of 1903 by the Association of German Engineers under Kaiser Wilhelm II, and it opened in November 1906. It was not only the first technical museum of its time but is also among the most visited and the largest today, covering more than 50,000 square metres." },
      { type: "P", ar: "في المتحف تعرض النماذج بحجمها الطبيعي ، سفن ، مولدات ذرية ، مطاحن هوائية ، مضخات صناعية ومحركات عملاقة وحتى العديد من الطائرات ، أعيد ترميم المتحف بعد نهاية الحرب العالمية الثانية حتى سنوات الستينيات ، يقع المتحف على جزيرة المتحف (Museumsinsel) وهو أحد أكبر معالم مدينة ميونخ ، كما ويستطيع السائح الحصول على منظر جميل لمدينة ميونخ من خلال برج المتحف", en: "The museum displays models at their real size: ships, atomic reactors, windmills, industrial pumps, giant engines and even many aircraft. It was restored after the Second World War through to the 1960s. The museum stands on Museumsinsel and is one of Munich's largest attractions; visitors can also enjoy a fine view of the city from the museum tower." },
      { type: "IMG", src: U("2022/09/img_3509.jpg"), cap_ar: "المتحف الالماني", cap_en: "The Deutsches Museum" },
      { type: "P", ar: "يعرض حوالي 17000 من القطع التقنية الحديثة والاثرية القديمة حيث يتم توسيعه باستمرار عن طريق اضافة أحدث التطورات التقنية ويعد المتحف من اهم الاماكن السياحية في ميونخ ويقع في قلب المدينة", en: "It displays around 17,000 modern technical and ancient exhibits, and is constantly expanded with the latest technical developments. The museum is one of the most important places to visit in Munich and lies in the heart of the city." },
      { type: "IMG", src: U("2022/09/img_3510.jpg"), cap_ar: "قاعات المتحف", cap_en: "The museum halls" },
      { type: "IMG", src: U("2022/09/img_3511.jpg"), cap_ar: "معروضات المتحف", cap_en: "Museum exhibits" },
      { type: "H3", ar: "افضل الانشطة التي يمكن القيام بها في المتحف الالماني بميونخ", en: "The best things to do at the Deutsches Museum" },
      {
        type: "LIST",
        ar: [
          "يمكنكم البدء بزيارة قاعة الاجتماعات الرئيسية التي تستضيف منتدى التقنيات ، حيث يقوم بجذب الكثير من الزوار اذ يتم عرض احدث الاجهزة التقنية وفي بعض الاحيان قد يأتي المخترع او المصمم لهذه الاجهزة",
          "ثم يمكنكم زيارة الأقسام المتنوعة في المتحف ، حيث تم تنظيمها بشكل ممتاز مع شروحات موضحة تسمح للزوار بأن يتعرفوا بشكل اكبر على الكثير من المجالات العلمية والتكنولوجية بصورة جيدة",
          "يمكنكم زيارة مكتبة المتحف وهي تعتبر مرجعا في العلوم والتكنولوجيا حيث تحتوي على 750 الف مجلد تقريبا و4000 مطبوعة ومجموعات من الجرائد الالكترونية والخرائط وبراءات الاختراعات",
          "ومن أجمل الأنشطة مشاهدة العروض الحديثة التي تقام في بعض أقسام المتحف ، حيث يتم دمج الأدوات العلمية بطريقة مميزة ويتم عرضها عن طريق استخدام أجهزة الإسقاط",
        ],
        en: [
          "Start with the main hall that hosts the technology forum, which draws many visitors as the newest technical devices are shown — and sometimes their inventor or designer attends.",
          "Then visit the museum's varied departments, excellently organised with clear explanations that let visitors learn much more about many scientific and technological fields.",
          "Visit the museum library, a reference in science and technology with around 750,000 volumes, 4,000 periodicals, collections of electronic journals, maps and patents.",
          "One of the finest activities is watching the modern presentations held in some departments, where scientific instruments are combined and displayed using projection.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3512.jpg"), cap_ar: "نماذج بحجمها الطبيعي", cap_en: "Full-size models" },
      { type: "P", ar: "كما تم الاشارة اليه اعلاه فان المتحف الالماني يعرض النماذج بحجمها الطبيعي ، وهو الامر الذي يمكن من الجلوس مباشرة في قمرة القيادة لاحدى طائرات لوفتهانزا الحديثة ، او القبض على دفة القيادة لاحدى السفن العملاقة ، فهناك نماذج كثيرة وحقيقية لانواع مختلفة من الغواصات ، وعدد كبير من المخترعات والمخترعين", en: "As noted above, the museum displays models at real size, which means you can sit in the cockpit of a modern Lufthansa aircraft or take the helm of a giant ship. There are many real models of different kinds of submarine, and a great number of inventions and inventors." },
      { type: "IMG", src: U("2022/09/img_3518.jpg"), cap_ar: "قسم الطائرات", cap_en: "The aviation section" },
      { type: "IMG", src: U("2022/09/img_3517.jpg"), cap_ar: "قسم البحرية", cap_en: "The maritime section" },
      { type: "IMG", src: U("2022/09/img_3516.jpg"), cap_ar: "معروضات علمية", cap_en: "Scientific exhibits" },
      { type: "IMG", src: U("2022/09/img_3515.jpg"), cap_ar: "من داخل المتحف", cap_en: "Inside the museum" },
      { type: "P", ar: "المتحف الالماني هو جيد للأطفال كونه يقدم مجموعة كبيرة من المعارض التفاعلية ، وهناك قسم كامل مخصص للأطفال الفضوليين ، في مملكة الأطفال يمكن للمستكشفين الشباب الجلوس خلف عجلة قيادة محرك اطفاء حقيقي ، أو الطيران في الهواء ، أو العزف على غيتار عملاق ، فقط على سبيل المثال لا الحصر من 1000 نشاط صديق للطفل في المتحف الألماني في ميونيخ", en: "The museum is good for children, offering a large range of interactive exhibits, and there is a whole section for curious children. In the Kids' Kingdom young explorers can sit behind the wheel of a real fire engine, fly through the air or play a giant guitar — just a few of the 1,000 child-friendly activities in the Deutsches Museum." },
      { type: "IMG", src: U("2022/09/img_3519.jpg"), cap_ar: "مملكة الأطفال", cap_en: "The Kids' Kingdom" },
      { type: "P", ar: "يمكن الوصول الى المتحف عن طريق أقرب محطة ترام Deutsches Museum ، وأقرب محطة أتوبيس Boschbrücke", en: "The museum can be reached from the nearest tram stop, Deutsches Museum, and the nearest bus stop, Boschbrücke." },
      { type: "H3", ar: "اوقات عمل وسعر تذكرة دخول المتحف الالماني بميونخ", en: "Opening hours and ticket price of the Deutsches Museum" },
      { type: "P", ar: "مفتوح كافة أيام الاسبوع من الساعة 09:00 صباحا وحتى الساعة 17:00 مساء ، وسعر تذكرة الدخول 11 يورو للكبار ، وللاطفال 4 يورو", en: "Open every day of the week from 09:00 until 17:00. Entry costs 11 euros for adults and 4 euros for children." },
    ],
  },
  {
    slug: "nymphenburg-palace",
    title_ar: "قصر نيمفينبورغ .. القصر الراقي",
    title_en: "Nymphenburg Palace — the elegant palace",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/img_3524.jpg"),
    blocks: [
      { type: "P", ar: "يقع قصر نيمفينبورغ Schloss Nymphenburg في غرب ميونخ في منطقة نويهاوزن نيمفينبورغ ، ويتكون القصر من القصر نفسه وحديقة واسعة وعدة أكشاك ملكية صغيرة ، ويعد قصر نيمفينبورغ أحد أكبر القصور في أوروبا ، ويزوره في وقتنا هذا أعدادا كبيرة من السياح من جميع أنحاء العالم سنويا ، كان هذا القصر المقر الصيفي لعائلة ويتلزباخ لفترة طويلة", en: "Schloss Nymphenburg lies in western Munich in the Neuhausen-Nymphenburg district. It comprises the palace itself, a wide garden and several small royal pavilions, and is one of the largest palaces in Europe, visited today by great numbers of tourists from all over the world. For a long time it was the summer residence of the Wittelsbach family." },
      { type: "P", ar: "تم تأسيس هذا القصر احتفالا بولادة ولي العهد ماكس ايمانويل المولود في عام 1662م ولقد ولد بعد زواج والده ملك بافاريا بالانتخاب فرديناند ماريا وأمه هنرييت أديلايد بعشر سنوات وعندما أسس هذا القصر أصبح المقر الرسمي الصيفي لملوك بافاريا", en: "The palace was founded to celebrate the birth of the crown prince Max Emanuel, born in 1662, ten years after the marriage of his father, the Bavarian elector Ferdinand Maria, and his mother Henriette Adelaide. Once founded, it became the official summer residence of the rulers of Bavaria." },
      { type: "P", ar: "عند علم فرديناند ماريا باقتراب موعد قدوم ولي العهد فكر في تشييد قصر نيمفنبورغ تيمنا بولده وقد بدأ في التشييد لهذا البناء في غرب ميونيخ في واحدة من أجمل حدائق ميونيخ وبدأ من الجزء الأوسط وشكل مجموعة من الفيلات على التراث الايطالي وأهداها الى زوجته", en: "When Ferdinand Maria learned that the crown prince was on the way, he decided to build Nymphenburg in his son's honour. Construction began in western Munich in one of the city's most beautiful gardens, starting from the central section, forming a group of villas in the Italian tradition which he presented to his wife." },
      { type: "IMG", src: U("2022/09/img_3525.jpg"), cap_ar: "قصر نيمفينبورغ وحديقته", cap_en: "Nymphenburg Palace and its garden" },
      { type: "P", ar: "طور بناء قصر نيمفنبورغ في ميونيخ ولي العهد ماكس ايمانويل في عام 1700م ولقد وكل في تلك المهمة المهندس أنريكو زوكالي مع المهندس أنطونيو فيكاردي وشيدوا الأجنحة لهذا القصر من اليسار واليمين ثم ربطوا المباني الجديدة بالفلل الايطالية التي شيدت في عهد فرديناند ماريا", en: "Crown prince Max Emanuel developed the palace in 1700, entrusting the task to the architects Enrico Zuccalli and Antonio Viscardi, who built the wings to left and right and connected the new buildings with the Italian villas raised under Ferdinand Maria." },
      { type: "P", ar: "تكاتف المهندس المعماري جوزيف ايفنر مع المهندس المعماري الفرنسي الشهير دومينيك جيرار في عام 1915م ووضعوا خطة شاملة لتطوير القصر وواحدة من النقاط التي تم التركيز عليها اعادة التصميم للجناح المركزي بالقصر وأصبح نقطة محورية كما تم تأسيس شقق ملكية وأعيد بناء المرافق الواقعة أمام القصر الرئيسي لتتناسب مع المباني الحديثة", en: "The architect Joseph Effner worked with the famous French architect Dominique Girard on a comprehensive plan for the palace. One focus was the redesign of the central wing, which became the focal point; royal apartments were created and the facilities in front of the main palace were rebuilt to match the newer buildings." },
      { type: "P", ar: "بعد مرور عام 1751م خطط المهندسون الى اعادة التشكيل لحديقة القصر وهذا ما أضاف اليها الأبعاد الحالية والنمط الباروكي وقد تولى بالانتخاب الحكم الملك كارل ألبريشت في عام 1726م ومن بعده الامبراطور تشارلز السابع عام 1742م ولقد واصل الامبراطور عمليات التطوير في بناء قصر نيمفنبورغ الذي بدأه والده", en: "After 1751 the architects planned to reshape the palace garden, giving it its present dimensions and Baroque style. Karl Albrecht became elector in 1726 and after him Emperor Charles VII in 1742, who continued the development of Nymphenburg begun by his father." },
      { type: "P", ar: "عندما تولى الحكم بالانتخاب الامبراطور كارل تيودور في كل من بافاريا والبالاتينيت من عام 1777م الى عام 1799م تم توسيع صالات العرض بالقصر وافتتح الامبراطور حديقة القصر للجمهور في عام 1792م وطور في الزخارف والديكورات لتتناسب مع التراث الحديث", en: "When Elector Karl Theodor ruled both Bavaria and the Palatinate from 1777 to 1799, the palace galleries were expanded; he opened the palace garden to the public in 1792 and developed the ornament and decoration to suit more modern taste." },
      { type: "H3", ar: "أفضل الانشطة التي يمكن القيام بها في قصر نيمفينبورغ بميونخ", en: "The best things to do at Nymphenburg Palace" },
      {
        type: "LIST",
        ar: [
          "ابدأ بجولة مبدئية في أرجاء المكان ، وستستمتع خلالها بمشاهدة الطراز المعماري الذي يتزين به القصر من الخارج",
          "من أجل توثيق ذكرى زيارة هذا المكان ستجد أنه من المتاح لك ولجميع الزوار التقاط بعض الصور التذكارية في جميع أرجاء المكان",
          "حينما تتعرف على القصر من الداخل سوف ترى جميع التفاصيل الموجودة بداخله ، ولن تفوت رؤية غرف القصر التي جُهّز بعضها كغرف ملكية ومجموعة أخرى للخدم وعددا آخر منها لاستقبال الضيوف",
          "ما يميز هذا القصر صالة الاستقبال الموجودة بداخله والتي صممت بذوق مميز ينعكس في الزخارف والنقوش التي تزين جدرانها والثريات الثمينة التي تعتلي أسقفها",
          "تعكس قطع الأثاث الموجودة في القصر لمسات من الفن القديم ، فهناك أثاث على النمط الباروكي وكذلك على الطراز الكلاسيكي",
          "جولتك في القصر سوف تخولك من مشاهدة عدد من الآثار الفنية المتنوعة مثل التماثيل والمنحوتات ومجموعة من اللوحات الفنية لأبرز الرسامين",
          "من المسموح لكافة زوار قصر نيمفينبورغ بالتنزه في الحديقة المحيطة بالقصر والاستمتاع بجمالها",
        ],
        en: [
          "Begin with an initial walk around the grounds, enjoying the architecture that adorns the palace from outside.",
          "To record your visit, you and every visitor may take photographs throughout the grounds.",
          "Once inside, you will see every detail the palace holds, and you will not want to miss the rooms — some fitted out as royal chambers, others for servants and a number for receiving guests.",
          "What sets this palace apart is its reception hall, designed with distinctive taste reflected in the ornament and carving on its walls and the precious chandeliers on its ceilings.",
          "The furniture in the palace carries touches of older art, with both Baroque and Classical pieces.",
          "Your tour lets you see a range of artistic treasures such as statues, sculptures and a collection of paintings by leading artists.",
          "All visitors may stroll through the garden surrounding the palace and enjoy its beauty.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3524-1.jpg"), cap_ar: "واجهة القصر", cap_en: "The palace façade" },
      { type: "IMG", src: U("2022/09/img_3532-1.jpg"), cap_ar: "من داخل القصر", cap_en: "Inside the palace" },
      { type: "H3", ar: "عنوان ومواعيد عمل وسعر تذكرة قصر نيمفينبورغ بميونخ", en: "Address, opening hours and ticket price of Nymphenburg Palace" },
      { type: "P", ar: "يقع القصر في منطقة نويهاوزن نيمفينبورغ غرب مدينة ميونخ ، ويمكن الوصول اليه بسهولة بواسطة الترام ، والحديقة المحيطة بالقصر مفتوحة للجمهور", en: "The palace lies in the Neuhausen-Nymphenburg district west of Munich and is easily reached by tram; the garden surrounding it is open to the public." },
    ],
  },
  {
    slug: "olympic-park",
    title_ar: "الحديقة الاولمبية .. ايقونة السياحة في ميونخ",
    title_en: "The Olympic Park — an icon of tourism in Munich",
    kicker_ar: "معالم ميونخ",
    kicker_en: "Munich landmarks",
    image: U("2022/09/img_3539.jpg"),
    blocks: [
      { type: "P", ar: "الحديقة الأولمبية في ميونيخ هي حديقة أولمبية شيدت لدورة الألعاب الأولمبية الصيفية لعام 1972 ، تقع الحديقة في حي Oberwiesenfeld وتواصل العمل كمكان للمناسبات الثقافية والاجتماعية والدينية", en: "The Olympic Park in Munich was built for the 1972 Summer Olympic Games. It lies in the Oberwiesenfeld district and continues to serve as a venue for cultural, social and religious events." },
      { type: "P", ar: "تتميز الحديقة الاولمبية بهندستها المعمارية التي تميزها عن العديد من المواقع الأولمبية الأخرى ، فانها فريدة من نوعها وكل عام يأتي اليها ما يقارب أربعة ملايين شخص لممارسة الرياضة أو للاستمتاع بالمعالم السياحية أو لمشاهدة العديد من الأحداث ووسائل الترفيه ، كل هذا جعلها من افضل اماكن السياحة في ميونخ", en: "The Olympic Park stands out for architecture that distinguishes it from many other Olympic sites — it is truly unique. Every year some four million people come to play sport, to enjoy the sights or to watch its many events and entertainment, all of which makes it one of the best places to visit in Munich." },
      { type: "IMG", src: U("2022/09/img_3540.jpg"), cap_ar: "الحديقة الاولمبية", cap_en: "The Olympic Park" },
      { type: "P", ar: "الملعب الاولمبي .. هو مكان مميز وفريد بفضل بنائه المذهل تحت سقف أيقوني ، وليس فقط المحور المعماري للحديقة الأولمبية بل كان دائما المكان الأكثر أهمية لأكبر وأعظم الأحداث في الرياضة ، منذ افتتاحه رسميا في 26 مايو 1972 وهو من تصميم المعماري الألماني فراي أوتو", en: "The Olympic Stadium is a distinctive, unique place thanks to its astonishing structure beneath an iconic roof. It is not only the architectural axis of the Olympic Park but has always been the most important venue for the greatest events in sport, since it opened officially on 26 May 1972; it was designed by the German architect Frei Otto." },
      { type: "P", ar: "ومن حيث الثقافة لا يزال الاستاد الأولمبي أحد أهم المواقع في ألمانيا ورائدتها ، فقد قدم روبي وليامز وجينيسيس ومايكل جاكسون والرولينغ ستونز وبروس سبرينغستين والتينورات الثلاثة والعديد من نجوم العالم الآخرين حفلات موسيقية رائعة في الهواء الطلق أمام جمهور تم بيع التذاكر فيها بالكامل", en: "Culturally, the Olympic Stadium remains one of Germany's leading venues: Robbie Williams, Genesis, Michael Jackson, the Rolling Stones, Bruce Springsteen, the Three Tenors and many other world stars have given superb open-air concerts there to sold-out crowds." },
      { type: "IMG", src: U("2022/09/img_3541.jpg"), cap_ar: "الملعب الاولمبي", cap_en: "The Olympic Stadium" },
      { type: "IMG", src: U("2022/09/img_3542.jpg"), cap_ar: "سقف الملعب الأيقوني", cap_en: "The stadium's iconic roof" },
      { type: "IMG", src: U("2022/09/img_3543.jpg"), cap_ar: "البرج الاولمبي", cap_en: "The Olympic Tower" },
      { type: "P", ar: "يقع البرج الاولمبي في الحديقة الاولمبية بمدينة ميونخ ، ويبلغ ارتفاعه 290 مترا ، كما ويوجد في اعلى البرج مطعم دوار ، ويوفر البرج اطلالة بانورامية على كل من الحديقة الاولمبية ومدينة ميونخ وجبال الألب ، كما ويتوفر متجر يبيع الهدايا التذكارية عند مدخل البرج", en: "The Olympic Tower stands in the Olympic Park and is 290 metres high, with a revolving restaurant at the top. It offers panoramic views over the Olympic Park, the city of Munich and the Alps, and a souvenir shop sits at its entrance." },
      { type: "P", ar: "منذ افتتاحه في عام 1968 سجل البرج اكثر من 35 مليون زائر ، واعتبارا من عام 2004 وعلى ارتفاع 182 متر هناك مطعم دوار يتسع الى 230 شخصا ، ويعمل البرج ايضا كبرج اذاعي", en: "Since it opened in 1968 the tower has recorded more than 35 million visitors. Since 2004, at a height of 182 metres, there has been a revolving restaurant seating 230 people, and the tower also works as a broadcasting mast." },
      { type: "P", ar: "يتميز البرج بالحياة العصرية والكلاسيكية والاثرية لمدينة ميونخ ، حيث يشاهد الزوار القطع الفنية التي ترجع الى آلاف السنين والمقتنيات الاثرية التي تضفي من العبق التاريخي على البرج ، ويعتبر من المعالم الواضحة والمميزة في ميونخ", en: "The tower brings together the modern, classical and historic life of Munich: visitors see artworks going back thousands of years and antiquities that lend it a historic air, and it is one of the city's clearest, most distinctive landmarks." },
      { type: "IMG", src: U("2022/09/img_3544.jpg"), cap_ar: "الاطلالة من البرج", cap_en: "The view from the tower" },
      { type: "H3", ar: "أفضل الانشطة التي يمكن القيام بها في الحديقة الاولمبية بميونخ", en: "The best things to do at the Olympic Park" },
      {
        type: "LIST",
        ar: [
          "زيارة الملعب الاولمبي ومشاهدة سقفه الأيقوني وحضور ما يُقام فيه من أحداث رياضية وحفلات",
          "الصعود الى البرج الاولمبي والاستمتاع بالاطلالة البانورامية على ميونخ وجبال الألب ، وتناول الطعام في المطعم الدوار",
          "التنزه في مساحات الحديقة الخضراء وحول بحيرتها وممارسة الرياضة فيها",
        ],
        en: [
          "Visit the Olympic Stadium, see its iconic roof and attend the sporting events and concerts held there.",
          "Go up the Olympic Tower to enjoy the panoramic view over Munich and the Alps, and eat in the revolving restaurant.",
          "Stroll through the park's green spaces and around its lake, and play sport there.",
        ],
      },
      { type: "IMG", src: U("2022/09/img_3545.jpg"), cap_ar: "بحيرة الحديقة الاولمبية", cap_en: "The Olympic Park lake" },
      { type: "H3", ar: "اوقات عمل واسعار تذاكر الحديقة الاولمبية بميونخ", en: "Opening hours and ticket prices of the Olympic Park" },
      { type: "P", ar: "الحديقة مفتوحة للزوار على مدار العام ، أما البرج الاولمبي فيفتح يوميا وتُشترى تذكرة الصعود اليه من مدخل البرج", en: "The park is open to visitors all year round; the Olympic Tower opens daily and a ticket for the ascent is bought at the tower entrance." },
    ],
  },
];
