import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

const in_briefGuide: Guide = {
  slug: "in-brief",
  title_ar: "المغرب باختصار",
  title_en: "Morocco in brief",
  kicker_ar: "ثقافة",
  kicker_en: "Culture",
  image: U("2022/05/img_6600.jpg"),
  blocks: [
    { type: "H3", ar: "المغرب باختصار", en: "Morocco in Brief", noNumber: true },
    { type: "IMG", src: U("2022/05/img_6600.jpg"), cap_ar: "المغرب باختصار", cap_en: "Morocco in Brief" },
    { type: "H3", ar: "حضارة .. عراقة .. مستقبل مشرق", en: "Civilization... Heritage... A Bright Future", noNumber: true },
    { type: "H3", ar: "تقاليد راسخة", en: "Deep-Rooted Traditions", noNumber: true },
    { type: "P", ar: "المغرب بلد متعدد في مكوناته القومية واللغوية والثقافية ويتميز بموروث من التقاليد المتناقلة من جيل الى جيل ، فلا شيء ثابت في المملكة ، حتى الثقافة حية وتنبض يوما بعد يوم في ايماءات يومية بسيطة ، في الحفلات أو الطقوس أو ببساطة العادات اليومية ، ابق هناك لفترة من الوقت واستمتع بفن العيش بأسلوب مغربي", en: "Morocco is a country of diverse ethnic, linguistic, and cultural components, characterized by a heritage of traditions passed from one generation to the next. Nothing is static in the Kingdom; even the culture is alive, pulsating day after day through simple daily gestures, celebrations, rituals, or simply daily customs. Stay for a while and enjoy the Moroccan art of living." },
    { type: "H3", ar: "ثقافات حية", en: "Living Cultures", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4459.jpg"), cap_ar: "ثقافات حية", cap_en: "Living Cultures" },
    { type: "P", ar: "لتغمر نفسك في الثقافة والتقاليد المغربية ، فان المدن العتيقة هي الوجهة المثالية ، من خلال تقاطع شوارع كل مدينة ، ستغمر نفسك في تفاصيل الحياة اليومية للمغاربة ، يتطور المغرب وسكانه على ايقاع نمط الحياة منطقة البحر الأبيض المتوسط المعترف بها من قبل اليونسكو ، انها مجموعة من الممارسات والأطباق ، والرمزية التي تضفي سحرا مميزا ، شاي في كل وقت ، لمة حول الكسكس والطاجين ، تجارة في الحرف التقليدية ، تضامن وطيد ، ستغادر مع حقيبة مليئة بالذكريات التي لاتنسى", en: "To immerse yourself in Moroccan culture and traditions, the ancient medinas are the perfect destination. In the maze-like streets of each city, you will be enveloped in the details of daily Moroccan life. Morocco and its people evolve to the rhythm of the Mediterranean lifestyle, recognized by UNESCO. It's a collection of practices, dishes, and symbolism that adds a special charm: tea at all hours, gatherings around couscous and tagine, trade in traditional crafts, and strong solidarity. You will leave with a suitcase full of unforgettable memories." },
    { type: "H3", ar: "احتفالات فريدة", en: "Unique Festivities", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4458.jpg"), cap_ar: "احتفالات فريدة", cap_en: "Unique Festivities" },
    { type: "P", ar: "تقام العديد من التظاهرات الثقافية ، الفنية والاحتفالات الدينية في جميع مدن المغرب ، التي توضح بشكل مثالي التقاليد المغربية ، يشتهر المغرب بمواسمه ومهرجاناته ذات الصيت العالمي ، فلا تفوت موسم طانطان المشهور والمسجل منذ عام 2008 على القائمة التمثيلية للتراث الثقافي غير المادي للبشرية ومهرجان حب الملوك (الكرز) في مدينة صفرو ، وموسم الورود بقلعة مكونة أو مهرجان كناوة في الصويرة ، فلديك كل ما يلزم لاسعاد نفسك على الطراز المغربي", en: "Numerous cultural, artistic, and religious events are held in all of Morocco's cities, perfectly showcasing Moroccan traditions. Morocco is famous for its world-renowned moussems (festivals). Don't miss the famous Tan-Tan Moussem, inscribed since 2008 on the Representative List of the Intangible Cultural Heritage of Humanity, the Cherry Festival in Sefrou, the Rose Festival in Kelaat M'Gouna, or the Gnaoua Festival in Essaouira. You'll have everything you need to enjoy yourself, Moroccan style." },
    { type: "H3", ar: "موسيقى كناوة", en: "Gnaoua Music", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4460.jpg"), cap_ar: "موسيقى كناوة", cap_en: "Gnaoua Music" },
    { type: "P", ar: "تسافر بنا موسيقى كناوة في رحلة روحية ثقافية ، صنفت موسيقى كناوة في عام 2019 ضمن قائمة التراث الثقافي غير المادي للبشرية لليونسكو ، وهذا الفن دخل المغرب من خلال عبيد استقدموا من أفريقيا جنوب الصحراء الى المغرب ، وهو مزيج من طقوس تجمع بين الغناء والرقص ، وهي تدفعنا الى الرقص والتماهي مع الايقاعات القوية ، وترتدي فرقة الكناوة أزياء ملونة ويعزف الكناويون موسيقاهم بآلتين أساسيتين : القراقب والكمبري ، وقد ساهم فنانون كبار قدموا من أنحاء العالم مثل ليد زيبلين Led Zeppelin ، بات ميثيني Pat Metheny ، ديدييه لوكوود Didier Lockwood أو ماركوس ميللر Marcus Miller في اعطاء اشعاع وانتعاشة جديدين لهذا الفن بتقديمهم لعروض خاصة بجانب الكناويون", en: "Gnaoua music takes us on a spiritual and cultural journey. In 2019, it was added to UNESCO's Representative List of the Intangible Cultural Heritage of Humanity. This art form came to Morocco with enslaved people brought from sub-Saharan Africa. It is a blend of rituals combining song and dance, compelling listeners to move and become one with its powerful rhythms. The Gnaoua troupes wear colorful costumes, and the musicians play two main instruments: the 'krakebs' (large iron castanets) and the 'guembri' (a three-stringed bass lute). Great artists from around the world, like Led Zeppelin, Pat Metheny, Didier Lockwood, and Marcus Miller, have contributed to its global reach and revival by performing alongside Gnaoua masters." },
    { type: "H3", ar: "مدن قديمة وعتيقة", en: "Old and Ancient Cities", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4456.jpg"), cap_ar: "مدن قديمة وعتيقة", cap_en: "Old and Ancient Cities" },
    { type: "P", ar: "تجولوا في المدن المغربية وهي قلبها النابض ، لتكتشفوا طابعها السحري والمدهش الذي تتميز به ، في قلب مدن مغربية ، خلف اسوار حمراء عالية ، كنوز تغوص بكم في تاريخ المغرب الأصيل ، تنبض الأحياء القديمة بسكانها الذين ينقلون معرفتهم من جيل الى جيل ، وتندرج مدن فاس وتطوان والصويرة ومراكش ضمن قائمة اليونسكو للتراث العالمي ، تعتبر مدينة فاس من أعرق المدن المغربية وأشهرها ، كما تعتبر تطوان والصويرة والرباط من أبرز المدن المغربية التي تستحق الزيارة ، امبريالية ، ساحلية أو واقعة على منحدرات الجبال ، سوف تتيح لك السفر عبر الزمن ، اكتشفوا هذه الأحياء القديمة ، وتمتعوا بدفء الأزقة وسكانها", en: "Wander through the Moroccan medinas, the beating heart of the cities, to discover their magical and astonishing character. In the heart of Moroccan cities, behind high red ramparts, lie treasures that immerse you in Morocco's authentic history. The old quarters pulse with their inhabitants, who pass their knowledge from one generation to the next. The medinas of Fes, Tetouan, Essaouira, and Marrakesh are on the UNESCO World Heritage list. Fes is one of the oldest and most famous Moroccan cities, while Tetouan, Essaouira, and Rabat are also prominent cities well worth a visit. Whether imperial, coastal, or perched on mountain slopes, they allow you to travel back in time. Discover these ancient quarters and enjoy the warmth of the alleyways and their people." },
    { type: "IMG", src: U("2022/10/img_4457.jpg"), cap_ar: "مدن قديمة وعتيقة", cap_en: "Old and Ancient Cities" },
  ],
};

const programGuide: Guide = {
  slug: "program",
  title_ar: "تعرف على البرنامج السياحي المعد للمغرب",
  title_en: "The travel program prepared for Morocco",
  kicker_ar: "برنامج سياحي",
  kicker_en: "Itinerary",
  image: U("2022/10/img_4493.jpg"),
  blocks: [
    { type: "IMG", src: U("2022/10/img_4493.jpg"), cap_ar: "أزقة المغرب الزرقاء", cap_en: "Morocco's blue alleys", size: "compact" },
    { type: "P", ar: "لمحبي السياحة والسفر اقدم لكم برنامج سياحي لمدة 7 أيام ، متمنيا ان يكون غني ومثمر بوجود الكثير من الأماكن السياحية الرائعة والمميزة التي يمكنكم زيارتها خلال هذه الايام", en: "For travel and tourism enthusiasts, here is a 7-day itinerary packed with wonderful and unique tourist attractions for you to visit, promising a rich and rewarding trip." },
    { type: "P", ar: "فالمملكة المغربية تعد من الدول السياحية التي اكتملت فيها معالم السحر والجمال لتكون في مقدمة الدول السياحية التي يقصدها الكثير من السياح ، أتمنى ان تتعرفوا على أجمل أماكنها وملامحها الفاتنة والتي تتنوع بين الطبيعية والتاريخية والثقافية والسياحية والترفيهية مما سيوفر لكم اقامة سعيدة ومميزة باذن الله ، فهذه الرحلة المتجهة الى بعض المدن مليئة بالمرح العائلي وتضم أشهر الوجهات عند العرب", en: "The Kingdom of Morocco is a premier tourist destination where the elements of charm and beauty converge, placing it at the forefront of countries sought by many tourists. We hope you will discover its most beautiful sites and enchanting features, which range from natural and historical to cultural and recreational, promising a happy and memorable stay, God willing. This journey to several cities is filled with family fun and includes some of the most famous destinations for Arab travelers." },
    { type: "H3", ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes.", noNumber: true },
    { type: "P", ar: "المدن الامبراطورية تاريخها وآثارها التي تعود الى ألف عام ، ارث من السلالات الماضية المجيدة ، انطلق في جولة لمدة سبعة أيام واكتشف سحرها وغموضها", en: "The Imperial Cities boast a history and monuments stretching back a thousand years, a legacy of glorious past dynasties. Embark on a seven-day tour to discover their charm and mystery." },
    { type: "P", ar: "خطوة بخطوة .. ستزور أربع من أجمل مدن المغرب ، فعند وصولك الى مراكش ، انطلق على الفور لاستكشاف المدينة الحمراء وكنوزها المعمارية : مسجد الكتبية ، ضريح السعديين ، حينها ستكتشف العادات والحرف المحلية في المدينة العتيقة", en: "Step by step, you will visit four of Morocco's most beautiful cities. Upon arriving in Marrakesh, you will immediately set off to explore the Red City and its architectural treasures: the Koutoubia Mosque and the Saadian Tombs. You'll then discover the local customs and crafts in the old medina." },
    { type: "IMG", src: U("2022/10/img_4501.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4500.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4499.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "P", ar: "الرباط ستكون هي وجهتك القادمة ، فدائما ما ترحب العاصمة التي تطل على المحيط بزوارها الكرام ، فعند وصولك قم بجولة في أزقتها التي تحدها أشجار النخيل ، واستمتع بمشاهدة ضريح محمد الخامس ، والصومعة التي تعد من الآثار التاريخية الراسخة", en: "Rabat will be your next destination. The oceanfront capital always extends a warm welcome to its visitors. Upon arrival, take a tour of its palm-lined alleys and enjoy the sights of the Mausoleum of Mohammed V and the Hassan Tower, one of its enduring historical monuments." },
    { type: "IMG", src: U("2022/10/img_4504.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4503.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4502.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "P", ar: "وستنتهي رحلتك بزيارة مديني فاس ومكناس ، وكلتاهما تتميزان بمناظر خلابة ، وكلتاهما فريد من نوعه ، فمدينة فاس هي العاصمة الروحية للمملكة المغربية ، وهي مدينة غامضة تم تصنيفها من قبل اليونسكو على انها تراث عالمي ، ومدينة مكناس فهي مدينة السلطان مولاي اسماعيل ، وهي مكان ساحر يرمز اليه ببوابة باب المنصور", en: "Your journey will conclude with a visit to the cities of Fes and Meknes. Both boast stunning scenery, and each is unique in its own right. Fes, the spiritual capital of the Kingdom of Morocco, is a mysterious city designated as a UNESCO World Heritage site. Meknes, the city of Sultan Moulay Ismail, is an enchanting place symbolized by the monumental Bab Mansour gate." },
    { type: "IMG", src: U("2022/10/img_4507.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4506.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4505.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4510.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4509.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4508.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "P", ar: "بالتأكيد تستوجب زيارة المدن الأربع المذكورة في فترة اسبوع ، مراحل عديدة وقطع مسافات وترتيب جيد قبل السفر ، لكن السفر اليهم يحتوي أيضا على بعض المفاجآت ، ففي المغرب تخفي العديد من المناطق والمدن كنوزا قيمة ، ولا تزال حول فاس ومكناس أنقاض مدينة وليلي الرومانية القديمة ، وهناك أيضا افران الملقبة بسويسرا الصغيرة", en: "Visiting these four cities in one week certainly requires careful planning, multiple stops, and covering significant distances. However, the journey also holds some surprises. Many of Morocco's regions and cities hide precious treasures. Near Fes and Meknes lie the ruins of the ancient Roman city of Volubilis, and there's also Ifrane, nicknamed 'Little Switzerland'." },
    { type: "P", ar: "أخيرا فان مدينة الدار البيضاء (كازابلانكا) ، والتي هي ليست ببعيدة عن الرباط ومراكش ، ستكشف لك عن سحرها وتاريخها ايضا ، فان توفر لك الوقت ، فأنطلق اليها في رحلة استكشافية سريعة ، واستمتع بمغرب الأصالة والتقاليد ، والبلد الذي له تاريخ غني ومتنوع للغاية", en: "Finally, the city of Casablanca, not far from Rabat and Marrakesh, will also reveal its charm and history to you. If you have the time, embark on a quick exploratory trip and enjoy a Morocco of authenticity and tradition—a country with an exceptionally rich and diverse history." },
    { type: "IMG", src: U("2022/10/img_4514.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4513.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
    { type: "IMG", src: U("2022/10/img_4512.jpg"), cap_ar: "سافر عبر الزمن من خلال زيارة المدن الامبراطورية الأربع للمغرب العتيق ، لاكتشاف حضارة وثقافة وتاريخ وتراث غني ومتنوع لمدن : مراكش ، الرباط ، فاس ، ومكناس", cap_en: "Travel through time by visiting the four Imperial Cities of old Morocco to discover the rich and diverse civilization, culture, history, and heritage of Marrakesh, Rabat, Fes, and Meknes." },
  ],
};

const hammamGuide: Guide = {
  slug: "hammam",
  title_ar: "الحمام المغربي صحة وعافية للجسم",
  title_en: "The Moroccan hammam: health and wellbeing",
  kicker_ar: "عافية",
  kicker_en: "Wellbeing",
  image: U("2022/10/img_4544.jpg"),
  blocks: [
    { type: "H3", ar: "الحمام المغربي .. صحة وعافية ونقاوة جسم", en: "The Moroccan Hammam: Health, Wellness, and Body Purity", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4544.jpg"), cap_ar: "الحمام المغربي .. صحة وعافية ونقاوة جسم", cap_en: "The Moroccan Hammam: Health, Wellness, and Body Purity" },
    { type: "H3", ar: "الحمام المغربي التقليدي هو عبارة عن حمام بخار ساخن (حوالي 50 درجة مئوية) ورطب (رطوبة 100٪)", en: "The traditional Moroccan hammam is a hot steam bath (around 50°C) with high humidity (100%).", noNumber: true },
    { type: "P", ar: "منذ قرون والمغاربة يقصدون أسبوعيا الحمام المغربي الشعبي حتى يومنا الحاضر ، لتميزه في تنظيف وتقشير البشرة ، بالاضافة الى أنه ملتقى للعائلة والأصدقاء ، وطقوس الزفاف ، وعادة ما تبدأ طقوسه بنقع الجسم بالماء الساخن ، ثم وضع غسول الطين المغربي ، وبعدها الاستحمام بالصابون المغربي ذي اللون الأسود الذي يتميز عن غيره من أنواع الصابون ، ثم الاستحمام بالماء البارد لاغلاق المسام ، وقد يتبادر الى الذهن بعض التساؤلات حول الاختلاف بين الحمام المغربي ، والحمام التركي ، والفرق بينهما هو أن الحمام المغربي يتميز بتنظيف البشرة بالبخار ، والصابون الأسود ، أما الحمام التركي يستخدم الماء بدلا من البخار ، ويتميز بالبلاط الساخن ، والاسترخاء ، وهو مناسب للذين لا يفضلون علاج البخار ، ويتشابه الحمام التركي والمغربي في فعالية تنظيف البشرة والاسترخاء", en: "For centuries, Moroccans have visited the public hammam weekly, a tradition that continues to this day, renowned for its ability to cleanse and exfoliate the skin. It is also a meeting place for family and friends and a key part of wedding rituals. The experience typically begins with soaking the body in hot water, followed by an application of Moroccan rhassoul clay. Next comes a wash with the distinctive black Moroccan soap, and the ritual finishes with a cold water rinse to close the pores. One might wonder about the difference between the Moroccan and Turkish hammams. The key distinction is that the Moroccan hammam focuses on deep cleansing using steam and black soap, while the Turkish hammam uses running water instead of steam and is characterized by heated tiles and relaxation, making it suitable for those who do not prefer a steam treatment. However, both are highly effective for skin cleansing and relaxation." },
    { type: "H3", ar: "فوائد الحمام المغربي", en: "Benefits of the Moroccan Hammam", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4556.jpg"), cap_ar: "فوائد الحمام المغربي", cap_en: "Benefits of the Moroccan Hammam" },
    { type: "IMG", src: U("2022/10/img_4557.jpg"), cap_ar: "فوائد الحمام المغربي", cap_en: "Benefits of the Moroccan Hammam" },
    { type: "P", ar: "هناك العديد من الفوائد للجسم والبشرة عند عمل الحمام المغربي ومنها التالي", en: "The Moroccan hammam offers numerous benefits for the body and skin, including the following:" },
    { type: "H3", ar: "مميزات الحمام المغربي", en: "Features of the Moroccan Hammam", noNumber: true },
    { type: "P", ar: "هناك العديد من المميزات للحمام المغربي ومنها", en: "The Moroccan hammam has several distinct features, including:" },
    { type: "H3", ar: "طقوس الحمام في العرس المغربي", en: "Hammam Rituals in a Moroccan Wedding", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4558.jpg"), cap_ar: "طقوس الحمام في العرس المغربي", cap_en: "Hammam Rituals in a Moroccan Wedding" },
    { type: "IMG", src: U("2022/10/img_4543.png"), cap_ar: "طقوس الحمام في العرس المغربي", cap_en: "Hammam Rituals in a Moroccan Wedding" },
    { type: "IMG", src: U("2022/10/img_4559.jpg"), cap_ar: "طقوس الحمام في العرس المغربي", cap_en: "Hammam Rituals in a Moroccan Wedding" },
    { type: "H3", ar: "هندسة الحمام المغربي", en: "The Architecture of the Moroccan Hammam", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4542.jpg"), cap_ar: "هندسة الحمام المغربي", cap_en: "The Architecture of the Moroccan Hammam" },
    { type: "H3", ar: "المصطلحات الخاصة بالحمام المغربي", en: "Moroccan Hammam Terminology", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4544-1.jpg"), cap_ar: "المصطلحات الخاصة بالحمام المغربي", cap_en: "Moroccan Hammam Terminology" },
  ],
};

const breedsGuide: Guide = {
  slug: "breeds",
  title_ar: "تعرف على سلالات المغرب",
  title_en: "The breeds of Morocco",
  kicker_ar: "طبيعة",
  kicker_en: "Nature",
  image: U("2022/03/img_3565.jpg"),
  blocks: [
    { type: "H3", ar: "المغرب .. بوتقة بين السلالات والثقافات", en: "Morocco: A Melting Pot of Dynasties and Cultures", noNumber: true },
    { type: "P", ar: "لكل دولة تاريخها الخاص حقائق وأحداث ومراحل تاريخية تم الابلاغ عنها حتى الآن لاعطاء البلد المعني قيمته التاريخية ، ان تاريخ البلد هو أحد الأحداث التي تعتبر جديرة بالذاكرة ، ولا يزال تاريخ المغرب هو النموذج المثالي ، مع العديد من السلالات المتتالية عبر عدة سنوات : سلالة الأدارسة ، سلالة المرابطين ، سلالة الموحدين ، سلالة المرينيين ، سلالة السعديين وسلالة العلويين ، يعتبر المغرب دولة متعددة الثقافات معترف به دوليا ، مع أنواع متعددة من التراث المعترف به من قبل التراث العالمي لليونسكو", en: "Every country has its own history—facts, events, and historical periods that have been chronicled to give the nation its historical significance. A country's history is a story worth remembering, and Morocco's is a prime example. With its many successive dynasties over the centuries—the Idrisid, Almoravid, Almohad, Marinid, Saadi, and Alaouite dynasties—Morocco is an internationally recognized multicultural nation, boasting various forms of heritage recognized by UNESCO World Heritage." },
    { type: "P", ar: "المغرب هو أحد الوجهات المفضلة للسياح الأجانب ، لعشاق الاكتشاف ، والأكثر اهتماما بالطبيعة والتاريخ وفن العيش والضيافة المغربية ، والتجربة المعاشة خلال رحلاتهم في المغرب والتي تجعلهم يغادرونه وهم راضون عن اقامتهم به", en: "Morocco is a favorite destination for international tourists, for lovers of discovery, and for those interested in nature, history, the Moroccan art of living, and hospitality. The experience of traveling through Morocco leaves visitors satisfied with their stay." },
    { type: "H3", ar: "سلالة الأدارسة", en: "The Idrisid Dynasty", noNumber: true },
    { type: "H3", ar: "سلالة المرابطين", en: "The Almoravid Dynasty", noNumber: true },
    { type: "H3", ar: "سلالة الموحدين", en: "The Almohad Dynasty", noNumber: true },
    { type: "H3", ar: "سلالة المرينيين", en: "The Marinid Dynasty", noNumber: true },
    { type: "H3", ar: "سلالة السعديين أو الزيدانيين", en: "The Saadi or Zaydanid Dynasty", noNumber: true },
    { type: "H3", ar: "سلالة العلويين", en: "The Alaouite Dynasty", noNumber: true },
  ],
};

const museumsGuide: Guide = {
  slug: "museums",
  title_ar: "تعرف على المتاحف بالمغرب",
  title_en: "The museums of Morocco",
  kicker_ar: "ثقافة",
  kicker_en: "Culture",
  image: U("2022/05/img_6600.jpg"),
  blocks: [
    { type: "IMG", src: U("2022/05/img_6600.jpg"), cap_ar: "", cap_en: "" },
    { type: "P", ar: "المغرب", en: "Morocco" },
    { type: "H3", ar: "تعرف على أشهر المتاحف بالمغرب", en: "Discover the Most Famous Museums in Morocco", noNumber: true },
    { type: "H3", ar: "المغرب بلد ذو ثقافة غنية", en: "Morocco, a country of rich culture", noNumber: true },
    { type: "P", ar: "أثناء اقامتك في المغرب ستكتشف التاريخ والعديد من الفنون ، ففي كل مكان تمتزج التأثيرات لتساهم في تكوين تراث غني ومتنوع من خلال المتاحف والمعارض الفنية ، التي لها دور كبير في الحفاظ عليه وتعزيزه وجعله في متناول الجميع ، فهناك عدد كبير من المدن المغربية مليئة بالكنوز الثقافية والأثرية والتراثية", en: "During your stay in Morocco, you will discover history and many forms of art. Everywhere, influences blend to form a rich and diverse heritage, largely preserved, promoted, and made accessible to all through its museums and art galleries. A great number of Moroccan cities are filled with cultural, archaeological, and heritage treasures." },
    { type: "H3", ar: "مدينة الرباط", en: "Rabat", noNumber: true },
    { type: "H3", ar: "بين التقاليد والحداثة", en: "Between Tradition and Modernity", noNumber: true },
    { type: "P", ar: "متحف محمد السادس .. واجهة من ابداعات الفن الحديث", en: "Mohammed VI Museum... A Showcase of Modern Art Creations" },
    { type: "P", ar: "متحف التاريخ والحضارات .. اثر كبير في تاريخ المغرب", en: "Museum of History and Civilizations... A Major Landmark in Morocco's History" },
    { type: "P", ar: "المدرسة المرينية بسلا .. ارث المرينيين", en: "The Marinid Madrasa of Salé... The Marinid Legacy" },
    { type: "H3", ar: "مدينة مراكش", en: "Marrakesh", noNumber: true },
    { type: "H3", ar: "امبراطورية ذات الثقافات المتنوعة", en: "An Empire of Diverse Cultures", noNumber: true },
    { type: "P", ar: "قصر الباهية .. تحفة معمارية مغربية", en: "Bahia Palace... A Moroccan Architectural Masterpiece" },
    { type: "P", ar: "متحف البربر .. الانعماس في الثقافة البربرية", en: "The Berber Museum... An Immersion into Berber Culture" },
    { type: "P", ar: "متحف اف سان لوران .. تكريم لمصمم الأزياء الشهير", en: "Yves Saint Laurent Museum... A Tribute to the Famous Fashion Designer" },
    { type: "H3", ar: "فاس", en: "Fes", noNumber: true },
    { type: "H3", ar: "عاصمة الفنون والحرف التقليدية", en: "The Capital of Arts and Traditional Crafts", noNumber: true },
    { type: "P", ar: "متحف البطحاء .. مجموعة من الكنوز اليدوية", en: "Batha Museum... A Collection of Handcrafted Treasures" },
    { type: "P", ar: "متحف الخشب .. متحف فن النجارين", en: "The Wood Museum... A Museum of the Art of Woodworking" },
    { type: "P", ar: "متحف دار بلغازي .. لمحة عن الثقافة الفاسية", en: "Dar Belghazi Museum... A Glimpse into Fassi Culture" },
    { type: "H3", ar: "مكناس", en: "Meknes", noNumber: true },
    { type: "H3", ar: "فرساي المغرب", en: "The Versailles of Morocco", noNumber: true },
    { type: "P", ar: "متحف دار الجامعي .. لمسة اسبانية مغاربية", en: "Dar Jamai Museum... A Hispano-Moorish Touch" },
    { type: "P", ar: "متحف بري بلقاري .. شهادة عن الخزف الريفي", en: "Borj Belqari Museum... A Testament to Rif Pottery" },
    { type: "P", ar: "متحف مكناس .. معرض للفنون والحرف المحلية", en: "Meknes Museum... An Exhibition of Local Arts and Crafts" },
    { type: "H3", ar: "آسفي", en: "Safi", noNumber: true },
    { type: "H3", ar: "مدينة الفخار والخزف", en: "City of Pottery and Ceramics", noNumber: true },
    { type: "P", ar: "المتحف الوطني للسيراميك .. موطن فن الخزف", en: "The National Ceramics Museum .. Home of the Art of Pottery" },
    { type: "H3", ar: "العيون", en: "Laayoune", noNumber: true },
    { type: "H3", ar: "حلقة وصل بين الصحراء والبحر", en: "A Link Between the Desert and the Sea", noNumber: true },
    { type: "P", ar: "متحف العيون .. تقرير للثقافات البدوية", en: "Laayoune Museum .. A Tribute to Bedouin Cultures" },
    { type: "H3", ar: "طنجة", en: "Tangier", noNumber: true },
    { type: "H3", ar: "مهد الثقافة المتوسطية", en: "Cradle of Mediterranean Culture", noNumber: true },
    { type: "P", ar: "متحف القصبة .. متحف للثقافات المتوسطية", en: "Kasbah Museum .. Museum of Mediterranean Cultures" },
  ],
};

const water_sportsGuide: Guide = {
  slug: "water-sports",
  title_ar: "تعرف على الرياضات والأنشطة البحرية بالمغرب",
  title_en: "Water sports and marine activities in Morocco",
  kicker_ar: "أنشطة",
  kicker_en: "Activities",
  image: U("2022/10/img_4519.jpg"),
  blocks: [
    { type: "H3", ar: "المغرب .. موطن الرياضات البحرية", en: "Morocco: A Haven for Water Sports", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4519.jpg"), cap_ar: "المغرب .. موطن الرياضات البحرية", cap_en: "Morocco: A Haven for Water Sports" },
    { type: "P", ar: "يقدم المغرب لعشاق الرياضات المائية أكثر من 3000 كيلومتر من الساحل ، فمن أمواج المحيط الأطلسي الى مساحات شاسعة من البحر الأبيض المتوسط ، حيث تمتد شواطئ يتم العناية بها على مدار السنة وهي تتوفر على جميع البنى التحتية من أجل أفضل اختيار للاستماع بالاجازات والمرح ، فتمتعوا بقدر أكبر من الاسترخاء وممارسة الرياضة مع اطلالة مدهشة وفريدة على الشواطئ", en: "For water sports enthusiasts, Morocco offers over 3,000 kilometers of coastline, from the waves of the Atlantic Ocean to the vast expanses of the Mediterranean Sea. Here, well-maintained beaches stretch out year-round, equipped with all the necessary infrastructure for a perfect, fun-filled vacation. Enjoy ultimate relaxation and exhilarating sports with stunning and unique views of the shores." },
    { type: "H3", ar: "ركوب الأمواج والرياضات الأخرى على شواطئ المغرب الجميلة", en: "Surfing and Other Sports on Morocco's Beautiful Beaches", noNumber: true },
    { type: "H3", ar: "الجت سكي والتجذيف والركمجة", en: "Jet Skiing, Paddling, and Surfing", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4516.jpg"), cap_ar: "الجت سكي والتجذيف والركمجة", cap_en: "Jet Skiing, Paddling, and Surfing" },
    { type: "H3", ar: "على سواحل المحيط الأطلسي والبحر الأبيض المتوسط", en: "On the coasts of the Atlantic Ocean and the Mediterranean Sea", noNumber: true },
    { type: "H3", ar: "الغطس والصيد للجمع بين الرياضة والاكتشاف", en: "Diving and Fishing: Combining Sport and Discovery", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4517.jpg"), cap_ar: "الغطس والصيد للجمع بين الرياضة والاكتشاف", cap_en: "Diving and Fishing: Combining Sport and Discovery" },
    { type: "H3", ar: "المهرجان البحري الدولي بالربا", en: "The Rabat International Nautical Festival", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4520.jpg"), cap_ar: "المهرجان البحري الدولي بالربا", cap_en: "The Rabat International Nautical Festival" },
    { type: "IMG", src: U("2022/10/img_4518.jpg"), cap_ar: "المهرجان البحري الدولي بالربا", cap_en: "The Rabat International Nautical Festival" },
  ],
};

const productsGuide: Guide = {
  slug: "products",
  title_ar: "تعرف على ما تنتجه المغرب",
  title_en: "What Morocco produces",
  kicker_ar: "منتجات",
  kicker_en: "Products",
  image: U("2022/10/img_4524.jpg"),
  blocks: [
    { type: "H3", ar: "تعرف على ما تنتجه المغرب", en: "Discover Morocco's Products", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4524.jpg"), cap_ar: "تعرف على ما تنتجه المغرب", cap_en: "Discover Morocco's Products" },
    { type: "H3", ar: "المغرب غنى بمنتجاته المحلية", en: "Morocco is rich in local products", noNumber: true },
    { type: "P", ar: "يتميز المغرب بثرواته الطبيعية المتنوعة والمتعددة ، مما يجعل منه خزانة غنية بالمنتجات المحلية المتوارثة من جيل لآخر مثل : التوابل كالزعفران وتسمى أيضا “الذهب الأحمر” ، وزيت الزيتون ، وكذلك العسل وماء زهرة البرتقال ، دون نسيان زيت أركان ذو الطعم الرائع ، كما ويستخدم في طقوس الحمام المغربي الحناء وماء الورد والصابون الأسود والغسول ، فحبذا لو تأخذ معك واحدة من هذه الكنوز المغربية في أمتعتك وقت عودتك لوطنك", en: "Morocco is distinguished by its diverse and abundant natural resources, making it a rich treasure trove of local products passed down from one generation to the next. These include spices like saffron, also known as \"red gold,\" olive oil, honey, and orange blossom water, not to mention the wonderfully flavored argan oil. Henna, rose water, black soap, and ghassoul clay are also used in Moroccan hammam rituals. Be sure to pack one of these Moroccan treasures in your luggage to take home with you." },
    { type: "H3", ar: "زيت الأركان", en: "Argan Oil", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4521.jpg"), cap_ar: "زيت الأركان", cap_en: "Argan Oil" },
    { type: "IMG", src: U("2022/10/img_4522.jpg"), cap_ar: "زيت الأركان", cap_en: "Argan Oil" },
    { type: "IMG", src: U("2022/10/img_4523.jpg"), cap_ar: "زيت الأركان", cap_en: "Argan Oil" },
    { type: "P", ar: "فوائد زيت الأركان", en: "Benefits of Argan Oil" },
    { type: "H3", ar: "الزعفران", en: "Saffron", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4525.jpg"), cap_ar: "الزعفران", cap_en: "Saffron" },
    { type: "IMG", src: U("2022/10/img_4526.jpg"), cap_ar: "الزعفران", cap_en: "Saffron" },
    { type: "IMG", src: U("2022/10/img_4524.jpg"), cap_ar: "الزعفران", cap_en: "Saffron" },
    { type: "P", ar: "استعمالات الزعفران", en: "Uses of Saffron" },
    { type: "H3", ar: "التين الشوكي", en: "Prickly Pear", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4529.jpg"), cap_ar: "التين الشوكي", cap_en: "Prickly Pear" },
    { type: "IMG", src: U("2022/10/img_4528.jpg"), cap_ar: "التين الشوكي", cap_en: "Prickly Pear" },
    { type: "IMG", src: U("2022/10/img_4527.jpg"), cap_ar: "التين الشوكي", cap_en: "Prickly Pear" },
    { type: "P", ar: "فوائد التين الشوكي", en: "Benefits of Prickly Pear" },
    { type: "H3", ar: "ماء الورد", en: "Rose Water", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4531.jpg"), cap_ar: "ماء الورد", cap_en: "Rose Water" },
    { type: "IMG", src: U("2022/10/image-12.jpg"), cap_ar: "ماء الورد", cap_en: "Rose Water" },
    { type: "IMG", src: U("2022/10/img_4530.jpg"), cap_ar: "ماء الورد", cap_en: "Rose Water" },
    { type: "P", ar: "فوائد استخدام ماء الورد المغربي الطبيعي للبشرة والوجه :", en: "Benefits of using natural Moroccan rose water for the skin and face:" },
    { type: "H3", ar: "ماء زهرة البرتقال", en: "Orange Blossom Water", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4534.jpg"), cap_ar: "ماء زهرة البرتقال", cap_en: "Orange Blossom Water" },
    { type: "IMG", src: U("2022/10/img_4533.jpg"), cap_ar: "ماء زهرة البرتقال", cap_en: "Orange Blossom Water" },
    { type: "IMG", src: U("2022/10/img_4535.jpg"), cap_ar: "ماء زهرة البرتقال", cap_en: "Orange Blossom Water" },
    { type: "P", ar: "استعمالات ماء زهرة البرتقال", en: "Uses of Orange Blossom Water" },
  ],
};

const clothingGuide: Guide = {
  slug: "clothing",
  title_ar: "أزياء مغربية",
  title_en: "Moroccan clothing",
  kicker_ar: "أزياء",
  kicker_en: "Fashion",
  image: U("2022/10/img_4560.jpg"),
  blocks: [
    { type: "H3", ar: "اللباس التقليدي المغربي", en: "Traditional Moroccan Clothing", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4560.jpg"), cap_ar: "اللباس التقليدي المغربي", cap_en: "Traditional Moroccan Clothing" },
    { type: "P", ar: "اللباس التقليدي المغربي هو مجموعة الألبسة التراثية والشعبية التي حافظ ومازال يحافظ عليها الشعب المغربي منذ القديم ، ويظهر على المغاربة بمختلف الأعمار من الرجال والنساء تشبثهم وفخرهم بالألبسة التقليدية خاصة في الأعراس والمناسبات ، ومما لا شك فيه ان الزي التقليدي هو جزء لا يتجزأ من التراث المغربي", en: "Traditional Moroccan clothing is a collection of heritage and folk garments that the Moroccan people have preserved since ancient times. Moroccans of all ages, both men and women, demonstrate their attachment and pride in their traditional attire, especially at weddings and special occasions. Without a doubt, traditional dress is an integral part of Moroccan heritage." },
    { type: "P", ar: "هذا التنوع الجميل في لباس المغرب التقليدي ، الذي يجمع بين طياته تشكيلة متنوعة من الثقافات ، تحكي تاريخا ، وتراث متنوعا ، ويعتز ويفتخر المغاربة بلباسهم التقليدي بصفة عامة وبالقفطان خاصة كأحد رموز الثقافة الشعبية الأصيلة ، ومهما تعددت أنواع الأثواب وجودتها تبقى للتكشيطة خاصيتها التي لا محيد عنها وهي مفخرة النساء من جميع الطبقات ، حيث تجد ان المغربيات ما زلن يفضلن اللجوء الى الخياط عوض التصميمات الحديثة", en: "This beautiful diversity in traditional Moroccan dress, which brings together a variety of cultures, tells a story of a rich and varied heritage. Moroccans take great pride in their traditional attire in general, and the Caftan in particular, as a symbol of authentic popular culture. Regardless of the many types and qualities of fabrics, the Takchita holds its own essential character and is a source of pride for women of all classes. You will find that Moroccan women still prefer to go to a tailor rather than opt for modern designs." },
    { type: "H3", ar: "ما يميز الخياطة التقليدية للقفطان المغربي", en: "What Distinguishes the Traditional Tailoring of the Moroccan Caftan", noNumber: true },
    { type: "H3", ar: "ما يميز اللباس التقليدي المغربي", en: "What Distinguishes Traditional Moroccan Clothing", noNumber: true },
    { type: "H3", ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", en: "Technique Used in Crafting Traditional Attire", noNumber: true },
    { type: "P", ar: "القفطان", en: "Caftan" },
    { type: "IMG", src: U("2022/10/img_4574.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "الجلابة", en: "Djellaba" },
    { type: "IMG", src: U("2022/10/img_4573.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "التكشيطة", en: "Takchita" },
    { type: "IMG", src: U("2022/10/img_4572.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "المضة", en: "M'damma" },
    { type: "IMG", src: U("2022/10/img_4571-1.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "الملحفة", en: "Malhafa" },
    { type: "IMG", src: U("2022/10/img_4570.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "الجابادور", en: "Jabador" },
    { type: "IMG", src: U("2022/10/img_4569.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "الكندورة", en: "Gandoura" },
    { type: "IMG", src: U("2022/10/img_4568.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "الشربيل", en: "Cherbil" },
    { type: "IMG", src: U("2022/10/img_4567.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "البرنوس او السلهام", en: "Burnous or Selham" },
    { type: "IMG", src: U("2022/10/img_4566.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Technique Used in Crafting Traditional Attire" },
    { type: "P", ar: "الحايك", en: "Haik" },
    { type: "IMG", src: U("2022/10/img_4565.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Traditional weaving technique" },
    { type: "P", ar: "البلوزة الوجدية", en: "Blouza Oujdia" },
    { type: "IMG", src: U("2022/10/img_4564.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Traditional weaving technique" },
    { type: "P", ar: "الملابس الجبلية", en: "Jebli Clothing" },
    { type: "P", ar: "الزي الجبلي في الشمال", en: "The Jebli attire of the north" },
    { type: "P", ar: "الجلابة", en: "Djellaba" },
    { type: "IMG", src: U("2022/10/img_4563.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Traditional weaving technique" },
    { type: "P", ar: "الجابادور", en: "Jabadour" },
    { type: "P", ar: "القفطان", en: "Caftan" },
    { type: "P", ar: "الكندورة أو القندورة", en: "Gandoura" },
    { type: "P", ar: "الدراعة", en: "Dra'a" },
    { type: "IMG", src: U("2022/10/img_4562.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Traditional weaving technique" },
    { type: "P", ar: "البلغة", en: "Belgha" },
    { type: "IMG", src: U("2022/10/img_4561.jpg"), cap_ar: "التقنية المعتمدة في حياكة الأزياء التقليدية", cap_en: "Traditional weaving technique" },
    { type: "P", ar: "سروال قندريسة", en: "Seroual Qandrissi" },
  ],
};

const foodGuide: Guide = {
  slug: "food",
  title_ar: "أكلات وأطباق مغربية",
  title_en: "Moroccan food and dishes",
  kicker_ar: "مطبخ",
  kicker_en: "Cuisine",
  image: U("2022/10/img_4539.jpg"),
  blocks: [
    { type: "H3", ar: "تعرف على أشهر الأكلات المغربية", en: "Famous Moroccan Dishes", noNumber: true },
    { type: "IMG", src: U("2022/10/img_4539.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "بتصنيفه في المركز الثاني عالميا في فن الطبخ لعام 2017 من قبل موقع التدوين البريطاني Worldsim Travel ، يقدم المغرب تجربة طبخ استثنائية ، تعد مراكش وفاس وأكادير وحتى الرباط من بين الوجهات الأكثر جاذبية من حيث فن الطبخ ، ويوجد أكثر من 15 مطعما مغربيا ضمن قائمة أفضل 1000 مطعم في العالم ، شاي بالنعناع أو الطاجين أو الكسكس أو البسطيلة ، اليك أفضل الاختصاصات التي يمكنك تذوقها وتعطيك رغبة في العودة", en: "Ranked second worldwide for its cuisine in 2017 by the British travel blog Worldsim Travel, Morocco offers an exceptional culinary experience. Marrakesh, Fes, Agadir, and even Rabat are among the most attractive destinations for gastronomy. With more than 15 Moroccan restaurants listed among the world's top 1000, from mint tea and tagine to couscous and pastilla, here are the best specialties to try that will leave you wanting to return." },
    { type: "P", ar: "المقبلات المغربية", en: "Moroccan Appetizers" },
    { type: "IMG", src: U("2022/10/img_4537.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "حساء الحريرة", en: "Harira Soup" },
    { type: "IMG", src: U("2022/02/img_2444.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "طاجن اللحم", en: "Meat Tagine" },
    { type: "IMG", src: U("2022/02/img_2445.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "الكسكس", en: "Couscous" },
    { type: "IMG", src: U("2022/02/img_2446.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "الرفيسة", en: "Rfissa" },
    { type: "IMG", src: U("2022/10/img_4541.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "الشباكية المغربية", en: "Moroccan Chebakia" },
    { type: "IMG", src: U("2022/02/img_2447.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "كعب الغزال", en: "Kaab el Ghazal" },
    { type: "IMG", src: U("2022/02/img_2449.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "الطنجية المراكشية", en: "Marrakeshi Tanjia" },
    { type: "IMG", src: U("2022/02/img_2450.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "السفة المدفونة بالدجاج", en: "Sfa Medfouna with Chicken" },
    { type: "IMG", src: U("2022/02/img_2451.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "البقلاوة المغربية", en: "Moroccan Baklava" },
    { type: "IMG", src: U("2022/02/img_2452.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "حلوى اللوز", en: "Almond Sweets" },
    { type: "IMG", src: U("2022/02/img_2453.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Famous Moroccan Dishes" },
    { type: "P", ar: "البسطيلة", en: "Pastilla" },
    { type: "IMG", src: U("2022/02/img_2454.jpg"), cap_ar: "تعرف على أشهر الأكلات المغربية", cap_en: "Discover the Most Famous Moroccan Dishes" },
  ],
};

const albumGuide: Guide = {
  slug: "album",
  title_ar: "ألبوم الصور",
  title_en: "Photo album",
  kicker_ar: "ألبوم",
  kicker_en: "Album",
  image: U("2022/04/img_4938.jpg"),
  blocks: [],
  gallery: [
    "2022/04/img_4938.jpg",
    "2022/04/img_4951.jpg",
    "2022/04/img_4950.jpg",
    "2022/04/img_4949.png",
    "2022/04/img_4952.jpg",
    "2022/04/img_4953.jpg",
    "2022/04/img_4960.jpg",
    "2022/04/img_4961.jpg",
    "2022/04/img_4954.jpg",
    "2022/04/img_4962.jpg",
    "2022/04/img_4955.jpg",
    "2022/04/img_4963.jpg",
    "2022/04/img_4956.jpg",
    "2022/04/img_4964.jpg",
    "2022/04/img_4957.jpg",
    "2022/04/img_4965.jpg",
    "2022/04/img_4959.jpg",
    "2022/04/img_4967.jpg",
    "2022/04/img_4975.jpg",
    "2022/04/img_4974.jpg",
    "2022/04/img_4973.jpg",
    "2022/04/img_4972.jpg",
    "2022/04/img_4971.jpg",
    "2022/04/img_4970.jpg",
    "2022/04/img_4968.jpg",
    "2022/04/img_4976.jpg",
    "2022/04/img_4977.jpg",
    "2022/04/img_4978.jpg",
    "2022/04/img_4979.jpg",
    "2022/04/img_4980.jpg",
    "2022/04/img_4989.jpg",
    "2022/04/img_4988.jpg",
    "2022/04/img_4987.jpg",
    "2022/04/img_4986.jpg",
    "2022/04/img_4985.jpg",
    "2022/04/img_4984.jpg",
    "2022/04/img_4983.jpg",
  ].map((n) => ({ src: U(n), cap_ar: "المغرب", cap_en: "Morocco" })),
};

export const moroccoGuides: Guide[] = [in_briefGuide, programGuide, hammamGuide, breedsGuide, museumsGuide, water_sportsGuide, productsGuide, clothingGuide, foodGuide, albumGuide];
