import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

// ثقافة شعب سامي (source p=34712)
const samiCulture: Guide = {
  slug: "sami-culture",
  title_ar: "تعرف على ثقافة شعب سامي في النرويج",
  title_en: "The culture of the Sámi people of Norway",
  kicker_ar: "ثقافة شعب سامي",
  kicker_en: "Sámi culture",
  image: U("2023/04/img_0631.jpg"),
  blocks: [
    {
      type: "H3",
      ar: "من فينمارك في الشمال الى ترونديلاغ في الجزء الأوسط من النرويج",
      en: "From Finnmark in the north to Trøndelag in central Norway",
      noNumber: true,
    },
    {
      type: "P",
      ar: "يمكنك تجربة أسلوب حياة سامي ، جرب يدك في التزلج على الجليد بالكلاب ، وقم بالتخييم في لاففو التقليدية (خيمة سامي) ، وتذوق مأكولات سامي التقليدية مثل بيدوس (يخنة الرنة السميكة) وlefse (خبز البطاطس المسطح)",
      en: "You can experience the Sámi way of life: try your hand at dog sledding, camp in a traditional lavvo (a Sámi tent) and taste traditional Sámi food such as bidos (a thick reindeer stew) and lefse (flat potato bread).",
    },
    {
      type: "P",
      ar: "في شمال النرويج ، يمكنك قضاء يوم مع عائلة من رعاة الرنة والتعرف عن قرب على قطيعهم ، في أبريل ومايو ، يمكنك حتى تجربة الهجرة السنوية لأيائل الرنة",
      en: "In northern Norway you can spend a day with a family of reindeer herders and get close to their herd, and in April and May you can even witness the annual reindeer migration.",
    },
    {
      type: "P",
      ar: "على مدار العام ، تقدم العديد من مهرجانات سامي حفلات موسيقية ومعارض وأنشطة ممتعة مثل سباق الرنة ورمي اللاسو ، ويعد متحف سامي الوطني في كاراسجوك ومتحف فارانجر سامي والمتحف النرويجي للتاريخ الثقافي في أوسلو مجرد أمثلة قليلة من المتاحف التي تقدم معارض آسرة حول ثقافة وتاريخ سامي",
      en: "Throughout the year, many Sámi festivals offer concerts, exhibitions and enjoyable activities such as reindeer racing and lasso throwing. The Sámi National Museum in Karasjok, the Varanger Sámi Museum and the Norwegian Museum of Cultural History in Oslo are just a few of the museums with captivating exhibitions on Sámi culture and history.",
    },
    {
      type: "P",
      ar: "تلتقي الأصوات القديمة والحرف اليدوية التقليدية وثقافة الرنة القديمة بالتكنولوجيا الجديدة وطريقة الحياة الحديثة ، فيما يلي حقائق رائعة عن السامي ، السكان الأصليون في النرويج",
      en: "Ancient voices, traditional handicrafts and an old reindeer culture meet new technology and a modern way of life. Here are some fascinating facts about the Sámi, the indigenous people of Norway.",
    },
    { type: "H3", ar: "النرويج هي موطن لمعظم سامي في العالم", en: "Norway is home to most of the world's Sámi" },
    {
      type: "P",
      ar: "يقدر اجمالي عدد سكان سامي في النرويج والسويد وفنلندا وروسيا بنحو 80,000 نسمة ، ويعيش حوالي نصفهم في النرويج ، تقع الغالبية العظمى من المستوطنات في شمال النرويج ، وفي المقام الأول مقاطعة فينمارك ، ومع ذلك هناك مجتمعات سامية في أقصى الجنوب حتى ترونديلاغ",
      en: "The total Sámi population in Norway, Sweden, Finland and Russia is estimated at around 80,000 people, and roughly half of them live in Norway. The vast majority of settlements are in northern Norway, primarily in Finnmark county, yet there are Sámi communities as far south as Trøndelag.",
    },
    {
      type: "P",
      ar: "يعتقد الكثيرون أن تقاليد سامي تتكون فقط من الأزياء الملونة ومنتجات الحرف اليدوية التقليدية واصطياد الرنة باللاسو ، لكن تراث سامي مرئي وحيوي أيضا في كل شيء من موسيقى الراب والهندسة المعمارية الحديثة الى الفن المعاصر والتصميم المتطور ، يمكن أن يكون سامي الحديث مخرج أفلام حائزا على جوائز وراعي أيائل الرنة على عربة ثلجية ، لكن كليهما قد يشعر بنفس العلاقة العميقة مع الطبيعة",
      en: "Many people think Sámi tradition consists only of colourful costumes, traditional handicrafts and lassoing reindeer, but Sámi heritage is also visible and alive in everything from rap music and modern architecture to contemporary art and cutting-edge design. A modern Sámi may be an award-winning film director or a reindeer herder on a snowmobile, yet both may feel the same deep connection with nature.",
    },
    {
      type: "P",
      ar: "فاذا قمت بزيارة شمال النرويج ، يمكنك أيضا تجربة طريقة حياة سامي ، قم بالتخييم في لاففو التقليدية (خيمة سامي) تحت الأضواء الشمالية ، واحصل على لقاء وثيق مع الرنة أو اذهب لرؤية معرض فن سامي",
      en: "So if you visit northern Norway you can experience the Sámi way of life too: camp in a traditional lavvo under the northern lights, get a close encounter with reindeer or go and see an exhibition of Sámi art.",
    },
    { type: "IMG", src: U("2023/04/img_0628.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
    { type: "H3", ar: "انضم الى العديد من مهرجانات سامي", en: "Join one of the many Sámi festivals" },
    {
      type: "P",
      ar: "حضور مهرجان سامي مكان جيد (وممتع للغاية) للبدء اذا كنت ترغب في معرفة المزيد عن الثقافة والتقاليد ، في شهر يوليو من كل عام ، يجذب المهرجان الدولي للسكان الأصليين Riddu Riđđu في Manndalen في ترومس الفنانين ومشجعي المهرجان من جميع أنحاء العالم ، مع الحفلات الموسيقية تحت شمس منتصف الليل ومجموعة واسعة من الأنشطة ، يعد Riddu Riđđu بالتأكيد مهرجانا غير عادي",
      en: "Attending a Sámi festival is a good — and very enjoyable — place to start if you want to learn more about the culture and traditions. Every July the Riddu Riđđu international indigenous festival in Manndalen, Troms, draws artists and festivalgoers from all over the world; with concerts under the midnight sun and a wide range of activities, Riddu Riđđu is certainly an extraordinary festival.",
    },
    {
      type: "P",
      ar: "يحتفل أسبوع سامي في ترومسو بكل شيء سامي بالتزامن مع يومهم الوطني في 6 فبراير ، جرب يدك في سباق الرنة ، وتعلم جويك ، أو استمتع بالحفلات الموسيقية والمحادثات والأجزاء السخية من الطبق التقليدي البيدوس ، ولا تفوت البطولة الوطنية في رمي اللاسو",
      en: "Sámi Week in Tromsø celebrates everything Sámi around their national day on 6 February. Try your hand at reindeer racing, learn a joik, or enjoy the concerts, talks and generous portions of the traditional dish bidos — and don't miss the national lasso-throwing championship.",
    },
    {
      type: "P",
      ar: "جذب مهرجان عيد الفصح الصامي في كاوتوكيينو العائلات والناس من جميع الأعمار ، وأصبح نقطة محورية في ثقافتهم ، يمتلئ البرنامج بالحفلات الموسيقية والمعارض ، بالاضافة الى الأنشطة الترفيهية مثل صليب السكوتر وسباق الرنة",
      en: "The Sámi Easter Festival in Kautokeino attracts families and people of all ages and has become a focal point of their culture, with a programme full of concerts and exhibitions as well as fun activities such as snowmobile cross and reindeer racing.",
    },
    {
      type: "P",
      ar: "المهرجانات الأخرى التي يجب عليك التحقق منها هي أسبوع موسيقى سامي في ألتا ، ومهرجان تانا الشتوي ، ومهرجان عيد الفصح الصامي في كاراسجوك ، وماركوميانو في غالوجيدي ، ومهرجان سكابما في ليبيسبي",
      en: "Other festivals worth checking out are Sámi Music Week in Alta, the Tana Winter Festival, the Sámi Easter Festival in Karasjok, Márkomeannu in Gállogieddi and the Skábma festival in Lebesby.",
    },
    { type: "IMG", src: U("2023/04/img_0629.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
    { type: "H3", ar: "البرلمان الصامي على شكل لافو", en: "The Sámi parliament shaped like a lavvo" },
    {
      type: "P",
      ar: "في عام 1989م تم افتتاح البرلمان الصامي بعد العديد من الاحتجاجات في السبعينيات والثمانينيات ضد بناء محطة للطاقة الكهرومائية في نهر ألتايلفا في شمال النرويج ، والمعروفة باسم جدل ألتا ، منذ ذلك الحين تمكن الصامي النرويجي من انتخاب ممثلين في برلمان يركز فقط على قضايا سامي",
      en: "The Sámi parliament opened in 1989 after many protests in the 1970s and 1980s against the building of a hydroelectric power station on the Alta river in northern Norway, known as the Alta controversy. Since then Norwegian Sámi have been able to elect representatives to a parliament devoted solely to Sámi affairs.",
    },
    {
      type: "P",
      ar: "تتشكل القطعة المعمارية اللافتة للنظر الموجودة في كاراسجوك في فينمارك (المعروفة باسم عاصمة سامي) على شكل لافو وهي خيمة سامية ، والتي كانت دائما رمزا لثقافتهم البدوية ، فهم يرحبون بالزوار للمشاركة في الجولات المصحوبة بمرشدين في مبنى البرلمان (من الاثنين الى الجمعة) ، والتي يتم تقديمها باللغة الصامية والنرويجية والانجليزية",
      en: "The striking building in Karasjok in Finnmark — known as the Sámi capital — is shaped like a lavvo, the Sámi tent that has always been a symbol of their nomadic culture. Visitors are welcome to join guided tours of the parliament building from Monday to Friday, given in Sámi, Norwegian and English.",
    },
    { type: "IMG", src: U("2023/04/img_0630.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
    {
      type: "H3",
      ar: "يتحدث الشعب الصامي ما لا يقل عن خمس لغات مختلفة",
      en: "The Sámi people speak at least five different languages",
    },
    {
      type: "P",
      ar: "من بين اللغات الصامية التسع المختلفة في العالم ، هناك خمس لغات مستخدمة في النرويج ، الثلاثة الأكثر شيوعا هي سامي الشمالي ولولي سامي وسامي الجنوبي ، يمر بيت سامي وسامي الشرقي حاليا بمرحلة تنشيط في النرويج ، لا تشبه أي من اللغات بعضها البعض ، كما أنها لا ترتبط باللغة النرويجية أو أي لغة اسكندنافية أخرى",
      en: "Of the nine different Sámi languages in the world, five are used in Norway. The three most common are Northern Sámi, Lule Sámi and Southern Sámi, while Pite Sámi and Eastern Sámi are currently being revitalised in Norway. None of the languages resembles the others, and none is related to Norwegian or any other Scandinavian language.",
    },
    {
      type: "P",
      ar: "خلال أجزاء كبيرة من القرن العشرين ، منع الساميون في النرويج من التحدث بلغتهم الخاصة واضطروا الى تعلم اللغة النرويجية بموجب سياسات استيعاب صارمة ، ونتيجة لذلك يتحدث أقل قليلا من نصف الصاميين في النرويج لغة سامية اليوم ، لهذا حصل الشعب الصامي على اعتذار رسمي من الحكومة النرويجية في عام 1999م",
      en: "For large parts of the twentieth century the Sámi in Norway were forbidden to speak their own language and were forced to learn Norwegian under strict assimilation policies. As a result, slightly fewer than half of the Sámi in Norway speak a Sámi language today, and in 1999 the Sámi people received an official apology from the Norwegian government.",
    },
    { type: "IMG", src: U("2023/04/img_0633.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0632.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway", size: "compact" },
    { type: "H3", ar: "يشهد التقليد الصوتي الصامي جويك نهضة", en: "The Sámi vocal tradition of joik is seeing a revival" },
    {
      type: "P",
      ar: "يويك – الموسيقى الشعبية للسامي – هي واحدة من أقدم تقاليد الأغاني في أوروبا ، لها خصائص صوتية خاصة ويتم تنفيذها كاهداء لشخص أو حيوان أو مكان ، يمارس يويك في العديد من المواقف كجزء من الحياة اليومية",
      en: "Joik — the folk music of the Sámi — is one of the oldest song traditions in Europe. It has its own particular vocal qualities and is performed as a dedication to a person, an animal or a place, and it is practised in many situations as part of daily life.",
    },
    {
      type: "P",
      ar: "ان بقاء الجويك على مر القرون ، على الرغم من الضغط من أجل التثاقف والاستيعاب من قبل الحكومة النرويجية ، هو في حد ذاته ظاهرة رائعة ، لفترة طويلة أدين جويك باعتباره خاطئا ، وفي الخمسينيات كان ممنوعا من استخدام جويك في مدارس منطقة سامي ، ولحسن الحظ تغير هذا ، ففي الواقع كان جويك يشهد تنشيطا في السنوات الأخيرة ، ويدرج العديد من الفنانين الشباب جويك كعنصر في الموسيقى المعاصرة ، وأصبح الجمع بين جويك وأنماط أخرى مختلفة مثل الجاز والميتال والروك أكثر شعبية بشكل متزايد",
      en: "That joik has survived across the centuries, despite pressure for acculturation and assimilation by the Norwegian government, is a remarkable phenomenon in itself. For a long time joik was condemned as sinful, and in the 1950s it was banned from schools in the Sámi area. Fortunately that has changed: joik has been revitalised in recent years, many young artists include it as an element in contemporary music, and combining joik with styles such as jazz, metal and rock has become increasingly popular.",
    },
    {
      type: "P",
      ar: "في مايو 2019م ، مثلت المجموعة النرويجية السامية المسماة KEiiNO النرويج في مسابقة الأغنية الأوروبية في تل أبيب ، يجمع KEiiNO بين البوب والالكترونيات والرقص والجويك ، وتمزج أغنية Spirit in the sky بين اللغة الانجليزية وسامي في البوب وجويك ، احتل KEiiNO المركز السادس في النهائي وكان في الواقع فائزا واضحا في التصويت العام الذي يعد 50 في المائة من النتيجة النهائية",
      en: "In May 2019 the Norwegian Sámi group KEiiNO represented Norway at the Eurovision Song Contest in Tel Aviv. KEiiNO combine pop, electronica, dance and joik, and their song Spirit in the Sky blends English and Sámi with pop and joik. KEiiNO came sixth in the final and were in fact clear winners of the public vote, which counts for 50 per cent of the final score.",
    },
    {
      type: "P",
      ar: "من بين الفنانين النرويجيين الآخرين المشهورين بتفسيراتهم لجويك ماري بوين وآن ماري أندرسن وفرود فيلهايم وايلا ماري هاتا ايزاكسن وايل ماريا ايرا ومارجا مورتنسون",
      en: "Other Norwegian artists known for their interpretations of joik include Mari Boine, Ann-Mari Andersen, Frode Fjellheim, Ella Marie Hætta Isaksen, Áilu Máret Æira and Marja Mortensson.",
    },
    { type: "IMG", src: U("2023/04/img_0634.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
    { type: "H3", ar: "مؤلف الأغنية الافتتاحية لفروزن هو سامي", en: "The composer of the opening song of Frozen is Sámi" },
    {
      type: "P",
      ar: "أراد فريق انتاج ديزني وراء فروزن ، بما في ذلك الملحن كريستوف بيك ، استخدام موسيقى الشمال كمصدر الهام للموسيقى في الفيلم ، خلال رحلة بحثية الى النرويج في عام 2012م اكتشفوا فرود فيلهايم ، وهو موسيقي وملحن له جذور سامية ، وافق فيلهايم لاحقا على المشاركة في كتابة موسيقى الفيلم مع بيك ، وأصبحت النتيجة النهائية الأغنية الافتتاحية Vuelie وهي نسخة معدلة قليلا من أغنية Eatnemen Vuelie (بمعنى أغنية الأرض) التي كتبها فيلهايم في الأصل في عام 1996م ، تتميز القطعة بجويك الذي تعلمه فيلهايم في طفولته ، وتم الاحتفال بفيلهايم لاحقا لاحضاره جويك الى هوليوود",
      en: "The Disney production team behind Frozen, including composer Christophe Beck, wanted to use Nordic music as inspiration for the film's score. On a research trip to Norway in 2012 they discovered Frode Fjellheim, a musician and composer with Sámi roots, who later agreed to co-write the film's music with Beck. The result was the opening song Vuelie, a slightly reworked version of Eatnemen Vuelie (Song of the Earth), which Fjellheim originally wrote in 1996. The piece features joik, which Fjellheim learned in childhood, and he was later celebrated for bringing joik to Hollywood.",
    },
    { type: "IMG", src: U("2023/04/img_0635.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
    {
      type: "H3",
      ar: "النرويج هي موطن لأكثر من 200 ألف من أيائل الرنة",
      en: "Norway is home to more than 200,000 reindeer",
    },
    {
      type: "P",
      ar: "لطالما كانت الرنة جزءا أساسيا من ثقافة سامي ، لا يوجد تقريبا أي جزء من الرنة غير مستخدم : اللحوم للطهي والفراء والجلد للملابس والأحذية ، وتتحول القرون الى كل شيء من الأدوات المفيدة الى الفن الجميل",
      en: "Reindeer have always been an essential part of Sámi culture, and almost no part of the animal goes unused: the meat for cooking, the fur and hide for clothing and shoes, and the antlers turned into everything from useful tools to fine art.",
    },
    {
      type: "P",
      ar: "تمارس تربية الرنة النرويجية في المقام الأول في شمال النرويج ، وترونديلاغ ، وموري أوغ رومسدال في مضيق النرويج ، وهيدمارك في شرق النرويج ، اليوم يشارك حوالي 3000 شخص في تربية الرنة الصامية ، 2200 منهم في فينمارك وحدها ، يكسب الرعاة لقمة العيش من خلال بيع منتجات الرنة ، يباع اللحم في جميع أنحاء النرويج ويتم تصديره أيضا ، وتتحول الجلود الى قفازات وأحذية ومنتجات جلدية أخرى",
      en: "Norwegian reindeer husbandry is practised mainly in northern Norway, Trøndelag, Møre og Romsdal in the fjord region and Hedmark in eastern Norway. Today around 3,000 people are involved in Sámi reindeer herding, 2,200 of them in Finnmark alone. Herders earn their living by selling reindeer products: the meat is sold all over Norway and also exported, and the hides are turned into gloves, shoes and other leather goods.",
    },
    {
      type: "P",
      ar: "مما لا يثير الدهشة بما فيه الكفاية ، أن الرنة هي أيضا مركزية جدا في مطبخ سامي ، ببساطة لا يمكنك زيارة فينمارك دون تذوق لحم الرنة ، وهو تخصص اقليمي ، يتم تقديم الرنة بكل الطرق التي يمكن تخيلها ، ولكن الطبق الأكثر شهرة هو على الأرجح البيدوس ، وهو يخنة مصنوعة من الجزر والبطاطس ولحم الرنة المطبوخ ببطء",
      en: "Unsurprisingly, reindeer is also central to Sámi cuisine — you simply cannot visit Finnmark without tasting reindeer meat, a regional speciality. It is served in every imaginable way, but the most famous dish is probably bidos, a stew made with carrots, potatoes and slowly cooked reindeer meat.",
    },
    { type: "IMG", src: U("2023/04/img_0636.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
    { type: "H3", ar: "الدودجي هي الكلمة الصامية للحرف اليدوية", en: "Duodji is the Sámi word for handicraft" },
    {
      type: "P",
      ar: "تحتوي ثقافة سامي على العديد من التعبيرات المميزة ، والدودجي – الحرف اليدوية الصامية – هي واحدة منها ، أدوات الدودجي والملابس والاكسسوارات وظيفية ومفيدة وغالبا ما تتضمن عناصر فنية ، على الرغم من حدوث تغييرات طفيفة في الدودجي التقليدي ، الا أن العديد من التقاليد الحرفية مثل تطريز اللؤلؤ وأربطة الأحذية النسيجية ونحت الخشب وصنع السكاكين يتم الحفاظ عليها بدقة ، اليوم يعتبر الدودجي التقليدي قطعا فنية قيمة من قبل جامعي الأعمال من جميع أنحاء العالم",
      en: "Sámi culture has many distinctive expressions, and duodji — Sámi handicraft — is one of them. Duodji tools, clothing and accessories are functional and useful, and often include artistic elements. Although traditional duodji has changed slightly, many craft traditions such as pearl embroidery, woven shoe bands, wood carving and knife making are carefully preserved, and today traditional duodji is regarded as valuable art by collectors from all over the world.",
    },
    {
      type: "P",
      ar: "الزي التقليدي والذي يسمى كوفتي هو تقليد حي آخر ، اليوم يستخدم في الغالب لارتداء الملابس للمناسبات الخاصة ، مثل حفلات الزفاف والتأكيدات والمناسبات الثقافية الأخرى ، كما يمكن أن تشير ألوان الزي وأنماطه وزخارفه الى الأصل الجغرافي للشخص ، ألوان سامي التقليدية هي الأحمر والأخضر والأزرق والأصفر",
      en: "The traditional costume, called the gákti, is another living tradition. Today it is mostly worn for special occasions such as weddings, confirmations and other cultural events, and its colours, patterns and ornaments can indicate a person's geographical origin. The traditional Sámi colours are red, green, blue and yellow.",
    },
    {
      type: "P",
      ar: "لمعرفة المزيد عما يحدث في المشهد الفني الصامي اليوم ، فان مركز سامي للفن المعاصر في كاراسجوك يستحق الزيارة بالتأكيد ، يهدف المتحف الى أن يكون مكانا لمعارض الفن المعاصر الصامي ، والذي يتراوح من التعبيرات الجديدة الى الدودجي التقليدي",
      en: "To learn more about what is happening in the Sámi art scene today, the Sámi Centre for Contemporary Art in Karasjok is well worth a visit. The museum aims to be a place for exhibitions of contemporary Sámi art, ranging from new expressions to traditional duodji.",
    },
    { type: "IMG", src: U("2023/04/img_0637.jpg"), cap_ar: "ثقافة شعب سامي بالنرويج", cap_en: "Sámi culture in Norway" },
  ],
};

// النرويج باختصار (source p=34507)
const norwayBrief: Guide = {
  slug: "norway-brief",
  title_ar: "النرويج باختصار – تعرف على عدد من الأمور الخاصة بالنرويج",
  title_en: "Norway in brief — a few practical things to know",
  kicker_ar: "النرويج باختصار",
  kicker_en: "Norway in brief",
  image: U("2022/03/img_3731.jpg"),
  blocks: [
    { type: "H3", ar: "النرويج بشكل عام", en: "Norway in general" },
    {
      type: "P",
      ar: "اتفق معظم المسافرين ومحبي الطبيعة أن النرويج تتفوق من حيث الطبيعة على كل من سويسرا والنمسا ، في اعتقادي الشخصي انها حقيقة وليست رأي",
      en: "Most travellers and nature lovers agree that Norway surpasses both Switzerland and Austria when it comes to nature — in my personal view that is a fact, not an opinion.",
    },
    {
      type: "P",
      ar: "أكثر ما يميز طبيعة النرويج هي المضائق المائية Norway Fjords التي يتنافس الكثير منها في الجمال وخصوصا في غربها ، ولكن عند زيارتك الأولى للنرويج ستلاحظ أن كل شبر فيها يستحق الزيارة",
      en: "What stands out most in Norway's nature are the fjords, many of which compete in beauty, especially in the west — but on your first visit you will notice that every inch of the country deserves a visit.",
    },
    {
      type: "P",
      ar: "الطبيعة الجبلية في النرويج يمكن أن نصنفها ميزة ويمكن أن نصنفها عيبا ، بالنسبة للسائح يعتبر عيبا لأن القيادة ستكون متعبة (ولكن المناظر تشفع)",
      en: "Norway's mountainous terrain can be counted as an advantage or a drawback: for the traveller it is a drawback because the driving is tiring — but the views make up for it.",
    },
    { type: "H3", ar: "مطارات النرويج", en: "Airports in Norway" },
    {
      type: "LIST",
      ar: ["هناك مطاران تستطيع الوصول عن طريقهما للنرويج", "مطار أوسلو", "مطار بيرغن"],
      en: ["There are two airports through which you can reach Norway", "Oslo airport", "Bergen airport"],
    },
    { type: "H3", ar: "تكاليف المعيشة", en: "The cost of living" },
    {
      type: "P",
      ar: "التسوق والمعيشة والأنشطة في النرويج أسعارها تعتبر عالية جدا ، وهنا نعرض متوسط الأسعار لبعض الأساسيات",
      en: "Shopping, living and activities in Norway are very expensive. Here are the average prices of a few basics.",
    },
    {
      type: "LIST",
      ar: [
        "علبة كولا : 1.2 دينار بحريني",
        "برجر عادي : 9 دينار بحريني",
        "تذكرة تلفريك : 50 دينار بحريني",
        "ايجار سيارة كهربائية صغيرة : 40 دينار بحريني",
      ],
      en: [
        "A can of cola: 1.2 Bahraini dinars",
        "An ordinary burger: 9 Bahraini dinars",
        "A cable car ticket: 50 Bahraini dinars",
        "Renting a small electric car: 40 Bahraini dinars",
      ],
    },
    {
      type: "P",
      ar: "لذلك فان معادلة تقليل التكاليف سهلة مثل : الطبخ الشخصي + لا تتسوق + لا تدخل أنشطة كثيرة + الحجز المبكر للسكن والمواصلات والطيران ، عموما أسعار التذاكر والسكن والمواصلات والخضار والفواكه في النرويج مقبولة ومعقولة جدا ، ماعدا السيارات فاعتبرها أغلى من قريناتها بقليل",
      en: "So the formula for cutting costs is simple: cook for yourself, don't shop, don't book many activities, and reserve accommodation, transport and flights early. In general the prices of tickets, accommodation, transport, vegetables and fruit in Norway are acceptable and quite reasonable — except for cars, which are a little pricier than elsewhere.",
    },
    { type: "H3", ar: "أفضل وقت لزيارة النرويج", en: "The best time to visit Norway" },
    {
      type: "P",
      ar: "أفضل وقت لزيارة النرويج هو فصل الربيع والصيف ، فمتوسط درجات الحرارة ما بين 15-25 درجة مئوية",
      en: "The best time to visit Norway is spring and summer, when average temperatures are between 15 and 25 degrees Celsius.",
    },
    {
      type: "P",
      ar: "وعلى غير العادة الخليجيون يزورون النرويج في الشتاء أيضا ، ولكن ليس للتزلج أو حبا في الثلوج ، ولكن لمشاهدة أحد أجمل الظواهر الطبيعية وهي الشفق القطبي Aurora وغالبا الرحلات تكون لمدينة ترومسو ومنها تنطلق البرامج",
      en: "Unusually, Gulf visitors also come to Norway in winter — not for skiing or for love of snow, but to see one of the most beautiful natural phenomena, the aurora. Those trips are usually to Tromsø, from where the programmes set out.",
    },
    {
      type: "P",
      ar: "الليل قصير جدا في المناطق التي اعتاد الخليجيون زيارتها ، تقريبا مدة الليل 3 ساعات ، ولا يكون هناك ظلام دامس بل بالعكس كل شيء تستطيع أن تراه",
      en: "The night is very short in the areas Gulf visitors usually go to — roughly three hours — and it never gets pitch dark; on the contrary, you can see everything.",
    },
    { type: "H3", ar: "هل النرويج مناسبة للعائلات ؟", en: "Is Norway suitable for families?" },
    {
      type: "LIST",
      ar: [
        "كل شيء مناسب للعوائل ولكن الاختلاف في هدفك من الرحلة سواء عائلة مع أو بدون أطفال أو أصدقاء",
        "الأنشطة قليلة جدا وغالية ، وتعوضها المناطق الطبيعية والريفية والتي هي أكثر ما يميز النرويج",
        "الطرق تعتبر متعبة لحد ما والأجواء تميل للبرودة غالبا",
        "لا يوجد منع للنقاب في النرويج والأمر طبيعي هناك",
      ],
      en: [
        "Everything is suitable for families; the difference lies in the purpose of your trip — a family with or without children, or friends.",
        "Activities are few and expensive, but the natural and rural areas that most distinguish Norway make up for that.",
        "The roads are somewhat tiring and the weather usually tends to be cold.",
        "There is no ban on the niqab in Norway and it is perfectly normal there.",
      ],
    },
    { type: "H3", ar: "ما هو أفضل مسار سياحي في النرويج ؟", en: "What is the best route around Norway?" },
    {
      type: "P",
      ar: "مخطط منطقي يضمن مشاهدة أغلب المناطق الجميلة في النرويج مع عدم تغير السكن بكثرة ، اذا كانت رحلتك لمدة اسبوعين مثلا",
      en: "A sensible plan that lets you see most of Norway's beautiful areas without changing accommodation too often — if your trip lasts two weeks, for example:",
    },
    {
      type: "LIST",
      ar: [
        "الوصول لـ أوسلو",
        "ثم السكن في فوس (وزيارة ما حولها خلال اقامتك)",
        "ثم السكن في سترين (وزيارة ما حولها خلال اقامتك)",
        "ثم العودة لـ أوسلو (السكن فيها ما تبقى من أيام)",
      ],
      en: [
        "Arrive in Oslo",
        "Then stay in Voss, visiting the surrounding area during your stay",
        "Then stay in Stryn, visiting the surrounding area during your stay",
        "Then return to Oslo and stay there for the remaining days",
      ],
    },
    { type: "H3", ar: "ما هي أبرز المدن والقرى في النرويج ؟", en: "Which are the main towns and villages in Norway?" },
    {
      type: "LIST",
      ar: [
        "أوسلو Oslo",
        "فوس Voss ، ومنها تستطيع زيارة : أودا Odda وبيرغن Bergen وفلام Flam",
        "سترين Stryn ، ومنها تستطيع زيارة : غيرانغر Geiranger وأولدن Olden ولوين Loen",
      ],
      en: [
        "Oslo",
        "Voss — from where you can visit Odda, Bergen and Flåm",
        "Stryn — from where you can visit Geiranger, Olden and Loen",
      ],
    },
    { type: "H3", ar: "السكن في الأكواخ", en: "Staying in cabins" },
    {
      type: "LIST",
      ar: [
        "الأكواخ هو خيار السكن الأفضل في المناطق التي تم ذكرها بالأعلى",
        "كذلك تجربة الكرفان أعتقد انها ستكون بوابتك لخوض تجربة مميزة ، فهناك مواقع كثيرة تؤجر كرفانات بأحجام مختلفة وغالبا حتى 6 أشخاص تستطيع استئجارها",
      ],
      en: [
        "Cabins are the best accommodation option in the areas mentioned above.",
        "A caravan is also, I believe, your gateway to a special experience — many sites rent caravans in different sizes, often for up to six people.",
      ],
    },
    { type: "H3", ar: "استئجار السيارات", en: "Renting a car" },
    {
      type: "P",
      ar: "أفضل شركات استئجار السيارات في النرويج ، فهذه الشركات كلها مميزة وهي الأشهر",
      en: "The best car rental companies in Norway — all of them are good and they are the best known:",
    },
    { type: "LIST", ar: ["سكست", "يوروب كار", "هيرتز"], en: ["Sixt", "Europcar", "Hertz"] },
  ],
};

// أفضل عشرة أماكن للسياحة في النرويج (source p=34306)
const topTenPlaces: Guide = {
  slug: "top-ten-places",
  title_ar: "السياحة في النرويج – أفضل عشرة أماكن",
  title_en: "Tourism in Norway — the top ten places",
  kicker_ar: "أفضل 10 أماكن",
  kicker_en: "Top 10 places",
  image: U("2023/04/img_0401.jpg"),
  blocks: [
    { type: "H3", ar: "في النرويج تحتار من أين تبدأ ؟", en: "In Norway, where do you even start?", noNumber: true },
    {
      type: "P",
      ar: "من المدن الحضرية العصرية الى المضايق المتلألئة والأضواء الشمالية والقرى النائية فوق الدائرة القطبية الشمالية ، النرويج بلد طويل جدا ومليء بالأشياء التي يمكن رؤيتها والقيام بها",
      en: "From modern urban cities to glittering fjords, the northern lights and remote villages above the Arctic Circle, Norway is a very long country and full of things to see and do.",
    },
    {
      type: "P",
      ar: "لذلك نحتار من أين نبدأ ؟ للحصول على أقصى استفادة من عطلتنا ، أوصيك باختيار منطقة أو منطقتين لاستكشافها بروية ، اليك بعض الاقتراحات",
      en: "So where to begin? To get the most out of a holiday, I recommend choosing one or two regions and exploring them at a relaxed pace. Here are some suggestions.",
    },
    { type: "IMG", src: U("2023/04/img_0562.jpg"), cap_ar: "أفضل 10 أماكن في النرويج", cap_en: "The top 10 places in Norway" },
    { type: "H3", ar: "منطقة أوسلو", en: "The Oslo region", sub_ar: "The Oslo region", sub_en: "منطقة أوسلو" },
    {
      type: "P",
      ar: "يتم طهي الكثير من الأشياء في العاصمة النرويجية أوسلو ، والتي أطلق عليها اسم العاصمة الأوروبية الخضراء 2019 ، مشهد طعام متطور ، وأحياء جديدة وغير تقليدية ، وتقويم أحداث مليء بالكامل ، والعديد من المتاحف والمعالم السياحية الجديدة تماما ، بعض الجمل التشويقية لما يمكن أن تتوقعه ، محاطا بمضيق أوسلو والغابات العميقة",
      en: "A great deal is cooking in the Norwegian capital Oslo, named European Green Capital 2019: a sophisticated food scene, new and unconventional neighbourhoods, a packed events calendar and many brand-new museums and attractions — just a taste of what you can expect, all surrounded by the Oslofjord and deep forests.",
    },
    {
      type: "P",
      ar: "يمكنك بسهولة الجمع بين حياة المدينة الحضرية والمرح القائم على الطبيعة مثل ركوب الدراجات والتزلج في بعض أفضل منتجعات التزلج في النرويج والرحلات الى المناطق القريبة من أوستفولد وفيستفولد ، مع مدن ساحرة مثل فريدريكستاد وتونسبيرغ المنتشرة على طول الساحل ، تقع هادلاند الوجهة الفنية الجديدة في النرويج على بعد حوالي ساعة بالسيارة من أوسلو ، حيث يمكنك زيارة الحديقة الفنية الرائعة في الهواء الطلق في متحف كيستيفوس مع مبنى المعرض المذهل The Twist",
      en: "You can easily combine urban city life with nature-based fun such as cycling and skiing at some of Norway's best ski resorts, plus trips to nearby Østfold and Vestfold, with charming towns like Fredrikstad and Tønsberg spread along the coast. Hadeland, Norway's new art destination, is about an hour's drive from Oslo, where you can visit the wonderful open-air sculpture park at the Kistefos Museum with its stunning gallery building, The Twist.",
    },
    {
      type: "P",
      ar: "أنت أيضا على بعد ساعتين فقط من المشي لمسافات طويلة وركوب الدراجات في المناطق الجبلية المركزية",
      en: "You are also just two hours from hiking and cycling in the central mountain areas.",
    },
    { type: "IMG", src: U("2023/04/img_0494.jpg"), cap_ar: "منطقة أوسلو", cap_en: "The Oslo region", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0495.jpg"), cap_ar: "منطقة أوسلو", cap_en: "The Oslo region", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0496.jpg"), cap_ar: "منطقة أوسلو", cap_en: "The Oslo region", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0497.jpg"), cap_ar: "منطقة أوسلو", cap_en: "The Oslo region", size: "compact" },
    {
      type: "H3",
      ar: "ترومسو وأرض الأضواء الشمالية",
      en: "Tromsø and the land of the northern lights",
      sub_ar: "Tromsø and the land of the northern lights",
      sub_en: "ترومسو وأرض الأضواء الشمالية",
    },
    {
      type: "P",
      ar: "تقع عاصمة القطب الشمالي ترومسو في وسط شمال النرويج ، اذا كانت قائمة أمنياتك تتضمن الأضواء الشمالية ومشاهدة الحيتان وشمس منتصف الليل ومغامرات الطبيعة الملحمية ، فهذا هو المكان الذي تريد الذهاب اليه",
      en: "The Arctic capital of Tromsø lies in the middle of northern Norway. If your bucket list includes the northern lights, whale watching, the midnight sun and epic nature adventures, this is where you want to go.",
    },
    {
      type: "P",
      ar: "استمتع بظروف رائعة للقيام بجولات التزلج وركوب الدراجات والمشي لمسافات طويلة في منطقة لينغنفيورد ، وتجربة ثقافة سامي في مدن مثل كاراسجوك وألتا ، والدخول الى أقصى نقطة في شمال أوروبا في نورث كيب ، في الجزء الشرقي من هذه المنطقة الشاسعة ستجد شبه جزيرة فارانجر ، وهي جنة مراقبي الطيور ، يمكنك الذهاب لصيد سلطعون الملك والتزلج بالكلاب في كيركينيس وفارانجر ، حيث يمكنك أيضا قضاء ليلة في أحد فنادق الجليد ، وفي المناطق المحيطة بترومسو تنتظر عدة جزر ليتم استكشافها بما في ذلك سينجا وكفالويا وسوماروي",
      en: "Enjoy superb conditions for ski touring, cycling and hiking in the Lyngenfjord region, experience Sámi culture in towns such as Karasjok and Alta, and stand at the northernmost point of Europe at the North Cape. In the eastern part of this vast region you will find the Varanger peninsula, a birdwatcher's paradise, and you can go king crab fishing and dog sledding in Kirkenes and Varanger, where you can also spend a night in an ice hotel. Around Tromsø several islands wait to be explored, including Senja, Kvaløya and Sommarøy.",
    },
    { type: "IMG", src: U("2023/04/img_0508.jpg"), cap_ar: "ترومسو", cap_en: "Tromsø", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0507.jpg"), cap_ar: "ترومسو", cap_en: "Tromsø", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0505.jpg"), cap_ar: "ترومسو", cap_en: "Tromsø", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0503.jpg"), cap_ar: "ترومسو", cap_en: "Tromsø", size: "compact" },
    {
      type: "H3",
      ar: "لوفوتين ونوردلاند",
      en: "Lofoten and Nordland",
      sub_ar: "Lofoten and Nordland",
      sub_en: "لوفوتين ونوردلاند",
    },
    {
      type: "P",
      ar: "قمم مذهلة ، ومضايق متلألئة ، وقرى صيد أصلية ، وشواطئ مثالية للصور ، ناهيك عن الأضواء الشمالية وشمس منتصف الليل ، ربما تكون قد شاهدت صورا مذهلة لـ لوفوتين وفيستيرالن (مملكة الحيتان) على انستغرام ، وكنصيحة مهمة عليكم زيارة هذه الأماكن خارج موسم الصيف عندما تختفي الحشود",
      en: "Stunning peaks, glittering fjords, authentic fishing villages and picture-perfect beaches, not to mention the northern lights and the midnight sun. You have probably seen breathtaking photos of Lofoten and Vesterålen — the kingdom of the whales — on Instagram, and an important tip is to visit outside the summer season, when the crowds disappear.",
    },
    {
      type: "P",
      ar: "تنتظرك أيضا مغامرات خارجية من المستوى التالي في جنة نارفيك للتزلج وركوب الدراجات والمشي لمسافات طويلة ، وهناك جوهرة أقل شهرة هي هيلجيلاند في الجنوب قليلا ، هناك يمكنك القيادة على الطريق الساحلي بين ترونديلاغ وبودو ، الذي تم التصويت عليه كأحد أكثر الطرق الخلابة في العالم",
      en: "Next-level outdoor adventures also await in the Narvik paradise for skiing, cycling and hiking, and a lesser-known gem is Helgeland a little to the south, where you can drive the coastal road between Trøndelag and Bodø, voted one of the most scenic roads in the world.",
    },
    {
      type: "P",
      ar: "تعد مدينة بودو الساحلية النابضة بالحياة أكبر مدينة في مقاطعة نوردلاند وتوفر الكثير من المرح في الهواء الطلق في منطقة سالتن القريبة بالاضافة الى مشهد ثقافي مزدهر ، في الواقع أصبحت بودو عاصمة الثقافة الأوروبية في عام 2024م",
      en: "The lively coastal city of Bodø is the largest in Nordland county and offers plenty of outdoor fun in the nearby Salten area as well as a thriving cultural scene — in fact Bodø became a European Capital of Culture in 2024.",
    },
    { type: "IMG", src: U("2023/04/img_0515.jpg"), cap_ar: "لوفوتين", cap_en: "Lofoten", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0513.jpg"), cap_ar: "لوفوتين", cap_en: "Lofoten", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0511.jpg"), cap_ar: "نوردلاند", cap_en: "Nordland", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0509.jpg"), cap_ar: "نوردلاند", cap_en: "Nordland", size: "compact" },
    {
      type: "H3",
      ar: "بيرغن والمضايق الغربية",
      en: "Bergen and the western fjords",
      sub_ar: "Bergen and the western fjords",
      sub_en: "بيرغن والمضايق الغربية",
    },
    {
      type: "P",
      ar: "تلتقي مواقع التراث العالمي التاريخية بالموضة المبتكرة والمطاعم العصرية والمشهد الموسيقي التقدمي في بيرغن ، ثاني أكبر مدينة في النرويج ، قم بزيارة بعض أفضل المتاحف في البلاد مثل متاحف KODE الفنية ومنازل الملحنين ، وانغمس في الشوارع المرصوفة بالحصى ، واستمتع بتجربة المدينة من الأعلى في أحد قمم الجبال السبعة المحيطة",
      en: "Historic world heritage sites meet innovative fashion, modern restaurants and a progressive music scene in Bergen, Norway's second largest city. Visit some of the country's finest museums such as the KODE art museums and the composers' homes, lose yourself in the cobbled streets, and experience the city from above on one of the seven surrounding mountain peaks.",
    },
    {
      type: "P",
      ar: "تعتبر بيرغن بوابة لبعض أشهر المضايق في النرويج ، بما في ذلك مضيق سوجنيفيورد ، وهو أطول وأعمق مضيق في النرويج في الشمال ، ومضيق هاردانجر – حيث ستجد صخرة ترولتونغا الشهيرة – في الجنوب ، تحتوي العديد من المضايق البحرية على أفرع جانبية جميلة ولكنها أقل ازدحاما",
      en: "Bergen is the gateway to some of Norway's most famous fjords, including the Sognefjord — Norway's longest and deepest — to the north, and the Hardangerfjord, home to the famous Trolltunga rock, to the south. Many of the fjords have side arms that are just as beautiful but far less crowded.",
    },
    {
      type: "P",
      ar: "سافر الى قرية المضيق فلام مع خط بيرغن وخط فلام ، وقد تم التصويت عليهما كواحدة من أجمل رحلات القطارات في العالم ، وللاستمتاع في الهواء الطلق في محيط ملحمي قم بزيارة فوس ونوردفيورد",
      en: "Travel to the fjord village of Flåm on the Bergen Line and the Flåm Line, voted among the most beautiful train journeys in the world, and for outdoor fun in epic surroundings visit Voss and Nordfjord.",
    },
    { type: "IMG", src: U("2023/04/img_0522.jpg"), cap_ar: "بيرغن والمضايق الغربية", cap_en: "Bergen and the western fjords", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0520.jpg"), cap_ar: "بيرغن والمضايق الغربية", cap_en: "Bergen and the western fjords", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0518.jpg"), cap_ar: "بيرغن والمضايق الغربية", cap_en: "Bergen and the western fjords", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0516.jpg"), cap_ar: "بيرغن والمضايق الغربية", cap_en: "Bergen and the western fjords", size: "compact" },
    {
      type: "H3",
      ar: "الشمال الغربي وغيرانغرفيورد",
      en: "The Geirangerfjord and the Northwest",
      sub_ar: "The Geirangerfjord and the Northwest",
      sub_en: "الشمال الغربي وغيرانغرفيورد",
    },
    {
      type: "P",
      ar: "تعتبر بلدة أليسوند الخلابة على طراز فن الآرت نوفو نقطة انطلاق مثالية لمغامرة المضيق البحري في الشمال الغربي ، وتقع في الجزء الشمالي من مضايق النرويج ، تجذب هذه المنطقة هواة الهواء الطلق على مدار السنة ، من أليسوند يمكنك الذهاب بالقارب أو الحافلة الى غيرانغرفيورد المصنف من قبل منظمة اليونسكو ، أشهر مضيق في النرويج ، مع شلالات الأخوات السبع والعديد من الشلالات الأخرى التي تنحدر من سفوح الجبال شديدة الانحدار",
      en: "The picturesque art nouveau town of Ålesund is a perfect starting point for a fjord adventure in the Northwest, in the northern part of Norway's fjord region, and the area draws outdoor enthusiasts year-round. From Ålesund you can travel by boat or bus to the UNESCO-listed Geirangerfjord, Norway's most famous fjord, with the Seven Sisters and many other waterfalls tumbling down its steep mountainsides.",
    },
    {
      type: "P",
      ar: "تعتبر عاصمة تسلق الجبال أوندالسنيس قاعدة مثالية أخرى هنا ، حيث انها محاطة بقمم مذهلة (يمكنك الصعود الى الأعلى بجندول) ، وتقع على بعد مسافة قصيرة فقط من مناطق الجذب الشهيرة عالميا مثل طريق ترولستيغن الجبلي وطريق الأطلسي ، وأوندالسنيس هي نقطة النهاية لسكة حديد راوما وقد تم التصويت عليها كواحدة من أجمل رحلات القطارات في العالم ، ويعد الشمال الغربي أيضا موطنا لمدينة موسيقى الجاز مولدي وعاصمة سمك القد المجفف كريستيانسوند",
      en: "The mountaineering capital of Åndalsnes is another perfect base here, surrounded by stunning peaks — you can ride a gondola to the top — and only a short distance from world-famous attractions such as the Trollstigen mountain road and the Atlantic Road. Åndalsnes is the end point of the Rauma railway, voted one of the most beautiful train journeys in the world, and the Northwest is also home to the jazz city of Molde and the klipfish capital Kristiansund.",
    },
    { type: "IMG", src: U("2023/04/img_0530.jpg"), cap_ar: "غيرانغرفيورد", cap_en: "The Geirangerfjord", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0528.jpg"), cap_ar: "غيرانغرفيورد", cap_en: "The Geirangerfjord", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0526.jpg"), cap_ar: "الشمال الغربي", cap_en: "The Northwest", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0524.jpg"), cap_ar: "الشمال الغربي", cap_en: "The Northwest", size: "compact" },
    {
      type: "H3",
      ar: "منطقة ستافنجر",
      en: "The Stavanger region",
      sub_ar: "The Stavanger region",
      sub_en: "منطقة ستافنجر",
    },
    {
      type: "P",
      ar: "ماذا ستحصل اذا جمعت بين مطاعم ميشلان وبيوت خشبية قديمة ، وفن شوارع عالمي المستوى ، وأجواء رائعة متعددة الثقافات ؟ سافر الى ستافنجر للحصول على الاجابة ، ستافنجر هي أكبر مدينة في الجزء الجنوبي الغربي من البلاد ، ونقطة انطلاق مثالية اذا كنت ترغب في الخروج الى مناطق الجذب الطبيعية الشهيرة مثل ليسفيورد وبريكستولن (صخرة المنبر)",
      en: "What do you get if you combine Michelin restaurants, old wooden houses, world-class street art and a wonderful multicultural atmosphere? Travel to Stavanger for the answer. Stavanger is the largest city in the south-west of the country and a perfect starting point if you want to head out to famous natural attractions such as the Lysefjord and Preikestolen, the Pulpit Rock.",
    },
    {
      type: "P",
      ar: "تعد منطقة ييرين الساحلية جنة الشاطئ ، وهي موطن لبعض من أوسع شواطئ النرويج وأكثرها بياضا ، كما سيجد عشاق ركوب الأمواج والطائرات الورقية ما يستمتعون به ، اتبع طريق بحر الشمال باتجاه ايغرسوند واكتشف كيف تقع المدن والقرى الساحرة ، مثل سوغندالستراند الخلابة ، واحدة تلو الأخرى مثل سلسلة من اللآلئ على طول الساحل",
      en: "The coastal Jæren region is a beach paradise, home to some of Norway's widest and whitest beaches, and surfing and kite fans will find plenty to enjoy. Follow the North Sea Road towards Egersund and discover how charming towns and villages, such as picturesque Sogndalstrand, follow one another like a string of pearls along the coast.",
    },
    { type: "IMG", src: U("2023/04/img_0534.jpg"), cap_ar: "منطقة ستافنجر", cap_en: "The Stavanger region", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0533.jpg"), cap_ar: "منطقة ستافنجر", cap_en: "The Stavanger region", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0532.jpg"), cap_ar: "منطقة ستافنجر", cap_en: "The Stavanger region", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0531.jpg"), cap_ar: "منطقة ستافنجر", cap_en: "The Stavanger region", size: "compact" },
    {
      type: "H3",
      ar: "تروندهايم وترونديلاغ",
      en: "Trondheim and Trøndelag",
      sub_ar: "Trondheim and Trøndelag",
      sub_en: "تروندهايم وترونديلاغ",
    },
    {
      type: "P",
      ar: "تجذب منطقة ترونديلاغ ، الواقعة في وسط النرويج ، هواة التاريخ المتشددين ، وعشاق الطعام المخلصين ، ومستكشفي الطبيعة النشطين على حد سواء ، يمكنك الذهاب لصيد الأسماك أو ركوب الدراجات أو التزلج أو التنزه سيرا على الأقدام في أحد مسارات الحجاج التسعة وهي طرق القديس أولاف ، والتي تؤدي جميعها الى كاتدرائية نيداروس المذهلة في تروندهايم",
      en: "The Trøndelag region in central Norway attracts hardcore history fans, devoted foodies and active nature explorers alike. You can go fishing, cycling, skiing or walking on one of the nine pilgrim paths, the St Olav Ways, all of which lead to the stunning Nidaros Cathedral in Trondheim.",
    },
    {
      type: "P",
      ar: "مدينة تروندهايم الطلابية النابضة بالحياة هي عاصمة المنطقة ، وتعرف باسم موطن النكهات الاسكندنافية ، انغمس في تجارب تذوق الطعام بدءا من مطاعم ميشلان الفاخرة الى حانات الطعام العصرية والمقاهي المريحة ، اتبع رائحة المنتجات المحلية الطازجة على الطريق الدائري الخلاب الطريق الذهبي في اينهيريد ، وسافر بالزمن الى الوراء في مدينة التعدين رورس المدرجة في قائمة اليونسكو ، وفي جبال دوفريفييل يمكنك القاء نظرة على ثيران المسك",
      en: "The lively student city of Trondheim is the regional capital and is known as the home of Nordic flavours. Immerse yourself in food experiences from fine Michelin restaurants to modern food halls and cosy cafés, follow the scent of fresh local produce along the scenic circular route known as the Golden Road in Innherred, travel back in time in the UNESCO-listed mining town of Røros, and in the Dovrefjell mountains you can catch sight of musk oxen.",
    },
    { type: "IMG", src: U("2023/04/img_0540.jpg"), cap_ar: "تروندهايم", cap_en: "Trondheim", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0538.jpg"), cap_ar: "تروندهايم", cap_en: "Trondheim", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0537.jpg"), cap_ar: "ترونديلاغ", cap_en: "Trøndelag", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0535.jpg"), cap_ar: "ترونديلاغ", cap_en: "Trøndelag", size: "compact" },
    {
      type: "H3",
      ar: "كريستيانساند وجنوب النرويج",
      en: "Kristiansand and Southern Norway",
      sub_ar: "Kristiansand and Southern Norway",
      sub_en: "كريستيانساند وجنوب النرويج",
    },
    {
      type: "P",
      ar: "جنوب النرويج هي الجنة الصيفية للنرويجيين ، مع الشواطئ الجميلة ، والآلاف من الجزر ، وساعات شمس في السنة أكثر من معظم أجزاء البلاد الأخرى ، تجول في الشوارع الضيقة بين المنازل الخشبية البيضاء في المدن الساحلية الساحرة مثل ريسور وأريندال وغريمستاد وماندال وفليكفيورد ، أو تعرف على مهد التقاليد الشعبية النرويجية في وادي سيتيسدال ، أكبر مدينة في جنوب النرويج هي كريستيانساند ، حيث يمكنك التجول في مدينة بوسيبين القديمة ، والاستمتاع بالمأكولات البحرية الطازجة ، والاستمتاع بأيام هادئة على شاطئ المدينة",
      en: "Southern Norway is the Norwegians' summer paradise, with beautiful beaches, thousands of islands and more hours of sunshine a year than most other parts of the country. Wander the narrow streets between the white wooden houses of charming coastal towns such as Risør, Arendal, Grimstad, Mandal and Flekkefjord, or discover the cradle of Norwegian folk traditions in the Setesdal valley. The largest city in Southern Norway is Kristiansand, where you can stroll through the old town of Posebyen, enjoy fresh seafood and spend lazy days on the city beach.",
    },
    {
      type: "P",
      ar: "وحضور العديد من المهرجانات الممتعة ، حديقة حيوان ديريباركن ومدينة الملاهي هي الفائز المؤكد بين الصغار ، وعلى بعد مسافة قصيرة بالسيارة من كريستيانساند تقع منارة ليندسنس ، أقصى نقطة في جنوب النرويج ، وليندسنس هو أيضا المكان الذي ستجد فيه المطعم المتميز الحاصل على نجمة ميشلان Under ، أكبر مطعم تحت الماء في العالم",
      en: "There are also many enjoyable festivals to attend, and the Dyreparken zoo and amusement park is a sure winner with the little ones. A short drive from Kristiansand stands the Lindesnes lighthouse, the southernmost point of Norway, and Lindesnes is also where you will find the Michelin-starred restaurant Under, the largest underwater restaurant in the world.",
    },
    { type: "IMG", src: U("2023/04/img_0551-1.jpg"), cap_ar: "جنوب النرويج", cap_en: "Southern Norway", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0549-1.jpg"), cap_ar: "جنوب النرويج", cap_en: "Southern Norway", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0545-1.jpg"), cap_ar: "كريستيانساند", cap_en: "Kristiansand", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0541-1.jpg"), cap_ar: "كريستيانساند", cap_en: "Kristiansand", size: "compact" },
    {
      type: "H3",
      ar: "جبال ووديان شرق النرويج",
      en: "The mountains and valleys of Eastern Norway",
      sub_ar: "The mountains and valleys of Eastern Norway",
      sub_en: "جبال ووديان شرق النرويج",
    },
    {
      type: "P",
      ar: "تعد الغابات الكثيفة والوديان العميقة والهضاب الجبلية الضخمة في شرق النرويج كلها نقاط انطلاق ممتازة لمغامرات الطبيعة المختلفة ، هذا هو المكان الذي تجد فيه بعضا من أكبر منتجعات التزلج في النرويج ، مثل جيلو وتريسيل وهيمسيدال ، وهي تضمن الاستمتاع طوال العام حيث تتحول الى وجهات لركوب الدراجات على مستوى عالمي بمجرد اختفاء الثلج",
      en: "The dense forests, deep valleys and vast mountain plateaus of Eastern Norway are all excellent starting points for different nature adventures. This is where you find some of Norway's largest ski resorts, such as Geilo, Trysil and Hemsedal, and they guarantee year-round enjoyment as they turn into world-class cycling destinations once the snow disappears.",
    },
    {
      type: "P",
      ar: "تعد فالدرس وهالينغدال وليلهامر وغودبراندسدالن وجهات عائلية شهيرة تقدم كل شيء من المتنزهات الترفيهية الى المزارع الساحرة والمشي لمسافات طويلة ، الشيء نفسه ينطبق على تيليمارك ، حيث يمكنك الذهاب في رحلة بحرية في قناة تيليمارك ومشاهدة واحد من أكثر المناظر اثارة للاعجاب في شرق النرويج من جبل غاوستاتوبن ، وتوفر المتنزهات الوطنية في دوفريفييل ويوتنهايمن ورونداني فرصا ممتازة للأنشطة القائمة على الطبيعة مثل المشي لمسافات طويلة وركوب الدراجات والتجديف والتسلق",
      en: "Valdres, Hallingdal, Lillehammer and Gudbrandsdalen are popular family destinations offering everything from amusement parks to charming farms and hiking, and the same is true of Telemark, where you can cruise the Telemark Canal and see one of Eastern Norway's most impressive views from Mount Gaustatoppen. The national parks of Dovrefjell, Jotunheimen and Rondane offer excellent opportunities for nature-based activities such as hiking, cycling, rafting and climbing.",
    },
    { type: "IMG", src: U("2023/04/img_0555.jpg"), cap_ar: "شرق النرويج", cap_en: "Eastern Norway", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0554.jpg"), cap_ar: "شرق النرويج", cap_en: "Eastern Norway", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0553.jpg"), cap_ar: "شرق النرويج", cap_en: "Eastern Norway", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0552.jpg"), cap_ar: "شرق النرويج", cap_en: "Eastern Norway", size: "compact" },
    {
      type: "H3",
      ar: "جزر سفالبارد",
      en: "The Svalbard Islands",
      sub_ar: "The Svalbard Islands",
      sub_en: "جزر سفالبارد",
    },
    {
      type: "P",
      ar: "هل أنت مستعد لنقل الحياة البرية الى المستوى التالي ؟ تقع جزر سفالبارد في منتصف المحيط المتجمد الشمالي ، في منتصف الطريق بين النرويج والقطب الشمالي ، هنا يمكنك المشاركة في الأنشطة الغريبة القائمة على الطبيعة على مدار السنة في مناظر طبيعية وعرة وهشة ، جرب يدك في التزلج على الجليد أو الذهاب لاستكشاف الجليد أو الانضمام الى رحلة سفاري على الجليد أو البحث عن الأضواء الشمالية ، بالاضافة الى بضعة آلاف من الدببة القطبية ، فان الجزر هي موطن لما يقرب من 3000 شخص ، وتعد مدينة لونغييربين الرئيسية مدينة صغيرة ملونة تقدم مجموعة واسعة من الأنشطة الثقافية والأماكن عالية الجودة لتناول الطعام والشراب والتي عادة ما تتوقع أن تجدها فقط في المدن الكبرى",
      en: "Ready to take wildlife to the next level? The Svalbard Islands lie in the middle of the Arctic Ocean, halfway between Norway and the North Pole. Here you can take part in extraordinary nature-based activities all year round in a rugged, fragile landscape: try dog sledding, go ice caving, join a snowmobile safari or hunt for the northern lights. Along with a few thousand polar bears, the islands are home to around 3,000 people, and the main town of Longyearbyen is a small, colourful place offering a wide range of cultural activities and high-quality places to eat and drink that you would usually expect only in big cities.",
    },
    { type: "IMG", src: U("2023/04/img_0561.jpg"), cap_ar: "جزر سفالبارد", cap_en: "The Svalbard Islands", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0559.jpg"), cap_ar: "جزر سفالبارد", cap_en: "The Svalbard Islands", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0557.jpg"), cap_ar: "جزر سفالبارد", cap_en: "The Svalbard Islands", size: "compact" },
    { type: "IMG", src: U("2023/04/img_0556.jpg"), cap_ar: "جزر سفالبارد", cap_en: "The Svalbard Islands", size: "compact" },
  ],
};

// أطباق وأكلات نرويجية (source p=34981)
const norwegianFood: Guide = {
  slug: "norwegian-food",
  title_ar: "أطباق وأكلات نرويجية – تعرف على فن الطهو النرويجي",
  title_en: "Norwegian dishes and food — the art of Norwegian cooking",
  kicker_ar: "أطباق وأكلات",
  kicker_en: "Dishes and food",
  image: U("2023/04/img_0775.jpg"),
  blocks: [
    {
      type: "H3",
      ar: "هل أنت جائع ؟ اذا هيا بنا في رحلة استكشافية للأكلات المفضلة لدى الشعب النرويجي",
      en: "Hungry? Then let's set off on a journey through the Norwegians' favourite food",
      noNumber: true,
    },
    { type: "H3", ar: "كان هناك تغيير هائل في المواقف تجاه التقاليد الغذائية", en: "Attitudes to food traditions have changed enormously" },
    {
      type: "P",
      ar: "المواقف تجاه التقاليد الغذائية في النرويج تغيرت في السنوات الأخيرة ، اليوم يحتفلون بما هو نرويجي فريد من الناحية الحديثة وغير التقليدية ، فعندما يتعلق الأمر بالطعام والشراب في النرويج ، فقد حدثت ثورة طهي بهدوء في السنوات القليلة الماضية ، وشهدت المطاعم والمطابخ العادية ارتفاعا دراماتيكيا في الأغذية المحلية والعضوية",
      en: "Attitudes to food traditions in Norway have changed in recent years, and today Norwegians celebrate what is uniquely Norwegian in a modern, unconventional way. When it comes to food and drink in Norway, a culinary revolution has quietly taken place over the past few years, and both restaurants and ordinary kitchens have seen a dramatic rise in local and organic food.",
    },
    { type: "H3", ar: "ما يميز الطهي النرويجي حقا", en: "What really makes Norwegian cooking distinctive" },
    {
      type: "P",
      ar: "موجود الى حد كبير في عاداتهم الزراعية الفريدة الى حد ما : الأغنام والأبقار والماعز ترعى في المراعي الخارجية على طول الساحل وفي الجبال ، يعد المناخ البارد والأرض غير الملوثة مثاليا للزراعة البطيئة للخضروات والفواكه والتوت دون الاستخدام المكثف للمبيدات الحشرية",
      en: "It lies largely in their rather unique farming habits: sheep, cattle and goats graze on outlying pastures along the coast and in the mountains, and the cold climate and unpolluted land are ideal for the slow growing of vegetables, fruit and berries without heavy use of pesticides.",
    },
    {
      type: "P",
      ar: "المزارع المتواضعة والصغيرة التي تنتج الحليب والجبن ولحم البقر تتم في بيئات صحية خالية تقريبا من الأمراض ، وتخضع للوائح صارمة عندما يتعلق الأمر برعاية الحيوانات ، وبالطبع يمنح الساحل الواسع النرويج مأكولات بحرية طويلة وغنية",
      en: "The modest, small farms producing milk, cheese and beef work in healthy environments almost free of disease and under strict regulations on animal welfare, and of course the vast coastline gives Norway a long, rich seafood tradition.",
    },
    { type: "IMG", src: U("2023/04/img_0775.jpg"), cap_ar: "أحد المخبوزات النرويجية الشهية", cap_en: "One of the delicious Norwegian bakes" },
    { type: "H3", ar: "لقد أتى العمل الشاق لغرس الفخر بثماره", en: "The hard work of instilling pride has paid off" },
    {
      type: "P",
      ar: "على كل مستوى من مستويات السلسلة الغذائية ثماره حقا ، يظهر منتجون جدد صغار الحجم للجبن والعسل والمعجنات وعصير التفاح واللحوم المنتجة بيئيا ، من بين أمور أخرى ، في جميع أنحاء البلاد ، ناهيك عن مئات مصانع الجعة الصغيرة التي تجرب أنواعا مختلفة من الشراب ، ونظرا لأن النرويج من بين أكبر ثلاث دول مستهلكة للقهوة في العالم ، فليس من المستغرب أنهم يحاولون باستمرار تحضير أفضل أنواع القهوة على هذا الكوكب",
      en: "At every level of the food chain the effort has truly borne fruit. New small-scale producers of cheese, honey, pastries, cider and environmentally produced meat, among other things, are appearing all over the country, not to mention hundreds of microbreweries experimenting with different brews. And since Norway is among the world's three biggest coffee-consuming nations, it is no surprise that they constantly try to make the best coffee on the planet.",
    },
    { type: "H3", ar: "وفي الوقت نفسه اكتسب النرويجيون سمعة دولية هائلة", en: "Meanwhile, Norwegians have gained an enormous international reputation" },
    {
      type: "P",
      ar: "فالنرويج هي البلد الأكثر حصولا على جوائز في تاريخ مسابقة الطهي الدولية Bocuse d'Or ، وفي عام 2016م أصبح مطعم Maaemo أول مطعم نرويجي يحصل على جميع النجوم الثلاثة من قبل دليل ميشلان",
      en: "Norway is the most awarded country in the history of the Bocuse d'Or international cooking competition, and in 2016 Maaemo became the first Norwegian restaurant to receive all three Michelin stars.",
    },
    { type: "H3", ar: "اختر عجينة بول المفضلة لديك", en: "Choose your favourite bolle" },
    {
      type: "P",
      ar: "تحذير : قد يكون ذلك مسببا للادمان ، سواء كنت في سفر ، أو حفلة عيد ميلاد ، أو تتناول وجبة خفيفة بعد العمل ، أو تكافئ نفسك مكافأة صغيرة في يوم صعب ، ستجد دائما هناك أشياء لذيذة من أجلك",
      en: "A warning: this can be highly addictive. Whether you are travelling, at a birthday party, having a snack after work or giving yourself a small reward on a hard day, there is always something delicious waiting for you.",
    },
    {
      type: "IMG",
      src: U("2023/04/img_0776.jpg"),
      cap_ar: "في النرويج يحبون هذه العجائب الصغيرة اللزجة من كعكة الخميرة ، هل تشعرون بلمحة من الهيل فيها ؟ ففي بعض الأحيان يضاف اليها المزيد من الزبدة والسكر وكميات من القرفة",
      cap_en: "In Norway they love these small sticky wonders of yeast cake — can you taste a hint of cardamom? Sometimes more butter, sugar and plenty of cinnamon are added.",
    },
    { type: "H3", ar: "يمكن أن تغري الكعك الحجر", en: "Buns that could tempt a stone" },
    {
      type: "P",
      ar: "تقول بوديل نوردجور ، مؤلفة كتب الطبخ النرويجية والمتحمسة للكعك ، التي فازت بالعديد من الجوائز لعملها مع ثقافة الطعام النرويجية : ببساطة ان الكعك النرويجي لا يقاوم ، فالعجائب الصغيرة هذه يمكن أن تغري حجرا ، وتجعل العالم أفضل قليلا لبضع دقائق",
      en: "Bodil Nordjore, the Norwegian cookbook author and bun enthusiast who has won many awards for her work with Norwegian food culture, says simply that Norwegian buns are irresistible: these little wonders could tempt a stone, and they make the world a little better for a few minutes.",
    },
    { type: "H3", ar: "عجينة بول بالزعفران", en: "Saffron buns" },
    {
      type: "IMG",
      src: U("2023/04/img_0778.jpg"),
      cap_ar: "في شهر ديسمبر من كل عام يضيفون شيئا مميزا الى عجينة بول : الزعفران ، ويطلقون على كعك الزعفران على شكل حرف S اسم Lussekatter ، وهي مصنوعة للاحتفال بيوم القديسة لوسي في 13 ديسمبر",
      cap_en: "Every December something special is added to the bolle dough: saffron. The S-shaped saffron buns are called lussekatter and are made to celebrate St Lucy's Day on 13 December.",
    },
    { type: "H3", ar: "كعك محشو بكاسترد الفانيليا المخملي", en: "Buns filled with velvety vanilla custard" },
    {
      type: "IMG",
      src: U("2023/04/img_0779.jpg"),
      cap_ar: "مفضل آخر هو Skolebrød ، كعك كبير محشو بكاسترد الفانيليا المخملي ومزين بالجليد ومغموس بجوز الهند المبشور",
      cap_en: "Another favourite is skolebrød, a large bun filled with velvety vanilla custard, iced and dipped in grated coconut.",
    },
    { type: "H3", ar: "كعك القرفة الوردية", en: "Pink cinnamon buns" },
    {
      type: "IMG",
      src: U("2023/04/img_0780.jpg"),
      cap_ar: "يمكن أن تكون الكعكة حتى بيانا للأزياء ، فسرعان ما أصبحت كعكات القرفة المزججة الوردية لنيكولين ليشولم من أوسلو والتي تسمى Skillings نجاحا كبيرا على وسائل التواصل الاجتماعي عندما أطلقتها في ربيع عام 2020م ، وفي غضون أيام كان صف من الناس ينتظرون كعكة طازجة",
      cap_en: "A bun can even be a fashion statement: the pink-glazed cinnamon buns by Oslo's Nikoline Lisholm, called skillings, quickly became a social media hit when she launched them in spring 2020, and within days people were queuing for a fresh one.",
    },
    { type: "H3", ar: "كيف يحب الخبراء الكعك ؟", en: "How do the experts like their buns?" },
    {
      type: "P",
      ar: "من الآمن القول أنه يمكنك الاستمتاع بثقافة الكعك في أي مكان في النرويج ، حتى في ظاهرة Maaemo الحاصلة على نجوم ميشلان ، وينظر الى المطعم على نطاق واسع على أنه أفضل مطعم في النرويج وفي طليعة المطبخ الاسكندنافي ، وبعد اعادة فتحه في بيورفيكا العصرية في أوسلو أضاف الطاهي كعك القرفة الى القائمة",
      en: "It is safe to say you can enjoy bun culture anywhere in Norway, even at the Michelin-starred phenomenon Maaemo, widely regarded as the best restaurant in Norway and at the forefront of Nordic cuisine. After reopening in trendy Bjørvika in Oslo, the chef added cinnamon buns to the menu.",
    },
    {
      type: "P",
      ar: "بعد أن يتم تقديم وجبة حياتهم ، يتم اصطحاب الضيوف الى غرفة جديدة حيث تتزايد القهوة وكعك القرفة ، وحتى بعد عشاء مكون من 15 طبقا ، لا يمكن لأحد أن يقاوم كعكة القرفة الطازجة التي تشعر وكأنها عناق لذوقك",
      en: "After being served the meal of their lives, guests are led into another room where the coffee and cinnamon buns keep coming, and even after a fifteen-course dinner nobody can resist a fresh cinnamon bun that feels like a hug for your taste buds.",
    },
    {
      type: "IMG",
      src: U("2023/04/img_0781-1.jpg"),
      cap_ar: "الشعب النرويجي يعشق تذوق الكعكات بمختلف مذاقاتها",
      cap_en: "Norwegians love tasting buns in all their flavours",
    },
    { type: "H3", ar: "اصنع كعك القمح في المنزل", en: "Make wheat buns at home" },
    {
      type: "IMG",
      src: U("2023/04/img_0782.jpg"),
      cap_ar: "حاول أن تصنع هذه الكعكات الحلوة والرقيقة واللذيذة في المنزل ، فهي سهلة الصنع",
      cap_en: "Try making these sweet, soft and delicious buns at home — they are easy to make.",
    },
    { type: "H3", ar: "قاموس بعض الأكلات النرويجية", en: "A glossary of some Norwegian bakes" },
    {
      type: "LIST",
      ar: [
        "الكعك الحلو – Hveteboller",
        "كعك حلو مع الزبيب – Rosinboller",
        "الكعك الحلو مع الشوكولاتة – Sjokoladeboller",
        "كعك كبير مخبوز مع حشوة القرفة والسكر – Kanelboller / kanelsnurrer / kanelknuter",
        "كعك القرفة من بيرغن في مضايق النرويج ، تم احضاره لأول مرة من ألمانيا في الفترة الهانزية قبل 500 عام ، ولا يزال متاحا على نطاق واسع ، ويجب تناوله عند التواجد في بيرغن – Skillingsboller",
        "تترجم الى كعكات المدرسة ، خبز كبير بالكاسترد وجوز الهند المبشور – Skolebrød",
        "كعك كبير مع شمس من الكاسترد الذي يعمل كطقس مرور عندما تعود الشمس بعد الليل القطبي في شمال النرويج – Solboller",
        "كعك حلو محشو بالكريمة أو المربى ويتم تقديمه للاحتفال ببداية الأربعين يوما من الصوم الكبير – Fastelavnsboller",
        "كعكة حلم مصنوعة من الكعك مع دوامات القرفة والكاسترد وتزجيج كثيف – Prinsessekake",
        "كعك مقلي على شكل دونات بدون ثقب مركزي ومليء بالمربى أو الشوكولاتة – Berlinerboller",
      ],
      en: [
        "Sweet buns – hveteboller",
        "Sweet buns with raisins – rosinboller",
        "Sweet buns with chocolate – sjokoladeboller",
        "Large buns baked with a cinnamon and sugar filling – kanelboller / kanelsnurrer / kanelknuter",
        "Cinnamon buns from Bergen in the Norwegian fjords, first brought from Germany in the Hanseatic period 500 years ago, still widely available and a must when you are in Bergen – skillingsboller",
        "Translating as school bread, a large bun with custard and grated coconut – skolebrød",
        "A large bun with a sun of custard, a rite of passage when the sun returns after the polar night in northern Norway – solboller",
        "Sweet buns filled with cream or jam, served to mark the beginning of the forty days of Lent – fastelavnsboller",
        "A dream of a cake made from buns with cinnamon swirls, custard and thick icing – prinsessekake",
        "Fried buns shaped like doughnuts without a central hole and filled with jam or chocolate – berlinerboller",
      ],
    },
  ],
};

// ألبوم الصور (source p=35033)
const albumImages = [
  "2023/04/img_0716-1.jpg",
  "2023/04/img_0695.jpg",
  "2023/04/img_0686.jpg",
  "2023/04/img_0677-1.jpg",
  "2023/04/img_0676-1.jpg",
  "2023/04/img_0679-1.jpg",
  "2023/04/img_0683-1.jpg",
  "2023/04/img_0691.jpg",
  "2023/04/img_0692-1.jpg",
  "2023/04/img_0693-1.jpg",
  "2023/04/img_0724-1.jpg",
  "2023/04/img_0733-1.jpg",
  "2023/04/img_0738-2.jpg",
  "2023/04/img_0742-1.jpg",
  "2023/04/img_0745-2.jpg",
  "2023/04/img_0748-1.jpg",
  "2023/04/img_0749-1.jpg",
  "2023/04/img_0757-1.jpg",
  "2023/04/img_0758-1.jpg",
  "2023/04/img_0785-1.jpg",
  "2023/04/img_0790.jpg",
  "2023/04/img_0607-1.jpg",
  "2023/04/img_0610-1.jpg",
  "2023/04/img_0614-1.jpg",
  "2023/04/img_0631-1.jpg",
  "2023/04/img_0636-2.jpg",
  "2023/04/img_0639-1.jpg",
  "2023/04/img_0648-2.jpg",
  "2023/04/img_0649-1.jpg",
  "2023/04/img_0661-1.jpg",
  "2023/04/img_0597-1.jpg",
  "2023/04/img_0605-1.jpg",
  "2023/04/img_0570-2.jpg",
  "2023/04/img_0571-1.jpg",
  "2023/04/img_0524-1.jpg",
  "2023/04/img_0536-1.jpg",
  "2023/04/img_0507-2.jpg",
  "2023/04/img_0508-1.jpg",
];

const photoAlbum: Guide = {
  slug: "photo-album",
  title_ar: "السياحة في النرويج – ألبوم الصور",
  title_en: "Tourism in Norway — the photo album",
  kicker_ar: "ألبوم الصور",
  kicker_en: "Photo album",
  image: U("2023/04/img_0692.jpg"),
  blocks: [
    {
      type: "H3",
      ar: "صور من النرويج",
      en: "Photos from Norway",
      noNumber: true,
      sub_ar: "صور من واقع الحياة بالنرويج ، لتعطي تصورا عن واقع الحياة في ذلك البلد الراقي",
      sub_en: "Photographs of everyday life in Norway, to give a sense of what life is really like in that refined country",
    },
  ],
  gallery: albumImages.map((n) => ({ src: U(n), cap_ar: "صور من النرويج", cap_en: "Photos from Norway" })),
};

export const norwayMoreGuides: Guide[] = [samiCulture, norwayBrief, topTenPlaces, norwegianFood, photoAlbum];
