import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

export const norwayGuides: Guide[] = [
  {
    slug: "train-journeys",
    title_ar: "تعرف على بعض من أفضل رحلات القطار في العالم",
    title_en: "Some of the finest train journeys in the world",
    kicker_ar: "رحلة القطار النرويجية",
    kicker_en: "The Norwegian train trip",
    image: U("2023/04/img_0660.jpg"),
    blocks: [
      {
        type: "P",
        ar: "اركب براحة الى المضايق البحرية المذهلة ، عبر الجبال ، الى الجنوب الجميل ، وشمال الدائرة القطبية الشمالية ، توفر خطوط السكك الحديدية الثمانية هذه ، مناظر خلابة على طول الطريق ، تصنف العديد من الخطوط في النرويج باستمرار من بين أفضل رحلات القطار في العالم",
        en: "Ride in comfort to the stunning fjords, across the mountains, down to the beautiful south and north of the Arctic Circle. These eight railway lines offer breathtaking views all the way, and many of Norway's lines are consistently ranked among the best train journeys in the world.",
      },
      {
        type: "P",
        ar: "يتعلق ركوب القطار في النرويج بالمناظر الفريدة والجميلة التي تستمتع بها على طول الطريق ، بقدر ما يتعلق بالوصول الى وجهتك ، تصنف العديد من خطوط السكك الحديدية النرويجية من بين أجمل رحلات القطار في العالم ، وفقا للونلي بلانيت وغيرها",
        en: "Taking the train in Norway is as much about the unique and beautiful scenery you enjoy along the way as it is about reaching your destination. Many Norwegian railway lines are ranked among the most beautiful train journeys in the world, according to Lonely Planet and others.",
      },
      {
        type: "P",
        ar: "رحلات القطار مثل خط نوردلاند وخط بيرغن تقدم أكثر بكثير من مجرد وسائل النقل ، بصفتك راكبا ، تقترب من المناظر الطبيعية والثقافة على طول المسارات بطريقة مستحيلة في وسائل النقل الأخرى",
        en: "Journeys such as the Nordland Line and the Bergen Line offer far more than transport. As a passenger you come close to the landscape and the culture along the tracks in a way that is impossible by other means.",
      },
      {
        type: "P",
        ar: "كتب جان هيلج أوستلوند العديد من الكتب عن رحلات القطار النرويجية وتاريخ السكك الحديدية ، توفر سويسرا والنمسا منافسة شديدة ، لكنني ما زلت أقول : ان النرويج وجهة ممتازة للسكك الحديدية الأوروبية ، قد يكون لديهم قطارات أسرع جنوبا ، لكننا نحتل مرتبة عالية من حيث التاريخ والتوقفات المثيرة للاهتمام والطبيعة الجميلة على طول المسارات ، يقول أوستلوند : السفر بالقطار هو أيضا أحد أكثر الطرق استدامة لاستكشاف البلاد",
        en: "Jan Helge Østlund has written many books about Norwegian train journeys and railway history. Switzerland and Austria provide stiff competition, he says, but I still maintain that Norway is an excellent European rail destination. They may have faster trains further south, but we rank highly for history, interesting stops and beautiful nature along the tracks. Travelling by train, Østlund adds, is also one of the most sustainable ways to explore the country.",
      },
      { type: "H3", ar: "خط بيرغن", en: "The Bergen Line" },
      {
        type: "P",
        ar: "ربما يكون خط بيرغن هو رحلة القطار النرويجية ذات المناظر الخلابة الأكثر شعبية لسبب وجيه ، حيث يمر القطار عبر المناظر الجبلية الجميلة من أوسلو الى غول وجيلو ، صعودا عبر وادي هالينغدال نحو فينس في الجبال العالية ، وعلى طول نهر هاردانغيوكولين الجليدي الرائع ، قبل النزول نحو المحطة النهائية",
        en: "The Bergen Line is perhaps the most popular scenic Norwegian train journey, and for good reason. The train passes through beautiful mountain landscapes from Oslo to Gol and Geilo, climbing through the Hallingdal valley towards Finse in the high mountains and alongside the magnificent Hardangerjøkulen glacier, before descending towards the final station.",
      },
      {
        type: "P",
        ar: "لا يربط خط بيرغن اثنتين من أهم مدننا ، بيرغن وأوسلو فحسب ، بل يسافر أيضا عبر مقطع عرضي مذهل من المناظر الطبيعية النرويجية على طول الطريق ، الحقول والمضايق والغابات والجبال كلها جزء من الرحلة التي تستغرق سبع ساعات ، يقول أوستلوند : حقيقة أنه يمر بأعلى نقطة في النرويج لخط السكك الحديدية أمر مثير للاهتمام أيضا",
        en: "The Bergen Line not only connects two of the country's most important cities, Bergen and Oslo, it also travels through a stunning cross-section of Norwegian landscape along the way. Fields, fjords, forests and mountains are all part of the seven-hour journey. The fact that it passes the highest point of any railway in Norway is interesting too, says Østlund.",
      },
      {
        type: "P",
        ar: "قامت هيئة الاذاعة النرويجية بتصوير الرحلة بأكملها وبثها مباشرة دون انقطاع في التلفزيون ، منذ ذلك الحين ، أصبحت الرحلة مفضلة بين السياح ، يغتنم الكثيرون الفرصة للانتقال في محطة ميردال لتجربة خط فلام الشهير عالميا ، وهي رحلة عبر بعض أكثر الطبيعة الخلابة في النرويج",
        en: "The Norwegian Broadcasting Corporation filmed the entire journey and broadcast it live and uninterrupted on television. Since then the trip has become a favourite among visitors, and many take the chance to change at Myrdal station to experience the world-famous Flåm Line, a journey through some of Norway's most spectacular nature.",
      },
      { type: "IMG", src: U("2023/04/img_0654.jpg"), cap_ar: "خط بيرغن", cap_en: "The Bergen Line" },
      { type: "H3", ar: "خط فلام", en: "The Flåm Line" },
      {
        type: "P",
        ar: "حقيقة أنها واحدة من أشهر السكك الحديدية في العالم ، على الرغم من مدتها القصيرة التي تبلغ حوالي ساعة واحدة ، هناك الكثير عن خط فلام والمناظر التي يقدمها على طول الطريق ، ففي كل عام يفوق عدد راكبي هذه الرحلة نصف مليون مسافر من خلال الرحلة شديدة الانحدار من محطة ميردال وصولا الى قرية فلام ، الواقعة في الجزء الأعمق من مضيق أورلاندز",
        en: "It is genuinely one of the most famous railways in the world, despite its short duration of about an hour. There is a great deal to say about the Flåm Line and the views it offers along the way. Every year more than half a million passengers ride the steep journey from Myrdal station down to the village of Flåm, at the innermost part of the Aurlandsfjord.",
      },
      {
        type: "P",
        ar: "يتمتع خط فلام باطلالات رائعة في الطقس المعتدل ، يقول أوستلوند : مع الشلالات الدرامية والأنهار والوديان والجبال ، فان هذا الامتداد هو بالنسبة للكثيرين تعريف الطبيعة النرويجية",
        en: "The Flåm Line has wonderful views in mild weather. With its dramatic waterfalls, rivers, valleys and mountains, says Østlund, this stretch is for many people the very definition of Norwegian nature.",
      },
      {
        type: "P",
        ar: "كعاشق للقطارات مدى الحياة ، يقدر أوستلوند الجوانب التقنية للقطارات العتيقة على خط فلام على وجه الخصوص ، قبل كل شيء خط فلام هو تحفة فنية ، بسبب الصعود الحاد من 0 الى 866 مترا فوق مستوى سطح البحر ، هناك حاجة الى قاطرتين ، واحدة في الأمام والأخرى خلف القطار ، وكل عربة مزودة بنظام فرامل خاص",
        en: "As a lifelong train lover, Østlund particularly appreciates the technical side of the vintage trains on the Flåm Line. Above all the line is a masterpiece: because of the sharp climb from 0 to 866 metres above sea level, two locomotives are needed, one at the front and one behind the train, and every carriage has its own special braking system.",
      },
      {
        type: "P",
        ar: "تقدم فلام مجموعة واسعة من الأنشطة ومشاهدة المعالم السياحية الصديقة للبيئة على مدار السنة ، أصبح خط فلام أيضا عامل جذب كبير في فصل الشتاء ، عندما يتضاعف كرافعة تزلج",
        en: "Flåm offers a wide range of eco-friendly activities and sightseeing all year round, and the Flåm Line has become a major draw in winter too, when it doubles as a ski lift.",
      },
      { type: "IMG", src: U("2023/04/img_0655.jpg"), cap_ar: "خط فلام", cap_en: "The Flåm Line" },
      { type: "H3", ar: "خط دوفر", en: "The Dovre Line" },
      {
        type: "P",
        ar: "يعد خط دوفر طريقة لا تنسى للسفر من أوسلو الى تروندهايم ، تمر الرحلة التي تستغرق سبع ساعات عبر جودبراندسدالين وروندان ودوفرفيل عبر بعض الحدائق الوطنية المذهلة في النرويج",
        en: "The Dovre Line is an unforgettable way to travel from Oslo to Trondheim. The seven-hour journey passes through Gudbrandsdalen, Rondane and Dovrefjell, across some of Norway's most stunning national parks.",
      },
      {
        type: "P",
        ar: "يجعل خط دوفر يومك رائعا في السفر ، هناك العديد من الأشياء الرائعة التي يمكنك رؤيتها أثناء سفرك على طول بحيرة ميوسا ونحو هامر وليلهامر ، تسافر أيضا عبر ايدسفول ، مسقط رأس الدستور النرويجي ، على الرغم من أن المشهد لن يكون دراماتيكيا تماما كما هو الحال على خطوط السكك الحديدية الأكثر شهرة لدينا ، الا أنه لا يزال هناك الكثير لرؤيته على طول الطريق ، ومن بين الأنواع الأخرى ثور المسك هو مشهد متكرر في هذه الرحلة ، يقول خبير القطار أوستلوند : يمكنك أيضا التوقف في منتصف الطريق في جبال دوفريفيل ، انضم الى رحلة سفاري ثور المسك ، واستمتع بوجبة الذواقة في Kongsvold Fjeldstue ، أحد أكثر الفنادق والمطاعم تفردا في النرويج ، ويقع بالقرب من محطة Kongsvoll",
        en: "The Dovre Line makes for a wonderful day of travel. There is a great deal to see as you travel along Lake Mjøsa and towards Hamar and Lillehammer, and you also pass through Eidsvoll, the birthplace of the Norwegian constitution. Although the scenery is not quite as dramatic as on our most famous lines, there is still plenty to see along the way — among other species, the musk ox is a frequent sight on this journey. You can also stop halfway in the Dovrefjell mountains, says train expert Østlund, join a musk ox safari and enjoy a gourmet meal at Kongsvold Fjeldstue, one of the most distinctive hotels and restaurants in Norway, near Kongsvoll station.",
      },
      {
        type: "P",
        ar: "اذا كنت تسافر مع أطفال ، فلن ترغب في تفويت حديقة هوندرفوسن العائلية في ليلهامر ، وفي محطة بيورلي ، يمكنك تغيير القطارات وركوب خط راوما الشهير",
        en: "If you are travelling with children you will not want to miss the Hunderfossen family park in Lillehammer, and at Bjorli station you can change trains and ride the famous Rauma Line.",
      },
      { type: "IMG", src: U("2023/04/img_0663.jpg"), cap_ar: "خط دوفر", cap_en: "The Dovre Line" },
      { type: "H3", ar: "خط راوما", en: "The Rauma Line" },
      {
        type: "P",
        ar: "وصف أوستلوند خط راوما بأنه واحد من أجمل وأعنف خطوط السكك الحديدية في النرويج ، سيكون للامتداد الذي يبلغ طوله 114 كيلومترا دائما مكان خاص في قلبه",
        en: "Østlund describes the Rauma Line as one of the most beautiful and wildest railways in Norway. The 114-kilometre stretch will always have a special place in his heart.",
      },
      {
        type: "P",
        ar: "من بيورلي وصولا الى Åndalsnes ، ستختبر بعضا من أكثر المناظر الطبيعية المذهلة في هذا الجانب من سويسرا ، في رأيي قد يكون أجمل امتداد للأرض التي تقدمها هذه البلاد",
        en: "From Bjorli down to Åndalsnes you will experience some of the most stunning landscape on this side of Switzerland — in my opinion perhaps the most beautiful stretch of land this country has to offer.",
      },
      {
        type: "P",
        ar: "تستغرق الرحلة حوالي ساعة و40 دقيقة ، تشمل المعالم البارزة وادي رومسدالين ، والوجه الصخري Trollveggen ، وجسر Kylling الفريد ، اذا سافرت مع خط دوفر ، فستتمكن من الوصول بسهولة الى خط راوما عبر محطة دومباس ، يركز القطار على السياحة ، مع نوافذ وأدلة بانورامية في الصيف",
        en: "The journey takes about one hour and 40 minutes. The highlights include the Romsdalen valley, the Trollveggen rock face and the unique Kylling bridge. If you travel on the Dovre Line you can easily reach the Rauma Line via Dombås station. The train is focused on tourism, with panoramic windows and guides in summer.",
      },
      {
        type: "P",
        ar: "من قرية المضيق البحري Åndalsnes ، التي تسمى أيضا عاصمة تسلق الجبال ، يمكنك المشي لمسافات طويلة في سلسلة جبال Romsdalseggen الشهيرة ، أو الذهاب في جولة التزلج ، أو تجربة الطريق النرويجي ذات المناظر الطبيعية الخلابة Geiranger-Trollstigen",
        en: "From the fjord village of Åndalsnes, also called the mountaineering capital, you can hike the famous Romsdalseggen ridge, go on a ski tour, or experience the Geiranger-Trollstigen national scenic route.",
      },
      { type: "IMG", src: U("2023/04/img_0657.jpg"), cap_ar: "خط راوما", cap_en: "The Rauma Line" },
      { type: "H3", ar: "خط روروس", en: "The Røros Line" },
      {
        type: "P",
        ar: "افتتح خط روروس عام 1877م وهو أقدم خط رئيسي في النرويج ، تصل الرحلة التي تستغرق خمس ساعات بين هامار (ساعة واحدة بالقطار من أوسلو) وتروندهايم عبر البرية الجميلة والغابات الغامضة في أوستيردالن قبل أن تستمر في الوصول الى مدينة التعدين الفريدة المدرجة في قائمة اليونسكو ، روروس وعلى طول الطريق الى ستورن",
        en: "The Røros Line opened in 1877 and is the oldest main line in Norway. The five-hour journey connects Hamar (one hour by train from Oslo) and Trondheim through the beautiful wilderness and mysterious forests of Østerdalen, before continuing to the unique UNESCO-listed mining town of Røros and on towards Støren.",
      },
      {
        type: "P",
        ar: "يعتبر الكثيرون أن خط روروس ممل بعض الشيء ، ولكن هناك في الواقع الكثير من الأشياء التي يمكنك مشاهدتها اذا كنت تأخذ الوقت الكافي للبحث ، في مساحات شاسعة من الغابات ومع قليل من الحظ ، يمكنك اكتشاف كل من الموظ ، والولفيرين ، والوشق ، والذئب ، والدب",
        en: "Many consider the Røros Line a little dull, but there is in fact a great deal to see if you take the time to look. In vast stretches of forest, and with a little luck, you can spot moose, wolverine, lynx, wolf and bear.",
      },
      { type: "IMG", src: U("2023/04/img_0659.jpg"), cap_ar: "خط روروس", cap_en: "The Røros Line" },
      { type: "H3", ar: "خط سورلاند", en: "The Sørland Line" },
      {
        type: "P",
        ar: "على الرغم من أن الرحلة التي تستغرق ثماني ساعات بين أوسلو وستافنجر قد لا تتمتع بالسمعة البرية التي تتمتع بها نظيراتها الشمالية ، الا أن خط سورلاند لا يزال بديلا أكثر متعة ورائعة للقيادة اذا كنت ذاهبا الى الجنوب السعيد",
        en: "Although the eight-hour journey between Oslo and Stavanger may not have the wild reputation of its northern counterparts, the Sørland Line is still a far more enjoyable and wonderful alternative to driving if you are heading for the happy south.",
      },
      {
        type: "P",
        ar: "يمر القطار بالعديد من الوجهات المناسبة للعائلات ، بما في ذلك أكبر حديقة مائية في الدول الاسكندنافية ، وBø Sommarland في Telemark ، وKristiansand ، والمعروفة باسم العاصمة الصيفية للجنوب ، مع العديد من الشواطئ الرائعة ومناطق الجذب العائلية مثل حديقة حيوان كريستيانساند ومدينة الملاهي",
        en: "The train passes many family-friendly destinations, including the largest water park in Scandinavia, Bø Sommarland in Telemark, and Kristiansand, known as the summer capital of the south, with many wonderful beaches and family attractions such as Kristiansand Zoo and Amusement Park.",
      },
      {
        type: "P",
        ar: "يتصور الكثيرون مسار قطار على طول حافة المياه مباشرة ، ولكن أجزاء كبيرة من خط سورلاند تم بناؤها في الداخل لتجنب القصف في زمن الحرب ، في الواقع لن تتمكن من رؤية المحيط حتى تقترب من Egersund ، قبل ذلك كان هناك في الغالب الوديان والغابات ، ومن Nelaug ، هناك فرع يمتد الى Arendal ، مع مناظر جميلة على طول الطريق",
        en: "Many imagine a railway running right along the water's edge, but large parts of the Sørland Line were built inland to avoid wartime bombardment. In fact you will not see the ocean until you approach Egersund; before that it is mostly valleys and forest. From Nelaug a branch runs to Arendal, with beautiful views along the way.",
      },
      {
        type: "P",
        ar: "يوفر خط سورلاند أيضا وصولا سهلا الى المناظر الطبيعية الساحلية الجميلة في جنوب النرويج والبلدات التي تعد موطنا لمنازل خشبية قديمة جذابة مطلية باللون الأبيض ، بما في ذلك Risør وGrimstad وMandal وFlekkefjord وEgersund",
        en: "The Sørland Line also gives easy access to the beautiful coastal landscape of southern Norway and the towns that are home to charming old wooden houses painted white, including Risør, Grimstad, Mandal, Flekkefjord and Egersund.",
      },
      { type: "IMG", src: U("2023/04/img_0660.jpg"), cap_ar: "خط سورلاند", cap_en: "The Sørland Line" },
      { type: "H3", ar: "خط نوردلاند", en: "The Nordland Line" },
      {
        type: "P",
        ar: "يعد المسار الذي يبلغ طوله 729 كيلومترا بين تروندهايم وبودو أطول خط سكة حديد في النرويج ، تمر الرحلة عبر مناظر طبيعية رائعة ومتنوعة ، من المناظر الساحلية الشمالية المميزة الى المدن الداخلية الصغيرة والامتدادات الجبلية العالية ، أو في احدى المحطات الأخرى في Trøndelag ، للذهاب لصيد سمك السلمون أو استكشاف المتنزهات الوطنية الثلاثة الموجودة في Namdalen ، يمكنك أيضا النزول في Mosjøen أو Mo i Rana اذا كنت ترغب في استكشاف ساحل Helgeland الجميل",
        en: "The 729-kilometre route between Trondheim and Bodø is the longest railway line in Norway. The journey passes through magnificent and varied landscapes, from the distinctive northern coastal scenery to small inland towns and high mountain stretches. You can stop at one of the other stations in Trøndelag to fish for salmon or explore the three national parks in Namdalen, and you can also get off at Mosjøen or Mo i Rana if you want to explore the beautiful Helgeland coast.",
      },
      {
        type: "P",
        ar: "يمتد خط نوردلاند على مسافة 729 كيلومترا من التجارب والتاريخ والطبيعة الخلابة ، يعتقد الكثيرون أن الرحلة ستكون مملة لأنها تستغرق 11 ساعة ، في الواقع ، هذه واحدة من جواهر السكك الحديدية النرويجية الحقيقية",
        en: "The Nordland Line runs for 729 kilometres of experiences, history and spectacular nature. Many think the journey will be boring because it takes 11 hours; in fact, this is one of the true jewels of the Norwegian railways.",
      },
      {
        type: "P",
        ar: "خط نوردلاند هو خط السكك الحديدية النرويجي الوحيد الذي يعبر الدائرة القطبية الشمالية ، ويمكنك الاستمتاع به على مدار السنة ، يمكنك الاختيار بين رحلتين مغادرتين يوميا من تروندهايم وبودو ، وصنفت لونلي بلانيت رحلة القطار المسائية على أنها واحدة من أجمل الرحلات في العالم ، احجز رحلتك مبكرا اذا كنت تريد مقصورة نوم",
        en: "The Nordland Line is the only Norwegian railway that crosses the Arctic Circle, and you can enjoy it all year round. You can choose between two daily departures from Trondheim and Bodø, and Lonely Planet ranked the evening train as one of the most beautiful journeys in the world. Book early if you want a sleeping compartment.",
      },
      { type: "IMG", src: U("2023/04/img_0661.jpg"), cap_ar: "خط نوردلاند", cap_en: "The Nordland Line" },
      { type: "H3", ar: "خط أوفوتن", en: "The Ofoten Line" },
      {
        type: "P",
        ar: "يعد خط Ofoten ، الذي يطلق عليه اسم الأعجوبة الثامنة في العالم عندما تم بناؤه لأول مرة ، خط القطار في أقصى شمال النرويج ، تأخذك سكة حديد خام الحديد القديمة هذه من نارفيك بجوار Ofotfjord ، ينزلق القطار عبر المناظر الطبيعية التاريخية الجميلة والبرية مع مناظر رائعة للمضيق وقمم الجبال الخشنة والشلالات المتتالية ، تستغرق الرحلة الى الحدود السويدية حوالي ساعة ، ويمكنك المتابعة جنوبا عبر السويد الى ستوكهولم أو وجهات أخرى في أوروبا",
        en: "The Ofoten Line, called the eighth wonder of the world when it was first built, is the northernmost railway in Norway. This old iron-ore railway takes you from Narvik beside the Ofotfjord, gliding through beautiful, wild and historic landscape with magnificent views of the fjord, rugged peaks and cascading waterfalls. The journey to the Swedish border takes about an hour, and you can continue south through Sweden to Stockholm or other destinations in Europe.",
      },
      {
        type: "P",
        ar: "ليس المشهد فقط هو ما يثير الرهبة ، تخلق آثار القوات البحرية (rallare باللغة النرويجية) التي قامت ببناء السكك الحديدية في أواخر القرن التاسع عشر خلفية آسرة للرحلة ، هناك أيضا بقايا من الحرب العالمية الثانية ، وقع الكثير من القتال أثناء معركة نارفيك بالقرب من خط السكة الحديد ، الذي كان طريق التصدير لأكبر وأهم رواسب خام الحديد في أوروبا",
        en: "It is not only the scenery that inspires awe. The traces of the navvies (rallare in Norwegian) who built the railway in the late nineteenth century create a captivating backdrop to the journey. There are also remains from the Second World War: much of the fighting during the Battle of Narvik took place near the railway, which was the export route for the largest and most important iron-ore deposits in Europe.",
      },
      {
        type: "P",
        ar: "انطلق في محطة Katterat ، المحاطة بمباني جذابة مطلية باللون الأحمر ، ثم قم بالسير الى Rombaksbotn بجوار المضيق البحري ، متبعا الطريق القديم الجميل Rallarvegen ، في الصيف تتوفر الجولات المصحوبة بمرشدين والنقل بالقوارب الى نارفيك ، واذا كنت تحب التزلج ، فان منتجع Narvikfjellet للتزلج مفتوح حتى شهر مايو ، وفي الصيف ، يأخذك الجندول الى قمة الجبل للاستمتاع بمناظر المضيق البحري المذهلة",
        en: "Get off at Katterat station, surrounded by attractive red-painted buildings, then walk down to Rombaksbotn beside the fjord, following the beautiful old navvy road Rallarvegen. In summer guided tours and boat transfers to Narvik are available, and if you love skiing, the Narvikfjellet ski resort is open until May. In summer the gondola takes you to the mountain top for stunning fjord views.",
      },
      { type: "IMG", src: U("2023/04/img_0662.jpg"), cap_ar: "خط أوفوتن", cap_en: "The Ofoten Line" },
    ],
  },
  {
    slug: "tromso-locals",
    title_ar: "تعرف على دليل السكان المحليين في ترومسو",
    title_en: "The locals' guide to Tromsø",
    kicker_ar: "أهم النصائح",
    kicker_en: "Insider tips",
    image: U("2023/04/img_0401.jpg"),
    blocks: [
      {
        type: "P",
        ar: "تعرف ترومسو بباريس الشمال والمدينة القطبية الشمالية ، وهي مدينة طلابية تتمتع بأجواء خاصة ، اكتشف أفضل أماكن الحياة الليلية في شمال الدائرة القطبية الشمالية ، سواء كانت فكرتك عن المتعة هي البقاء في الداخل في الحانات والبارات المريحة ، أو المغامرة بالخارج لرؤية الأضواء الشمالية وشمس منتصف الليل",
        en: "Tromsø is known as the Paris of the North and the Arctic city. It is a student town with a special atmosphere. Discover the best nightlife north of the Arctic Circle, whether your idea of fun is staying indoors in cosy pubs and bars, or venturing outside to see the northern lights and the midnight sun.",
      },
      {
        type: "P",
        ar: "اليك كيفية قضاء عطلة نهاية أسبوع طويلة بأسلوب ترومسو الحقيقي : الجمعة الثقافية والسبت مع السكان المحليين والمشي في المناطق الحضرية يوم الأحد",
        en: "Here is how to spend a long weekend in true Tromsø style: a cultural Friday, a Saturday with the locals, and an urban walk on Sunday.",
      },
      { type: "H3", ar: "الجمعة الثقافية", en: "A cultural Friday", noNumber: true },
      {
        type: "P",
        ar: "تتمتع ترومسو بتقويم ثقافي مزدحم على مدار السنة ، لكن فصل الشتاء هو حقا شيء اضافي ، فكلما كان الجو أكثر برودة في الخارج زادت شدته في الداخل ، اليك عدد من النصائح المهمة للتجارب الثقافية في ترومسو",
        en: "Tromsø has a busy cultural calendar all year round, but winter is really something extra: the colder it is outside, the more intense it gets inside. Here are a few important tips for cultural experiences in Tromsø.",
      },
      { type: "H3", ar: "ابحث عن مهرجان ما", en: "Look for a festival", noNumber: true },
      {
        type: "P",
        ar: "فيما يتعلق بعدد الأشخاص الذين يعيشون هنا ، هناك الكثير مما قد يحدث ، بغض النظر عن الموسم ، فمع وجود العديد من المؤسسات الثقافية الكبيرة ذات الجودة العالية ، يسهل على السائحين العثور على الأحداث والأنشطة ، ومع ذلك فان ترومسو هي أولا وقبل كل شيء مدينة احتفالات ، اذا كنت تخطط للبقاء بضعة أيام ، فهناك فرصة جيدة لقضاء يوم الجمعة الثقافي الخاص بك في مهرجان ، يأتون من جميع الأنواع من الأفلام والموسيقى وفنون الأداء الى الطعام والأدب ، ومعظم تلك الأمور تحدث في وسط المدينة",
        en: "For the number of people who live here, a great deal happens whatever the season. With several large, high-quality cultural institutions, it is easy for visitors to find events and activities. Above all, though, Tromsø is a festival city: if you plan to stay a few days, there is a good chance of spending your cultural Friday at a festival. They come in all kinds — film, music and performing arts through to food and literature — and most take place in the city centre.",
      },
      { type: "H3", ar: "السكان الأصليون", en: "The indigenous people", noNumber: true },
      {
        type: "P",
        ar: "ان أكثر المهرجانات الفريدة في النرويج تحدث في يوم جمعة واحد فقط من كل عام : مهرجان Riddu Riđđu ، والذي يقام في يوليو في ماندالين ، على بعد حوالي ساعة ونصف بالسيارة من ترومسو ، يدور هذا المهرجان الأصلي حول ثقافة سامي المحلية",
        en: "The most unique festival in Norway happens on just one Friday each year: the Riddu Riđđu festival, held in July in Manndalen, about an hour and a half by car from Tromsø. This indigenous festival revolves around local Sámi culture.",
      },
      { type: "H3", ar: "اقفز في البحر", en: "Jump into the sea", noNumber: true },
      {
        type: "P",
        ar: "لا تفوت أهم مناطق الجذب في المدينة : Pust ، على شكل رف تجفيف تقليدي للأسماك ، تتمتع هذه الساونا العائمة بموقع مركزي بجوار الميناء",
        en: "Do not miss one of the city's top attractions: Pust, shaped like a traditional fish-drying rack. This floating sauna has a central location right by the harbour.",
      },
      { type: "H3", ar: "الطعام المفضل", en: "The food to choose", noNumber: true },
      {
        type: "P",
        ar: "تزخر مدينة ترومسو بأماكن مثيرة لتناول الطعام ، لذا فهي عبارة عن قطعة من الكعكة للعثور على وجبة رائعة ، جرب Bardus bistro ، أصغر مطعم في المدينة ، لتناول وجبات شهية مصنوعة من مكونات موسمية ومنتجة محليا ، يقع هذا المطعم عالي الجودة في منزل خشبي قديم ، ويدعو الضيوف للاستمتاع بالطعام في جو يصفونه بأنه أكثر متعة من الرسمية ، ستجده مقابل مبنى مكتبة ترومسو الكبير وبجوار بار Bardus ، الذي يقدم أفضل المشروبات في المدينة",
        en: "Tromsø is full of exciting places to eat, so finding a great meal is a piece of cake. Try Bardus bistro, the smallest restaurant in the city, for delicious dishes made with seasonal, locally produced ingredients. This high-quality restaurant sits in an old wooden house and invites guests to enjoy food in an atmosphere they describe as more fun than formal. You will find it opposite the large Tromsø library building and next to Bardus Bar, which serves the best drinks in town.",
      },
      { type: "H3", ar: "ساعة الكوكتيل", en: "Cocktail hour", noNumber: true },
      {
        type: "P",
        ar: "مع احترام بار Bardus Bar ، فاز مطعم وبار Hildr في Skippergata بالجائزة الأولى لأفضل مشروب في العالم بأسره : ginger daiquiri ، ومثل Bardus bistro ، يعد Hildr مطعما رائعا وحميميا مع قائمة طعام ملهمة ومتطورة باستمرار",
        en: "With respect to Bardus Bar, the restaurant and bar Hildr in Skippergata won first prize for the best drink in the entire world: the ginger daiquiri. Like Bardus bistro, Hildr is a wonderful, intimate restaurant with an inspiring, constantly evolving menu.",
      },
      { type: "H3", ar: "فرق موسيقية حية", en: "Live bands", noNumber: true },
      {
        type: "P",
        ar: "أنها ليلتك في أروع ملهى ليلي في المدينة : Storgata Camping ، هذا هو المكان الأفضل للاستمتاع بالفرق الموسيقية الحية والدي جيه ، الذين يجعلون من المستحيل الوقوف بدون حراك ، ولماذا لا تهدأ مع جولة من الميني غولف ؟",
        en: "It is your night at the coolest club in town: Storgata Camping. This is the best place to enjoy live bands and DJs who make it impossible to stand still — and why not wind down with a round of mini golf?",
      },
      { type: "H3", ar: "أثناء وجودك هنا", en: "While you are here", noNumber: true },
      {
        type: "P",
        ar: "ترومسو رائعة اذا كنت مهتما بالسكان الأصليين في النرويج سامي ، هناك أيضا الكثير من المتاحف الفنية الرائعة في المدينة ، وزيارة كاتدرائية القطب الشمالي مدرجة في قائمة مهام العديد من الزوار ، فقط ابحث عن المتاحف والمعارض لتزيد من شغفك",
        en: "Tromsø is wonderful if you are interested in Norway's indigenous Sámi people. There are also many excellent art museums in the city, and a visit to the Arctic Cathedral is on many visitors' to-do lists. Just look for the museums and galleries to feed your curiosity.",
      },
      { type: "H3", ar: "يوم السبت مع السكان المحليين", en: "Saturday with the locals", noNumber: true },
      {
        type: "P",
        ar: "الحياة في الشمال مختلفة ، لذا علينا أن نتكيف مع أشهر الشتاء المظلمة والصيف الخفيف مع شمس منتصف الليل ، وهذا يعطي المدينة والناس نوعا من عامل التميز ، تنعم ترومسو بمزيج سحري من الجبال والبحر وحياة المدينة ، انه فعلا كبير بما يكفي لعدم نفاد الأشياء التي يجب القيام بها ، وصغير بما يكفي للتعرف بسرعة على شعور بأنك تنتمي ، واليك عدد من النصائح لقضاء يوم سبت مع السكان المحليين في ترومسو",
        en: "Life in the north is different, so we have to adapt to the dark winter months and the bright summer with its midnight sun. That gives the city and its people a certain distinctive quality. Tromsø is blessed with a magical mixture of mountains, sea and city life — big enough that you never run out of things to do, and small enough to quickly feel that you belong. Here are some tips for a Saturday with the locals in Tromsø.",
      },
      { type: "H3", ar: "مدينة المهرجانات", en: "Festival city", noNumber: true },
      {
        type: "P",
        ar: "أول شيء تحتاج إلى التحقق منه هو ما اذا كان هناك مهرجان عندما تخطط للزيارة ، المهرجانات هي التي تجعل قلب ترومسو الثقافي ينبض ، انها توفر اختصارا مباشرا لجوهر حياة ترومسو",
        en: "The first thing to check is whether there is a festival when you plan to visit. Festivals are what make Tromsø's cultural heart beat, and they offer a direct shortcut to the essence of life here.",
      },
      { type: "H3", ar: "اقرأ وتعلم", en: "Read and learn", noNumber: true },
      {
        type: "P",
        ar: "احصل على مزاج القطب الشمالي الرائع من خلال قراءة كتاب Cora Sandel “Alberte and Jacob” عندما تخطط لرحلتك ، فبمجرد وصولك الى هنا ، أوصى بشدة بزيارة متحف Perspektivet ، المنزل الذي عاشت فيه Cora Sandel ، خذ وقتك للتجول في المجموعات ، وتذكر ان تتحقق من الصور القديمة لترومسو في الطابق الثالث",
        en: "Get into the wonderful Arctic mood by reading Cora Sandel's \"Alberte and Jacob\" while planning your trip. Once you arrive, I strongly recommend visiting the Perspektivet Museum, the house where Cora Sandel lived. Take your time wandering through the collections, and remember to check the old photographs of Tromsø on the third floor.",
      },
      { type: "H3", ar: "تعرف على ثقافة سامي", en: "Learn about Sámi culture", noNumber: true },
      {
        type: "P",
        ar: "قم بزيارة جامعة القطب الشمالي في النرويج ، فمن الحكمة لأولئك المهتمين بسامي أن يخصصوا عدة ساعات لمشاهدة المعارض الاثنوغرافية التي تغطي كل شيء من عصور ما قبل التاريخ الى ثقافة سامي المعاصرة",
        en: "Visit the Arctic University of Norway. Those interested in the Sámi would be wise to set aside several hours for the ethnographic exhibitions, which cover everything from prehistory to contemporary Sámi culture.",
      },
      { type: "H3", ar: "تفنن في الصيد", en: "Discover the fishing life", noNumber: true },
      {
        type: "P",
        ar: "يملأك المتحف القطبي بحياة الصيد المحلية وتاريخها ، وهو جزء مهم من هوية ترومسو ، جرب شيئا لن تجده في أي مكان آخر في العالم",
        en: "The Polar Museum immerses you in local fishing life and its history, an important part of Tromsø's identity. Try something you will not find anywhere else in the world.",
      },
      { type: "H3", ar: "ان كنت من هواة السينما", en: "If you love cinema", noNumber: true },
      {
        type: "P",
        ar: "انضم الى عرض فيلم في السينما المثيرة للاعجاب Verdensteatret ، وهي أقدم سينما لا تزال تعمل في شمال أوروبا",
        en: "Join a film screening at the impressive Verdensteatret, the oldest cinema still in operation in northern Europe.",
      },
      { type: "H3", ar: "انطلق في جولة تسوق", en: "Go shopping", noNumber: true },
      {
        type: "P",
        ar: "ابدأ رحلة التسوق الخاصة بك من خلال الانطلاق في Wabi Sabi لشراء المجوهرات المصممة محليا ، واطلع على المعارض الفنية في Galleri Nord وKrane ، وابحث عن القصص المصورة القديمة والجديدة والكتب وألعاب الطاولة وليغو في متجر Lego-Loftet المذهل",
        en: "Start your shopping trip at Wabi Sabi for locally designed jewellery, look at the art exhibitions in Galleri Nord and Krane, and hunt for old and new comics, books, board games and Lego in the amazing Lego-Loftet shop.",
      },
      { type: "H3", ar: "احصل على منظور جديد", en: "Get a new perspective", noNumber: true },
      {
        type: "P",
        ar: "اعبر الجسر واستقل تلفريك Fjellheisen الى أعلى الجبل لتستمتع بأجمل الأجواء",
        en: "Cross the bridge and take the Fjellheisen cable car to the top of the mountain to enjoy the finest atmosphere of all.",
      },
      { type: "H3", ar: "تمتع بافطارك", en: "Enjoy your breakfast", noNumber: true },
      {
        type: "P",
        ar: "قم بتأمين مقعد بجوار النافذة في Helmersen واحصل على افطار كامل أثناء مشاهدة الناس",
        en: "Secure a window seat at Helmersen and have a full breakfast while watching the world go by.",
      },
      { type: "H3", ar: "تلذذ بشرب القهوة والشاي", en: "Coffee and tea", noNumber: true },
      {
        type: "P",
        ar: "تناول الغداء أو تناول القهوة الفاخرة في Risø أو توقف عند حديقة Hildr لتناول كوب من الشاي اذا كان الطقس جيدا",
        en: "Have lunch or a fine coffee at Risø, or stop at the Hildr garden for a cup of tea if the weather is good.",
      },
      { type: "H3", ar: "الشعور بالجوع في Amtmandens", en: "Feeling hungry at Amtmandens", noNumber: true },
      {
        type: "P",
        ar: "يمكنك الحصول على الجبن واللحوم الباردة من ايطاليا وفرنسا واسبانيا جنبا الى جنب مع المكونات المحلية التي يتم تقديمها على لوح وكأس من أي مشروب تفضله",
        en: "You can get cheese and cold cuts from Italy, France and Spain alongside local ingredients served on a board, with a glass of whatever you prefer.",
      },
      { type: "H3", ar: "ليلة اللعبة", en: "Game night", noNumber: true },
      {
        type: "P",
        ar: "اذا كنت في حالة مزاجية لألعاب الطاولة ، فان Cafe Sånn هو خيار جيد ، خاصة اذا كنت تفضل اللعب أثناء الاستمتاع بساندويتش ستيك ضخم وكعك محلي الصنع ومشروب طازج ، ولدمج مشروبك مع شيء أكثر نشاطا ، جرب لعبة minigolf في Storgata Camping",
        en: "If you are in the mood for board games, Cafe Sånn is a good choice, especially if you like to play while enjoying a huge steak sandwich, homemade cakes and a fresh drink. To combine your drink with something more active, try the minigolf at Storgata Camping.",
      },
      { type: "H3", ar: "أثناء وجودك هناك", en: "While you are there", noNumber: true },
      {
        type: "P",
        ar: "مؤسسة Vertshuset Skarven هي مؤسسة محلية تقدم الأطباق التقليدية ، ويتم تقديم المزيد من المأكولات في القطب الشمالي ، بما في ذلك السمك المشوي ، في مطعم Arctandria في Fiskekompaniet ، اذا سيكون لديك فرصة لتجربة اللحوم النضرة من ملك السلطعون ، ايضا عليك اكتشاف المزيد من تجارب الطهي في ترومسو",
        en: "Vertshuset Skarven is a local institution serving traditional dishes, and more Arctic cuisine, including grilled fish, is served at the Arctandria restaurant and at Fiskekompaniet, where you will have the chance to try succulent king crab. You should also discover more of Tromsø's culinary experiences.",
      },
      { type: "H3", ar: "تمشية يوم الأحد", en: "A Sunday walk", noNumber: true },
      {
        type: "P",
        ar: "ما أحبه في ترومسو هو أن الطبيعة عمليا على عتبة داركم ، وفي كل مكان تذهب اليه تقريبا ، هناك مناظر رائعة في جميع الاتجاهات وامكانيات غير محدودة للتجارب القائمة على الطبيعة ، فقط اختر رحلة نهارية طويلة وصعبة أو رحلة قصيرة بعد الظهر سيرا على الأقدام أو بالدراجة أو على الزلاجات",
        en: "What I love about Tromsø is that nature is practically on your doorstep, and almost everywhere you go there are magnificent views in every direction and unlimited possibilities for nature-based experiences. Just choose a long, hard day trip or a short afternoon outing on foot, by bike or on skis.",
      },
      {
        type: "P",
        ar: "السكان المحليون هم من كبار المعجبين بالأنشطة الخارجية بغض النظر عن الموسم ، ففي فصل الشتاء ، تضيء الأضواء الشمالية السماء بينما تضمن شمس منتصف الليل تجربة فريدة من نوعها في الصيف ، واليك بعض النصائح للمشي في المناطق الحضرية يوم الأحد",
        en: "The locals are great fans of outdoor activities whatever the season. In winter the northern lights light up the sky, while the midnight sun guarantees a one-of-a-kind experience in summer. Here are some tips for an urban Sunday walk.",
      },
      { type: "H3", ar: "رحلة لا ينبغي تفويتها", en: "A trip not to be missed", noNumber: true },
      {
        type: "P",
        ar: "يعتبر التلفريك Fjellheisen الرحلة الأكثر شعبية في المدينة ، وهو أيضا أحد الرحلات المفضلة لدى الجميع ، فمناظر المدينة والجبال لا تصدق ، بغض النظر عن مقدار الوقت الذي تملكه ، أو الى أي مدى تخطط للذهاب ، يقدم Fjellheisen العديد من الخيارات ، تعتبر خطوات Sherpa مثالية للمشي السريع بعد الظهر ، بينما تستغرق Sørstien وقتا أطول قليلا ، اذا كنت ترغب في ذلك ، يمكنك دائما الصعود والنزول باستخدام التلفريك والبدء في التنزه في الأعلى ، ولديكم خيار آخر هو ركوب الحافلة الى Solligården والمشي لمسافات طويلة عبر سلسلة الجبال الى حوالي 15 كيلومترا ، سوف تمشي عبر Sollidalsaksla وBønntuva وFløya قبل أن تصل الى Fjellheisen",
        en: "The Fjellheisen cable car is the most popular trip in the city and a favourite with everyone: the views of the city and mountains are incredible. Whatever amount of time you have, or however far you plan to go, Fjellheisen offers many options. The Sherpa steps are perfect for a quick afternoon walk, while Sørstien takes a little longer. If you prefer, you can always go up and down by cable car and start your walk at the top. Another option is to take the bus to Solligården and hike across the mountain range for about 15 kilometres — you will walk over Sollidalsaksla, Bønntuva and Fløya before reaching Fjellheisen.",
      },
      { type: "H3", ar: "مسارات المشي لمسافات طويلة", en: "Hiking trails", noNumber: true },
      {
        type: "P",
        ar: "توجد مسارات مضاءة للمشي لمسافات طويلة في عدة أماكن حول ترومسو ، لذا يمكنك المشي لمسافات طويلة الى أماكن مثل ترومسويا أو ترومسدالن أو كفالويا بعد حلول الظلام ، فترومسويا هي الجزيرة التي يقع فيها وسط مدينة ترومسو ، فاذا كنت تتبع مسار Tromsøya للمشي لمسافات طويلة ، فيمكنك الدخول الى مقصورة Skihytta في الطريق ، من هناك استمر الى Varden ، وهي أعلى نقطة في الجزيرة ، وهناك العديد من المحطات الطبيعية على طول الطريق ، مثل الرصيف ومنطقة الاستحمام Telegrafbukta ورصيف المراكب الصغيرة",
        en: "There are lit hiking trails in several places around Tromsø, so you can walk to places such as Tromsøya, Tromsdalen or Kvaløya after dark. Tromsøya is the island on which the city centre lies; if you follow the Tromsøya hiking trail you can drop into the Skihytta cabin on the way, then continue to Varden, the highest point on the island. There are many natural stops along the way, such as the pier and the bathing area at Telegrafbukta and the small boat harbour.",
      },
      { type: "H3", ar: "جولة المضيق البحري", en: "A fjord tour", noNumber: true },
      {
        type: "P",
        ar: "نصيحة رائعة اذا كنت ترغب في الخروج من المدينة فما عليك الا ركوب الحافلة الى Ersfjordbotn ، انها قرية صغيرة جميلة في نهاية مضيق صغير ، فهناك نوعان من فرص المشي لمسافات طويلة في متناول اليد : جبال Nattmålsfjellet وBuren ، يبدأ كلا المسارين من ملعب كرة القدم ، واحد على كل جانب من الطريق ، وتعتبر Nattmålsfjellet رحلة أقصر مع اطلالات رائعة على Ersfjord وKaldfjord ، وBuren مخصص لأولئك الذين يرغبون في مغامرة أطول",
        en: "A great tip if you want to get out of the city: simply take the bus to Ersfjordbotn, a beautiful little village at the end of a small fjord. Two hiking options are at hand — the mountains Nattmålsfjellet and Buren. Both trails start from the football pitch, one on each side of the road. Nattmålsfjellet is the shorter trip with wonderful views over Ersfjord and Kaldfjord, while Buren is for those who want a longer adventure.",
      },
      { type: "H3", ar: "على عجلتين", en: "On two wheels", noNumber: true },
      {
        type: "P",
        ar: "ركوب الدراجة حول ترومسو هو خيار رائع آخر ، قم باستئجار دراجة كهربائية أو عادية كما تفضل أنت ، في الصيف يمكنك الذهاب للسباحة في Telegrafbukta",
        en: "Cycling around Tromsø is another great option. Hire an electric or an ordinary bike, whichever you prefer, and in summer you can go for a swim at Telegrafbukta.",
      },
      { type: "H3", ar: "الأنشطة الشتوية", en: "Winter activities", noNumber: true },
      {
        type: "P",
        ar: "يستمر فصل الشتاء في ترومسو لمدة تصل الى ثمانية أشهر ، وهذا يعني أن الأنشطة الشتوية الممتعة هي جزء من الحياة اليومية هناك ، لذا يعتبر صنع رجال الثلج والتزحلق على الجليد أمرا طبيعيا مثل التنزه في قمم الجبال على الزلاجات",
        en: "Winter in Tromsø lasts up to eight months, which means that enjoyable winter activities are part of everyday life. Building snowmen and skating are as natural here as touring the mountain tops on skis.",
      },
      {
        type: "P",
        ar: "وبالتالي ينصح بشدة برحلة تزلج على طول المسارات المضاءة ، الممر في Tromsøya هو الخيار الأكثر مركزية ، والطريق الموجود في Kvaløya يتمتع بأفضل منظر ، والطريق الموجود في Tromsdalen به أقل عدد من الأشخاص ، لذلك ما عليك سوى اختيار الخيار الذي يناسب حالتك المزاجية وقتها ، ويمكن لعشاق التزلج على الجليد تجربة حلبة التزلج على الجليد الجميلة في منطقة شارلوتينلوند الترفيهية ، واذا كان الطقس سيخدمك سيكون بامكانك أيضا الذهاب للتزلج في الداخل في Tromsø Ishall",
        en: "A ski trip along the lit trails is therefore strongly recommended. The track on Tromsøya is the most central option, the one on Kvaløya has the best view, and the one in Tromsdalen has the fewest people, so just choose whichever suits your mood. Skating enthusiasts can try the lovely ice rink in the Charlottenlund recreation area, and if the weather is against you, you can also skate indoors at Tromsø Ishall.",
      },
      { type: "H3", ar: "المشي لمسافات طويلة", en: "Hiking and a break", noNumber: true },
      {
        type: "P",
        ar: "فقط توقف عند مقهى Fjellstua ، فاذا قمت بالتنزه الى Fjellheisen بعد صعود الجبل ، فلا شيء يضاهي طبق الفطائر الطازجة عندهم ، واذا قمت بزيارة Ersfjordbotn فسيمكنك الاستمتاع باطلالة رائعة على المضيق البحري من مقهى Bryggejentene ، وأنت في الطريق الى أو من Ersfjordbotn ، يجدر أيضا الدخول الى المتجر وتناول وجبة Deli Eide Handel ، لديهم تركيز قوي على المنتجات المحلية ومقهى يقدم الأطباق التقليدية والبيتزا اللذيذة",
        en: "Just stop at the Fjellstua café: if you walk up to Fjellheisen after climbing the mountain, nothing beats their plate of fresh waffles. And if you visit Ersfjordbotn you can enjoy a wonderful fjord view from the Bryggejentene café. On the way to or from Ersfjordbotn it is also worth stopping in at the shop and having a meal at Deli Eide Handel, which has a strong focus on local products and a café serving traditional dishes and delicious pizza.",
      },
      { type: "H3", ar: "أثناء تواجدك هناك", en: "While you are out there", noNumber: true },
      {
        type: "P",
        ar: "انطلق في رحلة الى Lyngen ، وهو مكان شهير لتسلق الجبال وركوب الدراجات في الجبال ، يمكنك أيضا ممارسة رياضة المشي لمسافات طويلة في جزيرة Kvaløya ، حقا تستحق الشواطئ البيضاء في جزيرة Sommarøy الزيارة ، خاصة لقضاء أمسية صيفية طويلة تحت شمس منتصف الليل ، وتشمل الأنشطة الشتوية الباردة صيد الأضواء الشمالية وتزلج الكلاب ومشاهدة الحيتان",
        en: "Take a trip to Lyngen, a famous place for mountaineering and mountain biking. You can also hike on the island of Kvaløya, and the white beaches of Sommarøy are truly worth a visit, especially for a long summer evening under the midnight sun. Cold-season activities include chasing the northern lights, dog sledding and whale watching.",
      },
    ],
  },
  {
    slug: "spring",
    title_ar: "عشرة أسباب رائعة تدعوك للذهاب الى النرويج في الربيع",
    title_en: "Ten great reasons to travel to Norway in spring",
    kicker_ar: "الربيع في النرويج",
    kicker_en: "Springtime in Norway",
    image: U("2023/04/img_0609.jpg"),
    blocks: [
      {
        type: "P",
        ar: "قم بزيارة المدن المدمجة المليئة بالحياة ، أو شاهد الآلاف من أشجار الفاكهة في ازدهار كامل ، أو شاهد الفصول تتغير ببطء من مقصورة مريحة على قمة شجرة ، في كل ربيع تستيقظ النرويج من نومها الشتوي وتنفجر بالحياة ، فيما يلي بعض من أفضل الطرق لتجربة ذلك",
        en: "Visit compact cities full of life, see thousands of fruit trees in full bloom, or watch the seasons change slowly from a cosy treetop cabin. Every spring Norway wakes from its winter sleep and bursts into life. Here are some of the best ways to experience it.",
      },
      { type: "H3", ar: "الاحتفاء ببدء موسم جديد", en: "Celebrating the start of a new season" },
      {
        type: "P",
        ar: "هذا هو الوقت المثالي لقضاء عطلة في المدينة ، فبمجرد ظهور العلامات الأولى للربيع ، وعندما ترتفع درجة الحرارة فوق الصفر ، وتبدأ الشمس في حمل بعض الدفء ، يتدفق النرويجيون من منازلهم لتحقيق أقصى استفادة من الموسم الجديد ، تبدأ الأرصفة في الاستمتاع بالحياة ، حيث يذهب السكان المحليون الى أبعد الحدود للاستمتاع بأول أوتيبيلس من السنة (وهي البيرة التي يتم الاستمتاع بها في الخارج في الشمس) ، فاذا خرجت الشمس ، فسيكونون كذلك ، فهم يفضلون ان يجلسوا على جلد الغنم الناعم والدافئ",
        en: "This is the perfect time for a city break. As soon as the first signs of spring appear, when the temperature rises above zero and the sun starts to carry some warmth, Norwegians pour out of their homes to make the most of the new season. The pavements come alive as locals go to great lengths to enjoy the first utepils of the year (a beer enjoyed outdoors in the sun). If the sun comes out, so do they — preferably sitting on a soft, warm sheepskin.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : هل تعلم أن المدن النرويجية مدمجة ومليئة بالخبرات التي يمكنك رؤيتها والقيام بالكثير في 10,000 خطوة فقط ؟ على الرغم من أنه يجب عليك أيضا احضار الكعب العالي ، الا أنه من المهم للغاية حزم أفضل أحذية المشي الخاصة بك ، جرب المشي الطويل ، من خلال المتاحف الفنية ذات المستوى العالمي والأحياء الساحرة وأسواق الطعام الملونة في الشوارع في العديد من المدن ، يمكنك ايضا القيام بنزهة من الجبل الى وسط المدينة",
        en: "Quick tip: did you know that Norwegian cities are so compact and full of experiences that you can see and do a great deal in just 10,000 steps? Although you may also want to bring your heels, it is very important to pack your best walking shoes. Try a long walk through world-class art museums, charming neighbourhoods and colourful street food markets in many cities — you can even take a hike from the mountain down to the city centre.",
      },
      { type: "H3", ar: "المضايق البحرية تكون في ازدهار كامل", en: "The fjords in full bloom" },
      {
        type: "P",
        ar: "اذا كنت تريد تجربة حقيقية مرة واحدة في العمر ، فيجب عليك زيارة النرويج عندما تستيقظ البلاد من السبات ، في منتصف شهر ابريل في الجزء الجنوبي الغربي من النرويج ، ففي ذلك الوقت تتفتح عشرات الآلاف من أشجار الفاكهة بالقرب من المضايق البحرية",
        en: "If you want a genuine once-in-a-lifetime experience, you should visit Norway when the country wakes from hibernation, in mid-April in the south-western part of the country. That is when tens of thousands of fruit trees blossom near the fjords.",
      },
      {
        type: "P",
        ar: "تؤطر قمم الجبال المثيرة للاعجاب والمغطاة بالثلوج وسط المناظر الخلابة ، وهي نفس الجبال التي توفر الحماية للمناطق الصغيرة التي تحتوي على تربة خصبة ، مع الكثير من المساعدة من انعكاس المضايق البحرية للشمس ، تخلق المناظر الطبيعية مناخات صغيرة وفريدة تجعل من هذه القرى المريحة مثالية لزراعة الفاكهة ، وخاصة التفاح والكرز",
        en: "Impressive snow-capped peaks frame the spectacular scenery, and those same mountains shelter small areas of fertile soil. With much help from the fjords reflecting the sun, the landscape creates unique microclimates that make these cosy villages perfect for growing fruit, especially apples and cherries.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : المكان الأكثر شهرة لتجربة هذه الظاهرة هو منطقة Hardanger ، حيث يمكنك زيارة مجموعة من قرى الفاكهة المثالية مثل Lofthus وKinsarvik وUlvik ، تعد منطقة Sognefjord خيارا ممتازا آخر ، ولا تفكر حتى في المغادرة قبل أن تتذوق نتيجة ازدهار العام الماضي Eplemost اللذيذ (عصير التفاح النقي) وعصير التفاح من المنتجين المحليين",
        en: "Quick tip: the most famous place to experience this phenomenon is the Hardanger region, where you can visit a collection of perfect fruit villages such as Lofthus, Kinsarvik and Ulvik. The Sognefjord area is another excellent choice. And do not even think of leaving before tasting the result of last year's blossom — delicious eplemost (pure apple juice) and cider from local producers.",
      },
      { type: "H3", ar: "مشاهدة نبض الشلالات", en: "Watching the waterfalls pulse" },
      {
        type: "P",
        ar: "شاهد كيف تنبض الشلالات النرويجية الدرامية بالحياة في الربيع ، مايو ويونيو هو أفضل وقت مطلق لرؤيتها تنبض بالحياة ، عندما يذوب الجليد والثلج بعيدا ، وعن شلالات المياه المتدفقة التي تغرق على سفوح الجبال ، تمتلك النرويج قائمة طويلة من الشلالات التي تستحق الزيارة",
        en: "See how Norway's dramatic waterfalls pulse with life in spring. May and June are the absolute best time to see them come alive, when the ice and snow melt away and torrents of water plunge down the mountainsides. Norway has a long list of waterfalls worth visiting.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : Vøringsfossen ، بالقرب من Eidfjord في Hardanger ، هي واحدة من أروع الشلالات في النرويج ، توفر منصات المشاهدة الجديدة والمثيرة للاعجاب (التي يجب زيارتها لهواة الهندسة المعمارية) ، مناظر خلابة للمياه الهادرة والأخاديد العميقة",
        en: "Quick tip: Vøringsfossen, near Eidfjord in Hardanger, is one of Norway's most magnificent waterfalls. The impressive new viewing platforms — a must for architecture lovers — offer spectacular views of the roaring water and the deep gorge.",
      },
      { type: "IMG", src: U("2023/04/img_0609.jpg"), cap_ar: "الربيع في النرويج", cap_en: "Spring in Norway" },
      { type: "H3", ar: "الطيور تكون مفعمة بالحيوية", en: "The birds are full of life" },
      {
        type: "P",
        ar: "الربيع يحيي الطيور حقا ، يزخر ساحل النرويج الطويل بالحياة في هذا الوقت من العام ، عندما تعود الطيور المهاجرة التي غادرت في الخريف الى المنزل للتكاثر والاستمتاع بالمواسم الأكثر دفئا ، وكل ما عليك هو احضار مناظيرك وكاميراتك ، وربما حتى مسجل الصوت الخاص بك ، لأن هذه تجربة للأذنين وكذلك العينين ، فقط تأكد من أنك تتصرف باحترام تجاه جميع الأعشاش التي فقست حديثا",
        en: "Spring truly brings the birds to life. Norway's long coast teems with life at this time of year, when the migratory birds that left in autumn return home to breed and enjoy the warmer seasons. All you need is your binoculars and cameras, and perhaps even your sound recorder, because this is an experience for the ears as well as the eyes. Just make sure you behave respectfully towards all the newly hatched nests.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : في الشمال أصبحت فارانجر واحدة من أهم الوجهات في العالم لمشاهدة طيور القطب الشمالي ، فقد صمم المهندسون المعماريون المحليون في Biotope حظيرا حائزا على جوائز لآلاف مراقبي الطيور الذين يسافرون الى المنطقة لاكتشاف أنواع مثل النسور ذات الذيل الأبيض ، وصقور الجير وبط ستيلر وبط بحر القطب الشمالي ، حيث يتدفق عشاق الطيور أيضا الى جزر روندي ولوفوند وروفست من منتصف أبريل تقريبا ، عندما يعود الآلاف من البفن الأطلسي الى مناطق تكاثرهم",
        en: "Quick tip: in the north, Varanger has become one of the world's most important destinations for Arctic birdwatching. The local architects at Biotope have designed award-winning hides for the thousands of birdwatchers who travel to the region to spot species such as white-tailed eagles, gyrfalcons, Steller's eiders and Arctic sea ducks. Bird lovers also flock to the small islands of Runde, Lovund and Røst from around mid-April, when thousands of Atlantic puffins return to their breeding grounds.",
      },
      { type: "IMG", src: U("2023/04/img_0610.jpg"), cap_ar: "طيور الساحل النرويجي", cap_en: "Birds of the Norwegian coast" },
      { type: "H3", ar: "انتشار أسواق المزارعين ومهرجانات الطعام", en: "Farmers' markets and food festivals everywhere" },
      {
        type: "P",
        ar: "تقام أسواق المزارعين في جميع أنحاء النرويج ، تبدأ أقدمها في وقت مبكر من شهر مارس ، تصفح وتذوق مجموعة واسعة من الأشياء الجيدة الطازجة واللذيذة ، وكلها من انتاج المزارعين المحليين ، يعد كل من مهرجانات الطعام وأسواق المزارعين أمرا لا بد منه ، وهما جزء أساسي من ثورة الطهي العصرية في النرويج",
        en: "Farmers' markets are held all over Norway, the earliest starting as soon as March. Browse and taste a wide range of fresh, delicious produce, all from local farmers. Both food festivals and farmers' markets are a must, and they are an essential part of Norway's modern culinary revolution.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : يمكنك العثور على أسواق المزارعين في العديد من الأماكن في البلاد ، اثنان من أفضل مهرجانات الطعام التي تقام في الربيع قبل بدء موسم المهرجانات حقا في الصيف هما مهرجان Spis & Drikk في أوسلو ومهرجان أوسلو النباتي",
        en: "Quick tip: you can find farmers' markets in many places around the country. Two of the best food festivals held in spring, before the festival season really begins in summer, are the Spis & Drikk festival in Oslo and the Oslo Vegan Festival.",
      },
      { type: "H3", ar: "انتعاش الطبيعة", en: "Nature refreshed" },
      {
        type: "P",
        ar: "أحد أعظم الأشياء في الربيع هو مشاهدة كيف تتخلص الطبيعة من معطفها الشتوي ، وتصبح منعشة وخضراء ، ناهيك عن نعمة الأيام الأطول والأدفأ ، الى جانب الطيور المغردة السعيدة بشدة ، فيا ترى ما هو أفضل مكان لاحتضان ومراقبة تغير الفصول من بين قمم الأشجار ؟ وبشكل أكثر تحديدا ، لماذا لا تسكن في منزل شجرة مع وسائل الراحة الحديثة والتصميم الداخلي الاسكندنافي المريح ؟ فهي متوفرة ولك الخيار في ذلك",
        en: "One of the greatest things about spring is watching nature shed its winter coat and turn fresh and green, not to mention the blessing of longer, warmer days along with intensely happy songbirds. So what better place to embrace and observe the changing seasons than among the treetops? More specifically, why not stay in a treehouse with modern comforts and cosy Scandinavian interiors? They are available, and the choice is yours.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : يجب على عشاق الهندسة المعمارية البحث عن بعض الأكواخ ذات الأسطح الشجرية التي تتمتع بتصميم أنيق وفريد من نوعه ، فهذا هو سبب آخر للذهاب الى النرويج",
        en: "Quick tip: architecture lovers should look out for the treetop cabins with their elegant and unique design — one more reason to go to Norway.",
      },
      { type: "H3", ar: "امكانية الغوص في المياه الصافية", en: "Diving in crystal-clear water" },
      {
        type: "P",
        ar: "اذا كنت تحب الغوص ، فتأكد من جدولة مغامرتك تحت الماء في أوائل الربيع ، في هذا الوقت من العام ، لم تبدأ المياه في الدفء فحسب ، بل لا تزال تتمتع برؤية واضحة وضوح الشمس ، في وقت لاحق من الموسم ، تصبح البحار غامضة ، مما يعني أنك بحاجة الى احضار شعلة لرؤيتها ، وعلى الجانب المشرق سيساعد الضوء من الشعلة في جذب العديد من المخلوقات تحت الماء (جميعها صديقة للغواصين) ، اكتشف المزيد عن الغوص في النرويج فهو أمر ممتع لا محاله",
        en: "If you love diving, be sure to schedule your underwater adventure in early spring. At this time of year the water has not only begun to warm up, it still has crystal-clear visibility. Later in the season the seas become murkier, which means you need to bring a torch to see. On the bright side, the light from the torch helps attract many underwater creatures (all of them diver-friendly). Discover more about diving in Norway — it is undoubtedly good fun.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : يعج هاتتان في فيورد النرويج بالحياة تحت الماء ، وتبرز سالستراومين بالقرب من بودو كمكان لتجربة التيارات المثيرة ، أو ماذا عن الشعور بأنك مستكشف حقيقي والغوص بين الحطام في نارفيك ؟ انه أمر رائع",
        en: "Quick tip: the Norwegian fjords teem with underwater life, and Saltstraumen near Bodø stands out as a place to experience thrilling currents. Or how about feeling like a real explorer and diving among the wrecks in Narvik? It is wonderful.",
      },
      { type: "IMG", src: U("2023/04/img_0616.jpg"), cap_ar: "المياه الصافية", cap_en: "Crystal-clear water" },
      { type: "H3", ar: "بدء السباحة في الهواء الطلق", en: "The start of open-air swimming" },
      {
        type: "P",
        ar: "هل أنت فايكنغ حقيقي ؟ اذا عليك أثبات ذلك عن طريق أخذ بضع ضربات جريئة على الأقل في مياه الينابيع الباردة ، وكلما كان ذلك مبكرا ، كان ذلك أفضل ، ولكن بالنسبة للفايكنغ الحديث ، من المقبول البدء في الغوص في بداية مايو تقريبا ، على الرغم من أنه يمكنك ببساطة القفز من أي رصيف يسمح بالسباحة ، اذا فلماذا لا تأخذه الى أعلى درجة ؟ علق مشاكلك بعيدا في ساونا أنيقة وجدد شبابك بالسباحة المنعشة",
        en: "Are you a real Viking? Then prove it by taking at least a few bold strokes in the cold spring water — the earlier the better. But for the modern Viking it is acceptable to start diving in around the beginning of May. Although you can simply jump off any pier where swimming is allowed, why not take it up a level? Hang your troubles away in a stylish sauna and be rejuvenated by a refreshing swim.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : يمكنك العثور على بعض حمامات البخار الفريدة حقا في النرويج ، مثل قارب سبا القطب الشمالي فولكانا في ترومسو ، أو حمامات البخار المخفية في رف تجفيف للأسماك في سولت باوسلو ، هناك أيضا العديد من حمامات البخار العائمة على المضايق والبحيرات النرويجية ، بما في ذلك ساونا سوريا موريا الذهبية الشبيهة بالقصص الخيالية في دالين في تيلمارك",
        en: "Quick tip: you can find some truly unique saunas in Norway, such as the Arctic spa boat Vulkana in Tromsø, or the saunas hidden in a fish-drying rack at SALT in Oslo. There are also many floating saunas on Norwegian fjords and lakes, including the fairytale-like golden Soria Moria sauna in Dalen in Telemark.",
      },
      { type: "H3", ar: "اختبار الانهار الجليدية", en: "Experiencing the glaciers" },
      {
        type: "P",
        ar: "يعد التنزه الجليدي أمرا لا بد منه لأي مغامر حقيقي يزور النرويج في أواخر الربيع ، المغامرة عبر الجليد الذي يزيد عمره عن ألف عام في بعض الأماكن ، يتم تغليفه بظلال الفيروز والتعجب من التكوينات الشبيهة بالنحت ، حيث الطبيعة نفسها هي الفنانة ، يعد التزلج أو المشي لمسافات طويلة في نهر جوستيتالسبرين الجليدي بالطول (60 كيلومترا دائما بصحبة مرشد) مفضلا خاصا بين أولئك الذين هم في حالة جيدة ، لا تقلق ليست كل المشي الجليدي متطلبا مثل ذلك",
        en: "A glacier hike is a must for any real adventurer visiting Norway in late spring: an adventure across ice that is more than a thousand years old in some places, wrapped in shades of turquoise, marvelling at sculpture-like formations where nature itself is the artist. Skiing or hiking the length of the Jostedalsbreen glacier (60 kilometres, always with a guide) is a particular favourite among those in good shape. Do not worry — not all glacier walks are that demanding.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : تتوفر مغامرات الأنهار الجليدية للجميع في العديد من الفروع الجليدية في Jostedalsbreen ، مثل نهر Nigardsbreen الجليدي في Sogn og Fjordane ، والنهر الجليدي Folgefonna في Hardanger ، والنهر الجليدي Svartisen في Nordland ، من بين أمور أخرى ، تبدأ معظم الجولات المنتظمة على الأنهار الجليدية في مايو أو بداية يونيو",
        en: "Quick tip: glacier adventures are available for everyone on many of the arms of Jostedalsbreen, such as the Nigardsbreen glacier in Sogn og Fjordane, the Folgefonna glacier in Hardanger and the Svartisen glacier in Nordland, among others. Most regular glacier tours start in May or the beginning of June.",
      },
      { type: "IMG", src: U("2023/04/img_0613.jpg"), cap_ar: "الأنهار الجليدية", cap_en: "The glaciers" },
      { type: "H3", ar: "ظاهرة تزلج الربيع", en: "The phenomenon of spring skiing" },
      {
        type: "P",
        ar: "تزلج الربيع Vårskiturer ، فقد تحظى النرويج بشعبية كبيرة في بعض المناطق الجبلية وفي الشمال ، عادة ما يكون هناك الكثير من الثلوج البكر حتى أواخر أبريل ومايو ، والأيام الأكثر دفئا (قد تتمكن من التزلج بقميص صوفي) وتنمو لفترة أطول وأطول",
        en: "Spring skiing, vårskiturer, is hugely popular in some mountain areas and in the north. There is usually plenty of untouched snow into late April and May, and the days grow warmer (you may be able to ski in a woollen shirt) and longer and longer.",
      },
      {
        type: "P",
        ar: "ففي شمال النرويج ، تحصل حتى على شمس منتصف الليل في أواخر الربيع ، لا تغلق العديد من منتجعات التزلج على الجليد حتى نهاية نيسان (أبريل) ، ففي العديد من المناطق يكون الربيع هو الموسم المثالي لجولات التزلج وركوب الطائرات الورقية ، وذلك بفضل انعكاس الشمس عن الثلج ، وقد تحصل أيضا على تان جميل في الربيع ، فقط لا تنس أن تحزم كريم الوقاية من الشمس والنظارات الشمسية",
        en: "In northern Norway you even get the midnight sun in late spring. Many ski resorts do not close until the end of April, and in many areas spring is the ideal season for ski touring and snowkiting. Thanks to the sun reflecting off the snow you may also get a lovely tan in spring — just do not forget to pack sunscreen and sunglasses.",
      },
      {
        type: "P",
        ar: "نصيحة سريعة : جرب Narvikfjellet وهو منتجع تزلج في الشمال ، حيث يمكنك التزلج من أعلى الجبل وصولا الى المضيق البحري ، غالبا حتى يونيو ، أو استقل القطار الى Finse بين أوسلو وبيرغن لركوب الطائرات الورقية (تتوفر الدورات التدريبية) والتزلج الريفي على الثلج على هضبة جبل هاردانجيرفيدا",
        en: "Quick tip: try Narvikfjellet, a ski resort in the north where you can ski from the mountain top all the way down to the fjord, often until June. Or take the train to Finse between Oslo and Bergen for snowkiting (courses available) and cross-country skiing on the Hardangervidda mountain plateau.",
      },
    ],
  },
  {
    slug: "opera-house",
    title_ar: "تعرف على دار الأوبرا والباليه النرويجية وخصائصها",
    title_en: "The Norwegian Opera & Ballet and what makes it special",
    kicker_ar: "الأوبرا والباليه النرويجية",
    kicker_en: "The Norwegian Opera and Ballet",
    image: U("2023/04/img_0710.jpg"),
    blocks: [
      { type: "H3", ar: "هيا لنمضي أوقات ممتعة في أجمل اوبرا", en: "Let us spend some wonderful hours in the most beautiful opera house" },
      {
        type: "P",
        ar: "من أجمل المبانى التى يمكن أن تراها على الاطلاق فهى تمتاز بهندسة معمارية فريدة فتجدها تخرج من قلب الماء بلونها الأبيض الجميل و بهندستها المعمارية الغريبة",
        en: "One of the most beautiful buildings you will ever see. It has a unique architecture, rising out of the water itself in beautiful white with its extraordinary design.",
      },
      {
        type: "P",
        ar: "يمكنك المشى حتى على سطحها ويوفر السطح لك مجموعة من المناظر البانورامية الجميلة ، ويمكن أن تتمتع برؤية الجزر المحيطة بها وهناك العديد من الجولات التى تنظمها الى المدينة لزيارة دار الأوبرا مصحوبة بمجموعة من المرشدين الذين يجيبون على أسئلتك مما سيمكنك من التعرف على تاريخ الأوبرا جيدا ، ويمكنك أيضا تجربة حجز تذكرة والاستمتاع بالعروض والحفلات التى تقدمها الأوبرا",
        en: "You can even walk on its roof, which gives you a range of beautiful panoramic views, and you can enjoy the sight of the surrounding islands. Many city tours are organised to visit the Opera House with guides who answer your questions, so you can get to know its history well, and you can also try booking a ticket and enjoying the performances and concerts it presents.",
      },
      { type: "IMG", src: U("2023/04/img_0701.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو", cap_en: "The Opera and Ballet House in Oslo" },
      { type: "IMG", src: U("2023/04/img_0702.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو", cap_en: "The Opera and Ballet House in Oslo" },
      { type: "IMG", src: U("2023/04/img_0703.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو", cap_en: "The Opera and Ballet House in Oslo" },
      { type: "IMG", src: U("2023/04/img_0706.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو", cap_en: "The Opera and Ballet House in Oslo" },
      { type: "IMG", src: U("2023/04/img_0707.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو", cap_en: "The Opera and Ballet House in Oslo" },
      { type: "IMG", src: U("2023/04/img_0709.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو", cap_en: "The Opera and Ballet House in Oslo" },
      { type: "H3", ar: "نماذج من العروض التي تقدمها دار الأوبرا والباليه بأوسلو", en: "Examples of the performances presented at the Oslo Opera and Ballet House" },
      { type: "IMG", src: U("2023/04/img_0704.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "H3", ar: "العنوان وموقع الأوبرا على الخريطة", en: "The address and the location of the opera on the map" },
      {
        type: "LIST",
        ar: ["العنوان : Kirsten Flagstads plass 1, Oslo", "اسم دار الأوبرا بالنرويجي : Den Norske Opera & Ballett"],
        en: ["Address: Kirsten Flagstads plass 1, Oslo", "Norwegian name: Den Norske Opera & Ballett"],
      },
      { type: "IMG", src: U("2023/04/img_0705.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "H3", ar: "خصائص دار الأوبرا والباليه", en: "The features of the Opera and Ballet House" },
      {
        type: "P",
        ar: "تقع دار الأوبرا في أوسلو مباشرة عند الميناء ، مع مظهر خارجي أبيض بزاوية يبدو أنه يرتفع من الماء ، يدعو زواره لتسلق سقفه والاستمتاع بالمناظر البانورامية لأوسلو والمضيق البحري ، على مدار السنة",
        en: "The Opera House lies right at the harbour in Oslo, with an angled white exterior that seems to rise out of the water, inviting visitors to climb its roof and enjoy panoramic views of Oslo and the fjord all year round.",
      },
      {
        type: "P",
        ar: "توفر النوافذ واسعة النطاق على مستوى الشارع للجمهور لمحات من البروفات وأنشطة الورش ، الجزء الداخلي من المبنى عبارة عن خشب البلوط بشكل أساسي ، والقاعة الرئيسية على شكل حدوة حصان ، تذكرنا بالمسارح الكلاسيكية في الماضي ، تم تصميم الأوبرا من قبل شركة الهندسة المعمارية النرويجية سنوهيتا ، وحصلت على العديد من الجوائز المرموقة",
        en: "Large-scale windows at street level give the public glimpses of rehearsals and workshop activity. The interior of the building is mainly oak, and the main hall is horseshoe-shaped, recalling the classical theatres of the past. The opera was designed by the Norwegian architecture firm Snøhetta and has won many prestigious awards.",
      },
      { type: "IMG", src: U("2023/04/img_0718.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "IMG", src: U("2023/04/img_0717.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "IMG", src: U("2023/04/img_0716.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "IMG", src: U("2023/04/img_0714.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "IMG", src: U("2023/04/img_0713.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "IMG", src: U("2023/04/img_0712-2.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      {
        type: "P",
        ar: "تقدم الأوبرا والباليه الوطنية النرويجية برنامجا غنيا ومتنوعا من ثلاث مراحل : البيت الرئيسي (1369 مقعدا) والبيت الثاني (400 مقعد) والاستوديو (200 مقعد) ، يستخدم سقف الأوبرا والبهو أيضا للحفلات الموسيقية",
        en: "The Norwegian National Opera and Ballet presents a rich and varied programme on three stages: the Main House (1,369 seats), the Second House (400 seats) and the Studio (200 seats). The opera roof and foyer are also used for concerts.",
      },
      {
        type: "P",
        ar: "دار أوبرا هي المقر الرئيسي للأوبرا النرويجية والمسرح الوطني للأوبرا في النرويج ، افتتحت في 12 ابريل 2008م ، يقع المبنى في حي Bjørvika في وسط أوسلو على رأس Oslofjord ، يتم تشغيل الدار من قبل Statsbygg الوكالة الحكومية التي تدير الممتلكات للحكومة النرويجية",
        en: "The Opera House is the home of the Norwegian National Opera and the national opera theatre of Norway. It opened on 12 April 2008 and stands in the Bjørvika district of central Oslo at the head of the Oslofjord. It is run by Statsbygg, the government agency that manages property for the Norwegian state.",
      },
      {
        type: "P",
        ar: "يحتوي المبنى على 1100 غرفة بمساحة اجمالية تبلغ 49 ألف متر مربع ، أما المسرح الرئيسي فهو بعرض 16 مترا ، وعمق 40 مترا ، الأسطح الخارجية المائلة للمبنى مغطاة بالرخام من كارارا بايطاليا ، والجرانيت الأبيض تجعله يبدو وكأنه يرتفع من الماء ، وهو أكبر مبنى ثقافي تم بناؤه في النرويج منذ اكتمال Nidarosdomen حوالي عام 1300م",
        en: "The building contains 1,100 rooms with a total area of 49,000 square metres. The main stage is 16 metres wide and 40 metres deep. The sloping outer surfaces are clad in marble from Carrara in Italy and white granite, making it look as if it rises from the water, and it is the largest cultural building constructed in Norway since Nidarosdomen was completed around 1300.",
      },
      {
        type: "P",
        ar: "تتوفر الجولات المصحوبة بمرشدين باللغتين النرويجية والإنجليزية",
        en: "Guided tours are available in both Norwegian and English.",
      },
      { type: "IMG", src: U("2023/04/img_0712-1.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
      { type: "H3", ar: "أوقات العمل", en: "Opening hours" },
      {
        type: "LIST",
        ar: [
          "6 أبريل – 10 أبريل : الاثنين والخميس والجمعة والسبت والأحد من 12:00 ظهرا حتى 4:00 مساء",
          "11 أبريل – 25 مايو : من الاثنين حتى السبت من 11:00 صباحا حتى 10:00 مساء ، والأحد من 12:00 ظهرا حتى 6:00 مساء",
          "2 يناير – 5 أبريل : من الاثنين حتى السبت من 11:00 صباحا حتى 10:00 مساء ، والأحد من 12:00 ظهرا حتى 6:00 مساء",
        ],
        en: [
          "Apr 6 – Apr 10: Mon, Thu, Fri, Sat, Sun 12:00 PM–4:00 PM",
          "Apr 11 – May 25: Mon–Sat 11:00 AM–10:00 PM, Sun 12:00 PM–6:00 PM",
          "Jan 2 – Apr 5: Mon–Sat 11:00 AM–10:00 PM, Sun 12:00 PM–6:00 PM",
        ],
      },
      { type: "IMG", src: U("2023/04/img_0710-1.jpg"), cap_ar: "دار الأوبرا والباليه بأوسلو بالنرويج", cap_en: "The Opera and Ballet House in Oslo, Norway" },
    ],
  },
];
