import type { Guide } from "./france-guides";

export const spainProgramsD: Guide[] = [
  {
    slug: "program-andalusia",
    title_ar: "برنامج سياحي – مدن الأندلس – اسبانيا",
    title_en: "Travel itinerary – the cities of Andalusia – Spain",
    kicker_ar: "برنامج سياحي",
    kicker_en: "Itinerary",
    image:
      "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0898.jpg?resize=558%2C236&ssl=1",
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "اكتشف اسبانيا — برنامج سياحي متكامل لمدة ثمانية أيام — مدن الأندلس — لتكن اسبانيا وجهتك القادمة !",
        en: "Discover Spain — A complete eight-day travel itinerary — The cities of Andalusia — Let Spain be your next destination!",
      },
      {
        type: "P",
        ar: "تقدم لك هذه الرحلة الجواهر المعمارية للأندلس : غرناطة واشبيلية وقرطبة ومالقا ، بالاضافة الى امتداد ساحل كوستا ديل سول الشهير ، بما في ذلك شواطئها الذهبية وقراها المطلية باللون الأبيض ونمط الحياة المريح الذي يمكنك اختباره بشكل أفضل في مدينة ماربيا السياحية",
        en: "This trip offers you the architectural jewels of Andalusia: Granada, Seville, Cordoba and Malaga, in addition to the famous stretch of the Costa del Sol coast, including its golden beaches, its whitewashed villages, and the relaxed lifestyle that you can best experience in the tourist city of Marbella.",
      },
      {
        type: "P",
        ar: "هذه أرض الثقافة والتاريخ والحفلات والمناطق الطبيعية والطعام الممتاز ، ستتمكن من زيارة كل شيء من المعالم الأثرية الرائعة الى مجموعة واسعة من المناظر الطبيعية المختلفة وستتاح لك الفرصة للمشاركة في العديد من الأحداث الشعبية الفريدة وتذوق مجموعة من منتجات تذوق الطعام اللذيذة",
        en: "This is a land of culture, history, festivals, natural areas and excellent food. You will be able to visit everything from magnificent monuments to a wide variety of different landscapes, and you will have the chance to take part in many unique popular events and taste a range of delicious food products.",
      },
      {
        type: "P",
        ar: "تتمثل احدى طرق اكتشاف ثقافة الأندلس في استكشاف المواقع التي منحت تصنيف اليونسكو للتراث العالمي ، في غرناطة سترى قصر الحمراء وحدائق العريف وحي ألبايسين في العصور الوسطى ، وفي قرطبة وسطها التاريخي مع المسجد الكبير ، وفي اشبيلية الكاتدرائية وقصر الكازار وأرشيف جزر الهند ، وفي خاين المواقع الأثرية ، وفي أوبيدا وبايزا",
        en: "One way to discover the culture of Andalusia is to explore the sites that have been given UNESCO World Heritage status: in Granada you will see the Alhambra palace, the Generalife gardens and the medieval Albaicín quarter; in Cordoba its historic centre with the great Mosque; in Seville the cathedral, the Alcazar palace and the Archive of the Indies; in Jaén the archaeological sites; and in Úbeda and Baeza.",
      },
      {
        type: "P",
        ar: "ستتمكن أيضا من تجربة مهرجانات مثل أسبوع عيد الفصح والكرنفال في قادس وحج روسيو في هويلفا ومعرض أبريل في اشبيلية",
        en: "You will also be able to experience festivals such as Holy Week, the carnival in Cadiz, the Rocío pilgrimage in Huelva, and the April Fair in Seville.",
      },
      {
        type: "P",
        ar: "ستجد مجموعة متنوعة من المناظر الطبيعية التي تتراوح من شواطئ كوستا ديل سول وكوستا دي لا لوز والميريا الى بساتين الزيتون الواسعة في خاين ، يمكنك زيارة حديقة دونيانا الوطنية التي تم الاعلان عنها أيضا كموقع للتراث العالمي أو الذهاب للتزلج في منتجع سييرا نيفادا للتزلج",
        en: "You will find a variety of landscapes ranging from the beaches of the Costa del Sol, the Costa de la Luz and Almeria to the vast olive groves of Jaén. You can visit Doñana National Park, which has also been declared a World Heritage site, or go skiing at the Sierra Nevada ski resort.",
      },
      {
        type: "P",
        ar: "أخيرا ، تذكر أن الأندلس لديها ألف نكهة مختلفة في انتظار تجربتها ، من حمائر خيريز (كاديز) ومونتيلا – موريالس (غرطبة) ، الى الأطباق الكلاسيكية للأسماك المقلية الطازجة المعروفة باسم بيسكيتو فريتو ، من قادس ومالقا ، ولحم الخنزير المعالج من هويلفا وغرطبة ، وزيت الزيتون ، وغيرها من الأطباق النموذجية مثل جازباتشو وسالموريجو",
        en: "Finally, remember that Andalusia has a thousand different flavours waiting to be tried, from the sherries of Jerez (Cadiz) and Montilla-Moriles (Cordoba), to the classic dishes of freshly fried fish known as pescaíto frito from Cadiz and Malaga, cured ham from Huelva and Cordoba, olive oil, and other typical dishes such as gazpacho and salmorejo.",
      },
      {
        type: "H3",
        ar: "اليوم الأول والثاني",
        en: "Day one and two",
        sub_ar: "أشبيلية",
        sub_en: "Seville",
      },
      {
        type: "P",
        ar: "يمكنك الوصول الى محطة سانتا خوستا في أشبيلية بواسطة قطار AVE فائق السرعة من محطة مدريد Madrid Puerta de Atocha (ساعتان و20 دقيقة) ، أو محطة برشلونة Barcelona Sants (5 ساعات و50 دقيقة) ، أو السفر جوا الى مطار أشبيلية سان بابلو",
        en: "You can reach Santa Justa station in Seville by high-speed AVE train from Madrid Puerta de Atocha station (2 hours and 20 minutes), or from Barcelona Sants station (5 hours and 50 minutes), or by flying to Seville San Pablo airport.",
      },
      {
        type: "P",
        ar: "اقضي اليومين التاليين في استكشاف عاصمة الأندلس ، وهي مدينة لا يجب اغفالها في أي رحلة الى جنوب اسبانيا ، يمكنك زيارة الكاتدرائية ومشاهدة برج الجرس الجميل لا خيرالدا ، أو قصر المورق المذهل ، أو التجول في حي سانتا كروز الساحر",
        en: "Spend the next two days exploring the capital of Andalusia, a city that must not be overlooked on any trip to southern Spain. You can visit the cathedral and see the beautiful bell tower, La Giralda, or the stunning Moorish palace, or stroll through the charming Santa Cruz quarter.",
      },
      {
        type: "P",
        ar: "في المساء لا تفوت فرصة حضور عرض رائع للفلامنكو",
        en: "In the evening, do not miss the chance to attend a wonderful flamenco show.",
      },
      { type: "P", ar: "المبيت في أشبيلية", en: "Overnight in Seville." },
      {
        type: "H3",
        ar: "اليوم الثالث",
        en: "Day three",
        sub_ar: "أشبيلية / قرطبة",
        sub_en: "Seville / Cordoba",
      },
      {
        type: "P",
        ar: "استقل قطار AVE فائق السرعة من محطة أشبيلية سانتا خوستا الى محطة قرطبة المركزية (43 دقيقة) ، صنفت هذه المدينة كتراث عالمي من طرف اليونسكو ، وقد كانت عاصمة الخلافة الأموية ، وهي موطن للمسجد الكبير المذهل في قرطبة",
        en: "Take the high-speed AVE train from Seville Santa Justa station to Cordoba Central station (43 minutes). This city has been classified as a UNESCO World Heritage site, was the capital of the Umayyad Caliphate, and is home to Cordoba's magnificent great Mosque.",
      },
      {
        type: "P",
        ar: "سافر عبر التاريخ ، بينما تتجول في الحي اليهودي القديم ، ثم توقف لالتقاط صورة على الجسر الروماني ، واكتشف الأفنية والساحات الملونة المليئة بالنباتات المزهرة أو استمتع بعرض الفروسية في الاسطبلات الملكية",
        en: "Travel through history as you wander through the old Jewish quarter, then stop to take a photo on the Roman bridge, and discover the colourful courtyards and squares full of flowering plants, or enjoy an equestrian show at the Royal Stables.",
      },
      { type: "P", ar: "المبيت في قرطبة", en: "Overnight in Cordoba." },
      {
        type: "H3",
        ar: "اليوم الرابع",
        en: "Day four",
        sub_ar: "قرطبة / غرناطة",
        sub_en: "Cordoba / Granada",
      },
      {
        type: "P",
        ar: "استقل قطار AVE فائق السرعة من محطة قرطبة المركزية الى غرناطة (ساعة و33 دقيقة) ، التي تقع على سفح جبال سييرا نيفادا وعلى بعد ساعة من البحر",
        en: "Take the high-speed AVE train from Cordoba Central station to Granada (1 hour and 33 minutes), which lies at the foot of the Sierra Nevada mountains and an hour from the sea.",
      },
      {
        type: "P",
        ar: "في المساء قم بزيارة الحي الغجري المسمى حي ساكرامونتي ، المعروف بمنازل الكهوف ورقص الفلامنكو",
        en: "In the evening, visit the gypsy quarter called Sacromonte, known for its cave houses and flamenco dancing.",
      },
      { type: "P", ar: "المبيت في غرناطة", en: "Overnight in Granada." },
      {
        type: "H3",
        ar: "اليوم الخامس",
        en: "Day five",
        sub_ar: "غرناطة",
        sub_en: "Granada",
      },
      {
        type: "P",
        ar: "تشتهر غرناطة المصنفة كتراث عالمي بحدائق جنة العريف وقصر الحمراء الجميل ومنطقة البيازين ، وهي مدينة ثقافية غنية يأجواء رائعة وحيوية ومليئة بمقاهي المأكولات الخفيفة وغرف الشاي العربية",
        en: "Granada, classified as a World Heritage site, is famous for the Generalife gardens, the beautiful Alhambra palace and the Albaicín district. It is a culturally rich city with a wonderful, lively atmosphere, full of snack cafés and Arab tea rooms.",
      },
      { type: "P", ar: "المبيت في غرناطة", en: "Overnight in Granada." },
      {
        type: "H3",
        ar: "اليوم السادس",
        en: "Day six",
        sub_ar: "غرناطة / مالقا",
        sub_en: "Granada / Malaga",
      },
      {
        type: "P",
        ar: "استقل قطار AVE فائق السرعة الى أنتيكيرا ثم قم بتغيير القطار الى مالقا (ساعة و35 دقيقة) ، مالقا هي عاصمة ساحل كوستا ديل سول ، الذي يعتبر أشهر خط ساحلي في اسبانيا ، وهي مدينة ساحلية حافلة بالتاريخ والثقافة مثل القصبة الاسلامية والمسرح الروماني ومتحف بيكاسو",
        en: "Take the high-speed AVE train to Antequera, then change trains to Malaga (1 hour and 35 minutes). Malaga is the capital of the Costa del Sol, considered the most famous coastline in Spain, and it is a coastal city rich in history and culture, such as the Alcazaba fortress, the Roman theatre and the Picasso Museum.",
      },
      {
        type: "P",
        ar: "لا تنسى التسوق من المتاجر التي تقدم كل شيء ابتداء من الحرف اليدوية الأندلسية الى الأزياء الراقية ، والتمتع بالحياة الليلية النابضة بالحياة في المدينة",
        en: "Do not forget to shop at stores offering everything from Andalusian handicrafts to high fashion, and to enjoy the city's vibrant nightlife.",
      },
      { type: "P", ar: "المبيت في مالقا", en: "Overnight in Malaga." },
      {
        type: "H3",
        ar: "اليوم السابع",
        en: "Day seven",
        sub_ar: "مالقا / ماربيا ، أو روندا أو شواطئ ساحل كوستا ديل سول",
        sub_en: "Malaga / Marbella, or Ronda, or the beaches of the Costa del Sol",
      },
      {
        type: "P",
        ar: "يمكنك استئجار سيارة والتوجه الى مدينة ماربيا الساحلية المعروفة بنمط الحياة الفاخر الذي توفره ، والمعروفة كذلك بالمدينة القديمة الساحرة ، من أشهرها مرسى بويرتو بانوس المليء باليخوت الفاخرة ومطاعم المأكولات الفاخرة والمحلات التجارية الحصرية",
        en: "You can rent a car and head to the coastal city of Marbella, known for the luxurious lifestyle it offers, as well as for its charming old town. Among its most famous spots is Puerto Banús marina, filled with luxury yachts, fine-dining restaurants, and exclusive shops.",
      },
      {
        type: "P",
        ar: "أو يمكنك أيضا ركوب قطار AVE فائق السرعة (ساعتين ونصف) والقيام برحلة الى مدينة روندا الأندلسية ، والتنزه على طول شوارعها المرصوفة بالحجارة والجسر الجديد المذهل الذي يمتد عبر نهر التاخو",
        en: "Or you can also take the high-speed AVE train (two and a half hours) and make a trip to the Andalusian city of Ronda, and stroll along its cobblestone streets and the stunning New Bridge that spans the Tajo river.",
      },
      {
        type: "P",
        ar: "أو ابتعد أكثر لاستكشاف شواطىء متعددة في كوستا ديل سول ، ومنتجعات الشواطىء الشهيرة جدا والمعروفة مثل Benalmadena أو Torremolinos أو Estepona",
        en: "Or venture further afield to explore multiple beaches on the Costa del Sol, and the very famous, well-known beach resorts such as Benalmádena, Torremolinos or Estepona.",
      },
      { type: "P", ar: "المبيت في مالقا", en: "Overnight in Malaga." },
      {
        type: "H3",
        ar: "اليوم الثامن",
        en: "Day eight",
        sub_ar: "مالقا",
        sub_en: "Malaga",
      },
      {
        type: "P",
        ar: "خذ رحلة العودة الى وطنك من مطار مالقا ، وفي حفظ الله ، أو استقل قطار AVE فائق السرعة الى محطة مدريد بويرتا دي أتوشا (ساعتان و40 دقيقة) لمواصلة الرحلة لمدن أخرى متميزة في اسبانيا",
        en: "Take your return flight home from Malaga airport, and may God protect you, or take the high-speed AVE train to Madrid Puerta de Atocha station (2 hours and 40 minutes) to continue your trip to other distinctive cities in Spain.",
      },
    ],
  },
  {
    slug: "program-madrid-barcelona",
    title_ar: "برنامج سياحي – مدريد وبرشلونة والمناطق المجاورة – اسبانيا",
    title_en:
      "Travel itinerary – Madrid, Barcelona and the surrounding areas – Spain",
    kicker_ar: "برنامج سياحي",
    kicker_en: "Itinerary",
    image:
      "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0898.jpg?resize=558%2C236&ssl=1",
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "اكتشف اسبانيا — برنامج سياحي متكامل لمدة تسعة أيام — مدريد وبرشلونة والمناطق المجاورة — لتكن اسبانيا وجهتك القادمة !",
        en: "Discover Spain — A complete nine-day travel itinerary — Madrid, Barcelona and the surrounding areas — Let Spain be your next destination!",
      },
      {
        type: "P",
        ar: "يجمع هذا المسار بين المدينتين الرمزيتين في اسبانيا وهما مدريد وبرشلونة ، برحلات يومية الى مدن التراث العالمي وهي : شقوبية وتوليدو / كوينكا انطلاقا من العاصمة والجولات الى جبل مونتسيرات وكوستا برافا الجميلة انطلاقا من برشلونة ، يمكنك السفر بين المدينتين بواسطة قطار AVE فائق السرعة ، تستغرق الرحلة ساعتين ونصف فقط",
        en: "This route combines the two iconic cities of Spain, Madrid and Barcelona, with day trips to World Heritage cities, namely: Segovia and Toledo/Cuenca setting off from the capital, and excursions to Montserrat mountain and the beautiful Costa Brava setting off from Barcelona. You can travel between the two cities by high-speed AVE train, the journey taking only two and a half hours.",
      },
      {
        type: "H3",
        ar: "اليوم الأول والثاني",
        en: "Day one and two",
        sub_ar: "مدريد",
        sub_en: "Madrid",
      },
      {
        type: "P",
        ar: "الوصول الى مطار مدريد باراخاس ، اقض اليومين التاليين في استكشاف المعالم السياحية الرئيسية في مدريد عاصمة اسبانيا ، مثل القصر الملكي ، ومتحف برادو ، وجران فيا ، وملعب سانتياغو بيرنابيو ، والتسوق في منطقة الميل الذهبي",
        en: "Arrival at Madrid Barajas airport. Spend the next two days exploring the main tourist attractions of Madrid, Spain's capital, such as the Royal Palace, the Prado Museum, Gran Vía, Santiago Bernabéu stadium, and shopping in the Golden Mile area.",
      },
      { type: "P", ar: "المبيت في مدريد", en: "Overnight in Madrid." },
      {
        type: "H3",
        ar: "اليوم الثالث",
        en: "Day three",
        sub_ar: "رحلة ليوم كامل الى مدينة شقوبية",
        sub_en: "A full-day trip to the city of Segovia",
      },
      {
        type: "P",
        ar: "خذ القطار فائق السرعة AVE / AVANT من محطة مدريد الرئيسية شامارتين الى مدينة شقوبية المصنفة كتراث عالمي من طرف اليونسكو (27 دقيقة)",
        en: "Take the high-speed AVE/AVANT train from Madrid's main Chamartín station to the city of Segovia, classified as a UNESCO World Heritage site (27 minutes).",
      },
      {
        type: "P",
        ar: "بعد الوصول استكشف هذه المدينة التي يعود تاريخها الى العصور الوسطى بما في ذلك زيارة القناة المائية الرومانية ، والقصر الاسلامي ، والتنزه على طول شوارعها التي تعود للقرون الوسطى ، والتسوق من متاجر الهدايا التذكارية المحلية",
        en: "After arriving, explore this city whose history goes back to the Middle Ages, including a visit to the Roman aqueduct and the Islamic-era Alcázar, strolling along its medieval streets, and shopping at local souvenir stores.",
      },
      {
        type: "P",
        ar: "بعد الغداء واذا كنت ترغب في ذلك ، استقل سيارة أجرة أو حافلة عامة لزيارة القصر والحدائق الشهيرة ، ومصنع الزجاج القديم في مدينة لا غرانخا المجاورة",
        en: "After lunch, if you wish, take a taxi or public bus to visit the famous palace and gardens, and the old glass factory in the nearby town of La Granja.",
      },
      {
        type: "P",
        ar: "ثم ارجع الى مدريد للمبيت فيها",
        en: "Then return to Madrid to spend the night.",
      },
      {
        type: "H3",
        ar: "اليوم الرابع",
        en: "Day four",
        sub_ar: "رحلة ليوم كامل الى طليطلة أو كوينكا",
        sub_en: "A full-day trip to Toledo or Cuenca",
      },
      {
        type: "H3",
        ar: "في حال اخترت طليطلة",
        en: "If you choose Toledo",
      },
      {
        type: "P",
        ar: "استقل قطار AVANT فائق السرعة من محطة مدريد بويرتا دي أتوتشا ثم توجه الى مدينة طليطلة المصنفة كتراث عالمي من طرف اليونسكو (33 دقيقة)",
        en: "Take the high-speed AVANT train from Madrid Puerta de Atocha station, then head to the city of Toledo, classified as a UNESCO World Heritage site (33 minutes).",
      },
      {
        type: "P",
        ar: "وعند الوصول استكشف سيرا على الأقدام هذه المدينة الساحرة التي تعرف بمدينة الثقافات الثلاث ، والمشهورة بماضيها الاسلامي والمسيحي واليهودي ، تعتبر طليطلة مكانا رائعا للتسوق من محلات الحرف اليدوية المحلية",
        en: "Upon arrival, explore on foot this charming city known as the City of the Three Cultures, famous for its Islamic, Christian and Jewish past. Toledo is a wonderful place to shop for local handicrafts.",
      },
      {
        type: "P",
        ar: "ثم العودة الى مدريد للمبيت",
        en: "Then return to Madrid to spend the night.",
      },
      {
        type: "H3",
        ar: "في حال اخترت كوينكا",
        en: "If you choose Cuenca",
      },
      {
        type: "P",
        ar: "استقل قطار AVE / AVANT فائق السرعة من محطة بويرتا دي أتوشا ثم توجه الى مدينة كوينكا المصنفة كتراث عالمي من طرف اليونسكو (54 دقيقة) ، والتي تقع على منحدرات نهر هويكار",
        en: "Take the high-speed AVE/AVANT train from Puerta de Atocha station, then head to the city of Cuenca, classified as a UNESCO World Heritage site (54 minutes), which sits on the cliffs above the Huécar river.",
      },
      {
        type: "P",
        ar: "وعند الوصول حاول استكشاف المنازل المعلقة أو Casas Colgadas ، والتي تشتهر بها المدينة ، ولا تنسى التقاط صورة للذكرى على الجسر المعلق ، بوينتي دي سان بابلو",
        en: "Upon arrival, try to explore the hanging houses, or Casas Colgadas, for which the city is famous, and do not forget to take a souvenir photo on the suspension bridge, Puente de San Pablo.",
      },
      {
        type: "P",
        ar: "ثم العودة الى مدريد للمبيت",
        en: "Then return to Madrid to spend the night.",
      },
      {
        type: "H3",
        ar: "اليوم الخامس",
        en: "Day five",
        sub_ar: "مدريد / برشلونة",
        sub_en: "Madrid / Barcelona",
      },
      {
        type: "P",
        ar: "استقل قطار AVE فائق السرعة من محطة مدريد بويرتا دي أتوشا ثم توجه مباشرة الى محطة برشلونة سانتس (ساعتين ونصف)",
        en: "Take the high-speed AVE train from Madrid Puerta de Atocha station and head directly to Barcelona Sants station (two and a half hours).",
      },
      {
        type: "P",
        ar: "في المساء توجه الى منطقة بورت أولمبيك للاستمتاع بالحياة الليلية الصاخبة",
        en: "In the evening, head to the Port Olímpic area to enjoy the bustling nightlife.",
      },
      { type: "P", ar: "المبيت في برشلونة", en: "Overnight in Barcelona." },
      {
        type: "H3",
        ar: "اليوم السادس",
        en: "Day six",
        sub_ar: "برشلونة",
        sub_en: "Barcelona",
      },
      {
        type: "P",
        ar: "اقض يومك في استكشاف هذه المدينة العالمية ، الهندسة المعمارية للمهندس غاودي في كنيسة العائلة المقدسة الشهيرة ، أو مبنى لا بيدريرا ، أو حتى حديقة غويل ، أو التنزه على طول لاس رامبلاس ، أو التسوق في شارع غراسيا ، أو زيارة ملعب كامب نو",
        en: "Spend your day exploring this cosmopolitan city: the architecture of Gaudí at the famous Sagrada Família church, or the La Pedrera building, or even Park Güell, or strolling along Las Ramblas, or shopping on Gràcia street, or visiting Camp Nou stadium.",
      },
      { type: "P", ar: "المبيت في برشلونة", en: "Overnight in Barcelona." },
      {
        type: "H3",
        ar: "اليوم السابع",
        en: "Day seven",
        sub_ar: "رحلة ليوم كامل الى منتسرات",
        sub_en: "A full-day trip to Montserrat",
      },
      {
        type: "P",
        ar: "اليوم توجه الى مرتفعات مونتسيرات الصخرية المعروفة بتشكيلاتها الصخرية الوردية الفريدة ومناظرها المذهلة ، ودير البينديكتين الذي يبلغ عمره 1000 عام ، يمكنك اما القيام بجولة مع مرشد الى مونتسيرات أو ركوب قطار من ساحة اسبانيا",
        en: "Today head to the rocky heights of Montserrat, known for their unique pink rock formations and stunning views, and the 1000-year-old Benedictine monastery. You can either take a guided tour to Montserrat or catch a train from Plaça d'Espanya.",
      },
      {
        type: "P",
        ar: "هناك طريقتان للوصول الى قمة مونتسيرات من ساحة اسبانيا ، الطريقة الأكثر جمالا وأسرعها هي النزول في محطة Aeri di Montserrat ، حيث يمكنك ركوب التلفريك الى الأعلى ، أو الأخذ بالخيار الآخر وهو المضي قدما نحو محطة دير مونتسيرات وركوب القطار الجبلي الى الأعلى",
        en: "There are two ways to reach the summit of Montserrat from Plaça d'Espanya. The more scenic and faster way is to get off at Aeri de Montserrat station, where you can ride the cable car up, or take the other option, which is to continue to Montserrat Monastery station and ride the mountain train up.",
      },
      { type: "P", ar: "المبيت في برشلونة", en: "Overnight in Barcelona." },
      {
        type: "H3",
        ar: "اليوم الثامن",
        en: "Day eight",
        sub_ar: "رحلة ليوم كامل الى مدينة جيرونا وساحل كوستا برافا",
        sub_en: "A full-day trip to the city of Girona and the Costa Brava coast",
      },
      {
        type: "P",
        ar: "سافر عبر المناطق الريفية ذات المناظر الخلابة لزيارة مدينة جيرونا الرومانية الملونة واكتشف المدينة القديمة الرائعة",
        en: "Travel through picturesque countryside to visit the colourful Roman city of Girona and discover its wonderful old town.",
      },
      {
        type: "P",
        ar: "استمر في المنطقة الشاطئية لساحل كوستا برافا المحاطة بالجمال البري ، وفي الطريق قم بزيارة مدينة Pals الساحرة ، وكذلك قرية Calella de Palafrugell الساحلية ، استمتع بالشواطئ واستكشف الشوارع الجذابة ، أو استمتع فقط بأشعة شمس البحر الأبيض المتوسط",
        en: "Continue on to the coastal area of the Costa Brava, surrounded by wild beauty, and on the way visit the charming town of Pals, as well as the coastal village of Calella de Palafrugell. Enjoy the beaches and explore the attractive streets, or simply relax in the Mediterranean sunshine.",
      },
      { type: "P", ar: "المبيت في برشلونة", en: "Overnight in Barcelona." },
      {
        type: "H3",
        ar: "اليوم التاسع",
        en: "Day nine",
        sub_ar: "برشلونة",
        sub_en: "Barcelona",
      },
      {
        type: "P",
        ar: "خذ رحلة العودة الى وطنك من مطار برشلونة ال برات ، وفي حفظ الله",
        en: "Take your return flight home from Barcelona El Prat airport, and may God protect you.",
      },
    ],
  },
];
