import type { Guide } from "./france-guides";

const IMG = (n: string) => `https://i0.wp.com/100region.com/wp-content/uploads/2023/04/${n}?w=1400&ssl=1`;

// Nine deep-dive shopping pages linked from the "markets" guide of Spain.
export const spainGuidesShopping: Guide[] = [
  {
    slug: "shopping-crafts",
    title_ar: "عالم غني بالحرف اليدوية في اسبانيا",
    title_en: "A world rich in Spanish handicrafts",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0950.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "تسوق من خلال اكتشاف روائع الحرف اليدوية في اسبانيا — اكتشف العالم الغني بالحرف اليدوية في اسبانيا",
        en: "Shop while discovering the treasures of Spanish handicrafts — discover the world rich in handicrafts in Spain",
      },
      {
        type: "P",
        ar: "اذا كان التسوق هو شغفك ، أو كنت ترغب في استعادة شيء صغير معك كتذكار عند السفر ، فهذا هو الوقت المناسب لدعم المتاجر المحلية ، تتوفر مجموعة واسعة من الحرف اليدوية في اسبانيا ، وهي عناصر عالية الجودة تشكل جزء من تقاليدهم وثقافتهم",
        en: "If shopping is your passion, or you like to take a small something home with you as a souvenir when you travel, this is the right time to support local shops. A wide range of handicrafts is available in Spain — high-quality items that form part of their traditions and culture.",
      },
      {
        type: "P",
        ar: "عند وصولك ، سترى أن البلدات والمدن في جميع أنحاء البلاد تتميز بنوع معين من الحرف اليدوية ، ابدأ رحلتك الى اسبانيا لاستكشاف العديد من الحرف اليدوية المعروضة !",
        en: "When you arrive, you will see that towns and cities all across the country are distinguished by a particular kind of handicraft. Begin your journey to Spain to explore the many crafts on offer!",
      },
      { type: "H3", ar: "حتما سترغب في شراء شيء ما !", en: "You will certainly want to buy something!" },
      {
        type: "P",
        ar: "ستجد فخارا زخرفيا في تالافيرا دي لا رينا (كاستيل لا مانشا) ، حيث يعود التقليد الى قرون ، في سارغاليدوس (غاليسيا) يتم تزيين السيراميك عموما بتصاميم نباتية ، في لاماس دي مورو (أستورياس) سترى أن الأسود هو اللون السائد ، والفخار المنتج في مانيس (منطقة فالنسيا) ولا بيسبال دي امبوردا (كاتالونيا) محمي بعلامة تجارية مسجلة ومعترف بها من قبل الاتحاد الأوروبي لقيمتها المواسمية العالية",
        en: "You will find decorative pottery in Talavera de la Reina (Castile-La Mancha), where the tradition goes back centuries. In Sargadelos (Galicia) the ceramics are generally decorated with plant designs. In Llamas de Mouro (Asturias) you will see that black is the dominant colour, and the pottery produced in Manises (the Valencia region) and La Bisbal d'Empordà (Catalonia) is protected by a registered trademark recognised by the European Union for its high seasonal value.",
      },
      { type: "H3", ar: "هل تبحث عن عناصر حرفية غير عادية ؟", en: "Are you looking for unusual craft items?" },
      {
        type: "P",
        ar: "اذا كان الأمر كذلك ، فتوجه الى توليدو (كاستيل لا مانشا) لاكتشاف أعمالهم اليومية المعقدة التي تنطوي على استخدام ترصيع الذهب والفضة والخيط ، والفضة وأوراق الذهب على الصلب أو الحديد لتشكيل الأشكال والتصاميم ، أو الى غرناطة (الأندلس) ، حيث ستتعرف على فن انتارسيا ، الذي يعود تاريخه الى العصور الموزارابية ، حيث يتم وضع النجوم والأشكال الأخرى على الخشب",
        en: "If so, head to Toledo (Castile-La Mancha) to discover their intricate daily work involving gold and silver damascening and thread, with silver and gold leaf on steel or iron to form shapes and designs; or to Granada (Andalusia), where you will get to know the art of intarsia, dating back to Mozarabic times, in which stars and other shapes are laid into wood.",
      },
      { type: "H3", ar: "اذا كنت ترغب في شراء سلة …", en: "If you would like to buy a basket …" },
      {
        type: "P",
        ar: "فكل ما عليك القيام به هو التوجه الى مايوركا (جزر البليار) أو لانزاروت (جزر الكناري) ، في كلا المكانين يعملون مع الأنواع المحلية من أشجار النخيل ، وفي كاسيريس تصنع السلال باستخدام الخوص",
        en: "All you have to do is head to Mallorca (the Balearic Islands) or Lanzarote (the Canary Islands); in both places they work with the local species of palm tree, and in Cáceres the baskets are made using wicker.",
      },
      { type: "H3", ar: "الأنواع الأخرى من الحرف اليدوية …", en: "Other kinds of handicrafts …" },
      {
        type: "P",
        ar: "التي ستجدها هي التطريز والدانتيل والأقمشة المنسوجة ، والتي هي نموذجية جدا في غاليسيا وكاديز (الأندلس) وقشتالة وليون ، والأشياء المصنوعة من خشب البقس في نافارا ، والزجاج المنفوخ ، وهي تقنية قديمة يمكنك مشاهدتها في La Granja de San Ildefonso (Castile and Leon)",
        en: "…that you will find are embroidery, lace and woven fabrics, which are very typical in Galicia, Cádiz (Andalusia) and Castile and León; objects made of boxwood in Navarre; and blown glass, an ancient technique you can watch in La Granja de San Ildefonso (Castile and León).",
      },
      { type: "H3", ar: "عند التجول في الشوارع …", en: "When wandering the streets …" },
      {
        type: "P",
        ar: "ستجد الكثير من المتاجر الصغيرة التي تحتوي على جميع أنواع العناصر المصنوعة يدويا ، ولا تنس التحقق قبل السفر لمعرفة ما اذا كانت هناك أي معارض حرفية أو أسواق حرفية تتزامن مع تواريخك",
        en: "…you will find many small shops holding all kinds of handmade items. And do not forget to check before travelling to see whether there are any craft fairs or craft markets that coincide with your dates.",
      },
    ],
  },
  {
    slug: "shopping-atmosphere",
    title_ar: "أجواء تسوق مثالية مفعمة بالموسيقى",
    title_en: "Perfect shopping atmospheres filled with music",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0950.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "تسوق في أسبانيا وسط أجواء مفعمة بالموسيقى — يالله نفرح ونتسوق",
        en: "Shop in Spain amid atmospheres filled with music — let's celebrate and shop",
      },
      {
        type: "P",
        ar: "تقدم اسبانيا العديد من الأحداث المختلفة التي تجعل التسوق تجربة فريدة تماما : الموسيقى المتفائلة والطعام اللذيذ وأحدث اتجاهات التصميم ، وكل هذا في بيئة احتفالية ستكون أكثر متعة حظيت بها على الاطلاق ، اذا كنت تفكر في الذهاب للتسوق في اسبانيا ، فلا تفوت هذه الأحداث الأنيقة !",
        en: "Spain offers many different events that make shopping a completely unique experience: upbeat music, delicious food and the latest design trends, all in a festive setting that will be the most fun you have ever had. If you are thinking of going shopping in Spain, do not miss these stylish events!",
      },
      { type: "H3", ar: "الصيف الأبيض ، جيرونا", en: "White Summer, Girona" },
      {
        type: "P",
        ar: "يقام هذا الحدث الثقافي في جيرونا في منتصف أغسطس ، وهو المكان المثالي للقيام ببعض التسوق الصيفي في محيط لا ينسى ، تقع في بالز ، واحدة من أكثر القرى سحرا في كوستا برافا ، ستتمكن من التسوق في العديد من متاجر العلامات التجارية واكتشاف بعض من أفضل التصميمات الابداعية القادمة من ثقافة البحر الأبيض المتوسط ، ويكمل كل هذا حفلات موسيقية ومجموعة مذهلة من خيارات الطهي ، لا تفوت الفرصة !",
        en: "This cultural event is held in Girona in mid-August and is the perfect place to do some summer shopping in unforgettable surroundings. Located in Pals, one of the most charming villages on the Costa Brava, you will be able to shop in many brand stores and discover some of the best creative designs coming out of Mediterranean culture, all complemented by concerts and an amazing range of culinary options. Do not miss the chance!",
      },
      { type: "H3", ar: "ليلة فوغ فاشن أوت ، مدريد", en: "Vogue Fashion's Night Out, Madrid" },
      {
        type: "P",
        ar: "هل يمكنك أن تتخيل الاستمتاع بليلة في الخارج في مدريد بينما تظل جميع متاجرك المفضلة مفتوحة ؟ مع Vogue Fashion’s Night Out ، يمكنك فعل ذلك بالضبط ، يقام هذا الحدث الساحر في شهر سبتمبر من كل عام ، ويجمع بين أفضل العلامات التجارية للأزياء والجمال ونمط الحياة ، يمكنك الاستفادة من الخصومات الفريدة واكتشاف أحدث الاتجاهات وحتى الاستماع الى الموسيقى الحية والاستمتاع بالكوكتيلات اللذيذة ، حدث مثالي للذهاب للتسوق في مدريد ، ويقع في منطقة سالامانكا الحصرية بجوار الشوارع المعروفة مثل كالي دي سيرانو وكالي دي فيلاسكيز وباسيو دي لا كاستيلانا",
        en: "Can you imagine enjoying a night out in Madrid while all your favourite shops stay open? With Vogue Fashion's Night Out you can do exactly that. This charming event is held every September and brings together the best fashion, beauty and lifestyle brands. You can take advantage of unique discounts, discover the latest trends and even listen to live music and enjoy delicious cocktails — a perfect event for shopping in Madrid, set in the exclusive Salamanca district next to well-known streets such as Calle de Serrano, Calle de Velázquez and Paseo de la Castellana.",
      },
      {
        type: "H3",
        ar: "واحدة من أكثر الليالي براقة في مشهد الموضة في مدريد …",
        en: "One of the most glittering nights on the Madrid fashion scene …",
      },
      {
        type: "P",
        ar: "لليلة واحدة ، يفتح أكثر من 200 متجر في وسط مدريد أبوابهم لتقديم خصومات كبيرة ، والموسيقى الحية ، والتسوق ، والمنصات ، وجلسات التصوير ، ووجود عارضات ومصممين مشهورين ، وعناصر محدودة الاصدار ، يتم أيضا تقديم مجموعات الأزياء الجديدة لخريف وشتاء خلال ليلة فوغ فاشون",
        en: "For one night, more than 200 shops in central Madrid open their doors to offer big discounts, live music, shopping, catwalks, photo shoots, the presence of famous models and designers, and limited-edition items. The new autumn and winter fashion collections are also presented during Vogue Fashion's Night.",
      },
      { type: "H3", ar: "سوق نومادا ، فالنسيا", en: "Nomada Market, Valencia" },
      {
        type: "P",
        ar: "اذا سافرت الى مدينة فالنسيا في مايو ، فلا تفوت أحد أهم معارض التصميم المستقلة في اسبانيا ، يطلق عليه سوق نومادا ، ويقام في مدينة الفنون والعلوم الشهيرة ، في كل عام يجمع هذا الحدث أكثر من 100 مبدع صاعد من الفن والأزياء والتصميم الذين يضيء شغفهم في عملهم ، فرصة مثالية للاستمتاع بالتصميم وشراء بعض العناصر الفريدة وبأسعار معقولة ، على الرغم من وجود العديد من الطرق المختلفة لاكتشاف مدينة فالنسيا ، الا أنه لا توجد طرق أنيقة مثل هذه !",
        en: "If you travel to the city of Valencia in May, do not miss one of the most important independent design fairs in Spain: Nomada Market, held in the famous City of Arts and Sciences. Every year this event brings together more than 100 rising creatives from art, fashion and design whose passion shines through their work — a perfect opportunity to enjoy design and buy unique items at reasonable prices. Although there are many different ways to discover the city of Valencia, none of them is as stylish as this one!",
      },
      { type: "H3", ar: "لاس دالياس ، إيبيزا", en: "Las Dalias, Ibiza" },
      {
        type: "P",
        ar: "اذا كنت تبحث عن أحداث حيث يمكنك التسوق لشراء الملابس واكسسوارات الموضة ، فان لاس دالياس هي المكان المناسب لك ، يقع في ايبيزا ، وهو واحد من أشهر الأسواق في الجزيرة ، مع أكثر من 30 عاما من التاريخ ، تمتلئ حدائقها كل يوم سبت بأكثر من 200 منصة ، وتقدم مجموعة كبيرة من العناصر : الملابس المصنوعة يدويا والمجوهرات والحرف اليدوية والمنتجات الزخرفية وأكثر من ذلك بكثير ، يمكنك أيضا الاستمتاع بالمطاعم والموسيقى الحية في نفس الوقت",
        en: "If you are looking for events where you can shop for clothes and fashion accessories, Las Dalias is the place for you. Located in Ibiza, it is one of the most famous markets on the island, with more than 30 years of history. Its gardens fill every Saturday with more than 200 stalls offering a huge range of items: handmade clothing, jewellery, handicrafts, decorative products and much more. You can also enjoy the restaurants and live music at the same time.",
      },
      {
        type: "P",
        ar: "كل شيء قريب من هذه الجزيرة ، لذلك يمكنك بسهولة الذهاب للتسوق هنا بعد الاستمتاع بالسباحة في أحد الخلجان العديدة ، مثل سالادا أو كونتا أو فاديلا ، أنت على وشك الوقوع في حب ايبيزا أكثر !",
        en: "Everything is close on this island, so you can easily go shopping here after enjoying a swim in one of the many coves, such as Salada, Cunta or Vadella. You are about to fall in love with Ibiza even more!",
      },
      {
        type: "P",
        ar: "هذه ليست سوى بعض الأحداث التي تم تنظيمها لتستمتع بها عند التسوق في المدن الاسبانية ، اذا كنت من محبي الموضة وأحدث الاتجاهات ، فهذا هو النشاط المثالي لك ، لماذا لا تأتي الى اسبانيا وتجربها مباشرة ؟",
        en: "These are just some of the events organised for you to enjoy while shopping in Spanish cities. If you are a fan of fashion and the latest trends, this is the perfect activity for you. Why not come to Spain and try it first-hand?",
      },
    ],
  },
  {
    slug: "shopping-tips",
    title_ar: "نصائح تسوق ناجحة ومعلومات مفيدة",
    title_en: "Tips for successful shopping and useful information",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0950.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "نصائح ومعلومات مفيدة لتجربة تسوق استثنائية — هل ستسافر الى اسبانيا قريبا ؟",
        en: "Tips and useful information for an exceptional shopping experience — are you travelling to Spain soon?",
      },
      {
        type: "P",
        ar: "اذاً نقترح عليك تخصيص بعض من الوقت للتسوق أثناء وجودك في اسبانيا ، الموضة والحرف اليدوية والطعام والشراب ، والأشياء الزخرفية المتنوعة والجودة والتفرد ، مع ساعات العمل الطويلة ومناطق التسوق وكل ما تريد",
        en: "Then we suggest you set aside some time for shopping while you are in Spain: fashion, handicrafts, food and drink, and a variety of decorative objects, quality and uniqueness, with long opening hours, shopping districts and everything you want.",
      },
      { type: "H3", ar: "اليك أهم النصائح", en: "Here are the most important tips" },
      {
        type: "P",
        ar: "اذهب للتسوق لرؤية العلامات التجارية والبوتيكات الفاخرة ، وتمتع بروائح وألوان الأسواق التقليدية ، ولاحظ صدام القديم والجديد ، حيث تلتقي الحرف الشعبية بالتصميم المبتكر ، وتجول في الشوارع التاريخية بحثا عن الموسيقى والكتب والتحف ، واستمتع بالمتاجر ومراكز التسوق مع جميع الخدمات التي قد تحتاجها ، تجربة التسوق في اسبانيا واسعة النطاق مثل خيالك ، هناك شيء واحد فقط تحتاجه مسبقا : توفر مساحة اضافية صغيرة في حقيبتك !",
        en: "Go shopping to see the luxury brands and boutiques, enjoy the scents and colours of the traditional markets, and notice the clash of old and new where folk crafts meet innovative design. Wander the historic streets in search of music, books and antiques, and enjoy the stores and shopping centres with all the services you might need. The shopping experience in Spain is as wide-ranging as your imagination — there is only one thing you need in advance: a little extra space in your suitcase!",
      },
      { type: "H3", ar: "من مراكز المدن الى مراكز التسوق", en: "From city centres to shopping malls" },
      {
        type: "P",
        ar: "ما هي أفضل المناطق للتسوق في اسبانيا ؟ في معظم المدن والبلدات التي تزورها ، توجد أفضل الخيارات في المركز ، لكن أيضا تحتوي معظم المدن الكبيرة على مناطق تسوق أكثر تحديدا ، بعضها متخصص جدا : أحياء التسوق الفاخرة مثل منطقة سالامانكا في مدريد أو باسيج دي غراسيا في برشلونة ، كلها أماكن ذات تصميم وأزياء حديثة وبديلة ، مثل سوهو في ملقة ومالاسانيا في مدريد ، ومناطق أخرى مليئة بالمحلات التجارية التقليدية ، مثل بلازا ريدوندا في فالنسيا ، والحي القوطي في برشلونة",
        en: "What are the best areas for shopping in Spain? In most of the cities and towns you visit the best options are in the centre, but most large cities also have more specific shopping areas, some of them highly specialised: luxury shopping districts such as the Salamanca area of Madrid or Passeig de Gràcia in Barcelona; places of modern and alternative design and fashion such as Soho in Málaga and Malasaña in Madrid; and other areas full of traditional shops such as Plaza Redonda in Valencia and the Gothic Quarter in Barcelona.",
      },
      { type: "H3", ar: "خيار آخر …", en: "Another option …" },
      {
        type: "P",
        ar: "خاصة اذا كنت تبحث عن الأزياء والاكسسوارات والعطور ومستحضرات التجميل أو الالكترونيات ، هو زيارة مراكز التسوق الكبيرة والمتاجر التي ستجدها في العديد من المدن",
        en: "…especially if you are looking for fashion, accessories, perfumes and cosmetics or electronics, is to visit the large shopping centres and department stores you will find in many cities.",
      },
      { type: "H3", ar: "عادة ما يكون لمراكز التسوق أوقات عمل طويلة …", en: "Shopping centres usually have long opening hours …" },
      {
        type: "P",
        ar: "وجميع أنواع المتاجر (بما في ذلك سلاسل الأزياء الاسبانية والدولية الرائدة) ، بالاضافة الى خدمات مثل مواقف السيارات (التي قد تكون مجانية أو مدفوعة الثمن) ، ووسائل النقل العام الجيدة ، والمطاعم ، وحتى الأنشطة للأطفال في بعض الحالات ، لجعل يوم التسوق أكثر متعة للأطفال ، في مدن مثل مدريد أو برشلونة ، هناك أيضا مجمعات تسوق كبيرة مخصصة تماما لمتاجر الأزياء أو خطوط الديكور المعروفة",
        en: "…and all kinds of shops (including the leading Spanish and international fashion chains), plus services such as car parks (which may be free or paid), good public transport, restaurants and even activities for children in some cases to make the shopping day more fun for them. In cities such as Madrid or Barcelona there are also large shopping complexes devoted entirely to fashion stores or well-known home-decor lines.",
      },
      { type: "H3", ar: "أسواق الشوارع", en: "Street markets" },
      {
        type: "P",
        ar: "يمكنك أيضا العثور على أسواق الشوارع في وجهتك … جميع المدن الاسبانية تقريبا لديها واحد أو أكثر من أسواق الشوارع الأسبوعية أو الشهرية ، يتخصص البعض منها في العناصر المستعملة أو التحف أو الأزياء أو المنتجات العضوية ، والبعض الآخر يقدم مجموعة لا حصر لها من السلع اليومية والملابس والاكسسوارات والفواكه والخضروات وما الى ذلك ، لكنهم جميعا مشغولون وحيويون ، وغالبا ما يكونون مع جو احتفالي ، وأحيانا المتجولين والفنانين",
        en: "You can also find street markets at your destination. Almost all Spanish cities have one or more weekly or monthly street markets. Some specialise in second-hand items, antiques, fashion or organic produce, while others offer an endless range of everyday goods, clothing, accessories, fruit and vegetables and so on — but they are all busy and lively, often with a festive atmosphere and sometimes with street performers and artists.",
      },
      {
        type: "P",
        ar: "لكن أبرزها هم : راسترو الشهير – في مدريد ، الس انكانتس – في برشلونة ، لا ألكايسيريا – في غرناطة ، لاس دالياس – في ايبيزا ، سوق الخميس – في أشبيلية ، وراسترو دي ميستالا – في فالنسيا",
        en: "The most notable are: the famous El Rastro in Madrid, Els Encants in Barcelona, La Alcaicería in Granada, Las Dalias in Ibiza, the Thursday market in Seville, and Rastro de Mestalla in Valencia.",
      },
      { type: "H3", ar: "الموضة والطعام والحرف اليدوية", en: "Fashion, food and handicrafts" },
      {
        type: "P",
        ar: "من أين الى ماذا .. ما الذي نوصيك بشرائه في رحلتك الى اسبانيا ؟ الموضة والحرف اليدوية والأطعمة الذواقة هي دائما من بين أفضل الاختيارات ، على الرغم من أن الاختيار يعتمد على أذواقك ، وبالطبع على الأماكن التي تزورها : هناك الكثير من التنوع الذي نقترح التحقق من التخصصات المحلية في وجهتك قبل التخطيط للتسوق",
        en: "From where to what — what do we recommend you buy on your trip to Spain? Fashion, handicrafts and gourmet foods are always among the best choices, although the choice depends on your tastes and of course on the places you visit: there is so much variety that we suggest checking the local specialities at your destination before planning your shopping.",
      },
      { type: "H3", ar: "الموضة والاكسسوارات", en: "Fashion and accessories" },
      {
        type: "P",
        ar: "لن تندم على شراء الأزياء والاكسسوارات كالتي كتب عليها صنع في اسبانيا ، من الخطوط الحصرية للمصممين الاسبان ذوي المكانة الدولية الى صادرات اسبانيا الى نصف الكوكب ، والتي ستبدو أنيقة في المنزل",
        en: "You will not regret buying fashion and accessories such as those labelled Made in Spain — from the exclusive lines of Spanish designers of international standing to Spain's exports to half the planet, which will look stylish back home.",
      },
      { type: "H3", ar: "واذا كنت تتخيل نفسك صياد رائع …", en: "And if you imagine yourself a great hunter …" },
      {
        type: "P",
        ar: "فتجول في المناطق العصرية في المدن الكبيرة (مالاسانيا في مدريد ، رافال أو غراسيا في برشلونة ، روسافا في فالنسيا ، سوهو في مالقا) ، حيث يكون للمصممين المحليين متاجر صغيرة خاصة بهم ويمكنك العثور على عناصر فريدة ومبتكرة",
        en: "…then wander the trendy areas of the big cities (Malasaña in Madrid, El Raval or Gràcia in Barcelona, Russafa in Valencia, Soho in Málaga), where local designers have their own small shops and you can find unique and innovative items.",
      },
      { type: "H3", ar: "واذا كنت تبحث عن تذكار أكثر تقليدي …", en: "And if you are looking for a more traditional souvenir …" },
      {
        type: "P",
        ar: "فلا تنس أن كل منطقة لديها زيها المحلي التقليدي ، من فساتين الفلامنكو الشهيرة عالميا في الأندلس ، مع الكشكشة والألوان الزاهية ، الى القطن الأبيض على طراز Ad Lib في ايبيزا ، أو الدمشق الحريري في فالنسيا ، أو الباسك txapela (beret) ، أو وشاح الخصر التقليدي لسان فيرمين",
        en: "…do not forget that each region has its own traditional local dress, from the world-famous flamenco dresses of Andalusia with their frills and bright colours, to the Ad Lib-style white cotton of Ibiza, the silk damask of Valencia, the Basque txapela (beret), or the traditional waist sash of San Fermín.",
      },
      { type: "H3", ar: "في التداخل بين الموضة والحرف اليدوية …", en: "At the overlap between fashion and handicrafts …" },
      {
        type: "P",
        ar: "تنتج العديد من المناطق الاسبانية سلعا جلدية استثنائية : حقائب الظهر والحقائب والأحزمة والأحذية والعناصر الجلدية الصغيرة تشكل خيارا رائعا في معظم أنحاء اسبانيا ، بما في ذلك الأندلس وكاستيلا لا مانشا ، أو ربما شيء لتزيين منزلك ؟ الفخار من تالافيرا دي لا رينا (في توليدو ، كاستيلا لا مانشا ، وعنصر التراث الثقافي غير المادي لليونسكو)، أو من سارجاديلوس (لوغو ، غاليسيا) ، مانيس (فالنسيا) أو أوبيدا (خاين ، الأندلس) ، أو الفولاذ الدمشقي من توليدو (كاستيلا لا مانشا) هي بعض من تشمل الحرف اليدوية الأخرى للشراء في اسبانيا اذا كنت تريد عنصرا محليا تقليديا ذا شخصية سلال الخوص والقصب والمصابيح والعناصر الزخرفية في منطقة فالنسيا ، واسبارتو المنسوجة في أي شيء من الحقائب الى السجاد في كاستيلا لا مانشا ، وقطع خشب البقس مثل الأوعية أو السدادات في نافارا",
        en: "Many Spanish regions produce exceptional leather goods: backpacks, bags, belts, shoes and small leather items are a great choice in most of Spain, including Andalusia and Castile-La Mancha. Or perhaps something to decorate your home? Pottery from Talavera de la Reina (in Toledo, Castile-La Mancha, and a UNESCO intangible cultural heritage element), or from Sargadelos (Lugo, Galicia), Manises (Valencia) or Úbeda (Jaén, Andalusia), or Damascus steel from Toledo (Castile-La Mancha) are some of them. Other handicrafts to buy in Spain if you want a traditional local item with character include wicker and cane baskets, lamps and decorative items in the Valencia region, esparto woven into anything from bags to rugs in Castile-La Mancha, and boxwood pieces such as bowls or stoppers in Navarre.",
      },
      { type: "H3", ar: "الطعام والشراب", en: "Food and drink" },
      {
        type: "P",
        ar: "اذا كنت تبحث عن هدايا تذكارية عالية الذوق … فأنت محظوظ ، المطبخ الاسباني هو الأساس الرئيسي لنظام البحر الأبيض المتوسط الغذائي ، وهذه الأطعمة والنبيذ هي خيار ممتاز للشراء لنفسك أو كهدايا",
        en: "If you are looking for souvenirs in the best of taste, you are lucky: Spanish cuisine is the main foundation of the Mediterranean diet, and these foods and wines are an excellent choice to buy for yourself or as gifts.",
      },
      { type: "H3", ar: "كل منطقة لديها شيء فريد لاغرائك …", en: "Every region has something unique to tempt you …" },
      {
        type: "P",
        ar: "لذا خذ القليل من النكهة الاسبانية معك الى المنزل ، بدءا من لحم الخنزير الأيبيري ، أو الأجبان المحلية اللذيذة ، أو زيت الزيتون الذهب السائل للبحر الأبيض المتوسط ، والقائمة تطول ، كالحلويات (كعكة تارتا دي سانتياغو في غاليسيا ، والفواكه المسكرة في أراغون ، والعسل في كاستيلا لا مانشا) وحتى بعض الأطعمة المعلبة الذواقة",
        en: "…so take a little Spanish flavour home with you, starting with Iberian ham, the delicious local cheeses, or olive oil — the liquid gold of the Mediterranean — and the list goes on, such as sweets (tarta de Santiago in Galicia, candied fruit in Aragon, honey in Castile-La Mancha) and even some gourmet tinned foods.",
      },
      { type: "H3", ar: "وعلى الرغم من عدم وجود قيود …", en: "And although there are no restrictions …" },
      {
        type: "P",
        ar: "على تناول الأطعمة بين دول الاتحاد الأوروبي ، يجب عليك التحقق من اللوائح اذا كنت ذاهبا الى مكان ما خارج الاتحاد الأوروبي",
        en: "…on taking food between EU countries, you should check the regulations if you are going somewhere outside the European Union.",
      },
      { type: "H3", ar: "التسوق مع الخبرات", en: "Shopping with experiences" },
      {
        type: "P",
        ar: "اذا كنت ترغب في اضافة شيء اضافي الى تجربة التسوق الخاصة بك ، فيمكنك دمجها مع العديد من الأنشطة الأخرى المتاحة في اسبانيا ، ربما ترغب في استخدام خدمات المتسوق الشخصي ؟ خاصة في المدن الكبيرة ، يمكن لهؤلاء المهنيين تقديم المشورة لك وارشادك الى أفضل المتاجر للأزياء والديكور ، أو المحلات الأكثر تميزا",
        en: "If you would like to add something extra to your shopping experience, you can combine it with the many other activities available in Spain. Perhaps you would like to use the services of a personal shopper? Especially in the big cities, these professionals can advise you and guide you to the best shops for fashion and décor, or the most distinctive boutiques.",
      },
      {
        type: "H3",
        ar: "قبل أن تشتري نبيذا أو جبنا أو زيتا خاصا ، هل ترغب في تجربتها ؟",
        en: "Before buying a special wine, cheese or oil, would you like to taste it?",
      },
      {
        type: "P",
        ar: "في اسبانيا ، يمكنك تذوق هذه المنتجات وغيرها ، حيث يمكنك التعرف عليها ، وتقدير خصائصها وتحديد الخصائص التي تريد شراؤها ، خيار رائع آخر هو تذكار التراث الفني أو الثقافي أو التاريخي لاسبانيا من متاجر المتاحف أو المعارض ، أو السيراميك أو العناصر الجلدية مباشرة من ورشة الحرف اليدوية ، حتى تتمكن من الاستمتاع بتجربة رؤيتها مصنوعة ، تحتاج فقط الى العثور على ما يعجبك أكثر في كل وجهة ، فالاحتمالات لا حصر لها",
        en: "In Spain you can taste these products and others, getting to know them, appreciating their qualities and deciding which ones you want to buy. Another great option is a souvenir of Spain's artistic, cultural or historical heritage from museum or gallery shops, or ceramics or leather items straight from the craft workshop, so you can enjoy the experience of seeing them made. You only need to find what you like most at each destination — the possibilities are endless.",
      },
      { type: "H3", ar: "نصائح وتوصيات ومعلومات مفيدة", en: "Tips, recommendations and useful information" },
      {
        type: "P",
        ar: "قبل أن تبدأ التسوق في اسبانيا ، اليك بعض النصائح الأساسية :",
        en: "Before you start shopping in Spain, here are some essential tips:",
      },
      {
        type: "LIST",
        ar: [
          "أحد أكثر الأشياء اثارة للدهشة في التسوق في اسبانيا هو طول ساعات العمل ، حيث تفتح معظم الأماكن من الاثنين الى السبت ، من الساعة 09:30 الى الساعة 13:30 ثم من الساعة 16:30 الى الساعة 20:00 ، ولكن في معظم الوجهات السياحية تفتح المتاجر بعد ذلك بكثير ، وتسمح لهم العديد من المدن بتعيين ساعاتهم الخاصة",
          "في بعض المنتجعات السياحية ، وخاصة على الساحل في موسم الذروة ، ليس من غير المعتاد العثور على متاجر مفتوحة حتى المساء ، حتى بعد الساعة 22:00",
          "مراكز التسوق الرئيسية والمتاجر الكبرى مفتوحة طوال اليوم من الساعة 10:00 الى الساعة 21:00 أو الساعة 22:00 ، والعديد منها مفتوح أيام الأحد أيضا",
          "في اسبانيا ، الأسعار محددة ولا تتوقع المساومة كثيرا",
          "اذا كنت تعيش خارج الاتحاد الأوروبي ، فيمكنك المطالبة بالضريبة على مشترياتك",
        ],
        en: [
          "One of the most surprising things about shopping in Spain is the long opening hours: most places open Monday to Saturday from 09:30 to 13:30 and then from 16:30 to 20:00, but in most tourist destinations shops open much later than that, and many cities allow them to set their own hours.",
          "In some tourist resorts, especially on the coast in high season, it is not unusual to find shops open into the evening, even after 22:00.",
          "The main shopping centres and department stores are open all day from 10:00 to 21:00 or 22:00, and many of them open on Sundays too.",
          "In Spain prices are fixed and you should not expect much bargaining.",
          "If you live outside the European Union, you can claim back the tax on your purchases.",
        ],
      },
    ],
  },
  {
    slug: "shopping-historic",
    title_ar: "أصالة التسوق مع تاريخ زاخر",
    title_en: "Authentic shopping with a rich history",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0956.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "الأماكن الأكثر أصالة للتسوق في اسبانيا — المحلات التجارية التي لها مائة عام وأكثر — تاريخ من أجل اعادتك الى الماضي",
        en: "The most authentic places to shop in Spain — shops that are a hundred years old and more — a history to take you back in time",
      },
      {
        type: "P",
        ar: "تحرص اسبانيا جيدا للحفاظ على المتاجر التي يزيد عمرها عن مائة عام ، تم تمرير معظمها عبر الأجيال وهي اليوم جزء من التراث التاريخي لكل مدينة ، تعال واكتشف متاجر فريدة من نوعها حيث يمكنك شراء جميع أنواع الأشياء المثيرة للاهتمام والملتوي وأخذ هدية تذكارية مختلفة حقا الى المنزل",
        en: "Spain takes great care to preserve shops that are more than a hundred years old. Most of them have been passed down through the generations and are today part of the historical heritage of each city. Come and discover one-of-a-kind shops where you can buy all sorts of interesting and quirky things and take a truly different souvenir home.",
      },
      { type: "H3", ar: "مدريد", en: "Madrid" },
      {
        type: "P",
        ar: "العاصمة محفوظة بما يكفي … لأن لديها قائمة طويلة من المتاجر التي يبلغ عمرها مائة عام ، اذا كنت تبحث عن بعض الأحذية التي ستدوم مدى الحياة ، فستجد في Calzados Lobo كل مقاس وأسلوب كلاسيكي ، هل تريد قراءة كتاب عتيق أو مستعمل ؟ ثم توجه الى ليبريا سان جينيس ، أو الأكشاك في كويستا مويانو ، اذا كنت ترغب في تجربة بعض المعجنات بلمسة مميزة ، فان Lhardy هو المكان المناسب للذهاب اليه",
        en: "The capital is well enough preserved, because it has a long list of hundred-year-old shops. If you are looking for shoes that will last a lifetime, at Calzados Lobo you will find every size and classic style. Do you want to read an antique or second-hand book? Then head to Librería San Ginés, or the stalls on Cuesta de Moyano. If you would like to try some pastries with a distinctive touch, Lhardy is the place to go.",
      },
      { type: "H3", ar: "أو ربما تأخذ بعض …", en: "Or perhaps take some …" },
      {
        type: "P",
        ar: "التورونيس الحرفي (النوجا ، التي تستمتع بها في الغالب في عيد الميلاد) ، أو ربما تبحث عن قطعة لمرة واحدة من الفخار المصنوع يدويا ، اذا كان الأمر كذلك ، فتوجه الى أنتيغوا كازا تالافيرا ، في وسط بلازا ديل سول مباشرة ، يمكنك شراء مروحة أو بعض كاستانيتس ، أو اصلاح مظلتك في كاسا دي دييغو",
        en: "…artisan turrón (nougat, mostly enjoyed at Christmas), or perhaps you are looking for a one-off piece of handmade pottery. If so, head to Antigua Casa Talavera. Right in the middle of Plaza del Sol you can buy a fan or some castanets, or repair your umbrella at Casa de Diego.",
      },
      { type: "IMG", src: IMG("img_0956.jpg"), cap_ar: "التسوق في اسبانيا", cap_en: "Shopping in Spain" },
      { type: "H3", ar: "أشبيلية", en: "Seville" },
      {
        type: "P",
        ar: "كالي سيربس … وهو شارع يقع في قلب المدينة ، حيث ستجد معظم متاجر أشبيلية التي يبلغ عمرها مائة عام ، ما زلت في الوقت المناسب لزيارة متاجر مثل El Cronómetro ، صانع الساعات من أعلى مستويات الجودة ، أو بابيليريا فيرير ، التي يعتقد أنها واحدة من أقدم متاجر القرطاسية في اسبانيا ، التي تأسست في عام 1856م",
        en: "Calle Sierpes is a street in the heart of the city where you will find most of Seville's hundred-year-old shops. You are still in time to visit stores such as El Cronómetro, a watchmaker of the very highest quality, or Papelería Ferrer, believed to be one of the oldest stationery shops in Spain, founded in 1856.",
      },
      { type: "IMG", src: IMG("img_0957.jpg"), cap_ar: "التسوق في اسبانيا", cap_en: "Shopping in Spain" },
      { type: "H3", ar: "برشلونة", en: "Barcelona" },
      {
        type: "P",
        ar: "يوجد في برشلونة العديد … من المتاجر التي لا تزال تفتح أبوابها منذ قرن من الزمان منذ افتتاحها لأول مرة ، في البعض مثل كازا بيتهوفن ، ستجد بعض الدرجات الموسيقية الرائعة للدراسة والاستمتاع بها ، ستضيف سيريريا سوبيرا الضوء الى حياتك ومنزلك مع كل نوع من الشموع التي يمكن تخيلها ، واذا كنت تتطلع الى صنع ذكريات خاصة ، فيمكنك دائما شراء بعض اللوز المحمص من كازا جيسبرت كثيرا أثناء التجول في وسط المدينة",
        en: "Barcelona has many shops that are still opening their doors a century after they first opened. In some, such as Casa Beethoven, you will find wonderful sheet music to study and enjoy. Cereria Subirà will add light to your life and your home with every kind of candle imaginable, and if you are hoping to make special memories you can always buy some roasted almonds from Casa Gispert while strolling through the city centre.",
      },
      { type: "H3", ar: "في أجزاء أخرى من المدينة …", en: "In other parts of the city …" },
      {
        type: "P",
        ar: "ستجد tiendas de ultramarinos ملتوية ، وهو نوع من محلات البقالة التقليدية التي تبيع جميع أنواع المنتجات الغذائية التي ستحتفظ بها ، مثل El Riojano (A Coruña) أو La Confianza (Huesca) أو El Niño Llorón (Valencia)",
        en: "…you will find quirky tiendas de ultramarinos, a kind of traditional grocery shop selling all sorts of food products that keep, such as El Riojano (A Coruña), La Confianza (Huesca) or El Niño Llorón (Valencia).",
      },
      { type: "IMG", src: IMG("img_0958.jpg"), cap_ar: "التسوق في اسبانيا", cap_en: "Shopping in Spain" },
    ],
  },
  {
    slug: "shopping-cities",
    title_ar: "أفضل المدن الاسبانية للتسوق",
    title_en: "The best Spanish cities for shopping",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0951.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "أفضل المدن الاسبانية للتسوق — اليك بعض من أفضل المدن للتسوق في اسبانيا",
        en: "The best Spanish cities for shopping — here are some of the best cities for shopping in Spain",
      },
      {
        type: "P",
        ar: "من المتاجر الصغيرة الساحرة الى مراكز التسوق الكبيرة ، من الفنون والحرف اليدوية الى العلامات التجارية الكبرى ، فاذا كنت تستمتع بالتسوق ، فان اسبانيا هي المكان المناسب لك ، والأكثر من ذلك هو أن مناطق التسوق عادة ما تكون قريبة من مواقع أخرى مثيرة للاهتمام ، هذا يعني أنه يمكنك التسوق ورؤية المواقع في نفس الوقت",
        en: "From charming small shops to large shopping centres, from arts and crafts to the big brands — if you enjoy shopping, Spain is the place for you. What is more, the shopping areas are usually close to other interesting sights, which means you can shop and see the sights at the same time.",
      },
      { type: "H3", ar: "برشلونة", en: "Barcelona" },
      {
        type: "P",
        ar: "اذا كنت من محبي العلامات التجارية الكبرى ، فلن ترغب في تفويت باسيج دي غراسيا ، انه شارع مليء بالمباني الحداثية وجميع العلامات التجارية الأكثر فخامة وشهرة في العالم ، ولكن اذا كنت تبحث عن شيء بديل أكثر قليلا ، فيجب عليك التحقق من كارير تالرز الشهيرة ، التي تمتلئ بالمتاجر الصغيرة الساحرة التي تبيع المنتجات الحرفية والموسيقى والملابس القديمة",
        en: "If you are a fan of the big brands, you will not want to miss Passeig de Gràcia, a street full of Modernista buildings and all the most luxurious and famous brands in the world. But if you are looking for something a little more alternative, you should check out the famous Carrer Tallers, which is full of charming small shops selling artisan products, music and vintage clothing.",
      },
      { type: "H3", ar: "ماربيا", en: "Marbella" },
      {
        type: "P",
        ar: "تشتهر بويرتو بانوس ، في قلب كوستا ديل سول مباشرة ، بسحرها ، انها موطن لأكثر من 100 علامة تجارية فاخرة مع أحدث المجموعات من المصممين ذوي الشهرة العالمية ، تقع المتاجر أيضا بجوار الميناء ، حيث يمكنك رؤية عدد من اليخوت والسفن الضخمة التي ستأخذ أنفاسك",
        en: "Puerto Banús, right in the heart of the Costa del Sol, is famous for its glamour. It is home to more than 100 luxury brands with the latest collections from world-renowned designers. The shops are also next to the marina, where you can see a number of yachts and huge ships that will take your breath away.",
      },
      { type: "H3", ar: "مدريد", en: "Madrid" },
      {
        type: "P",
        ar: "اذا كنت تبحث عن منتجات فاخرة ذات طابع ، فان مدريد هي المدينة المناسب لك ، ففي حي سالامانكا ، ستجد العديد من العلامات التجارية المرموقة وبعض الأزياء الراقية الأصيلة المذهلة ، لكن بحثك سيقودك أيضا الى سوق السلع المستعملة في الهواء الطلق راسترو مدريد ، يقع في قلب منطقة لا لاتينا ، يمكنك العثور على التحف والأزياء وبعض العناصر المدهشة حقا هنا",
        en: "If you are looking for luxury products with character, Madrid is the city for you. In the Salamanca district you will find many prestigious brands and some stunning authentic haute couture. But your search will also lead you to the open-air second-hand market El Rastro de Madrid, in the heart of La Latina, where you can find antiques, fashion and some really surprising items.",
      },
      { type: "H3", ar: "غرناطة", en: "Granada" },
      {
        type: "P",
        ar: "يمكنك العثور على بعض الأسواق السحرية في غرناطة ، مثل سوق ألكايسيريا ، انه بازار ضخم ، حيث يمكنك أن تضيع بين الحرير والسيراميك ومصابيح غرناطة ، بعد استكشاف هذه الأسواق الملونة والشوارع الضيقة ، تذكر الصعود الى ألبايسين قبل الانتهاء من جولتك في المدينة",
        en: "You can find some magical markets in Granada, such as the Alcaicería market — a huge bazaar where you can lose yourself among the silk, ceramics and Granada lamps. After exploring these colourful markets and narrow streets, remember to climb up to the Albaicín before finishing your tour of the city.",
      },
      {
        type: "P",
        ar: "هذه ليست سوى بعض المدن التي يمكنك فيها الحصول على اصلاح التسوق الخاص بك ، ولكن هناك الكثير لاكتشافه ، تذكر التحقق من أوقات العمل قبل زيارة أي منطقة تسوق ، لأنها عادة ما تكون مختلفة في اسبانيا مقارنة ببقية أوروبا ، في بعض الأماكن ، يمكنك حتى الاستمرار في التسوق جيدا في الليل",
        en: "These are just some of the cities where you can get your shopping fix, but there is much more to discover. Remember to check the opening hours before visiting any shopping area, because they are usually different in Spain compared with the rest of Europe — in some places you can even keep shopping well into the night.",
      },
      { type: "H3", ar: "مالقا", en: "Málaga" },
      {
        type: "P",
        ar: "يعد مركز مالقا مركزا رائعا للحياة الاجتماعية في المدينة ، فيه مجموعة واسعة من المتاجر والشرفات ، والجاذبية الثقافية للمعالم التاريخية التي ستجدها عند زيارة المنطقة ، وأجوائها النابضة بالحياة ستجعل يوم التسوق الخاص بك تجربة لا تقدر بثمن ، فيا ترى كيف ترغب في قضاء يوم في التسوق في عاصمة كوستا ديل سول ؟",
        en: "The centre of Málaga is a wonderful hub for the city's social life, with a wide range of shops and terraces, the cultural appeal of the historic monuments you will find when visiting the area, and a vibrant atmosphere that will make your shopping day a priceless experience. So how would you like to spend a day shopping in the capital of the Costa del Sol?",
      },
    ],
  },
  {
    slug: "shopping-general",
    title_ar: "التسوق في اسبانيا بشكل عام",
    title_en: "Shopping in Spain in general",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0949-1.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "وجهات مثالية وعلامات تجارية لدى التسوق في اسبانيا — ومواسم تخفيضات ، واستعادة رسوم",
        en: "Perfect destinations and brands when shopping in Spain — plus sales seasons and tax refunds",
      },
      {
        type: "P",
        ar: "في اسبانيا ستستمتع كما لم يحدث من قبل بالتسوق ، وذلك بفضل مجموعة واسعة من العروض : فهناك الكثير من العلامات التجارية الرائدة والمصممين الاسبان والعالميين ، والأزياء البديلة ومراكز التسوق الكبيرة ، ناهيك عن الأماكن الترفيهية لجميع أفراد الأسرة وتخفيضات وأسواق متجددة باستمرار ، بالاضافة الى المحلات الحرفية الصغيرة التقليدية ، واذا أضفنا الى ذلك توقيت العمل المستمر للمحلات ، وبالتالي فان التسوق الجيد مضمون ، في اسبانيا سوف تجد بضائع ذات جودة عالية في الأزياء والمجوهرات والأحذية والهدايا",
        en: "In Spain you will enjoy shopping as never before, thanks to a huge range on offer: plenty of leading brands, Spanish and international designers, alternative fashion and large shopping centres, not to mention entertainment venues for the whole family, sales and constantly renewed markets, plus small traditional craft shops. And if we add to that the continuous opening hours of the shops, good shopping is guaranteed. In Spain you will find high-quality goods in fashion, jewellery, footwear and gifts.",
      },
      { type: "H3", ar: "علامات تجارية كبيرة", en: "Big brands" },
      {
        type: "P",
        ar: "من بين المصممين الاسبانيين أصحاب الصيحات المميزة نجد : Amaya Arzuaga ، وCusto Dalmau ، وAdolfo Domínguez ، وJesús del Pozo ، وRoberto Verino ، وPurificación García ، وÁgatha Ruiz de la Prada ، وManolo Blahnik ، وAna Locking ، وÁngel Schlesser ، وDavid Delfín ، وDevota & Lomba ، وDuyos ، وFrancis Montesinos ، وHannibal Laguna ، مع ذلك استمتع باقامتك في اسبانيا للتسوق من بعض متاجرها",
        en: "Among the Spanish designers with distinctive styles we find: Amaya Arzuaga, Custo Dalmau, Adolfo Domínguez, Jesús del Pozo, Roberto Verino, Purificación García, Ágatha Ruiz de la Prada, Manolo Blahnik, Ana Locking, Ángel Schlesser, David Delfín, Devota & Lomba, Duyos, Francis Montesinos and Hannibal Laguna. So enjoy your stay in Spain by shopping in some of their stores.",
      },
      {
        type: "P",
        ar: "الملحقات الأسبانية مشهورة أيضا بجودتها ، مع الشركات والعلامات التجارية مثل : Camper ، وLoewe ، وMascaró",
        en: "Spanish accessories are also renowned for their quality, with companies and brands such as Camper, Loewe and Mascaró.",
      },
      { type: "H3", ar: "مدريد وبرشلونة .. وجهات مثالية للتسوق", en: "Madrid and Barcelona — perfect shopping destinations" },
      {
        type: "P",
        ar: "مدريد : تتعدد أنماط الملابس حسب المنطقة : سوف تجد في Milla de Oro (منطقة حي سالامانكا وكالي سيرانو على وجه الخصوص) ، وهي أرقى المحلات والماركات وفي المنطقة المنحصرة بين Fuencarral وHortaleza ، وسوف تجد المتاجر البديلة أيضا ، أما في شارع Gran Vía وشارع Preciados ، ستجد الواجهات الضخمة للمحلات والسوق الزقاقي الشهير El Rastro الذي يقام أيام الأحد ، منذ أكثر من 400 سنة",
        en: "Madrid: clothing styles vary by area. In the Milla de Oro (the Salamanca district and Calle Serrano in particular) you will find the finest shops and brands, and in the area between Fuencarral and Hortaleza you will find the alternative stores too. On Gran Vía and Calle Preciados you will find the huge shop fronts and the famous street market El Rastro, held on Sundays for more than 400 years.",
      },
      {
        type: "P",
        ar: "برشلونة : واحدة من المدن الأوروبية الكبرى للابتكار والتصميم ، وهذا واضح من خلال الشوارع والمحلات التجارية ، ومن المعروف أن المركز التجاري الرئيسي لبرشلونة هو بمتابة شوبينج لاين : خمسة كيلومترات من الشوارع المخصصة للراجلين وهو أكبر مجمع تجاري في أوروبا الواقع في الهواء الطلق ، لذلك اغتنم هذه الفرصة لمعرفة المحلات التجارية الأنيقة في Paseo de Gràcia ، وهي المحلات التجارية العريقة في الحي القوطي أو أكثر التصاميم استقلالية في Born ، أما عن بقية الوجهات السياحية الاسبانية فتجد أيضا المحلات التجارية بجميع أنواعها وغالبا المنتجات المصنوعة من قبل الحرفيين المحليين ، في الأندلس على سبيل المثال ، يجب أن تسأل عن السلع الجلدية",
        en: "Barcelona: one of Europe's great cities for innovation and design, which is clear from its streets and shops. Barcelona's main commercial centre is known as a shopping line: five kilometres of pedestrian streets, the largest open-air shopping complex in Europe. So take this chance to get to know the elegant shops on Passeig de Gràcia, the long-established shops of the Gothic Quarter or the most independent designs in El Born. As for the rest of Spain's tourist destinations, you will also find shops of every kind and often products made by local artisans — in Andalusia, for example, you should ask about leather goods.",
      },
      { type: "H3", ar: "مواسم التخفيضات والخصومات", en: "Sales and discount seasons" },
      {
        type: "P",
        ar: "هناك مواسم يوصى بها بشكل خاص للتسوق في اسبانيا ، من بين هذه المواسم أعياد الميلاد ، عندما تحتفي المدن بالأسواق الجميلة الخاصة بأعياد الميلاد التي تضم العديد من المنتجات للزينة ولتقديمها كهدايا ، وهناك أيضا أوقات أخرى قد تهمك ، تلك التي تتوافق مع فترات التخفيضات",
        en: "There are seasons that are especially recommended for shopping in Spain. Among them is Christmas, when the cities celebrate with beautiful Christmas markets featuring many products for decoration and for giving as gifts. There are also other times that may interest you: those that coincide with the sales periods.",
      },
      { type: "H3", ar: "الشتاء", en: "Winter" },
      {
        type: "P",
        ar: "عادة ما تبدأ فترة التخفيضات الخاصة بفصل الشتاء من 1 يناير وتمتد الى غاية 28 فبراير ، ومن بين التواريخ التي يجب أخذها بين الاعتبار أيضا نجد الجمعة الأسود BlackFriday ، الذي يحتفل به في الجمعة الرابع من شهر نوفمبر ، وعادة ما تدوم الاحتفالات طيلة نهاية الأسبوع ، خلال هذه الأيام ، يعرض العديد من المتاجر والمحلات التجارية عروض وتخفيضات مهمة",
        en: "The winter sales period usually starts on 1 January and runs until 28 February. Among the other dates to bear in mind is Black Friday, celebrated on the fourth Friday of November, with the celebrations usually lasting all weekend. During these days many stores and shops offer significant deals and discounts.",
      },
      { type: "H3", ar: "الصيف", en: "Summer" },
      {
        type: "P",
        ar: "بينما تبدأ التخفيضات الصيفية من 1 يوليو وتمتد الى غاية 31 أغسطس ، بالاضافة الى ذلك ، عادة ما تكون هناك تخفيضات أيضا في منتصف الموسم على مدار السنة",
        en: "The summer sales begin on 1 July and run until 31 August. In addition, there are usually mid-season sales throughout the year as well.",
      },
      { type: "H3", ar: "استعادة الرسوم", en: "Tax refunds" },
      {
        type: "P",
        ar: "بصفتك مقيما خارج حدود الاتحاد الأوروبي بامكانك طلب استرداد ضريبة القيمة المضافة الخاصة بمشترياتك ، ما عليك الا طلب الاستمارة الخاصة بالاعفاء الضريبي من المتاجر عند قيامك بالتسوق ، بعد ذلك سيتوجب عليك ختمها في مكتب الجمارك في غضون فترة لا تتجاوز 3 أشهر اعتبارا من تاريخ الشراء",
        en: "As a resident outside the borders of the European Union you can request a refund of the VAT on your purchases. You only need to ask the shops for the tax-exemption form when you shop; after that you will have to get it stamped at the customs office within a period of no more than 3 months from the date of purchase.",
      },
      {
        type: "P",
        ar: "يعتبر نظام DIVA الالكتروني هو الاجراء المعتمد للتأكد من صحة الفواتير في Customs ، يساعد هذا النظام على تسريع عملية التأكد من صحة المستندات واسترداد الضريبة ، وبفضل هذه الطريقة ما عليك سوى طلب استمارة ديفا (DIVA) من المتاجر التي تتوفر على هذه الخدمة ، ثم القيام بالمصادقة عليها مباشرة في الآلات الأوتوماتيكية المتواجدة في العديد من المطارات وفي الموانئ الرئيسية والجمارك البرية في اسبانيا",
        en: "The electronic DIVA system is the approved procedure for validating invoices at Customs. This system helps speed up the process of validating documents and refunding the tax. Thanks to this method you only need to ask for the DIVA form from shops that offer this service, then validate it directly at the automatic machines located in many airports and at the main ports and land customs posts in Spain.",
      },
      {
        type: "P",
        ar: "لديك أيضا امكانية الحصول على استرداد ضريبة القيمة المضافة مقدما ، قبل الختم في مكتب الجمارك في اليوم الأخير ، عبر Global Blue ، تمتلك هذه الشركة مكاتب ومراكز معلومات ، حيث يمكنك اجراء ذلك في مراكز المدن المختلفة",
        en: "You also have the option of receiving the VAT refund in advance, before the stamp at the customs office on the last day, through Global Blue. This company has offices and information centres where you can do this in various city centres.",
      },
    ],
  },
  {
    slug: "shopping-malaga",
    title_ar: "التسوق في مالقا",
    title_en: "Shopping in Málaga",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0949.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "يوم من التسوق في شوارع مالقا وفي مراكز التسوق الخاصة بها — يالله نستمتع بأسواق مالقا الجميلة !",
        en: "A day of shopping on the streets of Málaga and in its shopping centres — let's enjoy the beautiful markets of Málaga!",
      },
      {
        type: "P",
        ar: "يعد مركز مالقا مركزا رائعا للحياة الاجتماعية في المدينة ، فيه مجموعة واسعة من المتاجر والشرفات ، والجاذبية الثقافية للمعالم التاريخية التي ستجدها عند زيارة المنطقة ، وأجوائها النابضة بالحياة ستجعل يوم التسوق الخاص بك تجربة لا تقدر بثمن ، فيا ترى كيف ترغب في قضاء يوم في التسوق في عاصمة كوستا ديل سول ؟",
        en: "The centre of Málaga is a wonderful hub for the city's social life, with a wide range of shops and terraces, the cultural appeal of the historic monuments you will find when visiting the area, and a vibrant atmosphere that will make your shopping day a priceless experience. So how would you like to spend a day shopping in the capital of the Costa del Sol?",
      },
      { type: "H3", ar: "شوارع التسوق الأكثر شهرة في البلدة القديمة", en: "The most famous shopping streets in the old town" },
      {
        type: "P",
        ar: "لنبدأ في البلدة القديمة في مالقا ، انها موطن لأحد أكثر الشوارع تميزا وشهرة للتسوق في اسبانيا : كالي لاريوس ، هنا يمكنك التجول من متجر الى متجر ، وتصفح ماركات الأزياء الشهيرة والعطور ومستحضرات التجميل والاكسسوارات ، يعتبر أحد أغلى الشوارع في اسبانيا ، ولكن يمكنك أيضا العثور على المتاجر التقليدية الصغيرة ، والتي تتركز حول منطقة كالي لاريوس",
        en: "Let's start in the old town of Málaga, home to one of the most distinctive and famous shopping streets in Spain: Calle Larios. Here you can stroll from shop to shop, browsing famous fashion brands, perfumes, cosmetics and accessories. It is considered one of the most expensive streets in Spain, but you can also find small traditional shops concentrated around the Calle Larios area.",
      },
      {
        type: "P",
        ar: "شاشات النوافذ اللافتة للنظر ليست هي العلاج الوحيد للعيون ، فالمتاجر نفسها موجودة داخل المباني الفخمة ذات الجمالية الخاصة جدا ، قرر البناء الرئيسي الذي صممها ، ادواردو ستراكان فيانا كارديناس ، أنه يجب أن تكون متماثلة مع زوايا مستديرة",
        en: "The eye-catching window displays are not the only treat for the eyes: the shops themselves are inside grand buildings with a very particular aesthetic. The chief builder who designed them, Eduardo Strachan Viana-Cárdenas, decided that they should be symmetrical with rounded corners.",
      },
      { type: "IMG", src: IMG("img_0951.jpg"), cap_ar: "التسوق في مالقا", cap_en: "Shopping in Málaga" },
      {
        type: "P",
        ar: "وبالتوازي مع كالي لاريوس ، ستجد كالي نويفا ، وهي منطقة أخرى للمشاة في البلدة القديمة في المدينة وموطن للعديد من العلامات التجارية الكبرى ، قبل افتتاح كالي لاريوس ، كان كالي نويفا شارع التسوق الرئيسي في المدينة ، على الرغم من اسمه ، الا أنه واحد من أقدم الشوارع في البلدة القديمة في المدينة",
        en: "Parallel to Calle Larios you will find Calle Nueva, another pedestrian area in the city's old town and home to many major brands. Before Calle Larios opened, Calle Nueva was the city's main shopping street; despite its name, it is one of the oldest streets in the old town.",
      },
      { type: "H3", ar: "محلات صغيرة قريبة من كالي لاريوس", en: "Small shops close to Calle Larios" },
      {
        type: "P",
        ar: "اذا كنت تبحث عن يوم أكثر استرخاء للتسوق ، فقد ترغب في البدء بزيارة المتاجر في كالي دي لوس مارتيرز ، حيث ستجد العديد من المحلات المستعملة والعتيقة",
        en: "If you are looking for a more relaxed shopping day, you may want to start by visiting the shops on Calle de los Mártires, where you will find many second-hand and vintage stores.",
      },
      {
        type: "P",
        ar: "وفي مكان قريب ستجد كالي أندريس بيريز ، هذا واحد من أضيق الشوارع في البلدة القديمة في مالقا ، ولكن لديه الكثير لتقدمه مثل الشوارع الرئيسية في المدينة ، يعبر الفن عن نفسه بعدة طرق مختلفة في هذا الشارع ، وهو أمر ستراه وتشعر به عند زيارة مؤسساته : من المعارض الفنية والأكشاك الحرفية ومحلات الشاي الى متجر التحف الموجود داخل القصر ، تشتهر هذه المنطقة أيضا بمتجر الآيس كريم التقليدي الشهير ، حيث يمكنك تذوق تورون الحرفي الشهير",
        en: "Nearby you will find Calle Andrés Pérez, one of the narrowest streets in the old town of Málaga, yet it has as much to offer as the city's main streets. Art expresses itself in many different ways on this street, something you will see and feel when visiting its establishments: from art galleries, craft stalls and tea shops to the antiques store inside the palace. This area is also famous for its well-known traditional ice-cream shop, where you can taste the famous artisan turrón.",
      },
      {
        type: "P",
        ar: "اذا واصلت في وسط مالقا ، فتأكد من عدم تفويت ساحة بلازا بينتور يوجينيو شيكانو الملونة ، والمعروفة أيضا باسم لا بريشا ، انها نقطة التقاء جذابة للغاية لأي شخص يحب الحرف اليدوية ، حيث ستجد العديد من متاجر الحرفيين الفريدة هناك",
        en: "If you continue through central Málaga, make sure not to miss the colourful Plaza Pintor Eugenio Chicano, also known as La Brecha. It is a very attractive meeting point for anyone who loves handicrafts, as you will find many unique artisan shops there.",
      },
      { type: "IMG", src: IMG("img_0949-1.jpg"), cap_ar: "التسوق في مالقا", cap_en: "Shopping in Málaga" },
      {
        type: "P",
        ar: "تقع كالي توري دي ساندوفال وكالي سانشا دي لارا وكالي ساليناس أيضا في المركز ، وهي مناطق بها علامات تجارية تجارية وشركات صغيرة ، حيث يمكنك الابتعاد عن صخب الشوارع الرئيسية لبعض الوقت ، بينما تتجول على طول الاعجاب بنوافذ المتجر ، ستصل الى ساحة بلازا ديل أوبيسبو ، وهي منطقة على الطراز الباروكي والتي تعد موطنا لمبنيين مهمين : القصر الأسقفي وكاتدرائية مالقا",
        en: "Calle Torre de Sandoval, Calle Sancha de Lara and Calle Salinas are also in the centre — areas with commercial brands and small businesses, where you can get away from the bustle of the main streets for a while. As you stroll along admiring the shop windows, you will reach Plaza del Obispo, a Baroque-style square that is home to two important buildings: the Episcopal Palace and Málaga Cathedral.",
      },
      { type: "IMG", src: IMG("img_0950.jpg"), cap_ar: "التسوق في مالقا", cap_en: "Shopping in Málaga" },
      { type: "H3", ar: "مراكز التسوق حول البلدة القديمة", en: "Shopping centres around the old town" },
      {
        type: "P",
        ar: "غالبية مراكز التسوق في المدينة قريبة جدا من وسطها التاريخي ، على هذا النحو ، دون الحاجة الى العناء كثيرا ، يمكنك زيارة الطوابق المختلفة من المتاجر الكبرى ، أو تصفح الشركات في مركز التسوق في محطة قطار ماريا زامبرانو ، أو الاستمتاع بيوم من التسوق في الهواء الطلق في مركز التسوق بويرتو مويل أونو",
        en: "The majority of the city's shopping centres are very close to its historic centre. As such, without needing to go to much trouble, you can visit the different floors of the department stores, browse the businesses in the shopping centre at María Zambrano train station, or enjoy a day of open-air shopping at the Muelle Uno port shopping centre.",
      },
    ],
  },
  {
    slug: "shopping-street-markets",
    title_ar: "أشهر أسواق الشوارع في اسبانيا",
    title_en: "The most famous street markets in Spain",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0955.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "التسوق في أشهر أسواق الشوارع في اسبانيا — أسواق الشوارع .. المتعة الحقيقية للتسوق !",
        en: "Shopping in the most famous street markets of Spain — street markets, the real joy of shopping!",
      },
      {
        type: "P",
        ar: "تملأ صفوف من الأكشاك المشرقة والمبهجة شوارع اسبانيا بالحرف اليدوية والتحف والمقتنيات وجميع أنواع الكبح الذي من غير المرجح أن تجده في أي متجر عادي ، فهي فرصة رائعة لتغمر نفسك في جو مثير وممتع ، هناك لا تعرف أبدا ما قد ستجده !",
        en: "Rows of bright and cheerful stalls fill the streets of Spain with handicrafts, antiques, collectables and all kinds of curiosities you are unlikely to find in any ordinary shop. It is a wonderful chance to immerse yourself in an exciting and enjoyable atmosphere — there you never know what you might find!",
      },
      { type: "H3", ar: "سوق شارع ال راسترو ، مدريد", en: "El Rastro street market, Madrid" },
      {
        type: "P",
        ar: "أحد أكثر الأسواق شهرة في اسبانيا ، حيث تفتح الأكشاك كل يوم أحد من الساعة 9 صباحا حتى الساعة 3 مساء ، واذا كنت محظوظا بما يكفي لزيارة مدريد في عطلة رسمية ، فستجد أيضا السوق مفتوحا للعمل ، تقع الأكشاك في كالي ريبيرا دي كورتيدوريس والشوارع المحيطة بها ، لذلك فهي فرصة ممتازة لاستكشاف أحياء مدريد المعروفة مثل لا لاتينا ولافابيس أيضا",
        en: "One of the most famous markets in Spain, where the stalls open every Sunday from 9 a.m. until 3 p.m. And if you are lucky enough to visit Madrid on a public holiday, you will also find the market open for business. The stalls are on Calle Ribera de Curtidores and the surrounding streets, so it is an excellent chance to explore well-known Madrid neighbourhoods such as La Latina and Lavapiés too.",
      },
      {
        type: "P",
        ar: "واذا كنت تشعر ببعض الانحدار والجوع بعد كل هذا التسوق ، فيمكنك دائما التوقف لتناول المقبلات في أحد الحانات في المنطقة المحيطة بالسوق",
        en: "And if you are feeling a little worn out and hungry after all that shopping, you can always stop for tapas at one of the bars in the area around the market.",
      },
      { type: "H3", ar: "سوق لا ألكايسيريا ، غرناطة", en: "La Alcaicería market, Granada" },
      {
        type: "P",
        ar: "في الماضي ، اعتادت لا ألكايسيريا أن تكون سوقا عربيا للحرير ، يعتبر اليوم بازارا رائعا وله تاريخ غني ، تم الحفاظ عليه وتحويله الى مركز اهتمام ثقافي محلي مفتوح يوميا من الساعة 10 صباحا حتى الساعة 9 مساء",
        en: "In the past, La Alcaicería used to be an Arab silk market. Today it is a wonderful bazaar with a rich history, preserved and turned into a local site of cultural interest, open daily from 10 a.m. until 9 p.m.",
      },
      {
        type: "P",
        ar: "هل يمكنك أن تتخيل نفسك تتجول في تلك الشوارع الضيقة ؟",
        en: "Can you imagine yourself wandering those narrow streets?",
      },
      {
        type: "P",
        ar: "كل يوم يملئون الأكشاك التي تبيع الأقمشة والهدايا التذكارية والحرف اليدوية النموذجية للمدينة ، Marquetry والفوانيس الزجاجية الملونة وخزف Fajalauza (قطع الفخار المزججة والمزينة التي نشأت في منطقة غرناطة المعروفة باسم Albaicín) ، كلها أمثلة على الهدايا التذكارية الرائعة للمدينة لأخذها معك الى المنزل",
        en: "Every day they fill the stalls selling fabrics, souvenirs and the handicrafts typical of the city. Marquetry, coloured glass lanterns and Fajalauza pottery (the glazed and decorated ceramic pieces that originated in the Granada district known as the Albaicín) are all examples of the city's wonderful souvenirs to take home with you.",
      },
      { type: "IMG", src: IMG("img_0952.jpg"), cap_ar: "أسواق الشوارع في اسبانيا", cap_en: "Street markets in Spain" },
      { type: "H3", ar: "الس انكيانتس ، برشلونة", en: "Els Encants, Barcelona" },
      {
        type: "P",
        ar: "اذا كانت المساومة أو التصفح في المتاجر التي تبيع الحرف اليدوية والتحف هو الشيء الذي يعجبك ، فستجد نزهة حول سوق Els Encants رائعة للغاية !",
        en: "If bargaining or browsing in shops selling handicrafts and antiques is your thing, you will find a stroll around the Els Encants market absolutely wonderful!",
      },
      {
        type: "P",
        ar: "يعود تاريخه الى عام 1300م ، مما يجعله أحد أقدم الأسواق التي لا تزال تعمل في أوروبا ، اليوم ، يقع في ساحة بلاسا دي ليه غلوريس ، حيث ستجد أكثر من 300 كشك مفتوح أيام الاثنين والأربعاء والجمعة والسبت بين الساعة 9 صباحا والساعة 8 مساء ، يدافع السوق عن التجارة المستدامة",
        en: "It dates back to the year 1300, making it one of the oldest markets still operating in Europe. Today it is located in Plaça de les Glòries, where you will find more than 300 stalls open on Mondays, Wednesdays, Fridays and Saturdays between 9 a.m. and 8 p.m. The market champions sustainable trade.",
      },
      {
        type: "P",
        ar: "هناك مساحات مخصصة لبيع المنتجات المستعملة ، والمزادات الكلاسيكية التي تساهم في الاقتصاد الدائري تقام فيه ، لكن تذكر أنه لا يمكنك المشاركة في هذه الا اذا كنت مستيقظ مبكرا وقمت بزيارة السوق بين الساعة 7.45 و9:30 صباحا ، بداية مبكرة مثمرة !",
        en: "There are spaces dedicated to selling second-hand products, and the classic auctions that contribute to the circular economy are held here. But remember that you can only take part in these if you are up early and visit the market between 7.45 and 9:30 a.m. — a fruitful early start!",
      },
      { type: "IMG", src: IMG("img_0953.jpg"), cap_ar: "أسواق الشوارع في اسبانيا", cap_en: "Street markets in Spain" },
      { type: "H3", ar: "ال جويفز ، أشبيلية", en: "El Jueves, Seville" },
      {
        type: "P",
        ar: "سوق شارع ال جويفز هو منجم ذهب لهواة الجمع ، ونقطة التقاء رائعة لمحبي التحف والكتب وسجلات الفينيل والأشياء القديمة والعتيقة ، الكثير من هذه المنتجات هي عناصر مستعملة تم اعادة تدويرها ، كما استحوذ الجو المفعم بالحيوية والملونة في ال جويفز ، على خيال العديد من الكتاب الذين ذكروه في عملهم ، كتب سرفانتس نفسه عن ال جويفز في كتابه رينكونيتي اي كورتاديلو 1612م",
        en: "The El Jueves street market is a gold mine for collectors and a wonderful meeting point for lovers of antiques, books, vinyl records and old and vintage objects. Many of these products are recycled second-hand items. The lively, colourful atmosphere of El Jueves has also captured the imagination of many writers who mentioned it in their work — Cervantes himself wrote about El Jueves in his book Rinconete y Cortadillo in 1612.",
      },
      {
        type: "P",
        ar: "يفتح السوق كل يوم خميس (باستثناء خميس العهد) ، من الساعة 7 صباحا حتى الساعة 3 مساء ، يقع في كالي فيريا وحولها في الحي القديم في اشبيلية ، مما يعني أن هذه المنطقة بأكملها أعجوبة تنتظر استكشافها",
        en: "The market opens every Thursday (except Maundy Thursday) from 7 a.m. until 3 p.m. It is located on and around Calle Feria in the old quarter of Seville, which means this whole area is a marvel waiting to be explored.",
      },
      { type: "IMG", src: IMG("img_0954.jpg"), cap_ar: "أسواق الشوارع في اسبانيا", cap_en: "Street markets in Spain" },
      { type: "H3", ar: "سوق شارع لا مولا، فورمينتيرا", en: "La Mola street market, Formentera" },
      {
        type: "P",
        ar: "سوق حرفي مليء بروح البحر الأبيض المتوسط ، معروف بكونه سوق الهبي الحقيقي ، تعني الزيارة هنا رحلة العودة الى الستينيات من خلال القصص التي رواها أصحاب الأكشاك الحرفيون الذين وصلوا الى فورمينتيرا خلال تلك السنوات كبدو صغار يتمتعون بروح حرة يبحثون عن نمط حياة بديل ، والذين وقعوا تحت تعويذة الجزيرة",
        en: "A craft market full of Mediterranean spirit, known as the true hippy market. A visit here means a trip back to the sixties through the stories told by the artisan stallholders who arrived in Formentera during those years as young free-spirited nomads looking for an alternative lifestyle, and who fell under the island's spell.",
      },
      {
        type: "P",
        ar: "لا يقام السوق الا بين مايو وأكتوبر ، يومي الأربعاء والأحد من الساعة 4 مساء في قرية بيلار دي لا مولا ، يبيع الحرفيون السيراميك والأواني الزجاجية والخشب والجلود وأكثر من ذلك ، كما أقاموا ورش عمل حتى يتمكن الزوار من تعلم العمل مع هذه المواد ، وانشاء الهدايا التذكارية اليدوية الخاصة بهم",
        en: "The market is only held between May and October, on Wednesdays and Sundays from 4 p.m. in the village of El Pilar de la Mola. The artisans sell ceramics, glassware, wood, leather and much more, and they also run workshops so visitors can learn to work with these materials and create their own handmade souvenirs.",
      },
      { type: "IMG", src: IMG("img_0955.jpg"), cap_ar: "أسواق الشوارع في اسبانيا", cap_en: "Street markets in Spain" },
      {
        type: "P",
        ar: "أسواق سحرية مع حركة دؤوبة وطعام لذيذ وأجواء دافئة ومرحبة حقا ، فاذا كنت تستمتع باكتشاف العادات اليومية للمدن التي تزورها ، فستستمتع حقا بنزهة عبر أسواق الشوارع في اسبانيا ، حيث ان كل كشك هو صندوق كامل من المفاجآت !",
        en: "Magical markets with constant bustle, delicious food and a truly warm, welcoming atmosphere. So if you enjoy discovering the everyday customs of the cities you visit, you will really enjoy a stroll through the street markets of Spain, where every stall is a whole box of surprises!",
      },
    ],
  },
  {
    slug: "shopping-places",
    title_ar: "أماكن مقترحة للتسوق في اسبانيا",
    title_en: "Suggested places to shop in Spain",
    kicker_ar: "أسواق",
    kicker_en: "Shopping",
    image: IMG("img_0949-1.jpg"),
    blocks: [
      {
        type: "H3",
        noNumber: true,
        ar: "أماكن مهمة ومميزة للتسوق في اسبانيا — تسوق وسط أجواء مفعمة بالحيوية",
        en: "Important and special places to shop in Spain — shop amid a lively atmosphere",
      },
      {
        type: "P",
        ar: "بالاضافة الى مدريد أو فالنسيا أو برشلونة المعروفة جدا ، هناك العديد من الوجهات الاسبانية ، حيث يمكنك أن تأخذ الى المنزل بعض أسلوبها في حقيبتك ، الفن أو الموضة أو التصميم القادم أو المنتجات الذواقة أو الحرف اليدوية المحلية ، فجميع العناصر الفريدة هذه التي ستكون أكثر من مجرد تذكار بسيط لوجهة عطلتك",
        en: "In addition to the very well-known Madrid, Valencia or Barcelona, there are many Spanish destinations where you can take some of their style home in your suitcase: art, fashion, up-and-coming design, gourmet products or local handicrafts — all these unique items that will be more than a simple souvenir of your holiday destination.",
      },
      {
        type: "P",
        ar: "اليكم بعض الأماكن المثيرة للاهتمام للزيارة والذهاب للتسوق في اسبانيا :",
        en: "Here are some interesting places to visit and go shopping in Spain:",
      },
      {
        type: "H3",
        ar: "ستي كاليس أو الشوارع السبعة في البلدة القديمة في بلباو",
        en: "Siete Calles, or the seven streets, in the old town of Bilbao",
      },
      {
        type: "P",
        ar: "متاهة من المتاجر والحانات والمطاعم ، حيث يمكنك شراء المنتجات التقليدية أو أحدث الاتجاهات في الموضة والتصميم ، فهل يا ترى الوقت مناسب لك للزيارة ؟ في صباح يوم السبت ، ستتمكن من الانتهاء من احتساء القهوة على صوت موسيقى الجاز في سوق ريبيرا ، على ضفاف مصب نيرفيون",
        en: "A maze of shops, bars and restaurants where you can buy traditional products or the latest trends in fashion and design. So is it a good time for you to visit? On a Saturday morning you will be able to finish off with a coffee to the sound of jazz music in the Ribera market, on the banks of the Nervión estuary.",
      },
      { type: "H3", ar: "كالي لاريوس في الحي القديم في ملقا", en: "Calle Larios in the old quarter of Málaga" },
      {
        type: "P",
        ar: "طريق المشاة اللطيف الذي يسمح لك بالذهاب للتسوق في نفس الوقت الذي تزور فيه المواقع السياحية مثل كاتدرائية مالقا ، والمعروفة أيضا باسم لا مانكيتا ، أو الذراع الواحد ، لأنها تفتقد برجا ، يمكنك انهاء مسيرتك بمشروب واطلالة رائعة على ميناء مالقا ، وهي منطقة تجارية مع مجموعة مختارة من الثقافة والمأكولات التي تستحق الزيارة",
        en: "A pleasant pedestrian route that lets you go shopping at the same time as visiting the sights, such as Málaga Cathedral, also known as La Manquita, or the one-armed lady, because it is missing a tower. You can end your walk with a drink and a wonderful view over the port of Málaga, a commercial area with a select mix of culture and cuisine that is worth a visit.",
      },
      {
        type: "H3",
        ar: "بلازا لوغو والمناطق المحيطة بها في أكورونيا",
        en: "Plaza de Lugo and its surroundings in A Coruña",
      },
      {
        type: "P",
        ar: "ان الميل الذهبي من مدينة الزجاج ، ما يسمى شرفات منطقة لا مارينا ، متناثر بالعلامات التجارية الجاليكية والوطنية والدولية والمتاجر النموذجية وورش الحرف اليدوية ، خط سير تسوق فاخر مخصص للتصميم والأزياء وبالطبع أفضل المأكولات",
        en: "The golden mile of the city of glass — the so-called galleries of the La Marina area — is dotted with Galician, national and international brands, typical shops and craft workshops: a luxury shopping route devoted to design, fashion and of course the best cuisine.",
      },
      {
        type: "H3",
        ar: "أحياء فيغيتا وتريانا في لاس بالماس ، غران كناريا",
        en: "The Vegueta and Triana districts of Las Palmas, Gran Canaria",
      },
      {
        type: "P",
        ar: "طريق يجمع بين العلامات التجارية العالمية والحرف التقليدية ، منقط بشرفات حيوية وواجهات الفن الحديث ، يوصى بشدة أيضا بجزر الكناري عند البحث عن أفضل قيمة مقابل المال ، لأنها تتمتع بأقل الضرائب في أوروبا",
        en: "A route that combines global brands with traditional crafts, dotted with lively terraces and Art Nouveau façades. The Canary Islands are also highly recommended when looking for the best value for money, because they enjoy the lowest taxes in Europe.",
      },
      {
        type: "P",
        ar: "من الأزياء الدولية والفاخرة الى المتاجر المحلية الشهيرة ، دون أن ننسى ثروة الأسواق البلدية أو أسواق الشوارع ، حيث يمكنك العثور على كل شيء تقريبا ، فالتسوق في اسبانيا هو وسيلة للمساهمة في التنمية المحلية وفهم الثقافة والتواصل مع الناس",
        en: "From international and luxury fashion to the famous local shops, without forgetting the wealth of municipal markets or street markets where you can find almost everything — shopping in Spain is a way of contributing to local development, understanding the culture and connecting with people.",
      },
      {
        type: "P",
        ar: "بعد كل هذا ما رأيك ان نذهب سويا للتسوق ؟",
        en: "After all this, what do you say we go shopping together?",
      },
    ],
  },
];
