import type { Guide } from "./france-guides";

// Barcelona landmark deep-dive pages ("read more" sections on the original site).
export const spainGuidesBarcelona: Guide[] = [
  {
    slug: "sagrada-familia",
    title_ar: "كنيسة ساغرادا فاميليا",
    title_en: "The Sagrada Família Church",
    kicker_ar: "برشلونة",
    kicker_en: "Barcelona",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2875.jpg",
    blocks: [
      {
        type: "P",
        ar: "كنيسة ساغرادا فاميليا La sagrada Família والمعروفة أيضا باسم Sagrada Família ( العائلة المقدسة ) هي كاتدرائية رومانية كاثوليكية صغيرة غير مكتملة في منطقة ايكسامبل في برشلونة كاتالونيا باسبانيا ، صممها المهندس المعماري الاسباني انطوني غاودي (1852-1926) ، ويعد عمله في المبنى جزءا من أحد مواقع التراث العالمي في 7 نوفمبر 2010 ، كرس البابا بنديكتوس السادس عشر الكنيسة وأعلنها كنيسة صغيرة",
        en: "The Sagrada Família church (La Sagrada Família), also known as Sagrada Família (the Holy Family), is an unfinished Roman Catholic minor basilica in the Eixample district of Barcelona, Catalonia, Spain. It was designed by the Spanish architect Antoni Gaudí (1852-1926), and his work on the building is part of a World Heritage Site. On 7 November 2010, Pope Benedict XVI consecrated the church and declared it a minor basilica",
      },
      {
        type: "P",
        ar: "في 19 مارس 1882 ، بدأ بناء ساغرادا فاميليا تحت اشراف المهندس المعماري فرانسيسكو دي باولا ديل فيلار ، في عام 1883 ، عندما استقال فيلار ، تولى غاودي منصب كبير المهندسين المعماريين ، وقام بتحويل المشروع بأسلوبه المعماري والهندسي ، والدمج بين أشكال فن القوطية والخطوط المنحنية في الآرت نوفو ، كرس غاودي ما تبقى من حياته للمشروع ، ودفن في سرداب ، في وقت وفاته عام 1926 ، كان أقل من ربع المشروع قد اكتمل",
        en: "On 19 March 1882, construction of the Sagrada Família began under the supervision of the architect Francisco de Paula del Villar. In 1883, when Villar resigned, Gaudí took over as chief architect and transformed the project with his own architectural and engineering style, combining Gothic forms with the curved lines of Art Nouveau. Gaudí devoted the rest of his life to the project and is buried in the crypt. At the time of his death in 1926, less than a quarter of the project had been completed",
      },
      {
        type: "P",
        ar: "بالاعتماد فقط على التبرعات الخاصة ، تقدم بناء ساغرادا فاميليا ببطء وتوقف بسبب الحرب الاهلية الاسبانية في يوليو 1936 ، أشعل الثوار النار في القبو واقتحموا طريقهم الى ورشة العمل ، ودمروا جزئيا مخططات غاودي الأصلية ورسوماته ونماذج الجص ، مما أدى الى 16 عاما من العمل لتجميع أجزاء النموذج الرئيسي ، استؤنف البناء علي فترات متقطعة في الخمسينيات ، ان التطورات في التقنيات مثل التصميم بمساعدة الكمبيوتر والتحكم الرقمي باستخدام الحاسوب (CNC) قد مكنت منذ ذلك الحين من احراز تقدم أسرع وتجاوز البناء نقطة المنتصف في عام 2010 ، ومع ذلك لا تزال هناك بعض من أكبر تحديات المشروع ، بما في ذلك بناء عشرة أبراج أخرى ، كل منها يرمز الى أهمية شخصية توراتية في العهد الجديد",
        en: "Relying only on private donations, construction of the Sagrada Família advanced slowly and was interrupted by the Spanish Civil War in July 1936. Revolutionaries set fire to the crypt and broke into the workshop, partly destroying Gaudí's original plans, drawings and plaster models, which led to 16 years of work to piece together the fragments of the main model. Construction resumed intermittently in the 1950s. Advances in technology such as computer-aided design and computer numerical control (CNC) have since enabled faster progress, and construction passed the midpoint in 2010. Even so, some of the project's greatest challenges remain, including building ten more towers, each symbolising the importance of a biblical figure in the New Testament",
      },
      {
        type: "P",
        ar: "من المتوقع أن يكتمل المبنى بحلول عام 2026 ، الذكرى المئوية لوفاة غاودي ، تتمتع الكاتدرائية بتاريخ طويل من الاختلاف في الرأي بين سكان برشلونة حول أنها من المحتمل قد تنافس كاتدرائية برشلونة ، وحول تصميم غاودي نفسه ، وحول احتمال أن العمل بعد وفاة غاودي قد تجاهل تصميمه ، واقتراح عام 2007 بناء نفق قريب كجزء من وصلة السكك الحديدية عالية السرعة بين إسبانيا وفرنسا ، مما قد يزعج استقرارها قال الناقد الفني راينر زيربست ، في وصفه لـ ساغرادا فاميليا ، ربما يكون من المستحيل العثور على مبنى كنسية مثله في تاريخ الفن بأكمله ، ويصفها بول جولدبيرجر بأنها التفسير الشخصي الأكثر استثنائية للعمارة القوطية منذ العصور الوسطى ، البازيليكا ليست الكنيسة الكاتدرائية لأبرشية برشلونة ، حيث ينتمي هذا اللقب الى كاتدرائية الصليب المقدس وسانت يولاليا",
        en: "The building is expected to be completed by 2026, the centenary of Gaudí's death. The basilica has a long history of dividing opinion among the people of Barcelona: over the possibility that it might rival Barcelona Cathedral, over Gaudí's design itself, over the possibility that work after Gaudí's death has ignored his design, and over the 2007 proposal to build a nearby tunnel as part of the high-speed rail link between Spain and France, which might disturb its stability. The art critic Rainer Zerbst said, describing the Sagrada Família, that it is probably impossible to find a church building like it in the entire history of art, and Paul Goldberger describes it as the most extraordinary personal interpretation of Gothic architecture since the Middle Ages. The basilica is not the cathedral church of the archdiocese of Barcelona, as that title belongs to the Cathedral of the Holy Cross and Saint Eulalia",
      },
      {
        type: "P",
        ar: "بعض من أجزائها غير المكتملة دمرت أثناء الحرب الفوضوية ، الا أن العمل استمر بعدها والتزم عدة معماريون بعد جاودي في تصميمها ، وهي الآن من أكثر الأماكن جاذبية للسياح في برشلونة الذين بامكانهم زيارة الأجزاء المكتملة منها ، حيث زارها قرابة المليون شخص في عام 2004 حسب صحيفة كاتالونيا",
        en: "Some of its unfinished parts were destroyed during the war's chaos, yet work continued afterwards and several architects after Gaudí committed themselves to his design. It is now one of the most attractive places for tourists in Barcelona, who can visit the completed parts of it; around a million people visited it in 2004 according to a Catalan newspaper",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2875.jpg",
        cap_ar: "كنيسة ساغرادا فاميليا ببرشلونة",
        cap_en: "The Sagrada Família church in Barcelona",
      },
      {
        type: "P",
        ar: "يستدعي تصميم غاودي الأصلي ما مجموعه ثمانية عشر برجا ، يمثلون بترتيب تصاعدي للارتفاع الاثني عشر رسولا ومريم العذراء ، والمبشرين الأربعة ، والأطول من الجميع ، يسوع المسيح ، تم بناء ثمانية أبراج اعتبارا من عام 2010 ، تتوافق مع أربعة رسل في واجهة المهد وأربعة رسل في واجهة الآلام ، وفقا لـ تقرير الأعمال لعام 2005 للموقع الرسمي للمشروع ، تشير الرسومات الموقعة من غاودي والتي تم العثور عليها مؤخرا في أرشيف البلدية ، الى أن مستدقة العذراء كان يقصدها في الواقع أن تكون أقصر من تلك التي رسمها الانجيليون ، سوف يتبع ارتفاع البرج نية غاودي ، والتي وفقا للتقرير ستعمل مع الأساس الحالي",
        en: "Gaudí's original design calls for a total of eighteen towers, representing in ascending order of height the twelve apostles, the Virgin Mary, the four evangelists and, tallest of all, Jesus Christ. Eight towers had been built as of 2010, corresponding to four apostles on the Nativity façade and four apostles on the Passion façade. According to the 2005 work report on the project's official website, drawings signed by Gaudí and recently found in the municipal archive indicate that the spire of the Virgin was in fact intended to be shorter than those drawn for the evangelists. The tower's height will follow Gaudí's intention, which according to the report will work with the existing foundation",
      },
      {
        type: "P",
        ar: "تعلو أبراج الانجيليين منحوتات من رموزهم التقليدية ثور مجنح ( القديس لوقا ) ، رجل مجنح ( القديس ماثيو ) ، نسر ( القديس يوحنا ) ، وأسد مجنح ( القديس مرقس ) ، يجب أن يعلو البرج المركزي ليسوع المسيح صليب عملاق ، سيكون ارتفاعه الاجمالي 172.5 مترا ، أقل من ارتفاع تل مونتجويك في برشلونة ، حيث اعتقد غاودي أن خليقته يجب ألا تتجاوز خلق الله ، الأبراج السفلية محاطة باشكال حزم من القمح وكؤوس مع عناقيد عنب ، تمثل القربان المقدس ، تدعو المخططات الى وضع أجراس أنبوبية داخل الأبراج ، مدفوعة بقوة الرياح ، ودفع الصوت الى داخل الكنيسة ، أجرى غاودي دراسات صوتية لتحقيق النتائج الصوتية المناسبة داخل المعبد ومع ذلك يوجد جرس واحد فقط في مكانه حاليا",
        en: "The evangelists' towers are topped by sculptures of their traditional symbols: a winged bull (Saint Luke), a winged man (Saint Matthew), an eagle (Saint John) and a winged lion (Saint Mark). The central tower of Jesus Christ is to be crowned by a giant cross, and its total height will be 172.5 metres, lower than the height of Montjuïc hill in Barcelona, since Gaudí believed his creation should not surpass God's creation. The lower towers are surrounded by shapes of sheaves of wheat and chalices with bunches of grapes, representing the Eucharist. The plans call for tubular bells to be placed inside the towers, driven by the force of the wind and pushing the sound into the church. Gaudí carried out acoustic studies to achieve the appropriate sound results inside the temple, yet only one bell is currently in place",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2873.jpg",
        cap_ar: "صورة توضح التفاصيل الدقيقة في تشييد كنيسة ساغرادا فاميليا ببرشلونة",
        cap_en: "A photo showing the fine detail in the construction of the Sagrada Família church in Barcelona",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2874.jpg",
        cap_ar: "دقة التصاميم في كنيسة ساغرادا فاميليا ببرشلونة",
        cap_en: "The precision of the designs in the Sagrada Família church in Barcelona",
      },
      {
        type: "P",
        ar: "الكنيسة لها مكانة في التراث العالمي ، فهي جنبا الى جنب مع ستة مبان أخرى من غاودي في برشلونة ، يعد جزء من لاساغرادا فاميليا أحد مواقع التراث العالمي لليونسكو ، حيث يشهد على مساهمة غاودي الابداعية الاستثنائية في تطوير الهندسة المعمارية وتكنولوجيا البناء ، بعد أن مثلت الحداثة في كاتالونيا ومتوقع وأثرت في العديد من الأشكال والتقنيات التي كانت ذات صلة بتطور البناء الحديث في القرن العشرين ، يتضمن النقش فقط القبو وواجهة الميلاد",
        en: "The church holds a place in world heritage: together with six other Gaudí buildings in Barcelona, part of La Sagrada Família is a UNESCO World Heritage Site, bearing witness to Gaudí's exceptional creative contribution to the development of architecture and building technology, having represented Modernisme in Catalonia and influenced many forms and techniques relevant to the development of modern construction in the twentieth century. The inscription covers only the crypt and the Nativity façade",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2872.jpg",
        cap_ar: "الواجهة الامامية لكنيسة ساغرادا كاميليا ببرشلونة",
        cap_en: "The front façade of the Sagrada Família church in Barcelona",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2877.jpg",
        cap_ar: "ابداع التصاميم من داخل كنيسة ساغرادا كاميليا ببرشلونة",
        cap_en: "The brilliance of the designs inside the Sagrada Família church in Barcelona",
      },
      {
        type: "P",
        ar: "يمكن للزوار الوصول الى أبراج صحن الكنيسة والسرداب والمتحف والمتجر والآلام والميلاد ، يتطلب الدخول الى أي من الأبراج الحجز والشراء المسبق للتذكرة ، لا يمكن الوصول الا عن طريق المصعد الذي يصعد قليلا حتى ما تبقى من الأبراج الى الجسر بين الأبراج ، يتم النزول عبر درج حلزوني ضيق للغاية يزيد عن 300 درجة ، هناك تحذير منشور لمن يعانون من حالات طبية",
        en: "Visitors can reach the nave towers, the crypt, the museum, the shop, and the Passion and Nativity façades. Entering any of the towers requires booking and buying the ticket in advance. Access is only by a lift that rises a little way up what remains of the towers to the bridge between them; the descent is by an extremely narrow spiral staircase of more than 300 steps, and a warning is posted for those with medical conditions",
      },
      {
        type: "P",
        ar: "اعتبارا من يونيو 2017 ، أصبح شراء التذاكر عبر الانترنت متاحا ، اعتبارا من أغسطس 2010 ، كانت هناك خدمة يمكن من خلالها للزوار شراء رمز دخول اما من أكشاك سيرفكايكسا ATM ( جزء من بنك كايكسا ) أوعبر الانترنت ، خلال موسم الذروة ، من مايو الى أكتوبر ، تأخر الحجوزات للدخول لمدة تصل الى بضعة أيام ليس بالأمر غير المعتاد",
        en: "As of June 2017, buying tickets online became available. As of August 2010, there was a service through which visitors could buy an entry code either from ServiCaixa ATM kiosks (part of La Caixa bank) or online. During the peak season, from May to October, waiting a few days for an entry booking is not unusual",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2876.jpg",
        cap_ar: "قبة كنيسة ساغرادا كاميليا ببرشلونة",
        cap_en: "The dome of the Sagrada Família church in Barcelona",
      },
    ],
  },
  {
    slug: "la-rambla",
    title_ar: "شارع الرامبلا .. نبض الحركة ببرشلونة",
    title_en: "La Rambla — the pulse of movement in Barcelona",
    kicker_ar: "برشلونة",
    kicker_en: "Barcelona",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2887-1.jpg",
    blocks: [
      {
        type: "P",
        ar: "يعتبر شارع رامبلا ببرشلونة الشارع الحيوي على مدار الساعة ، وهو أحد أبرز معالم اقليم برشلونة الواقعة باسبانيا التي لا تهدأ من حيوية الزوار العرب خصوصا طيلة أيام السنة ، حيث يعتبر شارع الرامبلا بالاضافة الى ذلك من أهم شوارع اقليم كاتالانيا التجارية نظرا لكونه شارعها الرئيسي الذي يشكل نقطة وصل بين ساحة كاتالونيا ومركز المدينة القديم ، اذ يمتد شارع الرامبلا برشلونة على طول يقدر حوالي 1.2 كيلو متر مربع ، ويعتبر حاليا من أجمل الاماكن السياحية الجاذبة للزوار من كل أنحاء العالم",
        en: "La Rambla in Barcelona is a street that is lively around the clock, and one of the most prominent landmarks of the Barcelona region in Spain, a place that never quietens from the bustle of Arab visitors in particular all year round. La Rambla is also one of the most important commercial streets in the Catalonia region, being its main street and the link between Plaça de Catalunya and the old city centre. La Rambla in Barcelona stretches for about 1.2 kilometres, and it is currently one of the most beautiful tourist places attracting visitors from all over the world",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2880.jpg",
        cap_ar: "شارع الرامبلا كما هي عادته معجا بالناس",
        cap_en: "La Rambla, as usual, packed with people",
      },
      {
        type: "P",
        ar: "شارع الرامبلا برشلونة هو الشارع الرئيسي في المدينة وقلبها النابض بالزوار يوميا ففي الصباح يمتلئ بالباعة المتجولين والسياح وعند المساء يصبح لليل حكايات وروايات حيث يتحول شارع الرامبلا برشلونة لخلايا مكتظة بالناس وتبدأ سهرات السمر مليئة بأجواء الفرح والسعادة وحتى طلوع الفجر ، يعتبر شارع الرامبلا من اهم معالم السياحة في اسبانيا ، يمتد الشارع على طول 1.2كم يربط ساحة كاتالونيا بمركز المدينة حيث ينتهي بشاطئ كريستوف كولومبوس المليء بالسفن والميناء الأولمبي ليكسب شارع الرامبلا في مدينة برشلونة اطلالة جميلة على البحر الأبيض المتوسط",
        en: "La Rambla is the main street of Barcelona and its heart, beating with visitors daily. In the morning it fills with street vendors and tourists, and in the evening the night takes on its own stories and tales as La Rambla turns into cells packed with people, and evenings full of joy and happiness begin and last until dawn. La Rambla is one of the most important tourist landmarks in Spain; the street runs for 1.2 km linking Plaça de Catalunya with the city centre, ending at the Christopher Columbus shore filled with ships and the Olympic Port, giving La Rambla in Barcelona a beautiful view of the Mediterranean Sea",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2886.jpg",
        cap_ar: "لقطة علوية لشارع الرامبلا ببرشلونة",
        cap_en: "An aerial shot of La Rambla in Barcelona",
      },
      {
        type: "P",
        ar: "كما اشرت فان الشارع له شعبية لدى السياح والسكان المحليين على حد سواء ، تصطف على جانبيه الأشجار ، وعادة ما يكون مزدحما للغاية وخاصة في ذروة الموسم السياحي ، شعبية الشارع لدى السياح قد أثرت على طبيعته ، مع الانتقال الى مقاهي الرصيف وأكشاك بيع التذكارات ، عانى الشارع من وجود النشالين ، وخاصة في الطرف الجنوبي ، يقع شارع لا رامبلا قبالة بلازا كاتالونيا والرائدة في أسفل اليمين نحو الميناء والشاطئ ، وستجد عازفي الشوارع ، والكثير من الحانات والمطاعم وسوق بوكويريا بما يجلب الكثير من المتعة والبهجة ، كما يقع شارع لا رامبلا بالقرب من الميناء التي توجد به أسواق محلية صغيرة الحجم وبها على الجبهات تذكارات من الرسامين",
        en: "As I mentioned, the street is popular with tourists and locals alike. It is lined with trees on both sides and is usually extremely crowded, especially at the peak of the tourist season. Its popularity with tourists has affected its character, with the shift towards pavement cafés and souvenir stalls, and the street has suffered from pickpockets, especially at the southern end. La Rambla lies off Plaça de Catalunya and leads down to the right towards the port and the beach, and you will find street musicians and many bars and restaurants and the Boqueria market, all bringing plenty of fun and delight. La Rambla is also close to the port, where there are small local markets with souvenirs from painters on their fronts",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2887.jpg",
        cap_ar: "تنتشر محلات بيع الورود بشارع الرامبلا ببرشلونة",
        cap_en: "Flower shops are spread along La Rambla in Barcelona",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2888.jpg",
        cap_ar: "احد جوانب شارع الرامبلا ببرشلونة",
        cap_en: "One side of La Rambla in Barcelona",
      },
      {
        type: "H3",
        ar: "افضل الانشطة التي يمكن القيام بها في شارع الرامبلا ببرشلونة",
        en: "The best activities to do on La Rambla in Barcelona",
      },
      {
        type: "P",
        ar: "التجول بهذا الشارع الشعبي النابض بالحياة في كل جوانبه الداخلية والحيوية والتعرف على ما به من نشاطات مسلية",
        en: "Strolling along this popular street, alive in all its inner and lively corners, and discovering the entertaining activities it holds",
      },
      {
        type: "P",
        ar: "أما بالنسبة لأول نشاط يمكنكم ممارسته في داخل هذا الشارع الفريد من نوعه فإننا نشيد بكم مشاهدة أحد عروض رقصة الفلامينغو المليئة بالاثارة والمتعة التي تقام بشكل دوري في وسط ساحة الشارع بشكل مجاني",
        en: "As for the first activity you can enjoy inside this one-of-a-kind street, we recommend watching one of the flamenco dance shows, full of excitement and enjoyment, held regularly in the middle of the street's square, free of charge",
      },
      {
        type: "P",
        ar: "تستطيعون بالاضافة الى ذلك القيام بالتقاط العدد الكافي من الصور التخليدية لهذه الرحلة بشكل احترافي وخصوصا للمعالم الأثرية المنتشرة في كل مكان بالشارع أو العروض المسرحية التي يقوم بها بعض الشبان اليافعين",
        en: "You can also take plenty of commemorative photos of this trip professionally, especially of the historic landmarks spread everywhere along the street, or of the theatrical performances put on by some young men",
      },
      {
        type: "P",
        ar: "وهكذا في ختام رحلتكم الساحرة للأعين والتي لا يوجد لها مثيل بالعالم اننا نقول لكم بأنكم في حاجة لتناول وجبة العشاء",
        en: "And so, at the close of your trip that enchants the eyes and has no equal in the world, we say to you that you will need to have dinner",
      },
      {
        type: "P",
        ar: "ضمن أحد المطاعم الكتالانية العريقة على أنغام الموسيقى والاطلالات الآسرة للفؤاد",
        en: "In one of the long-established Catalan restaurants, to the sound of music and views that captivate the heart",
      },
      {
        type: "P",
        ar: "يمكنك شراء ما تحتاجه من سوق لابوكويرا للاحتياجات اليومية فهو مركز تسوق معروف في شارع لا رامبلا برشلونة كما يوجد الكثير من المتاجر لبيع الهدايا التذكارية المميزة بأسعار مناسبة لجميع السياح",
        en: "You can buy what you need from La Boqueria market for daily necessities, as it is a well-known shopping centre on La Rambla in Barcelona, and there are also many shops selling distinctive souvenirs at prices suitable for all tourists",
      },
      {
        type: "P",
        ar: "ستحصل على صور تذكارية مقابل بعض السنتات مع الأشخاص الذين يظهرون بملابس مميزة ذات الوان زاهية ويقدمون عروضا مضحكة مكسبين شارع الرامبلا برشلونة متعة وتسلية تجذب السياح بكثرة",
        en: "For a few cents you will get souvenir photos with the people who appear in distinctive brightly coloured costumes and put on funny performances, giving La Rambla in Barcelona a fun and entertaining quality that attracts tourists in great numbers",
      },
      {
        type: "P",
        ar: "اخذ قسطا من الراحة في المقاهي العديدة وتناول وجبات سريعة في المطاعم الموجودة على الجانب الايسر من الساحة المليئة بأشجار النخيل المحاط بها من كافة الاتجاهات حيث تتواجد بعد منتصف شارع الرامبلا برشلونة",
        en: "Take a rest in the many cafés and eat fast food in the restaurants on the left-hand side of the square, which is full of palm trees surrounding it from every direction, found past the middle of La Rambla in Barcelona",
      },
      {
        type: "P",
        ar: "ستستمتع كثيرا اثناء الحصول على صورة شخصية لك يرسمها احد فنانين الرسم المتواجدون بكثرة في شارع لا رامبلا وخاصة في الآونة الأخيرة",
        en: "You will greatly enjoy having a portrait of yourself drawn by one of the many painters present on La Rambla, especially in recent times",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2889.jpg",
        cap_ar: "شارع الرامبلا ببرشلونة",
        cap_en: "La Rambla in Barcelona",
      },
      {
        type: "H3",
        ar: "بعض المشاهد بشارع رامبلا ببرشلونة",
        en: "Some scenes on La Rambla in Barcelona",
      },
      {
        type: "P",
        ar: "يزدحم الممشى المركزي الذي تصطف على جانبيه الأشجار في لا رامبلا خلال النهار وحتى وقت متأخر من الليل ، وتنعكس أصوله كمجرى مائي في تصميم الرصف ، الذي يبدو أنها متموجة مثل الماء ، وعلى طول الكورنيش توجد أكشاك لبيع الصحف والهدايا التذكارية ، وأكشاك أخرى لبيع الزهور ، كما يوجد تجار الشوارع وفناني الأداء ومقاهي وحانات الأرصفة ، كما تقع العديد من المعالم البارزة داخل الكورنيش ، بما في ذلك فسيفساء خوان ميرو ونافورة كاناليتيس ونقطة التقاء شعبية",
        en: "The central tree-lined promenade of La Rambla is crowded during the day and until late at night. Its origins as a watercourse are reflected in the design of the paving, which appears to ripple like water, and along the promenade there are kiosks selling newspapers and souvenirs and others selling flowers, as well as street traders, performers, and pavement cafés and bars. Many notable landmarks also lie within the promenade, including the Joan Miró mosaic and the Canaletes fountain, a popular meeting point",
      },
      {
        type: "P",
        ar: "توجد على طول رامبلا المباني التاريخية مثل قصر فيرينا ومسرح ليسيو الذي يتم فيه عرض الأوبرا والباليه ، يفتح سوق لا بوكوريا قبالة رامبلا ، وهو واحد من أهم المعالم السياحية في المدينة ، ويستضيف مجموعة متنوعة جدا من السلع",
        en: "Along La Rambla there are historic buildings such as the Palau de la Virreina and the Liceu theatre, where opera and ballet are performed. La Boqueria market opens off La Rambla, one of the city's most important attractions, hosting a very wide variety of goods",
      },
      {
        type: "P",
        ar: "يؤدي أحد الشوارع الجانبية ، التي لا يتجاوز طوله بضعة أمتار ، الى الساحة الملكية Plaça Reial وهي ساحة يوجد بها أشجار النخيل والمباني ذات الطوابق التي تحتوي على العديد من الحانات والمطاعم ، حيث يتجمع جامعو الطوابع والعملات في عطلات نهاية الأسبوع",
        en: "One of the side streets, no more than a few metres long, leads to Plaça Reial, a square with palm trees and multi-storey buildings containing many bars and restaurants, where stamp and coin collectors gather at weekends",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2892.jpg",
        cap_ar: "من مشاهد شارع الرامبلا ببرشلونة",
        cap_en: "Scenes from La Rambla in Barcelona",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2891.jpg",
        cap_ar: "من مشاهد شارع الرامبلا ببرشلونة",
        cap_en: "Scenes from La Rambla in Barcelona",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2890.jpg",
        cap_ar: "من مشاهد شارع الرامبلا ببرشلونة",
        cap_en: "Scenes from La Rambla in Barcelona",
      },
      {
        type: "H3",
        ar: "المزيد من الانشطة بشارع الرامبلا ببرشلونة",
        en: "More activities on La Rambla in Barcelona",
      },
      {
        type: "LIST",
        ar: [
          "يمكن السير في لاس رامبلاس والتمتع بالطبيعة الخلابة ، فالأهمية الأولى للمشاة والتجول في المنطقة",
          "يوجد به مسرح ليسيو ، فهو يقع في أقصى الشمال من شارع الرامبلا",
          "يمكن التمتع بالفن الياباني والديكور واللوحات اليابانية الساحرة المتواجدة على الجدران الخاصة بمبنى لاس رامبلا",
          "يوجد الكثير من العروض المتنوعة ، ويشتهر هناك التماثيل البشرية ، وكذلك يوجد الكثير من الفنانين والرسامين والكاريكاتير",
          "يوجد الكثير من الألعاب المدهشة ، ويوجد التمثال المشهور للرحالة الأسطوري كريستوفر كولومبس",
          "يوجد تمثال بشري لجاليليو فيمكنك التمتع بمشاهدته بجانب غيره من التماثيل البشرية المبهرة",
          "يوجد بلاط على شكل دائري للفنان الكبير ميرو ، فيوجد الكثير من السياح يهتمون بالسير فوق تلك الدائرة",
          "يوجد بالشارع سوق للمواد الغذائية يسمى لا بويكيريا فود ماركت ، فيمكن للسياح التمتع بالطعام الفريش والرائع",
          "يوجد أيضا الكثير من المحلات التجارية المختلفة التي يمكنك التسوق من خلالها",
          "يوجد مكان مخصص لركوب الدراجات ، حيث يراعى أيضا محبي رياضة ركوب الدراجات مع التمتع بالمناظر الطبيعية الخلابة أثناء التجول في الشارع بالدراجة",
          "يوجد بالشارع الكثير من متاجر الهدايا التذكارية التي تمكنك من شراء هدايا مميزة تذكرك برحلتك الرائعة في برشلونة",
          "يخصص مكان لتأجير الدراجات وذلك مقابل 5 يورو",
          "يوجد بالشارع معرض فنون مبهر جدا لعشاق الفن",
        ],
        en: [
          "You can walk along Las Ramblas and enjoy the stunning setting, since pedestrians and strolling around the area come first here",
          "It has the Liceu theatre, located at the far northern end of La Rambla",
          "You can enjoy Japanese art, decoration and the charming Japanese paintings on the walls of the Las Ramblas building",
          "There are many varied performances, and human statues are famous there, as well as many artists, painters and caricaturists",
          "There are many amazing attractions, and the famous statue of the legendary explorer Christopher Columbus",
          "There is a human statue of Galileo that you can enjoy watching alongside other impressive human statues",
          "There is circular tiling by the great artist Miró, and many tourists make a point of walking over that circle",
          "The street has a food market called La Boqueria Food Market, where tourists can enjoy fresh and wonderful food",
          "There are also many different shops where you can do your shopping",
          "There is a dedicated place for cycling, so cycling lovers are catered for too, enjoying the stunning views while riding along the street",
          "The street has many souvenir shops that let you buy distinctive gifts to remind you of your wonderful trip in Barcelona",
          "A place is set aside for bicycle rental for 5 euros",
          "The street has a very impressive art gallery for art lovers",
        ],
      },
    ],
  },
  {
    slug: "park-guell",
    title_ar: "حديقة جويل .. ترفيه بلا نهاية",
    title_en: "Park Güell — endless entertainment",
    kicker_ar: "برشلونة",
    kicker_en: "Barcelona",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2897-1.jpg",
    blocks: [
      {
        type: "P",
        ar: "منتزة غويل هو نظام حدائق عامة يتكون من حدائق وعناصر معمارية تقع في كارمل هيل في برشلونة ، ينتمي كارمل هيل الى سلسلة جبال كولسيرولا يقع بارك ديل كارمل على الوجه الشمالي ، يقع منتزه غويل في حي لا سالوت في حي غراسيا في برشلونة ، مع وضع التحضر في الاعتبار ، عين أوزيبي غويل تصميم الحديقة الى انطونيو جودي المهندس المعماري الشهير ووجه الحداثة الكاتالونية",
        en: "Park Güell is a system of public gardens made up of gardens and architectural elements located on Carmel Hill in Barcelona. Carmel Hill belongs to the Collserola mountain range, and Park del Carmel lies on the northern face. Park Güell is located in the La Salut neighbourhood in the Gràcia district of Barcelona. With urbanisation in mind, Eusebi Güell assigned the design of the park to Antoni Gaudí, the famous architect and the face of Catalan Modernisme",
      },
      {
        type: "P",
        ar: "تم بناء الحديقة من عام 1900 الى عام 1914 وتم افتتاحها رسميا كمتنزه عام في عام 1926 ، وفي عام 1984 أعلنت منظمة اليونسكو المنتزه موقع تراث عالمي تحت عنوان أعمال أنتوني غاودي",
        en: "The park was built from 1900 to 1914 and was officially opened as a public park in 1926, and in 1984 UNESCO declared the park a World Heritage Site under the title Works of Antoni Gaudí",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2893.jpg",
        cap_ar: "منتزة غويل ببرشلونة",
        cap_en: "Park Güell in Barcelona",
      },
      {
        type: "P",
        ar: "بارك غويل هو انعكاس لوفرة غاودي الفنية ، والتي تنتمي الى مرحلته الطبيعية ( العقد الأول من القرن العشرين ) ، خلال هذه الفترة أتقن المهندس المعماري أسلوبه الشخصي من خلال الالهام من الأشكال العضوية ، لقد طبق سلسلة من الحلول الهيكلية الجديدة المتجذرة في تحليل الهندسة ، الى ذلك يضيف الفنان الكتالوني حرية ابداعية وابداعا ابداعيا زخرفيا ، بدء من نوع من الباروك ، تكتسب أعماله ثراء بنيويا من الأشكال والأحجام ، خالية من الصلابة العقلانية أو أي نوع من المباني الكلاسيكية ، في تصميم منتزه غويل ، أطلق غاودي العنان لكل عبقريته المعمارية ووضع لممارسة الكثير من حلوله الهيكلية المبتكرة التي ستصبح رمزا لأسلوبه العضوي والتي ستبلغ ذروتها في انشاء كنيسة بازيليكا واكسبيرتوري للعائلة المقدسة ( الكاتالونية )",
        en: "Park Güell is a reflection of Gaudí's artistic abundance, belonging to his naturalist phase (the first decade of the twentieth century). During this period the architect perfected his personal style through inspiration from organic forms; he applied a series of new structural solutions rooted in the analysis of geometry, to which the Catalan artist adds creative freedom and decorative inventiveness, starting from a kind of Baroque. His works gain a structural richness of forms and volumes, free of rational rigidity or any kind of classical building. In designing Park Güell, Gaudí unleashed all his architectural genius and put into practice many of his innovative structural solutions that would become the symbol of his organic style and would culminate in the building of the Basílica i Temple Expiatori de la Sagrada Família (in Catalan)",
      },
      {
        type: "P",
        ar: "صمم غويل وغاودي هذه الحديقة الواقعة داخل منتزه طبيعي ، لقد تخيلوا مجموعة منظمة من المنازل عالية الجودة ، المزينة بأحدث التطورات التكنولوجية لضمان أقصى قدر من الراحة ، منتهية بلمسة فنية ، لقد تصوروا أيضا مجتمعا متأثرا بشدة بالرمزية ، نظرا لأنهم في العناصر المشتركة للحديقة كانوا يحاولون تجميع العديد من المثل السياسية والدينية المشتركة بين الراعي والمهندس المعماري ، لذلك هناك مفاهيم ملحوظة نشأت من الكاتالونية السياسية – خاصة في درج المدخل ، حيث يتم تمثيل البلدان الكاتالونية – ومن الكاثوليكية نصب آل كالفاريو النصب التذكاري آل كالفاريو ، المصمم في الأصل ليكون كنيسة صغيرة العناصر الاسطورية مهمة للغاية من الواضح أن مفهوم غويل وغاودي للحديقة مستوحى أيضا من معبد أبولو في دلفي",
        en: "Güell and Gaudí designed this garden set inside a natural park. They imagined an organised group of high-quality houses, fitted with the latest technological advances to guarantee the utmost comfort and finished with an artistic touch. They also envisioned a community strongly influenced by symbolism, since in the shared elements of the park they were trying to bring together many of the political and religious ideals shared by the patron and the architect. There are therefore notable concepts arising from political Catalanism — especially in the entrance staircase, where the Catalan lands are represented — and from Catholicism, the Calvary monument, originally designed to be a small chapel. Mythological elements are extremely important, and clearly Güell and Gaudí's concept of the park was also inspired by the Temple of Apollo at Delphi",
      },
      {
        type: "P",
        ar: "من ناحية أخرى العديد من الخبراء حاولوا ربط المتنزه برموز مختلفة بسبب الايقونات المعقدة التي طبقها غاودي على المشروع الحضري ، تنتقل مثل هذه المراجع من التبرير السياسي الى التمجيد الديني مرورا بالأساطير والتاريخ والفلسفة ، وعلى وجه التحديد تزعم العديد من الدراسات أنها ترى اشارات الى الماسونية ، على الرغم من المعتقدات الدينية العميقة لكل من غادوي والكونت غويل ، ولم يتم اثبات هذه الاشارات في تأريخ المهندس المعماري الحديث ، ان تعدد الرموز الموجودة في بارك غويل ، كما ذكرنا سابقا مرتبط بالعلامات السياسية والدينية ، مع لمسة من الغموض وفقا لتفضيلات ذلك الوقت للألغاز والألغاز",
        en: "On the other hand, many experts have tried to link the park to various symbols because of the complex iconography Gaudí applied to the urban project. Such references move from political justification to religious glorification, passing through myth, history and philosophy. Specifically, many studies claim to see references to Freemasonry, despite the deep religious beliefs of both Gaudí and Count Güell, and these references have not been proven in modern architectural historiography. The multiplicity of symbols found in Park Güell, as mentioned earlier, is linked to political and religious signs, with a touch of mystery in line with the taste of that time for riddles and puzzles",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2894.jpg",
        cap_ar: "متحف Gaudi House في حديقة جويل ببرشلونة",
        cap_en: "The Gaudí House Museum in Park Güell in Barcelona",
      },
      {
        type: "P",
        ar: "كانت الحديقة في الأصل جزء من موقع اسكان غير ناجح تجاريا ، فكرة الكونت أوزيبي غويل ، الذي سميت الحديقة باسمه ، كانت مستوحاة من حركة جاردن سيتي الانجليزية ، ومن هنا جاء الاسم الانجليزي الأصلي منتزة ( بارك غويل ) كان الموقع عبارة عن تل صخري به القليل من النباتات وقليل من الأشجار ، يطلق عليه مونتانيا بيلادا ( الجبل العاري )",
        en: "The park was originally part of a commercially unsuccessful housing development, the idea of Count Eusebi Güell, after whom the park is named. It was inspired by the English Garden City movement, hence the original English name Park Güell. The site was a rocky hill with little vegetation and few trees, called Muntanya Pelada (the Bare Mountain)",
      },
      {
        type: "P",
        ar: "كان يضم بالفعل منزلا ريفيا كبيرا يسمى منزل لارارد أو منزل مونتانير دي دالت وكان بجوار حي من منازل الطبقة العليا يسمى لا سالوت ( الصحة ) ، كان القصد هو استغلال الهواء النقي ( بعيدا عن المصانع المدخنة ) والمناظر الجميلة من الموقع ، مع توفير ستين قطعة مثلثة للمنازل الفاخرة ، أضاف الكونت أوزيبي غويل الى هيبة التطوير من خلال الانتقال في عام 1906 للعيش في منزل لارارد ، في النهاية تم بناء منزلين فقط ولم يتم تصميم أي منهما بواسطة غويل ، كان من المفترض أن يكون أحدهما منزلا للعرض ، ولكن عند اكتماله في عام 1904 تم عرضه للبيع ، وبما أنه لم يتقدم أي مشترين ، قام غاودي ، بناء على اقتراح غويل ، بشرائه بمدخراته وانتقل للعيش مع أسرته ووالده في عام 1906",
        en: "It already contained a large country house called Casa Larrard or Casa Muntaner de Dalt, and it was next to a neighbourhood of upper-class houses called La Salut (Health). The intention was to exploit the fresh air (away from the smoky factories) and the beautiful views from the site, while providing sixty triangular plots for luxury houses. Count Eusebi Güell added to the prestige of the development by moving in 1906 to live in Casa Larrard. In the end only two houses were built, neither of them designed by Güell. One was meant to be a show house, but when it was completed in 1904 it was put up for sale, and since no buyers came forward, Gaudí, at Güell's suggestion, bought it with his savings and moved in with his family and his father in 1906",
      },
      {
        type: "P",
        ar: "تم بناء هذا المنزل الذي عاش فيه غاودي من عام 1906 الى عام 1926 ، على يد فرانسيسك بيرينغير في عام 1904 ، يحتوي على أعمال أصلية لغاودي والعديد من معاونيه ، هو الآن متحف منزل غاودي ( كاسا موسيو غاودي ) منذ عام 1963 ، في عام 1969 تم اعلانها معلما فنيا تاريخيا للمصلحة الوطنية",
        en: "This house, in which Gaudí lived from 1906 to 1926, was built by Francesc Berenguer in 1904. It contains original works by Gaudí and many of his collaborators, and it has been the Gaudí House Museum (Casa Museu Gaudí) since 1963. In 1969 it was declared a historic artistic monument of national interest",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2895.jpg",
        cap_ar: "سمندل موازييك متعدد الألوان من تصميم غاودي، المعروف باسم الدراك (التنين) ، عند المدخل الرئيسي، كما تم ترميمه بعد التخريب في شباط / فبراير 2007",
        cap_en: "A multicoloured mosaic salamander designed by Gaudí, known as el drac (the dragon), at the main entrance, as restored after the vandalism of February 2007",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2896.jpg",
        cap_ar: "فسيفساء غاودي على الشرفة الرئيسية بحديقة جويل ببرشلونة",
        cap_en: "Gaudí's mosaic on the main terrace of Park Güell in Barcelona",
      },
      {
        type: "H3",
        ar: "افضل الانشطة التي يمكن القيام بها في حديقة جويل ببرشلونة",
        en: "The best activities to do at Park Güell in Barcelona",
      },
      {
        type: "P",
        ar: "بانتظارك العديد من الأنشطة الشيقة ، ولكن ما ننصح بالبدء به هو أن تستهل نزهتك في هذه الحديقة بجولة تستكشف عن طريقها أجزاء الحديقة كافة وتمتع ناظريك بما يحيط بك من مشاهد جميلة ، كتلك الأشجار الكبيرة والمساحات الخضراء الرحبة ، وربما أنجذبت لرؤية ما تتباهى به الحديقة من منحوتات",
        en: "Many enjoyable activities await you, but what we advise starting with is to begin your outing in this park with a tour through which you explore all its parts and delight your eyes with the beautiful scenes around you, such as the large trees and the wide green spaces, and you may be drawn to see the sculptures the park takes pride in",
      },
      {
        type: "P",
        ar: "كما ستلاحظ خلال التجول وجود العديد من المقاعد المخصصة للجلوس ، باستطاعتك اللجوء لها في أي وقت تريد",
        en: "As you stroll you will also notice many benches for sitting, which you can turn to whenever you wish",
      },
      {
        type: "P",
        ar: "ومع الاطلالة الرائعة التي تنفرد بها هذه الحديقة على مدينة برشلونة ، سيكون عليك استقطاع بعض الوقت الملائم للاستمتاع بهذه الاطلالة ، ونوصي أيضا بالتوجه الى منصة المشاهدة الموجودة في الحديقة والتي تدهش زائريها بما تقدمه من اطلالات ساحرة على مدينة برشلونة",
        en: "And with the wonderful view over the city of Barcelona that is unique to this park, you will have to set aside some suitable time to enjoy that view, and we also recommend heading to the viewing platform in the park, which amazes its visitors with the charming views it offers over the city of Barcelona",
      },
      {
        type: "P",
        ar: "وبالتأكيد أن أجواء حديقة جويل في برشلونة الساحرة ، سوف تمنحك طاقة اضافية لتأدية بعض الأنشطة الرياضية التي ستجدها ممتعة للغاية مثل المشي في مسارات المشي المتاحة في الحديقة ، أو ربما أردت ممارسة بعض التمارين الرياضية باستخدام الأجهزة الرياضية المجانية المتوفرة",
        en: "And certainly the charming atmosphere of Park Güell in Barcelona will give you extra energy to do some sporting activities that you will find very enjoyable, such as walking along the walking trails available in the park, or perhaps you would like to exercise using the free sports equipment provided",
      },
      {
        type: "P",
        ar: "بالاضافة الى ما سبق توفر حديقة جويل في برشلونة العديد من الأنشطة الأخرى التي قد تود تجربتها مثل زيارة كاسا ديل غواردا ، زيارة متحف غاودي هاوس و زيارة المسرح اليوناني",
        en: "In addition to the above, Park Güell in Barcelona offers many other activities you might like to try, such as visiting the Casa del Guarda, visiting the Gaudí House Museum, and visiting the Greek Theatre",
      },
      {
        type: "IMG",
        src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/09/img_2897.jpg",
        cap_ar: "صورة عامة لحديقة جويل ببرشلونة",
        cap_en: "A general view of Park Güell in Barcelona",
      },
      {
        type: "H3",
        ar: "المزيد من المعرفة عن حديقة جويل ببرشلونة",
        en: "More to know about Park Güell in Barcelona",
      },
      {
        type: "P",
        ar: "هذه الحديقة مستمدة من حركة الحدائق الانجليزية ، وقد بني عليه بعد ذلك في نفس المنطقة منزل ريفي أطلق عليه دار مونتانير دو دالت",
        en: "This park draws on the English garden movement, and afterwards a country house called Casa Muntaner de Dalt was built on it in the same area",
      },
      {
        type: "P",
        ar: "حيث أنه قد كان مبنيا بالقرب من منازل الطبقة العليا ، والتي تعرف باسم منطقة لا سالوت ، حيث حينها كان الهدف هو الاستفادة من المناظر الجميلة التي يتمتع بها الموقع",
        en: "As it was built near the upper-class houses known as the La Salut area, where at the time the aim was to benefit from the beautiful views the site enjoys",
      },
      {
        type: "P",
        ar: "ومن ثم قد أطلق المهندس المعماري الفنان غاودي العنان لخياله أثناء محاولته لتصميم هذا المكان الرائع ، وأول ما بدأ قد حافظ على تلك المناظر الطبيعية الخلابة الموجودة بالفعل",
        en: "Then the architect and artist Gaudí let his imagination run free as he tried to design this wonderful place, and the first thing he did was to preserve the stunning natural scenery already there",
      },
      {
        type: "P",
        ar: "قام أيضا بعمل ربط بينها وبين اقامة فضاء أصيل كبير يتكامل ويتناسق مع الطبيعة ويستنسخها ، ومن ضمن فنياته في انشاء هذه الحديقة أنه عمل على انشاء الأعمدة والممرات ذات الطابع الجمالي المعماري الرائع ، ثم قام بمحاولة انشاء منطقة تكون هي رمز الى الكتالونيا والمسيحية في مثل هذه الحدائق المسماة بحدائق جيل",
        en: "He also linked it with the creation of a large authentic space that integrates and harmonises with nature and reproduces it. Among his techniques in creating this park, he worked on creating columns and walkways with a wonderful architectural and aesthetic character, then he tried to create an area that would be a symbol of Catalonia and of Christianity in these gardens called Park Güell",
      },
      {
        type: "P",
        ar: "لذا تعد بارك جيل the park güell Barcelona عبارة عن حدائق في المقام الأول ، يوجد فيها درج جميل لتزيين البوابة ، ويوجد أيضا في وسطها عدة جزر بها نفورات وهي مصممة معماريا بطريقة جميلة وأيضا ترمز الى العديد من الأشياء المتفقة مع الثقافة الكتالونية",
        en: "So Park Güell Barcelona is first and foremost a garden. It has a beautiful staircase decorating the gateway, and in its middle there are several islands with fountains, architecturally designed in a beautiful way and also symbolising many things consistent with Catalan culture",
      },
      {
        type: "P",
        ar: "اما عن الشرفة الرئيسية فهنا نأتي الى نقطة هامة ومحورية في حديقة جويل برشلونة هي مكان الشرفة الرئيسية ، والتي نجدها في شكلها الجميل يحيط بها مقعد طويل له هيئة ثعبان بحري حيث أن منحنيات هذا المقعد الثعباني الشكل هي عبارة عن عدد من الجيوب صنعت ونحتت من أجل خلق جو اجتماعي ، حاول غاودي أيضا استعمال العديد من الزخارف الكتالونية الرائعة واستخدام عدد من الرموز الدينية ، وأيضا وضع فيها الشعر القديم ضمن أعمال الزخرفة",
        en: "As for the main terrace, here we come to an important and central point in Park Güell in Barcelona: the place of the main terrace, which we find in its beautiful form surrounded by a long bench shaped like a sea serpent, since the curves of this serpentine bench form a number of pockets made and carved in order to create a social atmosphere. Gaudí also tried to use many wonderful Catalan ornaments and a number of religious symbols, and he also placed old poetry within the decorative work",
      },
      {
        type: "H3",
        ar: "اسعار تذاكر حديقة جويل ببرشلونة",
        en: "Ticket prices for Park Güell in Barcelona",
      },
      {
        type: "P",
        ar: "تختلف رسوم دخول حديقة غويل في برشلونة حسب السن ، وتنقسم الرسوم الى فئتين ، الفئة الأولى فئة البالغين ، وتبلغ الرسوم 8 يورو ، أما الفئة الثانية فهي فئة الأطفال والمحدد بسن من 7-12 سنة ، وتبلغ الأسعار لهذه الفئة 5 يورو",
        en: "Entry fees for Park Güell in Barcelona differ by age, and the fees are divided into two categories: the first is the adults category, where the fee is 8 euros, and the second is the children category, set for ages 7-12, where the price for this category is 5 euros",
      },
    ],
  },
];
