export const SPAIN_EN_4: Record<string, { title: string; values: string[] }> = {
  marbella: {
    title: "Discover everything about the enchanting city of Marbella",
    values: [
      "",
      "Discover Spain",
      "Discover everything about the enchanting city of Marbella",
      "Have a holiday coming up? Then let's spend it in Marbella!",
      "Marbella offers an unrivalled tourist experience: sixteen golf courses, four marinas, twenty-five beaches, about twenty thalassotherapy centres, and countless resorts, along with an old town built in the Andalusian style and festivals held all year round. It is also home to some of the most luxurious yachts in the world, restaurants with top-quality cuisine, and extremely fashionable shops.",
      "",
      "There is no doubt…",
      "…that the city of Marbella has grown from a small town into a world-class city at remarkable speed. Over the years it has earned a reputation as a playground for the wealthy and famous; today Marbella is a modern residential city as well as one of Europe's leading luxury resort destinations.",
      "Marbella enjoys the best climate in Western Europe",
      "Located in the most southerly part of Europe, Marbella is shielded from Atlantic winds by the Bay of Gibraltar and also protected from northerly winds by the Sierra Blanca mountains. This makes Marbella warmer than other parts of Spain in winter and cooler than other parts of Spain in summer; it enjoys more than 320 sunny days a year.",
      "Marbella offers Western European standards",
      "Marbella boasts an extremely high standard of living that rivals any other European city: shops carrying international brands, trendy boutiques, high-quality service, modern hospitals and highways, international schools, theatres, museums, cultural clubs, and fast internet connections along with technology and communications, among other things. As a result, many people move to Marbella to live permanently and continue running their businesses online, while others relocate to Marbella to start a business there or begin a new venture, so today they live on the Costa del Sol enjoying a uniquely distinctive way of life.",
      "Turning free time into personal benefit",
      "Aside from the climate, Marbella has one of the best and largest selections of golf courses in Europe, as well as marinas, tennis courts, sports halls, horse-riding centres, hunting, tennis, fishing, football, basketball, cycling, hiking, mountain climbing, skiing, motorcycling and motor racing — these are just some of the many activities available on the Costa del Sol, along with amusement parks, safari parks, zoos, aquariums, bowling alleys and cinemas, all catering to the needs of young people and every member of the community.",
      "Marbella offers elegant restaurants",
      "On top of all this, the city offers a large, varied and excellent selection of elegant restaurants serving every kind of cuisine from around the world. Then there is the vibrant nightlife: bars, piano bars, dance clubs, trendy nightclubs and private parties, which will keep you up until the early hours.",
      "The history of Marbella",
      "For those who prefer history…",
      "…Marbella's rich past bears witness to its former glory; its history dates back to the third century BC, when it was originally an agricultural settlement. Its strategic location on the Via Augusta made it an important trading city.",
      "Ten things you should know before heading to Marbella",
      "The wonderful city of Marbella is…",
      "…a coastal area on the Mediterranean shore, centred within the province of Málaga in southern Spain. It is known worldwide for its stunning resorts on the Costa del Sol, the stretch of coastline in the Andalusian region famed for its enchanting beaches. This area is also known for its splendid views of Gibraltar, Morocco and Africa in general.",
      "1 - Marbella, Málaga and Andalusia are stunning filming locations",
      "Marbella has long captured the hearts and minds of filmmakers and TV producers. It is a sunny, bright place all year round, which makes filmmakers choose it to produce their work. Among the most recent series filmed there is the Spanish series Toy Boy, inspired by the atmosphere of the bustling nightclubs on the Costa del Sol. This series offers a unique blend of dance performances and mafia storylines rooted deep in a handful of characters' lives. Produced by Netflix, it lets you get to know Marbella better, especially its beautiful marina, and the unfolding events may even help you pick up Spanish quickly.",
      "In general, Andalusia as a whole has appeared in several films and series such as Star Wars: Attack of the Clones, as well as Indiana Jones and the Last Crusade. With all this trivia for film and TV lovers in mind, Marbella comes as a pleasant surprise, turning your own holiday into your very own movie.",
      "",
      "2 - Large numbers of expatriates settle in Marbella",
      "Nearly 300,000 British nationals live in Marbella, while 2.5 million English visitors come every year. There are, of course, also large numbers of European tourists, especially Germans and Scandinavians.",
      "However, there are also many Arab, Russian and Chinese people of wealth who have bought very luxurious homes there. These are, naturally, the owners of the lavish yachts that serve as floating luxury villages, as well as the owners of the fantastical cars, as if you were in a science-fiction film.",
      "As for you, if you are an ordinary tourist, don't let that put you off or stop you from going, because you can enjoy the beauty of Marbella's stunning beaches without needing to spend huge sums of money, or even any money at all in some cases.",
      "3 - Celebrity homes and golf courses",
      "A host of stars and celebrities live in Marbella, among them James Hewitt, Rod Stewart and Simon Cowell — but don't worry, the latter is not here to judge your performance!",
      "Accordingly, in order to satisfy the refined taste of the wealthy and famous, numerous impeccably maintained golf courses have been built. These vast green spaces are hard to miss while driving around the Costa del Sol.",
      "4 - An Arab touch carved by European hands",
      "It is well known that southern Spain was once under Andalusian rule, so there are very visible Arab touches and an Eastern culture pervading some areas, since Islamic rule lasted for a period from around 700 AD to 1400 AD, and it was the Amazigh, or Berbers, who spread their culture across the region.",
      "As a result, many buildings feature Arab-Berber architecture, a wonderful blend of building styles, and many streets still echo with the resonance of the past and the fragrance of history. What is perhaps most distinctive about this is that today it has taken on a European form tinged with an Eastern character — something unique that is not found in many countries around the world.",
      "",
      "5 - The Golden Mile, the pinnacle of luxury and opulence",
      "We are now certain that Marbella is a hub of wealth and riches, as shown by the homes and properties of the affluent, but the Golden Mile is an entirely new dimension of luxury living. It is hard to believe what the eye sees, given the sheer number of astonishing sights — it feels more like fantasy than reality. It begins at Puerto Banús and stretches for more than a mile, all of it stunningly beautiful, so much so that you feel as though you are in the resorts and palaces of the turquoise Caribbean islands, only here everything is on a much grander scale.",
      "",
      "6 - Puerto Banús facilities, south-west of Marbella",
      "Opened in 1970, it is home to numerous upscale restaurants and bars, of course in the marina. You will no longer be surprised to find legendary yachts overlooking chic boutiques such as Gucci and Fendi. If you are in the mood for shopping, we recommend setting aside a budget of a few thousand euros, or you can simply walk and enjoy gazing at the shop windows, after which you can head to the sea to relax after mulling over the eye-watering prices that astonished you during your stroll.",
      "At this point an important question will occur to you: so why come here at all? Well, if you are planning to one day become a member of this elite club of the wealthy, you will find this a very exciting opportunity. Alternatively, if you simply wish to be close to the joy and witness the pursuit of a good life, this too is an opportunity not to be underestimated. In fact, you will be surrounded by elegant people and houses that will be a source of inspiration for you. Moreover, there is a wonderful nightlife with music and special shows, as well as many amazing culinary experiences and various forms of entertainment awaiting you.",
      "7 - Ideal sunny weather all year round and the Ascari club",
      "With nearly 300 days of clear sunshine, no one could turn down such a wonderful offer! Indeed, it is the true power of sun therapy that really comes into its own in Marbella. Moreover, alongside the sunshine come the motor races: the Ascari racing club, filled with the wonders of Formula One, is a true adrenaline rush for motorsport enthusiasts, giving a perfect balance after long stretches of relaxation in Marbella, on the Costa del Sol.",
      "",
      "8 - Mountain backdrops all along the coast",
      "On a clear day, you can see three countries at once: Gibraltar, Morocco, and of course Spain. Well, technically, you are in Spain, but you will still have views of the sea in front of you while Spain lies behind you.",
      "Try to fully live the experience of literally standing between the continents of Europe and Africa. Moreover, history and the present day meet together in Marbella, making it a truly magical place.",
      "",
      "9 - The old town",
      "You can discover the authentic part of Marbella. Many tourists come to this place solely to enjoy the beach, so they may end up repeating the same activities every day, thereby missing the chance to discover new things and thus losing the very essence of travel.",
      "Avoid this by all means, because the old town is very close to the main street opposite Alameda Park. Needless to say, this will open up a whole new dimension to your trip. Just try the southern European way of relaxed living, then sip a cup of coffee while enjoying watching people walk by.",
      "Everything feels better there, as life is almost carefree; well, the same applies to Marbella — just let the scenery melt and blend with your feelings.",
      "",
      "10 - Fresh, healthy food",
      "Sunshine, seafood, fresh vegetables and fruit are true immunity boosters — don't you think so? Try the traditional paella dishes, made mainly from seafood and rice, and also try Pulpo, the octopus dish prepared to perfection.",
      "Also, replenish your vitamins and strengthen your essential minerals with some of the fresh vegetables and fruit from this region, which are, of course, extremely organic and healthy produce.",
      "",
    ],
  },
  villajoyosa: {
    title: "Discover the best things to do in Villajoyosa",
    values: [
      "",
      "Discover Spain",
      "Discover the best things to do in Villajoyosa",
      "Best Of Villajoyosa",
      "Villajoyosa is a charming coastal city…",
      "…located on the Mediterranean, specifically on the Costa Blanca in Spain. This hidden gem is known locally as La Vila Joiosa (meaning 'the joyful town') or simply La Vila. It lies 32 km north of Alicante and just below the famous resort of Benidorm. It is well worth a visit, if only to experience how different the atmosphere is compared to the nearby, bustling Benidorm.",
      "",
      "Villajoyosa is a relaxed coastal town…",
      "…for the working class, with a population of around 34,000, most of them Spanish. The town has managed to preserve the authenticity of a traditional fishing village, having received fewer tourists than most other coastal resorts in the Marina Baixa area. The town sits along a long stretch of white sandy beach and offers a fishing harbour, delicious seafront restaurants, a lovely beach promenade, and a maze of small narrow streets. The city's main economic focus is on chocolate production and tourism.",
      "",
      "The history of Villajoyosa",
      "The first settlements date back…",
      "…in Villajoyosa to the Bronze Age. In the Roman era, the city of Allon was founded. It is not entirely clear exactly where the city of Allon stood in relation to the current town, but it is believed it may have been located where the old town now stands. There is some evidence from the discovery of remains of hot springs and a military settlement along the Amadorio riverbed.",
      "The area was largely abandoned…",
      "…during the Middle Ages; however, in 1300, Bernat de Sarrià, admiral to King James II of Aragon, founded the Christian town of La Vila Joiosa on this site as a strategic point for defending against attacks by Muslims from the sea. Villajoyosa then went on to play an important role during the sixteenth century in confronting numerous pirate attacks along the Alicante coast. For this reason King Philip II ordered the construction of a defensive wall, which was completed in the middle of the century; parts of these walls can still be seen today in the old town. Villajoyosa officially became a city in 1911, a status granted by King Alfonso XIII.",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "What to do in Villajoyosa?",
      "You'll be amazed by the colourful houses…",
      "The main attraction in Villajoyosa is its famous multicoloured painted houses in the old town. The fishermen's houses are beautifully painted in every colour of the rainbow, giving the old town a bright, cheerful look. There are various reasons said to explain why fishermen painted the fronts of their houses in such bright colours, but no one seems to know the true version. One story, however, is that since each fisherman painted his boat a particular colour, they used the leftover paint on the fronts of their houses. A more romantic version is that after being at sea for a while, fishermen would recognise their houses from a distance out at sea by their colour.",
      "Whatever the story, the beauty is that these charmingly painted houses remain almost perfectly preserved to this day, making Villajoyosa one of the most picturesque and colourful towns along the Spanish coast.",
      "",
      "You'll get lost in the narrow streets…",
      "The old town of Villajoyosa is surrounded by remnants of sixteenth-century defensive walls, and walking through the maze of narrow streets among the colourful houses and lovely squares will reveal a beautiful side of La Vila to you. Just outside the defensive walls, right next to the Amadorio riverbed, one can see the hanging balconies of the old houses.",
      "",
      "The western, or Ponent, defensive wall is adorned with the colourful hanging balconies of the old houses and overlooks the Amadorio riverbed. The best vantage point to admire these Casas Colgantes, or hanging houses, is from Puente Río Amadorio, the bridge over the Amadorio River on Avenida de País Valencia. It is best to explore the Levante defensive wall while heading down the main road towards the sea via Carrer Costera de la Mar.",
      "",
      "Enjoy its beaches…",
      "Villajoyosa enjoys a mild Mediterranean climate with plenty of sunshine almost all year round. Such excellent weather conditions make visiting the beach even in winter very appealing. Villajoyosa is home to various beaches that never become crowded, aside from a few weeks in midsummer when Spanish holidaymakers flock from inland cities to the coast.",
      "",
      "The main beach in Villajoyosa is Playa Centro. This golden sandy beach stretches for more than 1,300 metres along the town's seafront up to the colourful houses of the old town, and shade can be found among the various palm trees lining the shore. There are also many bars and restaurants along this blue-flag beach promenade.",
      "In addition to the southern and northern parts of the town, several other small, unspoiled beaches can be found, some of them hidden among rocky outcrops. One noteworthy beach is Racó del Conill. This official nudist beach lies to the north of Villajoyosa and is small and secluded. The road to reach this beach is very narrow, so take care, but the view from above just before reaching this beach makes the trip worthwhile. However, you may not visit the beach itself while dressed, as nudity is required.",
      "",
      "The main seafront has a lovely promenade that stretches from the harbour all the way to the old town, extending just over 1.2 km. Along the seafront there are plenty of bars and restaurants for enjoying refreshments, some Spanish tapas, or a dinner of delicious Spanish food.",
      "Stroll through the park along the Amadorio riverbed…",
      "The park in the bed of the Amadorio River opened in 2010, and it is a true oasis. For most of the year the riverbed is dry, but when we visited there was a little water. It also has a playground and some exercise equipment. Looking up from the riverbed, you will see the colourful hanging houses built on the defensive walls of the old town, and further down the riverbed, you will have a good view of the bridge linking the old part of the town with the new.",
      "",
      "Visit the Valor Chocolate Museum…",
      "Belgium is famous for chocolate, so why would a Belgian visit a chocolate factory in Spain? Well, the reason is that Villajoyosa has a rich history of chocolate production, and the town is currently famous for its three chocolate factories. The museum tells the history of how chocolate was brought to Europe, as well as the history of Valor chocolate. The company was founded in 1881 and still belongs to the same family, which has been making chocolate ever since.",
      "",
      "The museum also shows the development of the production process and the machinery used from the beginning up to recent times. For chocolate lovers, it will be very hard to leave the shop without buying some delicious chocolate; we even decided to try the 99% chocolate. With this chocolate, you can make your own authentic Spanish hot chocolate, which is perfect to enjoy alongside some delicious churros.",
      "",
      "The visit is free and there are at least 14 tours a day, in both English and Spanish. More information about the schedule and timings can be found on their website. Aside from the Valor museum, which is the largest and most famous, there are two other chocolate museums in town: Chocolates Pérez and Chocolates Clavileño.",
      "Festival of the Moors and Christians",
      "Every year, in the last week of July, the fiestas de Moros y Cristianos are held in Villajoyosa. It commemorates the Christian victory over the Muslim conquerors who attacked with a fleet in 1538. The Moorish-facing Christians awaited on the beach and, with support from neighbouring towns, repelled the attack. What makes this celebration so unique is the landing on the town's beach, along with fireworks, music and processions.",
      "Practical information for visiting Villajoyosa",
      "Best time to visit Villajoyosa?",
      "Given the mild climate with little rainfall, Villajoyosa is a year-round destination; however, it can be hot in the middle of summer during August, and during winter from late November to March, temperatures drop along with sea temperatures, though they never come close to freezing. So the best season to visit is during spring and autumn, when there are fewer people and temperatures are comfortable, allowing you to enjoy some mild, uncrowded beach time.",
      "How to get to Villajoyosa?",
      "Villajoyosa is located in the autonomous community of Valencia, or the Valencian Community, in the province of Alicante on the eastern coast of Spain. The nearest major city is Alicante, just 32 km south of Villajoyosa, and Alicante International Airport is 50 km away, mostly via full motorway. Benidorm lies about 12 km to the north, Calpe 35 km away, and Dénia 60 km away, from where some ferries depart to Mallorca and Ibiza.",
      "When visiting by car, follow the AP-7 or the smaller N-332, whether from Benidorm, Calpe or Dénia in the north, or from Alicante in the south. From both Benidorm and Alicante, Villajoyosa can also be reached by tram.",
      "The city's location on the map",
      "",
    ],
  },
  "canary-islands": {
    title: "Discover everything about the enchanting Canary Islands",
    values: [
      "",
      "Discover Spain",
      "Discover everything about the enchanting Canary Islands",
      "Let's begin a journey of imagination together",
      "On this page you will learn about the following:",
      "The Canary Islands in general",
      "Reasons to travel to the Canary Islands",
      "The naming of the Canary Islands",
      "The geography of the Canary Islands",
      "The history of the Canary Islands",
      "Historical monuments in the Canary Islands",
      "The modern history of the Canary Islands",
      "Population patterns in the Canary Islands",
      "The climate of the Canary Islands",
      "The economy of the Canary Islands",
      "Animals in the Canary Islands",
      "The Canary Islands, or Islas Canarias, also known as the Fortunate Isles, the Isles of the Blessed, or the Isles of Happiness, or Qanaria, are an archipelago belonging to Spain in the Atlantic Ocean, one of Spain's seventeen autonomous communities. The region is divided into two provinces: Santa Cruz de Tenerife and Las Palmas.",
      "The Canary Islands in general",
      "The Canary Islands, south of the Iberian Peninsula and of volcanic origin, enjoy an ideal climate marked by a mild winter and a summer without excessive heat, offering incredible holidays in any season. They are connected by international airports and are said to be like a miniature continent thanks to the variety of landscapes and climates. They consist of 8 islands, namely:",
      "Gran Canaria",
      "Tenerife",
      "Fuerteventura",
      "Lanzarote",
      "La Palma",
      "La Gomera",
      "El Hierro",
      "La Graciosa",
      "Their breathtaking scenery and unique corners make these islands a very romantic destination for couples to enjoy. Among the most striking natural areas are the volcanic landscapes of Lanzarote, the sand-dune beaches of Fuerteventura and Gran Canaria, the green forests of La Palma and La Gomera, or Mount Teide in Tenerife, the highest peak in Spain.",
      "Opportunities for sporting activities such as surfing, diving, hiking and so on are extremely varied. For swimming you will find pristine beaches and black sand, as well as natural pools; many choose to explore the coast aboard a sailboat or take a boat trip. It is also one of the best places in the world for stargazing.",
      "You will also find other suggestions of interest for discovering the beautiful city of San Cristóbal de La Laguna (Tenerife), listed as a World Heritage site, or the works of the artist César Manrique in Lanzarote.",
      "Reasons to travel to the Canary Islands",
      "National parks",
      "The Canaries are one of the most biodiverse regions in the world. Five of the islands have been designated nature reserves, and there are four national parks, namely:",
      "Teide National Park (Tenerife)",
      "Caldera de Taburiente (La Palma)",
      "Timanfaya (Lanzarote)",
      "Garajonay (La Gomera)",
      "Numerous carnivals",
      "These traditional celebrations take place in February, the most famous being that of Santa Cruz de Tenerife.",
      "Family entertainment programmes",
      "There are several tourist programmes for families, such as camel rides, whale-watching trips, and numerous water parks and zoos, including Siam Park and Loro Parque (in Tenerife).",
      "The naming of the Canary Islands",
      "The name of the Canary Islands is derived from the Latin name Canariae Insulae, meaning 'Islands of the Dogs', a name given to the largest island, Gran Canaria. According to the historian Pliny the Elder, King Juba II of Mauretania named the island Canaria because of the presence of large numbers of dogs of great size.",
      "There is another theory that what were called dogs were actually a type of monk seal, or sea dog, since the Latin name for the sea dog is canis marinus, and sea dogs were endangered and no longer exist in the Canary Islands.",
      "There is an alternative account stating that the islands' original inhabitants, the Guanches, revered dogs, mummified them, and treated them as sacred animals. What is certain is that the name of these islands was not derived, as is commonly believed, from the name of the canary bird; rather, it was the opposite — the bird was named after the islands. As for the Arabic name 'the Isles of the Blessed' (Jazur al-Khalidat), Qudama ibn Ja'far mentioned in his book al-Kharaj that the reason for the name is that fruits, grains and flowers grow on the islands by themselves without cultivation.",
      "The geography of the Canary Islands",
      "The Canary Islands consist essentially of four major main islands, surrounded by scattered smaller islands, namely Tenerife, Gran Canaria, Lanzarote and La Palma. Although the capital, Santa Cruz de Tenerife, is located on the island of Tenerife, which covers an area of 2,034.38 square kilometres and has a population of 833,000, it is the largest island in the Canaries and among Spain's islands in terms of population.",
      "These islands consist of several small villages, some of which have turned into towns thanks to the spread of tourist resorts along their coastlines, which have become a destination for both foreign and domestic tourism thanks to their permanently mild temperatures year-round, ranging between 20 and 25 degrees Celsius.",
      "The islands as a whole are volcanic in nature, with peaks surrounded by rocky beaches. The highest peak in the archipelago is Mount Teide (3,718 m) in Tenerife. The Canary Islands cover an area of 7,447 km² (the thirteenth largest region by area in Spain).",
      "The history of the Canary Islands",
      "In the fourteenth century the scholar Ibn Khaldun spoke of the islands within the geography chapter of his book al-Muqaddimah, under the First Region: to its west lie the Isles of the Blessed, from which Ptolemy began measuring the lengths of countries; they do not fall within the extent of the region but rather lie in the surrounding ocean, in numerous islands, the largest and most famous of which are three, said to be inhabited.",
      "He also described the islands' original inhabitants as follows: it has reached us that ships of the Franks passed by them in the middle of this century and fought them, taking spoils and captives, selling some of their captives on the coasts of the far Maghreb, and they entered the service of the Sultan. When they learned the Arabic tongue, they told of the state of their islands, saying that they dig the earth for farming with horns, that iron is not found in their land, that their food is barley and their livestock are goats, that they fight with stones which they hurl backwards, and that their worship is prostration to the sun when it rises; they know no religion, no call to faith has reached them, and the location of these islands can only be found by chance, not by intent.",
      "The islands played a major role during the voyage undertaken by Christopher Columbus to discover Latin America, because his four ships, carrying him and his companions, set out from the port of Cádiz in southern Spain and stopped at the Canary Islands to take on the necessary supplies, from where subsequent voyages of discovery set out, making them an obligatory route for those heading to the lands of the New World.",
      "Perhaps for this reason we find that most of the inhabitants of those islands have family ties to Spaniards residing in many Latin American countries, particularly Cuba, whose relationship with the Canary Islands amounts to a kind of deep, organic bond linking the two together, even in the way of pronouncing the Castilian language, which is the language of the Spanish-speaking world.",
      "Historical monuments in the Canary Islands",
      "In addition to the traces left by the ships that accompanied Christopher Columbus on his historic voyage to discover the New World in 1492, which are now gathered in an archaeological museum commemorating the voyages of discovery, a museum has been set up on the site of the house where the famous explorer stayed during his time on the island, containing some of the tools Columbus used during his first voyage, in addition to other artefacts related to the New World after its discovery.",
      "The modern history of the Canary Islands",
      "In modern times the Canary Islands have witnessed several riots and movements calling for the independence of the Canary Islands. The Canary Islands Independence Movement, also known as the Movement for the Self-determination and Independence of the Canary Archipelago, is an independence movement that no longer exists. It once had a radio station based in Algiers and resorted to violence in attempts to force the Spanish government to establish an independent state for it in the Canary Islands.",
      "The Canary Islands Independence Movement was founded by Antonio Cubillo in 1964, with its headquarters in Algiers. It was recognised as the Movement for the Self-determination and Independence of the Canary Archipelago in 1968 by the Organisation of African Unity. Its armed struggle was carried out by its military wing, the Armed Guanche Forces, an armed terrorist movement that targeted the citizens of the Canary Islands and which bombed a shopping centre in Las Palmas de Gran Canaria in 1976, killing countless residents of the Canary Islands. In 1978, Antonio Cubillo was the victim of an attempt on his life in Algiers carried out by the Spanish secret services, which left him disabled.",
      "The movement's radio broadcasts called for the Canarian people to return to their roots and attempted to promote the use of the Amazigh language, but its efforts largely failed to achieve any success, because the Canarian people were opposed to the violence and terrorism the movement pursued on the one hand, and rejected Amazigh identity, since their origin is Andalusian with Arab roots, on the other.",
      "As a result, the movement's membership never exceeded 100 people at its peak; nevertheless, the movement's flag became extremely famous and was adopted, without stars, by the pre-autonomy government. The movement halted its activity after the Spanish government established an autonomous region for the Canary archipelago in 1982, after which Antonio Cubillo was granted a royal pardon and returned to Spain.",
      "Population patterns in the Canary Islands",
      "Its original inhabitants are the Guanches, of Amazigh origin, and the majority of the Canary Islands' population belong to the Catholic Christian faith. There are also other Christian communities such as Protestants, most of whom were born abroad, especially in Northern Europe, in addition to the Church of Jesus Christ of Latter-day Saints.",
      "Other religions on the islands are Islam, Buddhism, Judaism and the Baháʼí Faith. Two Catholic saints were born in the Canary Islands: Pedro de Betancur and José de Anchieta (missionaries in Guatemala and Brazil respectively). The main religious festival of the Canary Islands is the pilgrimage to the Basilica de Candelaria in Tenerife, where people come to celebrate the feast of the Virgin Mary (mother of Jesus), who is regarded on the island, as Our Lady of Candelaria, as the patron saint of the Canary Islands. In the archipelago there is also the Islamic Federation of the Canary Islands.",
      "The climate of the Canary Islands",
      "Its climate is mild, with rain typically falling in winter. Temperatures remain constant throughout the year, and dry African winds blow over it, affecting the southern beaches of Gran Canaria and Tenerife, which has helped the growth of plants typical of North African regions there, such as palm trees, fig trees, cacti, laurel and eucalyptus.",
      "The economy of the Canary Islands",
      "The economy of the Canary Islands relies on agriculture, fishing and tourism, which form an important resource, as the Canary Islands are considered a distinguished tourist destination in both summer and winter, as well as an ideal place for astronomical observation, with an observatory established at an altitude of 2,432 metres on the island of La Palma, home to some of the most important observatories in the world. They also export various agricultural products such as fruits (bananas, citrus, peaches, figs and grapes) and vegetables (tomatoes, onions and potatoes) as well as sugar cane and grains, with most of the production exported to Spain and European Union countries. The textile and food industries also form the basis of the islands' industrial sector.",
      "Animals in the Canary Islands",
      "The famous, beautifully singing canary birds are native to the Canary Islands and took their name from the islands, as European explorers brought them to Europe and bred them in cages, popularising varieties that had not previously existed, especially among the British.",
    ],
  },
};
