export const SPAIN_EN_2: Record<string, { title: string; values: string[] }> = {
  cordoba: {
    title: "Córdoba — the city of flowers",
    values: [
      "Discover Spain",
      "Córdoba .. The City Of Flowers",
      "Let's go travel to Córdoba!",
      "Córdoba is famous throughout the world for its Great Mosque; its historic old town is a World Heritage Site, full of small streets waiting to be explored, courtyards filled with roses, charming squares and lively bars, where you can enjoy a good flamenco performance or try the local cuisine",
      "The scent of jasmine and orange blossom is always present in spring at its very best, especially in May, which is the month of many traditional festivals in Córdoba",
      "Four cultures and a lot of life",
      "The Great Mosque, the Alcázar de los Reyes Cristianos, the synagogue, and the Roman bridge are the main examples of Córdoba's old quarter",
      "The city reflects its Roman past …",
      "and the coexistence of Christian, Islamic and Jewish cultures throughout its history. Recommended sights include the Jewish quarter, the Calahorra Tower, the Roman theatre, the Caballerizas Reales, and the Plaza de la Corredera. A good way to explore the city is to take a guided tour of the sights, or to follow one of the themed routes suggested at the tourist offices, including Roman Córdoba, the Caliphate route, or the Fernandine route. Just 10 kilometres from the city, with direct bus routes to it, lies the largest archaeological site in Spain, Madinat al-Zahra, the ruins of the former capital of the caliphate, which has been a World Heritage Site since 2018",
      "The city's charm is not limited …",
      "to its main landmarks; take a stroll to discover the maze of narrow streets (make sure to see Callejón de las Flores and Calleja de la Luna) and the squares, fountains and courtyards decorated with roses. In fact, Córdoba's main festivities focus on these spaces",
      "Varied celebrations …",
      "The Patio Festival, a World Heritage event, is famous, but in May the city also celebrates the May Crosses, the Battle of the Flowers, and the balcony and wall competition, when the city is filled with roses, there are open-air flamenco shows, and a festive atmosphere fills the streets. The month ends with the Córdoba Fair",
      "Delights made in Córdoba",
      "Going out for tapas …",
      "and trying traditional dishes of the local cuisine, discovering the art of horsemanship, enjoying a flamenco show in a tablao, or relaxing in an Arab bath — all are special experiences in Córdoba",
      "The most famous areas for tapas are the historic quarter and the neighbourhoods of San Lorenzo, San Andrés and Santa Marina. Be sure to try local specialities such as salmorejo (cold tomato soup), flamenquines (fried pork rolls in breadcrumbs), aubergine with honey, mazamorra (cold almond soup), Iberian ham from Los Pedroches, cheese from Zuheros, and wine from Montilla-Moriles",
      "You can enjoy …",
      "horsemanship and Andalusian horse culture all year round with shows at the Caballerizas Reales, while in the historic city centre there are many tablaos with regular flamenco music and dance performances",
      "A traditional bath …",
      "Finally, you can relax in a modern traditional bath at the Arab baths in the Jewish quarter, or by booking an Al-Andalus experience at the Córdoba tourist office",
      "Facts about Córdoba",
      "Córdoba, a city and a capital ..",
      "The province of Córdoba belongs to the Andalusia region in southern Spain and lies on the bank of the Guadalquivir river. It has a population of about 400,000. It was famous during the Islamic rule of Spain, and many Arab historians mentioned it in their writings, among them Yaqut al-Hamawi. Córdoba, under the Umayyad Abd al-Rahman III, was the capital of the state of al-Andalus, and a walker could see by the light of its lamps from ten miles away. Its population reached about one million at that time, while the largest city in Europe then had no more than a quarter of a million inhabitants",
      "The number of Córdoba's baths …",
      "public baths, along with their facilities and houses, was about 283,000, and it had 80,000 palaces, and it had 170 women who all copied out Qurans in Kufic script. The city contained 50 hospitals, and it had 600 mosques, the most important of which was the Great Mosque of Córdoba, which had no equal or parallel in splendour, ornamentation, and magnificence of construction at that time",
      "Origin of the name",
      "Based on the information …",
      "given by Yaqut al-Hamawi about the origin of the city of Córdoba, the origin of the word Córdoba goes back to two sources, one a foreign Roman one and the other Arabic. As for the meaning of the word in Arabic, it refers to a fierce enemy, and an Arabic verse of poetry mentions the word: 'When he saw me, he came to Córdoba .. and roamed among the donkeys and horsemen'",
      "In another account, the term Córdoba means 'he struck him down', and it also means that 'al-qurtuba' is the sword, as if from 'qartabahu' meaning 'he cut it'. As for tracing the word's origin back to ancient languages, this was noted by the author of the article on Córdoba in the Encyclopaedia of Islam, and by many Western and Arab writers, since the word is originally an ancient Iberian one taken from the word Corduba or Corduva, which is indeed",
      "Arab writers also found an ancient word referring to an ancient, timeless city, which was mentioned during the conflict between the Greeks and Carthage, since the people of Córdoba took part in Hannibal's campaign against Rome, and it also became subject to the Roman Empire around the year 206 BC",
      "",
      "History of Córdoba",
      "Roman Córdoba",
      "Capital of the province of Baetica",
      "Córdoba was founded as a Roman settlement on the northern side of the Guadalquivir river (formerly the Baetis river) during the era of the Roman Republic in 206 BC, and it later became the capital of the province of Baetica (southern Spain) within the Roman Empire. Córdoba remained a Roman city for more than seven centuries, and traces of Roman rule still remain in Córdoba, most notably the Roman bridge (Puente Romano) that crosses the Guadalquivir, the ruins of a Roman temple, as well as a recently discovered Roman mausoleum. The philosopher Seneca emerged in Córdoba during that period",
      "After the fall of the Roman state due to successive invasions by Germanic tribes (barbarians), some of these tribes, such as the Vandals and the Alans, descended upon the Iberian Peninsula (present-day Spain and Portugal), followed by the Visigoths, who came to control the whole peninsula, including Córdoba, by the time the Muslims arrived in the eighth century CE (first century AH), after a conflict with the Byzantine Romans",
      "Islamic Córdoba",
      "The era of the governors",
      "After the Umayyad Muslims led by Tariq ibn Ziyad conquered Seville, Écija and other cities of southern al-Andalus, the number of fighters dwindled, prompting Ibn Ziyad to divide his army into detachments and appoint Mughith al-Rumi to lead the detachment that conquered Córdoba in the year 92 AH/710 CE, after crossing with his forces to Iberia (which the Muslims named al-Andalus) and killing its king Roderic",
      "The Umayyads made al-Andalus a province subordinate to the province of North Africa, until Umar ibn Abd al-Aziz made al-Andalus a province directly subordinate to the Umayyad capital in Damascus. The Umayyads made Córdoba the seat of their governors over al-Andalus, and it remained so until the fall of the Umayyad state at the hands of the Abbasids in 750 CE",
      "",
      "The Umayyad era",
      "But Córdoba's status only rose with the arrival of the Umayyad prince Abd al-Rahman al-Dakhil in al-Andalus, fleeing from the Abbasids. He seized control of affairs in Islamic al-Andalus and made Córdoba his capital in 756 CE, which marked the beginning of Córdoba's golden age, as it became the capital of the whole of Islamic al-Andalus and the most important city on the peninsula. During al-Dakhil's reign, work began on the Great Mosque of Córdoba, which still stands in the city today, and rule continued in the hands of the Umayyads of Abd al-Rahman al-Dakhil's lineage during this period",
      "The Umayyad state was subjected to a series of successive revolts, and its rulers lost control of affairs, until one of al-Dakhil's descendants, Abd al-Rahman III, known as al-Nasir, managed to re-establish Umayyad rule and subject most of al-Andalus to his authority from Córdoba, in the tenth century CE (fourth century AH). His power grew to the point that he took for himself the title of Caliph of the Muslims, based on what he considered his family's ancient right to the caliphate, which preceded the right of the Abbasids",
      "Al-Nasir moved his government to a new city he founded a few miles from Córdoba, naming it al-Zahra, but Córdoba remained the country's main city",
      "After the events of the Uprising of the Suburb, the city reached the height of its glory during the reign of Caliph Abd al-Rahman al-Nasir (912–961), his son al-Hakam II (961–976), followed by the chamberlain al-Mansur ibn Abi Amir (981–1002), who seized control of power in Córdoba while the Umayyad caliph became a prisoner in his palaces at al-Zahra. Al-Mansur built himself a palace of government on the edge of Córdoba, which he named al-Madina al-Zahira. Córdoba was one of the most important European states in the tenth century, and it was a beacon of learning and culture in Europe, and the capital of Arab and Islamic literature and culture. The city produced the poet Ibn Zaydun, the Umayyad poetess Wallada bint al-Mustakfi, the jurist Ibn Hazm, and the scholar Abbas ibn Firnas, and the musician Ziryab moved there and founded a school of urban culture",
      "",
      "The era of the Taifa kings and the Almoravids",
      "In the 1020s and 1030s, the caliphate collapsed due to the Berber revolt and the rise of the Taifa kings, who divided the state into more than 12 small states, including Granada, Seville, Almería, Valencia, Toledo, Zaragoza, Badajoz and Silves. The Muslim rulers of Seville and Toledo contended over Córdoba, until the city fell into the hands of the ambitious king of Seville, al-Mu'tamid ibn Abbad, in 1078 CE. Córdoba thus lost its status as a state capital, and neighbouring Seville rose to prominence instead of it",
      "While these Taifa states inherited the wealth of the caliphate, the instability of their rule and the constant infighting among them made them easy prey for the Christians of the north, until the jurists and consultative scholars of Morocco and al-Andalus issued a fatwa in favour of Yusuf ibn Tashfin, leader of the Almoravid state in the Maghreb, to depose them and seize power from their hands. The fatwas of prominent eastern scholars such as al-Ghazali and al-Turtushi supported this, so he took over most of al-Andalus from the hands of the Taifa kings, and the lands of al-Andalus, including Córdoba, became organised under the kingdom of Yusuf ibn Tashfin, in the year 1091 CE",
      "The era of the Almohads",
      "The Almoravid state fell to another Islamic movement, the Almohad movement, and Córdoba and the rest of Islamic al-Andalus came under their control in the mid-twelfth century. The Almohads restored the capital of al-Andalus to Córdoba, so it regained some of its former status, and during this period the Muslim philosopher Averroes (Ibn Rushd) appeared in Córdoba, in addition to the Jewish religious scholar Maimonides, the most famous Jewish philosopher of the Middle Ages",
      "The Almohads did not last long after that, as they suffered a crushing defeat at the Battle of Las Navas de Tolosa in 1212 CE, after which most of the Islamic cities in al-Andalus fell into the hands of the Christian kingdom of Castile, and Córdoba fell in 1236 CE to Ferdinand III, after more than five centuries of Islamic rule over the city",
      "Spanish Córdoba",
      "Córdoba was quickly emptied afterwards of most of its Muslim population, and the Spanish kings allowed those who remained to keep their Islamic faith after their conquest of the city, as with the rest of the Muslims in al-Andalus. They used Muslim workers and engineers to design buildings, palaces and churches for themselves in the Andalusian style, and the remaining Muslims under Spanish rule were called the Mudéjars. But this did not last long, as they began to be restricted, then forced to convert to Christianity through the Inquisition, which used various forms of torture and killing, so that some of them feared being discovered as Muslims lest they be killed, until Spain decided to expel the Muslims and their descendants who had converted to Christianity from all its lands. The Jews were also expelled, at the beginning of the seventeenth century, and the lands and estates were distributed among Christian settlers from the north who resettled cities such as Córdoba",
      "The old Islamic and Jewish quarters are still known in present-day Córdoba, and its huge mosque still stands at its centre, although a church was built inside the mosque in the sixteenth century, and the mosque is now used as a cathedral belonging to the Catholic Church. UNESCO has made the centre of the city of Córdoba (that is, the old quarter, including the mosque and the Jewish quarter) a World Heritage Site, in addition to the nearby city of al-Zahra",
      "Southern Spain (Andalusia, as the Spanish named it) went through a period of economic and cultural decline afterwards compared with the rest of Spain, and Seville flourished at Córdoba's expense because it was used as a port linking Spain with the New World. However, the whole region now enjoys economic prosperity due to the boost in tourism and the establishment of the autonomous region of Andalusia, and Córdoba forms the seat of the province of Córdoba within this region",
      "Archaeological sites",
      "The most important sites of Roman Córdoba:",
      "The Roman bridge, which crosses the Guadalquivir river, was restored during the Islamic era, and is still in use today",
      "The Roman temple, to the north of the old city",
      "The Roman mausoleum",
      "The most important sites of Islamic Córdoba:",
      "Its Great Mosque is one of the most beautiful things created by the Muslims in al-Andalus, and UNESCO has classified it as a World Heritage Site",
      "The city of al-Zahra, founded by Abd al-Rahman al-Nasir and named after his wife, which was completely burned down during the Berber revolt in 1020 CE, and is currently being restored, although only 10% of its total area has been excavated so far. At its heart lies Dar al-Rawda, the palace of Abd al-Rahman al-Nasir, to which water was brought from the mountain",
      "The Arab baths",
      "The Jewish quarter of Córdoba, called in Spanish 'Judería', meaning the place of the Jews, even though the Jews were expelled from Córdoba back in the seventeenth century",
      "The Calahorra Tower, an Islamic fortress located on the other (southern) side of the Guadalquivir at the end of the Roman bridge, to which the Spanish kings later made additions, and which now houses a museum",
      "The remains of the city walls and some of their gates, especially on the western side",
      "The waterwheel, located next to the Roman bridge",
      "Other monuments:",
      "The Alcázar of Córdoba, a palace built by the Christian rulers of Córdoba after they conquered it, on the site of the old palace of Córdoba, from which Christopher Columbus was permitted in 1492 to sail in search of a new route to India",
    ],
  },
  malaga: {
    title: "Get to know everything about the wonderful city of Málaga",
    values: [
      "Discover Spain",
      "Málaga Spain",
      "On this page you will learn about the following:",
      "Málaga in general",
      "The location of Málaga",
      "The climate of Málaga",
      "Religions in Málaga",
      "The history of Málaga",
      "Tourism in Málaga",
      "Reasons to travel to Málaga",
      "Let's go and discover one of the most beautiful cities in Spain and Europe",
      "Málaga is a Spanish city …",
      "an ancient one built by the Phoenicians about 2,770 years ago. The city is located in the south of the country and is the capital of the province of Málaga in the Andalusia region, overlooking the Mediterranean Sea, and lies in the heart of the Costa del Sol area, and is the most important Spanish port after Barcelona. It is surrounded by mountains, and around it flow the Guadalmedina and Guadalhorce rivers. Its mild, moderate climate attracts many tourists. The Spanish painter Pablo Picasso was born in this city. Málaga was known as 'Malaqa' during the Islamic rule of Spain, but the name Málaga is taken from the Phoenician name 'Malaka' or 'Malka'",
      "The location of the city of Málaga",
      "The city of Málaga is located …",
      "in southern Spain on the coast of Costa del Sol in the north of the Mediterranean Sea. It is about 100 km east of the Strait of Gibraltar and about 130 km from the town of Tarifa (which lies at the southernmost point of Europe), and Málaga is also about 130 km from the African continent, lying at roughly the same latitude as the cities of Algiers, Tunis, Aleppo, Mosul, Tehran, Kunduz, and California. Below you can find the location of Málaga on the map",
      "https://maps.app.goo.gl/HeWpPWGNqent8jeq6?g_st=com.automattic.jetpack.JetpackShare",
      "The climate of the city of Málaga",
      "Málaga enjoys a Mediterranean climate …",
      "that is almost subtropical, with a very humid winter and a hot summer. The city's weather is generally sunny, enjoying more than 300 sunny days compared with about 50 rainy days a year, and due to its coastal location, Málaga receives Mediterranean sea breezes that help cool the summer heat",
      "",
      "Religions in Málaga",
      "Most of Málaga's population …",
      "belong to the Roman Catholic Church, and due to recent migration there has also been a growing presence of Islam in the city, and a new mosque has recently been built in Málaga. In addition to Catholicism and Islam, the city also has a growing presence of the Evangelical faith and some Jewish presence",
      "The history of Málaga",
      "The city of Málaga was founded …",
      "in 1000 BC by the Phoenicians, who named it Malaka, a name mostly derived from the word for 'salt' in Phoenician, and which also exists in some Semitic languages such as Hebrew and Arabic, since fish were salted automatically on its shores",
      "Phoenician merchants settled it and described it as 'the light of the night', due to the reflection of the moonlight on its shore overlooking the Mediterranean Sea. The Phoenicians, during their presence in Málaga, built a fortress",
      "In the seventh century BC, the Greeks founded the colony of Mainake near Phoenician Málaga at the invitation of Arganthonios, king of the kingdom of Tartessos, which negatively affected Málaga",
      "",
      "The Carthaginians invaded the region, destroyed Mainake, and occupied Málaga in the sixth century BC, after 70 years of Greek dominance, and Carthaginian control of the city lasted until 218 BC, when the Romans entered it",
      "The Roman occupation was the beginning of an important era for Málaga, as the Romans created an economic and cultural centre there, in addition to building the port and a Roman theatre, considered the oldest in Spain. Under the Roman emperor Titus (79–81 CE), Málaga became Rome's allied city in the region, which raised its status with the Empire",
      "When the Roman Empire began to collapse at the start of the fifth century CE, the coasts of Andalusia, including Málaga, were regularly divided among small Gothic tribes. Eventually, the Goths entered the centre of the city of Málaga in 623 CE, when the last Roman forces left it",
      "In the eighth century CE, the conquest of Málaga was one of the easiest Islamic conquests, as it was apparently conquered twice — the first conquest was in the time of Tariq ibn Ziyad, and it was a marginal, distant conquest, from which the people of the city soon recovered their city, and the other conquest was a real one that confirmed the first, and it most likely took place in the year 94–95 AH",
      "The city of Málaga played a major historical role in the political and economic building of the Islamic state in al-Andalus during the era of the Taifa kings and the Almoravids, and it reached the height of glory and civilisational prosperity in the era of the Almohads, and even more so in the era of the Nasrids. Málaga came under Almoravid rule in 483 AH after the Battle of Sagrajas, and in 547 AH al-Lushi surrendered the city to the Almohads, and in 625 AH, after the weakening of the Almohads, Muhammad ibn Yusuf ibn Hud annexed Málaga to his kingdom, and he remained its ruler until he died",
      "Christian attempts to take control of Málaga were made in 887 AH and 888 AH, but they failed thanks to the resistance of al-Zagal, who took over the rule instead of his brother. Attempts from Castile resumed, and they were able to take control of Málaga after a long siege, in 892 AH, and the Spanish entry into the city led to a massacre exceeding in brutality the Srebrenica massacre that occurred 10 years before it",
      "After the fall of the city, internal resistance arose, led by the hero commander Ahmad al-Thaghri, who was killed and buried in a cave in Carmona (near Seville)",
      "",
      "Tourism in Málaga",
      "Málaga is considered one of the most important centres …",
      "of tourist attraction in Spain, as the city is nicknamed the capital of Costa del Sol (the capital of the sunny coast), and the most important tourist sites in the city are the birthplace and museum of Pablo Picasso, the Carmen Thyssen Museum, the old town and the beaches, and the port of Málaga is considered the second busiest port on the Iberian Peninsula",
      "The other most prominent tourist centres in the city are the old Islamic palace in the Alcazaba, the Roman theatre, the old Jewish quarter, the cathedral, the church of Santiago, and the Holy Week Museum",
      "Other events in Málaga",
      "Málaga holds many …",
      "traditional celebrations, the most important of which is the Verdiales festival on 28 December, which coincides with April Fools' Day in Spain. Also, every February, the Carnival Festival is held, during which people dress up in traditional costumes, flamenco dancing takes place, and there is a display of decorated cars, while stalls selling pottery and traditional crafts spread throughout",
      "",
      "By choosing Málaga as your next destination, you will have chosen light, art, and al-Andalus in its purest form",
      "They say Málaga is the Andalusian paradise …",
      "meaning that if there is a destination where you can disconnect and enjoy the sun, this is Málaga. Many of those who visit the city or the famous Costa del Sol feel overwhelmed by its sea, its cuisine and its people, but although this is a lot, the province of Málaga has as many amazing places as it does beautiful ones",
      "Discover the Caminito del Rey, the wonderful trail, and thousands of activities and tourist sites that will make you love this beautiful province and al-Andalus in general",
      "Reasons to travel to Málaga",
      "Málaga is known as …",
      "the capital of Costa del Sol, and perhaps the best definition of it is the ideal global city of al-Andalus, and anyone who knows Spain well knows that it can resemble major Spanish cities such as Bilbao, Barcelona, and even Valencia",
      "For this exact reason, you should visit Málaga, because it is global, modern, classic, and historic all at once, and it has so many breathtaking views and immense beauty that you will find in one city all the entertainment you need for a wonderful holiday",
      "The city of Picasso can be seen from several points of view, as the painter himself showed in his work — you can see the Málaga of Picasso, you can see the huge Málaga, you can even see the Málaga of bullfighting that he captured in his work",
      "",
      "The importance of visiting Málaga",
      "Although Málaga …",
      "is one of those destinations that must be fully experienced, you will find beauty in every corner and every nook. We leave you with the essentials for a visit to the city of Málaga:",
      "Castles are always a recommendation in every place; the Gibralfaro Castle, in addition to being a historic lighthouse of Phoenician origin, is a place that enjoys wonderful views over the sea and the city. This castle is part of a fortified complex that reaches to the Alcazaba, and both stretch along the entire hill, leaving stunning views with a panoramic vista of the city, since this was a strategic and historic site, where many civilisations fought to exercise control",
      "Immerse yourself in one of the almost fully preserved archaeological complexes in the ancient Andalusian city, which was once a city of ancient palaces, gardens and fortresses that housed the court of the Nasrid kingdom",
      "With more than 36 museums, the city can be defined as a reference point for museum tourism. The best thing about Málaga's museums is that most of them are located in the city centre and are easy to enjoy, and if we have to highlight some of the best museums in Málaga, we would say you must not miss:",
      "The Picasso Museum",
      "The Carmen Thyssen Museum",
      "The Málaga Museum",
      "The Centre Pompidou Málaga",
      "The Interactive Museum of Music",
      "In addition to paying close attention to the temporary exhibitions, artists, and fine arts events that gather there regularly",
      "",
      "You will find in the historic centres of the great Spanish destinations the grand cathedral churches, and in Málaga this will be no less true, since Málaga Cathedral is the most impressive monument in the historic centre of the city of Málaga",
      "Originally it was left unfinished, and in tribute to Málaga's charm, its people began affectionately calling the cathedral 'La Manquita' (the one-armed lady), despite the fact that its full name is the Cathedral of the Incarnation of Málaga, a cathedral originally Gothic in style and completed in the Renaissance style, defined by history, architectural styles, and beauty",
      "If you walk through the old town of Málaga, at the foot of the Alcazaba hill, you will find the Roman remains of the Gran Teatro Romano de Málaga, a unique place that shows the importance of the presence of the Roman Empire in the city",
      "This is how ancient Málaga appears with a theatre; although it is of medium size, part of the cavea (the public tiers) and the orchestra, decorated with large marble slabs, is well preserved",
      "The theatre in the background has a decorated facade adorned with openings, columns and sculptures, some of which are still preserved. The best thing is that there is the possibility of completing the visit by stopping at the interpretation centre",
      "Another wonderful thing to see in the city of Málaga is strolling through the Mercado Central shipyard market in the city, which dates back to the end of the nineteenth century",
      "A market that emerged from a building of Nasrid origin and a later naval workshop, today featuring a visually appealing design and structure. Although it is best to share fresh produce purchases with neighbours, you can enjoy the bars and atmosphere",
      "The most impressive shopping street you will find in the centre of Málaga is undoubtedly Calle Larios, visited by hundreds of people daily for shopping, and at Christmas it is famous for its light show and decorations",
      "Calle Larios, as it is known, is Calle Marqués de Larios, and it is the most common venue for every event or tradition, from the Málaga Film Festival to Christmas, Easter, or August; it is a place of joy par excellence for enjoying the international nature of this city",
      "",
      "The best of the province of Málaga",
      "Málaga is not just the city …",
      "it is one of eight Andalusian provinces located in the south, bordered by the Mediterranean Sea along its entire coastline — the famous Costa del Sol — the province where places such as Marbella, Nerja, or Torremolinos are found",
      "The province where the sea stands out with more than 160 kilometres of coastline, or the best marinas in the south, is also distinguished by a large number of golf courses and its inland areas — places with unique landscapes, mountains, charming towns and caves or archaeological sites scattered between the coast and the interior. So if you want to see and get to know the province of Málaga, you cannot miss the most-visited place for adventure, natural landscapes and beauty in the inland areas of the province of Málaga. The famous Caminito del Rey is one of the places you must see if you are in the city, so you should discover the wonderful places, as authentic as they are",
      "One way to unify and travel around Málaga for lovers of long-distance walking is that the Diputación de Málaga implemented a route like this in order to unite it into a tourism product as a way to explore Málaga's nature and practise sport and tourism, all at once",
      "For this reason, it is suggested that if you have plenty of time, this is the way to do a route that runs through the province for more than 900 kilometres. The great route is a path divided into 35 stages and 6 variants, across 9 provinces and 54 urban areas",
      "",
      "Although the Great Path of Malaga is not a place in itself, we believe it is an important way to get to know the province, since many have identified it, the Great Path of Malaga is a kind of Camino de Santiago through the province of Málaga, which will let you get to know 4 natural parks, towns and the essence of Málaga",
      "Also, the village of Antequera, the Dolmens that make up its archaeological complex, or El Torcal, are the three main reasons that justify the trip from the city of Málaga inland towards Granada",
      "It is impressive to walk through El Torcal and its stunning karst landscapes, some strange rock formations that will make you feel as if you are on another planet or country, and it is known that there is no other place in Spain known for such splendour, of Jurassic origin and former seabed, which has been declared a natural area under UNESCO World Heritage status",
      "The archaeological group of the Antequera dolmens is also impressive with its large stones placed to build the hill that became a burial site centuries ago. How they were placed, their shapes, and why — this is a mystery in many cases, and legends in others; it is possible to learn everything and more with Discovering Spain if you are in Granada or Málaga",
      "Although Nerja is essential not only for its caves but also for its beaches or the Balcón de Europa, it is clear that you must not miss the caves, one of the wonders of nature, a cavity in the rock that can be visited and where you can even see the stalactites and stalagmites through all the galleries",
      "You should see Frigiliana on the Málaga coast, because it is one of those beautiful, white and charming towns that remind us of towns on the Greek coasts, an authentic Mediterranean town at its best",
      "",
      "Like Frigiliana, it is a must in the province of Málaga, a town with white cobblestone streets, where you can take wonderful photos, a completely white town with an oval bullring, unique because it is not common to find a bullring in this shape",
      "In addition, Mijas is famous for its donkey-taxi, which, as the name indicates, is a way to tour around the municipality on a donkey's back, a strange and unique way to travel, which besides being fun is safe for the animal, since according to the city council and officials, the donkey is well cared for and it is an essential figure in the municipality",
      "As a place of the ultimate expression of bullfighting and flamenco from Málaga, we find the wonderful town of Ronda, the tours around the city are distinctive",
      "Calle Larios, as it is known, is Calle Marqués de Larios, and it is the most common venue for every event or tradition, from the Málaga Film Festival to Christmas, Easter, or August; it is a place of joy par excellence for enjoying the international nature of this city",
      "Ardales, a town located in the centre of the province of Málaga, is considered a town to which part of the Caminito del Rey belongs, and it is also distinguished by its heritage. Among the most impressive places we find the Cueva de Ardales, a place of prehistoric importance, with cave paintings, which has an interpretation centre to complete the visit",
      "In the municipal district of Ardales, we find another place you should visit, the ruins of Bobastro, an ancient town where Umar ibn Hafsun settled, a rebel who settled in the place after revolting against the Umayyad forces, the ruling dynasty in Córdoba, whom he confronted from the year 880, when he revolted, until the year 919 CE. It was a legendary fortress built on the rock and was impregnable",
      "Today you can visit and learn what has been preserved, an important site for understanding the origin of al-Andalus. In addition to the ruins, you can also visit the Mozarabic Basilica, one of the pillars of rock-cut architecture, an exceptional example of architecture and heritage",
      "",
    ],
  },
  valencia: {
    title: "Get to know everything about the city of Valencia",
    values: [
      "Discover Spain",
      "How do you imagine Valencia?",
      "Valencia is the capital of the province of Valencia in eastern Spain on the Mediterranean Sea, and one of the country's largest cities, with a population of about 798,033",
      "The name",
      "The original Latin name of the city was Valentia, which means strength and valour, due to the Roman practice of recognising the bravery of former Roman soldiers after a war",
      "During the rule of the Islamic dynasties, the Spanish Muslims did not follow the Spanish name for that city, but changed some of its letters and made an adjustment to its spelling, so it became 'Valensiya', and they recorded it with this spelling in their historical and geographical writings. The Muslims described it as 'the city of soil', because of the abundance of soil due to the extent of its fields and farms",
      "History",
      "The Romans were the ones who founded ancient Valencia in the year 139 BC, and then the Visigoths took control of it in 413 CE",
      "Andalusian history",
      "The Muslims conquered it in 714 CE, and established, in it and in the cities of Játiva, Denia, and Sagunto, the foundations of Islamic rule. To the Muslims, in the era of their state in al-Andalus, goes the credit for the prosperity of the plain of Valencia, as they dug thirty-one canals on both sides of the river or Wadi al-Abyad, and channelled water from it to irrigate all its lands with ease, and they called these canals 'sawaqi' (acequias), and this Arabic word entered the Spanish language and remains present in it to this day. In the Arab era it was the third city of al-Andalus in order by population, which at that time exceeded a quarter of a million people",
      "An Islamic kingdom",
      "An Islamic kingdom was founded in Valencia in the year 401 AH – 1010 CE by two freedmen of al-Mansur ibn Amir, and their role in this kingdom was no more than overseeing irrigation affairs and maintaining its system in the Valencia region, but they rebelled and declared their independence, on the basis that rule would be a partnership between them. One of them soon died, so its people kept the other away from the city, and Valencia came under the rule of the governor of Barcelona, until it was conquered by Abd al-Aziz ibn Abd al-Rahman, grandson of al-Mansur ibn Amir. In the following centuries Valencia fell under the control of the rulers of the Taifa kingdoms, then the Almoravids, then the Almohads, until the Franks occupied it in 1238 CE, two years after the fall of Córdoba",
      "The Kingdom of Valencia",
      "The Kingdom of Valencia was officially established in 1237 CE in the context of the reconquest process, when Valencia was conquered from the Taifa kings, and Philip V ended the Kingdom of Valencia in 1707 CE by decrees, as a result of the War of the Spanish Succession",
      "During its existence, the Kingdom of Valencia was governed by laws and institutions, and the Charter of Valencia is recorded as having granted it broad self-government, initially from the Crown of Aragon, and later from the Kingdom of Spain",
      "Invasions",
      "There were numerous conquests by the Moorish population against the Christian base, the most dangerous of which was led by a Moorish leader, Muhammad Abu Abdullah, also known as al-Azraq, who led an important rebellion in 1244, 1248 and 1276. During the first conquest, the Muslims briefly gained independence for the lands south of the Júcar, but he was forced to surrender shortly after. During the second revolt, King James I was almost killed in battle, but al-Azraq only spared his life so as to buy a long period in his relationship with the Christian monarch, and during the third phase al-Azraq himself, but his son was killed, the Muslims continued to encourage unrest, and local uprisings always remained on the horizon",
      "The Kingdom of Spain",
      "When the Crown of Aragon merged with the Crown of Castile to form the Kingdom of Spain, the Kingdom of Valencia became a member of the Spanish monarchy",
      "Architecture",
      "The cathedral contains a large minaret remaining from the mosque that belonged to the Muslims. The old streets of the Barrio del Carmen contain buildings dating back to Roman and Arab times. Valencia Cathedral (the Cathedral of the Virgin) was built after the Reconquest between the thirteenth and fifteenth centuries, primarily in the Gothic style, but it contains elements of ornamentation and Romanesque architecture",
      "UNESCO recognised the Lonja de la Seda as a World Heritage Site. The Mercado Central is one of the largest in Europe",
      "Valencia is also home to the City of Arts and Sciences, a group of modern cultural buildings",
      "By visiting Valencia, you will have …",
      "already chosen one of the most impressive places in Spanish geography. Valencia is the Mediterranean Sea in its purest form, with its adventures and nature, and to experience it more intensely, you should do a series of essential things, as you must stop to have lunch every day at around twelve noon, or listen to a mascletà, or take part in Las Fallas",
      "But if you do not manage to attend the latter, do not worry either, because Valencia gives you the opportunity to do a variety of activities, ranging from listening to music of any kind at the Palau de les Arts to walking in nature at the Jardín del Turia",
      "So why should you visit Valencia?",
      "For one main reason, which is what Valencia looks like as a city and its people; it is a city that hosts festivals such as Las Fallas, one of the World Heritage sites, welcomes visitors and hosts an internationally recognised festival. With this you can get an idea of the closeness among its citizens and the harmony between the beauty of the coastal city and the cultures and warmth of its people when walking through its streets",
      "In addition, Valencia shows us wonderful examples of architecture, of yesterday, today and tomorrow, since the futuristic shapes impress us and leave us in awe of the buildings that make up the Ciutat de les Arts i les Ciències, so Valencia deserves a visit at its peak, because it combines the artistic expressions of its old city with the beauty of its historic landmarks",
      "Valencia Cathedral, known as the Cathedral of the Holy Grail, is one of the most important artistic and archaeological resources in the city; entering it and breathing in it, hard as it is, will make your body permeated with the scent of incense, the scent of the church, for a mystical and sublime experience",
      "It is known throughout the world because it houses the most important treasure of Christianity, the chalice or Holy Grail, from which the apostles and Jesus Christ shared wine at the Last Supper, present in the building, as archaeological remains and written sources indicate, and it is displayed in the Chapel of the Holy Grail",
      "The cathedral building is Gothic in style, and construction began in the thirteenth century and finished in the fourteenth century with the building of the tower, although it was covered with a neoclassical style in the eighteenth century, and in the twentieth century its Gothic structure was restored",
      "When visiting the cathedral you should stop at the museum, a new museum that houses Roman, Gothic and medieval artefacts",
      "The cathedral tower is a tower located within Valencia Cathedral itself, which was built on the original Roman temple, today also mostly in the Gothic style; it is a place where, if you dare to climb more than 200 steps, it will offer you the best views of the city of Valencia",
      "By the way, do not forget to delve into the legend or history of the Virgen del Buen Parto; perhaps this way you will understand why many pregnant women walk inside the cathedral and pray in front of it",
      "And Valencia will still amaze you …",
      "There is an impressive place in Valencia known as the Ciutat de les Arts i les Ciències",
      "A group of buildings dedicated to the dissemination of science, including the Hemisfèric, the Umbracle, the Museu de les Ciències, the Oceanogràfic, the Palau de les Arts Reina Sofía, and the Ágora, which houses the CaixaForum. These buildings are a contribution by the renowned Spanish architects Santiago Calatrava and Félix Candela, who turned the space into an architectural complex of unique and extraordinary beauty",
      "One of the Gothic buildings par excellence, and one of the sights that must be seen in the city of Valencia, is the Lonja de la Seda, also known as one of the merchants' halls, a symbol of the city's economic prosperity from the fifteenth century, and which still exists today",
      "This building was named a national monument and later a World Heritage Site, because its beauty and splendour were key factors in its construction. When the construction of this building was proposed in the fifteenth century, the intention to turn it into a symbol of the city was the key to making it one of the most impressive places in the city today",
      "Not far away, just a 10-minute drive separates the city from nature at its purest, since this natural park is a coastal lagoon of very shallow depth, of great ecological value for thousands of local and migratory species that pass through every year",
      "The best thing about the Albufera is that it is a very large place, and this makes it divided into four regional areas, of which 13 municipalities are part",
      "A vast area you can escape to from the city, where a Mediterranean climate prevails, so the temperature is mild, and where traditional activities such as hunting, fishing and farming, especially rice farming, are still practised today",
      "We are before the cradle of paella! For this reason, you should not leave without a trip to one of the surrounding towns specialising in this Valencian dish; we recommend El Palmar, to highlight a little of the delicious Valencian paellas",
      "And before leaving the Albufera, head over to the Laguna de Anna, a lake surrounded by forest where you can rent a boat and disconnect completely from the busy world",
      "A town carved into the rock is the best definition of this town",
      "The historic or old town, which has been declared a historic-artistic site, is one of the things you must visit; stroll through its streets full of pottery and stop at its granaries and parish church",
      "When you pass by and glance at the bullring, you cannot miss how the solution for its construction was that the bullring was carved into the rock, or how the construction of the bullring adapted to the particularities of the terrain",
      "A town like this, with an ancient history, allows us to learn more thanks to a visit to the Vicente Casanova Museum, the municipal archaeological museum, with remains of the Iberian culture that once inhabited the environment",
      "Close to Alicante, we find the town of Ontinyent, a historic place shown in the Pont Vell (old bridge), which connected the oldest part of the town with the modern part, La Vila, which is how the oldest part of the town is known, the place that has been preserved today along with some of the most important signs of modernity, which include the most iconic buildings and historic landmarks",
      "If you pass through Ontinyent, we recommend stopping at the Valencian Textile Museum, which will give you an idea of the town's industrial past",
      "Stop at the church of Santa María and in its square, take a walk and visit the anti-aircraft shelters in Ontinyent and Delgado",
      "One of the towns in the Valencian Community with the most tourist resources, Cullera has a beach, ruins, and one of the most beautiful lighthouses in Spain",
      "Cullera and its beaches are famous for their beauty, among them L'Estany, a magical corner that inspired Sorolla himself in his paintings",
      "But not only its beaches — Cullera is also home to the Dragut Pirate Cave Museum, which is ideal to visit with children, and the Islamic castle located on Mount Rabosa with its wonderful views",
      "The province of Valencia is very rich in walking trails and places of great importance, but in this case we will focus on one in particular, the route through the Valle de la Murta, a well-marked route suitable for everyone",
      "It runs in a circular route around the ruins of the Monastery of la Murta, in the municipal natural area, in the municipality of Alzira, capital of the Ribera Alta, a flat, level and simple forest trail",
    ],
  },
};
