export const SPAIN_EN_1: Record<string, { title: string; values: string[] }> = {
  madrid: {
    title: "Madrid — the icon of tourism in Spain",
    values: [
      "The city of Madrid, the capital, is one of the most beautiful cities in Spain. It embraces numerous tourist landmarks and cultural and historical treasures such as the Royal Palace, the Royal Theatre, and many archaeological museums and art galleries unmatched anywhere else in Europe. It is also famous for its distinctive restaurants and cafés and includes many buildings of refined architectural design. In summer, the Spanish city of Madrid is known for its wonderful weather that draws many tourists to it to spend an enjoyable holiday and have fun with their families amid landmarks, tourist areas, and truly wonderful activities.",
      "",
      "The Prado Museum",
      "The Prado Museum is considered Spain's main national museum and one of the oldest tourist attractions in Madrid. The museum's history dates back to the eighteenth century, and it houses a huge number of works and paintings by the most important artists in the world, related to European art between the twelfth and nineteenth centuries.",
      "",
      "The Reina Sofía Museum",
      "The Reina Sofía Museum is one of the most prominent tourist attractions in Madrid, Spain, as it is a modern complement to the historic Prado Museum. It was officially opened in 1992 by order of Queen Sofía. The museum houses a wide collection of artworks by the most famous Spanish artists, the most prominent of them being Pablo Picasso.",
      "",
      "",
      "",
      "",
      "Retiro Park",
      "Spain is famous for the celebrated Retiro Park, one of the most beautiful tourist areas in Madrid. The park extends over vast spaces and includes many recreational activities that help visitors spend an enjoyable time amid stunning nature and trees.",
      "",
      "Plaza de Cibeles",
      "Plaza de Cibeles is one of the tourist attractions in Madrid and one of the most beautiful squares in Spain. At its center stands a fountain surrounded by a monument to the Greek symbol of fertility, carved from purple marble in 1780. The square includes a number of important buildings and tourist sites in Madrid, such as the Post and Telegraph Museum.",
      "",
      "",
      "Near it lies one of the best shopping areas in Madrid; the buildings surrounding the square were built in the neoclassical style, and the fountain of this square is considered one of the finest and most magnificent tourist landmarks in Spain. Its name was originally Madrid Square, but it was changed to its current name in 1900.",
      "Plaza Mayor, Madrid",
      "Also known as the Great Square of Madrid, it is one of the most important and prominent tourist sites in Madrid, Spain, located in the heart of the city, making it a destination for all visitors and tourists from various parts of the world. The Great Square includes a large collection of Spanish restaurants and cafés.",
      "",
      "",
      "",
      "",
      "",
      "Puerta del Sol Square",
      "Puerta del Sol Square is located in the heart of the city and includes many buildings with distinctive architectural designs that make it one of the most beautiful tourist places in Madrid. At the center of the square stand a number of statues symbolizing the Spanish city of Madrid, which attract many tourists to it, in addition to the presence of many international shops.",
      "",
      "Gran Vía Street",
      "Gran Vía Street, located in the heart of the city, is considered one of the most famous bustling streets in Madrid and was completed in 1910. This street contains a large number of restaurants and many shops, making it one of the most prominent tourist attractions in Madrid.",
      "",
      "",
      "",
      "The Royal Palace",
      "The Royal Palace in Madrid is one of the most magnificent palaces in Europe and the largest in area, its area estimated at 13 hectares. It is located in the western part of the capital, Madrid, to the east of the Manzanares River on a street called Bailén Street. The Royal Palace in Madrid is the official residence of the Spanish royal family, but today it is used only for official ceremonies. The Royal Palace is considered one of the most important tourist attractions in Madrid.",
      "",
      "",
      "",
    ],
  },
  barcelona: {
    title: "Tourism in Spain — Barcelona",
    values: [
      "Tourism in Spain has witnessed tremendous growth, with millions of tourists visiting it every year from all over the world, making it one of the most tourist-attracting countries in the world. The city of Barcelona is the capital of the autonomous Spanish region of Catalonia, located on the coast of the Mediterranean Sea and surrounded by the Collserola mountain range, and it is a major element of tourism in Spain.",
      "Sagrada Família Church",
      "The Sagrada Família Church is one of the most famous religious tourist landmarks in Barcelona, containing many statues and stone sculptures. The world-renowned architect Antoni Gaudí began building this enormous temple in 1882, and to this day some parts of the Sagrada Família remain unfinished.",
      "",
      "La Rambla Street",
      "La Rambla Street in Barcelona is the main street of the city and its beating heart, visited daily by crowds. In the morning it fills with street vendors and tourists, while in the evening the night takes on its own stories and tales, as La Rambla transforms into cells packed with people, and evenings full of joy and happiness begin, lasting until dawn.",
      "La Rambla is considered one of the most important tourist landmarks in Barcelona; flowers are sold along its 1.2 km length, connecting Plaça de Catalunya to the city center, ending at Christopher Columbus's monument by the shore, filled with ships and the Olympic Port, giving La Rambla Street in Barcelona a beautiful view of the Mediterranean Sea.",
      "",
      "Park Güell, Barcelona",
      "Park Güell in Barcelona is a public park and historic garden in the north of the city of Barcelona, located in the La Salut neighborhood in the Gràcia district. It is one of the favorite places for tourists coming for tourism in Barcelona. Park Güell contains vast green spaces in addition to architectural elements with a special distinctive character. The park was built between 1900 and 1914 and was officially opened to the public in 1926.",
      "In 1984, the park was declared a World Heritage Site, and it is visited by thousands annually from all over the world. The park is home to a large number of wild animals and birds, especially various species of parrots that were brought from different parts of the world, as well as other rare bird species such as the short-toed eagle and hawks of the hummingbird moth family.",
      "",
      "",
      "The Barcelona History Museum",
      "This museum displays the history of the city of Barcelona from Roman times to the present day. It is located within a Gothic-style palace consisting of 3 floors in the Barri Gòtic (Gothic Quarter), near the church of Santa Llúcia. The museum houses relics and excavations dating back to the Roman settlements that inhabited the region, and it also displays the history of Catalonia and the emergence of the historic city of Barcelona and the stages of its founding. The museum is considered one of the most important tourist landmarks in Barcelona, Spain.",
      "",
      "",
    ],
  },
  bilbao: {
    title: "Learn everything about the city of Bilbao",
    values: [
      "Discover Spain",
      "On this page you will learn about the following:",
      "Bilbao in general",
      "The history of the city of Bilbao",
      "The geography of the city of Bilbao",
      "Sports in the city of Bilbao",
      "",
      "Bilbao in general",
      "A journey full of contrasts",
      "It is impossible to imagine the city of Bilbao without …",
      "Its distinctive old town, with more than 700 years of history. It is a great pleasure to stroll around the seven famous streets and discover famous buildings such as the cathedral, or the elegant theatre inspired by the Paris Opera House, and Arriaga, and a mix of shops and cafés, from traditional to spectacular.",
      "Basque cuisine",
      "The city of Bilbao is proof that gastronomy is an art in the Basque Country, one of the regions with the highest number of Michelin stars per capita in the world. Plaza Nueva and its surrounding streets are filled with crowded bars serving the famous pintxos — small, delicious bites of food. There, food lovers can find their place among the lively bars and restaurants run by families and renowned chefs, and you will also have the chance to visit La Ribera Market, a beautiful building where you can cook the produce you buy, or where you can taste it accompanied by a selection of Txakoli and Petit Chablis-style wines to the rhythm of live music.",
      "Although it may seem strange, its unique character comes from the combination of avant-garde spirit and the traditional feel of its old town, full of charming streets and bars serving pintxos, which proves how passionate they are about gastronomy — and all this has earned Bilbao a place of honor on the lists of the most interesting cities in Spain.",
      "A green city",
      "Culinary and cultural Bilbao is also a green city, with parks such as Doña Casilda de Iturrizar, surrounded by hills (try riding the Artxanda funicular, a classic option for a bird's-eye view of Bilbao). The estuary is another symbol of Bilbao's renewal — you can watch people surfing on the water, or take a boat to the famous suspended Vizcaya Bridge, which has been declared a World Heritage Site. And if all that is not enough, the stunning beaches and cliffs of Getxo are just over 30 minutes away by metro.",
      "A tourist could start by visiting …",
      "The city of Bilbao, located in northern Spain, with the Guggenheim Museum, is one of the most astonishing examples of 20th-century architecture, where Frank Gehry used 33,000 extremely thin titanium panels to create its strange curves. Inside, it shares, along with New York and Venice, one of the most important private collections of modern and contemporary art in the world. Bilbao also has another of the best art galleries in Spain, the Museum of Fine Arts.",
      "The city's commitment to creating a pioneering, imaginative image includes the Euskalduna Conference Centre, Norman Foster's metro stations, the Isozaki and Pelli towers, the Zubizuri Bridge, and new cultural centers such as La Alhóndiga by Philippe Starck, built atop an old wine cellar.",
      "",
      "Bilbao is a city located in …",
      "The north-center of Spain, and it is the capital of the province of Biscay, with a population of around 250,000. Bilbao is considered an industrial and commercial center in a region rich in iron mines, and it is also an important seaport, despite being located about 13 km from the Bay of Biscay. The Nervión River runs through the city and flows into the bay, and the city's exports include iron, steel, flour, paper, glass, and leather. Bilbao was founded around the year 1300 CE.",
      "History",
      "Burial sites have been found there …",
      "Dating back 6,000 years, on Mount Avril and Alcanda, and remains of an ancient settlement dating from the second to third century BC were discovered on top of Mount Malmasín. A number of researchers have identified these remains as the foundation of the ancient city of Amanum Portus, according to the historian Pliny the Elder, while others believe it to be the city of Flaviobriga according to the historian Ptolemy. Remains of an eleventh-century wall were discovered under the Church of San Antón.",
      "Bilbao was founded in the century …",
      "The fourteenth, then came a wave of settlement alongside most of the towns of the Biscay region, which make up about 70% of the modern communities in the area. The Lord of Biscay, Diego López V de Haro (Diego López V of Haro), founded Bilbao by order dated 15 June 1300 in Valladolid, which was approved by Ferdinand IV, King of Castile and León, in Burgos, on 4 January 1301. Diego López founded the new town on the right bank of the Nervión River, on land of the local government (Elizate) of Abando (Begoña), and it was granted by Haro of Logroño a charter of rights and privileges at a later time.",
      "In Bilbao there is a cathedral dedicated …",
      "To James the son of Zebedee (Santiago), built at the end of the thirteenth century as a small chapel on the road to Santiago, which was expanded over the following centuries. It was built mainly in the Gothic style and rebuilt in the Neo-Gothic revival. In addition, Bilbao's cathedral has several churches in the Gothic style, and in the sixteenth century the city manufactured swords (double-edged swords), known as \"Bilbo swords.\" The \"Bilbo\" swords were large, with a well-forged flexible blade, and gained popularity among sailors and Europeans who emigrated to the New World, America, because of the reputation of these swords, and they are also mentioned in a play by William Shakespeare.",
      "Geography",
      "Bilbao is located at the tip of the peninsula …",
      "The Iberian Peninsula, 19 kilometers from the Bay of Biscay, covering 40.65 square kilometers, of which 17.35 are residential areas and 23.30 square kilometers are mountains. The city lies between the Cantabrian and Pyrenees mountain ranges.",
      "Sports",
      "San Mamés Stadium …",
      "As is the case in Spain, football is one of the most prominent sports in the city of Bilbao, followed by basketball. The city's main club is the storied Athletic Bilbao, which plays at San Mamés Stadium, the oldest stadium in Spain, with a capacity of 39,750 spectators.",
      "Athletic Bilbao is distinguished by the fact that it does not include any player on the team from outside the Basque Country. In 2013, a new stadium was inaugurated in the city called the New San Mamés next to the old stadium, which was later demolished. The new stadium meets FIFA and UEFA standards for quality and luxury, and its construction cost about 173 million euros, with a total capacity estimated at 53,289 spectators.",
      "",
      "",
    ],
  },
  zaragoza: {
    title: "Learn everything about historic Zaragoza",
    values: [
      "Discover Spain",
      "On this page you will learn about the following:",
      "The city of Zaragoza in general",
      "The characteristics of the city of Zaragoza",
      "The city of Zaragoza in general",
      "With more than 2000 years …",
      "Of history, Zaragoza is famous for the massive Cathedral-Basilica of Our Lady of the Pillar, its Roman foundation, its cultural diversity, and its people's welcoming nature, yet its visitors discover much more among its streets. Zaragoza contains two majestic cathedrals, a fortified Islamic palace in the city center, massive remains of the Roman Caesaraugusta, Renaissance-style palace-houses, the unique treasures of Francisco de Goya's works, symbols of modern architecture, and one of the most diverse culinary scenes in Spain.",
      "A crossroads …",
      "Zaragoza, the capital of Aragon, is the fifth largest Spanish city by population. The capital on the Ebro lies at a crossroads between other major Spanish cities, and it is an ideal destination for a city break. Its international airport, high-speed train station, and radial road network put it within 2/3 hours of the main destinations in northern and central Spain, as well as southern France.",
      "A fertile destination for surprises …",
      "It is easy to feel at home in Zaragoza. The ease of access to its people and the accessibility of its spaces, along with the freshness of its blue skies, make it the best place for a city with a rich heritage, distinguished by its cultural diversity.",
      "Zaragoza also has a huge old quarter made for pedestrians, large green spaces with a unique character, kilometers of bike lanes, sustainable urban transport, a wide range of squares, viewpoints, balconies, corners, surprises, palaces, museums, churches, the warm social atmosphere of its streets, the culinary diversity of its restaurants, its tapas, and its nightlife.",
      "A huge city …",
      "Zaragoza is a huge heritage and historic site, where the legacy of its four ancestral cultures flourishes in its streets. Its main attraction, the Basilica of Our Lady of the Pillar, is the symbol of the city and the second cathedral of Zaragoza. Inside, you can find beautiful works by Francisco de Goya and the venerated sculpture of the Virgin of the Pillar. An essential part of visiting the basilica is climbing the tower of San Francisco de Borja.",
      "Additional tourist attractions …",
      "A few steps away is the Cathedral of the Savior (La Seo), the main historic temple in the city and a leading example of Aragonese Mudéjar art, which has been granted World Heritage status by UNESCO. Inside, it also houses one of the finest collections of Flemish tapestries from the fifteenth to seventeenth centuries.",
      "It is also essential to visit the beautiful Aljafería Palace, an eleventh-century Islamic fortress, built as a pleasure palace for the Taifa kings of Zaragoza. The palace, whose Mudéjar art has been declared a World Heritage Site since 2001, still surprises its visitors with the unexpected beauty of its Arab style, even in the north of Spain.",
      "The best way to discover the vast city of Zaragoza is through guided tours or aboard its tourist bus, whose route brings you closer to the city's main attractions and its large green spaces: José Antonio Labordeta Grande Park and the Luis Buñuel Water Park.",
      "The characteristics of the city of Zaragoza",
      "Zaragoza is the capital of the province of Zaragoza …",
      "It is also the capital of the region of Aragon in northeastern Spain, located on the Ebro River, with a population of about 678,000. One historian said of Zaragoza: it is one of the foundations of al-Andalus, large in diameter, populous, with extended outskirts, wide streets, fine houses and dwellings, connected gardens and orchards, and it has a strong stone wall, and it stands on the bank of a great river, part of which comes from the land of the Romans and part from the mountains of Qal'at Ayyub, and other than that.",
      "The waters of all these rivers gather above …",
      "The waters of all these rivers gather above the city of Tudela, then flow down to the city of Zaragoza. The city of Zaragoza is the White City, so named for the abundance of its plaster and lime, and one of its peculiarities is that no snake ever enters it — and if brought there, it dies. Some people claim there is a talisman for that, while others say that most of its buildings are made of marble, which is a type of alum salt, and that among its properties is that it does not allow snakes to enter a place where it is present, and likewise in several regions.",
      "Zaragoza has a great bridge …",
      "Which is crossed to reach the city, and it has impregnable walls and lofty buildings. Its name is derived from the name Caesaraugusta, after the one who built it. It is said that it was built in the shape of a cross and given four gates: a gate that, when the sun rises from its farthest point in midsummer, faces it at sunrise, and when it sets, faces the gate opposite it on the western side; and a gate that, when the sun rises from its farthest point in winter, faces it at sunrise, which is the southern gate, and when it sets, faces the gate opposite it.",
      "Among the most important landmarks of the city is the Aljafería Palace, built by al-Muqtadir, emir of the taifa of Zaragoza, in the second half of the eleventh century CE.",
      "Zaragoza, pronounced with a fatha on its first and second letters, then a damma on the qaf, a plain sin, and a plain ta, is a famous town in al-Andalus, whose lands connect with those of Tudela, known for sweet fruits that surpass all other fruits of al-Andalus. It is built on a great river, a river originating from the Cordillera Cantábrica mountains, renowned for its craftsmanship and refined management, standing at the forefront of its region.",
    ],
  },
};
