import type { Guide } from "./france-guides";

export const spainGuidesB: Guide[] = [
  {
    slug: "ibiza",
    title_ar: "جزر البليار (جزيرة ايبيزا)",
    title_en: "The Balearic Islands (Ibiza)",
    kicker_ar: "جزر",
    kicker_en: "Islands",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0939.jpg",
    blocks: [
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0939.jpg", cap_ar: "ايبيزا", cap_en: "Ibiza" },
      { type: "H3", ar: "اكتشف اسبانيا", en: "Discover Spain" , noNumber: true },
      { type: "H3", ar: "أجمل ما في جزر البليار – جزيرة ايبيزا", en: "The best of the Balearic Islands – Ibiza" , noNumber: true },
      { type: "H3", ar: "يالله نستمتع بأجمل جزيرة", en: "Let's enjoy the most beautiful island" , noNumber: true },
      { type: "P", ar: "تعتبر ايبيزا ، الواقعة في جزر البليار ، واحدة من الجزر الفريدة في اسبانيا ، وهي في الأصل الجزيرة التي يختارها العديد من المشاهير لقضاء العطلة ، وذلك بفضل تنوعها الطبيعي وثقافتها", en: "Ibiza, located in the Balearic Islands, is considered one of the unique islands of Spain. It is originally the island that many celebrities choose for their holidays, thanks to its natural diversity and culture." },
      { type: "P", ar: "وقد تم اعلانها كتراث عالمي من قبل اليونسكو ، وتشتهر بشكل خاص بشواطئها الجميلة والحياة الليلية المعروفة عالميا", en: "It has been declared a World Heritage Site by UNESCO, and it is especially famous for its beautiful beaches and its world-renowned nightlife." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0934.jpg", cap_ar: "ايبيزا", cap_en: "Ibiza" },
      { type: "P", ar: "ايبيزا مدينة فريدة من نوعها ، ففيها تجد مطعما للطاهي الاسباني باكو رونسيرو Paco Roncero (يعتبر الأغلى في العالم) وتجد أيضا ميناء موسوم بعلامة Blue 5 Star Marina (ميناء ايبيزا)", en: "Ibiza is a one-of-a-kind city; there you will find a restaurant by the Spanish chef Paco Roncero (considered the most expensive in the world), and you will also find a marina marked with the Blue 5 Star Marina label (Ibiza port)." },
      { type: "P", ar: "وهناك رحلات جوية مباشرة الى مطارها سانت جوزيف Sant Josep سواء من مدن اسبانية أخرى ، أو من وجهات أوروبية مختلفة ، فاذا كنت تنوي السفر على متن الباخرة فايبيزا متصلة بالعديد من المدن الاسبانية مثل برشلونة وفالنسيا ودانية Dénia وبالما دي ميورقة", en: "There are direct flights to its Sant Josep airport, whether from other Spanish cities or from various European destinations. If you intend to travel by ship, Ibiza is connected to many Spanish cities such as Barcelona, Valencia, Dénia and Palma de Mallorca." },
      { type: "P", ar: "وتتوفر على ثلاثة موانئ مهمة : ميناء ايبيزا Ibiza وسانتا ايولاريا Santa Eulària وسانت أنطوني Sant Antoni ، حيث يمكن الدخول اليها بالقوارب الخاصة والسفن المأجورة والرحلات البحرية", en: "It has three important ports: the port of Ibiza, Santa Eulària and Sant Antoni, which can be reached by private boats, chartered vessels and cruise ships." },
      { type: "H3", ar: "معالم لا يمكن اضاعة فرصة زيارتها", en: "Sights not to be missed" , noNumber: true },
      { type: "H3", ar: "جنوب الجزيرة", en: "South of the island" },
      { type: "P", ar: "سوف ترغب بزيارة العاصمة ، ايبيسا Eivissa ذات الأسوار المثيرة للاعجاب ، وهي مقبرة قديمة وميناء نشيط بفضل متاجره التي توفر مختلف الماركات ، وكذلك بفضل مقاهيه", en: "You will want to visit the capital, Eivissa, with its impressive walls; it is an ancient site and a lively port thanks to its shops offering various brands, as well as its cafés." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0936.jpg", cap_ar: "جنوب الجزيرة", cap_en: "South of the island" },
      { type: "H3", ar: "غرب الجزيرة", en: "West of the island" },
      { type: "P", ar: "وهناك مكان آخر يقع في غرب الجزيرة لا يقل أهمية ، وهو سانت أنطوني دي بورتماني Sant Antoni de Portmany : فهو مكان جيد لاقتناء هدايا من الجلد أو السيراميك أو المجوهرات", en: "There is another place on the west of the island that is no less important: Sant Antoni de Portmany, a good place to buy gifts made of leather, ceramics or jewellery." },
      { type: "P", ar: "وللتجول في الخليج حتى الوصول الى منطقة Caló d’es Moro ثم الاستمتاع بمشاهدة منظر غروب الشمس الأكثر شهرة في العالم ، فهناك العديد من الناس يفضلون الاستمتاع بهذه اللحظة في المقهي الشهير Café del Mar", en: "You can stroll around the bay until you reach the Caló d'es Moro area, then enjoy watching one of the most famous sunsets in the world; many people prefer to enjoy this moment at the famous Café del Mar." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0938.jpg", cap_ar: "غرب الجزيرة", cap_en: "West of the island" },
      { type: "H3", ar: "شرق الجزيرة", en: "East of the island" },
      { type: "P", ar: "وفي شرق الجزيرة يمكنك التعرف على Santa Eulària des Riu والتجول في الشوارع المرصصة بالحجارة لــ Es Puig de Missa أو السباحة في أحد شواطئها ذات الرمال الرقيقة ، وغير بعيد عن المنطقة سوف تجد السوق ذا الشهرة الواسعة Las Dalias ، الذي يقام كل يوم سبت ، حيث يمكنك اقتناء مجوهرات وتحف قديمة ولباس مثل لباس Adlib (نوع من اللباس المحلي في ايبيزا)", en: "In the east of the island you can discover Santa Eulària des Riu and wander the cobbled streets of Es Puig de Missa, or swim at one of its fine sandy beaches. Not far from the area you will find the widely famous Las Dalias market, held every Saturday, where you can buy jewellery, antiques and clothing such as Adlib fashion (a type of local dress in Ibiza)." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0935.jpg", cap_ar: "شرق الجزيرة", cap_en: "East of the island" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0937.jpg", cap_ar: "شرق الجزيرة", cap_en: "East of the island" },
    ],
  },
  {
    slug: "food",
    title_ar: "أكلات وأطباق اسبانية",
    title_en: "Spanish food and dishes",
    kicker_ar: "أكل",
    kicker_en: "Food",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0947.jpg",
    blocks: [
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0947.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
      { type: "H3", ar: "اكتشف اسبانيا", en: "Discover Spain" , noNumber: true },
      { type: "H3", ar: "أكلات وأطباق اسبانية شهية", en: "Delicious Spanish food and dishes" , noNumber: true },
      { type: "H3", ar: "يالله نتلذذ بالأكلات الاسبانية", en: "Let's savour Spanish cuisine" , noNumber: true },
      { type: "P", ar: "يعد بحر كانتابريا مع الجبال والوديان في المنطقة الداخلية ، خزانة الأطعمة الطبيعية لـ اسبانيا الخضراء ، حيث تعد أطباقا شهية تعتمد على الوصفات التقليدية ، ولكن أيضا مع ابداعات طهي بديعة ومبتكرة ورائدة ، مما ينتج فن أكل فريد مع أصناف متنوعة رائعة ومشهورة في جميع أنحاء العالم ، ومن المؤكد بعد أن تتذوقها ، ستعود مرة أخرى طلبا للمزيد ، وللعلم فانه يوجد في اسبانيا الخضراء أكثر من 50 مطعما حائزا على نجمة ميشلان ، ويستحوذ اقليم الباسك على أعلى نسبة", en: "The Cantabrian Sea, along with the mountains and valleys of the interior, forms the natural larder of Green Spain, where delicious dishes are prepared based on traditional recipes, but also with beautiful, innovative and pioneering culinary creations, producing a unique culinary art with wonderful varieties famous all over the world. Once you taste them, you are sure to come back for more. For your information, Green Spain has more than 50 Michelin-starred restaurants, with the Basque Country holding the highest share." },
      { type: "P", ar: "تفتخر كل منطقة في شمال اسبانيا بمطبخها الرائع ، فبداية من محار غاليسا الى الجودة الرائعة ونكهات أطباق أستورياس مثل يخنة فابادا وكذلك شراب التفاح ، ومجموعة متنوعة من مطبخ كانتابريا بدء من Cocido Montañes (يخنة مع الفاصوليا والخضروات واللحوم) وحتى الكعك المنفوش الى (sobaos pasiegos) وأيضا مع العادة المحلية الشائعة لـ الخروج لتناول مقبلات pintxos ، وهي النسخة الباسكية لمقبلات تاباس", en: "Every region of northern Spain takes pride in its wonderful cuisine, starting with Galician shellfish, moving to the great quality and flavours of Asturian dishes such as fabada stew and cider, and continuing with the variety of Cantabrian cuisine, from Cocido Montañés (a stew with beans, vegetables and meat) to fluffy sobaos pasiegos cakes, along with the popular local custom of going out for pintxos, the Basque version of tapas." },
      { type: "P", ar: "يعد فن الأكل في اسبانيا الخضراء فن حقيقي ويشكل جزء من التراث الثقافي للمنطقة ، وسترى ذلك بنفسك عندما تجلس في أي من مطاعم هذا البلد وحاناته", en: "The art of eating in Green Spain is a true art and forms part of the region's cultural heritage, and you will see this for yourself when you sit at any of this country's restaurants and bars." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0942.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0943.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0944.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0945.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0946.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0948.jpg", cap_ar: "أكلات اسبانية", cap_en: "Spanish cuisine" },
    ],
  },
  {
    slug: "weather",
    title_ar: "الطقس وفصول السنة",
    title_en: "The weather and the seasons of the year",
    kicker_ar: "طقس",
    kicker_en: "Weather",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0938.jpg",
    blocks: [
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2023/04/img_0938.jpg", cap_ar: "طقس اسبانيا", cap_en: "The weather in Spain" },
      { type: "H3", ar: "اكتشف اسبانيا", en: "Discover Spain" },
      { type: "H3", ar: "تعرف على طقس اسبانيا عبر مختلف فصول السنة", en: "Get to know Spain's weather across the different seasons" },
      { type: "H3", ar: "حيث تتبعك أشعة الشمس خلال كل موسم", en: "Where the sun follows you through every season" },
      { type: "P", ar: "اسبانيا بلد ذو مناخ معتدل على مدار السنة ولكنه لا يزال يحافظ على تناقضاته الموسمية ، هنا يمكنك التحقق من متوسط درجات الحرارة وساعات أشعة الشمس في بعض الوجهات الرئيسية ، كما نقدم لك المشورة بشأن نوع الملابس التي يجب احضارها لكل موسم ونقدم لك المزيد من المعلومات حول الطقس في اسبانيا", en: "Spain is a country with a moderate climate all year round, but it still keeps its seasonal contrasts. Here you can check the average temperatures and hours of sunshine in some of the main destinations, and we also offer advice on the kind of clothes you should bring for each season and give you more information about the weather in Spain." },
      { type: "H3", ar: "الطقس في اسبانيا", en: "Weather in Spain" },
      { type: "P", ar: "اسبانيا بلد مشمس مع حوالي 3000 ساعة من أشعة الشمس كل عام ، درجات الحرارة معتدلة ، ولكن لا تزال هناك اختلافات اعتمادا على مواسم ومناطق البلاد ، عادة ما تكون ألطف درجات الحرارة في الربيع والخريف ، مما يسمح لك بالاستمتاع بالهواء الطلق عمليا طوال اليوم ، يتم الوصول الى درجات الحرارة القصوى خلال شهري يوليو وأغسطس ، وهي ساخنة وجافة في جميع أنحاء البلاد ، تحدث أبرد درجات الحرارة خلال أشهر ديسمبر ويناير وفبراير ، وهي الأشهر الأكثر هطولا للأمطار ، خاصة في شمال اسبانيا", en: "Spain is a sunny country with about 3,000 hours of sunshine every year. Temperatures are moderate, but there are still differences depending on the season and the region of the country. The mildest temperatures are usually in spring and autumn, letting you enjoy the outdoors practically all day. Peak temperatures are reached during July and August, which are hot and dry across the whole country. The coldest temperatures occur during December, January and February, which are also the rainiest months, especially in the north of Spain." },
      { type: "H3", ar: "من الضروري أن تحزم معك التالي :", en: "Essentials you should pack:" },
      { type: "LIST", ar: ["النظارات الشمسية ، التي ستستخدمها على مدار السنة", "أحذية مريحة ، خاصة اذا كنت تزور المتاحف ، أو تذهب لمشاهدة معالم المدينة في المدن أو التنزه في الطبيعة", "حقيبة ظهر خفيفة ومريحة لحمل أغراضك ، على سبيل المثال ، النظارات الشمسية وكريم الشمس وزجاجة ماء ومظلة سفر صغيرة لأي احتمال"], en: ["Sunglasses, which you will use all year round", "Comfortable shoes, especially if you are visiting museums, sightseeing in cities or hiking in nature", "A light, comfortable backpack to carry your belongings, for example sunglasses, sunscreen, a water bottle and a small travel umbrella for any eventuality"] },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/04/img_4690.jpg", cap_ar: "ما يجب حزمه", cap_en: "What to pack" },
      { type: "H3", ar: "الشتاء", en: "Winter" },
      { type: "H3", ar: "من ديسمبر الى مارس", en: "From December to March" },
      { type: "P", ar: "هذه هي الأشهر الأكثر برودة ، على الرغم من أن اسبانيا ليست دولة ممطرة ، الا أننا نوصيك بحمل مظلة ، في الشمال ، يتكرر هطول الأمطار خلال هذه الأشهر ، في جميع أنحاء بقية البلاد ، قد يكون هناك عدة أيام ممطرة ، قد تكون سترة المطر فكرة جيدة", en: "These are the coldest months. Although Spain is not a rainy country, we still recommend carrying an umbrella. In the north, rainfall is frequent during these months, and across the rest of the country there may be several rainy days, so a rain jacket could be a good idea." },
      { type: "P", ar: "نوصيك بتعبئة الملابس والاكسسوارات الدافئة ، مثل الوشاح والقفازات ، في معظم أنحاء البلاد ، الأحذية المقاومة للماء ليست ضرورية حقا ، والأحذية المريحة تميل الى التوصية بها ، وربما الأحذية ، والجوارب السميكة ، الملابس المصنوعة من الأقمشة الدافئة مثل الصوف والفانيلا والصوف والملابس الداخلية الحرارية والجوارب والمعاطف الشتوية مطلوبة ، خاصة في البيئات الريفية ، اذا ذهبت الى جزر الكناري ، فان الشتاء مختلف تماما ولن تحتاج الى أكثر من سترة خفيفة", en: "We recommend packing warm clothes and accessories such as a scarf and gloves. In most of the country, waterproof shoes are not really necessary, and comfortable shoes tend to be recommended, along with boots and thick socks. Clothes made of warm fabrics such as wool and flannel, thermal underwear, socks and winter coats are needed, especially in rural areas. If you go to the Canary Islands, winter is completely different and you will not need more than a light jacket." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/04/img_4689.jpg", cap_ar: "الشتاء", cap_en: "Winter" },
      { type: "H3", ar: "الربيع", en: "Spring" },
      { type: "H3", ar: "من مارس الى يونيه", en: "From March to June" },
      { type: "P", ar: "يتفق الكثير من الناس على أن هذا هو أفضل موسم لزيارة اسبانيا ، الشمس دائما ما تكون في الخارج وكل يوم هناك المزيد من ساعات أشعة الشمس للاستمتاع بالهواء الطلق أثناء التنزه والأمسيات على المدرجات والمهارب الطبيعية", en: "Many people agree that this is the best season to visit Spain. The sun is always out, and every day there are more hours of sunshine to enjoy the outdoors while strolling and spending evenings on terraces and in natural surroundings." },
      { type: "P", ar: "خذ قمم بأكمام قصيرة ، أو قمم بأكمام طويلة بمواد رقيقة وجينز وفساتين ذات ألوان زاهية ، قد تكون الملحقات ، مثل النظارات الشمسية وقبعة الشمس والباشمينا وبعض الصنادل رفيقة سفر جيدة للاستمتاع بالصباح المشمس وبعد الظهر ، يحذرنا قول مأثور (En abril, aguas mil) زخات أبريل من حزم مظلة سفر صغيرة للاستحمام القصير ولكن المكثف في بعض الأحيان", en: "Bring short-sleeved tops, or long-sleeved tops in light fabrics, jeans and brightly coloured dresses. Accessories such as sunglasses, a sun hat, a pashmina and some sandals can be good travel companions for enjoying sunny mornings and afternoons. The saying (En abril, aguas mil) warns us of April showers, so pack a small travel umbrella for the brief but sometimes intense downpours." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/04/img_4688.jpg", cap_ar: "الربيع", cap_en: "Spring" },
      { type: "H3", ar: "الصيف", en: "Summer" },
      { type: "H3", ar: "من يونيه الى سبتمبر", en: "From June to September" },
      { type: "P", ar: "أشهر يونيو ويوليو وأغسطس وسبتمبر هي الأكثر سخونة وجفافا ، عادة ما تكون درجات الحرارة خلال النهار أكثر من 30 درجة مئوية ، في المناطق الداخلية وفي الجنوب ، قد تكون درجات الحرارة أكثر من 20 درجة في الليل ، يتمتع الشمال بمناخ أكثر اعتدالا مع درجات حرارة أكثر برودة وبعض الأمطار في مناطق مثل غاليسيا وأستورياس وكانتابريا", en: "The months of June, July, August and September are the hottest and driest. Daytime temperatures are usually above 30 degrees Celsius. In the inland areas and in the south, night-time temperatures can be above 20 degrees. The north enjoys a milder climate with cooler temperatures and some rain in regions such as Galicia, Asturias and Cantabria." },
      { type: "P", ar: "الشيء الأساسي الذي يجب حزمه لفصل الصيف في اسبانيا هو ملابس السباحة للاستمتاع بالشاطئ ، نوصي بارتداء ملابس فاتحة اللون ، الملابس البيضاء هي أيضا جزء بارز من أزياء ايبيزا ، هذه الملابس مغرية ومريحة في الأقمشة الرقيقة العائمة ، مثل الكتان والقطن ، بالنسبة للأحذية ، عادة ما يتم ارتداء الصنادل أو الشبشب ، الأنماط والسراويل القصيرة بدون أكمام شائعة أيضا", en: "The essential thing to pack for summer in Spain is swimwear to enjoy the beach. We recommend wearing light-coloured clothes; white clothing is also a prominent part of Ibiza fashion. These clothes are appealing and comfortable in light, flowing fabrics such as linen and cotton. For footwear, sandals or flip-flops are usually worn, and sleeveless tops and shorts are also common." },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/04/img_4687.jpg", cap_ar: "الصيف", cap_en: "Summer" },
      { type: "H3", ar: "الخريف", en: "Autumn" },
      { type: "H3", ar: "من سبتمبر الى ديسمبر", en: "From September to December" },
      { type: "P", ar: "تبدأ درجة الحرارة في الانخفاض والجو أكثر برودة أول شيء في الصباح وفي وقت متأخر بعد الظهر ، تبدأ الملابس الدافئة والوشاح الخفيف والسترات أو السترات في أن تصبح ضرورية ، في هذا الوقت من العام ، لا يزال هناك العديد من الأيام المشمسة ، خاصة من مدريد نحو الجنوب", en: "Temperatures start to drop and the air becomes cooler first thing in the morning and late in the afternoon. Warm clothes, a light scarf and jackets or sweaters start to become necessary. At this time of year there are still many sunny days, especially from Madrid southwards." },
      { type: "P", ar: "يوصي الكثير من الناس بأخذ عدة طبقات من الملابس الخفيفة بدلا من المعاطف الثقيلة أو الدافئة جدا ، بهذه الطريقة يمكنك التكيف بسهولة مع أي وقت من اليوم ، على سبيل المثال ، عندما يأتي المساء ، قد تشعر بالبرودة في المناطق الجبلية ، أو في المناطق الساحلية بسبب الرطوبة ، هناك عواصف عرضية وتدفقات من الطقس البارد في الخريف", en: "Many people recommend taking several layers of light clothing instead of heavy or very warm coats. This way you can easily adapt to any time of day. For example, when evening comes, you may feel cold in mountainous areas, or in coastal areas because of the humidity. There are occasional storms and spells of cold weather in autumn." },
    ],
  },
  {
    slug: "flag",
    title_ar: "مدلولات علم مملكة اسبانيا",
    title_en: "The meaning of the flag of the Kingdom of Spain",
    kicker_ar: "علم",
    kicker_en: "Flag",
    image: "https://i0.wp.com/100region.com/wp-content/uploads/2022/10/img_4686.jpg",
    blocks: [
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/10/img_4686.jpg", cap_ar: "علم اسبانيا", cap_en: "The flag of Spain" },
      { type: "P", ar: "أهمية علم الدولة", en: "The importance of the national flag" },
      { type: "IMG", src: "https://i0.wp.com/100region.com/wp-content/uploads/2022/03/img_3652.jpg", cap_ar: "علم مملكة اسبانيا", cap_en: "The flag of the Kingdom of Spain" },
      { type: "P", ar: "علم مملكة اسبانيا", en: "The flag of the Kingdom of Spain" },
    ],
  },
];
