export const SPAIN_EN_3: Record<string, { title: string; values: string[] }> = {
  granada: {
    title: "Discover everything about the elegant city of Granada",
    values: [
      "", // IMG
      "Discover Spain",
      "Discover everything about the elegant city of Granada",
      "Granada Spain",
      "On this page you will learn about the following:",
      "Granada in general",
      "Location and population of Granada",
      "The history of Granada",
      "Granada's tourist landmarks",
      "Let's fasten our belts and fly to the city of beauty and history!",
      "Granada in general",
      "Granada is the capital of a province…",
      "Granada is in an autonomous Andalusian region in Spain. It lies at the foot of the Sierra Nevada mountains (the Snow Mountains), at the confluence of four rivers — the Darro, the Genil, the Monachil and the Beiro — and belongs to the Vega de Granada district. The city sits at an average elevation of 738 metres above sea level, yet it is only an hour's drive from the Mediterranean coast, the Costa Tropical. Nearby lies the Sierra Nevada ski station, where the International Ski Federation's World Downhill Skiing Championship was held in 1996.",
      "The Iberians, Romans and Visigoths settled the area since ancient times, and the existing settlement became a major city in al-Andalus in the eleventh century during the presence of the Zirid taifa in Granada. In the thirteenth century it became the capital of the Emirate of Granada under Nasrid rule, and it was the last territory ruled by Muslims in the Iberian Peninsula. The Catholic Monarchs conquered Granada in 1492, and it gradually turned into a Christian city over the course of the sixteenth century.",
      "The Alhambra, an ancient Nasrid fortress and palace, is located in Granada; it is one of the most famous monuments of Islamic architecture and one of the most visited tourist sites in Spain. The influence of the Islamic period and Moorish architecture has also been preserved in the Albaicín quarter and other medieval remains of the city. The sixteenth century also witnessed a flourishing of Mudéjar and Renaissance architecture, followed later by the Baroque and Churrigueresque styles. Granada is also known within Spain for the University of Granada, which has an estimated 82,000 students spread across five different campuses in the city. The pomegranate (in Spanish: granada) is Granada's emblem.",
      "Location and population",
      "Granada lies at the foot of the mountains…",
      "the Sierra Nevada, at the confluence of three rivers: the Darro, the Beiro and the Genil, at an elevation of 738 metres above sea level. Granada's population is approximately 240,099 people, ranking it 13th among the largest urban areas in Spain, though 3.3% of residents do not hold Spanish nationality, and a large proportion of them, 31%, come from regions of South America. Below is the location of the city of Granada on the map.",
      "https://maps.app.goo.gl/82GnFw6RqoG3X8vYA?g_st=com.automattic.jetpack.JetpackShare",
      "The history of Granada",
      "Granada used to be called Ilbira…",
      "until the middle of the eighth century AD. In the eleventh century, the Berber Zirids moved the capital from the city of Ilbira to the city of Granada. Granada, or Agranata, is a name derived from the Latin origin (granatum, pomegranate) meaning the pomegranate, and it was so named for its beauty and for the abundance of pomegranate gardens surrounding it. Likewise, Yaqut's dictionary states that the meaning of Granada is 'the pomegranate' in the language of the non-Arabs of al-Andalus (the Hispanic language), and that the country was so named for its beauty. It is also said that it was so named because it was built on the spot where pomegranates were first planted after being brought there from Ifriqiya, and it is also said that it was so named because, by its location and its division across two hills, its dense dwellings resemble a split-open pomegranate. The pomegranate (in Spanish, granada) is the emblem of the city of Granada.",
      "Granada's landmarks",
      "Among the greatest cultural treasures…",
      "The Alhambra Palace and the Generalife are considered among the greatest cultural treasures of Granada shared by Muslims, Jews and Christians. The Generalife is a set of gardens attached to the palace, distinguished by its location and unique design, as well as by the diversity of its flowers, plants and fountains. The Alhambra represents the crowning achievement of the most notable architectural works of the Nasrid dynasty between the thirteenth and fourteenth centuries, and most of the Alhambra was built during the reigns of Yusuf I and Muhammad V, between 1333 and 1354.",
      "Granada is also known within Spain because of the standing of the University of Granada, and it is said that Granada is one of the best three cities for university students (the other two being Salamanca and Santiago de Compostela).",
      "The Alhambra",
      "The Alhambra was built…",
      "during the era of the Nasrid dynasty, and it was included among UNESCO World Heritage Sites in 1984. It is considered one of the most important and most visited sites in Spain, and it consists of a defensive area, the Alcazaba, residences for rulers and commoners, a palace for the Nasrid caliphs, the palace itself, in addition to gardens including the Generalife. The Alhambra sits atop a small plateau on the south-eastern edge of the city, on the slopes of the Snow Mountain (in Spanish: Sierra Nevada) above the valley. Beside it stood some dwellings built before the arrival of the Muslims, and the palace is fully surrounded by a wall bordered to the north by the valley and to the south by the Sabika hill.",
      "In the eleventh century the Alhambra developed into a fortified city that became a military stronghold controlling the entire city, but in the thirteenth century, with the arrival of the first caliph of the Nasrid dynasty, Muhammad ibn Nasr (1238–1273), the seat of the caliphate was established at the Alhambra. Senior officials were also housed there, including court officers and elite soldiers, during the thirteenth and fourteenth centuries.",
      "In 1527 the Holy Roman Emperor Charles V demolished part of the Alhambra to build his own palace, which bore his name, and some of the Catholic kings altered some of the palace's rooms after seizing it in 1492. Charles V also built a dressing room for his wife Isabella above one of the towers.",
      "In the eighteenth century, maintenance of the palace stopped for a hundred years, and during the French occupation of the palace large parts of the fortress were lost. Continuous repairs and restorations did not begin until the nineteenth century, and the palace now houses the Alhambra Museum, which contains pieces excavated from the site itself, in addition to the Museum of Fine Arts.",
      "The Generalife",
      "It is a set of gardens attached to the palace…",
      "and it was a place of rest and recreation for the Muslim princes of Granada when they wanted to escape the tedium of official life in the palace. It is located in a spot that allows it to be seen from all over the city, and the palace and gardens were built in the Nasrid style during the reign of Muhammad III (1302–1309), and were redesigned shortly afterwards by Abu al-Walid Ismail (1313–1324). It is now one of the most attractive places for tourists in Granada.",
      "Granada Cathedral",
      "Granada Cathedral was built…",
      "over the famous mosque of Granada built by the Nasrids in the centre of the city, and construction work began during the Spanish Renaissance in the early sixteenth century. Shortly after the fall of Granada at the hands of the Catholic Monarchs (Ferdinand II and Isabella), Juan Gil de Hontañón and Enrique Egas were commissioned to carry out the construction, and many buildings were also erected during the reign of Charles V. Granada Cathedral was built in the style of Toledo Cathedral, that is, in the Gothic style, which was the prevailing architectural style in Spain in the early sixteenth century. But in 1529 the Catholic authority cancelled Enrique Egas's commission and appointed Diego de Siloé, who completed his predecessor's work but added elements of the Renaissance style. Over time the bishopric carried out new architectural projects, such as the redesign of the cathedral's main façade in 1664 by Alonso Cano, to introduce Baroque elements, and in 1706 the cathedral's residence was built.",
      "The Royal Chapel",
      "The Catholic Monarchs issued…",
      "a royal decree on the thirteenth of September 1504 choosing Granada as the city in which they would be buried, so the Royal Chapel was built there on the ruins of the terrace of Granada's mosque so that the Catholic Monarchs and their children, Joanna and Philip I, could be buried. Construction of the Royal Chapel began in 1505 by Enrique Egas and took several stages to complete, its design combining the Gothic and Renaissance styles.",
      "The Albaicín",
      "It is a quarter of Andalusian origin…",
      "it is a quarter of Andalusian origin and is a major destination for many visitors who come to it for its historic and architectural standing and its natural scenery. Archaeological discoveries in the area date back to ancient times, and it grew in importance with the arrival of the Zirids in 1013, who built defensive walls around it. Under the Nasrid dynasty the quarter underwent great development, and it is distinguished by its narrow streets arranged in a grid pattern extending from the top of the city down to the river below.",
      "During the Islamic era the Albaicín was known for its many revolts against the caliph, and at that time it was home to craftsmen, artisans and aristocrats. With the Christian takeover it gradually began to lose its lustre, and under Philip II, after the Muslims were expelled from al-Andalus, the quarter was emptied of all its inhabitants.",
      "In 1994 UNESCO listed the Albaicín among World Heritage Sites, and among the architectural treasures of the Albaicín are the walls of the old Alcazaba dating back to the Zirid era, the walls built during the Nasrid era, the towers of the Alcazaba, and the main mosque which was converted into a church.",
      "Granada is different!",
      "Friendly and majestic…",
      "this is the ideal description of the province that seduces the visitor with its unmatched beauty. The city of Granada and its province make anyone fall in love with them: the unique and famous charm of flamenco in Sacromonte, the city of the Alhambra, and the wonders of nature displayed in the impossible landscapes such as those found in the Geopark. It is the best choice for lovers of culture and nature.",
      "Why visit the city of Granada?",
      "We will give you many reasons to visit Granada in this list of essential places in the city, but the main reason to visit the city of Granada is the beauty and charm of the Alhambra fortress, which has inspired many artists who fell in love with it and with Granada.",
      "No one remains indifferent: from local artists born in Granada such as Federico García Lorca, to those who once visited the city and province and were captivated by its beauty, such as Washington Irving, who ended up writing works such as Tales of the Alhambra.",
      "What should you see in the city of Granada?",
      "Among the places you should not miss in Granada, we suggest this list of must-see attractions.",
      "The massive fortress that makes up the Alhambra in Granada is the very heart of the city and the province. Moreover, if you are in Málaga, Seville and so on, you should also come and see one of the most visited landmarks in Andalusia.",
      "Lose yourself in one of the huge complexes that have been preserved almost intact, which was for a long time a city of palaces, gardens and ancient fortresses that once housed the court of the Nasrid kingdom.",
      "The Albaicín, one of the most iconic quarters in the city of Granada, is the area that today preserves all the splendour of the Arab world that once dominated our city.",
      "If we had to highlight one thing about this quarter, it would be the spot where we stop to take the most beautiful photo ever imagined, at the Mirador de San Nicolás. From here you can enjoy a panoramic view of the Alhambra, considered to offer the most beautiful sunset in Europe.",
      "Wandering through this place means finding a maze of white houses, typical taverns and tea shops in every square.",
      "Right next to the Albaicín, we find the famous quarter called Sacromonte, well known as the cradle of flamenco, but also because of its famous cave houses where gypsies and artists of Granada play their music. Nowadays all this is mixed with the cave houses of Cerro de San Miguel and Camino del Sacromonte, in addition to the caves that offer daily flamenco shows.",
      "Other iconic quarters include the Realejo, the old Jewish quarter of the city of Granada; it offers its visitors many contrasts, combining neighbourhoods with the best murals by the famous Niño de las Pinturas, and important squares such as the Campo del Príncipe, and much more.",
      "In the centre of the city stands Granada Cathedral, a symbol of the Catholic conquest. When Queen Isabella the Catholic managed to conquer the city, the first thing she did was order the construction of a cathedral over the main mosque of Granada, making this temple a unique masterpiece in Spain.",
      "The Catholic Monarchs also ordered the construction of the Royal Chapel in the square directly behind the cathedral, in the Isabelline Gothic style. It was chosen to be the burial place of the Catholic Monarchs and can still be visited today. Aside from them, you will also see the burial of their daughter, the so-called Joanna the Mad, and her husband Philip the Handsome; in fact, you will discover that other people are buried here too, but you should visit the place to learn more.",
      "Attractions to visit in the province of Granada",
      "If you decide to visit the city of Granada, you should leave time to explore the beauty of its province. You will find that it contains many contrasts, areas and zones that can be separated and distinguished by the natural beauty of its landscape, terrain, and of course its culture, or rather its cultures.",
      "It is located in the south-east of the Iberian Peninsula between the Penibaetic mountain range and the coast of Granada known as the Costa Tropical. Now let's talk about the best plans for organising your stay.",
      "The Sierra Nevada is famous for the Pradollano ski resort, which belongs to Monachil. These mountains are part of the Penibaetic system and rise snow-covered in winter, making any visitor fall in love with them.",
      "From any point in the city you can see the mountains, and they have much to offer, making them one of those places you must not miss.",
      "In the Sierra Nevada National Park you will find Güéjar Sierra with spectacular landscapes such as the Vereda de la Estrella, or Monachil with an impressive trail featuring hanging bridges and wonders such as Los Cahorros. Climbing the peaks of Mulhacén or Veleta is another wonderful activity you can undertake if you decide to get to know Granada's great mountains.",
      "When the Arabs were expelled from the city of Granada, they chose what is known as the Alpujarra. The region lies in the south-eastern part of the province of Granada, and it is the area occupying most of the southern face of the Sierra Nevada, characterised by rugged relief.",
      "An interesting fact is that we can speak of two Alpujarras, since one is the more famous, the Alpujarra of Granada, while the other is the Alpujarra of Almería; the distinction arises from the location of the lands each occupies within its own province.",
      "Getting to know this region means getting to know its white villages, understanding its architecture and its famous terrain (the flat roofs) that make up the distinctive landscape of this area.",
      "Nature, culture and legend come together in this destination; there are many places you should not miss, for example Lanjarón, Bubión, Capileira, Trevélez.",
      "The coast of Granada is called the Costa Tropical because it enjoys a special local climate, the unique beauty of towns such as Nerja or Frigiliana, and the simplicity of Granada that can be seen at every one of this coast's most important beaches.",
      "This tropical region has an average temperature of 18°C in winter and 25°C in summer; for this reason, this unique stretch of Mediterranean coast has become a unique place for growing tropical fruits and vegetables in a traditional, high-quality manner. Here the sun shines all year round.",
      "There are many places worth visiting, but perhaps one of the least famous is the impressive Geopark of Granada, recently declared as such because of its unique shape and landscapes.",
      "The Geopark brings together 72 sites of geological importance, some of international significance, spanning an area of 4,722 square kilometres, easily comparable to the famous Colorado Canyon by lovers of the most impressive landscapes.",
      "Two main destinations are worth visiting: Guadix and Gorafe. On the one hand, Guadix has great cultural interest, being full of life and traditions that stand out for its landmarks and its famous cave-house quarter. On the other hand, Gorafe is a place of outstanding archaeological importance; the megalithic park of Gorafe surrounds the municipality with sites of archaeological importance spread throughout its geography. It is now possible to stop at the interpretation centre and learn about the history and legends surrounding this unique region of the province of Granada.",
    ],
  },
  seville: {
    title: "Discover everything about the city of Seville",
    values: [
      "", // IMG
      "Discover Spain",
      "Discover everything about the city of Seville",
      "On this page you will learn about the following:",
      "Seville in general",
      "Origin of the name",
      "The history of Seville",
      "Seville's location and population",
      "Seville's climate",
      "Tourism in Seville",
      "Seville Football Club",
      "As long as we have a holiday .. so why not travel to Seville?",
      "Seville is the capital of the region of Andalusia and of the province of Seville in southern Spain, and it lies on the banks of the Guadalquivir River. It is the fourth largest city in Spain by population, after Madrid, Barcelona and Valencia, with an area of 140.8 km².",
      "Seville rose to great fame during the Islamic rule of Spain in the Middle Ages, and it was also called Hims after the Levantine troops who first settled there. In the mid-ninth century AD, Abd al-Rahman II ordered the construction of a naval fleet and an arms-manufacturing house there. Among its most famous rulers was al-Mu'tamid ibn Abbad, and among its most important landmarks is the Giralda tower, built by order of Sultan Abu Yusuf Yaqub al-Mansur al-Muwahhidi. Among its most prominent residents at the time was Ibrahim ibn Sahl, famous for his poetry collection. The city is famous as the city of art and music in al-Andalus.",
      "Origin of the name",
      "Origin of the word .. Spal is the oldest known name for Seville. It appears to have originated during the Phoenician colonisation of the Tartessian culture in south-western Iberia. According to Manuel Pellicer Catalán, it means 'lowlands' in the Phoenician language, similar to Hebrew. During Roman rule, the name was Latinised as Hispalis. After the Islamic conquest, this name was adapted into Arabic as Ishbiliya (Arabic: أشبيلية), and since there is no 'P' sound in Arabic, it was replaced with 'B'. Latin replaced the suffix with the indirect Arabic equivalent of '-iyya', and the stressed 'a/æ' shifted to 'i/ط', a phenomenon called imela. The English 'Seville' and the Spanish name are derivatives of Ishbiliya.",
      "The emblem",
      "'NO8DO' is the official emblem of Seville, and it is popularly believed that the riddle refers to the Spanish 'no me ha dejado', meaning ('Seville has not abandoned me'), with the figure eight in the middle representing 'madeja', a skein of wool thread. It is mentioned that the legend earned this title from King Alfonso X, who was residing at the Alcázar in the city and was supported by the citizens against his son, later Sancho IV of Castile, when the latter attempted to usurp the throne from him. The emblem appears on the municipal flag and is featured on the city's property, such as manhole covers, and on the tomb of Christopher Columbus in the cathedral.",
      "History",
      "Seville's history spans more than two thousand years, and the passage of various peoples has shaped the growth of a city with a distinctive character. Seville was a Roman city known early on as Hispalis; the nearby Roman city of Italica gives an impression of what Hispalis was like in the later Roman period.",
      "The Roman remains found in Seville include the remains of an aqueduct. After the successive victories of the Vandals and Visigoths in the province of Hispania in the fifth and sixth centuries, the Muslims conquered the city in 712 and it became an important centre for Muslims in al-Andalus.",
      "Early periods",
      "Seville flourished in the days of Islamic rule over Spain, and Abd al-Rahman II ordered the construction of a naval fleet and an arms-manufacturing house there in the mid-ninth century AD. Among its most famous rulers was al-Mu'tamid ibn Abbad, and it was named Hims after the settling of Levantine troops there. Among its landmarks is the Giralda tower, built by order of Sultan Abu Yusuf Yaqub al-Mansur al-Muwahhidi.",
      "The Islamic era",
      "The Muslims conquered Seville in (94 AH – 713 AD) under the leadership of Musa ibn Nusayr, after a siege lasting one month, and appointed over it Isa ibn Abdullah al-Tawil, its first Muslim governor.",
      "In 95 AH, Abd al-Aziz ibn Musa ibn Nusayr succeeded his father as governor of al-Andalus and settled in Seville, making it his capital.",
      "In 97 AH, Abd al-Aziz ibn Musa was killed in Seville, and after him al-Andalus was governed by Ayyub ibn Habib al-Lakhmi, who moved the capital to Córdoba.",
      "In 214 AH, Abd al-Rahman al-Awsat built the first great mosque there, the mosque of Muhammad ibn Umar ibn Adis.",
      "In 226 AH the Normans raided Seville and burned its mosque, but the Andalusian forces inflicted a decisive defeat on them near the village of Talyata north of Seville.",
      "Castilian rule",
      "In 231 AH the city's first wall was built, along with the arsenal, which still stands in its place to this day.",
      "In 300 AH, Abd al-Rahman al-Nasir crushed the revolt of Banu al-Hajjaj and Ibn Khaldun in Seville.",
      "In 301 AH, Ibn al-Sulaym, the first governor appointed by Abd al-Rahman al-Nasir, demolished the wall of Seville and rebuilt the emirate's palace.",
      "The golden age",
      "In 414 AH the era of the Taifa kingdoms began, when Abu al-Qasim Muhammad ibn Abbad, the qadi of Seville, seized control of its government and established the state of Banu Abbad.",
      "In 484 AH, Seville and Córdoba fell into the hands of the Almoravids, and the Almoravid commander Sir ibn Abi Bakr seized Seville and demolished the palaces of Banu Abbad.",
      "The 18th century",
      "In 549 AH the Almoravid rule in Seville ended at the hands of the Almohad commander Baraz ibn Muhammad al-Masufi, and the ruler of al-Andalus made Seville his capital.",
      "In 580 AH Abu Yaqub Yusuf prepared his great campaign against western al-Andalus in Seville, and was martyred during the Battle of Shantarin in Portugal; he was succeeded by his son Yaqub, and during his era the Almohad constructions were completed.",
      "In 596 AH the golden age of Seville ended with the death of Yaqub, who had titled himself al-Mansur.",
      "In 646 AH, Ferdinand III, King of Castile and León, besieged Seville and entered it after a siege lasting a year and five months.",
      "In the following years the sultans of the Marinid dynasty of Marrakesh tried to reclaim the city from the Christians, but their attempts failed, and thus Seville passed out of Muslim hands.",
      "The 19th and 20th centuries",
      "Following the Christian takeover, public buildings including churches were erected, and later the city experienced another golden age of development brought about by the accumulation of wealth from the granting of a monopoly on trade with the Spanish territories in the New World. After silt built up in the Guadalquivir, the city settled into a relative economic decline, and Seville's development in the nineteenth and twentieth centuries was marked by population growth and increasing industrialisation.",
      "Seville fell very quickly to Franco's forces near the beginning of the Spanish Civil War in 1936, because of its proximity to the invasion force coming from Morocco. After Franco's forces seized the city, resistance continued among the working class in some areas for some time, until a series of fierce reprisals took place.",
      "Seville's location and population",
      "Seville is located on a plain of the Guadalquivir River, with an average ground elevation of 7 metres (23 feet) above sea level. Its residents are known as Sevillanos, and the population of the city with its suburbs exceeds 1.5 million people.",
      "Climate",
      "Seville's climate is a Mediterranean climate with oceanic influences. The annual average temperature is 18.6°C, making it one of the hottest cities in Europe, but winters are mild, and January is the coolest month, with an average maximum temperature of 15.9°C and a minimum of 5.2°C. Summer is very hot, and August is considered the hottest month, with an average maximum temperature of 35.5°C and a minimum temperature of 19.4°C. Every year the temperature exceeds 40°C on several occasions.",
      "The extreme temperatures recorded at the weather station of Seville Airport are -5.5°C in February 1956, and 46.6°C in July 1995.",
      "Rainfall varies from 600 to 800 mm per year, concentrated in the period from October to April, and December is considered the rainiest month, with an average rainfall of 95 mm. On average there are 52 days of rain, 2,898 hours of sunshine, and four days of frost per year.",
      "Main attractions of the city",
      "Seville Cathedral was built from 1401 to 1519 on the former site of the city's mosque, and Seville Cathedral is among the largest of all Gothic medieval cathedrals, both in terms of area and volume; its interior is the longest in Spain, and it is lavishly decorated, with a large amount of gold. The cathedral reused some of the columns and elements of the mosque, most famously the Giralda, originally a minaret, which was converted into a bell tower topped by a statue, known locally as El Giraldillo, representing Faith. Inside, the tower was built with ramps instead of stairs, to allow the muezzin and others to ascend to the top. The Giralda rises majestically above the rooftops of Seville's houses and is considered the city's most important landmark. It was built in 1184 as the minaret of Seville's great mosque, which, along with its minaret, was converted into a cathedral. The Giralda is 97.5 metres tall, and its rotating weathervane top was built in the sixteenth century, since when the Giralda has become known by this name after the statue atop it.",
      "Facing Seville Cathedral is the Alcázar, built from the old Moorish palace of the city; construction began in 1181 and continued for more than 500 years, also during the Renaissance. The gardens are a mixture of Moorish, Andalusian and Christian traditions.",
      "The city hall was built in the sixteenth century, and the Plaza Nueva was built in the nineteenth century in a traditional-modern style.",
      "The University of Seville is located within the original site of the first tobacco factory in Europe. The Almoravids devised a new system for the layout of walls, increasing the internal and external corners of the wall so that it took the form of jagged, zigzagging lines. The advantage of this system was that it let enemy soldiers advance into one of the corners, then attackers would rush at them from atop the walls along the paths and inflict heavy casualties on them; this system resembles a spring which, when pressed and then released, springs forward with force and strikes whatever is in front of it. A section of these walls in Seville still stands, known as the Wall of Macarena, and it extends from the Macarena Gate to the Córdoba Gate, with some of its remains scattered afterward in the garden of the Instituto del Valle.",
      "Among Seville's surviving landmarks is the front wall built and erected by the ruler Abu al-Ala Idris in 1223, around which a moat was dug, and from which a low wall extended to the Guadalquivir River, ending in a huge tower with many sides — the Tower of Gold, which still stands today. Opposite this tower is a similar tower on the nearby shore of the city, linked to it by a huge iron chain that prevented ships from passing at night on the Guadalquivir River, to protect the city from infiltration via the river.",
      "Seville club",
      "Sevilla Fútbol Club is the football club of the city of Seville, and it has a long history in European football; it was founded in October 1905, and is considered the oldest Sevillian club and the second oldest club in Andalusia. It was the first Andalusian club to play in the European Cup, now known as the UEFA Champions League, in the 1957–58 season. Sevilla FC has also played twice in the European Cup Winners' Cup.",
    ],
  },
  "costa-del-sol": {
    title: "The Complete Guide to Costa del Sol",
    values: [
      "Discover Spain",
      "The Complete Guide to Costa del Sol",
      "Who could resist its beauty? It flaunts the most gorgeous scenery!",
      "", // IMG
      "Where is Costa del Sol located?",
      "Costa del Sol is the name given to the Mediterranean coastline located in southern Spain, stretching between Sotogrande in the west and Nerja in the east. The Costa del Sol area forms the southern extension of the Andalusia region, and Málaga is considered its capital.",
      "What does Costa del Sol look like?",
      "The Costa del Sol area boasts many famous resorts, making it one of the most popular places to spend a holiday in Spain, in addition to being one of the best European choices for relocation. It also enjoys wonderful weather all year round, as well as attractive beaches, various facilities, stunning views, and constant transport links.",
      "The Costa del Sol area can be divided into three zones:",
      "Western Costa del Sol…",
      "This area lies between Sotogrande and Marbella and is distinguished by the resorts of Manilva, Estepona and Marbella, in addition to the town of San Pedro and the white villages of Benahavís, Casares, Istán and Ojén. The western side of the Costa del Sol is home to some of the most luxurious resorts and most expensive properties, in addition to the Golden Mile of Marbella, Puerto Banús and the Zagaleta area.",
      "Central Costa del Sol…",
      "This area is considered one of the most developed and lies between Marbella and Málaga. It contains the famous resorts of Mijas Costa, Fuengirola and Benalmádena, in addition to Torremolinos. The Costa del Sol is one of the areas where significant tourism began in the sixties.",
      "Eastern Costa del Sol…",
      "This area lies between Málaga and Nerja, and it is a lesser-known area for being quiet and less developed. Torre del Mar, Torrox and Nerja are considered the most famous resorts of the eastern side of the Costa del Sol.",
      "How long is the Costa del Sol?",
      "The Costa del Sol stretches for 150 km along the Mediterranean coast, and despite this, its width is limited due to the presence of high mountains along most of the coast.",
      "What is the population of the Costa del Sol?",
      "The official population of the Costa del Sol rises to more than a million people. The town of Istán is considered the smallest of the eleven municipalities in the Costa del Sol, with a population of only 1,700, while Marbella is considered the largest municipality, with a population of about 140,000, and Málaga is home to about 568,000 people.",
      "What is the proportion of foreign residents in the Costa del Sol?",
      "Officially, about 300,000 people are foreign residents in the Costa del Sol, making up 18% of the total population. In some resorts such as Mijas and Marbella this proportion makes up half of the population of foreign residents. Two-thirds of foreigners in the Costa del Sol are of European nationalities, with British nationals representing the largest proportion, with 75,000 foreigners having made the Costa del Sol their home.",
      "What is the weather like in the Costa del Sol?",
      "The weather of the Costa del Sol is considered one of the most important tourist draws, as this area enjoys more than 320 sunny days a year, characterised by little rainfall and moderate temperatures throughout the year. The weather can be hot during summer, with temperatures reaching more than 30 degrees, but during winter it rarely drops below 16 degrees during the day.",
      "What are the arrangements for reaching the Costa del Sol?",
      "The Costa del Sol can be reached easily, especially if you are travelling from a European city. Málaga Airport ranks as the third busiest airport in Spain, welcoming more than 15 million passengers annually. Málaga Airport serves more than 100 airports from all over the world, including the largest Spanish cities, most European capitals and New York (in summer), and is served by nearly 70 airlines throughout the year.",
      "If you will be staying at a resort in the western Costa del Sol and are travelling from the United Kingdom, it is better to look for flights to Gibraltar Airport.",
      "How long do flights to the Costa del Sol take?",
      "From the United Kingdom, Ireland and France: flights take between two and a half and three hours",
      "From central Europe: flights coming from Germany take at least three hours",
      "From the United States: flights from Málaga to New York take between seven and eight hours",
      "How far is Málaga Airport from the Costa del Sol?",
      "The distance from Málaga Airport to the city centre is 8 km, about 10 minutes by car",
      "The distance from Málaga Airport to Benalmádena is 10 km, about 15 minutes by car",
      "The distance from Málaga Airport to Fuengirola is 24 km, about 20 minutes by car",
      "The distance from Málaga Airport to Marbella is 50 km, about 40 minutes by car",
      "The distance from Málaga Airport to Estepona is 80 km, about 55 minutes by car",
      "The distance from Málaga Airport to Manilva is 90 km, about 65 minutes by car",
      "The distance from Málaga Airport to Torrox is 65 km, about 45 minutes by car",
      "The distance from Málaga Airport to Nerja is 70 km, about 50 minutes by car",
      "What is the distance between the Costa del Sol and Gibraltar Airport?",
      "Gibraltar Airport is about 30 km from Manilva, 48 km from Estepona and 76 km from Marbella, in addition to which at least 30 minutes are needed to cross the border between Spain and Gibraltar.",
      "What are the most important attractions in the Costa del Sol?",
      "There is an endless list of attractions in the Costa del Sol, the most important of which are the beaches on the Mediterranean Sea, in addition to the many resorts that offer a wide range of beaches to suit everyone.",
      "In addition, there are multiple attractions such as entertainment options; besides the beaches of the Costa del Sol, there are multiple options for all tastes. Sports lovers can choose among more than 60 golf courses (some golf courses in the Costa del Sol are among the most famous in the world), marinas, tennis and racquet clubs, as well as countless opportunities to practise outdoor sports such as climbing, long-distance hiking, boating, in addition to skiing in the neighbouring Sierra Nevada mountains, which are only two hours away from the resorts of the Costa del Sol.",
      "Family activities in the Costa del Sol vary, including safari trips at Selwo Aventura through a visit to one of the best animal parks in the world, located in Fuengirola, fun at the water park in Torremolinos and Mijas, and a cable car ride to the top of the mountain in Benalmádena. Also worth mentioning is Tivoli World, Sea Life, a butterfly park, a music museum and dolphin venues.",
      "In addition to the many tourist facilities, the Costa del Sol offers a lot for residents; its resorts include excellent health facilities, amenities and schools, including many international schools to give children the opportunity to learn a foreign language, including Spanish.",
      "What are the beaches like in the Costa del Sol?",
      "The 150 km stretch of coastline gives rise to many different types of beaches, including rocky and sandy coves, natural spots, family beaches, beach clubs, and complete enjoyment of secluded spots. In 2016 the Costa del Sol had 22 blue-flag beaches in Benalmádena, Estepona, Fuengirola and Mijas, each containing three beaches, while Marbella has four beaches.",
      "What are the cultural activities in the Costa del Sol?",
      "The Costa del Sol offers more than just beaches and recreational activities, as its resorts offer cultural programmes throughout the year such as theatre, music, art and dance, while Málaga stands alone as the cultural centre of southern Spain with more than 35 museums, including, on a world-class level, the Picasso Museum and the Pompidou Centre. The city is also home to a symphonic orchestra, several theatres and concert halls.",
      "Outside the capital, Marbella hosts the annual art fair and the Starlite summer festival, which attracts celebrities with big artistic names such as Santana, Tom Jones, The Divo and Estrella Morente, all in the 2016 edition. Jazz festivals are held in Mijas and Los Boliches, while the Nerja festival is held in the world-famous caves of the resorts, where the best concerts and ballets are performed.",
      "In keeping with Spanish tradition, fairs and festivals form an essential part of life in the Costa del Sol; almost every resort, town and village celebrates a major event in honour of its local saint. The most famous Costa del Sol celebrations are held during Holy Week, with solemn processions in Málaga, Marbella and Vélez. Málaga's commemoration is particularly special: celebrations in honour of the Virgen del Carmen, patron saint of fishermen, on 16 July, are held in almost all the resorts of the Costa del Sol; the Málaga Fair in mid-August is considered one of the biggest summer parties held in southern Spain, and the Fuengirola Fair is held at the beginning of October.",
      "What about dining in the Costa del Sol?",
      "The Costa del Sol is considered a paradise for food lovers, with its varied venues and cuisines suiting all tastes at reasonable prices.",
      "There are thousands of restaurants to choose from in the Costa del Sol, ranging from modest bars serving traditional tapas to bars offering a tasting experience of the most delicious dishes that rival those of London and New York.",
      "At the top of the list are the finest restaurants in the Costa del Sol, with no fewer than seven stars in the Michelin guide, including four restaurants in Marbella, Dani García's restaurant at the two-star Puente Romano Hotel, a restaurant in Málaga, one in Fuengirola and another in Benahavís located in Casares, in addition to award-winning fine-dining restaurants where you can enjoy the most delicious dishes at very reasonable prices.",
      "Given the significant number of foreign residents, the Costa del Sol offers cuisine from all over the world; Spanish cuisine takes the lead, including local dishes such as fried fish and gazpacho, in addition to Mediterranean dishes such as paella and fresh fish. European recipes are also served throughout the Costa del Sol, where you can find many English-style pubs, Italian restaurants, French bistros and Swedish restaurants. Dining in the Costa del Sol plays an important role, as you can find restaurants serving Indian, Thai, Mexican, Persian, Chinese or Japanese food.",
      "What about shopping in the Costa del Sol?",
      "The Costa del Sol is a great shopping destination where you can find many stores and major retailers in most of the resorts.",
      "What are the best shopping centres in the Costa del Sol?",
      "There are many of them, including:",
      "La Cañada in Marbella, considered one of the largest shopping centres in southern Spain and home to major popular brands such as Apple, FNAC, Guess, Habitat",
      "Miramar in Fuengirola, considered one of the most famous shopping centres in the Costa del Sol, which includes many options from well-known brands in addition to small shops",
      "Larios Centre in Málaga, favoured by tourists and residents, which includes Primark and Dunnes stores, in addition to the advantage of being located near Vialia, another large shopping centre",
      "El Ingenio located in Vélez-Málaga, considered one of the best shopping centres on the eastern side of the Costa del Sol, and includes many good options of shops, markets and a cinema",
      "El Corte Inglés, whose Spanish branch includes several major stores in the Costa del Sol, with two stores in the city of Málaga, two stores in Marbella and another store in Fuengirola",
      "What are the best main shopping streets in the Costa del Sol?",
      "The best places to visit are:",
      "Calle Larios in Málaga: considered the main street in the city, in addition to the facing Calle Nueva, full of shops and well-known brands",
      "Ricardo Soriano Street in Marbella: considered the main street in the city, in addition to being home to famous Spanish shops such as Zara, Massimo Dutti and Mango, located near the old square, which includes unusual commercial shops",
      "What are the finest shopping spots in the Costa del Sol?",
      "If you prefer quality and want to buy some luxury purchases, Marbella offers you the best options in:",
      "Puerto Banús: the second destination for luxury shopping in Spain after Madrid and Barcelona, considered home to the most famous fashion and style brands, Italian, French and American brands, and if you want to stroll around and see the latest trends, Puerto Banús is the right place",
      "El Corte Inglés: considered a branch of Puerto Banús, it includes upscale shops, markets and furniture stores",
    ],
  },
};
