import type { Guide } from "./france-guides";

const B = (n: string) => `https://i0.wp.com/100region.com/wp-content/uploads/2023/04/${n}?w=1400&ssl=1`;

const KICKER = { kicker_ar: "شواطئ", kicker_en: "Beaches" } as const;

// Deep-dive pages for the 19 beaches and coastlines of Spain (part 2).
export const spainBeachesB: Guide[] = [
  {
    slug: "beach-tropical",
    title_ar: "شواطىء وسواحل – تروبيكال",
    title_en: "Beaches and coastlines – Costa Tropical",
    ...KICKER,
    image: B("img_0934.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Costa Tropical", en: "Costa Tropical" },
      { type: "P", ar: "نبدأ رحلتنا على الساحل الغربي لغرناطة المعروف باسم كوستا تروبيكال ، من هنا الى مدينة مالقا ، سنستمتع بالمناظر الطبيعية المتنوعة لهذا الساحل الوعر", en: "We begin our journey on the western coast of Granada known as the Costa Tropical; from here to the city of Málaga we will enjoy the varied landscapes of this rugged coast." },
      { type: "P", ar: "يحتوي كوستا تروبيكال على خمسة مراكز سياحية : ألمونيكار وسالوبرينيا وموتريل وكاستيل دي فيرو ولا روبيتا", en: "The Costa Tropical has five tourist centres: Almuñécar, Salobreña, Motril, Castell de Ferro and La Rábita." },
      { type: "P", ar: "في كل هذه ستتمكن من تجربة الرياضات مثل ركوب الأمواج وركوب الأمواج والغوص (هناك عشب البحر بوسيدونيا) والابحار والتزلج على الماء والغولف وما الى ذلك ، وكيف ترغب في الابحار على متن يخت ؟", en: "In all of these you will be able to try sports such as surfing, windsurfing and diving (there is Posidonia seagrass), sailing, water skiing, golf and so on. And how would you like to sail aboard a yacht?" },
      { type: "H3", ar: "شواطئ لجميع الأذواق", en: "Beaches for every taste" },
      { type: "P", ar: "اذا كنت تبحث عن شواطئ مجهزة تجهيزا كاملا ، فجرب لا هيرادورا (ألمونيكار) أو بونينتي (موتريل) ، اذا كنت تفضل الخلجان الطبيعية ، فستحب تلك الموجودة في ال كاليتون وال بارغو ، ولعشاق الطبيعة ، هناك أيضا خيارات مثل شاطئ ال روسو في ألبونول", en: "If you are looking for fully equipped beaches, try La Herradura (Almuñécar) or Poniente (Motril). If you prefer natural coves, you will love those at El Cañuelo and El Pargo, and for nature lovers there are also options such as El Ruso beach in Albuñol." },
      { type: "H3", ar: "خطط سفر أخرى", en: "Other travel plans" },
      { type: "P", ar: "بمجرد وصولك الى المنطقة ، يمكنك تحقيق أقصى استفادة من اكتشاف المساحات الطبيعية ، مثل سلسلة جبال سييرا نيفادا أو المحمية الطبيعية في سلاسل جبال تيجيدا والميجارا وألهاما", en: "Once you arrive in the area, you can make the most of discovering the natural spaces, such as the Sierra Nevada mountain range or the nature reserve in the Tejeda, Almijara and Alhama ranges." },
      { type: "P", ar: "اذا كانت الثقافة التي تبحث عنها ، فستحب اكتشاف قلعة سالوبرينيا (وهي أيضا وجهة نظر رائعة) وحديقة ال ماجويلو النباتية (في ألمونيكار)", en: "If culture is what you are looking for, you will love discovering Salobreña Castle (which is also a wonderful viewpoint) and El Majuelo botanical garden (in Almuñécar)." },
      { type: "H3", ar: "المطبخ", en: "The cuisine" },
      { type: "P", ar: "جرب الفواكه الاستوائية الشهيرة والروبيان والجمبري والكركند", en: "Try the famous tropical fruits and the prawns, shrimp and lobster." },
    ],
  },
  {
    slug: "beach-de-la-luz",
    title_ar: "شواطىء وسواحل – دي لا لوز",
    title_en: "Beaches and coastlines – Costa de la Luz",
    ...KICKER,
    image: B("image-1-1.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Costa de la Luz", en: "Costa de la Luz" },
      { type: "P", ar: "تنتظرك الرمال الذهبية والشواطئ الطويلة وغروب الشمس المذهل على شواطئ قادس وهويلفا ، ولكن هناك أكثر من ذلك بكثير", en: "Golden sands, long beaches and stunning sunsets await you on the shores of Cádiz and Huelva, but there is much more than that." },
      { type: "P", ar: "المدن الساحلية ، والأرض التي كانت مأهولة بالسكان لأكثر من 3000 عام ، والقرى البيضاء بين الجبال هي العذر المثالي لاكتشاف هذا الساحل ، حيث يلتقي الترفيه والثقافة", en: "The coastal towns, a land inhabited for more than 3,000 years, and the white villages among the mountains are the perfect excuse to discover this coast, where leisure and culture meet." },
      { type: "H3", ar: "الشمس والرمال والكثير من الرياضة", en: "Sun, sand and plenty of sport" },
      { type: "P", ar: "شكل المحيط الأطلسي مصير هذا الساحل لعدة قرون ، وقع الفينيقيون واليونانيون والرومان والعرب في حب المناخ الرائع لهذه المنطقة ، التي تنتظرك الآن ، أكثر من 200 كيلومتر من الرمال الذهبية تصطف على الساحل ، حيث البحر هو عامل الجذب الرئيسي", en: "The Atlantic Ocean has shaped the destiny of this coast for centuries. The Phoenicians, Greeks, Romans and Arabs fell in love with the wonderful climate of this area, which now awaits you: more than 200 kilometres of golden sand line the coast, where the sea is the main attraction." },
      { type: "P", ar: "لا تغادر المنطقة دون زيارة مساحات شاسعة من الرمال على شواطئ مثل بولونيا وفالديفاكيروس في مقاطعة قادس ، أو ماتالاسكاناس ومازاغون في هويلفا", en: "Do not leave the area without visiting the vast stretches of sand on beaches such as Bolonia and Valdevaqueros in the province of Cádiz, or Matalascañas and Mazagón in Huelva." },
      { type: "P", ar: "مكان يمكنك أن تفعل فيه أكثر من مجرد الاسترخاء ، اذا كنت تريد الحركة ، فان الأمواج والرياح في المنطقة مثالية للرياضات المائية عالية الجودة ، ركوب الأمواج ، وركوب الأمواج بالطائرة الورقية مثالية لحرق الأدرينالين في هذا المكان الفريد ، هذا هو أيضا موطن حديقة دونيانا الوطنية ، أهم محمية طبيعية في اسبانيا ، حيث تقدم طبيعة مذهلة مع الأراضي الرطبة والمستنقعات والحياة البرية الفريدة ، بما في ذلك طيور النحام الملونة", en: "A place where you can do more than just relax: if you want action, the waves and wind of the area are perfect for high-quality water sports. Surfing and kitesurfing are ideal for burning adrenaline in this unique place. This is also home to Doñana National Park, the most important nature reserve in Spain, offering stunning nature with wetlands, marshes and unique wildlife, including colourful flamingos." },
      { type: "P", ar: "بعد الكثير من النشاط ، ستحتاج الى استعادة قوتك مع وجبة جيدة", en: "After so much activity you will need to recover your strength with a good meal." },
      { type: "P", ar: "التخصصات المحلية مثل التونة ذات الزعانف الزرقاء وجمبري هويلفا والجمبري الملكي سانلوكار لذيذة ، يمكنك أيضا اغتنام الفرصة لاكتشاف جميع الأنواع المختلفة من شيري من خيريز ، أشهر صادرات المنطقة", en: "Local specialities such as bluefin tuna, Huelva prawns and Sanlúcar king prawns are delicious. You can also take the opportunity to discover all the different kinds of sherry from Jerez, the area's most famous export." },
      { type: "H3", ar: "ما وراء الطبيعة", en: "Beyond nature" },
      { type: "P", ar: "يمكنك الاستمتاع بالفن والتاريخ في أي مكان في كوستا دي لا لوز ، ستفاجئك مدن مثل قادس ، التي لعبت دورا مهما طوال تاريخ اسبانيا ، بهندستها المعمارية للمنازل البيضاء والكنائس والتحصينات ، هل تعلم أن أول دستور اسباني تم توقيعه في قادس ، في عام 1812 ؟ أم أن الكرنفال قد يكون أكثر متعة من أي مكان آخر في اسبانيا ؟", en: "You can enjoy art and history anywhere on the Costa de la Luz. Cities such as Cádiz, which played an important role throughout Spain's history, will surprise you with their architecture of white houses, churches and fortifications. Did you know that the first Spanish constitution was signed in Cádiz, in 1812? Or that the carnival may be more fun there than anywhere else in Spain?" },
      { type: "P", ar: "مقاطعة قادس هي أيضا منطقة داخلية جميلة ، وهي منطقة رائعة لاستكشافها ، انها موطن للقرى البيضاء الشهيرة ، 19 مكانا بها منازل مطلية باللون الأبيض تطفو بين الجبال ، مكان بالكاد أثر فيه البشر على المناظر الطبيعية ، مع مناظر طبيعية رائعة سيستمتع بها أي مسافر", en: "The province of Cádiz also has a beautiful interior, a wonderful area to explore. It is home to the famous white villages, 19 places with whitewashed houses floating among the mountains, a place where humans have barely affected the landscape, with wonderful scenery any traveller will enjoy." },
      { type: "P", ar: "في المقاطعة التالية ، هناك أيضا أماكن في هويلفا مليئة بالتاريخ ، ترحب بك قرى مثل Moguer وPalos de la Frontera في Lugares Colombinos ، هذه هي الأماكن التي يمكنك فيها معرفة كل شيء عن رحلات كريستوفر كولومبوس واكتشاف أمريكا ، أيضا في هويلفا ، يشهد مايو أو يونيو المهرجان السنوي والحج في ال روسيو ، يشق الموكب الأكثر شعبية في اسبانيا طريقه ، مع الموسيقى والاخلاص الى قرية ألمونتي", en: "In the next province there are also places in Huelva full of history. Villages such as Moguer and Palos de la Frontera in the Lugares Colombinos welcome you; these are the places where you can learn all about the voyages of Christopher Columbus and the discovery of America. Also in Huelva, May or June sees the annual festival and pilgrimage of El Rocío, when Spain's most popular procession makes its way, with music and devotion, to the village of Almonte." },
    ],
  },
  {
    slug: "beach-artabro",
    title_ar: "شواطىء وسواحل – ارتابرو",
    title_en: "Beaches and coastlines – Gulf of Ártabro",
    ...KICKER,
    image: B("img_0926.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Gulf of Ártabro", en: "Gulf of Ártabro" },
      { type: "P", ar: "يتكون خليج أرتابرو من أربعة مصبات : A Coruña وBetanzos وAres وFerrol ، يأتي اسم هذه المنطقة في شمال غرب غاليسيا من الأشخاص الذين سكنوا المكان في عصور ما قبل الرومان أرتابري ، القرى في هذه المنطقة والأنهار العديدة التي تتدفق الى البحر وشواطئها تجعلها وجهة جذابة بشكل استثنائي", en: "The Gulf of Ártabro is made up of four estuaries: A Coruña, Betanzos, Ares and Ferrol. The name of this area in north-western Galicia comes from the people who inhabited the place in pre-Roman times, the Artabri. The villages in this area, the many rivers that flow into the sea and its beaches make it an exceptionally attractive destination." },
      { type: "P", ar: "ستجد في مصب ريا دا كورونيا شواطئ مثل ريازور وأورزان ، مع أمواج مثالية لركوب الأمواج ، تعد الأنهار التوأمة في آريس وبيتانزوس فرصة لاستكشاف المدن الفخمة ، ولكل منها شاطئها الخاص ، والاستمتاع بالمناظر الطبيعية في محمية المحيط الحيوي As Mariñas Coruñesas e Terras do Mandeo ، وفي فيرول ستجد مدينة يرتبط تاريخها ارتباطا وثيقا بتقاليدها البحرية", en: "In the Ría da Coruña estuary you will find beaches such as Riazor and Orzán, with waves perfect for surfing. The twin rias of Ares and Betanzos are a chance to explore stately towns, each with its own beach, and to enjoy the landscapes of the As Mariñas Coruñesas e Terras do Mandeo Biosphere Reserve. And in Ferrol you will find a city whose history is closely linked to its maritime traditions." },
      { type: "H3", ar: "القليل من الثقافة", en: "A little culture" },
      { type: "P", ar: "يجب ألا يفوت زوار A Coruña بأي حال من الأحوال رؤية برج هرقل ، لديها تسمية التراث العالمي وهي أقدم منارة تعمل في العالم ، بالاضافة الى أنها توفر مناظر خلابة", en: "Visitors to A Coruña should on no account miss seeing the Tower of Hercules; it has World Heritage designation and is the oldest working lighthouse in the world, as well as offering breathtaking views." },
      { type: "P", ar: "تستحق المدن الأخرى مثل فيرول (واحدة من أفضل الموانئ الطبيعية في العالم) ، والبلدات والقرى التقليدية مثل بيتانزوس (مع كنيستها الجميلة سانتا ماريا) وبونتيدوم الزيارة لمواقعها الأثرية الساحرة", en: "Other cities such as Ferrol (one of the best natural harbours in the world), and traditional towns and villages such as Betanzos (with its beautiful church of Santa María) and Pontedeume are worth a visit for their charming monumental sites." },
      { type: "H3", ar: "فن الطهو اللذيذ", en: "Delicious gastronomy" },
      { type: "P", ar: "من المستحيل مغادرة هذه المنطقة دون أخذ عينات من بعض أطباق المأكولات البحرية النموذجية", en: "It is impossible to leave this area without sampling some of the typical seafood dishes." },
    ],
  },
  {
    slug: "beach-verde",
    title_ar: "شواطىء وسواحل – فيردي",
    title_en: "Beaches and coastlines – Costa Verde",
    ...KICKER,
    image: B("img_0934.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Costa Verde (Green Coast)", en: "Costa Verde (Green Coast)" },
      { type: "P", ar: "يستحم بحر كانتابريا ساحل أستورياس لمسافة 350 كيلومترا ، حيث تندمج المروج والمنحدرات عمليا مع الماء", en: "The Cantabrian Sea bathes the coast of Asturias for 350 kilometres, where meadows and cliffs practically merge with the water." },
      { type: "P", ar: "منظر فريد من نوعه حيث ترسم الطبيعة والبحر وقرى الصيد صورة مثالية سيستمتع بها عشاق الرياضة أو الشاطئ أو الطعام الجيد تماما", en: "A unique landscape where nature, the sea and the fishing villages paint a perfect picture that lovers of sport, the beach or good food will thoroughly enjoy." },
      { type: "H3", ar: "رحلة على طول الساحل", en: "A trip along the coast" },
      { type: "P", ar: "يحدها المساحات الخضراء في مروجها ، يجمع ساحل أستورياس بين البلوز الشديد ورماله الذهبية بعباءة طبيعية ستبهر أي مسافر ، تنتظرك المناظر الطبيعية المكونة من فيلات وشواطئ ساحلية ساحرة هناك ، يتخلل اللون الأصفر والأحمر والأزرق اللون الأبيض لمنازل قرى الصيد هذه ، يرحب بكم كوديليرو ولانيس ولواركا وكانديس ولوانكو في جو يكون فيه البحر هو الميزة الرئيسية ، يعد المشي على طول ممشى هذه القرى دائما طريقة جيدة لامتصاص جمال بحر كانتابريا ، اذا كنت تفضل شيئا أكثر نشاطا ، فستجد في أستورياس الوجهة المثالية للرياضات المائية ، احصل على لوح التزلج الخاص بك جاهزا لأن شواطئ تابيا دي كاساريغو وغوزون وساليناس كلها مثالية للمشي على الأمواج", en: "Bordered by the green of its meadows, the coast of Asturias combines intense blues and golden sands with a natural cloak that will amaze any traveller. Landscapes made up of villas and charming coastal beaches await you there; yellow, red and blue break up the white of the houses of these fishing villages. Cudillero, Llanes, Luarca, Candás and Luanco welcome you in an atmosphere where the sea is the main feature. Walking along the promenade of these villages is always a good way to soak up the beauty of the Cantabrian Sea. If you prefer something more active, in Asturias you will find the perfect destination for water sports: get your board ready, because the beaches of Tapia de Casariego, Gozón and Salinas are all perfect for riding the waves." },
      { type: "P", ar: "يجدر الاستيقاظ مبكرا لمعرفة كيف تصل قوارب الصيد الى الميناء ، هذا هو المكان الذي يسقط فيه صيد اليوم في أسواق الأسماك ، ويملأ الجو بالرائحة المالحة النموذجية لهذه القرى", en: "It is worth getting up early to see how the fishing boats arrive at the harbour; this is where the day's catch is dropped off at the fish markets, filling the air with the salty smell typical of these villages." },
      { type: "P", ar: "بعد هذه التجربة ، أفضل خطة هي تذوق فن الطهو الأستوري اللذيذ ، هناك شيء للجميع مع اختيار الأسماك المشوية والمأكولات البحرية (مثل قنفذ البحر والكركند وما الى ذلك) والحساء واليخنات (مثل فابادا أستوريا الكلاسيكية) ، والجبن الرائع", en: "After this experience, the best plan is to taste the delicious Asturian gastronomy. There is something for everyone with a selection of grilled fish and seafood (such as sea urchin, lobster and so on), soups and stews (such as the classic Asturian fabada), and wonderful cheeses." },
      { type: "H3", ar: "الجانب الآخر من أستورياس", en: "The other side of Asturias" },
      { type: "P", ar: "يأخذنا الجانب البديل من أستورياس الى الداخل ، يرحب بك التاريخ والجبال في منطقة بها كل شيء ، جنة طبيعية داخلية تبدأ في بيكو دي يوروبا – حديقة وطنية موطن لمجموعة كبيرة من الحياة البرية ، بما في ذلك شعار المنطقة : الدب البني ، يمكن أيضا العثور على واحدة من المجوهرات التاريخية والمعمارية العظيمة في أستورياس ، الموقع الملكي لكوفادونغا ، داخل الحديقة", en: "The alternative side of Asturias takes us inland; history and mountains welcome you in an area that has everything, an inland natural paradise that begins in the Picos de Europa — a national park home to a wide range of wildlife, including the emblem of the region: the brown bear. One of the great historical and architectural jewels of Asturias, the Royal Site of Covadonga, can also be found inside the park." },
      { type: "P", ar: "بينما ننزل ، تملأ الأنهار التي تتدفق من هذه القمم وديان المنطقة بالحياة ، تاركة وراءها مدنا جميلة مثل أوفييدو ، المليئة بالسحر المعماري مثل مسرح كامبوامور أو الكاتدرائية أو قصر سانتا ماريا ديل نارانكو ، وهو مثال على الطراز ما قبل الرومانسكي", en: "As we descend, the rivers flowing from these peaks fill the valleys of the region with life, leaving behind beautiful cities such as Oviedo, full of architectural charm such as the Campoamor Theatre, the cathedral or the palace of Santa María del Naranco, an example of the pre-Romanesque style." },
      { type: "P", ar: "يمكن العثور على الانشاءات على الطراز الهندي بجوار هذه ، أعطى هؤلاء المهاجرون ، الذين ذهبوا الى أمريكا لكسب ثروتهم أنماطا جديدة للمباني المحلية مع الأروقة والشرفات والألوان في العديد من البلدات والمدن ، علاوة على ذلك اذا كنت مهتما باكتشاف طريق مليء بالروحانية ، فيمكنك السفر على طول طريق سانت جيمس أثناء مروره عبر أستورياس ، والمعروفة باسم الطريق البدائي ، بين أوفييدو وسانتياغو دي كومبوستيلا", en: "Indiano-style constructions can be found next to these; these emigrants, who went to America to make their fortune, gave new styles to local buildings with arcades, balconies and colours in many towns and cities. Moreover, if you are interested in discovering a route full of spirituality, you can travel along the Way of St James as it passes through Asturias, known as the Primitive Way, between Oviedo and Santiago de Compostela." },
    ],
  },
  {
    slug: "beach-basque",
    title_ar: "شواطىء وسواحل – الباسك",
    title_en: "Beaches and coastlines – the Basque Coast",
    ...KICKER,
    image: B("image-1-1.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Basque Coast", en: "Basque Coast" },
      { type: "P", ar: "يتميز الساحل في اقليم الباسك بمناظر طبيعية مع جرف حاد ومصبات الأنهار التي تتدفق الى البحر وسلاسل جبلية مكسوة بأخشاب الزان والبلوط ، تتمتع مدنها بتقاليد صيد طويلة ، والتي يمكن تجربتها في حياتها اليومية وفي نكهات المطبخ المحلي", en: "The coast of the Basque Country features landscapes with steep cliffs, estuaries flowing into the sea and mountain ranges clad in beech and oak woods. Its towns have a long fishing tradition, which can be experienced in their daily life and in the flavours of the local cuisine." },
      { type: "P", ar: "يمكنك أيضا رؤية جسر فيزكايا المعلق للتراث العالمي ، وهو أقدم جسر نقل فعال في الوجود", en: "You can also see the World Heritage Vizcaya suspension bridge, the oldest working transporter bridge in existence." },
      { type: "H3", ar: "الطبيعة", en: "Nature" },
      { type: "P", ar: "ستجد مناظر طبيعية فريدة من نوعها – على سبيل المثال عندما تتبع طريق فلايش من زومايا الى موتريكو مرورا بدبا ، حيث سترى منحدرات لها أكثر من 60 مليون سنة من التاريخ ، أوصى أيضا بمحمية المحيط الحيوي في أوردايباي ، موقع استثنائي آخر هو ساحل بيرميو ، مع جزيرة سان خوان دي غازتيلوغاتكس ، ستقنعك رحلة بحرية بالقارب حول المنطقة بسحرها", en: "You will find unique landscapes — for example when you follow the flysch route from Zumaia to Mutriku via Deba, where you will see cliffs with more than 60 million years of history. I also recommend the Urdaibai Biosphere Reserve. Another exceptional site is the coast of Bermeo, with the island of San Juan de Gaztelugatxe; a boat trip around the area will convince you of its charm." },
      { type: "H3", ar: "التقاليد البحرية", en: "Maritime traditions" },
      { type: "P", ar: "اكتشف هذا في القرى الصغيرة مثل Bermeo وLekeitio وGetaria وHondarribia وSanturzi ، حيث توجد طريقة جيدة لرؤية المطبخ بنفسك ، أوصي بالسمك المشوي على الفحم والأنشوجة وحساء السمك المعروف باسم مارميتاكو ، وسمك النازلي مع خدود سمك النازلي", en: "Discover this in small villages such as Bermeo, Lekeitio, Getaria, Hondarribia and Santurtzi, where there is a good way to see the cuisine for yourself. I recommend the charcoal-grilled fish, the anchovies, the fish soup known as marmitako, and hake with hake cheeks." },
    ],
  },
  {
    slug: "beach-brava",
    title_ar: "شواطىء وسواحل – برافا",
    title_en: "Beaches and coastlines – Costa Brava",
    ...KICKER,
    image: B("img_0926.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Costa Brava", en: "Costa Brava" },
      { type: "P", ar: "LIVING THE MEDITERRANEAN", en: "LIVING THE MEDITERRANEAN" },
      { type: "P", ar: "الخلجان من البحر الأزرق العميق ، وشواطئ الرمال الذهبية ، والحدائق الطبيعية ، وبلدات العصور الوسطى ، وأعمال سلفادور دالي … هذا هو المزيج المغري من كوستا برافا في جيرونا", en: "Coves of deep blue sea, golden sandy beaches, nature parks, medieval towns, the works of Salvador Dalí… this is the tempting mix of the Costa Brava in Girona." },
      { type: "P", ar: "هذه هي منطقة كاتالونيا من بلانس الى بورتبو مع مدن رائعة مثل جيرونا وقرى الصيد القديمة مع منازل بيضاء صغيرة مثل كاداكيس", en: "This is the area of Catalonia from Blanes to Portbou, with wonderful cities such as Girona and old fishing villages with small white houses such as Cadaqués." },
      { type: "P", ar: "مما لا شك فيه أنه مكان رائع للاستمتاع بالمناخ اللطيف للبحر الأبيض المتوسط ، أو زيارة بعض مطاعمها الحائزة على نجمة ميشلان ، أو اتباع طريق امبوردا دي أو للنبيذ ، يعد كوستا برافا دائما خيارا جيدا لوجهة العطلات", en: "There is no doubt it is a wonderful place to enjoy the mild Mediterranean climate, or to visit some of its Michelin-starred restaurants, or to follow the Empordà DO wine route. The Costa Brava is always a good choice for a holiday destination." },
      { type: "H3", ar: "الشواطئ والطبيعة الضوئية والطابع", en: "Beaches, light-filled nature and character" },
      { type: "P", ar: "هل تتوق الى البحر ؟ تحتوي هذه المنطقة على أكثر من 200 كيلومتر من الساحل ، مع شواطئ العلم الأزرق ، والمنتجعات السياحية مثل يوريت دي مار ، وخليج الورود (واحد من أجمل الخلجان في العالم) والخلجان الساحرة بين المنحدرات في توسا دي مار أو تورويلا دي مونتغري أو بيغور أو كاليلا دي بالافروجيل", en: "Longing for the sea? This area has more than 200 kilometres of coast, with Blue Flag beaches, tourist resorts such as Lloret de Mar, the Bay of Roses (one of the loveliest bays in the world) and charming coves between the cliffs in Tossa de Mar, Torroella de Montgrí, Begur or Calella de Palafrugell." },
      { type: "P", ar: "اذا كنت تبحث عن مناظر طبيعية حيث يمكنك الانفصال عن ضغوطك اليومية ، فان كوستا برافا مثالية مع ثلاث حدائق طبيعية : كاب دي كريس ، أيغوامولز دي امبوردا ، ومونتغري ، ايلي ميدس اي ال بايكس تير ، هل تعلم أن جزر ميديس مشهورة في جميع أنحاء العالم كموقع للغوص ؟", en: "If you are looking for landscapes where you can disconnect from your daily stresses, the Costa Brava is perfect with three nature parks: Cap de Creus, Aiguamolls de l'Empordà, and Montgrí, Illes Medes i el Baix Ter. Did you know that the Medes Islands are famous all over the world as a diving site?" },
      { type: "P", ar: "أفكار أخرى قد تعجبك : القيام برحلة بالقارب على بحيرة بانيوليس (واحدة من أكبر البحيرات في شبه الجزيرة الأيبيرية) أو زيارة واحدة من الحدائق النباتية الخيالية في المنطقة ، مثل ماريمورترا (بلانيس) ، مع اطلالات على البحر", en: "Other ideas you might like: taking a boat trip on Lake Banyoles (one of the largest lakes on the Iberian Peninsula) or visiting one of the area's fantastic botanical gardens, such as Marimurtra (Blanes), with views of the sea." },
      { type: "H3", ar: "موطن سلفادور دالي وتناول الطعام الفاخر", en: "Home of Salvador Dalí and fine dining" },
      { type: "P", ar: "كان فيغيريس مسقط رأس الفنان السريالي سلفادور دالي ، واليوم يمكنك رؤية متحف مسرح دالي غريب الأطوار هناك ، مع العديد من أهم أعماله", en: "Figueres was the birthplace of the surrealist artist Salvador Dalí, and today you can see the eccentric Dalí Theatre-Museum there, with many of his most important works." },
      { type: "P", ar: "جيرونا هي أيضا موطن لموقعين أكثر أهمية اذا كنت تريد معرفة المزيد عن هذا الرسام العبقري : منزل متحف سلفادور دالي في كاداكيس (القرية الأكثر روعة في أي مكان في كوستا برافا) ومتحف قلعة غالا دالي ، في بوبول", en: "Girona is also home to two more important sites if you want to learn more about this genius painter: the Salvador Dalí House-Museum in Cadaqués (the most wonderful village anywhere on the Costa Brava) and the Gala Dalí Castle Museum, in Púbol." },
      { type: "P", ar: "يجب أن تشمل جولة كوستا برافا أيضا بعض قراها المذهلة التي تعود للقرون الوسطى الى الداخل ، مثل بالز أو بيراتالادا ، والتوقف في مدينة جيرونا ، وهي مؤخرا مكانا لسلسلة لعبة العروش", en: "A tour of the Costa Brava should also include some of its stunning medieval villages inland, such as Pals or Peratallada, and a stop in the city of Girona, recently a location for the Game of Thrones series." },
      { type: "H3", ar: "المزيد من الثقافة لتغريك ؟", en: "More culture to tempt you?" },
      { type: "P", ar: "جرب أنقاض امبوريس ، وهي مدينة مستعمرة سابقة للحضارتين اليونانية والرومانية", en: "Try the ruins of Empúries, a former colonial city of both the Greek and Roman civilisations." },
      { type: "P", ar: "النقطة القوية الأخرى في هذا الجزء من اسبانيا هي بالطبع ، مطبخها الشهير ، تراكمت المطاعم حول جيرونا حوالي 15 نجمة ميشلان ، بما في ذلك معابد الطهي مثل سيلر دي كان روكا", en: "The other strong point of this part of Spain is, of course, its famous cuisine. The restaurants around Girona have accumulated around 15 Michelin stars, including culinary temples such as El Celler de Can Roca." },
    ],
  },
  {
    slug: "beach-marina-lucense",
    title_ar: "شواطىء وسواحل – مارينا لوسينسي",
    title_en: "Beaches and coastlines – Mariña Lucense",
    ...KICKER,
    image: B("img_0934.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Mariña Lucense", en: "Mariña Lucense" },
      { type: "P", ar: "مارينا لوسينسي هي الجزء الشرقي من الساحل على شواطئ بحر كانتابريا ، هذه منطقة من البحر والجبال والأنهار ومصبات الأنهار وموطن للشواطئ الشهيرة مثل كاتدرايس (الكاتدرائيات)", en: "Mariña Lucense is the eastern part of the coast on the shores of the Cantabrian Sea. This is an area of sea, mountains, rivers and estuaries, and home to famous beaches such as Catedrais (the Cathedrals)." },
      { type: "P", ar: "يحتوي Mariña Lucense على حوالي 100 كيلومتر من الساحل حيث ستجد موانئ صيد الحيتان القديمة ومجموعة متنوعة من المناظر الطبيعية مثل Río Eo وOsco y Terras de Burón Biosphere Reserve وشاطئ As Catedrais (حيث تشكل الصخور أقواسا ضخمة) وجزيرة Coelleira", en: "Mariña Lucense has around 100 kilometres of coast where you will find old whaling harbours and a variety of landscapes such as the Río Eo, Oscos y Terras de Burón Biosphere Reserve, As Catedrais beach (where the rocks form huge arches) and the island of Coelleira." },
      { type: "P", ar: "تضم Mariña Lucense قاعات مدينة Alfoz وBarreiros وBurela وCervo وFoz وLurrenzá وMondoñedo وOurol وA Pontenova وRibadeo وTrabada وO Valadouro وO Vicedo وViveiro وXove", en: "Mariña Lucense comprises the town halls of Alfoz, Barreiros, Burela, Cervo, Foz, Lourenzá, Mondoñedo, Ourol, A Pontenova, Ribadeo, Trabada, O Valadouro, O Vicedo, Viveiro and Xove." },
      { type: "H3", ar: "الرياضة على الشاطئ", en: "Sport on the beach" },
      { type: "P", ar: "تحتوي على العديد من الشواطئ في هذه المنطقة على العلم الأزرق ، وهي مجهزة بالكامل لجميع أنواع الرياضات المائية مثل ركوب الأمواج وركوب الأمواج وركوب الأمواج بالطائرة الورقية والتجديف بالكاياك والابحار ، هناك شواطئ لا نهاية لها مثل كوفا (في فيفيرو ، تمتد لمسافة 1.5 كيلومتر) وخلجان صغيرة أخرى", en: "Many of the beaches in this area have the Blue Flag, and they are fully equipped for all kinds of water sports such as surfing, windsurfing, kitesurfing, kayaking and sailing. There are endless beaches such as Covas (in Viveiro, stretching for 1.5 kilometres) and other small coves." },
      { type: "H3", ar: "الحرف اليدوية", en: "Handicrafts" },
      { type: "P", ar: "تشتهر المنطقة بأكملها بالطرق المتاحة لتعلم كل شيء عن الحرف التقليدية : السيراميك والفخار وشباك الصيد والنجارة تشمل المعالم السياحية الأخرى المثيرة للاهتمام متحف البحر الاقليمي", en: "The whole area is famous for the routes available to learn all about traditional crafts: ceramics, pottery, fishing nets and carpentry. Other interesting sights include the Regional Sea Museum." },
    ],
  },
  {
    slug: "beach-rias-altas",
    title_ar: "شواطىء وسواحل – رياس اطلس استوريز",
    title_en: "Beaches and coastlines – the Rías Altas estuaries",
    ...KICKER,
    image: B("image-1-1.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Rías Altas estuaries", en: "Rías Altas estuaries" },
      { type: "P", ar: "هذه هي مصبات الأنهار في شمال غاليسيا المطلة على المحيط الأطلسي المنحدرات المذهلة والشواطئ وقرى الصيد والمنارات والأسطورة هي المكونات الرئيسية لهذا الساحل", en: "These are the estuaries in northern Galicia facing the Atlantic Ocean. Stunning cliffs, beaches, fishing villages, lighthouses and legend are the main ingredients of this coast." },
      { type: "P", ar: "هذه منطقة ستجد فيها مصبات الأنهار مثل مصبات الأنهار مثل A Coruña وAres and Betanzos وFerrol وCedeira وOrtigueira مجمعة في منطقتين كبيرتين هما : A Coruña وAs Mariñas وFerrolterra ، هذا خط ساحلي جميل للتجول عن طريق البر ، أو للتنزه أو الغطس على مساحاته الطويلة من الرمال وعلى الشواطئ مثل موروزوس أو فيلاروب", en: "This is an area where you will find estuaries such as A Coruña, Ares and Betanzos, Ferrol, Cedeira and Ortigueira, grouped into two large areas: A Coruña and As Mariñas, and Ferrolterra. This is a beautiful coastline to tour by land, or to walk or snorkel along its long stretches of sand and on beaches such as Morouzos or Vilarrube." },
      { type: "H3", ar: "ماذا سترى ؟", en: "What will you see?" },
      { type: "P", ar: "برج هرقل في مدينة أكورونيا هو منارة للتراث العالمي ، وواحد من العديد من المنارات التي يمكن العثور عليها على طول الطريق", en: "The Tower of Hercules in the city of A Coruña is a World Heritage lighthouse, and one of the many lighthouses to be found along the way." },
      { type: "P", ar: "تشمل مناطق الجذب الأخرى آثار بيتانزوس وقصر بازو دي مارينان وضريح سانتو أندريه دي تيكسيدو ، ووفقا للتقاليد يجب على جميع الجاليكيين الحج مرة واحدة على الأقل في حياتهم الى سان أندريه دي تيكسيدو لتجنب أن يصبحوا روحا مضطربة", en: "Other attractions include the monuments of Betanzos, the Pazo de Mariñán palace and the sanctuary of Santo André de Teixido; according to tradition all Galicians must make a pilgrimage at least once in their lives to San Andrés de Teixido to avoid becoming a restless spirit." },
      { type: "H3", ar: "الطبيعة تستحق التصوير الفوتوغرافي", en: "Nature worth photographing" },
      { type: "P", ar: "سييرا دا كابيلادا هي موطن لبعض من أعلى المنحدرات في أوروبا ، وEstaca de Bares ، حيث يلتقي المحيط الأطلسي ببحر كانتابريا ، هي واحدة من أفضل الأماكن لمشاهدة الطيور في القارة", en: "The Serra da Capelada is home to some of the highest cliffs in Europe, and Estaca de Bares, where the Atlantic Ocean meets the Cantabrian Sea, is one of the best places for birdwatching on the continent." },
    ],
  },
  {
    slug: "beach-rias-baixas",
    title_ar: "شواطىء وسواحل – رياس بيكساس استوري",
    title_en: "Beaches and coastlines – the Rías Baixas estuary",
    ...KICKER,
    image: B("img_0926.jpg"),
    blocks: [
      { type: "H3", noNumber: true, ar: "يالله سياحة .. يالله على اسبانيا !", en: "Let's travel .. come on to Spain!" },
      { type: "P", ar: "Rías Baixas estuary", en: "Rías Baixas estuary" },
      { type: "P", ar: "يعتبر الكثيرون هذا الساحل جنة ، وهو أيضا موقع جزر سييس ، المعروفة من قبل الرومان باسم جزر الآلهة ، يجمع ساحلها بين لون البحر الأزرق والخضرة في موقعها مع تقاليد الملاحة البحرية في غاليسيا ، في منطقة تمتد من مصبات الأنهار في موروس ونويا الى مصب نهر مينو في غواردا (بونتيفيدرا)", en: "Many consider this coast a paradise, and it is also the location of the Cíes Islands, known by the Romans as the Islands of the Gods. Its coast combines the blue of the sea and the green of its setting with Galicia's seafaring traditions, in an area stretching from the estuaries of Muros and Noia to the mouth of the Miño river in A Guarda (Pontevedra)." },
      { type: "P", ar: "الشواطئ الديدانية غير المزدحمة ، مع مساحات طويلة من الرمال البيضاء والمياه الزرقاء الفيروزية التي يمكن العثور عليها قبل كل شيء في جنوب مصبات الأنهار رياس بايكساس ، في جزر سييس ، حيث يبرز شاطئ روداس بشكل خاص", en: "The uncrowded warm beaches, with long stretches of white sand and turquoise blue water, can be found above all in the south of the Rías Baixas estuaries, in the Cíes Islands, where Rodas beach particularly stands out." },
      { type: "P", ar: "أوصي أيضا بشواطئ مثل A Lanzada في O Grove ، و Illa de Arousa ، مع اعلان 36 كيلومترا من الساحل محمية طبيعية وتصطف على جانبيها شواطئ انفرادية جميلة ، في الشمال ، يمكنك زيارة شواطئ مثل أغويرا أو أس فورناس أو تيستال", en: "I also recommend beaches such as A Lanzada in O Grove, and Illa de Arousa, with 36 kilometres of coast declared a nature reserve and lined with beautiful secluded beaches. In the north, you can visit beaches such as Aguieira, As Furnas or Testal." },
      { type: "H3", ar: "التقاليد البحرية", en: "Seafaring traditions" },
      { type: "P", ar: "هذه أرض الصيادين ، وواحدة من أفضل الأماكن للاستمتاع بالمحار ، ومن الأمثلة الجيدة على ذلك موروس ، حيث تقف مساكن الصيادين القديمة الى جانب القصور القوطية ، وأو غروف ، التي تعد شهر أكتوبر من كل عام مكانا للمهرجان تكريما للمأكولات البحرية ، تنتج المنطقة أيضا نبيذا أبيض رائعا يمكن الاستمتاع به على طريق رياس بايكساس للنبيذ", en: "This is a land of fishermen, and one of the best places to enjoy shellfish. A good example is Muros, where the old fishermen's dwellings stand alongside Gothic mansions, and O Grove, where every October is the setting for a festival in honour of seafood. The area also produces a wonderful white wine that can be enjoyed on the Rías Baixas wine route." },
      { type: "P", ar: "تشمل الزيارات الموصى بها بونتيفيدرا ، بمركزها التاريخي المثير للاهتمام ، ودير بويو القريب ، وبلديات كامبادوس ، وسانكسينكسو ، وكاتويرا (التي تقيم في أغسطس حج الفايكنج الشهير) ، وتوي وفيغو في الجنوب", en: "Recommended visits include Pontevedra, with its interesting historic centre, and the nearby Poio monastery, and the municipalities of Cambados, Sanxenxo, Catoira (which in August holds the famous Viking pilgrimage), and Tui and Vigo in the south." },
    ],
  },
];
