import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

export const TUNIS_REGION_HEROES = {
  "tunis-capital": U("2022/10/img_4719.jpg"),
  "carthage-sidi-bou-said": U("2022/10/img_4721.jpg"),
  sbeitla: U("2022/10/img_4723.jpg"),
  "sousse-kantaoui": U("2022/10/img_4725.jpg"),
  tabarka: U("2022/10/img_4950-1.jpg"),
  monastir: U("2022/10/img_4952.jpg"),
};

/**
 * The six Tunisian region pages linked from "الأماكن السياحية".
 * Arabic text is kept exactly as published on the source pages.
 */
export const tunisiaRegionGuides: Guide[] = [
  {
    slug: "tunis-capital",
    title_ar: "تونس العاصمة وما حولها",
    title_en: "Tunis and its surroundings",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES["tunis-capital"],
    blocks: [
      { type: "H3", ar: "تونس .. متعة السياحة والترفيه", en: "Tunis — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "تونس مدينة عصرية ومزدهرة ومجيدة التاريخ ، فهي لا تتوقف عن مفاجأتك ، من جانب المدينة العتيقة ، عديد البناءات القديمة تفتح أبوابها ، بعضها تحولت الى متاحف وأخرى الى دور ثقافة أو الى مطاعم ومقاهى وقاعات شاي ، مدرجة من قبل منظمة اليونسكو على قائمة التراث العالمي ، المدينة العتيقة تحتوي على نفائس معمارية مما أوجب المحافضة عليها بترميم أنهج كاملة وتبليط عديد المسالك ، عند أبوابها تمتد المدينة العصرية ذات الواجهات الجميلة ، في حين يزخر محيطها في الأحياء الجديدة بالمطاعم الراقية وأماكن الترفيه",
        en: "Tunis is a modern, thriving city with a glorious history, and it never stops surprising you. In the old medina many historic buildings open their doors: some have become museums, others cultural houses, restaurants, cafés and tea rooms. Listed by UNESCO as World Heritage, the medina holds architectural treasures that called for careful preservation, with whole lanes restored and many alleys repaved. Beyond its gates stretches the modern city with its handsome facades, while the newer districts around it are full of fine restaurants and places to go out.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES["tunis-capital"], cap_ar: "تونس العاصمة", cap_en: "The capital, Tunis" },
      { type: "H3", ar: "تعنى لتشاهد — المدينة العتيقة والعمارات الفنية", en: "Not to be missed — the medina and its art architecture", noNumber: true },
      {
        type: "P",
        ar: "مدينة تونس العتيقة محافظ عليها بشكل مستمر وتعد مسالك سياحية ممتازة ، الأسواق مكسوة بقباب تتسرب منها اضاءة خافتة وهي حاشدة بالحركة ومليئة بالسلع من كل الأنواع : الأقمشة والعطور أو المجوهرات الثمينة ، أما الأنهج السكنية ، فهي متحف مصغر للطابع العمراني التونسي : جدران بيضاء وحدادة زرقاء ، معابر مسقوفة وقباب من القرميد الأخضر ، وأبواب صفراء مؤطرة بتصاميم حجرية منحوتة",
        en: "The medina of Tunis is continuously cared for and offers excellent walking routes. The souks are covered by domes that let in a soft light, busy with movement and packed with goods of every kind: fabrics, perfumes and precious jewellery. The residential lanes are a miniature museum of Tunisian urban character: white walls and blue ironwork, roofed passages, domes of green tiles and yellow doors framed by carved stone.",
      },
      {
        type: "P",
        ar: "الجانب العصري من المدينة والأحياء المحيطة بشارع بورقيبة لها طابعها الخاص ، عند سفح العمارات ذات الهندسة الحديثة ، حشد نشيط يتسارع بين المقاهي الشعبية ، ومحلات الموضة والمترو الخفيف والنخيل ، ولا تفوتك زيارة السوق المركزي الذي يفيض بالخضر والفواكه والأسماك ، ولا تنسى مشاهدة واجهة المسرح البلدي المنحوتة ، الذي افتتح في سنة 1902 ، وتمثال ابن خلدون ، المفكر الكبير من مواليد تونس في القرن الرابع عشر",
        en: "The modern side of the city and the districts around Bourguiba Avenue have a character of their own. At the foot of the modern buildings a lively crowd hurries between popular cafés, fashion shops, the light metro and the palm trees. Do not miss the central market overflowing with vegetables, fruit and fish, nor the carved facade of the Municipal Theatre opened in 1902, and the statue of Ibn Khaldun, the great thinker born in Tunis in the fourteenth century.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — السلاطين والبايات والمدينة العتيقة", en: "To know more — sultans, beys and the medina", noNumber: true },
      {
        type: "P",
        ar: "تونس المدينة الصغيرة ذات الأصول البربرية اكتسبت أهمية كبيرة بعد تقلص نفوذ جارتها قرطاج ، حتى اصبحت عاصمة البلاد في القرن الحادى عشر ، السلاطين الحفصيون الذين حكموا جزءا كبيرا من المغرب العربي ، جعلوا منها مدينة رائعة باستقطابها للنخب الأندلسية ، بعد دخول العثمانيين في القرن السادس عشر ، أعطت التأثيرات الايطالية والتركية الأحياء القديمة سحرا خاصا ، في المدينة استمتع بمسجد الزيتونة الكبير من القرن 9 ، والمساجد التركية المحلاة بالرخام ، زيارة تربة الباي ، المقابر التي تضم رفاة أسرة الباي ، والمدارس الدينية الأنيقة من القرن الــ 18 ، والقصور المزدانة بالخزف والأرابيسك والجص المنقوش ، الأسواق المركزية والأنهج المسقوفة المخصصة لمنتوجات الحرف اليدوية من المجوهرات ، والملابس المطرزة والطربوش الأحمر التقليدي",
        en: "Tunis, a small town of Berber origins, gained great importance as the influence of its neighbour Carthage receded, until it became the capital of the country in the eleventh century. The Hafsid sultans, who ruled much of the Maghreb, turned it into a splendid city by attracting the Andalusian elite. After the Ottomans arrived in the sixteenth century, Italian and Turkish influences gave the old quarters a particular charm. In the medina enjoy the great Zitouna Mosque from the ninth century and the Turkish mosques adorned with marble, visit the Tourbet el Bey where the bey's family is buried, the elegant eighteenth-century madrasas, the palaces decorated with ceramics, arabesque and carved plaster, and the central souks and roofed lanes devoted to handicrafts: jewellery, embroidered clothes and the traditional red chechia.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — ثقافة أو سهرة عصرية", en: "Things to do — culture or a modern night out", noNumber: true },
      {
        type: "P",
        ar: "في مدينة تونس ، يمكنك زيارة معالم فائقة ، مشاهدة معرض للصور في قصر خير الدين ، أو الاستماع الى حفل للموسيقى العربية والأندلسية في فضاءات تراثية ، أو متابعة مهرجان الفن المعاصر” دريم سيتي ” ، في وسط المدينة يمكنك زيارة الكاتدرائية ذات الطراز البيزنطي الموريسكي التي لا تزال ناشطة",
        en: "In Tunis you can visit outstanding monuments, see a photography exhibition at the Khereddine Palace, listen to a concert of Arab-Andalusian music in heritage venues, or follow the contemporary art festival “Dream City”. Downtown you can visit the still-active cathedral in Byzantine-Moorish style.",
      },
      {
        type: "P",
        ar: "واستمع الى حفل موسيقى كلاسيكية في المسرح البلدي أو تنزه في حديقة البلفيدير ، العب الجولف (ملعبان بالقرب من تونس العاصمة) أو استمتع مع الأولاد بمتنزه “قرطاج لاند” ، لقضاء أمسية عصرية ، وجب التحول الى ضفاف البحيرة ، أو قمرت أو حلق الوادي ، منطقة مفضلة سابقا من الطائفة اليهودية التونسية ، البحر لا يبعد كثيرا عن مركز المدينة حيث تتوفر العديد من الأنشطة في برج السدرية والزهراء على بعد 20 كلم ، هواة التاريخ ، تمتعوا قربا من العاصمة بجاذبية ضفاف قرطاج ومعالمها الأثرية وبثراء موقع أوذنة الواقع على بعد 25 كلم من تونس",
        en: "Listen to a classical concert at the Municipal Theatre or stroll in Belvedere Park, play golf (two courses near the capital) or enjoy Carthage Land amusement park with the children. For a modern evening head to Les Berges du Lac, Gammarth or La Goulette, a district once favoured by the Tunisian Jewish community. The sea is not far from the centre, with plenty to do at Borj Cedria and Ezzahra 20 km away. History lovers will enjoy the shores of Carthage and its ancient monuments close by, as well as the rich site of Oudhna 25 km from Tunis.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الكفتاجي أو لزاني بغلال البحر", en: "Try these dishes — kaftaji or seafood lasagne", noNumber: true },
      {
        type: "P",
        ar: "في أسواق المدينة العتيقة ، سوف تجد وجبات خفيفة ولذيذة : البريك الشهي ، والشطيرة الصغيرة وصحن الكفتاجي (خضروات الصيف مع البيض المقلي) أو صحفة اللبلابي (الحساء من الحمص والفلفل الحار) ، في قصر قديم أو فندق (خان قوافل) حول الى مطعم ، ستتذوق أفضل فنون الطبخ التونسي : الكسكسي بالهامور والسفرجل وبراعم الورد ، صحن من الخضار المحشوة (فندق الغلة) ، لحم الضأن الحلو المالح اللذيذ مع الفاكهة واللوز (مرقة حلوة) ، في التحلية تذوق البوزا وهي كريم الفستق ، أو الحلويات المعطرة بماء الورد لأجواء أكثر حداثة ، انتقل الى منطقة ضفاف البحيرة ، سوف تأكل السوشي ، والمعجنات (المعكرونة) بغلال البحر",
        en: "In the souks of the medina you will find tasty light meals: delicious brik, small sandwiches, a plate of kaftaji (summer vegetables with fried egg) or a bowl of lablabi (chickpea and chilli soup). In an old palace or a caravanserai turned restaurant you will taste the best of Tunisian cooking: couscous with grouper, quince and rose buds, a dish of stuffed vegetables, sweet-and-savoury lamb with fruit and almonds (marqa hloua), and for dessert bouza, a pistachio cream, or pastries scented with rose water. For a more contemporary mood move to Les Berges du Lac, where you can eat sushi and seafood pasta.",
      },
      { type: "H3", ar: "حاول السكن في — فندق أو دار ضيافة في المدينة العتيقة", en: "Where to stay — a hotel or guest house in the medina", noNumber: true },
      {
        type: "P",
        ar: "في وسط المدينة ، أو في الأحياء الجديدة أو في قلب المدينة العتيقة ، الاختيارات واسعة ، يمكنك الاقامة في فندق أعمال أو قصر فخم دولي لاقامة رومانسية ، يمنك اختيار فندق من جيل 1920 او غرفة ضيافة بالمدينة العتيقة ، حيث تدخل في علاقة حميمة مع الأحياء التاريخية في تونس : المأكولات التقليدية والمطاعم الرائعة والتراث التاريخي ، أما اذا كنت ترغب في التمتع بالبحر ، فستجد الفنادق المطلة على البحر في الزهراء وبرج السدرية ، جنوب تونس العاصمة",
        en: "Downtown, in the newer districts or in the heart of the medina, the choice is wide. You can stay in a business hotel or an international luxury palace for a romantic break, pick a hotel from the 1920s or a guest room in the medina, where you become intimately acquainted with the historic quarters of Tunis: traditional food, wonderful restaurants and historic heritage. If you want the sea, you will find seafront hotels in Ezzahra and Borj Cedria, south of the capital.",
      },
      { type: "H3", ar: "الخلاصة — متحف باردو", en: "In short — the Bardo Museum", noNumber: true },
      {
        type: "P",
        ar: "متحف باردو هوأكبر متاحف الفسيفساء في العالم ، اتخذ مقرا له في قصر الباي السابق بباردو ، تم تجديده بالكامل وتوسعته في سنة 2012 ، يضم المتحف مجموعة فريدة من الآثار الرومانية بالاضافة الى شهادات من تاريخ تونس ، من قرطاج حتى العصر العثماني ، منذ الدخول سيشدك مشهد أسطوري ضخم في فسيفساء تبرز مشاهد ميثولوجية حول عربة الآلهة نبتون ، ثم تمعن في الآلهة القرطاجية الغريبة ، تماثيل من الرخام كانت تزين المعابد الرومانية ، كما ستكتشف التراث اليهودي في تونس والاعمدة الحجرية التي تحمل طقوسا نوميدية ، الفن الاسلامي في تونس هو في دائرة الضوء : الأسطرلاب والمخطوطات الثمينة ، والأكواب الخزفية ، فضلا عن الزخرفة الغنية للقصر الذي يضم المتحف ، تأمل الروائع الواحدة تلوى الأخرى لمبدعي فسيفساء تونس ، الذين كانوا الأكثر شهرة في العهد الروماني ، هذه اللوحات تصور مغامرات أوليس والأعمال في الحقول ، والألعاب في المسرح وآلهة الأوليمب ، انها رحلة رائعة عبر الزمن",
        en: "The Bardo is the largest mosaic museum in the world, housed in the former bey's palace at Bardo and fully renovated and enlarged in 2012. It holds a unique collection of Roman antiquities alongside testimonies from Tunisia's history, from Carthage to the Ottoman era. From the entrance you are struck by an immense mythological mosaic showing scenes around the chariot of Neptune. Then study the strange Carthaginian deities, marble statues that once adorned Roman temples, the Jewish heritage of Tunisia and stone stelae bearing Numidian rites. Islamic art in Tunisia is in the spotlight too: astrolabes, precious manuscripts, ceramic bowls, as well as the rich decoration of the palace itself. Admire one masterpiece after another by Tunisia's mosaic makers, the most renowned of the Roman period, depicting the adventures of Ulysses, work in the fields, games in the theatre and the gods of Olympus. It is a wonderful journey through time.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "في المدينة العتيقة تتوفر أفضل التخصصات من الحرف اليدوية التونسية : فساتين مطرزة بالحرير ، صناديق المجوهرات المنقوشة بالفضة ، وأيضا الشاشية ، الطربوش التونسي الأحمر ، التي تقدم اليوم في ألوان مختلفة ، الأحياء العصرية تتواجد بها العديد من مراكز التسوق التي تحوي العلامات التجارية العالمية وكذلك محلات التصاميم والابتكار للصناعات التقليدية",
        en: "The medina offers the best Tunisian handicraft specialities: dresses embroidered with silk, jewellery boxes inlaid with silver, and the chechia, the red Tunisian cap, today made in various colours. The modern districts have many shopping centres with international brands as well as design shops that reinvent traditional crafts.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "المترو الخفيف (الترام) خدماته في جميع أنحاء العاصمة ، سيارة الأجرة تبقى وسيلة مريحة ورخيصة للتنقل ، المنتجعات السياحية في جنوب تونس (الزهراء، برج السدرية) يربطها القطار من المحطة المركزية بساحة برشلونة ، أما الضواحي الشمالية حلق الوادي ، قرطاج والمرسى فقطار (ت.ج.م) يربطها من محطة تونس البحرية",
        en: "The light metro (tram) serves the whole capital, and taxis remain a comfortable and cheap way to get around. The resorts south of Tunis (Ezzahra, Borj Cedria) are linked by train from the central station at Barcelona Square, while the northern suburbs of La Goulette, Carthage and La Marsa are served by the TGM train from Tunis Marine station.",
      },
    ],
  },
  {
    slug: "carthage-sidi-bou-said",
    title_ar: "قرطاج وسيدي بو سعيد وما حولهما",
    title_en: "Carthage, Sidi Bou Said and around",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES["carthage-sidi-bou-said"],
    blocks: [
      { type: "H3", ar: "قرطاج وسيدي بوسعيد .. متعة السفر والسياحة", en: "Carthage and Sidi Bou Said — the pleasure of travel", noNumber: true },
      {
        type: "P",
        ar: "قرطاج سيدي بو سعيد ، حلق الوادى ، قمرت ، المرسى : موقع مميز ومشاهد أخاذة بالقرب من العاصمة تلك هي ضفاف قرطاج ، منطقة الاصطياف والمهرجانات والسهر ، قرطاج اليوم هي مدينة حديثة يقترن اسمها صيفا بمهرجانه الموسيقي الدولي ، جارتها سيدي بو سعيد ، قرية بديعة فوق التلال ، ذات المنازل البيضاء والزرقاء المطلة على البحر ، بالقرب تمتد شواطئ المرسى ومنتجع قمرت بنزله الفاخرة",
        en: "Carthage, Sidi Bou Said, La Goulette, Gammarth, La Marsa: a remarkable setting and breathtaking views right beside the capital — these are the shores of Carthage, a place of summer holidays, festivals and nightlife. Carthage today is a modern town whose name is tied in summer to its international music festival. Its neighbour Sidi Bou Said is an exquisite hilltop village of white and blue houses overlooking the sea, and nearby stretch the beaches of La Marsa and the Gammarth resort with its luxury hotels.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES["carthage-sidi-bou-said"], cap_ar: "قرطاج وسيدي بو سعيد", cap_en: "Carthage and Sidi Bou Said" },
      { type: "H3", ar: "تعنى لتشاهد — التاريخ والشاعرية", en: "Not to be missed — history and poetry", noNumber: true },
      {
        type: "P",
        ar: "قرطاج هي بلا منازع من أجمل المواقع حول البحر المتوسط ، فتنة الخليج ذي الانعكاسات الفيروزية ، والمنازل البيضاء المحاطة بأشجار السرو ، وفي الأفق جبل بوقرنين يطل من وراء الضباب ، تجول في أنهج المدينة واكتشف مقتطفات تاريخية : بقايا كنيسة سان سيبريان المطلة على البحر والمنازل القرطاجية بحي ماجون والموانئ البونيقية أين تربض بعض قوارب الصيادين ، ثم اتجه نحو قرية سيدي بو سعيد وتجول في أنهجها المبلطة بين الشبابيك الزرقاء والبوجانفيليا الوردي ، تناول عصيرا وقسطا من الراحة في مقهى الحصائر لطابعها واجوائها التقليدية ، تمعن المشاهد الطبيعية البحرية الرائعة من مقهى سيدي الشبعان ، عديد الفنانين والرسامين استقروا في هذه القرية الملهمة ، غير بعيد عنها المرسى وواجهتها البحرية ، وقمرت وشواطئها الممتدة ، تجذب سكان تونس الباحثين عن أماكن للاسترخاء",
        en: "Carthage is unquestionably one of the loveliest sites on the Mediterranean: the charm of a bay with turquoise reflections, white houses surrounded by cypress trees, and on the horizon Mount Boukornine emerging from the haze. Wander the streets and discover fragments of history: the remains of the Saint Cyprian church above the sea, the Punic houses of the Magon quarter, and the Punic ports where a few fishing boats still rest. Then head to the village of Sidi Bou Said and stroll its paved lanes between blue shutters and pink bougainvillea; take a juice and a rest at the Café des Nattes for its traditional character, and contemplate the superb sea views from Café Sidi Chabaane. Many artists and painters have settled in this inspiring village. Not far away, La Marsa with its seafront and Gammarth with its long beaches draw the people of Tunis in search of somewhere to relax.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — قرطاج المدينة الرائدة قديما", en: "To know more — Carthage, a leading city of antiquity", noNumber: true },
      {
        type: "P",
        ar: "تأسست قرطاج من قبل الملكة الفينيقية عليسة ، المعروفة أيضا باسم ديدون ، وكانت احدى أكثر المدن نفوذا في العصور القديمة ، حيث امتد نفوذها الى سردينيا واسبانيا ، وكان الزراعة ، ورغم انتصارات القائد حنبعل ، غزا الرومان قرطاج وجعلوا منها واحدة من أكثر المدن المزدهرة لامبراطوريتهم ، وفي وقت لاحق ، درس بها القديس أوغسطين ، أحد آباء الكنيسة في الغرب ، في متحف قرطاج ، تعرف على الحضارة البونيقية ، حيث ترى تمثال الاله بعل متربعا على عرشه ، أقنعة الطين المطهو ، الأعمدة الحجرية تحمل منحوتة “علامة التانيت” الغامضة ، في الموقع نفسه ، سترى الميناء القديم البونيقي وآثار منازل وغيرها من القرطاجيون (أوالبونيقيون) منافسين لليونانيين لمهارتهم في الابحار والتجارة و بقايا الآثار الرومانية الكثيرة",
        en: "Carthage was founded by the Phoenician queen Elissa, also known as Dido, and was one of the most powerful cities of antiquity, its influence reaching Sardinia and Spain. Despite the victories of the general Hannibal, the Romans conquered Carthage and made it one of the most prosperous cities of their empire; later Saint Augustine, one of the Fathers of the Western Church, studied here. In the Carthage museum you meet the Punic civilisation: a statue of the god Baal seated on his throne, terracotta masks, stone stelae carved with the mysterious “sign of Tanit”. On the same site you will see the ancient Punic port and the remains of houses — the Carthaginians, or Punics, rivalled the Greeks in seafaring and trade — as well as abundant Roman remains.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — الثقافة والحياة الليلية", en: "Things to do — culture and nightlife", noNumber: true },
      {
        type: "P",
        ar: "موقع قرطاج مسجل بقائمة التراث العالمي لليونسكو ويستحق زيارة مطولة ، تراكم الاثار في مساحة كبيرة تسمح لنا بتصور المدينة التاريخية : خزانات مياه بسعة 60 مليون لتر ، حمامات رومانية ضخمة ، ونمط عيش راق ، بالمتحف الأثري ، سنكتشف الفن والشعائر الدينية لقرطاج البونية ، اليوم قرطاج وما جاورها هي مراكز الثقافة حيث العديد من دور العرض الفنية ، الحفلات والعروض الموسيقية تتم في الكاتدرائية القديمة (الأكروبليوم) بقرطاج ، وفي قصر العبدلية بالمرسى أو في قصر البارون دي ارلانجي في سيدي بو سعيد ، المنطقة مكرسة أيضا للترفيه : فنادق شاطئية ، رياضات مائية ، ومراكز علاج بمياه البحر وملعبان للجولف ومارينا سيدي بو سعيد ، أما حياة الليل فهي ثرية : المطاعم والمشارب والنوادي الليلية والمهرجانات الموسيقية مهرجان «الجاز في قرطاج» والموسيقى الكلاسيكية «أكتوبر الموسيقى» في الأكروبليوم ، في الصيف يستضيف المسرح الأثري عروضا دولية في مهرجان قرطاج الدولي",
        en: "The site of Carthage is inscribed on the UNESCO World Heritage list and deserves a long visit. Ruins spread over a wide area let you picture the ancient city: cisterns holding 60 million litres, immense Roman baths and a refined way of life. In the archaeological museum you discover the art and religious rites of Punic Carthage. Today Carthage and its neighbours are centres of culture with many art venues; concerts are held in the old cathedral (the Acropolium) at Carthage, at the Abdellia Palace in La Marsa or at the Baron d'Erlanger palace in Sidi Bou Said. The area is devoted to leisure too: beach hotels, water sports, thalassotherapy centres, two golf courses and the Sidi Bou Said marina. Nightlife is rich, with restaurants, bars, clubs and music festivals — “Jazz à Carthage” and the classical “Octobre Musical” at the Acropolium — while in summer the ancient theatre hosts international performances during the Carthage International Festival.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الطبخ الراقي", en: "Try these dishes — refined cooking", noNumber: true },
      {
        type: "P",
        ar: "منطقة اصطياف البايات سابقا ، ضفاف قرطاج كانت ولا زالت واحدة من أكثر المناطق شهرة في فن الطبخ ، الطهي الأصيل للعاصمة لا يزال متداولا ، تذوق مثلا الكابكابو وهو طبق من السمك مع الزيتون والليمون المصبر ، كمفتحات تذوق الطاجين التونسي – عجة سميكة بالخضار والجبن ، قريبة من التورتيا الاسبانية والسلطة المشوية وهي من الطماطم والفلفل المشويان ، في سيدي بو سعيد وقرطاج والمرسى ، اختيارات عديدة من المطاعم ، يمكن الاستمتاع بالاطباق التونسية التقليدية في ديكور قصر عثماني ، المطبخ المتوسطي المبتكر والوجبات الخفيفة مع الكوكتيلات في مشرب عصري ، أو أطباق ايطالية في أجواء استرخاء ، واذا زرت سيدي بو سعيد ، فاستمتع “بالبانبالوني” ، فطائر على شكل حلقة تؤكل ساخنة ، ثم بكأس من الشاي مع النعناع وحبوب الصنوبر في مقهى الحصائرالشهير",
        en: "Once the summer retreat of the beys, the shores of Carthage remain one of the most celebrated areas for cooking, and the capital's authentic cuisine is still served here. Taste kabkabou, a fish dish with olives and preserved lemon; as starters try Tunisian tajine, a thick omelette with vegetables and cheese close to the Spanish tortilla, and slata mechouia of grilled tomatoes and peppers. In Sidi Bou Said, Carthage and La Marsa the choice of restaurants is wide: traditional Tunisian dishes in the decor of an Ottoman palace, inventive Mediterranean cooking and light plates with cocktails in a modern bar, or Italian dishes in a relaxed setting. And if you visit Sidi Bou Said, enjoy a bambalouni, a ring-shaped doughnut eaten hot, then a glass of mint tea with pine nuts at the famous Café des Nattes.",
      },
      { type: "H3", ar: "حاول السكن في — فنادق فخمة ودور الضيافة", en: "Where to stay — luxury hotels and guest houses", noNumber: true },
      {
        type: "P",
        ar: "شواطئ قمرت تحفها الفنادق الشاطئية من كل الأصناف والأنواع ، من النادي البسيط الى المنتجع القصر ، خيارات أخرى للسكن متاحة ، اذا استهوتك قرية سيدي بو سعيد ، يمكن أن تقيم في فندق ظريف أو دار للضيافة ، أما اذا كنت تبحث عن راحة أكثر فخامة وحداثة ورقي ، فاختر اقامة فاخرة في غابة قمرت ، أو فندقا في قرطاج أو في كورنيش المرسى",
        en: "The beaches of Gammarth are lined with seaside hotels of every kind, from the simple club to the palace resort. Other options exist too: if the village of Sidi Bou Said charms you, stay in a delightful small hotel or a guest house; and if you are looking for greater luxury, modernity and refinement, choose a luxury stay in the Gammarth woods, a hotel in Carthage or one on the La Marsa corniche.",
      },
      { type: "H3", ar: "الخلاصة — منازل وقصور سيدي بوسعيد", en: "In short — the houses and palaces of Sidi Bou Said", noNumber: true },
      {
        type: "P",
        ar: "في سيدي بو سعيد الأبواب هي ابتسامة المنازل : زرقاء أو صفراء مشرقة ، مقوسة أو مستطيلة ، مؤطرة بالحجر المنقوش أو بالخزف ، أ وبالرخام الأبيض والأسود ، لكل منها نمطه الخاص ، أجملها مزركشة بمسامير سوداء كبيرة رتبت بخبرة في شكل نجوم ، او وردة او سمكة ، أثناء تنزهك لا تتردد في ترك الطريق الرئيسي لاستكشاف الأنهج الضيقة : ففي كل خطوة باب جديد يفاجئك ، سيدي بو سعيد كانت سابقا المنتجع المفضل لقضاء العطلة لدى العائلات التونسية المترفه ، على شاطئ البحر ، أعادوا تشكيل طريقة عيشهم المرهفة تحت رعاية ضريح سيدي أبو سعيد ، الولي الصالح من القرن الــ 13 ، خلف الجدران البسيطة المكسوة بالجير الكلسي الأبيض يختفي في بعض الأحيان قصر حقيقي ، وأحد هذه القصور بناه أوروبي متيم بالقرية سنة 1912 ، البارون رودولف دي ارلانجر ، حول اليوم الى متحف ، ويستضيف الحفلات الموسيقية ، منازل أخرى عديدة أضحت معارض للفنون أو دورا للضيافة",
        en: "In Sidi Bou Said the doors are the smile of the houses: blue or bright yellow, arched or rectangular, framed in carved stone, ceramic or black-and-white marble, each with its own style. The finest are studded with large black nails arranged expertly into stars, a rose or a fish. As you walk, do not hesitate to leave the main street and explore the narrow lanes: at every step a new door surprises you. Sidi Bou Said was once the favourite holiday retreat of well-to-do Tunisian families, who by the sea recreated their refined way of life under the protection of the shrine of Sidi Bou Said, a saint of the thirteenth century. Behind plain whitewashed walls a real palace is sometimes hidden; one of them was built in 1912 by a European in love with the village, Baron Rodolphe d'Erlanger, and is today a museum hosting concerts. Many other houses have become art galleries or guest houses.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "في سوق سيدي بو سعيد ، تشتري السجاد والهدايا التذكارية من الخزف والجلود والنعال الشرقية ، استفد من عديد محلات الصناعات التقليدية بقرطاج وما جاورها : منسوجات الصوف أو الحرير ، والمصابيح والزجاج المنفوخ والحلي التقليدي الذي أعيدت صياغته ، خيارات أخرى متوفرة كالحلويات التونسية ، مثل الحلويات بالتمر ، والصابون المعطر بالياسمين والفوطة (مناشف الحمام)",
        en: "In the souk of Sidi Bou Said you can buy carpets and souvenirs of ceramic and leather as well as oriental slippers. Make the most of the many craft shops in Carthage and around: wool or silk weaving, lamps, blown glass and traditional jewellery reworked in modern style. Other choices include Tunisian sweets such as date pastries, jasmine-scented soap and the fouta hammam towel.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "يبعد مطار تونس قرطاج 20 كلم عن فنادق قمرت ، وقطار (تي جي أم) يربط المرسى وسيدي بوسعيد ، قرطاج ، حلق الوادي وتونس ، خطوط الحافلات السريعة تربط المنطقة بتونس ، لزيارة قرطاج ، بالأمكان الاتفاق مع سيارة أجرة على معلوم لزيارة مختلف المواقع المنتشرة في المدينة الحديثة",
        en: "Tunis-Carthage airport is 20 km from the Gammarth hotels, and the TGM train links La Marsa, Sidi Bou Said, Carthage, La Goulette and Tunis. Express bus lines connect the area with Tunis. To visit Carthage you can agree a fare with a taxi to tour the various sites spread through the modern town.",
      },
    ],
  },
  {
    slug: "sbeitla",
    title_ar: "سبيطلة",
    title_en: "Sbeitla",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES.sbeitla,
    blocks: [
      { type: "H3", ar: "سبيطلة .. متعة السفر والترفية", en: "Sbeitla — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "سبيطلة مدينة صغيرة في الوسط الغربي للبلاد تقع على بعد 250 كلم من تونس العاصمة ، شهرت خصوصا بموقعها الروماني الرائع ، موقع سبيطلة لافت للنظر بمبنى الكابيتول المؤلف من ثلاثة معابد مخصصة للآلهة الحارسة لروما ، وبالقرب من سبيطلة موقعي مكثر ، أحد أكبر المواقع في تونس ، يضم آثارا مذهلة مثل قوس تراجان ، والحمامات الكبرى ورواق أنيق من الأعمدة ، وحيدرة حيث بقايا أحد أكبر الحصون البيزنطية بالمغرب العربي",
        en: "Sbeitla is a small town in the west-centre of the country, 250 km from Tunis, famous above all for its magnificent Roman site. What strikes you there is the Capitol, made up of three temples dedicated to the guardian gods of Rome. Near Sbeitla lie the sites of Makthar, one of the largest in Tunisia, with astonishing remains such as the arch of Trajan, the great baths and an elegant colonnade, and Haïdra, where the ruins of one of the largest Byzantine fortresses in the Maghreb still stand.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES.sbeitla, cap_ar: "موقع سبيطلة الأثري", cap_en: "The archaeological site of Sbeitla" },
      { type: "H3", ar: "تعنى لتشاهد — الآثار المسيحية القديمة", en: "Not to be missed — the early Christian remains", noNumber: true },
      {
        type: "P",
        ar: "تزخر المنطقة بعددا كبيرا من الآثار المسيحية القديمة ، في سبيطلة ، الكنيسة الكبرى فيتاليس بها وعاء جميل للتنصير مغطى بالفسيفساء ، والأقواس هي كل ما تبقى من كنيسة كبيرة من 33 مترا ، معالم تشير الى أن تونس كانت مركزا رئيسيا للمسيحية",
        en: "The region abounds in early Christian remains. At Sbeitla the great basilica of Vitalis has a beautiful baptismal font covered in mosaic, and a few arches are all that survive of a large church 33 metres long — monuments showing that Tunisia was a major centre of Christianity.",
      },
      { type: "H3", ar: "حاول السكن في — أحد الفنادق الجيدة", en: "Where to stay — a good hotel", noNumber: true },
      {
        type: "P",
        ar: "بعض الفنادق في القصرين وقرب موقع سبيطلة الأثري",
        en: "There are a few hotels in Kasserine and near the archaeological site of Sbeitla.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "تبعد سبيطلة 250 كلم عن تونس العاصمة و215 كلم عن توزر و30 كلم عن القصرين",
        en: "Sbeitla is 250 km from Tunis, 215 km from Tozeur and 30 km from Kasserine.",
      },
    ],
  },
  {
    slug: "sousse-kantaoui",
    title_ar: "سوسة والقنطاوي وما حولهما",
    title_en: "Sousse, Port El Kantaoui and around",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES["sousse-kantaoui"],
    blocks: [
      { type: "H3", ar: "سوسة والقنطاوي .. متعة السفر والسياحة", en: "Sousse and El Kantaoui — the pleasure of travel", noNumber: true },
      {
        type: "P",
        ar: "شواطئ ممتدة ومعالم تاريخية ونخيل باسق ، سوسة هي مدينة مفعمة بالمغريات حيث تجمع بين الترفيه والاكتشاف في وئام وتناغم ، مدينة حديثة ، هي واحدة من أكثر محطات الاصطياف حيوية في تونس ، وهي أيضا مدينة التاريخ ، حيث حافظت على المدينة العتيقة الرائعة والمعالم الاستثنائية التي جعلتها تصنف من بين معالم التراث الانساني من طرف اليونسكو ، وعلى بعد دقائق قليلة من سوسة ، المحطة المندمجة لميناء القنطاوي ذات الطابع الأندلسي المسخرة للترفية و الاصطياف",
        en: "Long beaches, historic monuments and tall palm trees: Sousse is a city full of temptations, combining leisure and discovery in harmony. A modern city, it is one of the liveliest holiday resorts in Tunisia, and it is also a city of history, having preserved a magnificent medina and exceptional monuments that earned it a place on the UNESCO World Heritage list. A few minutes from Sousse lies the integrated resort of Port El Kantaoui in Andalusian style, devoted to leisure and summer holidays.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES["sousse-kantaoui"], cap_ar: "سوسة وميناء القنطاوي", cap_en: "Sousse and Port El Kantaoui" },
      { type: "H3", ar: "تعنى لتشاهد — البحر والتاريخ", en: "Not to be missed — the sea and history", noNumber: true },
      {
        type: "P",
        ar: "في عصور ما قبل التاريخ كانت سوسة ، المسمات آنذاك حضرموت ، مدينة مشعة ، ثم تلاشى دورها الى أن جعل منها الأغالبة القاعدة البحرية للبلاد ، اليوم تضم المدينة العتيقة عدة معالم تذكر بمجد المدينة القديم : برج خلف المهيمن على المدينة وأسوارها ، الرباط وهو قلعة ومكان تزهد ديني ، والجامع الكبير الذي يبدو هو الأخر كقلعة ، والقصبة المهيبة ، ثالث مدينة في تونس ، تضم سوسة في جزءها العصري وسط مدينة نابضا بالحياة مع العديد من المحلات التجارية ومرافق الترفيه ، ومنتزها رائعا على الواجهة البحرية ، على بعد دقائق قليلة تجول على أرصفة مارينا مرسى القنطاوي ، و يمكنك أيضا زيارة القرى المجاورة للانتعاش بهواءها النقي ومشاهدة غابات الزياتين التي تشكل ثراء المنطقة منذ العصور القديمة",
        en: "In ancient times Sousse, then called Hadrumetum, was a brilliant city; its role later faded until the Aghlabids made it the naval base of the country. Today the medina holds several monuments recalling the city's old glory: the Khalaf tower dominating the town and its walls, the ribat which is both fortress and place of religious retreat, the Great Mosque that also looks like a fortress, and the imposing kasbah. The third city of Tunisia, Sousse has in its modern part a lively centre with many shops and leisure facilities and a fine seafront promenade. A few minutes away you can walk the quays of the Port El Kantaoui marina, and you can also visit the neighbouring villages for fresh air and the olive groves that have been the wealth of the region since antiquity.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — الفسيفساء والقلعة", en: "To know more — mosaics and the fortress", noNumber: true },
      {
        type: "P",
        ar: "في العصور القديمة كانت سوسة مزدهرة وتشتهر بالفسيفساء الجميل الذي يعرض اليوم في المتحف الأثري للمدينة ، أما المدينة العتيقة ، فقد توسعت منذ القرن التاسع حول الرباط ، موقع تزهد المتصوفين ، لقربها من القيروان ، العاصمة القديمة لتونس ، اتخذت سوسة كميناء عسكري انطلق منه الفتح الاسلامي لصقلية سنة 827 ، الجامع الكبير دون مئذنة ، هي شهادة استثنائية عن الهندسة المعمارية لتلك الفترة ، ومثله حصون المدينة المحفوظة على أحسن وجه والرباط والقصبة (قلعة) ، موقع أثري رائع آخر من العصور الوسطى ، القبة الكبيرة ، قبة الخاوي ، ذات النحت المزرد المجاورة لمتحف الفنون والتقاليد الشعبية",
        en: "In antiquity Sousse was prosperous and famous for beautiful mosaics, displayed today in the city's archaeological museum. The medina grew from the ninth century around the ribat, a retreat for mystics. Because of its closeness to Kairouan, Tunisia's old capital, Sousse was used as a military port from which the Islamic conquest of Sicily set out in 827. The Great Mosque, without a minaret, is an exceptional testimony to the architecture of that period, as are the city's remarkably preserved walls, the ribat and the kasbah. Another fine medieval site is the Kalaout el Koubba with its ribbed carving, next to the Museum of Popular Arts and Traditions.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — ارتياد النوادي وفهم الثقافة", en: "Things to do — clubs and culture", noNumber: true },
      {
        type: "P",
        ar: "رمال ناعمة ، مسابح ، رياضات مائية ، الفنادق العديدة بسوسة تلبي جميع رغبات العطل ، القنطاوي جولف (36 حفرة) يؤمه اللاعبون من جميع أنحاء العالم ، المنتجعات الجميلة ومراكز العلاج بمياه البحر توفر الرعاية في فصل الشتاء كما في الصيف ، الملاهي الليلية الشهيرة ، وثلاثة كازينوهات ، ومجموعة واسعة من المشارب والمطاعم تجعل من سوسة منتجعا نشيطا ، يتوفر بمرسى القنطاوي ، المنطقة المحببة لهوات السياحة البحرية ، مركزا للغوص ، في المدينة العتيقة ، العديد من المواقع الأثرية الاستثنائية تستحق الزيارة ، بعضها يعطي اطلالة بانورامية على المدينة ، المتحف الأثري بالقصبة الذي تم تجديده بالكامل يعرض لوحات الفسيفساء الروماني الفائقة الجمال ، في حين يستحضر متحف الفنون والتقاليد الشعبية الحياة اليومية في سوسة وحرفييها على شاكلة متحف الشمع ، حول سوسة ، استمتع بزيارة ثلاث مدن تاريخية أخرى : المنستير والقيروان والمهدية",
        en: "Soft sand, swimming pools and water sports: the many hotels of Sousse meet every holiday wish. El Kantaoui golf (36 holes) attracts players from all over the world, and the fine resorts and thalassotherapy centres offer treatments in winter as in summer. Famous nightclubs, three casinos and a wide range of bars and restaurants make Sousse a lively resort, while Port El Kantaoui, beloved of sailing enthusiasts, has a diving centre. In the medina many exceptional historic sites deserve a visit, some giving a panoramic view over the city. The fully renovated archaeological museum in the kasbah displays superb Roman mosaics, while the Museum of Popular Arts and Traditions evokes daily life in Sousse and its craftsmen in the manner of a wax museum. Around Sousse, enjoy visiting three other historic cities: Monastir, Kairouan and Mahdia.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الأسماك والأخطبوط", en: "Try these dishes — fish and octopus", noNumber: true },
      {
        type: "P",
        ar: "تقع سوسة في قلب منطقة شاسعة من زراعة الزيتون ، لهذا يستعمل زيت الزيتون في العديد من الأطباق الشهية : السلطة والأطباق المطبوخة وأيضا الحلويات ، سوسة مدينة ساحلية تمنح تشكيلة واسعة من منتوجات البحر المفعمة بالنكهات الطيبة : الأسماك والحبار والأخطبوط ، أما اذا كنت تفضل طبقا محليا صرفا بلحم الضأن ، تذوق البرغل الساحلي ، القمح المقشر والمسلوق على البخار مع اللحم والخضار ، واختم المأدبة بالشاي بالنعناع مع حلويات المقروض القيرواني أو مرطبات أخرى ، سوسة هي أيضا مدينة عصرية منفتحة على العالم ، اذ تجد فيها مطاعم ممتازة للتمتع بالسوشي ، والتاباس أو الأطباق الايطالية ، مجموعة من المطاعم بانتظارك في المنتجع السياحي ، في قصور المدينة و على أرصفة ميناء القنطاوي مع اطلالة على اليخوت والزوارق",
        en: "Sousse lies at the heart of a vast olive-growing region, so olive oil is used in many delicious dishes: salads, cooked plates and even sweets. As a coastal city Sousse offers a wide variety of seafood full of fine flavours: fish, squid and octopus. If you prefer a purely local dish with lamb, taste coastal borghol, hulled wheat steamed with meat and vegetables, and end the meal with mint tea and makroudh from Kairouan or other sweets. Sousse is also a modern city open to the world, with excellent restaurants for sushi, tapas or Italian dishes, and a whole range of places awaiting you in the tourist resort, in the city's palaces and on the quays of Port El Kantaoui overlooking the yachts and boats.",
      },
      { type: "H3", ar: "حاول السكن في — فندق أو شقق فندقية", en: "Where to stay — a hotel or apart-hotel", noNumber: true },
      {
        type: "P",
        ar: "تمتد على الواجهة البحرية الضخمة من سوسة الى ميناء القنطاوي ، فنادق الاصطياف الكبيرة لقضاء عطل الأحلام ، كلها توفر جميع الأنشطة والخدمات التي قد ترغب فيها ، ولأكثر استقلالية ، يمكن الاقامة في الشقق الفندقية بمارينا مرسى القنطاوي ، اذا رغبتم في أكثر سحر وهدوء وحميمية ، هناك عدد من الفنادق الصغيرة ودورالضيافة تفتح أبوابها في المدينة العتيقة وعلى الشواطئ المجاورة اسوسة",
        en: "Along the vast seafront from Sousse to Port El Kantaoui stand the large holiday hotels for a dream break, all offering every activity and service you could wish for. For more independence you can stay in the apart-hotels at the El Kantaoui marina, and if you want more charm, calm and intimacy a number of small hotels and guest houses open their doors in the medina and on the beaches near Sousse.",
      },
      { type: "H3", ar: "الخلاصة — زيت الزيتون", en: "In short — olive oil", noNumber: true },
      {
        type: "P",
        ar: "هل تعلم أن تونس هي أكبر منتج ومصدر لزيت الزيتون خارج الاتحاد الأوروبي ؟ في نهاية العصور القديمة ، كانت تونس أول مزود بالزيت لكامل الامبراطورية الرومانية ، وفي تونس اليوم نرى مناطق عدة من البلاد مرصعة بأشجار الزيتون العريقة ، فالزيتون كان دوما احدى أولى ثروات تونس ومنطقة سوسة مركزا رئيسيا للانتاج ، كما اشار الى ذلك الجغرافي الأندلسي البكري في القرن الحدي عشر ، “من بين عجائب القيروان نشير الى أهمية غابات الزياتين” ، كل شتاء يؤخذ الزيتون الى االمعصرة ، حيث يتم طحنه وعصره لاستخراج الزيت البكر الممتاز منه ، فلتكن اقامتك فرصة لتذوق الزيت التونسي اللذيذ والصحي بما أنه المكون الأساسي «لنظام الأكل المتوسطي» الشهير",
        en: "Did you know that Tunisia is the largest producer and exporter of olive oil outside the European Union? In late antiquity it was the first supplier of oil to the whole Roman Empire, and today several regions of the country are studded with ancient olive trees. The olive has always been one of Tunisia's first sources of wealth, and the Sousse region a major centre of production, as the Andalusian geographer al-Bakri noted in the eleventh century: “Among the wonders of Kairouan we note the importance of the olive groves.” Every winter the olives are taken to the press, where they are ground and pressed to extract extra-virgin oil. Let your stay be a chance to taste delicious, healthy Tunisian oil, the essential ingredient of the famous Mediterranean diet.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "الأسواق في سوسة تزخر بمنتجات الحرف اليدوية كسجاد القيروان السميك ، والمصابيح النحاسية المنقوشة ، والفساتين المطرزة وطواقم الشاي الخزفية المزينة ، والخفاف الجلدية متعددة الألوان ، وأيضا معدات نحتت من خشب الزيتون ، كالتماثيل الجميلة وأدوات المائدة والمطبخ ، كما يمكن اقتناء زيت الزيتون الذي تنتجه غابات المنطقة",
        en: "The souks of Sousse overflow with handicrafts: thick Kairouan carpets, engraved copper lamps, embroidered dresses, decorated ceramic tea sets, colourful leather slippers and objects carved from olive wood such as fine figurines and tableware and kitchen utensils. You can also buy the olive oil produced by the groves of the region.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "المطارات الدولية : في المنستير (20 كلم عن مدينة سوسة) والنفيضة (35 كلم من ميناء القنطاوي) ، خط قطار يربط سوسة بتونس العاصمة وصفاقس ، خط القطارات الجهوي يتيح سهولة الوصول الى المنستير والمهدية عبر قرى لمطة (موقع أثري) والمكنين (ورش الفخار)",
        en: "International airports: Monastir (20 km from Sousse) and Enfidha (35 km from Port El Kantaoui). A railway line links Sousse with Tunis and Sfax, and the regional line makes it easy to reach Monastir and Mahdia by way of the villages of Lamta (an archaeological site) and Moknine (pottery workshops).",
      },
    ],
  },
  {
    slug: "tabarka",
    title_ar: "طبرقة",
    title_en: "Tabarka",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES.tabarka,
    blocks: [
      { type: "H3", ar: "طبرقة .. متعة السفر والسياحة", en: "Tabarka — the pleasure of travel", noNumber: true },
      {
        type: "P",
        ar: "تقصد طبرقة لطبيعتها المتميزة ، بين البحر والجبال ،وشواطئ ذات رمال شقراء محاطة بنتوءات صخرية وغابات الصنوبر والبلوط ، البحر الصافي يخفي في أعماقه المرجان الأحمر الثمين ، والحصن الجنوي ، الشامخ على جزيرة صغيرة ، هو شعار مميز لطبرقة ، المناطق الداخلية الجبلية هي موعد مع رحلات ممتعة حول قرية عين دراهم ، نقطة الانطلاق نحو غابة شاسعة",
        en: "You come to Tabarka for its remarkable nature, between sea and mountains, with blond sandy beaches framed by rocky outcrops and forests of pine and oak. The clear sea hides precious red coral in its depths, and the Genoese fort standing tall on a small island is Tabarka's emblem. The mountainous interior promises lovely excursions around the village of Aïn Draham, the gateway to a vast forest.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES.tabarka, cap_ar: "طبرقة بين البحر والجبال", cap_en: "Tabarka between sea and mountains" },
      { type: "H3", ar: "تعنى لتشاهد — الغابات والسواحل البرية", en: "Not to be missed — forests and wild coasts", noNumber: true },
      {
        type: "P",
        ar: "حافظ وسط مدينة طبرقة ، المشيد في بداية عهد الحماية الفرنسية ، على طابعه القديم ، خذ لك شرابا في مقهى الأندلس ، مقهى تقليدي في قلب المدينة ، ثم تجول على طول المارينا ، حيث قوارب الصيادين الى جانب اليخوت ، وعلى مقربة محلات المجوهرات تقدم نفائس من لؤلؤ المرجان ، الحرفيون يصنعون أيضا تحفا من الفلين الذي يجمع في المنطقة ، وكذلك من الخشب المنحوت ، اختر نقطة عالية من المدينة للاستمتاع بالمشهد المدهش للخليج ، ثم تمهل عند الابر الصخرية العالية المنحوتة بمياه البحر والتي تتوهج عند غروب الشمس في عرض بديع ، وفي الداخل يبدو الجبل ملفوفا بمعطف غابي سميك ، هنا قرية عين دراهم بمنازلها ذات اسطح القرميد الأحمر",
        en: "The centre of Tabarka, built at the beginning of the French protectorate, has kept its old character. Have a drink at the Café Andalous, a traditional café in the heart of town, then walk along the marina where fishing boats sit beside yachts, and close by jewellery shops offer treasures of coral. Craftsmen also make pieces from the cork gathered in the region and from carved wood. Choose a high point in the town to enjoy the astonishing view over the bay, then linger at the tall rock needles carved by the sea, which glow at sunset in a magnificent display. Inland the mountain appears wrapped in a thick forest coat, and here stands the village of Aïn Draham with its red-tiled roofs.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — جبال غابية رائعة", en: "To know more — magnificent forested mountains", noNumber: true },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — الغوص أو التجول لمسافات طويلة", en: "Things to do — diving or long walks", noNumber: true },
      {
        type: "P",
        ar: "” لا تسمر أحمق ” كان في السبعينات شعارا مميزا لمهرجان طبرقة الموسيقي ، مغزى هذا الشعار أن طبرقة تقدم أكثر من الاصطياف ، فهي تنفرد بتضاريس وطبيعة تشبهها بجزيرة كورسيكا دون أي منطقة أخرى في تونس ، فطبرقة وجهة للاكتشاف ولها تقليد طويل في الغوص ومواقع الغطس فيها مذهلة ، كما أنها توفر العديد من فرص الرحلات في البحر نحو الخلجان القريبة أو الى جزيرة جالطة ، ينضاف الى كل هذا ملعب للجولف ومحطات استشفاء بمياه البحر والمعالجة بالمياه المعدنية (في حمام بورقيبة) ، في الصيف طبرقة تنشط بالعديد من الفعاليات تحت شعار موسيقى الجاز والموسيقى العالمية ، الشمال الغربي لتونس ، مع غابته الكثيفة والطبيعة البكر",
        en: "“Don't tan foolishly” was, in the 1970s, the memorable slogan of the Tabarka music festival, its point being that Tabarka offers more than a beach holiday. Its relief and nature make it resemble Corsica more than any other part of Tunisia. Tabarka is a destination for discovery with a long diving tradition and astonishing dive sites, and it offers many boat trips to the nearby bays or to the island of La Galite. Add to that a golf course and centres for thalassotherapy and mineral-water treatment (at Hammam Bourguiba). In summer Tabarka comes alive with many events under the banner of jazz and world music, in a north-west Tunisia of dense forest and untouched nature.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — جراد البحر أو السمك", en: "Try these dishes — lobster or fish", noNumber: true },
      {
        type: "P",
        ar: "أثناء اقامتك في طبرقة ، لا تفوت الفرصة لتذوق جراد البحر على رصيف الميناء بأحد المطاعم الذي سيمتعك بالأسماك والمأكولات البحرية ، أثناء اقامتك فنادق المنتجع السياحي تقدم لك المأكولات العالمية الجيدة ، ويمكنك أيضا الاكل في فندق عتيق وسط المدينة ، مع الاستمتاع برؤية الشاطىء",
        en: "During your stay in Tabarka do not miss the chance to taste lobster on the harbour quay at one of the restaurants that will delight you with fish and seafood. The resort hotels serve good international food, and you can also eat in an old hotel in the town centre while enjoying the view of the shore.",
      },
      { type: "H3", ar: "حاول السكن في — على الشاطىء أو في الغابة", en: "Where to stay — on the beach or in the forest", noNumber: true },
      {
        type: "P",
        ar: "طبرقة محطة سياحية تعد نحو عشرة منتجعات وفنادق على طول الشاطئ ، يمكنك اختيار اقامة فندقية على حافة الغابة أو فندق صغير ساحر في وسط المدينة ، حول عين دراهم تتوفر العديد من الفنادق المريحة ، فنادق للصيادين ذات ديكور ريفي ، واقامة ذات جودة عالية في قلب الطبيعة ، أو فندق كبير للعلاج بالمياه المعدنية وسط الغابة",
        en: "Tabarka is a resort with about ten hotels and holiday complexes along the beach. You can choose a hotel at the edge of the forest or a charming small hotel in the town centre. Around Aïn Draham there are many comfortable hotels, hunters' lodges with rustic decor, high-quality accommodation in the heart of nature, or a large mineral-water treatment hotel in the middle of the forest.",
      },
      { type: "H3", ar: "الخلاصة — المجوهرات والمرجان", en: "In short — jewellery and coral", noNumber: true },
      {
        type: "P",
        ar: "هل تعلم أن مجوهرات المرجان الأحمر التي تقترح عليك بطبرقة مقترنة بتاريخ المدينة ؟ فمنذ العصور القديمة ، تجتذب هذه المواد الثمينة الطامعين في الذهب الأحمر للبحر المتوسط كما يسمى المرجان أحيانا ، شبيه لنبتة حاملة لأزهار صغيرة بيضاء ، المرجان في الواقع هيكل عظمي جيري متحجر تسكنه حيوانات ضئيلة من عائلة شقائق البحر وقنديل البحر ، المرجان الأحمر بات نادرا اليوم ، بعد أن كان في السابق وفيرا خاصة على الساحل الشمالي لتونس ، في القرن الــ 16 تمكن تجار جنويون من احتكاره ، ولحماية أعمالهم بنوا قرية محصنة في طبرقة لا يزال قائما منها الحصن الجنوي شعار المدينة ، اليوم لا بد من الغوص الى أعماق سحيقة للعثور عليه",
        en: "Did you know that the red coral jewellery offered to you in Tabarka is bound up with the city's history? Since antiquity this precious material has attracted those coveting the “red gold of the Mediterranean”, as coral is sometimes called. It resembles a plant bearing small white flowers, but coral is in fact a calcified skeleton inhabited by tiny animals of the sea-anemone and jellyfish family. Red coral has become rare today, though it was once abundant, especially on Tunisia's northern coast. In the sixteenth century Genoese merchants secured a monopoly over it and, to protect their business, built a fortified village at Tabarka, of which the Genoese fort — the city's emblem — still stands. Today one must dive to great depths to find it.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
    ],
  },
  {
    slug: "monastir",
    title_ar: "المنستير وما حولها",
    title_en: "Monastir and around",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES.monastir,
    blocks: [
      { type: "H3", ar: "المنستير .. متعة السياحة والترفيه", en: "Monastir — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "شواطئ رملية شقراء وبحر ياقوتي ، وحصن الرباط من العصور الوسطى ومارينا مجهزة لاستقبال اليخوت ومنتجع بنزل فاخرة وملعبي جولف ، تقدم المنستير كل مكونات الوجهة السياحية المثالية ، الاقامة فيها تمكن أيضا من زيارة منطقة ثرية بالاكتشافات والمعالم من سوسة الى القيروان ، ومن اللجم الى المهدية ، سوف تسافر عبر التاريخ ، توقف في القرى المجاورة للتعرف على الحياة البدوية أو في موانىء الصيد الموجودة على طول الساحل",
        en: "Blond sandy beaches and a sapphire sea, the medieval ribat fortress, a marina equipped for yachts, a resort with luxury hotels and two golf courses: Monastir has every ingredient of the ideal destination. Staying here also lets you visit a region rich in discoveries and monuments, from Sousse to Kairouan and from El Jem to Mahdia — a journey through history. Stop in the neighbouring villages to learn about Bedouin life, or in the fishing harbours along the coast.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES.monastir, cap_ar: "المنستير ورباطها", cap_en: "Monastir and its ribat" },
      { type: "H3", ar: "تعنى لتشاهد — الرباط وميناء الصيد", en: "Not to be missed — the ribat and the fishing port", noNumber: true },
      {
        type: "P",
        ar: "نزهة جميلة على الواجهة البحرية : المارينا وساحة الرباط والمقبرة التي تغمرها مآذن ضريح بورقيبة ، تسلق الدرجات التسعين الضيقة لبرج المراقبة للرباط لتنمتع بمشهد بانورامي يقطع الانفاس ، مطل على المدينة الخلابة والشواطئ المجاورة ، استمتع بالأبراج والأسوار والمسجد المجاور ، ثم ادخل الى الأنهج المبلطة في المدينة العتيقة وابحث في الأسواق حيث الأكشاك مليئة بالتوابل المعطرة ومنتوجات الصناعات التقليدية الجميلة : الجلود والحقائب والبطانيات والسلال المنسوجة ، ثم تجول على رصيف ميناء الصيد المليء بالحركية ، المدينة محاطة بقرى زراعية وبساتين ، في حين يتبع الطريق الساحلي سلسلة من الخلجان والشواطئ الساحرة",
        en: "A lovely walk along the seafront: the marina, the ribat square and the cemetery overlooked by the minarets of the Bourguiba mausoleum. Climb the ninety narrow steps of the ribat's watchtower for a breathtaking panorama over the beautiful town and the nearby beaches, and enjoy the towers, the walls and the adjoining mosque. Then enter the paved lanes of the medina and browse the souks, where the stalls are full of fragrant spices and fine handicrafts: leather, bags, blankets and woven baskets. Afterwards walk the quay of the busy fishing port. The town is surrounded by farming villages and orchards, while the coast road follows a string of charming bays and beaches.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — مدينة الرباط وبورقيبة", en: "To know more — the city of the ribat and Bourguiba", noNumber: true },
      {
        type: "P",
        ar: "اسم المنستير ذو جذور بيزنطية ويعني الدير ، الطابع الروحي للمنطقة تواصل في القرون التالية ، حيث استقر بها جمع من الزهاد المسلمين ، وهذا ما جعل المدينة تتطور حول رباطها ، الحصن الصغير الذي شيد في القرن 8 لحماية هذا الجمع من الزهاد ، تم توسيعه في وقت لاحق من قبل سلاطين تونس ثم من قبل العثمانيين ، النواة الأولى تحولت الآن الى متحف يضم القطع النادرة ، مثل الاسطرلاب الرائع المصنع في قرطبة في القرن العاشر ، معلم شهير آخر بالمنستير هو الضريح ذو القباب الذهبية للحبيب بورقيبة أب الاستقلال ، من مواليد المنستير ، بورقيبة اثر بشكل عميق وكبير في تونس الحديثة من خلال سياسة التعليم والتطور الاجتماعي وتحرير المرأة ، يمكن زيارة ضريحه المتحف وكذلك قصر إقامته الصيفية السابق المشيد عام 1960",
        en: "The name Monastir has Byzantine roots and means monastery. The spiritual character of the area continued in later centuries, when a community of Muslim ascetics settled here, and so the town grew around its ribat, the small fortress built in the eighth century to protect that community and later enlarged by the sultans of Tunis and then the Ottomans. The original core is now a museum holding rare pieces, such as the superb astrolabe made in Cordoba in the tenth century. Another famous monument in Monastir is the golden-domed mausoleum of Habib Bourguiba, father of independence, who was born here and who profoundly shaped modern Tunisia through his policies on education, social progress and the emancipation of women. You can visit his mausoleum-museum as well as his former summer residence, built in 1960.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — الاسترخاء والتراث", en: "Things to do — relaxation and heritage", noNumber: true },
      {
        type: "P",
        ar: "بشواطئها ونخيلها وبحرها اللازوردي ، تبقى المنستير احدى أكبر وجهات العطل في تونس ، الاسترخاء أو الرياضات البحرية ، السباحة أو المعالجة بمياه البحر ، الترفيه وافر والأنشطة عديدة ، وهي أيضا وجهة للجولف : ميدان على شاطئ البحر وآخر على سفح تلة ، المارينا ومركز للغوص بانتظار عشاق البحر ، وهواة التاريخ سيزورون بشغف متحف جميل للفن الاسلامي في الرباط ، وحول المنستير سيجدون الموقع الأثري في لمطة ومدن التاريخ الكبرى سوسة والمهدية والقيروان ، دون أن ننسى واحد من أكثر المعالم روعة في تونس ، المسرح الروماني الكبير بالجم ، أما المولعون بالفنون التقليدية ، فستبهرهم ستر الزفاف المطرزة بالذهب والحرير المعروضة في متحف الفنون والتقاليد الشعبية",
        en: "With its beaches, palm trees and azure sea, Monastir remains one of the biggest holiday destinations in Tunisia. Relaxation or water sports, swimming or thalassotherapy — leisure is plentiful and activities are many. It is also a golf destination, with one course by the sea and another on a hillside, while the marina and a diving centre await sea lovers. History enthusiasts will eagerly visit the fine museum of Islamic art in the ribat, and around Monastir they will find the archaeological site of Lamta and the great historic cities of Sousse, Mahdia and Kairouan, not forgetting one of Tunisia's most magnificent monuments, the great Roman amphitheatre at El Jem. Lovers of traditional arts will be dazzled by the wedding veils embroidered with gold and silk displayed in the Museum of Popular Arts and Traditions.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الأسماك وغلال البحر", en: "Try these dishes — fish and seafood", noNumber: true },
      {
        type: "P",
        ar: "تقدم المنستير وفرة من الفواكه والخضروات الطازجة التي تحضر بطرق متنوعة وقد تكون محظوظا عند تذوق تخصص محلي ، مثل الكسكسي مع الأسماك الصغيرة «الشركاو» المطبوخ على البخار ، في المنستير ، الأسماك وغلال البحر تتصدر أولى المراتب في الطبخ سواء كانت مشوية ، مقلية أو مطهاة في الفرن ، الجهة معروفة بانتاجها للخضروات والبقوليات في فصل الربيع تذوق “مرقة الخضرة” بلحم الضأن مع الفاصوليا الخضراء والخضر الموسمية ، في المدينة العتيقة ، قرب الشاطئ وعلى أرصفة المارينا ، ستجد مجموعة متنوعة من المطاعم التي تلبي كل الأذواق",
        en: "Monastir offers an abundance of fresh fruit and vegetables prepared in many ways, and you may be lucky enough to taste a local speciality such as couscous with small steamed fish. Here fish and seafood take first place in the kitchen, whether grilled, fried or baked. The region is known for its vegetables and pulses, and in spring you should taste marqa khodra, lamb with green beans and seasonal vegetables. In the medina, near the beach and on the marina quays, you will find a variety of restaurants to suit every taste.",
      },
      { type: "H3", ar: "حاول السكن في — فندق على الشاطىء أو شقة في المارينا", en: "Where to stay — a beach hotel or a marina apartment", noNumber: true },
      {
        type: "P",
        ar: "الفنادق عديدة على طول الشاطئ ذي الرمال الناعمة لمنطقة صقانس ، وتتراوح الصيغ المقترحة من الفنادق الكلاسيكية الى الاقامة الشاملة «أول أنكلوزيف» ، رياضة أنشطة وأكلات محلية ودولية ، هذه المرافق مثالية لقضاء العطلات العائلية في الصيف أو لمدة أطول في نعومة الشتاء المشمس ، بمارينا المنستير ، على مقربة من وسط المدينة ، يمكنك أن تختار شقة فندقية وهي صيغة تجمع بين استقلالية الاقامة والتمتع بالخدمات الفندقية",
        en: "Hotels are numerous along the soft sandy beach of the Skanès area, with options ranging from classic hotels to all-inclusive stays, offering sport, activities and both local and international food. These places are ideal for family holidays in summer or for a longer stay in the gentle sunny winter. At the Monastir marina, close to the town centre, you can choose an apart-hotel, a formula combining independence with hotel services.",
      },
      { type: "H3", ar: "الخلاصة — الرباط", en: "In short — the ribat", noNumber: true },
      {
        type: "P",
        ar: "واحد من تلك القلاع الفريدة على السواحل المغاربية ، رباط المنستير هو متاهة من الساحات والأبراج والجدران المسننة ، في الأصل كان قلعة صغيرة مثل ما كان منتشرا منها على طول الساحل التونسي ، رباط سوسة حافظ على شكله الأصلي ، هذه المباني ، كانت تستعمل كخلوات تزهد للصوفيين ، كان حراسها يتعبدون ، ويستقبلون الطلاب والعلماء ، وتوكل اليهم مهمة الاشعار اذا تعرضت المدينة للغزو ، فكانوا يرسلون من خلال برج عال شارات ضوئية للتحذير من خطر قادم من البحر ، تحظى المنستير بمكانة دينية كبيرة وهي “واحد من أبواب الجنة” ، كما يقول المثل ، كما كان للرباط طوال الزمن أبعاد مهمة حتى أضحى المعلم الذي نزوره اليوم بكل بهجة",
        en: "One of those fortresses unique to the Maghreb coast, the ribat of Monastir is a maze of courtyards, towers and crenellated walls. It began as a small fort of the kind once common along the Tunisian coast — the ribat of Sousse has kept its original form. These buildings served as retreats for Sufi ascetics: their guardians worshipped, received students and scholars, and were charged with raising the alarm if the town were attacked, sending light signals from a high tower to warn of danger coming from the sea. Monastir enjoys great religious standing and is “one of the gates of paradise”, as the saying goes, and over time the ribat grew in importance until it became the monument we visit with such delight today.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "في دكاكين الأسواق ، شراء سجادة القيروان الجميلة ، أوقفة من الحلفة المنسوجة وكذلك مجوهرات من الفضة أو صينية من النحاس الأصفر ينقش عليها اسمك ، تزود بالمنتجات التونسية مثل زيت الزيتون ، الهريسة (بهارالفلفل الحار) والحلويات ، الموعد بالمكنين قرية الفخار الواقعة على بعد 20 كلم : جرار الفخار الكبيرة هي تخصصها ، ولكن تصنع فيها أيضا أدوات المائدة ومنتوجات من الخزف ذي الألوان التونسية",
        en: "In the souk shops buy a beautiful Kairouan carpet, a woven esparto basket, silver jewellery or a brass tray engraved with your name. Stock up on Tunisian products such as olive oil, harissa (hot pepper paste) and sweets. And make a date with Moknine, the pottery village 20 km away: large earthenware jars are its speciality, but it also makes tableware and ceramics in Tunisian colours.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "للمنستير مطار دولي «الحبيب بورقيبة» وهو على بعد دقائق من الفنادق ، خط قطارات جهوي يتيح الوصول بسهولة من والى سوسة والمهدية مرورا من قرى المكنين (ورش الفخار) ولمطة (موقع أثري) ، يمكن أيضا التنقل باستئجار سيارة أجرة وفي المدينة بالتاكسي",
        en: "Monastir has the Habib Bourguiba international airport, minutes from the hotels. A regional railway line makes it easy to travel to and from Sousse and Mahdia by way of the villages of Moknine (pottery workshops) and Lamta (an archaeological site). You can also get around by hiring a car, and by taxi within the city.",
      },
    ],
  },
];
