import type { Guide } from "./france-guides";

const U = (name: string) => `https://i0.wp.com/100region.com/wp-content/uploads/${name}?ssl=1`;

export const TUNIS_REGION_HEROES_2 = {
  kairouan: U("2022/10/img_4954.jpg"),
  kef: U("2022/10/img_4956.jpg"),
  nabeul: U("2022/10/img_4958.jpg"),
  "bizerte-dougga": U("2022/10/img_4960.jpg"),
  "gabes-matmata": U("2022/10/image-16.jpg"),
  tataouine: U("2022/10/img_4964-1.jpg"),
  mahdia: U("2022/10/img_4966.jpg"),
};

/**
 * Seven more Tunisian region pages linked from "الأماكن السياحية".
 * Arabic text is kept exactly as published on the source pages.
 */
export const tunisiaRegionGuides2: Guide[] = [
  {
    slug: "kairouan",
    title_ar: "القيروان وما حولها",
    title_en: "Kairouan and around",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2.kairouan,
    blocks: [
      { type: "H3", ar: "القيروان .. المدينة الاسلامية الأولى في منطقة المغرب العربي", en: "Kairouan — the first Islamic city of the Maghreb", noNumber: true },
      {
        type: "P",
        ar: "بعيدا عن الساحل ووسط المشاهد الطبيعية للسهول ، تمتدد مدينة القيروان الرائعة ، ذات الجذور الضاربة في القدم ، فهي أول عاصمة اسلامية بالمغرب العربي ، مدينتها العتيقة تعد نفائس فريدة : المسجد الكبير الجليل ، والفسقية الأغلبية ، وضريح سيدي الصاحب المزركش بالخزف ، معالم جعلتها تصنف في قائمة التراث الانساني لليونسكو ، ولا تنسى طبعا ورشات النسيج حيث تصمم الزربية القيروانية الشهيرة",
        en: "Far from the coast, amid the natural scenery of the plains, spreads the splendid city of Kairouan, whose roots reach deep into antiquity: it was the first Islamic capital of the Maghreb. Its medina holds unique treasures — the majestic Great Mosque, the Aghlabid basins and the ceramic-clad mausoleum of Sidi Sahbi — monuments that earned it a place on the UNESCO World Heritage list. And do not forget the weaving workshops where the famous Kairouan carpet is designed.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2.kairouan, cap_ar: "القيروان", cap_en: "Kairouan" },
      {
        type: "P",
        ar: "القيروان .. هي مدينة تونسية تبعد بحوالي 160 كيلومتر عن العاصمة تونس ، يعود تاريخها الى عام 50 هـ / 670 م عندما قام بانشائها عقبة بن نافع ، وكان هدفه من هذا البناء أن يستقر بها المسلمون ، اذ كان يخشى ان رجع المسلمون عن أهل أفريقيا أن يعودو الى دينهم ، وقد اختير موقعها على أساس حاجات استراتيجية واضحة ، وقد اختار لها موضعا بعيدا عن البصر في وسط البلاد ولئلا تمر عليها مراكب الروم فتهلكها",
        en: "Kairouan lies about 160 km from the capital Tunis. Its history goes back to 50 AH / 670 AD, when Uqba ibn Nafi founded it so that Muslims would settle there, fearing that if the Muslims withdrew the people of Africa would return to their former religion. Its site was chosen on clear strategic grounds — inland, out of sight, and beyond the reach of Byzantine ships that might destroy it.",
      },
      {
        type: "P",
        ar: "وصف قيروان .. تعتبر القيروان من أقدم وأهم المدن الاسلامية ، بل هي المدينة الاسلامية الأولى في منطقة المغرب ، ويعتبر انشاء مدينة القيروان بداية لتاريخ الحضارة العربية الاسلامية في المغرب العربي ، فلقد كانت مدينة القيروان تلعب دورين هامين في آن واحد هما : الجهاد والدعوة ، فبينما كانت الجيوش تخرج منها للغزو والتوسعات ، كان الفقهاء يخرجون منها لينتشروا بين البلاد يعلمون اللغة العربية وينشرون الاسلام ، لقد بقيت القيروان حوالي أربعة قرون عاصمة الاسلام الأولى لافريقيا والأندلس ومركزا حربيا للجيوش الاسلامية ونقطة ارتكاز رئيسية لاشاعة اللغة العربية ، وكلمة القيروان كلمة فارسية دخلت الى العربية ، وتعني مكان السلاح ومحط الجيش أو استراحة القافلة وموضع اجتماع الناس في الحرب",
        en: "Kairouan is among the oldest and most important Islamic cities — indeed the first in the Maghreb — and its founding marks the beginning of Arab-Islamic civilisation in the region. The city played two roles at once: military campaigning and religious teaching. While armies set out from it, jurists left it to spread through the country teaching Arabic and Islam. For some four centuries Kairouan remained the foremost Islamic capital for Africa and Andalusia, a military centre for the Islamic armies and a principal base for spreading the Arabic language. The word Kairouan comes from Persian and means a place of arms, an army camp, a caravan rest or a gathering place in war.",
      },
      { type: "H3", ar: "تعنى لتشاهد — الأسواق والقباب", en: "Not to be missed — souks and domes", noNumber: true },
      {
        type: "P",
        ar: "بعد الدخول الى المدينة العتيقة من بابها الهائل ، بين رفوف صغار الباعة في السوق ، تنقل بين الانهج ذات الواجهات البيضاء والأبواب الزرقاء الشاحبة ، هنا ستشعر بأجواء من خارج الزمن ، اصعد الى أعلى الحصن المسنن المحيط بالمدينة العتيقة لاكتشاف مدينة مغمورة بالقباب البيضاء ، في الأسواق تتنافس المحلات في عرض أفضل الزرابي ، مفخرة أهل القيروان ، خلال الجولة ، توقف عند مبنى «البروطة» الحاضن لبئر قديمة تحظى بتبجيل المتساكنين ، وبداخله جمل يدور باستمرار لتحريك نظام قديم من العجلات والدلاء لسحب الماء ، غادر البلدة العتيقة نحو الفسقية الأغلبية من القرن التاسع ، هذه الخزانات المائية الكبيرة هي جزء من مجمع مائي ضخم ، يعتبر استثنائيا في زمانه",
        en: "Entering the medina through its huge gate, past the stalls of the small traders, wander lanes of white facades and pale blue doors: here you feel out of time. Climb the crenellated wall around the old town to discover a city submerged in white domes. In the souks the shops compete to display the finest carpets, the pride of Kairouan. On the way, stop at the Bir Barouta building, which shelters an old well venerated by the inhabitants, where a camel turns endlessly to drive an ancient system of wheels and buckets that draws the water. Leave the old town for the ninth-century Aghlabid basins: these great reservoirs are part of an immense water complex, exceptional in its day.",
      },
      { type: "H3", ar: "مسجد القيروان", en: "The Great Mosque of Kairouan", noNumber: true },
      {
        type: "P",
        ar: "يعد مسجد القيروان الذي بناه عقبة بن نافع عند انشاء المدينة من أهم معالمها عبر التاريخ ، ولقد بدأ المسجد صغير المساحة ، بسيط البناء ، ولكن لم يمض على بنائه عشرون عاما حتى هدمه حسان بن نعمان الغساني وأقام مكانه مسجدا جديدا أكبر من الأول ، وفي عهد الخليفة هشام بن عبد الملك أمر بزيادة مساحته ، وأضاف اليه حديقة كبيرة في شماله ، وجعل له صهريجا للمياه ، وشيد مآذنه ، وفي عام 155 هـ أعيد بناؤه على يد يزيد بن حاتم ، وقد سارت التوسعات في العصور المختلفة حتى أصبح يشغل اليوم مساحة مستطيلة تتراوح أضلاعها ما بين (70 و122) مترا ، ويعتبر جامع القيروان من أقدم مساجد المغرب الاسلامي والمصدر الأول الذي اقتبست منه العمارة المغربية والأندلسية عناصرها الزخرفية والمعمارية ، كما كان هذا المسجد ميدانا للحلقات الدينية والعلمية واللغوية التي ضمت نخبة من أكبر علماء ذلك العصر",
        en: "The mosque built by Uqba ibn Nafi when the city was founded is its most important monument through history. It began small and simple, but within twenty years Hassan ibn Numan al-Ghassani pulled it down and built a larger one in its place. Under the caliph Hisham ibn Abd al-Malik it was enlarged, a great garden was added to its north, a cistern was dug and minarets raised; in 155 AH it was rebuilt by Yazid ibn Hatim. Successive enlargements have left it today a rectangle whose sides measure between 70 and 122 metres. The Great Mosque of Kairouan is among the oldest mosques of the Islamic Maghreb and the first source from which Moroccan and Andalusian architecture drew its decorative and structural elements; it was also the setting for religious, scholarly and linguistic circles gathering the greatest scholars of the age.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — عاصمة سابقة ومدينة مقدسة", en: "To know more — a former capital and a holy city", noNumber: true },
      {
        type: "P",
        ar: "تأسست القيروان سنة 670 ميلادي ، أثناء الفتح الاسلامي لافريقيا (الاسم القديم لتونس) ، وأصبحت واحدة من أهم المدن في البحر الأبيض المتوسط في عهد الأمراء الأغالبة في القرن التاسع ، حيث تم بناء المسجد الكبير في شكله الحالي ، وكأحد المعالم المعمارية الاسلامية الأولى بالمغرب العربي ، كان أنموذجا لكثير من المساجد الى حدود الأندلس ، متحف رقادة يضم قطعا رائعة من هذا العصر الذهبي الذي دام قرنين ، في المراحل التالية ، حافظت القيروان على مكانتها الدينية ، بالاضافة الى مسجد عقبة الكبير تضم ضريحا لصحابي سابق للنبي (ص) ، سيدي الصحبي : هذا المعلم الرائع بني في القرن السابع عشر ، ويتألف من عدة ساحات وغرف مزينة بلوحات وخزف ملون ، ويعرف هذا المسجد باسم “مسجد الحلاق”",
        en: "Kairouan was founded in 670 AD during the Islamic conquest of Ifriqiya (the old name of Tunisia) and became one of the most important cities of the Mediterranean under the Aghlabid emirs in the ninth century, when the Great Mosque took its present form. As one of the first Islamic architectural monuments of the Maghreb it was a model for many mosques as far as Andalusia. The Raqqada museum holds superb pieces from that two-century golden age. Later Kairouan kept its religious standing: beside the great mosque of Uqba it holds the mausoleum of a companion of the Prophet, Sidi Sahbi — a wonderful monument built in the seventeenth century with several courtyards and rooms decorated with painted panels and coloured ceramics, known as the “Mosque of the Barber”.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — المساجد والمتاحف", en: "Things to do — mosques and museums", noNumber: true },
      {
        type: "P",
        ar: "المسجد الكبير ، جامع عقبة يستحق الزيارة ، ويجوز لغير المسلمين الدخول الى فنائه ورؤية قاعة صلاته البديعة : غابة مهيبة من الأقواس والأعمدة القديمة ، يتسنى أيضا الصعود الى المئذنة ، المستوحاة من منارة الاسكندرية ، ستصاب بالدهشة لعظمة الهندسة المعمارية للقرن التاسع وبساطتها ، على نقيض تام مع المعلم الكبير الآخر في القيروان : زاوية سيدي الصحبي أو (مسجد الحلاق) ، حيث الأفنية كبيرة ومغلفة بخزف ملون ، خارج المدينة ، لا تتخلف عن زيارة متحف رقادة الكبير : حيث سترى الخزف ذي الانعكاسات المعدنية ، عملات ذهبية وصفحات من القرآن الكريم يعود تاريخها الى القرون الأولى من تاريخ المدينة ، وهناك أنشطة أخرى ممكنة في المنطقة : التنزه ، واكتشاف الكهوف والصيد في المواقع الجبلية ، أو مراقبة تجمعات الطيور في البحيرات المالحة",
        en: "The Great Mosque of Uqba deserves a visit: non-Muslims may enter its courtyard and see the magnificent prayer hall, an awe-inspiring forest of ancient arches and columns. You can also climb the minaret, inspired by the lighthouse of Alexandria, and be struck by the grandeur and simplicity of ninth-century architecture — a complete contrast with Kairouan's other great monument, the zawiya of Sidi Sahbi (the Mosque of the Barber), whose large courtyards are clad in coloured ceramics. Outside the city, do not miss the great Raqqada museum with its lustreware ceramics, gold coins and pages of the Quran dating from the city's first centuries. Other activities in the region include walking, exploring caves, hunting in the mountain areas and watching flocks of birds on the salt lakes.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الضأن والمقروض", en: "Food to try — lamb and makroudh", noNumber: true },
      {
        type: "P",
        ar: "في المدينة العتيقة ، أقصد مطعما صغيرا لتذوق مطبخ بسيط وغير مكلف ، بعض المطاعم الأكثر شهرة توفر لك ، وفقا لرغبتك ، من الكسكسي السخي الى المأكولات العالمية ، يمكن طلب الأطباق التونسية مثل مصلي علوش ولحم الضأن المشوي ، لا تنسى ما تشتهر به القيروان ، «المقروض» ، وهو حلوى صغيرة من الاختصاصات القديمة للمطبخ البربري ، مكون من السميد وزيت الزيتون والعسل بالاضافة الى تمر واحات الجنوب التونسي",
        en: "In the medina, head for a small restaurant and enjoy simple, inexpensive cooking; the better-known places offer everything from generous couscous to international dishes. Order Tunisian specialities such as mosli allouch and grilled lamb, and never forget what Kairouan is famous for: makroudh, a small pastry from the old Berber repertoire made of semolina, olive oil and honey, filled with dates from the southern oases.",
      },
      { type: "H3", ar: "حاول السكن في — الفندق الكلاسيكي", en: "Where to stay — the classic hotel", noNumber: true },
      {
        type: "P",
        ar: "هناك بعض الفنادق في القيروان ومنها فندق فخم مع مسبح في مبنى عتيق تمت اعادة تهيئته بقصبة المدينة (القلعة) ، أما اذا كنت تفضل دارا للضيافة ففي المدينة العتيقة غايتك",
        en: "Kairouan has a handful of hotels, including a luxurious one with a pool set in a restored historic building inside the kasbah. If you prefer a guest house, the medina is where to look.",
      },
      { type: "H3", ar: "الخلاصة — سجاد القيروان", en: "In short — the carpets of Kairouan", noNumber: true },
      {
        type: "P",
        ar: "يحكى أنه في القرن التاسع عشر ، كانت ابنة الوالي العثماني أولى من نسجت السجاد الصوفي في القيروان لاهدائه لأحد مساجد المدينة ، ثم تدعم التقليد ليجعل القيروان عاصمة السجاد أو الزربية في تونس ، في الواقع منذ عصور متأخرة ، كانت تونس تصنع جميع أنواع السجاد : من الكليم والمرقوم وهما نوع من السجاد يزين بخطوط متوازية أو بزخارف بربرية ، الى القطيف ، وهو سجاد سميك بألوان زاهية ، لكن السجاد القيرواني هو الأقرب الى الشرقي ، ويعرف بزينته حيث تتوسطه أشكال الزهور محاطة بنطاقات موازية ، السجاد الكلاسيكي يغلب عليه اللون الأحمر القرمزي ، أو الألوان الطبيعية من الأبيض والبني لصوف الأغنام ، لا تفوت متابعة عمل الحرفيات في ورشة السجاد ، فسوف تفتن بمهارتهن وبالرسومات الرائعة التي تتشكل أمامك",
        en: "It is said that in the nineteenth century the daughter of the Ottoman governor was the first to weave a woollen carpet in Kairouan, as a gift to one of the city's mosques; the tradition then took hold and made Kairouan the carpet capital of Tunisia. In fact Tunisia has long made carpets of every kind, from kilim and mergoum decorated with parallel lines or Berber motifs to the thick, brightly coloured qtif. The Kairouan carpet is the closest to the oriental style, recognisable by its decoration: flower shapes at the centre framed by parallel bands. Classic pieces are dominated by crimson red or by the natural whites and browns of sheep's wool. Do not miss watching the women at work in a carpet workshop: their skill and the wonderful patterns forming before you are captivating.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "لا يمكن تجاهل التخصص الكبير للقيروان ، فالسجاد في كل مكان ، من سجاد سميك كلاسيكي الى التصاميم الأكثر تنوعا ومن جميع الأحجام ، بأنماط هندسية أو شخصيات منمنمة صغيرة كالغزلان ، وهي أخف وزنا وأرخص ثمنا ، من سجاد صغير للكراسي الى كبيرا يغطي غرفة بأكملها ، أيضا بامكانك أن تعود من زيارتك بأنواع أخرى من الصناعات اليدوية مثل النحاس والفخار والجلود والمرطبات الصغيرة بالتمر “المقروض”",
        en: "Kairouan's great speciality is impossible to ignore: carpets are everywhere, from thick classic pieces to the most varied designs in every size, with geometric patterns or small stylised figures such as gazelles, which are lighter and cheaper — from a small chair rug to one covering a whole room. You can also come home with other crafts: copper, pottery, leather and the little date pastries, makroudh.",
      },
      {
        type: "P",
        ar: "سوق الربع : حيث يباع سجاد القيروان الشهير (الزربية) ، سوق البلاغجية : حيث تصنع وتباع الاحذية والسروج ، سوق الجرابة : حيث تنسج وتباع الاقمشة والاغطية ولوازم صناعة السجاد ، سوق العطارين : حيث تباع العطرات والبخور ولوازم الأعراس ، سوق النحاسين : حيث تصنع وتباع آواني النحاس",
        en: "Souk er-Rebaa, where the famous Kairouan carpet is sold; Souk el-Balaghjia, where shoes and saddles are made and sold; Souk el-Jaraba, where fabrics, blankets and carpet-making supplies are woven and sold; Souk el-Attarine, for perfumes, incense and wedding supplies; and Souk en-Nahhasine, where copperware is made and sold.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "تربط القيروان بقية البلاد خطوط الحافلات وسيارات الأجرة ذات مسار ثابت ، المطارين الدوليين بالمنستير والنفيضة الحمامات ، كلاهما على بعد 65 كلم من القيروان",
        en: "Bus lines and fixed-route shared taxis connect Kairouan with the rest of the country. The international airports of Monastir and Enfidha-Hammamet are both 65 km away.",
      },
    ],
  },
  {
    slug: "kef",
    title_ar: "الكاف",
    title_en: "Le Kef",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2.kef,
    blocks: [
      { type: "H3", ar: "الكاف .. متعة السياحة والترفية", en: "Le Kef — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "أترك شواطئ الساحل لاكتشاف وجه غير مألوف لتونس : جبال الأطلس والهضاب المرتفعة ، في هذه المشاهد المتناقضة من الغرب التونسي تنتصب الكاف ، البلدة الصغيرة المحافظة على سحرها ومعالمها ، جمال المنطقة الطبيعي ليس عامل الجذب الوحيد لها ، فهي غنية بالمعالم التاريخية مثل موقع سبيطلة الروماني الرائع",
        en: "Leave the coastal beaches behind to discover an unfamiliar face of Tunisia: the Atlas mountains and the high plateaux. In these contrasting landscapes of western Tunisia stands Le Kef, a small town that has kept its charm and its monuments. The natural beauty of the region is not its only attraction — it is rich in historic sites such as the splendid Roman city of Sbeitla.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2.kef, cap_ar: "الكاف", cap_en: "Le Kef" },
      { type: "H3", ar: "تعنى لتشاهد — الجبال والمدينة العتيقة", en: "Not to be missed — mountains and the old town", noNumber: true },
      {
        type: "P",
        ar: "تضاريس جبال الأطلس تقدم مشاهد طبيعية مثيرة من فوق القلعة العثمانية بالكاف مثلا أو من الجزء العلوي لمائدة يوغرطة التي تمكن من اطلالة جميلة على الجبال ، تجول في البلدة العتيقة لمدينة الكاف ، فمن ميزاتها تشابك المعالم التاريخية والآثار من جميع العصور وجميع الأديان ، ستعترضك خزانات المياه والحمامات الرومانية ، وكنيسة قديمة للقديس بطرس ، ومعبد يهودي من القرن الثامن عشر يحظى بمكانة كبيرة أيضا من لدى المسلمين في المدينة ، كما ستلاحظ تجاور ثلاثة مقابر : اسلامية ومسيحية ويهودية ، ويبقى ضريح سيدي بومخلوف ، ذو القباب البيضاء المضلعة والمئذنة المزينة بالخزف الأخضر ، المعلم الرمز للجهة",
        en: "The Atlas relief offers thrilling views, for instance from the Ottoman kasbah of Le Kef or from the top of Jugurtha's Table, which opens a beautiful panorama over the mountains. Wander the old town of Le Kef, remarkable for the way monuments and remains from every era and every religion are interwoven: Roman cisterns and baths, an old church of Saint Peter, an eighteenth-century synagogue held in high regard even by the town's Muslims, and three cemeteries side by side — Muslim, Christian and Jewish. The mausoleum of Sidi Bou Makhlouf, with its ribbed white domes and minaret decorated in green ceramic, remains the emblem of the region.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — المواقع الأثرية", en: "To know more — the archaeological sites", noNumber: true },
      {
        type: "P",
        ar: "الثراء التاريخي للمناطق الغربية جعل منها اليوم مقصد المولعين بالمعالم الأثرية ، مكثر أحد أكبر المواقع في تونس ، يضم آثارا مذهلة مثل قوس تراجان ، والحمامات الكبرى ورواق أنيق من الأعمدة «للشولا دي جوفانس» ، موقع سبيطلة لافت للنظر بمبنى الكابيتول المؤلف من ثلاثة معابد مخصصة للآلهة الحارسة لروما ، وحيدرة حيث بقايا أحد أكبر الحصون البيزنطية بالمغرب العربي ، ولعديد الكنائس المسيحية ، المناطق الغربية تضم فعلا عددا كبيرا من الآثار المسيحية القديمة ، في سبيطلة ، الكنيسة الكبرى فيتاليس بها وعاء جميل للتنصير مغطى بالفسيفساء ، معالم تشير الى أن تونس كانت مركزا رئيسيا لمسيحية الغرب",
        en: "The historic wealth of the western regions makes them a destination for lovers of antiquity today. Maktar, one of Tunisia's largest sites, holds astonishing remains such as the Arch of Trajan, the great baths and an elegant colonnaded portico of the Schola Juvenum. Sbeitla stands out for its capitol of three temples dedicated to the guardian deities of Rome, and Haïdra for the remains of one of the largest Byzantine fortresses in the Maghreb and for its many churches. The west indeed holds a great number of early Christian remains: at Sbeitla the great basilica of Vitalis has a beautiful baptismal font covered in mosaic — monuments showing that Tunisia was a major centre of western Christianity.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — الثقافة والتجوال لمسافات طويلة", en: "Things to do — culture and long walks", noNumber: true },
      {
        type: "P",
        ar: "انطلق في جولة عبر الممرات الجبلية أوفي الغابات أو على ضفاف بحيرة ، أعبر القرى ، وتأمل في عمل الحرفيين الذين ينسجون الحلفاء والحرفيات اللاتي ينسجن الزرابي والبطانيات ، استكشف الكهوف ، المغليثية ، وآثار المدن الرومانية أو الينابيع الساخنة ، في المحمية الطبيعية “السدين” قرب الكاف ، يمكن مراقبة الحيوانات الرائعة مثل النيص والنسور الملكية ، وفي مدينة الكاف العتيقة ، قم بزيارة لمتحف الفنون والتقاليد الشعبية ، داخل مبنى ديني جميل من القرن الثامن عشر ، واطلع على تقاليد الفروسية ، وحلي الشمال الغربي ، أو طريقة العيش في خيمة بدوية ، أيضا زيارة القصبة (القلعة) العثمانية المكونة من حصنين أحدهما كان مخصصا للمقيمين من الانكشاريين الأتراك والآخر للقوات المساعدة",
        en: "Set out along mountain paths, through forests or beside a lake; cross the villages and watch the craftsmen weaving esparto grass and the women weaving carpets and blankets. Explore caves, megalithic remains, Roman cities and hot springs. In the Es-Sedine nature reserve near Le Kef you can watch remarkable wildlife such as porcupines and imperial eagles. In the old town of Le Kef visit the museum of popular arts and traditions, housed in a beautiful eighteenth-century religious building, to learn about equestrian traditions, the jewellery of the north-west and life in a Bedouin tent. Visit too the Ottoman kasbah, made of two forts, one for the Turkish janissary garrison and the other for auxiliary troops.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الشعير والكسكس بالتمر", en: "Food to try — barley and couscous with dates", noNumber: true },
      {
        type: "P",
        ar: "اكتشف فن الطبخ الأصيل للمناطق الغربية والمنتجات المحلية السخية ، في الكاف ، يعدون كسكسي “البرزقان ” ذا الطعم الحلو والمالح في آن واحد ، مسقى بالحليب ومصحوب بلحم الضأن المعطر باكليل الجبل والفواكه الجافة والتمور ، هو أكلة المناسبات المميزة ، طبق جهوي آخر مميز هو الملثوث المصنوع من الشعير المسحوق ويعد كما الكسكسي ، تذوق خبز الشعير الريفي ، أو وصفات الأجداد مثل الزرير وهي تحلية من مسحوق السمسم والبندق",
        en: "Discover the authentic cooking of the western regions and its generous local produce. In Le Kef they prepare berzguen couscous, at once sweet and salty, moistened with milk and served with lamb scented with rosemary, dried fruit and dates — the dish of special occasions. Another distinctive regional dish is malthouth, made from crushed barley and prepared like couscous. Taste the rustic barley bread, or ancestral recipes such as zrir, a sweet of ground sesame and hazelnut.",
      },
      { type: "H3", ar: "حاول السكن في — في الريف أو في المدينة العتيقة", en: "Where to stay — countryside or medina", noNumber: true },
      {
        type: "P",
        ar: "الكاف هي المدينة الرئيسية في المنطقة ، توفر خيارات من الفنادق الصغيرة ودور ضيافة في المدينة العتيقة ، كما يمكن الاقامة على مقربة من المدينة ، بضيعة تم تحويلها الى اقامة ريفية مريحة للسياح",
        en: "Le Kef is the main town of the region and offers small hotels and guest houses in the old town. You can also stay just outside the town on a farm converted into a comfortable country lodging for visitors.",
      },
      { type: "H3", ar: "الخلاصة — مائدة يوغرطة", en: "In short — Jugurtha's Table", noNumber: true },
      {
        type: "P",
        ar: "يوغرطة هو الأمير البربري الشهير وبطل مقاومة الغزو الروماني ، كان جده ماسينيسا قد اوجد مملكة كبيرة الى جانب قرطاج ، في القرن الثاني قبل الميلاد حيث تعددت المعابد والمعالم الأثرية في المغرب الوسيط وشمال غرب تونس ، مائدة يوغرطة هي جبل مسطح على مساحة 80 هكتار وبارتفاع 1271 متر ، قلعة طبيعية كانت ملاذا آمنا على مر التاريخ ، احتمى بها الأمير البربري مع جيشه في حربه ضد الرومان ، محاطة تماما بالمنحدرات الحادة ، وتشرف على حقول القمح الشاسعة والجبال على مدى النظر ، لتسلقها عليك بدرج قديم منحوت في الصخر يوصلك الى القمة ، لاكتشاف مشهد يقطع الأنفاس ، بالموقع العديد من الآثار : الدولمينات ، القوس البيزنطي ، ومسجد صغير ، خزان محفور في الصخر وكهوف ومقابر من عصور ما قبل التاريخ",
        en: "Jugurtha was the famous Berber prince and hero of the resistance to Roman conquest; his grandfather Massinissa had created a great kingdom alongside Carthage in the second century BC, when temples and monuments multiplied in the central Maghreb and north-western Tunisia. Jugurtha's Table is a flat-topped mountain of 80 hectares rising to 1,271 metres — a natural fortress that has been a refuge throughout history, where the Berber prince sheltered with his army in his war against Rome. Ringed by sheer cliffs, it overlooks vast wheat fields and mountains as far as the eye can see. You climb it by an old stairway carved into the rock that brings you to the summit and a breathtaking view. The site holds many remains: dolmens, a Byzantine arch, a small mosque, a rock-cut cistern, caves and prehistoric tombs.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "في المرتفعات الغربية ، يصنع الفخار المقولب باليد دون عجلة الخزاف : المباخر والصحون والأواني ، في الكاف البطانيات المنسوجة الرائعة الألوان وغيرها من الأنسجة اليدوية ذات الأصباغ الطبيعية",
        en: "In the western highlands pottery is shaped by hand without a wheel: incense burners, dishes and jars. In Le Kef, look for the superbly coloured woven blankets and other hand-woven textiles dyed with natural pigments.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "من تونس ، يمكن الوصول الى الكاف بالقطار أو بسيارة تأجير (170 كلم منها 70 كلم طريق سيارة) ، سبيطلة تبعد 120 كلم عن الكاف و30 كلم عن القصرين",
        en: "From Tunis you can reach Le Kef by train or by hire car (170 km, of which 70 km is motorway). Sbeitla is 120 km from Le Kef and 30 km from Kasserine.",
      },
    ],
  },
  {
    slug: "nabeul",
    title_ar: "نابل الوطن القبلي",
    title_en: "Nabeul and Cap Bon",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2.nabeul,
    blocks: [
      { type: "H3", ar: "نابل .. متعة السياحة والترفية", en: "Nabeul — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "رعن متجه نحو صقلية ، هي تلك شبه جزيرة الوطن القبلي ، وكجارتها الايطالية تزخر المنطقة ببساتين البرتقال والليمون والشواطئ الرملية الجميلة وموانىء الصيد ، نابل عاصمة الوطن القبلي ، هي مدينة الخزف والحصير وتقطير زيوت الزهور ، موانىء الصيد بقليبية وبني خيار ، والمياه المعدنية بقربص وتربية الصقور بالهوارية هي بعض الملامح والمعالم السياحية لهذه المنطقة",
        en: "A cape pointing towards Sicily — that is the Cap Bon peninsula, and like its Italian neighbour the region abounds in orange and lemon groves, beautiful sandy beaches and fishing harbours. Nabeul, capital of Cap Bon, is the city of ceramics, matting and the distilling of flower oils. The fishing ports of Kelibia and Beni Khiar, the mineral waters of Korbous and the falconry of El Haouaria are some of the features and attractions of this region.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2.nabeul, cap_ar: "نابل", cap_en: "Nabeul" },
      { type: "H3", ar: "تعنى لتشاهد — أسواق وبانوراما", en: "Not to be missed — souks and panoramas", noNumber: true },
      {
        type: "P",
        ar: "في نابل ، يحلو التجول في سوق المدينة المحاط بأروقة ومحلات تجارية لمختلف الصناعات التقليدية ، اذا رغبت في مشاهدة حرفيين أثناء عملهم ، فعليك بزيارة قرية الحرفيين في مدخل المدينة حيث الحدادون ، ونساجو الحصير والخزافون وناقشو النحاس ، ولا تفوتك زيارة السوق المغطاة أين يمكنك اقتناء التوابل والهريسة النابلية الشهيرة وكذالك الفواكه والخضروات والأسماك : الوطن القبلي هو منطقة فلاحية هامة ، وبالتنقل الى قليبية ، توقف عند قلعتها الزيرية – المشيدة في القرن الثاني عشر ، وهي الأكبر في تونس ، اشرب الشاي بالنعناع في مقهى محلي مجاور يطل على البحر مع نزهة على طول ميناء الصيد ، في الهوارية ، أقصى نقطة بالوطن القبلي ، املأ أنفاسك بالهواء النقي والبري ، وزر الكهوف الغريبة التي حفرها الرومان لاستخراج حجارة البناء ، ثم لا تفوتك زيارة قربص ، مدينة المياه المعدنية السخنة المحاطة بشواطئ وبخلجان غاية في الجمال",
        en: "In Nabeul it is a pleasure to wander the town's souk, ringed by arcades and shops of every traditional craft. To watch craftsmen at work, visit the artisans' village at the entrance to the town, where the blacksmiths, mat weavers, potters and copper engravers work. Do not miss the covered market, where you can buy spices and the famous Nabeul harissa as well as fruit, vegetables and fish — Cap Bon is an important farming region. Travelling on to Kelibia, stop at its Zirid fortress, built in the twelfth century and the largest in Tunisia, drink mint tea in a nearby local café overlooking the sea and stroll along the fishing port. At El Haouaria, the peninsula's farthest point, fill your lungs with pure sea air and visit the strange caves the Romans cut to quarry building stone. Then do not miss Korbous, the town of hot mineral springs surrounded by beaches and exceptionally beautiful coves.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — أرض زراعية وضيافة", en: "To know more — farmland and hospitality", noNumber: true },
      {
        type: "P",
        ar: "في القرن الرابع قبل الميلاد كانت منطقة الوطن القبلي تشتهر «بالكروم والزيتون والكثير من أشجار الفاكهة» كما كتبه ديودوروس الصقلي ، حيث كانت تحت السيطرة القرطاجية ، والموقع الأثري الاستثنائي في كركوان ، المدرج على قائمة اليونسكو للتراث العالمي ، لا يزال يشهد على تلك الحضارة بمنازله القرطاجية",
        en: "In the fourth century BC Cap Bon was famous for “its vines, its olives and its many fruit trees”, as Diodorus of Sicily wrote, when the region was under Carthaginian control. The exceptional site of Kerkouane, on the UNESCO World Heritage list, still bears witness to that civilisation with its Carthaginian houses.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — الشاطىء والطبيعة", en: "Things to do — beach and nature", noNumber: true },
      {
        type: "P",
        ar: "الشواطئ الرملية والفنادق الجميلة من نابل الى قربة تعد بعطلة احلام ، استلقى تحت مضلة شمسية ، أو استمتع بالرياضات والأنشطة الترفيهية ، تنزه على متن سفينة القراصنة أو العب الجولف في الحمامات ، أو مارس الغوص بعدها تمتع بعلاجات في مركز صحي بمياه البحر ، على طول الساحل ، المشاهد البحرية رائعة تنشرح لها صدور المصطافين وهواة السياحة البحرية (ميناء قليبية يستقبل سفن التنزه) ، الوطن القبلي ، بتلاله وبساتينه وغاباته ، وجهة للمتنزهين وكذالك لصيادين الخنزير البري الذي يتواجد بكثرة بالمنطقة ، الوطن القبلي هو ايضا جهة محبذة لمشاهدة الطيور التي تتجمع في البحيرات الساحلية بالقرب من مضيق صقلية ، أما اذا كنت من محبي التاريخ ، اكتشف الموقع الأثري الاستثنائي في كركوان ، المدرج على قائمة اليونسكو للتراث العالمي (منازل قرطاجية) ، واستمتع أيضا بقلعة قليبية من القرن 12 ، والفسيفساء في متحف نابل والمحاجر الرومانية بالهوارية",
        en: "The sandy beaches and handsome hotels from Nabeul to Korba promise a dream holiday. Lie under a parasol or enjoy sports and leisure activities, sail on a pirate ship, play golf in Hammamet, dive, and afterwards take treatments at a seawater spa. All along the coast the seascapes are magnificent, delighting holidaymakers and yachting enthusiasts (Kelibia marina welcomes pleasure boats). With its hills, orchards and forests, Cap Bon is a destination for walkers and for hunters of the wild boar that abounds here. It is also a favoured area for watching the birds that gather in the coastal lagoons near the Strait of Sicily. History lovers should discover the exceptional site of Kerkouane on the UNESCO list (Carthaginian houses), and enjoy the twelfth-century fortress of Kelibia, the mosaics in the Nabeul museum and the Roman quarries at El Haouaria.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الفلفل وغلال البحر", en: "Food to try — peppers and seafood", noNumber: true },
      {
        type: "P",
        ar: "الوطن القبلي مشهور بالتفنن في الطبخ وبمنتجاته الفلاحية الوافرة ، المطاعم عديدة في وسط نابل وبالقرب من الفنادق الكبيرة ، لا تنس تذوق الهريسة ، المعدة من الفلفل الأحمر المطحون والمتبل ، وكذالك السلطة المشوية المعدة بالطماطم والفلفل الأخضر واللتي تؤكل طازجة مع القليل من زيت الزيتون ، موانئ الصيد عديدة على ساحل الجهة مما يوفر الأسماك اللذيذة التي ستقدم لك مع الكسكسي أو مشوية رفقة تستيرة وهو خليط من الخضروات المقلية والبيض المسحوق ، وتمتع بأكلات الحبار والاخطبوط والجمبري كفاتح للشهية أو كطبق رئيسي ، هذه المنطقة معروفة أيضا بفاكهتها ، وخاصة منها العنب والبرتقال",
        en: "Cap Bon is famous for refined cooking and abundant farm produce. Restaurants are numerous in central Nabeul and near the large hotels. Do not miss harissa, made of ground and seasoned red peppers, nor the grilled salad of tomatoes and green peppers eaten fresh with a little olive oil. The many fishing ports along the coast supply delicious fish, served with couscous or grilled with tastira, a mix of fried vegetables and crumbled egg. Enjoy squid, octopus and prawns as a starter or a main course. The region is also known for its fruit, especially grapes and oranges.",
      },
      { type: "H3", ar: "حاول السكن في — النزل والاقامات الريفية ودور الضيافة", en: "Where to stay — hotels, country lodgings and guest houses", noNumber: true },
      {
        type: "P",
        ar: "على طول شواطئها الرملية الجميلة ، نابل ، قليبية وقربة توفر مجموعة متنوعة من الفنادق البسيطة أو الفاخرة ، تضع على ذمتك على مدار السنة مجموعة واسعة من الأنشطة ، بعيدا عن المراكز السياحية ، اختر فندقا صغيرا بالمدينة أو دارا للضيافة ، يعد الوطن القبلي الكثير من المنازل في المدينة العتيقة والاقامات على شاطئ البحر واقامات ريفية وفي الضيعات",
        en: "Along their beautiful sandy beaches, Nabeul, Kelibia and Korba offer a range of hotels from simple to luxurious, with a wide choice of activities all year round. Away from the tourist centres, choose a small town hotel or a guest house: Cap Bon has many houses in the old town, seafront lodgings, country stays and farm accommodation.",
      },
      { type: "H3", ar: "الخلاصة — خزف نابل", en: "In short — the ceramics of Nabeul", noNumber: true },
      {
        type: "P",
        ar: "الجولان في نابل يطلعك على احدى أهم خاصيات الجهة : مربعات الخزف تزين واجهات البيوت والمحلات التجارية والمباني العامة ، في حين تتوسط المدينة جرة عملاقة مزينة بزخارف تقليدية ، فيعسر تجاهل الخزف لكل زائر لنابل ، ذالك أن سكان المدينة خزافون أبا عن جد بفضل مقاطع الطين الجيد القريبة ، فهم يصنعون الجرار والأطباق والمزهريات والأواني الفخارية المبرنقة بالأصفر والأخضر ، منذ أوائل القرن العشرين تخصص خزافو نابل في مربعات الخزف متعدد الألوان ، المستوحى من القصور والمعالم القديمة في تونس ، ويقدمون اليوم مجموعة واسعة من المنتجات : من اللوحات الخزفية ذات الطراز العثماني الى أواني الأكل ، مرورا بالمزهريات المتعددة الأشكال والألوان ، يمكن اقتناء مربعات الخزف التقليدي من المصانع الواقعة في نابل أو عند الخزافين ، طريقة اقتصادية ومبتكرة لتزويق منزلك بعد العودة من العطلة",
        en: "Walking through Nabeul reveals one of the region's defining features: ceramic tiles adorn the fronts of houses, shops and public buildings, while a giant jar decorated with traditional motifs stands at the centre of town. Ceramics are impossible to ignore here, for the townspeople have been potters for generations thanks to the good clay quarries nearby, making jars, dishes, vases and earthenware glazed in yellow and green. Since the early twentieth century the potters of Nabeul have specialised in polychrome tiles inspired by Tunisia's palaces and old monuments, and today they offer a wide range: Ottoman-style ceramic panels, tableware and vases of every shape and colour. You can buy traditional tiles from the factories in Nabeul or directly from the potters — an inexpensive and inventive way to decorate your home once the holiday is over.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "عديد من محلات الحرفيين والهدايا التذكارية بجوار الفنادق وفي الأسواق بنابل ، مراكز التسوق والمحلات التجارية في وسط المدينة توفر منتجات متنوعة وغالبا بأسعار معقولة : ملابس من الجلد وأحذية ومجوهرات وغيرها",
        en: "There are many craft and souvenir shops near the hotels and in the souks of Nabeul, and the shopping centres and stores downtown offer varied goods at often reasonable prices: leather clothes, shoes, jewellery and more.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "لا تبعد نابل عن مطار تونس قرطاج سوى 65 كلم و55 كلم عن مطار النفيضة الحمامات ، وتتوفر خدمة الحافلات السريعة والمريحة من محطة الحافلات في تونس (الطريق السيارة وطريق سريعة) ، للتنقل في جميع أنحاء المدينة والمدن المجاورة ، استعمل سيارة الأجرة",
        en: "Nabeul is only 65 km from Tunis-Carthage airport and 55 km from Enfidha-Hammamet airport. Fast, comfortable coaches run from the Tunis bus station (motorway and expressway). To move around the town and the neighbouring towns, use a taxi.",
      },
    ],
  },
  {
    slug: "bizerte-dougga",
    title_ar: "من بنزرت إلى دقة",
    title_en: "From Bizerte to Dougga",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2["bizerte-dougga"],
    blocks: [
      { type: "H3", ar: "بنزرت ودقة .. متعة السفر والترفية", en: "Bizerte and Dougga — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "عشاق الطبيعة والأصالة ، شواطئ وسهول شمال تونس ستغمركم ، الخلجان البرية والغابات وحقول الكروم والقمح الشاسعة ، على حافة البحر ، بنزرت ، حارسة المتوسط ، مدينة تاريخية ذات سحر ، وزيادة عن ذلك فهذه المنطقة المخضرة تأوي موقعين مرسمين بقائمة التراث العالمي لليونسكو : الاول أثري وهو مدينة دقة الرومانية ، والثاني طبيعي وهو بحيرة اشكل والمنتزه المحيط به ، التي تجلب الطيور المهاجرة بالآلاف",
        en: "Lovers of nature and authenticity: the beaches and plains of northern Tunisia will win you over — wild bays, forests and vast fields of vines and wheat. On the sea's edge, Bizerte, guardian of the Mediterranean, is a historic city full of charm. And this green region shelters two UNESCO World Heritage sites: the archaeological one, the Roman city of Dougga, and the natural one, Lake Ichkeul and its surrounding park, which draws migratory birds in their thousands.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2["bizerte-dougga"], cap_ar: "بنزرت", cap_en: "Bizerte" },
      { type: "H3", ar: "تعنى لتشاهد — المدينة العتيقة والمشاهد الطبيعية", en: "Not to be missed — the old town and the landscapes", noNumber: true },
      {
        type: "P",
        ar: "القلب النابض لمدينة بنزرت هو المرفأ القديم وهو مساحة مائية محفوفة بمنازل بيض وحصون عتيقة وأين تنساب في صمت مراكب الصيادين ، موقع مليء بالسحر والتاريخ ، على الأرصفة ، تمتع بالاجواء الحميمية في احدى المقاهى ، ثم ادخل القصبة المطوقة بالأسوار ، تجول في الانهج الضيقة للمدينة ، زر الأسواق ، واستمتع بمشاهد النافورة التركية من القرن الــ 17 ، اصعد الى القلعة الاسبانية المشرفة على المدينة ، للاستمتاع بالمشهد المطل على الميناء ، تجول في وسط المدينة التي حافظت على الطابع المعماري لفترة الحماية بشوارعها الفسيحة ، ولا تنسى زيارة المارينا الجديدة أو الميناء التجاري الذي يعج بالنشاط ، وحول المدينة ستفاجئك دون شك المشاهد الخضراء للتلال وحقول القمح والبساتين فالمنطقة من أخصب المناطق في تونس",
        en: "The beating heart of Bizerte is the old harbour, a stretch of water framed by white houses and ancient forts where the fishing boats slip in silently — a place full of charm and history. On the quays, enjoy the intimate atmosphere of a café, then enter the walled kasbah, wander the narrow lanes, visit the souks and admire the seventeenth-century Turkish fountain. Climb to the Spanish fort above the town for the view over the port, and stroll through the town centre, which has kept the architectural character of the protectorate era with its broad avenues. Do not miss the new marina or the bustling commercial port. Around the town the green hills, wheat fields and orchards will surely surprise you: this is one of the most fertile regions of Tunisia.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — قلعات وطيور", en: "To know more — forts and birds", noNumber: true },
      {
        type: "P",
        ar: "آثار أوتيك ، المؤسسة الفينيقية الأولى في تونس ، ودقة ، المدينة الصغيرة المحلية التي باتت رومانية ، تشهد على الماضي العريق والمجيد لهذه المنطقة الخصبة ، في دقة يمكن مشاهدة مدينة قديمة استثنائية ، حيث تبرز عدة معالم أثرية على غرار الضريح النوميدي والمسرح ومبنى الكابيتول ، وتحتل بنزرت موقعا استراتيجيا في البحر المتوسط ، حدد طابعها العسكري الى اليوم ، ميناءها القديم الداخلي وبحيرتها المتصلان بالبحر كانا يستقطبان مغامرات القراصنة حتى القرن الــ 17 ، غار الملح ، في جنوب بنزرت ، آوت الأسطول البحري العثماني ، وبالامكان مشاهدة بقايا الترسانة وثلاثة حصون ، المنطقة تم تثمينها وزراعتها في نفس الوقت من طرف الأندلسيين المسلمين الذين طردوا من اسبانيا والذين استقروا أيضا في تستور ، بلدة صغيرة حيث ترى المساجد الفريدة من نوعها والمستوحاة من الكنائس الاسبانية ، بحيرة اشكل هي واحدة من أهم المستنقعات في منطقة البحر المتوسط ، وهي نظام بيئي فريد ، يتميز بتداول مواسم الماء بين المالح والعذب ويستقطب الآلاف من الطيور المائية ، غابة الجبل تطل على البحيرة التي تضم حيوانات ونباتات لافتة للنظر",
        en: "The remains of Utica, the first Phoenician foundation in Tunisia, and Dougga, a small local town that became Roman, testify to the long and glorious past of this fertile region. At Dougga you can see an exceptional ancient city where several monuments stand out — the Numidian mausoleum, the theatre and the capitol. Bizerte holds a strategic position in the Mediterranean, which still marks its military character; its old inner harbour and its lake, both linked to the sea, attracted the adventures of pirates until the seventeenth century. Ghar el Melh, south of Bizerte, sheltered the Ottoman fleet, and the remains of the arsenal and three forts can still be seen. The region was developed and cultivated by the Andalusian Muslims expelled from Spain, who also settled in Testour, a small town with mosques unique in their kind, inspired by Spanish churches. Lake Ichkeul is one of the most important wetlands of the Mediterranean, a unique ecosystem alternating between salt and fresh water by season and attracting thousands of waterbirds; the wooded mountain overlooking the lake holds remarkable flora and fauna.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — الاستحمام أو الآثار", en: "Things to do — swimming or antiquities", noNumber: true },
      {
        type: "P",
        ar: "رغم أنها أقل شعبية من الحمامات ومن سوسة ، تمتلك بنزرت عددا من الفنادق الجميلة للتمتع بالشاطئ والشمس في الصيف وهي مقصد محبذ لسياحة الترفيه البحري والغوص ، وتختص المنطقة ببعض الشواطىء البكر الخلابة مثل كاب سيرات ، رافراف وغار الملح ، في حديقة اشكل الطبيعية المدرجة بقائمة اليونسكو للتراث العالمي ، يمكن التنزه على ضفاف البحيرة واستكشاف الجبل من خلال المسالك المهيئة ، هواة الآثار سيكتشفون التراث الأندلسي بتستور ، والحصون العثمانية الجميلة بغار الملح ، وقلعة بنزرت ، والموقع الأثري في أوتيكا وخصوصا موقع دقة الروماني الأكثر اثارة",
        en: "Though less popular than Hammamet or Sousse, Bizerte has a number of pleasant hotels for beach and sun in summer and is a favoured destination for water sports and diving. The region has some stunning unspoilt beaches such as Cap Serrat, Raf Raf and Ghar el Melh. In the Ichkeul national park, on the UNESCO list, you can walk along the lake shore and explore the mountain on the marked trails. Lovers of antiquity will discover the Andalusian heritage of Testour, the handsome Ottoman forts of Ghar el Melh, the fort of Bizerte, the site of Utica and above all the most thrilling of them, Roman Dougga.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الأسماك وغلال البحر", en: "Food to try — fish and seafood", noNumber: true },
      {
        type: "P",
        ar: "ملتفة حول ميناءها القديم ، بنزرت هي مركز مهم لتذوق المنتوجات البحرية كمفتحات أو كطبق رئيسي ، تمتع بالسمك المشوي والحبار والجمبري ، وسيقدم لك السمك المشوي مصحوبا بالخضر المقلية أو مطهو في الفرن مع الكمون والزعفران ، لخصوبتها توفر المناطق الشمالية منتوجا زراعيا متنوعا حيث تتجاور زراعة الحبوب وتربية الماشية وزراعة الزيتون ، طبق الطبيخ مخصص للمناسبات والأفراح ، وهو حساء القمح مع لحم الضأن ، بنكهة التوابل وقشور البرتقال ، أيضا يمكن تلذذ الكسكسي بالهامور ، الكسكسي هو طبق بربري قديم يصنع من السميد المطبوخ بالبخار ، ويقدم عادة مع لحم الضأن والخضراوات ، وكذلك في المدن الساحلية ، مع الأسماك ، لتناول الطعام ، هناك العديد من المطاعم الجيدة قرب الفنادق على الشاطئ ، وبالميناء القديم وأيضا بالمارينا",
        en: "Wrapped around its old port, Bizerte is an important place to taste seafood as a starter or a main course: grilled fish, squid and prawns. Grilled fish comes with fried vegetables, or baked with cumin and saffron. Thanks to their fertility the northern regions offer varied farm produce, with cereals, livestock and olives side by side. Tabikha, a wheat soup with lamb flavoured with spices and orange peel, is reserved for celebrations and weddings, and you can also enjoy couscous with grouper — couscous being an ancient Berber dish of steamed semolina, usually served with lamb and vegetables and, in the coastal towns, with fish. To eat, there are many good restaurants near the beach hotels, at the old port and at the marina.",
      },
      { type: "H3", ar: "حاول السكن في — فندق أو أقامة ريفية أو مسكن على الشاطىء", en: "Where to stay — hotel, country lodging or seafront house", noNumber: true },
      {
        type: "P",
        ar: "رغم أن المنطقة السياحية ببنزرت تعد كلاسيكية لقضاء عطلة على شاطئ البحر ، الا أنه بالامكان أيضا العثور على اقامات أكثر اصالة بالجهة ، من ذلك غرفة في اقامة ريفية بقلب الريف البنزرتي ، واقامات على طول شاطئ بكر ، أو فيلا فخمة تطل على البحر ، أو منزل قديم بالمدينة العتيقة",
        en: "Although the tourist area of Bizerte is a classic choice for a seaside holiday, you can also find more authentic places to stay: a room in a country house in the heart of the Bizerte countryside, lodgings along an unspoilt beach, a luxurious villa overlooking the sea, or an old house in the medina.",
      },
      { type: "H3", ar: "الخلاصة — خزافات سجنان", en: "In short — the women potters of Sejnane", noNumber: true },
      {
        type: "P",
        ar: "تشتهر سجنان ، القرية الصغيرة بخزفها التقليدي الذي يعود الى فجر التاريخ ، هنا النساء يتعلمن في سن مبكرة عجن الطين وقولبته ، براعتهن مدهشة : دون استخدام عجلة الخزاف ، ينتجن الأطباق ، والأواني والمزهريات المقولبة باتقان حسب أهوائهن ، يقمن بصنع اللعب الصغيرة والدمى المزخرفة التي تزينها الأشكال البربرية التقليدية بطلاء مستخرج من النباتات الحمراء ، تعرجات ، مثلثات ، وخطوط مستقيمة ، الشخوص المميزة تتفاعل بين أناملهن ، على الصحون والأطباق ، ترسمن رموزا قديمة كالنخيل ، والسلاحف والأسماك ، أدواتهن بسيطة : بعض الألواح ، قطعة من البلاستيك ، وقواقع لتلميع الأسطح ، قرية سجنان تحوطها التلال والبحيرات ، وهي معروفة أيضا باللقالق التي تعشش في السقالات الصناعية القديمة ، عديدة هي الأسباب التي تجعلك تلبي دعوة فنانات الخزف بسجنان",
        en: "Sejnane, a small village, is famous for a traditional pottery whose origins reach back to the dawn of history. Here women learn from an early age to knead and shape clay, and their mastery is astonishing: without a potter's wheel they produce dishes, jars and vases modelled to perfection as their fancy dictates. They make small toys and decorated dolls adorned with traditional Berber motifs painted with a dye drawn from red plants — zigzags, triangles and straight lines, with distinctive figures taking shape between their fingers. On plates and dishes they draw ancient symbols such as palms, turtles and fish. Their tools are simple: a few boards, a piece of plastic and shells to polish the surfaces. Ringed by hills and lakes, the village is also known for the storks that nest on old industrial scaffolding. There are many reasons to accept the invitation of Sejnane's ceramic artists.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "في بنزرت ، كما هو الحال في جميع مدن تونس ، تعرض دكاكين الصناعات التقليدية الهدايا التذكارية ومجموعة واسعة من الحلي ، والستر المطرزة والحقائب والخفاف والزرابي والسلال المنسوجة ، فلا تتردد في اقتناء الخزف البربري الأصلي لسجنان ذي الرسومات والأسلوب المنمق بألوانه الحمراء والسوداء",
        en: "In Bizerte, as in every Tunisian town, the craft shops display souvenirs and a wide range of jewellery, embroidered jackets, bags, slippers, carpets and woven baskets. Do not hesitate to buy the authentic Berber pottery of Sejnane with its stylised drawings in red and black.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "مطار تونس قرطاج يبعد 70 كلم عن بنزرت التي تربطها بالعاصمة طريق سيارة وخط للسكك الحديدية ، طريق آخر عبر سيارة تربط غرب تونس في اتجاه تستور ودقة",
        en: "Tunis-Carthage airport is 70 km from Bizerte, which is linked to the capital by motorway and by railway. Another road runs west towards Testour and Dougga.",
      },
    ],
  },
  {
    slug: "gabes-matmata",
    title_ar: "من قابس إلى مطماطة",
    title_en: "From Gabes to Matmata",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2["gabes-matmata"],
    blocks: [
      { type: "H3", ar: "قابس ومطماطة .. متعة السفر والترفية", en: "Gabes and Matmata — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "قابس هي الواحة الساحلية الوحيدة في البحر الأبيض المتوسط ، تحيط بها شواطئ من الرمل الدقيق ، واحتها الشاسعة بهجة حقيقية ، أما البلدة العتيقة فتتميز بأجوائها الأصيلة ، قابس هي بوابة الصحراء : بداية لرحلة بين قمم وهضاب قاحلة ، بين خيام البدو والقرى البربرية ، حيث يتسنى اكتشاف التقاليد الحية لطرق العيش التقليدي ، مثل قرية الكهوف المدهشة بجبل مطماطة",
        en: "Gabes is the only coastal oasis on the Mediterranean, ringed by beaches of fine sand, and its vast palm grove is a real delight, while the old town keeps an authentic atmosphere. Gabes is the gateway to the desert: the start of a journey among arid peaks and plateaux, Bedouin tents and Berber villages, where you can discover the living traditions of a traditional way of life, such as the astonishing cave village of the Matmata hills.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2["gabes-matmata"], cap_ar: "مطماطة", cap_en: "Matmata" },
      { type: "H3", ar: "تعنى لتشاهد — واحة وقرى قديمة", en: "Not to be missed — the oasis and the old villages", noNumber: true },
      {
        type: "P",
        ar: "تنزه في واحة قابس التي تعد مئات الآلاف من أشجار النخيل التي تنموا في ظلها العديد من أشجار الفاكهة ، وفي أوائل الصيف ، استمتع بأشجار الرمان المزهرة التي تثمر في الخريف فاكهة مليئة بعصير حلو ، تعرف على الأنهج والممرات المغطاة المتعرجة لحي المنزل القديم ، بالسوق الملونة في جارة اشتري التوابل ومسحوق الحناء ، النبتة الطبية للأصباغ والتلوين المقطوفة في الواحة ، لقابس شواطئ جميلة ، حيث يمرح عدد وفير من طيور النعام ومالك الحزين ، في المناطق الداخلية القرى البربرية القديمة المشدودة الى التلال تتماهى مع المشاهد الطبيعية الصخرية ، هذه الجهة تخفي أحد أكثر المواقع طرافة في تونس مطماطة حيث تخترق الأرض عديد الفوهات المحفورة في الصخر اللين ، هي في الواقع ساحات الكهوف السكان يعيشون في غرف تحت الأرض لاتقاء شدة الحر",
        en: "Walk in the oasis of Gabes with its hundreds of thousands of palms, in whose shade many fruit trees grow; in early summer enjoy the flowering pomegranates that in autumn bear fruit full of sweet juice. Explore the winding lanes and covered passages of the old Menzel quarter, and in the colourful souk of Jara buy spices and henna powder, the dye plant harvested in the oasis. Gabes has beautiful beaches where flamingos and herons abound. Inland, the old Berber villages clinging to the hills blend into the rocky landscape, and this region hides one of the most curious sites in Tunisia: Matmata, where the ground is pierced by craters dug into the soft rock — in fact the courtyards of the cave dwellings, where people live in underground rooms to escape the fierce heat.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — واحة ومنازل الكهوف", en: "To know more — the oasis and the cave houses", noNumber: true },
      {
        type: "P",
        ar: "استثنائية بموقعها على شاطئ البحر ، عرفت واحة قابس منذ القدم ، هناك في أفريقيا وفي وسط الصحراء مدينة تدعى تكابي ، أراضيها المروية جيدا ذات خصوبة عالية ، كتب بليني القديم ، في القرن الحادي عشر كانت قابس مدينة كبيرة محاطة بسور من الحجارة الكبيرة ، كما وصفها الرحالة البكري ، في قابس العديد من المواقع الأثرية من القرن السابع عشر : المساجد ، ضريح مقدس سيدي أبولبابة ومدرسة باتت الآن متحفا للفنون والتقاليد الشعبية ، في المناطق الصحراوية المجاورة يتواجد الى اليوم تقليد قديم في تونس : منازل الكهوف وهي بيوت مطماطة المخططة وفقا للعمارة التونسية القديمة : فناء مركزي تحيط به غرف ، لكن جميعها تحت الأرض ، قرى أخرى ، مثل طمزرت ، تلتف حول قمة الجبل ، بيوتها الحجرية تنصهر مع لون الصخر ومسجدها الصغير يشرف على متاهة من الأنهج",
        en: "Exceptional for its seaside setting, the oasis of Gabes has been known since antiquity: “there is in Africa, in the middle of the desert, a town called Tacape whose well-watered land is highly fertile”, wrote Pliny the Elder. In the eleventh century Gabes was a large town surrounded by a wall of great stones, as the traveller al-Bakri described it. Gabes holds many monuments from the seventeenth century: mosques, the shrine of Sidi Boulbaba and a madrasa that is now a museum of popular arts and traditions. In the neighbouring desert areas an ancient Tunisian tradition survives to this day: the cave houses of Matmata, laid out according to old Tunisian architecture with a central courtyard ringed by rooms — but all of it underground. Other villages, such as Tamezret, wrap around a hilltop, their stone houses merging with the colour of the rock and their small mosque overlooking a maze of lanes.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — مراقبة الطيور وثقافة أمازيغية", en: "Things to do — birdwatching and Amazigh culture", noNumber: true },
      {
        type: "P",
        ar: "في قابس تبدأ المغامرة للسياحة الصحراوية ، متحفها للفنون والتقاليد الشعبية يعرفك بالعديد من الأزياء والحياكة والسجاد واختصاصات المصوغ بالمنطقة ، وفي القرى المحيطة ، سوف تتعرف على المنازل الكهفية وأساليب زراعة الأراضي القاحلة ، سترى النساء يشكلن الستائر الجميلة على نول بدائية ، كما يمكنك الاطلاع على الثقافة البربرية : المتحف الصغير بطمزرت يشرح الرموز والتقاليد وتاريخ الملكة البربرية الكاهنة ، تلال المنطقة تفسح المجال لجولات راجلة ، وعشاق شريط حرب النجوم يعلمون أن بعض من مشاهده صورت في مطماطة ، المغرمون بتاريخ الحرب العالمية الثانية يجدون في متحف مارث شواهد عن خط التحصينات الذي أقامه الفرنسيون ثم احتله المارشال رومل ، ولهواة مراقبة الطيور خليج قابس يعد أحد أكبر المواقع في البحر الأبيض المتوسط التي تؤمها الطيور المهاجرة في فصل الشتاء",
        en: "Desert travel begins at Gabes. Its museum of popular arts and traditions introduces the region's costumes, weaving, carpets and jewellery specialities, and in the surrounding villages you will discover the cave houses and the techniques of farming arid land, and see women shaping beautiful hangings on rudimentary looms. You can also explore Berber culture: the small museum of Tamezret explains the symbols, the traditions and the history of the Berber queen al-Kahina. The region's hills invite walking, and Star Wars fans know that some scenes were filmed at Matmata. Enthusiasts of the Second World War will find in the Mareth museum evidence of the fortified line built by the French and later occupied by Marshal Rommel. For birdwatchers, the Gulf of Gabes is one of the largest Mediterranean sites visited by migratory birds in winter.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الأسماك والرمان", en: "Food to try — fish and pomegranates", noNumber: true },
      {
        type: "P",
        ar: "مدينة ساحلية كبيرة ، توفر قابس الأسماك وغلال البحر المطبوخة بطرق عدة : السمك المشوي ، الحبار المحشو وكلب البحر مع حساء الخضر أو الأسماك الصغيرة “الوزف” مع سلطة الفلفل ، خروف الرعاة يحتل أيضا مكانة هامة في المطبخ الجنوبي ، تذوقه مع الكسكسي أو محمرا ، اذا بقيت في قابس الى الخريف ، فاغتنم الفرصة للاستمتاع برمان الواحة ، لندرة المطاعم السياحية في منطقة قابس ، يمكنك تناول الطعام في الفنادق ، كما يمكنك اختيار أحد المطاعم الصغيرة التي تقدم مأكولات بسيطة دون كحول",
        en: "A large coastal town, Gabes offers fish and seafood cooked in many ways: grilled fish, stuffed squid and dogfish with vegetable soup, or small ouzef fish with pepper salad. Shepherds' lamb also holds an important place in southern cooking — taste it with couscous or roasted. If you stay into autumn, take the chance to enjoy the oasis pomegranates. Tourist restaurants are scarce in the Gabes area, so you can eat at the hotels or choose one of the small restaurants serving simple food without alcohol.",
      },
      { type: "H3", ar: "حاول السكن في — فندق صحراوي أو منزل في الكهف", en: "Where to stay — a desert hotel or a cave house", noNumber: true },
      {
        type: "P",
        ar: "الفنادق في قابس ، لقلة السياحة نسبيا ، عددها محدود ولكنها لا تخلو من السحر ، في المنطقة هناك أشكال أصيلة من الاقامات التي تجعلك تعيش كامل انفعالات الصحراء : نزل من الطراز الصحراوي ، دار للضيافة بطمزرت ، مبيت صحراوي أو منزل كهفي في مطماطة",
        en: "Because tourism here is relatively limited, hotels in Gabes are few but not without charm. The region offers authentic forms of accommodation that let you live the full emotion of the desert: a desert-style inn, a guest house at Tamezret, a desert camp or a cave house in Matmata.",
      },
      { type: "H3", ar: "الخلاصة — النسيج بالجنوب", en: "In short — weaving in the south", noNumber: true },
      {
        type: "P",
        ar: "نول النسيج يحتل مكانة بارزة في منازل قرى الجنوب ، ومنه تستمد القرويات عديد أغراض حياتهن اليومية : الكليم والمرقوم وهو السجاد الاحمر العازل عن الارض ، الأغطية تكسو الجدران وتغطي الأسرة والوسائد تقوم مقام الأثاث ، ألوانها الدافئة تستخرج من الأصباغ النباتية : الأحمر المشرق والأزرق الداكن والبني والبرتقالي ، أكثرها بساطة تميزها خطوط ذات ألوان زاهية ، أما أجملها فتملؤها أنماط هندسية ، ورموز وحيوانات صغيرة ، وفق مصطلحات غنية بالمعاني التقليدية ، لا تزال القرويات ينسجن قطعا كبيرة من الصوف ، لتصبح ملابس للرجال أو للنساء ، وقطع صغيرة تنسج لتغطية الرأس عند الخروج من المنزل يطلق عليها اسم «البخنوق» ، هذه القطعة من الصوف الناعم ، الأحمر للشابات والأسود لكبار السن ، مزينة برسوم صغيرة منسوجة باللون الأبيض",
        en: "The loom holds a prominent place in the houses of the southern villages, and from it the village women draw many objects of daily life: the kilim and the mergoum, the red carpet that insulates from the ground; blankets that clothe the walls and cover the beds; cushions that serve as furniture. Their warm colours come from plant dyes — bright red, deep blue, brown and orange. The simplest are marked by lines of vivid colour, while the finest are filled with geometric patterns, symbols and small animals in a vocabulary rich with traditional meaning. Village women still weave large pieces of wool that become men's or women's clothing, and small pieces to cover the head when leaving the house, called the bakhnoug: this piece of soft wool, red for young women and black for the elderly, is decorated with small motifs woven in white.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "سوق جارا بقابس هو المكان الذي تباع فيه جميع الاختصاصات الحرفية التقليدية في الجهة ، ستعثر على كل أنواع المنسوجات من الحلفاء : سلال ، قبعات الشمس ، كذلك الأحذية المطرزة ومرقوم (سجاد) جنوب تونس ، بألوانه الدافئة وأنماطه الهندسية البربرية ، لتلوين شعرك بلون أحمر نحاسي ، أقتني الحناء فهي في قابس من أجود ما يعرض في البلاد",
        en: "The Jara souk in Gabes is where all the region's traditional crafts are sold. You will find every kind of esparto weaving — baskets and sun hats — as well as embroidered shoes and the mergoum carpet of southern Tunisia with its warm colours and Berber geometric patterns. And to tint your hair a coppery red, buy henna: that of Gabes is among the finest in the country.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "مطارات دولية في جربة (حوالي 100 كلم عن قابس) وصفاقس (160 كلم) ، طرق ممتازة تربط دوز بمطماطة ومدنين لرحلة كبيرة في جنوب تونس ، داخل قابس أختر سيارات الأجرة الصفراء ذات العداد",
        en: "There are international airports at Djerba (about 100 km from Gabes) and Sfax (160 km). Excellent roads link Douz with Matmata and Medenine for a grand tour of southern Tunisia. Within Gabes, choose the yellow metered taxis.",
      },
    ],
  },
  {
    slug: "tataouine",
    title_ar: "تطاوين وما حولها",
    title_en: "Tataouine and around",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2.tataouine,
    blocks: [
      { type: "H3", ar: "تطاوين .. متعة السفر والترفية", en: "Tataouine — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "تتجلى الصحراء في أوج قسوتها في تطاوين ومدنين ، سهل حجري شاسع ينفتح على مشاهد طبيعية رائعة للجبال والهضاب المتصحرة والمنحدرات والقمم الصخرية ، وفي هذا المشهد المهيب تبرز أبنية مذهلة ، انها القصور المخازن المحصنة لبدو الصحراء ، نفس الاعجاب يتجدد بالقرى البربرية القديمة المشدودة الى قمم الجبال ، مثل شنني والدويرات ، فتطاوين هي فعلا منطقة المشاهد الطبيعية الأخاذة والعادات الفريدة",
        en: "The desert shows itself at its harshest in Tataouine and Medenine: a vast stony plain opening onto magnificent landscapes of mountains, desert plateaux, escarpments and rocky peaks. In this majestic scenery astonishing buildings stand out — the ksour, the fortified granaries of the desert Bedouin. The same wonder returns with the old Berber villages clinging to the mountain tops, such as Chenini and Douiret. Tataouine is truly a region of breathtaking landscapes and singular customs.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2.tataouine, cap_ar: "تطاوين", cap_en: "Tataouine" },
      { type: "H3", ar: "تعنى لتشاهد — الغرف والقرى المعلقة", en: "Not to be missed — the ghorfas and the hanging villages", noNumber: true },
      {
        type: "P",
        ar: "زيارة القصور بتسلق السلالم والدرج التي كانت في السابق تمكن من رفع المحاصيل الى خلايا التخزين أي الغرف ، القرى المعلقة كانت لها أيضا غرفها ، مخازن كانت تحتل قمم الجبال ، في قريتي شنني والدويرات لا تزال اللغة البربرية تستخدم الى اليوم ، في قرية شنني سيأخذونك الى القبور العملاقة ويروون لك أسطورة النيام السبعة ، الأسطورة المتوسطية القديمة التي وجدت هنا ترجمة لها ، في الدويرات يمكنك زيارة مسجد تحت الأرض ، ولمحبي الجيولوجيا وعصور ما قبل التاريخ لوحات من العصر الحجري الحديث واضحة بالقرب من غمراسن ، بجبل طباقة قرب مدنين نرى نتوءا بحريا من العصر البرمي (250 مليون سنة) ، الفريد من نوعه في أفريقيا",
        en: "Visit the ksour by climbing the ladders and stairs that once served to hoist the harvest up to the storage cells, the ghorfas. The hanging villages had their ghorfas too, granaries set on the mountain tops. In Chenini and Douiret the Berber language is still spoken today. At Chenini they will take you to the giant tombs and tell you the legend of the Seven Sleepers, the old Mediterranean legend that found its version here. At Douiret you can visit an underground mosque. For lovers of geology and prehistory there are clear Neolithic rock panels near Ghomrassen, and at Jebel Tebaga near Medenine a Permian marine outcrop (250 million years old), unique in Africa.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — القرى البربرية", en: "To know more — the Berber villages", noNumber: true },
      {
        type: "P",
        ar: "كيف استطاع القرويون الاستقرار والتأقلم في منطقة قاحلة ووعرة مثل بلاد القصور ؟ ولماذا اختاروا الاقامة في قمم الجبال ؟ الجواب يكمن في الجسور ، النظام المبتكر للاحتفاظ بمياه الأمطار الشحيحة ، هذه السدود الصغيرة من التراب والحجارة ، عديدة الطوابق عند سفح الجبل ، تحبس مياه السيلان السطحية وتجعل زراعة المدرجات ممكنة لتلبية احتياجات القرية ، أما المنازل الكهفية ، فانها توفر جوا معتدلا في كل موسم ، ميزة ثمينة في هذه المناطق الجبلية ذات الصيف الحار ، ورغم نمط حياتهم الريفي ، فقد تمكن القرويون من ابتداع حرف تحظى بشعبية جارفة لدى الزوار على غرار نسيج السجاد والشالات بألوان زاهية وزخارف دقيقة",
        en: "How did villagers settle and adapt in a land as arid and rugged as the land of the ksour, and why did they choose to live on the mountain tops? The answer lies in the jessour, the ingenious system for holding scarce rainwater: these small dams of earth and stone, tiered at the foot of the mountain, trap the run-off and make terraced farming possible to meet the village's needs. The cave houses, meanwhile, keep a mild climate in every season — a precious quality in these mountain areas with their hot summers. Despite their rural way of life the villagers created crafts hugely popular with visitors, such as woven carpets and shawls in bright colours with fine motifs.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — التجوال والدينصورات", en: "Things to do — walking and dinosaurs", noNumber: true },
      {
        type: "P",
        ar: "قم بجولة على الأقدام لزيارة القصور المختلفة والقرى الجبلية ، ثم قم بزيارة متحف ذاكرة الأرض في تطاوين ، حيث نرى احافير الديناصور والنيازك المكتشفة في الجهة ، تابع نسج الفليج وهي أشرطة طويلة تشكل عند تجميعها خيمة بدوية ، زر السوق الأسبوعية ملتقى المزارعين ومربي الماشية ، ولا يفوتك مهرجان القصور : ستتابع اعادة لاحتفالات تخزين المحاصيل وتسمع الموسيقى والأغاني التقليدية للجنوب الشرقي (خلال شهر مارس) ، واذا كنت مغرما بالنباتات والحيوانات ، فيمكنك استكشاف الحديقة الطبيعية سيدي التوي ، أما الرحلة في اتجاه الغرب فتوصلك الى واحة قصر غيلان الفاصلة بين الصحراء الصخرية والصحراء الرملية",
        en: "Walk out to visit the various ksour and the mountain villages, then see the Memory of the Earth museum in Tataouine with its dinosaur fossils and meteorites found in the region. Watch the weaving of the flij, the long strips that assembled make a Bedouin tent, and visit the weekly market where farmers and herders meet. Do not miss the Ksour Festival: you will see a re-enactment of the harvest-storing celebrations and hear the traditional music and songs of the south-east (in March). If you love plants and wildlife, explore the Sidi Toui national park, and a trip westwards brings you to the oasis of Ksar Ghilane, on the boundary between the stony desert and the sand desert.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الفطائر أو الكسكسي", en: "Food to try — flatbread or couscous", noNumber: true },
      {
        type: "P",
        ar: "المأكل في هذه القرى بسيط ، يمكن تذوق فطائر السميد “الكسرة” مغموسة في الزيت البكر المستمد من زيتون القرية ، والتين أو الرمان المجمع من الجسور والعسل المعطر بالاكليل والزعتر ، وبطبيعة الحال الكسكسي بلحم الضأن اللذيذ ، أما المأكولات العالمية ، فيمكنك تناولها في فنادق المنطقة",
        en: "Food in these villages is simple: taste the semolina flatbread, kesra, dipped in virgin oil from the village olives, figs or pomegranates gathered from the jessour, honey scented with rosemary and thyme, and of course delicious couscous with lamb. For international food, eat at the hotels of the region.",
      },
      { type: "H3", ar: "حاول السكن في — فندق أو غرفة في كهف", en: "Where to stay — a hotel or a room in a cave", noNumber: true },
      {
        type: "P",
        ar: "في تطاوين ومدنين هناك بعض الفنادق البسيطة ، وزيارة المنطقة فرصة لتجربة اقامة طريفة : فندق متمازج مع المشاهد الطبيعية الصحراوية ، أو اقامة في منزل كهفي",
        en: "Tataouine and Medenine have a few simple hotels, and a visit to the region is a chance to try an unusual stay: a hotel blended into the desert landscape, or a night in a cave house.",
      },
      { type: "H3", ar: "الخلاصة — القصور", en: "In short — the ksour", noNumber: true },
      {
        type: "P",
        ar: "مذهلة هي القصور التي تنشأ في قلب طبيعة جافة من جبال وهضاب وقمم شديدة الانحدار ، كانت هذه “القلاع الصحراوية” مركز التقاء البدو من المنطقة لخزن محاصيلهم وحمايتها من اللصوص في مقصورات تدعى غرف ، أما قصور الجبال فهي مشيدة في القمم وممزوجة مع الصخر في قرى مثل شنني ، دويرات وغرماسة ، ومن أكبر القصور في المنطقة قصر حدادة ، قصر أولاد سلطان وقصر أولاد دباب ويضم بعضها مئات الغرف الموزعة أحيانا على أربع طوابق",
        en: "Astonishing are the ksour that rise in the heart of a dry landscape of mountains, plateaux and steep peaks. These “desert castles” were the meeting point of the region's Bedouin, who stored their harvests there and protected them from thieves in cells called ghorfas. The mountain ksour are built on the summits and merge with the rock in villages such as Chenini, Douiret and Guermessa. Among the largest in the region are Ksar Haddada, Ksar Ouled Soltane and Ksar Ouled Debbab, some of which hold hundreds of ghorfas, sometimes spread over four storeys.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "في الأسواق الأسبوعية قد تجد بطانية منسوجة ، أو قطعة قماش جميلة وذات رسومات هندسية مثل البخنوق وهو الشال البربري المميز لنساء المنطقة",
        en: "At the weekly markets you may find a woven blanket or a beautiful piece of cloth with geometric designs, such as the bakhnoug, the Berber shawl distinctive to the women of the region.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "يمكن الوصول الى تطاوين عبر طريق معبدة وهي تبعد 140 كم عن مطار جربة الدولي",
        en: "Tataouine is reached by a paved road and lies 140 km from Djerba international airport.",
      },
    ],
  },
  {
    slug: "mahdia",
    title_ar: "المهدية وما حولها",
    title_en: "Mahdia and around",
    kicker_ar: "منطقة",
    kicker_en: "Region",
    image: TUNIS_REGION_HEROES_2.mahdia,
    blocks: [
      { type: "H3", ar: "المهدية .. متعة السفر والترفية", en: "Mahdia — the pleasure of travel and leisure", noNumber: true },
      {
        type: "P",
        ar: "تمتد مدينة المهدية على شبه جزيرة رقيقة ، محاطة بالمياه وزاخرة بالشواطىء الجميلة ، وهي كذالك مدينة الأصالة والنسيج حيث النساء تتزين بأبهى الحلل والمجوهرات ، والمنازل تتجمل بالستائر المطرزة ، بوابتها الضخمة «السقيفة الكحلة» تذكر بالماضي المجيد للمدينة : حيث كانت في القرن العاشر أول عاصمة للدولة الفاطمية قبل انتقالها الى مصر وسوريا ، أجواءها المتوسطية تذكر أنها كانت في القرن الماضي مقصد المهاجرين من اليونانين والأندلسيين وخصوصا الصيادين الصقليين",
        en: "Mahdia stretches along a slender peninsula surrounded by water and rich in beautiful beaches. It is also a city of authenticity and weaving, where women adorn themselves with the finest dress and jewellery and houses are decked with embroidered hangings. Its huge gate, Skifa el Kahla, recalls the city's glorious past: in the tenth century it was the first capital of the Fatimid state before it moved to Egypt and Syria. Its Mediterranean atmosphere recalls that in the last century it drew Greek and Andalusian migrants and above all Sicilian fishermen.",
      },
      { type: "IMG", src: TUNIS_REGION_HEROES_2.mahdia, cap_ar: "المهدية", cap_en: "Mahdia" },
      { type: "H3", ar: "تعنى لتشاهد — المدينة العتيقة وميناء الصيد", en: "Not to be missed — the medina and the fishing port", noNumber: true },
      {
        type: "P",
        ar: "زيارة المدينة العتيقة تبدأ بعبور رواق مغطى « السقيفة الكحلة» ببرجه المهيب ، كان في السابق مدخلا لحصن لا يعبره سوى حاشية الخليفة الفاطمي ، اليوم هو سوق تباع فيه ملابس الاعراس المطرزة والمذهبة ، ثم تنطلق الجولة بين أنهج المدينة وأبواب منازلها الخضراء الجميلة التي يؤطرها الحجر المنحوت ، استرح قليلا في ظل شجرة بساحة القاهرة ، ثم اتجه نحو المقبرة البحرية حيث القبور البيضاء البسيطة المنحدرة نحو البحر وهو مكان تربض فيه بضعة زوارق في ميناء حفر في الصخر قديما ، بالخروج من المدينة العتيقة ، وجب التجول في ميناء الصيد ، الذي يعد من أكبر المواني في تونس",
        en: "A visit to the medina begins by passing through the covered gallery of Skifa el Kahla with its imposing tower, once the entrance to a fortress crossed only by the Fatimid caliph's retinue and today a souk where embroidered and gilded wedding clothes are sold. The walk then goes on among the town's lanes and the beautiful green doors framed by carved stone. Rest a while in the shade of a tree on Cairo Square, then head for the marine cemetery, where simple white graves slope down towards the sea and a few boats lie in a harbour cut long ago into the rock. Leaving the medina, walk around the fishing port, one of the largest in Tunisia.",
      },
      { type: "H3", ar: "لمزيد من المعرفة — مدينة المهدية", en: "To know more — the city of Mahdia", noNumber: true },
      {
        type: "P",
        ar: "في البداية كانت المهدية ميناء تجاريا قرطاجيا تسمى كاب (رأس) أفريقيا ، ثم عرفت أوجها في القرن 10 مع بروز الخلفاء الفاطميين في تونس ، وأولهم المهدي الذي جعل من المهدية عاصمة له ، وبنى في شبه الجزيرة مدينة محصنة مذهلة ، وفي وقت لاحق ، غزا الفاطميون مصر وبنوا هناك عاصمة جديدة هي القاهرة لتصبح المهدية قاعدة للقراصنة ، ثم ميناء مسالما ، حيث استقر به العديد من الصيادين اليونانيين والصقليين ، في عام 1907 ، أصبحت المهدية شهيرة بفضل عدد من علماء الآثار من جميع أنحاء العالم واكتشافهم لحطام سفينة قديمة كانت محملة بالتماثيل والأشياء الثمينة ، بالقرب من مهدية خلفت العصور القديمة معلما أستثنائيا : مسرح الجم ، الذي يضاهي في حجمه نظيره الايطالي كولوسيوم روما ، وهو ما يعد دليلا على قيمة المنطقة عند الرومان لثراءها الفلاحي وزياتينها",
        en: "Mahdia began as a Carthaginian trading port called Cape Africa, then reached its peak in the tenth century with the rise of the Fatimid caliphs in Tunisia, the first of whom, al-Mahdi, made it his capital and built an astonishing fortified city on the peninsula. Later the Fatimids conquered Egypt and built a new capital there, Cairo, and Mahdia became a pirate base and then a peaceful port where many Greek and Sicilian fishermen settled. In 1907 Mahdia became famous thanks to archaeologists from around the world who discovered the wreck of an ancient ship loaded with statues and precious objects. Near Mahdia antiquity left an exceptional monument: the amphitheatre of El Jem, a rival in size to the Colosseum of Rome and proof of the value the Romans placed on this region for its farming wealth and its olives.",
      },
      {
        type: "P",
        ar: "مسرح الجم ، أيقونة السياحة في مدينة المهدية",
        en: "The amphitheatre of El Jem, the tourism icon of the Mahdia region.",
      },
      { type: "H3", ar: "أنشطة وبرامج عليك القيام بها — التاريخ أو الغوص", en: "Things to do — history or diving", noNumber: true },
      {
        type: "P",
        ar: "في المهدية لك ما تريد من الأنشطة : الاستلقاء على شواطئ من الرمال الذهبية ، والتمتع بالرياضات والألعاب التي تقدمها العديد من الفنادق ، الغوص في أعماق البحر أو الاسترخاء في مركز علاج بمياه البحر ، في المدينة العتيقة ، زر احدى ورشات النساجين أو منزلا قديما ، حيث الغرف تغطيها ستائر ملونة أو المسجد الفاطمي الكبير المشيد سنة 916 ، ثم تحول الى القلعة التركية «البرج – الكبير» ، حيث أدار القرصان درغوث معارك هامة ضد الاسبان من أجل السيطرة على تونس ، في متحف المدينة ، يمكنك الاستمتاع بمشاهدة الفسيفساء الروماني والعملات الذهبية من الحقبة البيزنطية واللباس التقليدي الجميل لعروس المهدية ، وحول المهدية ، لا تفوتك زيارة المنستير ، مدينة تاريخية أخرى ، والمسرح الروماني الكبير بالجم ، ثاني أكبر مسرح بعد كوليزي روما",
        en: "Mahdia offers whatever you want: lying on beaches of golden sand, sports and games at the many hotels, diving in the depths of the sea or relaxing at a seawater spa. In the medina, visit a weaver's workshop or an old house whose rooms are hung with coloured drapes, or the great Fatimid mosque built in 916; then go on to the Turkish fort, Borj el Kebir, from where the corsair Dragut led important battles against the Spanish for control of Tunisia. In the city museum you can admire Roman mosaics, gold coins from the Byzantine era and the beautiful traditional dress of the Mahdia bride. Around Mahdia, do not miss Monastir, another historic city, and the great Roman amphitheatre of El Jem, the second largest after the Colosseum of Rome.",
      },
      { type: "H3", ar: "جرب هذه الأكلات — الأخطبوط وزيت الزيتون", en: "Food to try — octopus and olive oil", noNumber: true },
      {
        type: "P",
        ar: "للسمك مكانة كبيرة في فن الطبخ بالمهدية ، سواء مع الكسكسي ، أو مطهوا بالفرن مع التوابل وشرائح الليمون ، لتناول وجبة خفيفة ، اختر سلطة الأخطبوط الطازج ، مع الليمون وزيت الزيتون ، أو شكشوكة من الفلفل والطماطم والبطاطا مع بيضة للتحلية ، تذوق «بريك المهدية» مثلث من عجينة مورقة محشو باللوز ، وفقا للرغبة يمكن أن يكون الغداء بمواجهه الميناء ، حيث بعض المطاعم الشهيرة ، أو بتناول وجبة خفيفة في مقهى في المدينة",
        en: "Fish holds a great place in Mahdia's cooking, whether with couscous or baked with spices and lemon slices. For something light, choose the fresh octopus salad with lemon and olive oil, or a chakchouka of peppers, tomatoes and potatoes with an egg. Taste the brik of Mahdia, a triangle of flaky pastry filled with almonds. Lunch can be taken facing the port, where several well-known restaurants are found, or as a snack in a café in town.",
      },
      { type: "H3", ar: "حاول السكن في — النوادي والنزل الفاخرة أو دور الضيافة", en: "Where to stay — clubs, luxury hotels or guest houses", noNumber: true },
      {
        type: "P",
        ar: "تعد المهدية عديد الفنادق الراقية المشيدة على امتداد الساحل ، من القصر الفخم الى النادي ، ويمكنك أيضا اختيار فندقا صغيرا وسط المدينة أو احدى دور الضيافة على شاطئ خالى من المصطافين ، على بعد كيلومترات قليلة من المهدية",
        en: "Mahdia has many refined hotels built along the coast, from the luxury palace to the holiday club, and you can also choose a small hotel in the town centre or a guest house on a beach empty of holidaymakers, a few kilometres from Mahdia.",
      },
      { type: "H3", ar: "الخلاصة — نسيج المهدية", en: "In short — the weaving of Mahdia", noNumber: true },
      {
        type: "P",
        ar: "في تونس ، يختلف زي العروس باختلاف الجهة ، السترة المطرزة بالذهب ، والمشدات اللماعة ، وسراويل الدانتيل والملاءات ، كل هذه الأزياء النسائية التقليدية تعد من روائع الصناعات التقليدية للبلاد ، في المهدية ، العروس المحلاة بالذهب والمجوهرات والقمصان اللماعة ، تلتف بملاءة حريرية متلألئة الألوان تنسج في ورشات المدينة العتيقة التي تضج بأصوات البكرات المنطلقة بسرعة في الأنوال الخشبية ، توقف للاستمتاع بمهارة الحرفيين الذين يتلاعبون ببكرات متعددة الألوان ، خبرتهم تعود لزمن بعيد كما نقله في القرن 12 الجغرافي الشهير الادريسي بقوله تصنع الاقمشة الرفيعة والجميلة المعروفة باسم أقمشة المهدية حيث تصدر بكثرة في جميع المواسم ، ذلك لأنها غير قابلة للتقليد",
        en: "In Tunisia the bride's dress differs from region to region: the gold-embroidered jacket, the shining bodices, the lace trousers and the wraps — all these traditional women's costumes are among the country's finest crafts. In Mahdia the bride, adorned with gold, jewellery and gleaming shirts, wraps herself in a silk sheet of shimmering colours woven in the workshops of the medina, which ring with the sound of shuttles flying through the wooden looms. Stop to admire the skill of the craftsmen handling their many-coloured spools; their expertise goes far back, as the famous twelfth-century geographer al-Idrisi recorded when he wrote that fine and beautiful fabrics known as Mahdia cloth are made there and exported in quantity in every season, because they cannot be imitated.",
      },
      { type: "H3", ar: "التسوق .. متعة المسافر", en: "Shopping — a traveller's pleasure", noNumber: true },
      {
        type: "P",
        ar: "استمتع باختيار وشاح الحرير الثمين المنسوج في أحد الورشات بالمدينة ، وهو علامة لصناعة عريقة بالمهدية ، أو اختيار زوج من الفوطة ، مناشف طويلة للحمام مصنوعة بالجهة ، ذات الألوان الزاهية والخطوط الرقيقة مما يجعلها من كماليات الموضة ، وأيضا أدوات المائدة المتعددة الألوان من الخزف ، وسجاد القيروان ، وعدة حاجيات أخرى من الصناعات التقليدية اليدوية",
        en: "Enjoy choosing a precious silk scarf woven in one of the town's workshops, the mark of an age-old Mahdia craft, or a pair of fouta, the long bath towels made in the region whose bright colours and fine stripes have made them a fashion accessory — as well as multicoloured ceramic tableware, Kairouan carpets and many other handicrafts.",
      },
      { type: "H3", ar: "كيفية الوصول", en: "Getting there", noNumber: true },
      {
        type: "P",
        ar: "ترتبط المهدية بمطار المنستير الدولي الذي يبعد 50 كلم ، يتيح خط القطار الجهوي الوصول بسهولة الى سوسة عبر قرى المكنين (ورش الفخار) ولمطة (موقع أثري) ، يمكن أيضا التنقل بسيارة تاكسي جماعي (بخط ثابت) وسيارات الأجرة",
        en: "Mahdia is served by Monastir international airport, 50 km away. The regional railway line makes it easy to reach Sousse by way of the villages of Moknine (pottery workshops) and Lamta (an archaeological site). You can also travel by shared fixed-route taxi or by ordinary taxi.",
      },
    ],
  },
];
