import type { UI } from "./ar";

export const en: UI = {
  siteName: "Ambassador of Love",
  tagline: "Ahmad's journey around the world",
  nav: {
    home: "Home",
    explore: "Explore",
    continents: "Continents",
    countries: "Countries",
    itineraries: "Itineraries",
    stories: "Stories",
    about: "About Ahmad",
    menu: "Menu",
    language: "Language",
  },
  hero: {
    eyebrow: "Bahrain • World",
    title: "From Bahrain to the world",
    sub: "Ahmad's journey to discover countries, cities, and cultures across the globe.",
    cta1: "Explore the journey",
    cta2: "About Ahmad",
  },
  sections: {
    aboutAhmad: "About Ahmad",
    ahmadIntro:
      "Ahmad Abdulrahman, from the Kingdom of Bahrain. He began travelling more than ten years ago with one goal: to visit a hundred countries and beyond. Today he documents what he has seen so others can benefit, building bridges of love and coexistence with each trip.",
    introTitle: "A story that began with passion",
    introCta: "About Ahmad",
    continentsLabel: "Continents",
    byContinent: "Explore by continent",
    destinations: "Destinations",
    viewAll: "View all destinations",
    countries: "Countries Ahmad has visited",
    countriesAll: "View all countries",
    countriesLine: "{count} countries documented across years of travel.",
    countriesWord: "countries",
    featured: "Featured journey",
    readStory: "Read the story",
    searchPlaceholder: "Search for a country",
    noResults: "No results",
    citiesLabel: "Cities",
    cities: "Cities Ahmad visited",
    otherCities: "Other cities",
    attractions: "Notable places",
    highlights: "Highlights",
    culture: "Culture & notes",
    relatedItineraries: "Related itineraries",
    discover: "Discover the journey",
    explore: "Explore",
    read: "Read",
    introduction: "Introduction",
    sectionsLabel: "Sections",
    moreSections: "More sections",
    keepScrolling: "Keep scrolling",
    world: "World",
    back: "Back",
    backTo: "Back to {name}",
    days: "days",
    day: "Day {n}",
  },
  labels: {
    capital: "Capital",
    currency: "Currency",
    population: "Population",
    area: "Area",
    religion: "Religion",
    founded: "Founded",
    close: "Close",
    previous: "Previous",
    next: "Next",
    openImage: "Open image",
    loading: "Loading…",
  },
  countriesPage: {
    title: "Countries Ahmad has visited",
    sub: "More than a hundred countries, documented over years.",
    all: "All countries",
  },
  about: {
    title: "Ahmad Abdulrahman",
    sub: "From the Kingdom of Bahrain — founder of the Ambassador of Love project.",
    p1: "Ahmad Abdulrahman Mohammed, from the Kingdom of Bahrain. I began travelling more than ten years ago with one clear goal: to visit a hundred countries and beyond. By God's grace, I recently completed that goal.",
    p2: "Today I document my journeys across social platforms so others can benefit, and so that together we can build relationships of love and connection rooted in peace and coexistence. I'm always glad to hear from travellers and answer questions about the road.",
    quote: "\u201cHow narrow life would be, were it not for the openness of travel.\u201d",
  },
  footer: {
    rights: "All rights reserved",
    desc: "A personal travel archive documenting Ahmad's journeys from Bahrain to more than a hundred countries around the world.",
    social: "Social",
    line: "Bahrain ⟶ World",
  },
  weather: {
    eyebrow: "Climate guide",
    title: "Weather through the year",
    sub: "Average temperatures and rainfall in the UAE, month by month.",
    high: "High",
    low: "Low",
    rain: "Rain",
    notes: {
      mildSunny: "Mild & sunny",
      pleasant: "Pleasant",
      warm: "Warm",
      warmToHot: "Warm to hot",
      hotDry: "Hot & dry",
      veryHot: "Very hot",
      hotHumid: "Hot & humid",
      hot: "Hot",
      mild: "Mild",
    },
    legend: { mild: "Mild", warm: "Warm", hot: "Hot", veryHot: "Very hot" },
  },
  anthem: { label: "National Anthem", play: "Play", pause: "Pause" },
  france: {
    name: "France",
    introBadge: "★ Introduction",
    aboutLabel: "00 · About",
    about:
      "France is a constitutional republic in Western Europe. Its motto is Liberty, Equality, and Fraternity. An ancient country formed in the Middle Ages, it reached its peak in the 19th and 20th centuries and held the second-largest colonial empire in 1950. It is a founding member of the European Union and a permanent member of the UN Security Council.",
    factLabel1: "01 · Fact",
    factLabel2: "02 · Fact",
    watchLabel: "03 · Watch",
    emblemLabel: "National Emblem",
    emblemTitle: "Emblem of the French Republic",
    geoLabel: "Geography",
    geoTitle: "France on the map · Capital Paris",
    glimpse: "A glimpse of France",
    anthemTitle: "La Marseillaise",
    moreAbout: "More about France",
    euro: "Euro (€)",
    population: "67.1 million",
    area: "674,843 km²",
    religion: "Christianity",
    founded: "1958",
  },
  assistant: {
    button: "Ask the travel assistant",
    title: "AI Travel Assistant",
    subtitle: "Safir Al Mohabba archive + reliable sources",
    welcome:
      "Hi. I can help with travel questions, countries, cities, cultures, attractions, and trip ideas using the Safir Al Mohabba archive and reliable internet sources.",
    placeholder: "Ask a travel question…",
    error: "Something went wrong. Please try again.",
    close: "Close",
    suggestions: [
      "What should I visit in France?",
      "Compare Japan and South Korea",
      "Best time to visit Switzerland",
      "What is the culture like in Morocco?",
      "Plan a 7-day trip in France",
      "Which cities did Ahmad cover in France?",
    ],
  },
  errors: {
    notFoundTitle: "Page not found",
    notFoundBody: "The page you're looking for doesn't exist or has been moved.",
    goHome: "Go home",
    errorTitle: "This page didn't load",
    errorBody: "Something went wrong on our end. You can try refreshing or head back home.",
    tryAgain: "Try again",
  },
  seo: {
    homeTitle: "Ambassador of Love — Ahmad's journey around the world",
    homeDesc:
      "The travel archive of Ahmad Abdulrahman, from Bahrain to the world: continents, countries, cities, stories and itineraries.",
    countriesTitle: "Countries — Ambassador of Love",
    countriesDesc: "Browse every country Ahmad Abdulrahman has visited around the world.",
    aboutTitle: "About Ahmad — Ambassador of Love",
    aboutDesc: "The story of Ahmad Abdulrahman from Bahrain and his journey to more than a hundred countries.",
  },
};