import type { UI } from "./ar";

export const es: UI = {
  siteName: "Embajador del Amor",
  tagline: "El viaje de Ahmad alrededor del mundo",
  nav: {
    home: "Inicio",
    explore: "Explorar",
    continents: "Continentes",
    countries: "Países",
    itineraries: "Itinerarios",
    stories: "Relatos",
    about: "Sobre Ahmad",
    menu: "Menú",
    language: "Idioma",
  },
  hero: {
    eyebrow: "Baréin • Mundo",
    title: "De Baréin al mundo",
    sub: "El viaje de Ahmad para descubrir países, ciudades y culturas de todo el mundo.",
    cta1: "Explorar el viaje",
    cta2: "Sobre Ahmad",
  },
  sections: {
    aboutAhmad: "Sobre Ahmad",
    ahmadIntro:
      "Ahmad Abdulrahman, del Reino de Baréin. Empezó a viajar hace más de diez años con un objetivo: visitar cien países y más. Hoy documenta lo que ha visto para que otros se beneficien, construyendo en cada viaje puentes de amor y convivencia.",
    introTitle: "Una historia que nació de una pasión",
    introCta: "Sobre Ahmad",
    continentsLabel: "Continentes",
    byContinent: "Explora por continente",
    destinations: "Destinos",
    viewAll: "Ver todos los destinos",
    countries: "Países que Ahmad ha visitado",
    countriesAll: "Ver todos los países",
    countriesLine: "{count} países documentados a lo largo de años de viaje.",
    countriesWord: "países",
    featured: "Relato destacado",
    readStory: "Leer el relato",
    searchPlaceholder: "Buscar un país",
    noResults: "Sin resultados",
    citiesLabel: "Ciudades",
    cities: "Ciudades que Ahmad visitó",
    otherCities: "Otras ciudades",
    attractions: "Lugares destacados",
    highlights: "Imprescindibles",
    culture: "Cultura y notas",
    relatedItineraries: "Itinerarios relacionados",
    discover: "Descubrir el viaje",
    explore: "Descubrir",
    read: "Leer",
    introduction: "Introducción",
    sectionsLabel: "Secciones",
    moreSections: "Más secciones",
    keepScrolling: "Sigue desplazándote",
    world: "Mundo",
    back: "Volver",
    backTo: "Volver a {name}",
    days: "días",
    day: "Día {n}",
  },
  labels: {
    capital: "Capital",
    currency: "Moneda",
    population: "Población",
    area: "Superficie",
    religion: "Religión",
    founded: "Fundación",
    close: "Cerrar",
    previous: "Anterior",
    next: "Siguiente",
    openImage: "Abrir imagen",
    loading: "Cargando…",
  },
  countriesPage: {
    title: "Países que Ahmad ha visitado",
    sub: "Más de cien países, documentados durante años.",
    all: "Todos los países",
  },
  about: {
    title: "Ahmad Abdulrahman",
    sub: "Del Reino de Baréin — fundador del proyecto Embajador del Amor.",
    p1: "Ahmad Abdulrahman Mohammed, del Reino de Baréin. Empecé a viajar hace más de diez años con un objetivo claro: visitar cien países y más. Gracias a Dios, hace poco logré esa meta.",
    p2: "Hoy documento mis viajes en las redes para que otros se beneficien y para construir juntos relaciones de amor y cercanía basadas en la paz y la convivencia. Siempre me alegra responder vuestras preguntas sobre viajes.",
    quote: "«Qué estrecha sería la vida sin la amplitud del viaje»",
  },
  footer: {
    rights: "Todos los derechos reservados",
    desc: "Un archivo personal de viajes que documenta los recorridos de Ahmad, desde Baréin hasta más de cien países del mundo.",
    social: "Redes",
    line: "Baréin ⟶ Mundo",
  },
  weather: {
    eyebrow: "Guía del clima",
    title: "El clima durante el año",
    sub: "Temperaturas y lluvias medias en los Emiratos, mes a mes.",
    high: "Máx",
    low: "Mín",
    rain: "Lluvia",
    notes: {
      mildSunny: "Suave y soleado",
      pleasant: "Agradable",
      warm: "Cálido",
      warmToHot: "Cálido a caluroso",
      hotDry: "Caluroso y seco",
      veryHot: "Muy caluroso",
      hotHumid: "Caluroso y húmedo",
      hot: "Caluroso",
      mild: "Suave",
    },
    legend: { mild: "Suave", warm: "Cálido", hot: "Caluroso", veryHot: "Muy caluroso" },
  },
  anthem: { label: "Himno nacional", play: "Reproducir", pause: "Pausa" },
  france: {
    name: "Francia",
    introBadge: "★ Introducción",
    aboutLabel: "00 · Resumen",
    about:
      "Francia es una república constitucional de Europa occidental cuyo lema es Libertad, Igualdad y Fraternidad. País antiguo formado en la Edad Media, alcanzó su apogeo en los siglos XIX y XX y poseía el segundo imperio colonial del mundo en 1950. Es miembro fundador de la Unión Europea y miembro permanente del Consejo de Seguridad de la ONU.",
    factLabel1: "01 · Dato",
    factLabel2: "02 · Dato",
    watchLabel: "03 · Vídeo",
    emblemLabel: "Emblema nacional",
    emblemTitle: "Emblema de la República Francesa",
    geoLabel: "Geografía",
    geoTitle: "Francia en el mapa · Capital París",
    glimpse: "Una mirada a Francia",
    anthemTitle: "La Marsellesa",
    moreAbout: "Más sobre Francia",
    euro: "Euro (€)",
    population: "67,1 millones",
    area: "674.843 km²",
    religion: "Cristianismo",
    founded: "1958",
  },
  assistant: {
    button: "Pregunta al asistente de viajes",
    title: "Asistente de viajes IA",
    subtitle: "Archivo de Ahmad + fuentes fiables",
    welcome:
      "Hola. Puedo ayudarte con preguntas sobre viajes, países, ciudades, culturas, lugares de interés e ideas de itinerarios, usando el archivo de Ahmad y fuentes fiables de internet.",
    placeholder: "Escribe tu pregunta de viaje…",
    error: "Algo salió mal. Inténtalo de nuevo.",
    close: "Cerrar",
    suggestions: [
      "¿Qué visitar en Francia?",
      "Compara Japón y Corea del Sur",
      "Mejor época para visitar Suiza",
      "¿Cómo es la cultura en Marruecos?",
      "Planifica un viaje de 7 días por Francia",
      "¿Qué ciudades de Francia cubrió Ahmad?",
    ],
  },
  errors: {
    notFoundTitle: "Página no encontrada",
    notFoundBody: "La página que buscas no existe o se ha movido.",
    goHome: "Ir al inicio",
    errorTitle: "Esta página no se cargó",
    errorBody: "Algo salió mal. Prueba a actualizar o vuelve al inicio.",
    tryAgain: "Reintentar",
  },
  seo: {
    homeTitle: "Embajador del Amor — el viaje de Ahmad por el mundo",
    homeDesc:
      "El archivo de viajes de Ahmad Abdulrahman, de Baréin al mundo: continentes, países, ciudades, relatos e itinerarios.",
    countriesTitle: "Países — Embajador del Amor",
    countriesDesc: "Explora todos los países que Ahmad Abdulrahman ha visitado por el mundo.",
    aboutTitle: "Sobre Ahmad — Embajador del Amor",
    aboutDesc: "La historia de Ahmad Abdulrahman, de Baréin, y su viaje a más de cien países.",
  },
};