import type { UI } from "./ar";

export const fr: UI = {
  siteName: "Ambassadeur de l'Amour",
  tagline: "Le voyage d'Ahmad autour du monde",
  nav: {
    home: "Accueil",
    explore: "Explorer",
    continents: "Continents",
    countries: "Pays",
    itineraries: "Itinéraires",
    stories: "Récits",
    about: "À propos d'Ahmad",
    menu: "Menu",
    language: "Langue",
  },
  hero: {
    eyebrow: "Bahreïn • Monde",
    title: "De Bahreïn au monde entier",
    sub: "Le voyage d'Ahmad à la découverte des pays, des villes et des cultures du monde.",
    cta1: "Explorer le voyage",
    cta2: "À propos d'Ahmad",
  },
  sections: {
    aboutAhmad: "À propos d'Ahmad",
    ahmadIntro:
      "Ahmad Abdulrahman, du Royaume de Bahreïn. Il a commencé à voyager il y a plus de dix ans avec un seul objectif : visiter cent pays et plus. Aujourd'hui, il documente ce qu'il a vu pour que d'autres en profitent, construisant à chaque voyage des ponts d'amour et de coexistence.",
    introTitle: "Une histoire née d'une passion",
    introCta: "À propos d'Ahmad",
    continentsLabel: "Continents",
    byContinent: "Explorer par continent",
    destinations: "Destinations",
    viewAll: "Voir toutes les destinations",
    countries: "Les pays visités par Ahmad",
    countriesAll: "Voir tous les pays",
    countriesLine: "{count} pays documentés au fil des années de voyage.",
    countriesWord: "pays",
    featured: "Récit à la une",
    readStory: "Lire le récit",
    searchPlaceholder: "Rechercher un pays",
    noResults: "Aucun résultat",
    citiesLabel: "Villes",
    cities: "Les villes visitées par Ahmad",
    otherCities: "Autres villes",
    attractions: "Lieux remarquables",
    highlights: "À ne pas manquer",
    culture: "Culture et notes",
    relatedItineraries: "Itinéraires liés",
    discover: "Découvrir le voyage",
    explore: "Découvrir",
    read: "Lire",
    introduction: "Introduction",
    sectionsLabel: "Sections",
    moreSections: "Autres sections",
    keepScrolling: "Continuez à faire défiler",
    world: "Monde",
    back: "Retour",
    backTo: "Retour à {name}",
    days: "jours",
    day: "Jour {n}",
  },
  labels: {
    capital: "Capitale",
    currency: "Monnaie",
    population: "Population",
    area: "Superficie",
    religion: "Religion",
    founded: "Fondation",
    close: "Fermer",
    previous: "Précédent",
    next: "Suivant",
    openImage: "Ouvrir l'image",
    loading: "Chargement…",
  },
  countriesPage: {
    title: "Les pays visités par Ahmad",
    sub: "Plus de cent pays, documentés au fil des années.",
    all: "Tous les pays",
  },
  about: {
    title: "Ahmad Abdulrahman",
    sub: "Du Royaume de Bahreïn — fondateur du projet Ambassadeur de l'Amour.",
    p1: "Ahmad Abdulrahman Mohammed, du Royaume de Bahreïn. J'ai commencé à voyager il y a plus de dix ans avec un objectif clair : visiter cent pays et plus. Grâce à Dieu, j'ai récemment atteint cet objectif.",
    p2: "Aujourd'hui, je documente mes voyages sur les réseaux afin que d'autres en profitent, et pour que nous construisions ensemble des liens d'amour fondés sur la paix et la coexistence. C'est toujours un plaisir de répondre à vos questions sur le voyage.",
    quote: "« Que la vie serait étroite sans l'ouverture du voyage »",
  },
  footer: {
    rights: "Tous droits réservés",
    desc: "Une archive de voyage personnelle documentant les périples d'Ahmad, de Bahreïn à plus de cent pays à travers le monde.",
    social: "Réseaux",
    line: "Bahreïn ⟶ Monde",
  },
  weather: {
    eyebrow: "Guide climatique",
    title: "La météo au fil de l'année",
    sub: "Températures et précipitations moyennes aux Émirats, mois par mois.",
    high: "Max",
    low: "Min",
    rain: "Pluie",
    notes: {
      mildSunny: "Doux et ensoleillé",
      pleasant: "Agréable",
      warm: "Chaud",
      warmToHot: "Chaud à très chaud",
      hotDry: "Chaud et sec",
      veryHot: "Très chaud",
      hotHumid: "Chaud et humide",
      hot: "Chaud",
      mild: "Doux",
    },
    legend: { mild: "Doux", warm: "Chaud", hot: "Très chaud", veryHot: "Caniculaire" },
  },
  anthem: { label: "Hymne national", play: "Lecture", pause: "Pause" },
  france: {
    name: "France",
    introBadge: "★ Introduction",
    aboutLabel: "00 · Aperçu",
    about:
      "La France est une république constitutionnelle d'Europe occidentale, dont la devise est Liberté, Égalité, Fraternité. Pays ancien formé au Moyen Âge, elle atteint son apogée aux XIXe et XXe siècles et possédait le deuxième empire colonial du monde en 1950. Elle est membre fondateur de l'Union européenne et membre permanent du Conseil de sécurité de l'ONU.",
    factLabel1: "01 · Fait",
    factLabel2: "02 · Fait",
    watchLabel: "03 · Vidéo",
    emblemLabel: "Emblème national",
    emblemTitle: "Emblème de la République française",
    geoLabel: "Géographie",
    geoTitle: "La France sur la carte · Capitale Paris",
    glimpse: "Un aperçu de la France",
    anthemTitle: "La Marseillaise",
    moreAbout: "En savoir plus sur la France",
    euro: "Euro (€)",
    population: "67,1 millions",
    area: "674 843 km²",
    religion: "Christianisme",
    founded: "1958",
  },
  assistant: {
    button: "Demandez à l'assistant voyage",
    title: "Assistant de voyage IA",
    subtitle: "Archive d'Ahmad + sources fiables",
    welcome:
      "Bonjour. Je peux répondre à vos questions sur le voyage, les pays, les villes, les cultures, les sites à visiter et la préparation de vos séjours, à partir de l'archive d'Ahmad et de sources fiables.",
    placeholder: "Posez votre question de voyage…",
    error: "Une erreur est survenue. Réessayez.",
    close: "Fermer",
    suggestions: [
      "Que visiter en France ?",
      "Compare le Japon et la Corée du Sud",
      "Meilleure période pour visiter la Suisse",
      "Comment est la culture au Maroc ?",
      "Planifie un voyage de 7 jours en France",
      "Quelles villes françaises Ahmad a-t-il couvertes ?",
    ],
  },
  errors: {
    notFoundTitle: "Page introuvable",
    notFoundBody: "La page que vous cherchez n'existe pas ou a été déplacée.",
    goHome: "Retour à l'accueil",
    errorTitle: "Cette page n'a pas pu se charger",
    errorBody: "Une erreur est survenue. Essayez de rafraîchir ou revenez à l'accueil.",
    tryAgain: "Réessayer",
  },
  seo: {
    homeTitle: "Ambassadeur de l'Amour — le voyage d'Ahmad autour du monde",
    homeDesc:
      "L'archive de voyage d'Ahmad Abdulrahman, de Bahreïn au monde entier : continents, pays, villes, récits et itinéraires.",
    countriesTitle: "Pays — Ambassadeur de l'Amour",
    countriesDesc: "Parcourez tous les pays visités par Ahmad Abdulrahman à travers le monde.",
    aboutTitle: "À propos d'Ahmad — Ambassadeur de l'Amour",
    aboutDesc: "L'histoire d'Ahmad Abdulrahman, de Bahreïn, et son voyage vers plus de cent pays.",
  },
};