import type { UI } from "./ar";

export const zh: UI = {
  siteName: "友爱使者",
  tagline: "艾哈迈德的环球旅程",
  nav: {
    home: "首页",
    explore: "探索",
    continents: "各大洲",
    countries: "国家",
    itineraries: "行程",
    stories: "游记",
    about: "关于艾哈迈德",
    menu: "菜单",
    language: "语言",
  },
  hero: {
    eyebrow: "巴林 • 世界",
    title: "从巴林走向世界",
    sub: "艾哈迈德的旅程，探索世界各地的国家、城市与文化。",
    cta1: "开始探索",
    cta2: "关于艾哈迈德",
  },
  sections: {
    aboutAhmad: "关于艾哈迈德",
    ahmadIntro:
      "艾哈迈德·阿卜杜勒拉赫曼来自巴林王国。十多年前，他带着一个简单的目标开始旅行：走访一百个以上的国家。如今他记录所见所闻，让更多人受益，并在每一次旅程中架起友爱与共处的桥梁。",
    introTitle: "始于热爱的故事",
    introCta: "关于艾哈迈德",
    continentsLabel: "各大洲",
    byContinent: "按大洲探索世界",
    destinations: "目的地",
    viewAll: "查看所有目的地",
    countries: "艾哈迈德到访过的国家",
    countriesAll: "查看所有国家",
    countriesLine: "多年旅行中记录的 {count} 个国家。",
    countriesWord: "个国家",
    featured: "精选游记",
    readStory: "阅读游记",
    searchPlaceholder: "搜索国家",
    noResults: "没有结果",
    citiesLabel: "城市",
    cities: "艾哈迈德到访过的城市",
    otherCities: "其他城市",
    attractions: "值得一看的地方",
    highlights: "亮点推荐",
    culture: "文化与笔记",
    relatedItineraries: "相关行程",
    discover: "探索旅程",
    explore: "探索",
    read: "阅读",
    introduction: "简介",
    sectionsLabel: "栏目",
    moreSections: "更多栏目",
    keepScrolling: "继续向下滚动",
    world: "世界",
    back: "返回",
    backTo: "返回{name}",
    days: "天",
    day: "第 {n} 天",
  },
  labels: {
    capital: "首都",
    currency: "货币",
    population: "人口",
    area: "面积",
    religion: "宗教",
    founded: "成立",
    close: "关闭",
    previous: "上一张",
    next: "下一张",
    openImage: "查看图片",
    loading: "加载中…",
  },
  countriesPage: {
    title: "艾哈迈德到访过的国家",
    sub: "一百多个国家，多年间的真实记录。",
    all: "全部国家",
  },
  about: {
    title: "艾哈迈德·阿卜杜勒拉赫曼",
    sub: "来自巴林王国 — 友爱使者项目的创办人。",
    p1: "我是来自巴林王国的艾哈迈德·阿卜杜勒拉赫曼·穆罕默德。十多年前，我带着一个明确的目标开始旅行：走访一百个以上的国家。感谢真主，我最近实现了这个目标。",
    p2: "如今我在各个平台记录自己的旅程，希望对他人有所帮助，也希望我们能共同建立以和平与共处为基础的友爱关系。欢迎随时与我交流任何旅行相关的问题。",
    quote: "「若无旅行的开阔，生活将何其狭窄」",
  },
  footer: {
    rights: "版权所有",
    desc: "一份个人旅行档案，记录艾哈迈德从巴林出发、走访全球一百多个国家的旅程。",
    social: "社交媒体",
    line: "巴林 ⟶ 世界",
  },
  weather: {
    eyebrow: "气候指南",
    title: "全年天气",
    sub: "阿联酋每月的平均气温与降雨量。",
    high: "最高",
    low: "最低",
    rain: "降雨",
    notes: {
      mildSunny: "温和晴朗",
      pleasant: "舒适宜人",
      warm: "温暖",
      warmToHot: "温暖偏热",
      hotDry: "炎热干燥",
      veryHot: "酷热",
      hotHumid: "炎热潮湿",
      hot: "炎热",
      mild: "温和",
    },
    legend: { mild: "温和", warm: "温暖", hot: "炎热", veryHot: "酷热" },
  },
  anthem: { label: "国歌", play: "播放", pause: "暂停" },
  france: {
    name: "法国",
    introBadge: "★ 简介",
    aboutLabel: "00 · 概况",
    about:
      "法国是西欧的一个立宪共和国，格言为自由、平等、博爱。这个古老的国家形成于中世纪，在19世纪和20世纪达到鼎盛，1950年拥有世界第二大殖民帝国。法国是欧盟创始成员国，也是联合国安理会常任理事国。",
    factLabel1: "01 · 小知识",
    factLabel2: "02 · 小知识",
    watchLabel: "03 · 观看",
    emblemLabel: "国徽",
    emblemTitle: "法兰西共和国国徽",
    geoLabel: "地理位置",
    geoTitle: "地图上的法国 · 首都巴黎",
    glimpse: "法国一瞥",
    anthemTitle: "马赛曲",
    moreAbout: "更多关于法国",
    euro: "欧元 (€)",
    population: "6710 万",
    area: "674,843 平方公里",
    religion: "基督教",
    founded: "1958 年",
  },
  assistant: {
    button: "咨询旅行助手",
    title: "AI 旅行助手",
    subtitle: "友爱使者档案 + 可靠资料",
    welcome:
      "你好。我可以结合友爱使者的旅行档案和可靠的网络资料，回答你关于旅行、国家、城市、文化、景点和行程规划的问题。",
    placeholder: "输入你的旅行问题…",
    error: "出错了，请再试一次。",
    close: "关闭",
    suggestions: [
      "在法国有哪些必去的地方？",
      "比较一下日本和韩国",
      "什么时候去瑞士最好？",
      "摩洛哥的文化是怎样的？",
      "帮我规划法国 7 天行程",
      "艾哈迈德介绍过法国的哪些城市？",
    ],
  },
  errors: {
    notFoundTitle: "页面未找到",
    notFoundBody: "你要找的页面不存在或已被移动。",
    goHome: "返回首页",
    errorTitle: "页面加载失败",
    errorBody: "出了一点问题。可以刷新页面或返回首页。",
    tryAgain: "重试",
  },
  seo: {
    homeTitle: "友爱使者 — 艾哈迈德的环球旅程",
    homeDesc: "艾哈迈德·阿卜杜勒拉赫曼的旅行档案：从巴林走向世界的大洲、国家、城市、游记与行程。",
    countriesTitle: "国家 — 友爱使者",
    countriesDesc: "浏览艾哈迈德·阿卜杜勒拉赫曼走访过的所有国家。",
    aboutTitle: "关于艾哈迈德 — 友爱使者",
    aboutDesc: "来自巴林的艾哈迈德·阿卜杜勒拉赫曼，以及他走访一百多个国家的故事。",
  },
};